<script>
    $(document).ready(function () {

        $('#codigoBarras').change(function () {
            var codBarras = $('#codigoBarras').val();
            if (codBarras !== null && codBarras !== '') {
                $.ajax({
                    url: '/mobile/enderecamento/dados-embalagem/codigoBarras/' + codBarras,
                    success: function (data) {
                        if (data.status === 'ok') {
                            var dsc = data.result.descricao;
                            var endereco = data.result.endereco;
                            if (endereco || $.trim(endereco) !== "") {
                                dsc += ' - ' + data.result.endereco;
                                $('#endereco').val(data.result.endereco);
                            } else {
                                dsc += ' - Sem picking';
                            }

                            $('#descricao').html(dsc);
                            $('#capacidade').val(data.result.capacidade);
                            $('#isEmbalagem').val(data.result.isEmbalagem);

                            if (data.result['isEmbalagem'] === true) {
                                $('#embalado').val(data.result.embalado);
                                $('#divEmb').show()
                            } else {
                                $('#divEmb').hide();
                            }
                        } else {
                            $('#descricao').html("Erro: " + data.msg);
                        }
                    }
                });
            }
        });
    });

    function nextInput(event) {
        if (event.which == 13 || event.keyCode == 13) {
            if (document.getElementById('codigoBarras').value != "") {
                endereco = document.getElementById('endereco');
                if (endereco) {
                    endereco.focus();
                    if (event.preventDefault) {
                        event.preventDefault();
                    } else {
                        event.returnValue = false;
                    }
                }
            }
            if (document.getElementById('codigoBarras').value == "") {
                endereco = document.getElementById('codigoBarras');
                if (codigoBarras) {
                    codigoBarras.focus();
                    if (event.preventDefault) {
                        event.preventDefault();
                    } else {
                        event.returnValue = false;
                    }
                }
            }
        }
        return true;
    }

    function nextInputEndereco(event) {
        if (event.which == 13 || event.keyCode == 13) {
            if (document.getElementById('endereco').value == "") {
                endereco = document.getElementById('endereco');
                if (endereco) {
                    endereco.focus();
                    if (event.preventDefault) {
                        event.preventDefault();
                    } else {
                        event.returnValue = false;
                    }
                }
            } else if (document.getElementById('endereco').value != "") {
                capacidade = document.getElementById('capacidade');
                if (capacidade) {
                    capacidade.focus();
                    if (event.preventDefault) {
                        event.preventDefault();
                    } else {
                        event.returnValue = false;
                    }
                }

            }
        }
        return true;
    }

    function nextInputCapacidade(event) {
        if (event.which == 13 || event.keyCode == 13) {
            if (document.getElementById('capacidade').value != "") {
                endereco = document.getElementById('lastro');
                if (endereco) {
                    endereco.focus();
                    if (event.preventDefault) {
                        event.preventDefault();
                    } else {
                        event.returnValue = false;
                    }
                }
            }
            if (document.getElementById('capacidade').value == "") {
                endereco = document.getElementById('capacidade');
                if (codigoBarras) {
                    codigoBarras.focus();
                    if (event.preventDefault) {
                        event.preventDefault();
                    } else {
                        event.returnValue = false;
                    }
                }
            }
        }
        return true;
    }

    function nextInputLastro(event) {
        if (event.which == 13 || event.keyCode == 13) {
            if (document.getElementById('lastro').value != "") {
                endereco = document.getElementById('camada');
                if (endereco) {
                    endereco.focus();
                    if (event.preventDefault) {
                        event.preventDefault();
                    } else {
                        event.returnValue = false;
                    }
                }
            }
            if (document.getElementById('lastro').value == "") {
                endereco = document.getElementById('capacidade');
                if (codigoBarras) {
                    codigoBarras.focus();
                    if (event.preventDefault) {
                        event.preventDefault();
                    } else {
                        event.returnValue = false;
                    }
                }
            }
        }
        return true;
    }



</script>
<div class="row">
    <form id="formulario" enctype="application/x-www-form-urlencoded" accept-charset="UTF-8" action="<?php echo $this->url(array('controller' => 'enderecamento', 'action' => 'cadastro-produto-endereco')) ?>" method="post">

        <div id="descricao"></div>
        <div>
            <label>Produto:</label>
            <input class="focus" type="text" name="codigoBarras" id="codigoBarras" required onkeydown="nextInput(event)" />
            <input type="hidden" name="isEmbalagem" id="isEmbalagem" />
        </div>

        <div class="row">
            <label>End:</label>
            <input type="text" name="endereco" id="endereco" class="valid" required onkeydown="nextInputEndereco(event)" />
        </div>
        <div class="row">
            <label>Cap:</label>
            <input type="text"  name="capacidade" id="capacidade" required size=6 maxlength=5 value="" onkeydown="nextInputCapacidade(event)" />
        </div>
        <div class="row">
            <label>Lastro:</label>
            <input type="text" name="lastro" id="lastro" size=6 maxlength=5 value="" onkeydown="nextInputLastro(event)" />
        </div>
        <div class="row">
            <label>Camada:</label>
            <input type="text" name="camada" id="camada" size=6 maxlength=5 value="" />
        </div>

        <div id="divEmb" style="display: none">
            <label>Emb:</label>
            <input type="text"  name="embalado" id="embalado" size=1 maxlength=1 value="" />
        </div>
        <div class="row">
            <label>Unitizador:</label>
            <select name="unitizador" id="unitizador" >
                <?php foreach ($this->unitizadores as $unitizador) : ?>
                    <option value="<?php echo $unitizador['id'] ?>"><?php echo $unitizador['descricao'] ?></option>
                <?php endforeach; ?>
            </select>
        </div>
        <br>
        <div class="row">
            <input type="submit" class="btn gradientBtn" name="submit" id="submit" value="Cadastrar" />
        </div>
    </form>
</div>