<script>
    $(document).ready(function () {

        $('#codigoBarras').change(function () {
            var codBarras = $('#codigoBarras').val();
            if (codBarras !== null && codBarras !== '') {
                $.ajax({
                    url: '/mobile/enderecamento/dados-embalagem/codigoBarras/' + codBarras,
                    success: function (data) {
                        if (data.status === 'ok') {
                            var dsc = data.result.descricao;
                            var endereco = data.result.endereco;
                            if (endereco || $.trim(endereco) !== "") {
                                dsc += ' - ' + data.result.endereco;
                                $('#endereco').val(data.result.endereco);
                            } else {
                                dsc += ' - Sem picking';
                            }

                            $('#descricao').html(dsc);
                            $('#capacidade').val(data.result.capacidade);
                            $('#isEmbalagem').val(data.result.isEmbalagem);

                            if (data.result['isEmbalagem'] === true) {
                                $('#embalado').val(data.result.embalado);
                                $('#divEmb').show()
                            } else {
                                $('#divEmb').hide();
                            }
                        } else {
                            $('#descricao').html("Erro: " + data.msg);
                        }
                    }
                });
            }
        });
    });

    function nextInput(event) {
        if (event.which == 13 || event.keyCode == 13) {
            if (document.getElementById('codigoBarras').value != "") {
                endereco = document.getElementById('endereco');
                if (endereco) {
                    endereco.focus();
                    if (event.preventDefault) {
                        event.preventDefault();
                    } else {
                        event.returnValue = false;
                    }
                }
            }
            if (document.getElementById('codigoBarras').value == "") {
                endereco = document.getElementById('codigoBarras');
                if (codigoBarras) {
                    codigoBarras.focus();
                    if (event.preventDefault) {
                        event.preventDefault();
                    } else {
                        event.returnValue = false;
                    }
                }
            }
            if (document.getElementById('endereco').value == "") {
                endereco = document.getElementById('endereco');
                if (endereco) {
                    endereco.focus();
                    if (event.preventDefault) {
                        event.preventDefault();
                    } else {
                        event.returnValue = false;
                    }
                }
            }
            if (document.getElementById('endereco').value != "") {
                capacidade = document.getElementById('capacidade');
                if (capacidade) {
                    capacidade.focus();
                    if (event.preventDefault) {
                        event.preventDefault();
                    } else {
                        event.returnValue = false;
                    }
                }
            }
        }
    }

    function nextInputEndereco(event) {
        if (event.which == 13 || event.keyCode == 13) {
            if (document.getElementById('endereco').value == "") {
                endereco = document.getElementById('endereco');
                if (endereco) {
                    endereco.focus();
                    if (event.preventDefault) {
                        event.preventDefault();
                    } else {
                        event.returnValue = false;
                    }
                }
            } else if (document.getElementById('endereco').value != "") {
                capacidade = document.getElementById('capacidade');
                if (capacidade) {
                    capacidade.focus();
                    if (event.preventDefault) {
                        event.preventDefault();
                    } else {
                        event.returnValue = false;
                    }
                }

            }
        }
        return true;
    }

</script>
<div class="col-xs-12">
    <form id="formulario" enctype="application/x-www-form-urlencoded" accept-charset="UTF-8" action="<?php echo $this->url(array('controller' => 'enderecamento', 'action' => 'cadastro-produto-endereco')) ?>" method="post">

        <div id="descricao"></div>
        <div>
            <label>Produto:</label>
            <input class="focus form-control" type="text" name="codigoBarras" id="codigoBarras" required onkeydown="nextInput(event)" />
            <input type="hidden" name="isEmbalagem" id="isEmbalagem" />
        </div>

        <div>
            <label>End: -------------------- Cap:</label>
            <input type="text" name="endereco" id="endereco" class="valid form-control" required onkeydown="nextInputEndereco(event)" />
            <br>
                <input type="text"  name="capacidade" id="capacidade" required size=6 maxlength=5 value="" />
            <br>
            <br>
        </div>

        <div id="divEmb" style="display: none">
            <label>Emb:</label>
            <input type="text" class="form-control" name="embalado" id="embalado" size=1 maxlength=1 value="" />
        </div>
        <div class="col-xs-12">
            <input type="submit" class="btn gradientBtn" name="submit" id="submit" value="Cadastrar" />
        </div>
    </form>
</div>