<script>
    $(document).ready(function(){

        $('#codigoBarras').change(function () {
            var codBarras = $('#codigoBarras').val();
            $.ajax({
                url:  '/mobile/enderecamento/dados-embalagem/codigoBarras/'+codBarras,
                success: function(data) {
                    if (data.status === 'ok'){
                        $('#isEmbalagem').val(data.result['isEmbalagem']);
                        if (data.result['isEmbalagem'] === true) {
                            $('#descricao').html(data['descricao']+' - '+data['endereco']);
                            $('#capacidade').val(data['capacidade']);
                            $('#embalado').val(data['embalado']).show();
                        } else {
                            $('#descricao').html(data['descricao']+' - '+data['endereco']);
                            $('#capacidade').val(data['capacidade']);
                            $('#embalado').enable(false).hide();
                        }
                    } else {
                        $('#descricao').html("Erro: " + data.msg);
                    }

                }
            });
        });
    });

    function nextInput(event) {
        if (event.which == 13 || event.keyCode == 13) {
            if (document.getElementById('codigoBarras').value != "") {
                endereco = document.getElementById('endereco');
                if (endereco) {
                    endereco.focus();
                    if (event.preventDefault) {
                        event.preventDefault();
                    } else {
                        event.returnValue = false;
                    }
                }
            }
            if (document.getElementById('codigoBarras').value == "") {
                endereco = document.getElementById('codigoBarras');
                if (codigoBarras) {
                    codigoBarras.focus();
                    if (event.preventDefault) {
                        event.preventDefault();
                    } else {
                        event.returnValue = false;
                    }
                }
            }
            if (document.getElementById('endereco').value == "") {
                endereco   = document.getElementById('endereco');
                if (endereco) {
                    endereco.focus();
                    if(event.preventDefault) {
                        event.preventDefault();
                    } else {
                        event.returnValue = false;
                    }
                }
            }
            if (document.getElementById('endereco').value != "") {
                capacidade   = document.getElementById('capacidade');
                if (capacidade) {
                    capacidade.focus();
                    if(event.preventDefault) {
                        event.preventDefault();
                    } else {
                        event.returnValue = false;
                    }
                }
            }
        }
    }

    function nextInputEndereco(event) {
        if (event.which == 13 || event.keyCode == 13) {
            if (document.getElementById('endereco').value == "") {
                endereco   = document.getElementById('endereco');
                if (endereco) {
                    endereco.focus();
                    if(event.preventDefault) {
                        event.preventDefault();
                    } else {
                        event.returnValue = false;
                    }
                }
            } else if (document.getElementById('endereco').value != "") {
                capacidade   = document.getElementById('capacidade');
                if (capacidade) {
                    capacidade.focus();
                    if(event.preventDefault) {
                        event.preventDefault();
                    } else {
                        event.returnValue = false;
                    }
                }

            }
        }
        return true;
    }

</script>
<form id="formulario" enctype="application/x-www-form-urlencoded" accept-charset="UTF-8" action="<?php echo $this->url(array('controller' => 'enderecamento', 'action' => 'cadastro-produto-endereco')) ?>" method="post">

    <div id="descricao"></div>
    <div>
        <label>Produto:</label>
        <input class="focus" type="text" name="codigoBarras" id="codigoBarras" onkeydown="nextInput(event)" />
        <input type="hidden" name="isEmbalagem" id="isEmbalagem" />
    </div>

    <div>
        <label>End: -------------------- Cap:</label>
        <input type="text" name="endereco" id="endereco" class="valid" onkeydown="nextInputEndereco(event)" />
        <input type="text" name="capacidade" id="capacidade" size=6 maxlength=5 value="" />
    </div>

    <div>
        <label>Emb:</label>
        <input type="text" style="display: none" name="embalado" id="embalado" size=1 maxlength=1 value="" />
    </div>

    <input type="submit" name="submit" id="submit" value="Cadastrar" />
</form>
