<form class="saveForm">
    <div>
        <span style="font-size: 14pt; font-weight: bolder" class="left">Paletes</span>
        <button type="button" name="imprimir" class="btn gradientBtn" style="margin-top: 0pt; margin-bottom: 4pt; width:auto; ">Endereçar</button>
    </div>
    <div>
        <button name="trocarNorma" class="btn gradientBtn" style="width:auto; margin-top: 0pt; margin-bottom: 4pt" >Recalcular</button>
        <button name="imprimir" class="btn gradientBtn" style="margin-top: 0pt; margin-bottom: 4pt; width:auto; ">Imprimir</button>
    </div>

    <div id="quantidade-grid" class="grid">
        <table style="width: 100%">
            <tbody>
                <table style="width: 100%">
                    <tr>
                        <td colspan="3"><b><?php echo $this->paletes[0]['produto'] ?></b></td>
                    </tr>
                    <?php
                    foreach ($this->paletes as $key => $palete):
                        $fontColor = "black";
                        $liberado = true;
                        if (!empty($palete['motivoNaoLiberar'])) {
                            $fontColor = "gray";
                            $liberado = false;
                        }?>
                        <tr <?php if (!($this->color)) {echo 'style="background-color: #EDEDED"';}?>>
                            <td> <input name="palete[]" value="<?php echo $palete['uma'] ?>" type="checkbox" checked="<?php echo $liberado?>"/>
                            <?php echo "<b>UMA:</b> " . $palete['uma'] ?>
                            </td>

                            <td style="padding-bottom: 3pt;padding-top: 3pt">
                                <table style="width: 100%">
                                    <tr>
                                        <input type="hidden" name="<?php echo 'endereco[' . $palete['uma'] . ']'?>" value="<?php echo $palete['idEndereco'] ?>">
                                    </tr>
                                    <tr>

                                        <td colspan="3"> <b></b><?php if ($palete['motivoNaoLiberar'] == '') {echo $palete['endereco'];} else { echo $palete['motivoNaoLiberar'];} ?></td>
                                        <td><?php echo "<b>Qtd:<b> " . $palete['qtd']  ?></td>
                                    </tr>
                                </table>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </table>
            </tbody>
        </table>
    </div>

</form>
