<form id="formulario" enctype="application/x-www-form-urlencoded" accept-charset="UTF-8" action="<?php echo $this->url(array('controller' => 'enderecamento', 'action' => 'endereco-destino')) ?>" method="post">
    <input type="hidden" name="enderecoSaida" id="enderecoSaida" value="<?php echo $this->codigoBarras ?>">
    <div>
        <b><label style="font-size:17px">Produto:</label></b>
        <input class="focus" type="text" name="etiquetaProduto" id="etiquetaProduto" value="" />
    </div>
    <br>
    <div>
        <table class="gTable ">
            <tbody>
            <tr>
                <td>Rua: <?php echo $this->rua?></td>
                <td>&nbsp;</td><td>&nbsp;</td>
                <td>Prédio: <?php echo $this->predio?></td>
            </tr>
            <tr>
                <td>Nível: <?php echo $this->nivel?></td>
                <td>&nbsp;</td><td>&nbsp;</td>
                <td>Apartamento: <?php echo $this->apartamento?></td>
            </tr>
            </tbody>
        </table>
    </div>
    <br>
    <div>
        <input type="submit" name="submit" id="submit" value="Buscar" />
    </div>
    <a class="finalizar" href="<?php echo $this->url(array('controller' => 'enderecamento', 'action' => 'endereco-uma', 'cb' => $this->cb, 'end' => $this->end, 'nivelAntigo' => $this->nivel)); ?>">Alternar para U.M.A.</a>
</form>

<div class = "gPager">
