<script>
    function nextInput(event, id) {
        if (event.which == 13 || event.keyCode == 13) {
            if (document.getElementById('uma').value != "") {
                endereco   = document.getElementById('endereco');
                if (endereco) {
                    endereco.focus();
                    if(event.preventDefault) {
                        event.preventDefault();
                    } else {
                        event.returnValue = false;
                    }
                }
            }
        }
        return true;
    }

    function nextInputCapacidade() {

        var rua         = document.getElementById('rua-nivel').value;
        var predio      = document.getElementById('predio-nivel').value;
        var apartamento = document.getElementById('apartamento-nivel').value;
        var nivel       = document.getElementById('nivel').value;
        var capacidadePicking = '';
        var countNivel = nivel.length;

        if (countNivel < 2) {
            nivel = '0'+nivel;
        }

        $.ajax({
            url: 'get-capacidade-picking-ajax/endereco/'+rua+'.'+predio+'.'+nivel+'.'+apartamento,
            success: function (data) {
                if (data.status == 'Ok') {
                    if (data.caracteristicaEndereco == 39 || data.caracteristicaEndereco == 37) {
                        capacidadePicking += '<div><label>CAPAC. PICKING:</label><input type="text" style="width: 40px" size="40" value="' + data.capacidadePicking + '" id="capacidadePicking" name="capacidadePicking"></div>';
                    }
                    $('#capacidade').html(capacidadePicking);
                } else {
                    $('#capacidade').html('');
                }
            }
        });
    }

    function formSubmit(event)
    {
        uma = document.getElementById('uma');
        endereco   = document.getElementById('endereco');

        if (uma.value !== "" && endereco.value !== "") {
            loadResult(uma, endereco);
        }

        if(event.preventDefault) {
            event.preventDefault();
        } else {
            event.returnValue = false;
        }

    }

    function formSubmitNivel(event)
    {
        nivel = document.getElementById('nivel');
        if (nivel.value !== "") {
            loadResultNivel(nivel);
        }

        if(event.preventDefault) {
            event.preventDefault();
        } else {
            event.returnValue = false;
        }
    }

    function loadResultNivel(nivel)
    {
        nivel.disabled = true;
        document.getElementById('retorno').innerHTML = 'Pesquisando...';
        load(document.getElementById('formulario-nivel').action, 'formulario-nivel', function(xhr){
            document.getElementById('retorno').innerHTML = '';
            nivel.disabled = false;
            nivel.value = "";
            nivel.focus();

            xmlDoc=xhr.responseXML;

            x=xmlDoc.getElementsByTagName("retorno");
            i=0;

            exibeMensagem(x,i);

            if (x[i].getElementsByTagName("resposta").length > 0) {
                status=(x[i].getElementsByTagName("resposta")[0].childNodes[0].nodeValue);
                if (status == 'success' || status == 'error') {
                    voltarUma();
                }
            }

        });
    }

    function loadResult(uma, endereco)
    {
        uma.disabled = true;
        endereco.disabled = true;

        document.getElementById('retorno').innerHTML = 'Pesquisando...';
        load(document.getElementById('formulario').action, 'formulario', function(xhr){

            document.getElementById('retorno').innerHTML = '';

            uma.disabled = false;
            uma.value = "";
            uma.focus();
            endereco.disabled = false;
            endereco.value = "";

            xmlDoc=xhr.responseXML;

            x=xmlDoc.getElementsByTagName("retorno");
            i=0;

            exibeMensagem(x,i);

            if (x[i].getElementsByTagName("nivelzero").length > 0) {
                hiddenElement("formulario");
                showElement("formulario-nivel");
                document.getElementById('nivel').focus();
                document.getElementById('uma-nivel').value = x[i].getElementsByTagName("uma")[0].childNodes[0].nodeValue;
                document.getElementById('rua-nivel').value = x[i].getElementsByTagName("rua")[0].childNodes[0].nodeValue;
                document.getElementById('predio-nivel').value = x[i].getElementsByTagName("predio")[0].childNodes[0].nodeValue;
                document.getElementById('apartamento-nivel').value = x[i].getElementsByTagName("apartamento")[0].childNodes[0].nodeValue;
            }

        });
    }

    function exibeMensagem(x,i)
    {
        if (x[i].getElementsByTagName("message").length > 0) {
            message=(x[i].getElementsByTagName("message")[0].childNodes[0].nodeValue);
            document.getElementById("retorno").innerHTML=message;
        }

        if (x[i].getElementsByTagName("resposta").length > 0) {
            status=(x[i].getElementsByTagName("resposta")[0].childNodes[0].nodeValue);
            if (status == 'error') {
                playSound('/alarme.mp3');
            }
        }

        if (x[i].getElementsByTagName("redirect").length > 0) {
            uma.disabled = true;
            redirect=(x[i].getElementsByTagName("redirect")[0].childNodes[0].nodeValue);
            setTimeout("location.href = redirect;",0);
        }

    }

    function voltarUma()
    {
        hiddenElement("formulario-nivel");
        showElement("formulario");
        document.getElementById('uma').focus();
    }

</script>

<?php $this->headScript()->appendFile($this->baseUrl('coletor/enderecamento.js')); ?>

<div id='retorno'></div>
<span id="dummy"></span>

<form id="formulario" enctype="application/x-www-form-urlencoded" accept-charset="UTF-8" action="<?php echo $this->url(array('controller' => 'enderecamento', 'action' => 'buscar')) ?>" onSubmit="formSubmit(event)" method="post">

    <div>
        <label>U.M.A:</label>
        <input type="text" name="uma" id="uma" value="" onkeydown="nextInput(event)" />
    </div>
    <div>
        <label>ENDEREÇO:</label>
        <input type="text" name="endereco" id="endereco" value="" />
    </div>

        <input type="submit" name="submit" id="submit" value="Buscar" />
</form>

<form id="formulario-nivel" action="<?php echo $this->url(array('controller' => 'enderecamento', 'action' => 'valida-nivel')) ?>" onSubmit="formSubmitNivel(event)" method="post">

    <div>
        <label>NÍVEL:</label>
        <input type="text" style="width: 40px" size="40" value="" id="nivel" name="nivel" onkeyup="nextInputCapacidade() ">
        <input type="hidden" value="" id="uma-nivel" name="uma">
        <input type="hidden" value="" id="rua-nivel" name="rua">
        <input type="hidden" value="" id="predio-nivel" name="predio">
        <input type="hidden" value="" id="apartamento-nivel" name="apartamento">
    </div>
    <div id="capacidade"></div>
    <input type="submit" name="submit" id="submit" value="Buscar" />
    <input type="button" name="voltar" id="voltar" value="Voltar" onclick="voltarUma()" />
</form>

