<form class="saveForm">
    <div>
        <span style="font-size: 14pt; font-weight: bolder" class="left">Paletes</span>
        <button type="button" name="imprimir" class="btn gradientBtn" style="margin-top: 0pt; margin-bottom: 4pt; width:auto; ">Endereçar</button>
    </div>
    <div>
        <button name="trocarNorma" class="btn gradientBtn" style="width:auto; margin-top: 0pt; margin-bottom: 4pt" >Recalcular</button>
        <button name="imprimir" class="btn gradientBtn" style="margin-top: 0pt; margin-bottom: 4pt; width:auto; ">Imprimir</button>
    </div>
    <div id="quantidade-grid" class="grid">
        <div style="text-align: start">
            <label><input type="checkbox" id="check_all" checked style="height: auto !important; margin: 5px">Todos</label>
        </div>
        <table style="width: 100%">
            <tbody>
            <?php
            if(is_array($this->paletes)){
                foreach ($this->paletes as $palete): ?>
                    <tr <?php if (!($this->color)) {echo 'style="background-color: #EDEDED"';}?>>
                        <td><input class="umas" name="palete[]" value="<?php echo $palete['ALL_UMA'] ?>" type="checkbox" checked/></td>
                        <td style="padding-bottom: 3pt;padding-top: 3pt">
                            <table style="width: 100%">
                                <tr>
                                    <td colspan="3">
                                        <b><?php echo $palete['DSC_PRODUTO'] ?></b>
                                    </td>
                                </tr>
                                <tr>
                                    <td><?php echo $palete['QTD_UMA'] . " x " . $palete['DSC_UNITIZADOR'] ?></td>
                                    <td><?php echo "<b>Qtd:<b> " . $palete['QTD']  ?></td>
                                    <td><a href="<?php echo $this->url(array('module' => 'mobile', 'controller' => 'enderecamento', 'action' => 'detalhe-endereco', 'produto' => $palete['COD_PRODUTO'], 'grade' => $palete['DSC_GRADE'])) ?>"> <input class="btn" type="button" value="Mais"></a></td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                <?php 
                endforeach; 
            }?>
            </tbody>
        </table>
    </div>
</form>
<script>
    $("#check_all").change(function () {
        var toggleTo = $(this).attr('checked');
        $(".umas").each(function (_,inpt) {
            inpt.checked = toggleTo;
        })
    });
</script>