<form id="form-transferencia" enctype="application/x-www-form-urlencoded" accept-charset="UTF-8" action="" method="post">
    <div>
        <label>U.M.A:</label>
        <input type="text" name="uma" id="uma" value="" />
    </div>
    <div>
        <label>NOVO ENDEREÇO:</label>
        <input type="text" name="endereco" id="endereco" value="" />
    </div>

    <input type="submit" name="submit" id="submit" class="btn" value="Alterar" />
</form>