<?php
/**
 * Created by PhpStorm.
 * User: Tarcísio César
 * Date: 14/12/2018
 * Time: 10:51
 */
?>
<style>
    .btn {
        width: 95%;
    }

    .lbl-headers {
        font-size: 15px;
        font-weight: bold;
        padding: 0 6px;
    }

    div.input-area {
        padding: 10px;
        margin: 10px 15px;
        background-color: #f3f3f3;
        border-radius: 10px;
    }

    html, body {
        margin:0;
        height: 100%;
    }

    .btn-spacing {
        margin-top: 5px;
    }

    .list-area {
        overflow-y: auto;
        max-height: inherit
    }

    .list-item {
        width: 100%!important;
        margin: 3px 0px !important;
        padding: 0px !important;
        text-align: center!important;
        font-weight: bold;
    }

    .div-loader {
        float:left;
        z-index: 99999;
        padding-top: 30px;
        position: absolute;
        background: #FFFFFF;
        width: 100%;
        height: inherit;
    }

    .btn-zerarProduto {
        font-family: Arial;
        color: #ffffff;
        font-size: 12px;
        background: #d93434;
        padding: 2px 5px;
        text-decoration: none;
    }

    .btn-zerarProduto:hover {
        background: #781f08;
        background-image: -webkit-linear-gradient(top, #781f08, #9e100b);
        background-image: -moz-linear-gradient(top, #781f08, #9e100b);
        background-image: -ms-linear-gradient(top, #781f08, #9e100b);
        background-image: -o-linear-gradient(top, #781f08, #9e100b);
        background-image: linear-gradient(to bottom, #781f08, #9e100b);
        text-decoration: none;
    }

    .btn-toggle {
        -moz-box-shadow:inset 0px 1px 0px 0px #ffffff;
        -webkit-box-shadow:inset 0px 1px 0px 0px #ffffff;
        box-shadow:inset 0px 1px 0px 0px #ffffff;
        background:-webkit-gradient(linear, left top, left bottom, color-stop(0.05, #ffffff), color-stop(1, #f6f6f6));
        background:-moz-linear-gradient(top, #ffffff 5%, #f6f6f6 100%);
        background:-webkit-linear-gradient(top, #ffffff 5%, #f6f6f6 100%);
        background:-o-linear-gradient(top, #ffffff 5%, #f6f6f6 100%);
        background:-ms-linear-gradient(top, #ffffff 5%, #f6f6f6 100%);
        background:linear-gradient(to bottom, #ffffff 5%, #f6f6f6 100%);
        filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#ffffff', endColorstr='#f6f6f6',GradientType=0);
        background-color:#ffffff;
        -webkit-border-radius:6px;
        -moz-border-radius:6px;
        border-radius:6px;
        border:1px solid #dcdcdc;
        display:inline-block;
        cursor:pointer;
        color:#666666;
        font-size:15px;
        font-weight:bold;
        padding:1px 24px 1px 16px;
        text-decoration:none;
        text-shadow:0px 1px 0px #ffffff;
        width: auto;
    }
    .btn-toggle:hover {
        background:-webkit-gradient(linear, left top, left bottom, color-stop(0.05, #f6f6f6), color-stop(1, #ffffff));
        background:-moz-linear-gradient(top, #f6f6f6 5%, #ffffff 100%);
        background:-webkit-linear-gradient(top, #f6f6f6 5%, #ffffff 100%);
        background:-o-linear-gradient(top, #f6f6f6 5%, #ffffff 100%);
        background:-ms-linear-gradient(top, #f6f6f6 5%, #ffffff 100%);
        background:linear-gradient(to bottom, #f6f6f6 5%, #ffffff 100%);
        filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#f6f6f6', endColorstr='#ffffff',GradientType=0);
        background-color:#f6f6f6;
    }
    .btn-toggle:active {
        position:relative;
        top:1px;
    }

    #arrow-info {
        -moz-transition: transform 350ms;
        -webkit-transition: transform 350ms;
        transition: transform 350ms;
    }

    .flip {
        transform: rotate(-180deg);
    }

</style>

<div id="dummy"></div>
<bgsound id="bgSoundId" loop="0" volume="100" />

<div id="loader" class="div-loader">
    <span style="font-size: 18px">Carregando...</span>
    <img src="/img/ajax-bar-loader.gif" alt="loading">
</div>

<div id="divBtnBack" style="display: none; margin-bottom: 5px">
    <button class="btn gradientBtn btn-spacing" id="btn-back-action">Voltar</button>
</div>

<div id="messenger"></div>
<a href="#messenger" style="display: none" id="anchorMsg"></a>

<div id="headers" style="padding-top: 5px; display: none">
</div>
<div id="btn-row" style="padding-top: 6px; display: none">
    <button id="toggleInfo" class="btn-toggle"><img id="arrow-info" src="/img/icons/bullet_arrow_up.png" width="24" height="24" alt="Arrow direction"><span>Ocultar Info</span></button>
</div>
<div id="header-active" style="padding-top: 5px; display: none">
    <div class="lbl-headers" id="lbl-inventario"></div>
    <div class="lbl-headers" id="lbl-contagem"></div>
    <div class="lbl-headers" id="lbl-endereco"></div>
    <div class="lbl-headers" id="lbl-pickingOf"></div>
    <div class="lbl-headers" id="lbl-produto"></div>
    <div class="lbl-headers" id="lbl-embvol"></div>
    <div class="lbl-headers" id="lbl-picking"></div>
</div>

<div id="list-inventarios" style="display: none;">
    <h3>Inventários disponíveis</h3>
    <p id="list-empty">Nenhum Inventário liberado para conferência.</p>
    <div id="list"></div>
</div>

<div id="contagens-by-inventario" style="display: none">
    <h3>Contagens</h3>
    <div id="list-contagens"></div>
</div>

<div id="bipagem-endereco" style="display: none">
    <div class="input-area">
        <form>
            <div class="field">
                <label for="cod-barras-end" class="field required"><div class="lbl-headers">Buscar Endereço</div></label>
                <input type="text" name="cod-barras-end" id="cod-barras-end" value="" class=" required focus" size="40" maxlength="100" style="width: 99%" alt="numeric">
            </div>
        </form>
        <button id="btn-consultar-endereco" class="btn gradientBtn btn-spacing">Buscar</button>
    </div>
    <div class="list-area" id="list-enderecos"></div>
</div>

<div id="bipagem-produto" style="display: none">
    <div class="input-area">
        <form>
            <div class="field">
                <label for="cod-barras-prod" class="field required"><div class="lbl-headers">Buscar Produto</div></label>
                <input type="text" name="cod-barras-prod" id="cod-barras-prod" value="" class="required focus" size="40" maxlength="100" style="width: 99%" alt="numeric">
            </div>
        </form>
        <button id="btn-consultar-produto" class="btn gradientBtn btn-spacing">Buscar</button><br>
        <button id="btn-finalizar" class="btn btn-spacing gradientBtnSuccess"></button>
    </div>
    <div class="list-area" id="list-produtos"></div>
</div>

<div id="conferencia" style="display: none">
    <div class="input-area">
        <form>
            <div class="field" id="div-lote">
                <label for="lote" class="field optional"><span class="lbl-headers">Lote</span></label>
                <input type="text" name="lote" id="lote" value="" size="10" maxlength="8" placeholder="Ex.: LI001">
            </div>
            <div class="field" id="div-validade">
                <label for="validade" class="field optional"><span class="lbl-headers">Validade</span></label>
                <input type="text" name="validade" id="validade" size="10" maxlength="8" placeholder="dd/mm/aa" alt="date">
            </div>
            <div class="field">
                <label for="qtd" class="field required"><span class="lbl-headers">Quantidade</span></label>
                <input type="text" name="qtd" id="qtd" value="" class="required focus" size="10" maxlength="15">
            </div>
        </form>
        <button id="btn-registrar" class="btn gradientBtn btn-spacing">Registrar</button>
    </div>
</div>

<script>
    $(function () {

        $("#validade").keyup(function () {

            var v = $(this).val();

            v = v.replace(/\D/g, "");
            v = v.replace(/(\d{2})(\d)/, "$1/$2");
            v = v.replace(/(\d{2})(\d)/, "$1/$2");
            v = v.replace(/(\d{2})(\d{2})$/, "$1$2");

            $(this).val(v);
        });

        var desconsideraZeroEsquerda = <?php echo ($this->desconsideraZeroEsquerda) ? "true" : "false"; ?>;
        var inventarios = [];
        var invSelecioando = {};
        var contagens = [];
        var contSelecioando = {};
        var enderecos = [];
        var contEndSelecionado = null;
        var produtos = [];
        var pickingOf = [];
        var elemBipado = {};
        var usaGrade = <?php echo ($this->usaGrade) ? "true" : "false"; ?>;
        var showing = 0;
        var views = ["loader","list-inventarios","contagens-by-inventario","bipagem-endereco","bipagem-produto","conferencia"];
        var headersArr = ["lbl-inventario", "lbl-contagem", "lbl-endereco, #lbl-pickingOf", "lbl-produto, #lbl-embvol, #lbl-picking"];
        var onErrRedirectTo = {4000: "list-inventarios", 4001: "bipagem-endereco", 4002: "bipagem-produto" };
        var endConfig = <?php echo $this->endConfig; ?>;
        var msgShowed = true;

        function myIndexOf(collection, target) {
            var index;
            for(var val in collection){
                if(collection[val] === target){
                    index = val;
                    return index;
                }
            }
            return -1;
        }

        function playSound(soundfile) {
            if (<?php echo $this->isOldBrowserVersion ?> === 'S') {
                document.getElementById("bgSoundId").src = soundfile;
            } else {
                var dummy = '<audio autoplay> <source src=' + soundfile + ' type="audio/mp3">' +
                    '<source src="' + soundfile + '" type="audio/mpeg"></audio>';
                $('#dummy').html(dummy);
            }
        }

        $(document).ready(function () {
            getInventarios();
        });

        var disarmEvent = function (event) {
            if (event.preventDefault) {
                event.preventDefault();
            } else {
                event.returnValue = false;
            }
        };

        var dispareSound = function (type) {
            var songFile = "/alarme_curto.mp3";
            if (type === "success") {
                songFile = "/confirm2.mp3";
            } else if (type === "warning") {
                songFile = "/warning.mp3";
            }

            playSound(songFile);
        };

        var notificar = function (type, msg, instantShowed) {
            if (type === undefined) type = "success";

            $("#messenger").html(
                '<ul class="flashMessenger">' +
                '    <li class="' + type + '_message" id="">' +
                '        <div style="display:block; float:right;">' +
                '            <a href="#" class="fmBtnClose">X</a>' +
                '        </div>' +
                '        <div style="display: block;" id="msg-text">' + msg + '</div>' +
                '    </li>' +
                '</ul>');

            dispareSound(type);

            //if (type === "error") alert(msg);
            msgShowed = instantShowed;
        };

        $(".fmBtnClose").live("click", function () {
            $("#messenger").empty();
        });

        var formatEndereco = function (endereco) {
            var cleared = endereco.slice(0, endereco.length - 1);
            var rua = endConfig.rua.toString();
            var predio = endConfig.predio.toString();
            var nivel = endConfig.nivel.toString();
            var apto = endConfig.apartamento.toString();
            var endArr = cleared.split(".");
            if (endArr.length === 4) {

                rua = (rua + endArr[0].toString()).slice(-rua.length);
                predio = (predio + endArr[1].toString()).slice(-predio.length);
                nivel = (nivel + endArr[2].toString()).slice(-nivel.length);
                apto = (apto + endArr[3].toString()).slice(-apto.length);

            } else if (endArr.length === 1) {
                var maskLength = endConfig.mask.replace(/\D/g,'').length;

                if (cleared.length < maskLength) return false;

                var endTrimned = cleared.slice(cleared.length - maskLength , cleared.length);
                rua = endTrimned.slice(0 , rua.length);
                predio = endTrimned.slice(rua.length , rua.length + predio.length);
                nivel = endTrimned.slice(rua.length + predio.length , rua.length + predio.length + nivel.length);
                apto = endTrimned.slice(rua.length + predio.length + nivel.length , rua.length + predio.length + nivel.length + apto.length);
            } else {
                notificar("error", "Formato de endereço incorreto!", true)
            }

            return [rua,predio,nivel,apto].join(".");
        };

        var changeViewer = function (changeTo) {
            $.each(views, function (k,v) {
                $("#"+v).hide();
            });

            if (changeTo === undefined || myIndexOf(views, changeTo) < 0) {
                changeTo = views[1];
            }

            showing = myIndexOf(views, changeTo);

            $.each(headersArr, function (k,v) {
                var element = $("#" + v);
                if ( k > (showing - 2)) {
                    element.hide();
                } else {
                    element.show();
                }
            });

            var divHeaders = $("#headers");
            var divActiveHeader = $("#header-active");
            if (showing > 1) {
                $("#divBtnBack").show();
                if ((showing - 2) > divHeaders.children("div").length) {
                    divHeaders.append($("#" + headersArr[(showing -3)]));
                } else {
                    divActiveHeader.prepend($("#" + headersArr[(showing -2)]));
                }

                divActiveHeader.show();

                if (showing > 2) {
                    $("#btn-row").show();
                }
                if (divHeaders.children("div").length && !$("#toggleInfo").hasClass('hiddingInfo'))
                    divHeaders.show();
            } else {
                $("#divBtnBack").hide();
                divHeaders.hide();
                divActiveHeader.hide();
                $("#btn-row").hide();
            }

            if (changeTo !== "loader") {
                if (msgShowed) {
                    $("#messenger").empty();
                } else {
                    msgShowed = true;
                }
            }

            $("#"+changeTo).show();

            if (showing > 2) {
                $("#" + changeTo + " div.input-area form div:visible:first input:text").val("").focus();
            }
            if ($("#messenger > ul > li.warning_message, #messenger > ul >li.error_message").length > 0)
                $("#anchorMsg")[0].click();
        };

        $("#btn-back-action").click(function () {
            switch ((showing - 1)) {
                case 1:
                    changeViewer("loader");
                    location.reload();
                    break;
                case 2:
                    getContagens();
                    break;
                case 3:
                    getEnderecos();
                    break;
                case 4:
                    openEndereco();
                    break;
            }
        });

        $("#toggleInfo").click(function () {
            $(this).blur();
            if ($(this).hasClass("hiddingInfo")) {
                $("#headers").show(350);
                $(this).children("span").text("Ocultar Info");
            }
            else {
                $("#headers").hide(350);
                $(this).children("span").text("Exibir Info");
            }
            $(this).toggleClass("hiddingInfo");
            $(this).children("img").toggleClass("flip");
        });

        var prepareListInventarios = function () {
            if (inventarios.length) {
                $("#list-empty").hide();
                $.each(inventarios, function (k, v) {
                    var dsc = "";
                    if (v.descricao === null) {
                        dsc = "Inventário " + v.id;
                    } else {
                        dsc = "Inv. " + v.id + " - " + v.descricao;
                    }
                    inventarios[k].dsc = dsc;
                    var newRow = $('<div class="row"><button class="btn gradientBtn btn-spacing selectInv" data-key="'+k+'" title="'+v.id+'">'+dsc+'</button></div>');
                    $("#list").append(newRow);
                });
                $("#list").show();
            }
            else {
                $("#list-empty").show();
                $("#list").hide();
            }
            changeViewer("list-inventarios")
        };

        var getInventarios = function () {
            changeViewer("loader");
            $("#list").empty();
            $.ajax({url: "/mobile/inventario-novo/get-inventarios",
                success: function(result){
                    if (result.status === "ok") {
                        inventarios = result.response;
                        prepareListInventarios();
                    } else {
                        notificar("error", result.exception);
                        window.location.href = "/mobile"
                    }
                }
            });
        };

        $(".selectInv").live("click",function () {
            invSelecioando = inventarios[$(this).data("key")];
            $("#lbl-inventario").text(invSelecioando.dsc);
            getContagens();
        });

        var controlaValidade = function () {
            return (!isEmpty(invSelecioando.controlaValidade) &&
                invSelecioando.controlaValidade !== 'N' &&
                (!isEmpty(elemBipado.controlaValidade) &&
                    elemBipado.controlaValidade === "S"))
        };

        var controlaLote = function () {
            return (!isEmpty(elemBipado.indControlaLote) &&
                     elemBipado.indControlaLote === "S")
        };

        var getContagens = function () {
            changeViewer("loader");
            $.ajax({url: "/mobile/inventario-novo/get-contagens/id/" + invSelecioando.id,
                success: function(result){
                    if (result.status === "ok") {
                        contagens = result.response;
                        prepareListContagens();
                    } else {
                        notificar("error", result.exception);
                        getInventarios();
                    }
                }
            });
        };

        var prepareListContagens = function () {
            var rowsDivg = [];
            var rowsNor = [];

            $("#list-contagens").empty();

            $.each(contagens, function (k, v) {

                var dsc = v.contagem + "ª Contagem";
                var classe = "gradientBtn";

                if (v.divergencia === 'S'){
                    dsc += " de Divergência";
                    classe = "gradientBtnDanger"
                }
                contagens[k].dsc = dsc;
                var newRow = $('<div class="row"><button class="btn '+ classe +' selectCont" data-key="'+ k +'" title="'+ v.contagem +'">'+ dsc +'</button></div>');

                if (v.divergencia === 'S') {
                    rowsDivg.push(newRow);
                } else {
                    rowsNor.push(newRow)
                }

            });

            $.each($.merge(rowsNor, rowsDivg), function (k,v) {
                $("#list-contagens").append(v);
            });

            changeViewer("contagens-by-inventario");
        };

        $(".selectCont").live("click",function () {
            contSelecioando = contagens[$(this).data("key")];
            $("#lbl-contagem").text(contSelecioando.dsc);
            getEnderecos();
        });

        var getEnderecos = function () {
            changeViewer("loader");
            $.ajax({url: "/mobile/inventario-novo/get-enderecos/id/" + invSelecioando.id + "/sq/" + contSelecioando.sequencia,
                success: function(result){
                    if (result.status === "ok") {
                        enderecos = result.response;
                        prepareListEnderecos()
                    } else {
                        notificar("error", result.exception);
                        if (result.errorCode === 4000) {
                            getInventarios();
                        } else {
                            getContagens();
                        }
                    }
                }
            });
        };

        var prepareListEnderecos = function () {
            var list = $("#list-enderecos");
            list.empty();
            if (!$.isEmptyObject(enderecos)) {
                for (var i in enderecos){
                    list.append('<div class="list-item">' + i + '</div>')
                }
                changeViewer("bipagem-endereco");
            } else {
                notificar("warning", "A " + contSelecioando.dsc + " não tem mais endereços! Selecione outra.");
                getContagens();
            }
        };

        $("#cod-barras-end").keypress(function( event ) {
            if ( event.which === 13  || event.keyCode === 13 ) {
                disarmEvent(event);
                if (!isEmpty($(this).val())) {
                    processEndereco($(this));
                    $(this).val("")
                }
            }
        });

        $("#btn-consultar-endereco").click(function( event ) {
            var input = $("#cod-barras-end");
            disarmEvent(event);
            if (!isEmpty(input.val())) {
                processEndereco(input);
                input.val("")
            }
        });

        var processEndereco = function (input) {

            var endFormated = formatEndereco(input.val());

            if (!endFormated) {
                notificar("warning", "O código de barras não corresponde à um endereço", true);
            } else if ((enderecos[endFormated] !== undefined)) {
                contEndSelecionado = enderecos[endFormated];
                $("#lbl-endereco").text("End. Atual: " + endFormated);
                openEndereco()
            } else {
                notificar("warning", "O endereço "+endFormated+" não está nesta contagem", true);
                input.focus();
            }

            input.val("");
        };

        var openEndereco = function () {
            changeViewer("loader");
            var paramsUrl = ["id", invSelecioando.id, "sq", contSelecioando.sequencia, "divrg", contSelecioando.divergencia, "end", contEndSelecionado.idEnd, "isPicking", contEndSelecionado.isPicking];
            $.ajax({
                url: "/mobile/inventario-novo/get-info-endereco/" + paramsUrl.join("/")  ,
                success: function (result) {
                    produtos = [];
                    pickingOf = [];
                    if (result.status === "ok") {
                        for (var index in result.response.listItens) {
                            produtos.push(result.response.listItens[index]);
                        }
                        pickingOf = result.response.pickingOf;
                        if (contEndSelecionado.isPicking && !isEmpty(pickingOf.itens)) {
                            var strProd = "Picking de:<br>";
                            $.each(pickingOf.itens, function(k, v){
                                strProd = strProd + v.idProduto + " - " + v.dscProduto;
                                if (usaGrade) {
                                    strProd = strProd + " - " + v.grade;
                                }
                                if (k < (pickingOf.itens.length - 1)) {
                                    strProd = strProd + "<br>";
                                }
                            });
                            $("#lbl-pickingOf").html(strProd).show();
                        } else {
                            $("#lbl-pickingOf").hide();
                        }
                        prepareListProdutos();
                    } else {
                        notificar("error", result.exception);
                        if (result.errorCode === 4000) {
                            getInventarios();
                        } else if (result.errorCode === 4001) {
                            getEnderecos();
                        }
                    }
                }
            })
        };

        var prepareListProdutos = function () {
            var list = $("#list-produtos");
            list.empty();
            if (produtos.length) {
                $.each(produtos , function (k,v) {
                    var dscProd = v.idProduto;
                    if (usaGrade) {
                        dscProd += " - " + v.grade;
                    }

                    dscProd += " - " + v.descricao + " - " + "****" + v.codBarras.toString().slice(v.codBarras.toString().length -6);
                    //dscProd += " - " + v.descricao + " - " + v.codBarras;
                    if (!isEmpty(v.lote)) {
                        dscProd += " Lote: " + v.lote;
                    }
                    if (!isEmpty(v.idVolume)) {
                        dscProd += " Volume: " + v.dscVolume;
                    }
                    if(v.zerado) {
                        dscProd += ' <a href="" data-key="' + k + '" class="btn-zerarProduto">Zerar Produto</a>';
                    }

                    list.append('<div class="list-item">' + dscProd + '</div>');
                });
            }

            if (contEndSelecionado.vazio) {
                $("#btn-finalizar").text("Finalizar Endereço Vazio")
            } else {
                $("#btn-finalizar").text("Finalizar Endereço")
            }

            changeViewer("bipagem-produto");
        };

        $(".btn-zerarProduto").live("click", function (event) {
            disarmEvent(event);
            var produto = produtos[$(this).data("key")];
            var descricao = produto.idProduto + " - " + produto.descricao + " " + produto.grade;
            if (!isEmpty(produto.idVol)) {
                descricao += " - " + produto.dscVol;
            }
            if (confirm("Esta ação irá zerar neste endereço o produto " + descricao+ ". Deseja realmente prosseguir?")) {
                confirmarProdutoZerado(produto);
            }
        });

        var confirmarProdutoZerado = function (produto) {
            changeViewer("loader");
            $.post(
                "/mobile/inventario-novo/confirmar-produto-zerado",
                {
                    inventario: invSelecioando,
                    contEnd: contEndSelecionado,
                    produto: produto
                }
            ).done(function( result ) {
                if (result.status === "ok") {
                    notificar("success", result.response);
                    openEndereco();
                } else {
                    notificar("error", result.exception);
                    if (result.errorCode === 4000) {
                        getInventarios();
                    } else if (result.errorCode === 4001) {
                        getEnderecos();
                    } else {
                        openEndereco();
                    }
                }
            })
        };

        $("#cod-barras-prod").keypress(function( event ) {
            if (event.which === 13 || event.keyCode === 13) {
                disarmEvent(event);
                if (!isEmpty($(this).val())) {
                    getInfoProduto($(this).val());
                    $(this).val("");
                }
            }
        });

        $("#btn-consultar-produto").click(function( event ) {
            var input = $("#cod-barras-prod");
            disarmEvent(event);
            if (!isEmpty(input.val())) {
                getInfoProduto(input.val());
                input.val("");
            }
        });

        var getInfoProduto = function (codBarras) {
            changeViewer("loader");
            var paramsUrl = ["codbarras", encodeURIComponent(codBarras), "id", invSelecioando.id, "end", contEndSelecionado.idEnd];
            $.ajax({
                url: "/mobile/inventario-novo/get-info-produto/" + paramsUrl.join("/") ,
                success: function (result) {
                    if (result.status === "ok") {
                        elemBipado = result.response.produto;
                        if (elemBipado.idVolume === null) {
                            elemBipado.idVolume = "";
                        }

                        if (contEndSelecionado.isPicking && myIndexOf(pickingOf.uniKey, elemBipado.idProduto + "--" + elemBipado.grade + "--" + elemBipado.norma) < 0)
                        {
                            notificar("warning", "Este produto não está vinculado à esse picking!");
                        }

                        prepareElement();
                    } else {
                        notificar("error", result.exception);
                        if (result.errorCode === 4000) {
                            getInventarios();
                        } else if (result.errorCode === 4001) {
                            getEnderecos();
                        } else {
                            openEndereco();
                        }
                    }
                }
            })
        };

        var prepareElement = function () {
            $("#lbl-produto").text([
                elemBipado.idProduto,
                elemBipado.descricao,
                ((usaGrade) ? elemBipado.grade : ""),
            ].join(" "));

            $("#lbl-embvol").text( elemBipado.descricaoEmbalagem + ((elemBipado.idEmbalagem !== null) ? "(" + elemBipado.quantidadeEmbalagem + ")" : "" ) );
            $("#lbl-picking").text( "Picking: " + elemBipado.picking);
            $("#qtd").val("");
            $("#lote").val("");
            $("#validade").val("");

            if (controlaLote()) {
                $("#div-lote").show();
            } else {
                $("#div-lote").hide();
            }

            if (controlaValidade()) {
                $("#div-validade").show();
            } else {
                $("#div-validade").hide();
            }

            changeViewer("conferencia");
        };

        $("#qtd, #validade, #lote").keypress(function( event ) {
            if ( event.which === 13  || event.keyCode === 13 ) {
                disarmEvent(event);
                if ( checkInputs(true) ) {
                    registrar();
                }
            }
        });

        $("#btn-registrar").click(function( event ) {
            disarmEvent(event);
            if ( checkInputs() ) {
                registrar();
            }
        });

        var checkInputs = function (toNext) {

            var inputQtd = $("#qtd");
            var inputVal = $("#validade");
            var inputLote = $("#lote");

            if ( controlaValidade()) {
                if (isEmpty(inputVal.val())) {
                    if (!toNext) notificar("warning", "A validade não foi informada", true);
                    inputVal.focus();
                    return false;
                }
                if (!isValidDate(inputVal.val())){
                    notificar("warning", "Esta data " + inputVal.val() + " não é válida" , true);
                    inputVal.focus();
                    return false;
                }
            }

            if ( controlaLote() && isEmpty(inputLote.val())) {
                if (!toNext) notificar("warning", "O Lote não foi informado", true);
                inputLote.focus();
                return false;
            }

            if (isEmpty(inputQtd.val())) {
                if (!toNext) notificar("warning", "A quantidade não foi informada", true);
                inputQtd.focus();
                return false;
            }

            return true;
        };

        $("#qtd").keyup(function () {
            var data = $(this).val().replace(/[^\d.]/,"");
            $(this).val(data);
        });

        function isValidDate(s) {
            var bits = s.split('/');
            var milenium = ((new Date()).getFullYear()).toString().substring(0, 2);
            var d = new Date(milenium +''+ bits[2] + '/' + bits[1] + '/' + bits[0]);
            return !!(d && (d.getMonth() + 1) == bits[1] && d.getDate() == Number(bits[0]));
        }

        var registrar = function () {
            changeViewer("loader");

            var validade = $("#validade").val();
            if (!isEmpty(validade)) {
                var bits = validade.split('/');
                var milenium = ((new Date()).getFullYear()).toString().substring(0, 2);
                validade = bits[0] + '/' + bits[1] + '/' + milenium + '' + bits[2];
            }
            $.post(
                "/mobile/inventario-novo/contagem-produto",
                {
                    inventario: invSelecioando,
                    contEnd: contEndSelecionado,
                    produto: elemBipado,
                    conferencia: {
                        qtd: $("#qtd").val(),
                        validade: validade,
                        lote: $("#lote").val()
                    }
                }
            ).done(function( result ) {
                if (result.status === "ok") {
                    contEndSelecionado.vazio = false;
                    notificar("success", result.response);
                    openEndereco();
                } else {
                    notificar("error", result.exception);
                    if (result.errorCode === 4000) {
                        getInventarios();
                    } else if (result.errorCode === 4001) {
                        getEnderecos();
                    } else {
                        openEndereco();
                    }
                }
            })
        };

        $("#btn-finalizar").click(function () {
            changeViewer("loader");
            $.post(
                "/mobile/inventario-novo/finalizar-contagem-os",
                {
                    inventario: invSelecioando,
                    contEnd: contEndSelecionado
                }
            ).done(function( result ) {
                if (result.status === "ok") {
                    notificar("success", result.response.msg);
                    if (result.response.code !== 5) {
                        getEnderecos();
                    } else if (result.response.code === 5) {
                        getInventarios();
                    }
                } else {
                    notificar("error", result.exception);
                    if (result.errorCode === 4000) {
                        getInventarios();
                    } else if (result.errorCode === 4001) {
                        getEnderecos();
                    } else {
                        openEndereco();
                    }
                }
            })
        });
    })
</script>
