<div id="userInfo">
    <h3>Inventários disponíveis</h3>
    <?php
        if (count($this->inventarios) == 0)
            echo '<p>Nenhum Inventário liberado para conferência.</p>';
        else
        {
            foreach ($this->inventarios as $inventario)
            { ?>
                <div class="row">
                    <a class="btn gradientBtn" href="<?php echo $this->url(array('controller' => 'inventario-novo', 'action' => 'seleciona-contagem', 'idInventario' => $inventario->getId() )); ?>" title="<?php echo $inventario->getId(); ?>" >Inv. <?php echo $inventario->getId(). " - " .$inventario->getDescricao(); ?>  </a>
                </div>
        <?php
            }
        }?>

</div>

