<?php if (count($this->numContagens) > 0) : ?>
    <div id="userInfo" class="row">
        <h4> <?php echo $inventario['id']. " - " .$inventario['descricao']; ?></h4>
        <h3>Contagens</h3>
        <?php foreach ($this->numContagens as $numContagem) : ?>
            <?php if ($numContagem['DIVERGENCIA'] != 1) : ?>
                <div class="row">
                    <a class="btn gradientBtn" href="<?php echo $this->url(array('controller' => 'inventario', 'action' => 'consulta-endereco', 'idInventario' => $this->idInventario, 'numContagem' => $numContagem['CONTAGEM'])); ?>" title="<?php echo $this->idInventario ?>" > <?php echo $numContagem['CONTAGEM'] ?> Contagem</a>
                </div>
            <?php else : ?>
                <div class="row">
                    <a class="btn gradientBtn" href="<?php echo $this->url(array('controller' => 'inventario', 'action' => 'consulta-endereco', 'idInventario' => $this->idInventario, 'numContagem' => $numContagem['CONTAGEM'], 'divergencia' => 1)); ?>" title="<?php echo $this->idInventario ?>" > <?php echo $numContagem['CONTAGEM'] ?> Contagem Divergência</a>
                </div>
            <?php endif; ?>
        <?php endforeach; ?>
    </div>
<?php endif; ?>