INSERT INTO VERSAO (DTH, NUMERO_VERSAO, SCRIPT) VALUES (SYSDATE, '6.8.0','1-estoque-proprietario.sql');

CREATE TABLE ESTOQUE_PROPRIETARIO
(
  COD_ESTOQUE_PROPRIETARIO    NUMBER (8) NOT NULL,
  COD_PRODUTO           VARCHAR2 (20 BYTE)  NOT NULL ,
  DSC_GRADE             VARCHAR2 (10 BYTE)  NOT NULL,
  COD_PESSOA            NUMBER (8) NOT NULL,
  IND_OPERCAO           CHAR(1 BYTE),
  QTD                   NUMBER(13,3),
  DTH_OPERACAO          DATE NOT NULL
);
ALTER TABLE ESTOQUE_PROPRIETARIO ADD CONSTRAINT ESTOQUE_PROPRIETARIO_PK PRIMARY KEY ( COD_ESTOQUE_PROPRIETARIO ) ;

CREATE SEQUENCE SQ_ESTOQUE_PROPRIETARIO
INCREMENT BY 1
START WITH 1
MAXVALUE 999999999999999999999999999
MINVALUE 0
NOCYCLE
NOCACHE
NOORDER;

ALTER TABLE NOTA_FISCAL ADD(
  COD_PESSOA NUMBER (8)
);

ALTER TABLE PEDIDO ADD(
  COD_PESSOA_PROPRIETARIO NUMBER (8)
);

INSERT INTO PARAMETRO (COD_PARAMETRO, COD_CONTEXTO_PARAMETRO, DSC_PARAMETRO, DSC_TITULO_PARAMETRO, IND_PARAMETRO_SISTEMA, COD_TIPO_ATRIBUTO, DSC_VALOR_PARAMETRO)
VALUES (SQ_PARAMETRO_01.NEXTVAL, (SELECT COD_CONTEXTO_PARAMETRO FROM CONTEXTO_PARAMETRO WHERE DSC_CONTEXTO_PARAMETRO = 'PARAMETROS DO SISTEMA'),
'CONTROLE_PROPRIETARIO', 'Controle de Proprietario','N','A','N');