<script>
    $(document).ready(function(){
        $('#todos').live('click',function(){
            var checked_status = this.checked;
            $("input").each(function()
            {
                this.checked = checked_status;
            });
        });
    });
</script>
<form id="enderecamento-form" method="post" class="saveForm" action="">

    <input type="submit" class="btn" value="botao" name="abc">

    <div id="quantidade-grid" class="grid">
        <table class="gTable ">
            <caption>Recebimento <?php echo $this->idRecebimento ?> - <?php echo "Paletes do Produto $this->codProduto - $this->produto / $this->grade"?></caption>
            <p>Endereço de picking:
                <?php if (is_array($this->endPicking)) echo $this->endPicking[0]; ?>
                - Saldo: <?php if (is_array($this->qtdTotal)) echo $this->qtdTotal[0]['QUANTIDADE'].' ('.$this->qtdTotal[0]['QUANTIDADE_TOTAL'].')' ?>
            </p>
            <p><input style="vertical-align: middle" type="checkbox" id="todos"> Selecionar Todos<br></p>
            <tbody>
                <tr class ="gTTitle">
                    <td>Selecione</td>
                    <td>U.M.A.</td>
                    <td>Unitizador</td>
                    <td>Embalagem/Volume</td>
                    <td>Qtd.Unitária</td>
                    <td>Situacao</td>
                    <td>Endereço</td>
                    <td>Impresso</td>
                    <td>Ação</td>
                </tr>
                <?php
                foreach ($this->paletes as $palete):
                    $fontColor = "black";
                    $liberado = true;
                    if ($palete['QTD_VOL_TOTAL'] > $palete['QTD_VOL_CONFERIDO']) {
                        $fontColor = "gray";
                        $liberado = false;
                    }
                    $this->color = !($this->color);?>
                    <tr style="color: <?php echo ($fontColor)?>" class = "<?php if (!$this->color) {echo 'gTResultSet gRowColor';} else {echo 'gTResultSet';}?>">
                        <td><?php if ($liberado == true) {?><input name="palete[]" value="<?php echo $palete['UMA'] ?>" type="checkbox" /> <?php }?></td>
                        <td><?php echo $palete['UMA'] ?></td>
                        <td><?php echo $palete['UNITIZADOR'] ?></td>
                        <td><?php echo $palete['VOLUMES'] ?></td>
                        <td><?php echo $palete['QTD'] ?></td>
                        <td><?php echo $palete['STATUS'] ?></td>
                        <td>
                            <?php if ($palete['ENDERECO'] == NULL) {echo "";} else { echo $palete['ENDERECO'];} ?>
                        </td>
                        <td>
                            <?php if ($palete['IND_IMPRESSO'] == 'S') {echo "SIM";} else { echo "NÃO";} ?>
                        </td>
                        <td><?php if (($palete['COD_SIGLA'] == \Wms\Domain\Entity\Enderecamento\Palete::STATUS_ENDERECADO) ||
                                      ($palete['COD_SIGLA'] == \Wms\Domain\Entity\Enderecamento\Palete::STATUS_EM_ENDERECAMENTO)) {?>
                                <a class="btn reader button" href="<?php echo "/enderecamento/palete/desfazer/id/".$palete['UMA']?>">Retornar Status</a>
                                <?php
                            } else if (($palete['COD_SIGLA'] == \Wms\Domain\Entity\Enderecamento\Palete::STATUS_EM_RECEBIMENTO) ||
                                       ($palete['COD_SIGLA'] == \Wms\Domain\Entity\Enderecamento\Palete::STATUS_RECEBIDO)) {?>
                                <a class="btn reader button" href="<?php echo "/enderecamento/palete/desfazer/id/".$palete['UMA']?>">Excluir</a>
                            <?php }?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        <div class = "gPager">
            <span>
                <?php echo "Total de " . count($this->paletes) . " registros encontrados"?>
            </span>
        </div>
    </div>
</form>
