<?php
/** @var \Wms\Domain\Entity\Integracao\AcaoIntegracao $integracao */
$integracao = $this->integracao;
$conexao = $integracao->getConexao();
?>
<style>
    #show-pass {
        cursor: pointer;
        margin-right: 6px;
    }
</style>
<fieldset>
    <legend>Conexão</legend>
    <table class="detailsPopUp">
        <tr class="title">
            <td>Código:</td>
            <td colspan="2">Descrição:</td>
            <td>Provedor:</td>
            <td colspan="2">Servidor:</td>
            <td>Porta:</td>
            <td>Usuário:</td>
            <td>Senha: <img id="show-pass"src="/img/icons/lock_open.png" alt="show-pass" title="Clique para exibir a senha!"></td>
        </tr>
        <tr>
            <td><?php echo $conexao->getId(); ?></td>
            <td colspan="2"><?php echo $conexao->getDescricao(); ?></td>
            <td ><?php echo $conexao->getProvedor(); ?></td>
            <td colspan="2"><?php echo $conexao->getServidor(); ?></td>
            <td><?php echo $conexao->getPorta(); ?></td>
            <td><?php echo $conexao->getUsuario(); ?></td>
            <td>
                <span id="span-hide-pass">********</span>
                <span id="span-show-pass"></span>
            </td>
        </tr>
    </table>
</fieldset>

<script>
    $("#show-pass").mouseenter(function () {

    })
</script>

<fieldset>
    <legend>Integração</legend>
    <table class="detailsPopUp">
        <tr class="title">
            <td>Código:</td>
            <td colspan="3">Descrição:</td>
            <td>Usa LOG</td>
        </tr>
        <tr>
            <td><?php echo $integracao->getId(); ?></td>
            <td colspan="3"><?php echo $integracao->getDscAcaoIntegracao(); ?></td>
            <td ><?php echo ($integracao->getIndUtilizaLog() == 'S') ? 'Sim' : 'Não'; ?></td>
        </tr>
    </table>
</fieldset>

<!--        <tr>-->
<!--            <td colspan="6" style="height:10px"></td>-->
<!--        </tr>-->
<!---->
<!--        <tr class="title">-->
<!--            <td colspan="3">Classe:</td>-->
<!--            <td colspan="3">Fabricante:</td>-->
<!--        </tr>-->
<!--        <tr>-->
<!--            <td colspan="3">--><?php //echo $produto->getClasse()->getNome(); ?><!--</td>-->
<!--            <td colspan="3">--><?php //echo $produto->getFabricante()->getNome(); ?><!--</td>-->
<!--        </tr>-->
<!---->
<!--        <tr>-->
<!--            <td colspan="6" style="height:10px"></td>-->
<!--        </tr>-->
<!---->
<!--        <tr class="title">-->
<!--            <td colspan="3">Linha de Separação:</td>-->
<!--            <td colspan="3">Tipo Comercialização:</td>-->
<!--        </tr>-->
<!--        <tr>-->
<!--            --><?php //if ($produto->getLinhaSeparacao() == null): ?>
<!--                <td colspan="3">--><?php //echo ''; ?><!--</td>-->
<!--            --><?php //else : ?>
<!--                <td colspan="3">--><?php //echo $produto->getLinhaSeparacao()->getDescricao(); ?><!--</td>-->
<!--            --><?php //endif; ?>
<!--            <td colspan="3">--><?php //echo $produto->getTipoComercializacao()->getDescricao(); ?><!--</td>-->
<!--        </tr>-->
<!---->
<!--        <tr>-->
<!--            <td colspan="6" style="height:10px"></td>-->
<!--        </tr>-->
<!---->
<!--        --><?php //if ($produto->getCodigoBarrasBase()): ?>
<!--            <tr class="title">-->
<!--                <td colspan="3">Código de Barra Base:</td>-->
<!--                <td colspan="3">Nº Volumes:</td>-->
<!--            </tr>-->
<!--            <tr>-->
<!--                <td colspan="3">--><?php //echo $produto->getCodigoBarrasBase(); ?><!--</td>-->
<!--                <td colspan="3">--><?php //echo $produto->getNumVolumes(); ?><!--</td>-->
<!--            </tr>-->
<!--        --><?php //endif; ?>

