<form id="" method="post" class="saveForm" action="<?php echo $this->url(array('module' => 'expedicao', 'controller' =>'conferencia', 'action' =>'finalizar' )); ?>">
    <div id="quantidade-grid" class="grid">
        <table class="gTable ">
            <tbody>
            <tr>
                <td>
                    <div>
                        <p><b>Cargas da expedição:</b></p>
                        <?php foreach($this->cargas as $carga) : ?>
                            <?php echo $carga->getCodCargaExterno(); ?>
                        <?php endforeach; ?>
                    </div>
                </td>
            </tr>
            <tr style="line-height: 20px;">
                <td><div>
                        <p><b>Selecione a Central de Entrega</b></p>
                        <ul id="centrais">
                            <?php foreach($this->centraisEntrega as $central) : ?>
                                <li>
                                    <input
                                        type="radio"
                                        name="centrais[]"
                                        value="<?php echo $central['centralEntrega']?>"
                                        checked="true">
                                    Central de Entrega <?php echo $central['centralEntrega']?>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    </div></td>
            </tr>
            <tr style="line-height: 50px;">
                <td colspan="3">
                    <?php
                    echo '<label>Senha para confirmação: </label>';
                    echo $this->formPassword("senhaConfirmacao", '', array(
                        'size' => '50',
                        'maxlength' => '20',
                    ));
                    ?>
                    <button name="btnFinalizar" type="submit" value="semConferencia">Finalizar Conferencia Cega</button>
                </td>
            </tr>
            <tr>
                <td colspan="3">
                    <button name="btnFinalizar" id="finaliza-pelo-coletor" type="submit" value="comConferencia">Finalizar Pelo Coletor</button>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</form>
