<form id="" method="post" target="_blank" class="saveForm" action="<?php echo $this->url(array('module' => 'expedicao', 'controller' => 'volume-patrimonio', 'action' => 'imprimir-volume-patrimonio')); ?>">
    <div id="quantidade-grid" class="grid">
        <table class="gTable ">
            <?php echo 'Expedição: '. $this->idExpedicao; ?><br /><br />
            <thead>
                <tr>
                    <td>Cod. Volume Patrimônio</td>
                    <td>Descrição</td>
                </tr>
            </thead>
            <tbody>
            <?php foreach ($this->volumesPatrimonio as $volume) : ?>
                <tr>
                    <td><?php echo $volume['volume']; ?></td>
                    <td><?php echo $volume['descricao']; ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
        <button name="btnImprimir" class="imprimir-volume" id="imprimir-volume" type="submit" value="">Imprimir Volume Patrimonio</button>
    </div>
</form>