<?php
function mask($val, $mask){
    $maskared = '';
    $k = 0;
    for($i = 0; $i<=strlen($mask)-1; $i++) {
        if($mask[$i] == '#') {
            if(isset($val[$k])) $maskared .= $val[$k++];
        } else {
            if(isset($mask[$i])) $maskared .= $mask[$i];
        }
    }
    return $maskared;
}

?>
<form id="formGrid" method="post" action="<?php echo $this->url(array('controller' => 'reentrega', 'action' => 'gerar-recebimento')) ?>">

    <table style="margin-left: 5pt; width: 90%; margin-right: 5pt; margin-top: 5pt; margin-bottom: 5pt">
        <tbody>
        <tr>
            <td colspan="1"></td>
            <td style="text-align:center; padding-right: 10pt;"><span><b>Nota Fiscal</b></span></td>
            <td style="text-align:center; padding-right: 10pt;"><span><b>Carga</b></span></td>
            <td style="text-align:center; padding-right: 10pt;"><span><b>Emitente</b></span></td>
        </tr>
        <?php foreach($this->notasFiscaisByCarga as $notaFiscal) : ?>
            <tr style="margin-bottom: 10pt; padding-bottom: 10pt">
                <td><input type="checkbox" value="<?php echo $notaFiscal['id'] ?>" name="mass-id[]"></td>
                <td style="text-align:left; padding-right: 10pt;">&nbsp;<?php echo $notaFiscal['numeroNf']. "/" . $notaFiscal['serieNf']?></td>
                <td style="text-align:center; padding-right: 10pt;">&nbsp;<?php echo $notaFiscal['carga'] ?></td>
                <td style="text-align:center; padding-right: 10pt;">&nbsp;<?php echo mask($notaFiscal['cnpj'],'##.###.###/####-##') . " " . $notaFiscal['nome'] ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>

    <button type="submit"><span>Gerar Recebimento</span></button>
</form>
