<input type="hidden" id="numeroNota" value="<?php echo $this->id ?>">
Qtd: <input type="text" name="quantidade" id="quantidade">
Codigo de Barras: <input type="text" name="codBarras" id="codBarras">
<button type="button" id="conferir"><span>Reconferir</span></button>

<div id="footer">
    <a href="<?php echo "/mobile/reentrega/finalizar-conferencia/id/" . $this->id ?>" class="finalizar">
        Finalizar
    </a>
</div>

<script type="text/javascript">
    $(document).ready(function(){
        $('#conferir').click(function(){
            $.ajax({
                type: 'POST',
                url: '/mobile/reentrega/reconferir-produtos',
                data: {
                    codBarras: $('#codBarras').val(),
                    qtd: $('#quantidade').val(),
                    numeroNota: $('#numeroNota').val()
                },
                success: function(data) {
                    $('#codBarras').val('');
                    $('#quantidade').val('');
                }
            });
        })
    });
</script>