<?php 
echo $this->form;
?>
<script src="/javascript/corteJs.js"></script>
<form id="relatorio-picking-listar" method="post" class="saveForm" action="<?php echo $this->url(array('module' => 'expedicao', 'controller' =>'onda-ressuprimento', 'action' =>'gerar' ))?>">
<div id="quantidade-grid" class="grid">
    <input type="button" style="margin-bottom: 15px; display:none" name="busca" value="Gerar Onda" id="gerar" class="btn" >
    <button type="button" style="margin-bottom: 15px; display:none" id="modelo-separacao" class="btn"><span>Modelo de Separação</span></button>
    <table class="gTable ">
        <caption>Selecione as Expedições</caption>
        <tbody>
            <tr class ="gTTitle">
                <td></td>
                <td>Gerar</td>
                <td>Expedição</td>
                <td>Cargas</td>
                <td>TipoPedido</td>
                <td>Cubagem</td>
                <td>Peso</td>
                <td>Modelo Separação</td>
                <td>Placa</td>
                <td>Itinerário</td>
                <td>Dth.Abertura</td>
                <td>Status</td>
            </tr>
            <?php if ($this->expedicoes) : ?>
                <?php
                foreach ($this->expedicoes as $expedicao): $this->color = !($this->color);?>
                    <tr class = "<?php if (!$this->color) {echo 'gTResultSet gRowColor';} else {echo 'gTResultSet';}?>">
                        <td class="gTdOpcRow">
                            <div class="gOpcRow">
                                <ul>
                                    <li><img src="/img/admin/icon_opc.gif" alt="Op&ccedil;&otilde;es" />
                                        <ul>
                                            <li><a href="/expedicao/corte/corte-total/id/<?php echo $expedicao['COD_EXPEDICAO']?>" target="_blank" title="Corte Total">Corte Total de Produtos</a></li>
                                            <li><a href="/expedicao/corte/corte-pedido/id/<?php echo $expedicao['COD_EXPEDICAO']?>/origin/ressuprimento" target="_blank" title="Corte de Pedidos">Corte de Pedidos</a></li>
                                            <li><a href="/expedicao/corte/corte-produto/id/<?php echo $expedicao['COD_EXPEDICAO']?>" target="_self"  class="dialogAjax" title="Corte de Produtos">Corte de Produtos</a></li>
                                        </ul>
                                    </li>
                                </ul>
                            </div>
                        </td>
                        <td>
                            <input
                                class="checkBoxClass"
                                style="vertical-align: middle"
                                type="checkbox"
                                name="expedicao[]"
                                value="<?php echo $expedicao['COD_EXPEDICAO']?>">
                        </td>
                        <td><?php echo $expedicao['COD_EXPEDICAO'] ?></td>
                        <td><?php echo $expedicao['CARGA'] ?></td>
                        <td><?php echo $expedicao['TIPO_PEDIDO'] ?></td>
                        <td><?php echo number_format($expedicao['CUBAGEM'],3) ?></td>
                        <td><?php echo number_format($expedicao['PESO'],3) ?></td>
                        <td><?php echo $expedicao['MODELO'] ?></td>
                        <td><?php echo $expedicao['PLACA'] ?></td>
                        <td><?php echo $expedicao['ITINERARIO'] ?></td>
                        <td><?php echo $expedicao['DTH_INICIO'] ?></td>
                        <td><?php echo $expedicao['STATUS'] ?></td>
                    </tr>
                <?php endforeach; ?>
            <?php endif; ?>
        </tbody>
        </table>
    <div class = "gPager">
</form>