<?php
echo $this->doctype();
?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <!--[if gte IE 9]
            <style type="text/css">
                .gradient {
                    filter: none;
                }
            </style>
        <![endif]-->
        <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
        <meta http-equiv="Content-Language" content="pt-br" />
        <meta name="Keywords" content="" />
        <meta name="Description" content="" />
        <meta name="url" content="http://www.wmsms.com.br" />
        <meta name="reply-to" content="info@wmsms.com.br" />
        <meta name="copyright" content="www.wmsms.com.br" />
        <meta name="category" content="Internet" />
        <meta name="Robots" content="Index,Follow" />
        <!--<meta name="viewport" content="width=200, initial-scale=2">-->
        <meta content="width=240, height=320">
            <meta name="mobileoptimized" content="200">
                <link rel="shortcut icon" href="<?php echo $this->baseUrl('img/admin/favicon.ico') ?>" type="image/x-icon" />
                <script type="text/javascript" src="<?php echo $this->baseUrl() . "/jquery/jquery-1.11.1.min.js" ?>"></script>
                <script language="JavaScript" src="/bootstrap/js/bootstrap.min.js"></script>
                <link rel="stylesheet" href="/bootstrap/css/bootstrap.min.css" type="text/css" media="screen" />
                <link rel="stylesheet" href="/bootstrap/css/bootstrap-theme.min.css" type="text/css" media="screen" />
                <link rel="stylesheet" href="/css/mobile/style.css" type="text/css" media="screen" />

                <?php
                echo $this->jQuery()
                        ->setLocalPath($this->baseUrl() . "/jquery/jquery-1.11.1.min.js")
                        ->uiEnable()
                        ->setUiLocalPath($this->baseUrl() . "/wms/resources/ui.js");

                echo $this->headScript();
                ?> 
                <script>
                    $(document).ready(function () {
                        $('.focus').focus();

                        //Fechar as mensagens
                        $('a.fmBtnClose').click(function () {
                            // remove li
                            $(this).parent('div').parent('li').fadeOut();
                        });
                    });
                </script>
                </head>
                <div id="content" class="container-fluid  text-center row">
                    <div id="body" class="row col-xs-12">
                        <div id="userInfo" class="row">
                            <div class="row">
                                <div class="row col-xs-12 top">
                                    <h1 class="top"><a class=" " href="#" title="WMS - Imperium">WMS - Imperium</a></h1>
                                </div>
                            </div>
                        </div>
                        <?php $this->messenger(); ?>
                        <?php echo $this->layout()->content; ?>
                    </div>
                </div>
                </html>