<?php
echo $this->doctype();
?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <!--[if gte IE 9]
            <style type="text/css">
                .gradient {
                    filter: none;
                }
            </style>
        <![endif]-->
        <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
        <meta http-equiv="Content-Language" content="pt-br" />
        <meta name="Keywords" content="" />
        <meta name="Description" content="" />
        <meta name="url" content="http://www.wmsms.com.br" />
        <meta name="reply-to" content="info@wmsms.com.br" />
        <meta name="copyright" content="www.wmsms.com.br" />
        <meta name="category" content="Internet" />
        <meta name="Robots" content="Index,Follow" />
        <meta name="viewport" content="width=device-width, initial-scale=1">
            <link rel="shortcut icon" href="<?php echo $this->baseUrl('img/admin/favicon.ico') ?>" type="image/x-icon" />
            <link rel="stylesheet" href="/bootstrap/css/bootstrap.css" type="text/css" media="screen" />
            <link rel="stylesheet" href="/css/mobile/style.css" type="text/css" media="screen" />

            <?php
            echo $this->jQuery()
                    ->setLocalPath($this->baseUrl() . "/jquery/jquery.js")
                    ->uiEnable()
                    ->setUiLocalPath($this->baseUrl() . "/wms/resources/ui.js");

            echo $this->headScript();
            ?> 
            <script>
                $(document).ready(function () {
                    $('.focus').focus();

                    //Fechar as mensagens
                    $('a.fmBtnClose').click(function () {
                        // remove li
                        $(this).parent('div').parent('li').fadeOut();
                    });
                });
            </script>
    </head>
    <div id="content" class="container-fluid  text-center">
        <body>
            <div id="body">



                <div id="top" class="col-xs-12">
                    <nav id="userInfo"class="navbar navbar-default col-xs-2 text-center black">
                        <div class="container-fluid">
                            <button type="button" class="navbar-toggle collapsed col-xs-6" data-toggle="collapse" data-target="#bs-example-navbar-collapse-4" aria-expanded="false">
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-4">
                                <div id="" class="col-xs-12 text-right">
                                    <a class="btn" href="<?php echo $this->baseUrl('mobile'); ?>" title="Inicio" >Inicio</a>
                                </div>
                                <div id="" class="col-xs-12 text-right">
                                    <?php if ($this->urlVoltar) : ?>
                                        <a class="btn" href="<?php echo $this->urlVoltar ?>"title="Voltar para tela anterior" >Voltar</a>
                                    <?php else : ?>
                                        <a class="btn" href="#" onclick="history.go(-1);return false" title="Voltar para tela anterior" >Voltar</a>
                                    </div>
                                <?php endif; ?>
                                <div id="" class="col-xs-12 text-right">
                                    <a class="btn" href="<?php echo $this->url(array('controller' => 'auth', 'action' => 'logout')); ?>" title="Desconectar" >Sair</a>
                                </div>
                            </div>
                        </div>
                    </nav>
                    <h1><a href="#" title="WMS - Imperium">WMS - Imperium</a></h1>
                </div>
                <div class="contentPadding">
                    <?php $this->messenger(); ?>
                    <?php echo $this->layout()->content; ?>
                </div>
            </div>
            <script language="JavaScript" src="/bootstrap/js/bootstrap.js"></script>
        </body>
    </div>
</html>