<?php
echo $this->doctype();
?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <!--[if gte IE 9]
            <style type="text/css">
                .gradient {
                    filter: none;
                }
            </style>
        <![endif]-->
        <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
        <meta http-equiv="Content-Language" content="pt-br" />
        <meta name="Keywords" content="" />
        <meta name="Description" content="" />
        <meta name="url" content="http://www.wmsms.com.br" />
        <meta name="reply-to" content="info@wmsms.com.br" />
        <meta name="copyright" content="www.wmsms.com.br" />
        <meta name="category" content="Internet" />
        <meta name="Robots" content="Index,Follow" />
        <meta name="viewport" content="width=device-width, initial-scale=1">
            <link rel="shortcut icon" href="<?php echo $this->baseUrl('img/admin/favicon.ico') ?>" type="image/x-icon" />
            <script type="text/javascript" src="<?php echo $this->baseUrl() . "/jquery/jquery-1.11.1.min" ?>"></script>
            <link rel="stylesheet" href="/bootstrap/css/bootstrap.css" type="text/css" media="screen" />
            <link rel="stylesheet" href="/css/mobile/style.css" type="text/css" media="screen" />
            <script language="JavaScript" src="/bootstrap/js/bootstrap.js"></script>
<script>alert('oiii');</script>

            <?php
            echo $this->jQuery()
                    ->setLocalPath($this->baseUrl() . "/jquery/jquery-1.11.1.min")
                    ->uiEnable()
                    ->setUiLocalPath($this->baseUrl() . "/wms/resources/ui.js");

            echo $this->headScript();
            ?> 
            <script>
                $(document).ready(function () {
                    $('.focus').focus();

                    //Fechar as mensagens
                    $('a.fmBtnClose').click(function () {
                        // remove li
                        $(this).parent('div').parent('li').fadeOut();
                    });
                });
            </script>
    </head>

    <div id="content" style="padding: initial;" class="container-fluid  text-center">
        <body>
            <nav id="top" class="navbar navbar-default">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button style="width:auto!important; background:#dddddd!important" type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <h1><a href="#" title="WMS - Imperium">WMS - Imperium</a></h1>
                    </div>
                    <div id="navbar" class="navbar-collapse collapse">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="active"><a href="<?php echo $this->baseUrl('mobile'); ?>" title="Inicio" ><b>Inicio</b> <span class="sr-only">(current)</span></a></li>
                            <?php if ($this->urlVoltar) : ?>
                                <li><a href="<?php echo $this->urlVoltar ?>"title="Voltar para tela anterior" ><b>Voltar</b></a></li>
                            <?php else : ?>
                                <li><a  href="#" onclick="history.go(-1);return false" title="Voltar para tela anterior" ><b>Voltar</b></a></li>
                            <?php endif; ?>
                            <li><a href="<?php echo $this->url(array('controller' => 'auth', 'action' => 'logout')); ?>" title="Desconectar" ><b>Sair</b></a></li>
                        </ul>
                    </div><!--/.nav-collapse -->
                </div><!--/.container-fluid -->
            </nav>
            <div id="body">
                <div class="contentPadding">
                    <?php $this->messenger(); ?>
                    <?php echo $this->layout()->content; ?>
                </div>
            </div>
        </body>
    </div>
</html>