<?php
echo $this->doctype();
?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
        <meta http-equiv="Content-Language" content="pt-br" />
        <?php
        echo $this->jQuery()
            ->setLocalPath($this->baseUrl() . "/jquery/jquery.js")
            ->uiEnable()
            ->setUiLocalPath($this->baseUrl() . "/wms/resources/ui.js");

        echo $this->headScript();
        ?>
        <script>
            function load(url, formId, callback) {
                var xhr;

                if(typeof XMLHttpRequest !== 'undefined') xhr = new XMLHttpRequest();
                else {
                    var versions = ["MSXML2.XmlHttp.5.0",
                        "MSXML2.XmlHttp.4.0",
                        "MSXML2.XmlHttp.3.0",
                        "MSXML2.XmlHttp.2.0",
                        "Microsoft.XMLHTTP"]

                    for(var i = 0, len = versions.length; i < len; i++) {
                        try {
                            xhr = new ActiveXObject(versions[i]);
                            break;
                        }
                        catch(e){}
                    } // end for
                }

                xhr.onreadystatechange = ensureReadiness;

                function ensureReadiness() {
                    if(xhr.readyState < 4) {
                        return;
                    }

                    if(xhr.status !== 200) {
                        return;
                    }

                    // all is well
                    if(xhr.readyState === 4) {
                        callback(xhr);
                    }
                }

                var elem = document.getElementById(formId).elements;
                var params = "";
                //url = document.getElementById(formId).action;
                for(var i = 0; i < elem.length; i++){
                    if (elem[i].tagName == "SELECT"){
                        params += elem[i].name + "=" +     encodeURIComponent(elem[i].options[elem[i].selectedIndex].value) + "&";
                    }else{
                        params += elem[i].name + "=" + encodeURIComponent(elem[i].value) + "&";
                    }
                }

                xhr.open("POST",url,false);
                xhr.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
                if(Object.is(params)){
                    xhr.setRequestHeader("Content-length", params.length);
                    xhr.setRequestHeader("Connection", "close");
                }
                xhr.setRequestHeader('X-Requested-With','XMLHttpRequest');
                xhr.send(params);
            }

            function playSound(soundfile) {
                document.getElementById("dummy").innerHTML=
                    "<embed src=\""+soundfile+"\" hidden=\"true\" autostart=\"true\" loop=\"false\" />";
            }

        </script>
<!--        --><?php //echo $this->headScript() ?>
    </head>
    <body onload="focusInput()">
        <div id="body">
            <div id="top">
                <div id="userInfo">
                    <a href="<?php echo $this->baseUrl('mobile'); ?>" title="Inicio" >Inicio</a>
                    <a href="#" onclick="history.go(-1);return false" title="Voltar para tela anterior" >Voltar</a>
                    <a href="<?php echo $this->url(array('controller' => 'auth', 'action' => 'logout')); ?>" title="Desconectar" >Sair</a>
                </div>
            </div>

            <div id="content">
                <?php $this->messenger(); ?>
                <?php echo $this->layout()->content; ?>
            </div>
        </div>
    </body>
</html>
