UPDATE MENU_ITEM
SET COD_PAI =
(SELECT M.COD_MENU_ITEM
 FROM MENU_ITEM M
   LEFT JOIN MENU_ITEM P ON P.COD_MENU_ITEM = M.COD_PAI
 WHERE M.DSC_MENU_ITEM = 'Endereço'
       AND P.DSC_MENU_ITEM = 'Cadastros')
WHERE COD_MENU_ITEM =
      (SELECT M.COD_MENU_ITEM
       FROM MENU_ITEM M
         LEFT JOIN MENU_ITEM P ON P.COD_MENU_ITEM = M.COD_PAI
       WHERE M.DSC_MENU_ITEM = 'Imprimir Etiquetas'
             AND P.DSC_MENU_ITEM = 'Produto');

INSERT INTO RECURSO (COD_RECURSO, DSC_RECURSO, COD_RECURSO_PAI, NOM_RECURSO) VALUES (SQ_RECURSO_01.NEXTVAL, 'Produtos da Expedicao', 0, 'expedicao:relatorio_produtos');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO)VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'expedicao:relatorio_produtos'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'index'), 'Produtos da Expedição');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO)VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'expedicao:relatorio_produtos'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'imprimir'), 'Imprimir Produtos da Expedição');
INSERT INTO MENU_ITEM (COD_MENU_ITEM, COD_RECURSO_ACAO, COD_PAI, DSC_MENU_ITEM, NUM_PESO, DSC_URL, SHOW) VALUES (SQ_MENU_ITEM_01.NEXTVAL, (SELECT COD_RECURSO_ACAO FROM RECURSO_ACAO WHERE COD_RECURSO = (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'expedicao:relatorio_produtos') AND COD_ACAO = '5'), (SELECT COD_MENU_ITEM FROM MENU_ITEM WHERE DSC_MENU_ITEM = 'Relatórios' AND COD_PAI = 0), 'Produtos da Expedicao', 1, '#', 'S');

INSERT INTO RECURSO (COD_RECURSO, DSC_RECURSO, COD_RECURSO_PAI, NOM_RECURSO) VALUES (SQ_RECURSO_01.NEXTVAL, 'Corte por Faixa', 0, 'expedicao:corte-faixa');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO)VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'expedicao:corte-faixa'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'index'), 'Gerar Corte por Faixa de Etiqueta');
INSERT INTO MENU_ITEM (COD_MENU_ITEM, COD_RECURSO_ACAO, COD_PAI, DSC_MENU_ITEM, NUM_PESO, DSC_URL, SHOW) VALUES (SQ_MENU_ITEM_01.NEXTVAL, (SELECT COD_RECURSO_ACAO FROM RECURSO_ACAO WHERE COD_RECURSO = (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'expedicao:corte-faixa') AND COD_ACAO = '5'), (SELECT COD_MENU_ITEM FROM MENU_ITEM WHERE DSC_MENU_ITEM = 'Expedição' AND COD_PAI = 0), 'Corte por Faixa de Etiquetas', 1, '#', 'S');

INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO)VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'usuario'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'imprimir'), 'Imprimir etiqueta de Usuário');

INSERT INTO RECURSO (COD_RECURSO, DSC_RECURSO, COD_RECURSO_PAI, NOM_RECURSO) VALUES (SQ_RECURSO_01.NEXTVAL, 'Reimpressão por Faixa', 0, 'expedicao:reimpressao-faixa');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO)VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'expedicao:reimpressao-faixa'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'index'), 'Reimprimir Faixa de Etiquetas');
INSERT INTO MENU_ITEM (COD_MENU_ITEM, COD_RECURSO_ACAO, COD_PAI, DSC_MENU_ITEM, NUM_PESO, DSC_URL, SHOW) VALUES (SQ_MENU_ITEM_01.NEXTVAL, (SELECT COD_RECURSO_ACAO FROM RECURSO_ACAO WHERE COD_RECURSO = (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'expedicao:reimpressao-faixa') AND COD_ACAO = '5'), (SELECT COD_MENU_ITEM FROM MENU_ITEM WHERE DSC_MENU_ITEM = 'Expedição' AND COD_PAI = 0), 'Reimpressao por Faixa de Etiquetas', 1, '#', 'S');

INSERT INTO ACAO(COD_ACAO, DSC_ACAO, NOM_ACAO) VALUES (SQ_ACAO_01.NEXTVAL, 'Excluir Nota', 'excluir-nota');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO)VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'recebimento'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'excluir-nota'), 'Excluir Nota Fiscal');

INSERT INTO CONTEXTO_PARAMETRO (COD_CONTEXTO_PARAMETRO, DSC_CONTEXTO_PARAMETRO) VALUES (SQ_CONTEXTO_PARAMETRO_01.NEXTVAL, 'RELATORIOS E IMPRESSAO');
INSERT INTO PARAMETRO (COD_PARAMETRO, COD_CONTEXTO_PARAMETRO, DSC_PARAMETRO, DSC_TITULO_PARAMETRO, IND_PARAMETRO_SISTEMA, COD_TIPO_ATRIBUTO, DSC_VALOR_PARAMETRO) VALUES (SQ_PARAMETRO_01.NEXTVAL, (SELECT COD_CONTEXTO_PARAMETRO FROM CONTEXTO_PARAMETRO WHERE DSC_CONTEXTO_PARAMETRO = 'RELATORIOS E IMPRESSAO'),'MODELO_ETIQUETA_PICKING', 'Modelo da Etiqueta de Picking','N','A','1');
INSERT INTO PARAMETRO (COD_PARAMETRO, COD_CONTEXTO_PARAMETRO, DSC_PARAMETRO, DSC_TITULO_PARAMETRO, IND_PARAMETRO_SISTEMA, COD_TIPO_ATRIBUTO, DSC_VALOR_PARAMETRO) VALUES (SQ_PARAMETRO_01.NEXTVAL, (SELECT COD_CONTEXTO_PARAMETRO FROM CONTEXTO_PARAMETRO WHERE DSC_CONTEXTO_PARAMETRO = 'RELATORIOS E IMPRESSAO'),'MODELO_ETIQUETA_SEPARACAO', 'Modelo da Etiqueta de Separação','N','A','1');
INSERT INTO PARAMETRO (COD_PARAMETRO, COD_CONTEXTO_PARAMETRO, DSC_PARAMETRO, DSC_TITULO_PARAMETRO, IND_PARAMETRO_SISTEMA, COD_TIPO_ATRIBUTO, DSC_VALOR_PARAMETRO) VALUES (SQ_PARAMETRO_01.NEXTVAL, (SELECT COD_CONTEXTO_PARAMETRO FROM CONTEXTO_PARAMETRO WHERE DSC_CONTEXTO_PARAMETRO = 'RELATORIOS E IMPRESSAO'),'MODELO_ETIQUETA_PRODUTO', 'Modelo da Etiqueta de Produto','N','A','1');
UPDATE PARAMETRO SET COD_CONTEXTO_PARAMETRO = (SELECT COD_CONTEXTO_PARAMETRO FROM CONTEXTO_PARAMETRO WHERE DSC_CONTEXTO_PARAMETRO = 'RELATORIOS E IMPRESSAO') WHERE DSC_PARAMETRO = 'MODELO_RELATORIOS';

ALTER TABLE HISTORICO_ESTOQUE ADD  (COD_UNITIZADOR NUMBER(8));
