INSERT INTO MENU_ITEM (COD_MENU_ITEM, COD_RECURSO_ACAO, COD_PAI, DSC_MENU_ITEM, NUM_PESO, DSC_URL, SHOW) VALUES (SQ_MENU_ITEM_01.NEXTVAL,0,(SELECT MIN(COD_MENU_ITEM) FROM MENU_ITEM WHERE DSC_MENU_ITEM = 'Cadastros'),'Nota Fiscal',1,'#','S');

INSERT INTO RECURSO (COD_RECURSO, DSC_RECURSO, COD_RECURSO_PAI, NOM_RECURSO) VALUES (SQ_RECURSO_01.NEXTVAL, 'Importar XML', 0, 'notafiscal:importarxml');

INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO)VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'notafiscal:importarxml'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'index'), 'Pagina XML');

INSERT INTO MENU_ITEM (COD_MENU_ITEM, COD_RECURSO_ACAO, COD_PAI, DSC_MENU_ITEM, NUM_PESO, DSC_URL, SHOW) VALUES (SQ_MENU_ITEM_01.NEXTVAL,(SELECT COD_RECURSO_ACAO FROM RECURSO_ACAO WHERE COD_RECURSO = (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'notafiscal:importarxml')),(SELECT MAX(COD_MENU_ITEM) FROM MENU_ITEM WHERE DSC_MENU_ITEM = 'Nota Fiscal'),'Importar XML',1,'#','S');