INSERT INTO "WMS_ADM"."RECURSO" (DSC_RECURSO, COD_RECURSO, COD_RECURSO_PAI, NOM_RECURSO) VALUES ('Cadastro Mascara Recurso', '768', '297', 'mascara-recurso');

INSERT INTO "WMS_ADM"."RECURSO" (DSC_RECURSO, COD_RECURSO, NOM_RECURSO) VALUES ('Menu de Expedição', '769', 'menu-expedicao');

UPDATE "WMS_ADM"."RECURSO" SET DSC_RECURSO = 'Menu de TI' WHERE ROWID = 'AAASe6AAGAAAAC/AAC' AND ORA_ROWSCN = '2846452';
INSERT INTO "WMS_ADM"."RECURSO_ACAO" (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES ('691', '769', '8', 'Visualizar');

DELETE FROM "WMS_ADM"."RECURSO_ACAO" WHERE ROWID = 'AAASe8AAGAAAADNAAA' AND ORA_ROWSCN = '4392439' and ( "COD_RECURSO_ACAO" is null or "COD_RECURSO_ACAO" is not null );
DELETE FROM "WMS_ADM"."RECURSO_ACAO" WHERE ROWID = 'AAASe8AAGAAAADPAAH' AND ORA_ROWSCN = '2846452' and ( "COD_RECURSO_ACAO" is null or "COD_RECURSO_ACAO" is not null );
DELETE FROM "WMS_ADM"."RECURSO_ACAO" WHERE ROWID = 'AAASe8AAGAAAADPAAI' AND ORA_ROWSCN = '2846452' and ( "COD_RECURSO_ACAO" is null or "COD_RECURSO_ACAO" is not null );
DELETE FROM "WMS_ADM"."RECURSO_ACAO" WHERE ROWID = 'AAASe8AAGAAAADPAAA' AND ORA_ROWSCN = '2846452' and ( "COD_RECURSO_ACAO" is null or "COD_RECURSO_ACAO" is not null );
DELETE FROM "WMS_ADM"."RECURSO_ACAO" WHERE ROWID = 'AAASe8AAGAAAADNAAB' AND ORA_ROWSCN = '4392439' and ( "COD_RECURSO_ACAO" is null or "COD_RECURSO_ACAO" is not null );
DELETE FROM "WMS_ADM"."RECURSO_ACAO" WHERE ROWID = 'AAASe8AAGAAAADMAAA' AND ORA_ROWSCN = '4393233' and ( "COD_RECURSO_ACAO" is null or "COD_RECURSO_ACAO" is not null );
DELETE FROM "WMS_ADM"."RECURSO_ACAO" WHERE ROWID = 'AAASe8AAGAAAADMAAB' AND ORA_ROWSCN = '4393233' and ( "COD_RECURSO_ACAO" is null or "COD_RECURSO_ACAO" is not null );
DELETE FROM "WMS_ADM"."RECURSO_ACAO" WHERE ROWID = 'AAASe8AAGAAAADMAAD' AND ORA_ROWSCN = '4393233' and ( "COD_RECURSO_ACAO" is null or "COD_RECURSO_ACAO" is not null );
DELETE FROM "WMS_ADM"."RECURSO_ACAO" WHERE ROWID = 'AAASe8AAGAAAADOAAB' AND ORA_ROWSCN = '4463275' and ( "COD_RECURSO_ACAO" is null or "COD_RECURSO_ACAO" is not null );



DELETE FROM "WMS_ADM"."RECURSO" WHERE ROWID = 'AAASe6AAGAAAAC/AAC' AND ORA_ROWSCN = '4462882' and ( "DSC_RECURSO" is null or "DSC_RECURSO" is not null );
DELETE FROM "WMS_ADM"."RECURSO" WHERE ROWID = 'AAASe6AAGAAAAC/AAD' AND ORA_ROWSCN = '4462882' and ( "DSC_RECURSO" is null or "DSC_RECURSO" is not null );
DELETE FROM "WMS_ADM"."RECURSO" WHERE ROWID = 'AAASe6AAGAAAAC8AAE' AND ORA_ROWSCN = '3381948' and ( "DSC_RECURSO" is null or "DSC_RECURSO" is not null );
DELETE FROM "WMS_ADM"."RECURSO" WHERE ROWID = 'AAASe6AAGAAAAC+AAA' AND ORA_ROWSCN = '4463209' and ( "DSC_RECURSO" is null or "DSC_RECURSO" is not null );
DELETE FROM "WMS_ADM"."RECURSO" WHERE ROWID = 'AAASe6AAGAAAAC8AAB' AND ORA_ROWSCN = '3381948' and ( "DSC_RECURSO" is null or "DSC_RECURSO" is not null );
DELETE FROM "WMS_ADM"."RECURSO" WHERE ROWID = 'AAASe6AAGAAAAC+AAD' AND ORA_ROWSCN = '4463209' and ( "DSC_RECURSO" is null or "DSC_RECURSO" is not null );
DELETE FROM "WMS_ADM"."RECURSO" WHERE ROWID = 'AAASe6AAGAAAAC9AAA' AND ORA_ROWSCN = '4392595' and ( "DSC_RECURSO" is null or "DSC_RECURSO" is not null );
DELETE FROM "WMS_ADM"."RECURSO" WHERE ROWID = 'AAASe6AAGAAAAC/AAB' AND ORA_ROWSCN = '4462882' and ( "DSC_RECURSO" is null or "DSC_RECURSO" is not null );
DELETE FROM "WMS_ADM"."RECURSO" WHERE ROWID = 'AAASe6AAGAAAAC8AAC' AND ORA_ROWSCN = '3381948' and ( "DSC_RECURSO" is null or "DSC_RECURSO" is not null );


UPDATE "WMS_ADM"."RECURSO" SET DSC_RECURSO = 'Menu de Recebimento', NOM_RECURSO = 'menu-recebimento' WHERE ROWID = 'AAASe6AAGAAAAC7AAA' AND ORA_ROWSCN = '4393221';
UPDATE "WMS_ADM"."RECURSO" SET DSC_RECURSO = 'Menu de Sistema', NOM_RECURSO = 'menu-sistema' WHERE ROWID = 'AAASe6AAGAAAAC7AAV' AND ORA_ROWSCN = '4393221';
UPDATE "WMS_ADM"."RECURSO" SET DSC_RECURSO = 'Menu de TI', NOM_RECURSO = 'menu-ti' WHERE ROWID = 'AAASe6AAGAAAAC7AAO' AND ORA_ROWSCN = '4393221';
UPDATE "WMS_ADM"."RECURSO" SET DSC_RECURSO = 'Menu de Cadastro', NOM_RECURSO = 'menu-cadastro' WHERE ROWID = 'AAASe6AAGAAAAC7AAW' AND ORA_ROWSCN = '4393221';


UPDATE "WMS_ADM"."RECURSO" SET DSC_RECURSO = 'Menu do Sistema' WHERE ROWID = 'AAASe6AAGAAAAC7AAV' AND ORA_ROWSCN = '4464962';

INSERT INTO "WMS_ADM"."RECURSO" (DSC_RECURSO, COD_RECURSO, NOM_RECURSO) VALUES ('Menu de Consulta', '769', 'menu-consulta');

UPDATE "WMS_ADM"."RECURSO_ACAO" SET DSC_RECURSO_ACAO = 'Acessar cadastros' WHERE ROWID = 'AAASe8AAGAAAADLAAM' AND ORA_ROWSCN = '4393221';

INSERT INTO "WMS_ADM"."RECURSO_ACAO" (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES ('691', '769', '5', 'Acessar');
INSERT INTO "WMS_ADM"."RECURSO_ACAO" (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES ('692', '638', '5', 'Acessar');
INSERT INTO "WMS_ADM"."RECURSO" (DSC_RECURSO, COD_RECURSO, NOM_RECURSO) VALUES ('Menu de Armazenagem', '770', 'menu-armazenagem');
INSERT INTO "WMS_ADM"."RECURSO" (DSC_RECURSO, COD_RECURSO, NOM_RECURSO) VALUES ('Menu de Inventário', '771', 'menu-inventario');
INSERT INTO "WMS_ADM"."RECURSO" (DSC_RECURSO, COD_RECURSO, NOM_RECURSO) VALUES ('Menu de Expedição', '772', 'menu-expedicao');
INSERT INTO "WMS_ADM"."RECURSO" (DSC_RECURSO, COD_RECURSO, NOM_RECURSO) VALUES ('Menu de Relatório', '773', 'menu-relatorio');
INSERT INTO "WMS_ADM"."RECURSO_ACAO" (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES ('693', '770', '5', 'Acessar');
INSERT INTO "WMS_ADM"."RECURSO_ACAO" (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES ('694', '771', '5', 'Acessar');
INSERT INTO "WMS_ADM"."RECURSO_ACAO" (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES ('695', '772', '5', 'Acessar');
INSERT INTO "WMS_ADM"."RECURSO_ACAO" (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES ('696', '773', '5', 'Acessar');
INSERT INTO "WMS_ADM"."RECURSO_ACAO" (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES ('397', '639', '5', 'Acessar');

INSERT INTO "WMS_ADM"."RECURSO" (DSC_RECURSO, COD_RECURSO, NOM_RECURSO) VALUES ('Relatóro Lista de Usuários', '774', 'rel-lista-usuario');
INSERT INTO "WMS_ADM"."RECURSO_ACAO" (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES ('697', '774', '3', 'Listar');

INSERT INTO "WMS_ADM"."RECURSO_ACAO" (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES ('698', '62', '5', 'Listar');
INSERT INTO "WMS_ADM"."RECURSO_ACAO" (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES ('699', '62', '2', 'Editar');
INSERT INTO "WMS_ADM"."RECURSO_ACAO" (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES ('702', '768', '5', 'Início ');
INSERT INTO "WMS_ADM"."RECURSO_ACAO" (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES ('703', '527', '1', 'Adicionar');
INSERT INTO "WMS_ADM"."RECURSO_ACAO" (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES ('704', '527', '2', 'Editar');
INSERT INTO "WMS_ADM"."RECURSO_ACAO" (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES ('723', '567', '5', 'Início');
INSERT INTO "WMS_ADM"."RECURSO_ACAO" (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES ('724', '567', '8', 'Visualizar');

UPDATE "WMS_ADM"."RECURSO_ACAO" SET COD_RECURSO = '60' WHERE ROWID = 'AAASe8AAGAAAADOAAF' AND ORA_ROWSCN = '5425322';
UPDATE "WMS_ADM"."RECURSO_ACAO" SET COD_RECURSO = '60' WHERE ROWID = 'AAASe8AAGAAAADOAAA' AND ORA_ROWSCN = '5425322';
UPDATE "WMS_ADM"."RECURSO_ACAO" SET COD_RECURSO = '60' WHERE ROWID = 'AAASe8AAGAAAADOAAG' AND ORA_ROWSCN = '5425322';
INSERT INTO "WMS_ADM"."RECURSO_ACAO" (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES ('725', '60', '5', 'Inicio atividade');
DELETE FROM "WMS_ADM"."RECURSO_ACAO" WHERE ROWID = 'AAASe8AAGAAAADLAAG' AND ORA_ROWSCN = '5423195' and ( "COD_RECURSO_ACAO" is null or "COD_RECURSO_ACAO" is not null );
DELETE FROM "WMS_ADM"."RECURSO_ACAO" WHERE ROWID = 'AAASe8AAGAAAADLAAF' AND ORA_ROWSCN = '5423195' and ( "COD_RECURSO_ACAO" is null or "COD_RECURSO_ACAO" is not null );
DELETE FROM "WMS_ADM"."RECURSO_ACAO" WHERE ROWID = 'AAASe8AAGAAAADLAAB' AND ORA_ROWSCN = '5423195' and ( "COD_RECURSO_ACAO" is null or "COD_RECURSO_ACAO" is not null );
DELETE FROM "WMS_ADM"."RECURSO_ACAO" WHERE ROWID = 'AAASe8AAGAAAADLAAA' AND ORA_ROWSCN = '5423195' and ( "COD_RECURSO_ACAO" is null or "COD_RECURSO_ACAO" is not null );
INSERT INTO "WMS_ADM"."RECURSO_ACAO" (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES ('726', '658', '1', 'Adicionar');
INSERT INTO "WMS_ADM"."RECURSO_ACAO" (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES ('727', '658', '2', 'Editar');
INSERT INTO "WMS_ADM"."RECURSO_ACAO" (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES ('728', '658', '4', 'Deletar');
INSERT INTO "WMS_ADM"."RECURSO_ACAO" (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES ('729', '658', '5', 'Início');
INSERT INTO "WMS_ADM"."RECURSO_ACAO" (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES ('730', '477', '1', 'Adicionar');
INSERT INTO "WMS_ADM"."RECURSO_ACAO" (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES ('731', '477', '2', 'Editar');
INSERT INTO "WMS_ADM"."RECURSO_ACAO" (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES ('732', '477', '4', 'Deletar');
INSERT INTO "WMS_ADM"."RECURSO_ACAO" (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES ('733', '477', '5', 'Iníciar');
INSERT INTO "WMS_ADM"."RECURSO_ACAO" (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES ('705', '527', '4', 'Deletar');
INSERT INTO "WMS_ADM"."RECURSO_ACAO" (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES ('706', '527', '5', 'Início');
INSERT INTO "WMS_ADM"."RECURSO_ACAO" (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES ('707', '537', '1', 'Adicionar');
INSERT INTO "WMS_ADM"."RECURSO_ACAO" (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES ('708', '537', '2', 'Editar');
INSERT INTO "WMS_ADM"."RECURSO_ACAO" (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES ('709', '537', '4', 'Deletar');
INSERT INTO "WMS_ADM"."RECURSO_ACAO" (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES ('710', '537', '5', 'Início');
INSERT INTO "WMS_ADM"."RECURSO_ACAO" (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES ('712', '467', '1', 'Adicionar');
INSERT INTO "WMS_ADM"."RECURSO_ACAO" (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES ('713', '467', '2', 'Editar');
INSERT INTO "WMS_ADM"."RECURSO_ACAO" (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES ('714', '467', '4', 'Deletar');
INSERT INTO "WMS_ADM"."RECURSO_ACAO" (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES ('715', '467', '5', 'Início');
INSERT INTO "WMS_ADM"."RECURSO_ACAO" (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES ('716', '457', '1', 'Adicionar');
INSERT INTO "WMS_ADM"."RECURSO_ACAO" (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES ('717', '457', '2', 'Editar');
INSERT INTO "WMS_ADM"."RECURSO_ACAO" (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES ('718', '457', '4', 'Deletar');
INSERT INTO "WMS_ADM"."RECURSO_ACAO" (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES ('719', '457', '5', 'Início');
UPDATE "WMS_ADM"."RECURSO_ACAO" SET COD_ACAO = '5' WHERE ROWID = 'AAASe8AAGAAAADMAAC' AND ORA_ROWSCN = '4815997';
DELETE FROM "WMS_ADM"."RECURSO_ACAO" WHERE ROWID = 'AAASe8AAGAAAADLABY' AND ORA_ROWSCN = '5418412' and ( "COD_RECURSO_ACAO" is null or "COD_RECURSO_ACAO" is not null );
DELETE FROM "WMS_ADM"."RECURSO_ACAO" WHERE ROWID = 'AAASe8AAGAAAADLABX' AND ORA_ROWSCN = '5418412' and ( "COD_RECURSO_ACAO" is null or "COD_RECURSO_ACAO" is not null );
UPDATE "WMS_ADM"."RECURSO_ACAO" SET COD_ACAO = '8', DSC_RECURSO_ACAO = 'Visualizar' WHERE ROWID = 'AAASe8AAGAAAADLABW' AND ORA_ROWSCN = '5418412';
UPDATE "WMS_ADM"."RECURSO_ACAO" SET DSC_RECURSO_ACAO = 'Início' WHERE ROWID = 'AAASe8AAGAAAADLABZ' AND ORA_ROWSCN = '5418412';
UPDATE "WMS_ADM"."RECURSO" SET COD_RECURSO_PAI = '769' WHERE ROWID = 'AAASe6AAGAAAAC7AAe' AND ORA_ROWSCN = '5418472';
UPDATE "WMS_ADM"."RECURSO" SET COD_RECURSO_PAI = '769' WHERE ROWID = 'AAASe6AAGAAAAC7AAY' AND ORA_ROWSCN = '5418472';
UPDATE "WMS_ADM"."RECURSO" SET COD_RECURSO_PAI = '769' WHERE ROWID = 'AAASe6AAGAAAAC7AAE' AND ORA_ROWSCN = '5418472';
UPDATE "WMS_ADM"."RECURSO" SET COD_RECURSO_PAI = '769' WHERE ROWID = 'AAASe6AAGAAAAC7AAl' AND ORA_ROWSCN = '5418472';
UPDATE "WMS_ADM"."RECURSO" SET COD_RECURSO_PAI = '769' WHERE ROWID = 'AAASe6AAGAAAAC7AAM' AND ORA_ROWSCN = '5418472';
UPDATE "WMS_ADM"."RECURSO_ACAO" SET DSC_RECURSO_ACAO = 'Início' WHERE ROWID = 'AAASe8AAGAAAADLAAf' AND ORA_ROWSCN = '5422482';
INSERT INTO "WMS_ADM"."RECURSO_ACAO" (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES ('720', '47', '8', 'Visualizar');
INSERT INTO "WMS_ADM"."RECURSO_ACAO" (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES ('721', '427', '5', 'Início');
INSERT INTO "WMS_ADM"."RECURSO_ACAO" (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES ('722', '427', '8', 'Visualizar');
INSERT INTO "WMS_ADM"."RECURSO_ACAO" (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES ('734', '487', '1', 'Adicionar');
INSERT INTO "WMS_ADM"."RECURSO_ACAO" (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES ('735', '487', '2', 'Editar');
INSERT INTO "WMS_ADM"."RECURSO_ACAO" (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES ('736', '487', '4', 'Deletar');
INSERT INTO "WMS_ADM"."RECURSO_ACAO" (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES ('737', '487', '5', 'Listar');
INSERT INTO "WMS_ADM"."RECURSO_ACAO" (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES ('738', '547', '1', 'Adicionar');
INSERT INTO "WMS_ADM"."RECURSO_ACAO" (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES ('739', '547', '2', 'Editar');
INSERT INTO "WMS_ADM"."RECURSO_ACAO" (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES ('740', '547', '4', 'Deletar');
INSERT INTO "WMS_ADM"."RECURSO_ACAO" (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES ('741', '547', '5', 'Início');
INSERT INTO "WMS_ADM"."RECURSO_ACAO" (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES ('742', '61', '1', 'Adicionar');
INSERT INTO "WMS_ADM"."RECURSO_ACAO" (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES ('743', '61', '2', 'Editar');
INSERT INTO "WMS_ADM"."RECURSO_ACAO" (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES ('744', '61', '4', 'Deletar');
INSERT INTO "WMS_ADM"."RECURSO_ACAO" (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES ('745', '61', '5', 'Início');
INSERT INTO "WMS_ADM"."RECURSO_ACAO" (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES ('746', '577', '1', 'Adicionar');
INSERT INTO "WMS_ADM"."RECURSO_ACAO" (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES ('747', '577', '2', 'Editar');
INSERT INTO "WMS_ADM"."RECURSO_ACAO" (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES ('748', '577', '4', 'Deletar');
INSERT INTO "WMS_ADM"."RECURSO_ACAO" (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES ('749', '577', '5', 'Início');
INSERT INTO "WMS_ADM"."RECURSO_ACAO" (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES ('750', '58', '5', 'Acessar');
UPDATE "WMS_ADM"."RECURSO" SET COD_RECURSO_PAI = '277' WHERE ROWID = 'AAASe6AAGAAAAC7AAu' AND ORA_ROWSCN = '5425034';
UPDATE "WMS_ADM"."RECURSO" SET COD_RECURSO_PAI = '58' WHERE ROWID = 'AAASe6AAGAAAAC7AAP' AND ORA_ROWSCN = '5431866';
UPDATE "WMS_ADM"."RECURSO" SET COD_RECURSO_PAI = '58' WHERE ROWID = 'AAASe6AAGAAAAC7AAv' AND ORA_ROWSCN = '5431905';
INSERT INTO "WMS_ADM"."RECURSO_ACAO" (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES ('751', '5', '1', 'Adicionar');
INSERT INTO "WMS_ADM"."RECURSO_ACAO" (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES ('752', '5', '2', 'Editar');
INSERT INTO "WMS_ADM"."RECURSO_ACAO" (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES ('753', '5', '4', 'Deletar');
INSERT INTO "WMS_ADM"."RECURSO_ACAO" (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES ('754', '5', '5', 'Início');

-- revision 2012.02.02
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, 62, 5, 'Inicio');
INSERT INTO recurso_acao (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, 62, 4, 'Deletar');
INSERT INTO recurso_acao (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, 62, 2, 'Editar');
INSERT INTO recurso_acao (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, 62, 1, 'Adicionar');

COMMIT;


-- revision 2012.23.02 feita por Adriano
--Observar os updates em RECURSO_ACAO, verificar quais os COD_RECURSO_ACAO estão cadastrados para o recurso 347
INSERT INTO MENU_ITEM (COD_MENU_ITEM, COD_RECURSO_ACAO, COD_PAI, DSC_MENU_ITEM, PESO, URL) VALUES (SQ_MENU_ITEM_01.NEXTVAL, 0, 20, 'Veículo', 10, '#');
UPDATE "WMS_ADM"."MENU_ITEM" SET COD_PAI = '103' WHERE COD_MENU_ITEM = 48;
UPDATE "WMS_ADM"."MENU_ITEM" SET COD_PAI = '103' WHERE COD_MENU_ITEM = 42;

UPDATE "WMS_ADM"."RECURSO" SET DSC_RECURSO = 'Cadastro de Veículos' WHERE COD_RECURSO = 347;

UPDATE "WMS_ADM"."RECURSO_ACAO" SET COD_ACAO = 8, DSC_RECURSO_ACAO = 'Visualizar' WHERE COD_RECURSO_ACAO = 621;
UPDATE "WMS_ADM"."RECURSO_ACAO" SET COD_ACAO = 5, DSC_RECURSO_ACAO = 'Início' WHERE COD_RECURSO_ACAO = 624;
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, 347, 1, 'Adicionar');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, 347, 2, 'Editar');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, 347, 4, 'Deletar');


COMMIT;


-- revisao 2012.02.24 Altero todos os depositos para ativo
update deposito set ind_ativo = 'S';
COMMIT;

INSERT INTO acao (cod_acao, dsc_acao, nom_acao)  VALUES (18, 'desativar', 'Desativar');
INSERT INTO acao (cod_acao, dsc_acao, nom_acao)  VALUES (19, 'ativar', 'Ativar');

INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, 37, 18, 'Desativar');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, 37, 19, 'Ativar');

-- atualizo filiais para ativo (tenho que checar os codigos de recursos antes de executar)
update filial set ind_ativo = 'S';

INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, 577, 18, 'Desativar');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, 577, 19, 'Ativar');

COMMIT;

-- 2012.02.28 atualizo codigo do item do menu produto
update menu_item set cod_recurso_acao = 809 where cod_menu_item = 38;
commit;

--2012.02.28 criacao da permissao de alteracao do produto
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, 58, 2, 'Editar');
commit;

--2012.03.01 alteracao do MENU_ITM para o menu apontar para o conteoller correto
UPDATE menu_item SET cod_recurso_acao = 772 WHERE cod_menu_item = 22;
commit;


--- cobrar do fabio a dml que troca o nome do campo "peso" por "capacidade" na tabela veiculo
ALTER TABLE VEICULO CHANGE PESO_VEICULO CAPACIDADE_VEICULO NUMBER(15,2) NOT NULL;
COMMENT ON COLUMN VEICULO.CAPACIDADE_VEICULO IS 'Capacidade de Carga do Veículo (em Kg)';

--- tornar o campo placa unico

CREATE  UNIQUE INDEX IX_VEICU_01 ON VEICULO (PLACA_VEICULO  ASC);
commit;
