DROP SEQUENCE SQ_AJUDA_INDICE_01;

DROP TABLE AJUDA_INDICE CASCADE CONSTRAINTS PURGE;
DROP TABLE AJUDA CASCADE CONSTRAINTS PURGE;


CREATE TABLE AJUDA
(
	COD_AJUDA  NUMBER(8)  NOT NULL ,
	DSC_AJUDA  VARCHAR2(60 BYTE)  NULL ,
	NUM_PESO  NUMBER(2)  NULL ,
	DSC_CONTEUDO  CLOB  NULL ,
	COD_AJUDA_PAI  NUMBER(8)  NULL ,
	COD_RECURSO_ACAO  NUMBER(8)  NULL 
);
COMMENT ON COLUMN AJUDA.COD_AJUDA IS 'Código da Ajuda (código sequêncial para a ajuda)';
COMMENT ON COLUMN AJUDA.DSC_AJUDA IS 'Descrição da Ajuda';
COMMENT ON COLUMN AJUDA.COD_PESO IS 'Código do Peso';
COMMENT ON COLUMN AJUDA.DSC_CONTEUDO IS 'Conteúdo da explicação sobre a funcionalidade';
COMMENT ON COLUMN AJUDA.COD_AJUDA_PAI IS 'Código da Ajuda (código ajuda do registro pai)';
COMMENT ON COLUMN AJUDA.COD_RECURSO_ACAO IS 'Código do Recurso Ação (código sequêncial para o recurso ação)';

CREATE  UNIQUE INDEX PK_AJUDA ON AJUDA
(
	COD_AJUDA  ASC
);

CREATE INDEX FK_AJUDA_AJUDA ON AJUDA
(
	COD_AJUDA_PAI  ASC
);

CREATE INDEX FK_AJUD_RECAC ON AJUDA
(
	COD_RECURSO_ACAO  ASC
);

ALTER TABLE AJUDA ADD CONSTRAINT  PK_AJUDA PRIMARY KEY (COD_AJUDA);
ALTER TABLE AJUDA ADD CONSTRAINT  FK_AJUDA_AJUDA FOREIGN KEY (COD_AJUDA_PAI) REFERENCES AJUDA(COD_AJUDA);
ALTER TABLE AJUDA ADD CONSTRAINT  FK_AJUD_RECAC FOREIGN KEY (COD_RECURSO_ACAO) REFERENCES RECURSO_ACAO(COD_RECURSO_ACAO) ON DELETE SET NULL;


-- revision 2012.03.05 feita por Augusto (tem que verificar esses valores antes de rodar na producao)

INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, 657, 1, 'Adicionar');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, 657, 2, 'Editar');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, 657, 4, 'Deletar');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, 657, 5, 'Iniciar');
commit;

INSERT INTO MENU_ITEM (COD_MENU_ITEM, COD_RECURSO_ACAO, COD_PAI, DSC_MENU_ITEM, NUM_PESO, DSC_URL) VALUES (SQ_MENU_ITEM_01.NEXTVAL, 813, 3, 'Ajuda', 10, '0');
commit;

--revision 2012.05.03 feita por Renato Medina
INSERT INTO RECURSO (COD_RECURSO, DSC_RECURSO, COD_RECURSO_PAI, NOM_RECURSO) VALUES (SQ_RECURSO_01.NEXTVAL, 'Embalagens dos Produtos', 0, 'produto-embalagem');
INSERT INTO RECURSO (COD_RECURSO, DSC_RECURSO, COD_RECURSO_PAI, NOM_RECURSO) VALUES (SQ_RECURSO_01.NEXTVAL, 'Volumes dos Produtos', 0, 'produto-volume');

-- revision 2012.03.07 add produto recurso acao 
INSERT INTO recurso_acao (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, 58, 5, 'Acessar');

-- revision 2012.03.09 alterar nome de tabela
ALTER TABLE ANDAMENTO_RECEBIMENTO RENAME TO RECEBIMENTO_ANDAMENTO;

INSERT INTO recurso_acao (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL , 639, 4, 'Cancelar');

INSERT INTO acao (COD_ACAO, DSC_ACAO, NOM_ACAO) VALUES (20, 'iniciar', 'INICIAR');

INSERT INTO recurso_acao (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL , 639, 20, 'Iniciar Recebimento');

INSERT INTO acao (COD_ACAO, DSC_ACAO, NOM_ACAO) VALUES (21, 'conferencia-cega', 'Conferencia Cega');

INSERT INTO recurso_acao (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL , 639, 21, 'Conferencia Cega');

-- revision 2012-03-12 corrigir problema do campo nome/descriacao da tabela acao

ALTER TABLE ACAO MODIFY(NOM_ACAO VARCHAR2(30 BYTE));
ALTER TABLE ACAO ADD (TMP_NOM_ACAO CHAR(30 BYTE) );
UPDATE ACAO SET TMP_NOM_ACAO = NOM_ACAO;
UPDATE ACAO SET NOM_ACAO = DSC_ACAO;
UPDATE ACAO SET DSC_ACAO = TMP_NOM_ACAO;
ALTER TABLE ACAO DROP COLUMN TMP_NOM_ACAO;

-- revision 2012-03-12 novas acoes para recebimento
INSERT INTO acao (COD_ACAO, NOM_ACAO, DSC_ACAO) VALUES (22, 'finalizar', 'Finalizar');

INSERT INTO recurso_acao (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL , 639, 22, 'Finalizar Recebimento');

INSERT INTO acao (COD_ACAO, NOM_ACAO, DSC_ACAO) VALUES (23, 'conferencia', 'Conferencia');

INSERT INTO recurso_acao (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL , 639, 23, 'Conferencia');

INSERT INTO acao (COD_ACAO, NOM_ACAO, DSC_ACAO) VALUES (24, 'view-conferencia', 'Visualizar Conferencia');

INSERT INTO recurso_acao (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL , 639, 24, 'Visualizar Conferencia');

-- revision 2012-03-12 Fabio alteração tabela
ALTER TABLE CONFERENCIA_RECEBIMENTO RENAME TO RECEBIMENTO_CONFERENCIA;

ALTER TABLE RECEBIMENTO_CONFERENCIA RENAME COLUMN COD_CONFERENCIA_RECEBIMENTO TO COD_RECEBIMENTO_CONFERENCIA;

DROP SEQUENCE SQ_CONFERENCIA_RECEBIMENTO_01;
CREATE SEQUENCE SQ_RECEBIMENTO_CONFERENCIA_01
  START WITH 17
  MAXVALUE 99999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

-- revision 2012-03-16
INSERT INTO recurso_acao (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL , 6, 18, 'Desativar Usuário');

-- revision 2012-03-14 Adriano - Criada tela Sistemas->Configurações
INSERT INTO RECURSO (COD_RECURSO, DSC_RECURSO, COD_RECURSO_PAI, NOM_RECURSO) VALUES (SQ_RECURSO_01.NEXTVAL, 'Alterar Parametros do Sistema', 297, 'configuracao');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, 777, 5, 'Início');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, 777, 2, 'Editar');
INSERT INTO MENU_ITEM (COD_MENU_ITEM, COD_RECURSO_ACAO, COD_PAI, DSC_MENU_ITEM, NUM_PESO, DSC_URL) VALUES (SQ_MENU_ITEM_01.NEXTVAL, 823, 13, 'Configurações', 10, '#');


-- revision 2012-03-19 Adriano - Alterada descrição do item no menu Cadastros -> Produto -> Produto;
-- Verificar o COD_MENU_ITEM na hora de aplicar o update.
UPDATE "WMS_ADM"."MENU_ITEM" SET DSC_MENU_ITEM = 'Dados Logísticos' WHERE COD_MENU_ITEM = 38;


INSERT INTO acao (COD_ACAO, NOM_ACAO, DSC_ACAO) VALUES (25, 'bloquear', 'Bloquear');
INSERT INTO acao (COD_ACAO, NOM_ACAO, DSC_ACAO) VALUES (26, 'desbloquear', 'Desbloquear');

INSERT INTO recurso_acao (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL , 337, 25, 'Bloquear');
INSERT INTO recurso_acao (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL , 337, 26, 'Desbloquear');

-- revision 2012-03-20 Adicionado couna de valor do parametro (Fabio tem que revisar o comando)
ALTER TABLE PARAMETRO ADD DSC_VALOR_PARAMETRO VARCHAR2(120 BYTE) NULL;
COMMENT ON COLUMN PARAMETRO.DSC_VALOR_PARAMETRO IS 'Descricao do Valor do Parametro';

UPDATE PARAMETRO P SET P.DSC_VALOR_PARAMETRO = (SELECT PV.DSC_VALOR_PARAMETRO FROM PARAMETRO_VALOR PV WHERE P.COD_PARAMETRO = PV.COD_PARAMETRO);

DROP TABLE PARAMETRO_VALOR CASCADE CONSTRAINTS PURGE;

INSERT INTO CONTEXTO_PARAMETRO (COD_CONTEXTO_PARAMETRO, DSC_CONTEXTO_PARAMETRO) VALUES (3, 'DEPOSITO');

INSERT INTO PARAMETRO (COD_PARAMETRO, COD_CONTEXTO_PARAMETRO, DSC_PARAMETRO, DSC_TITULO_PARAMETRO, IND_PARAMETRO_SISTEMA, COD_TIPO_ATRIBUTO, DSC_VALOR_PARAMETRO)
VALUES (SQ_PARAMETRO_01.NEXTVAL, 3, 'FORMATO_MASCARA_ENDERECO', 'Formato da mascara de Endereços', 'N', 'A', '00.000.00.00');

ALTER TABLE VEICULO ADD IND_FROTA_PROPRIA CHAR(1 BYTE) DEFAULT 'S' NOT NULL;
COMMENT ON COLUMN VEICULO.IND_FROTA_PROPRIA IS 'Indicativo se o veiculo é frota propria';

ALTER TABLE TIPO_VEICULO DROP COLUMN NOM_TIPO_VEICULO CASCADE CONSTRAINTS;
ALTER TABLE TIPO_EST_ARMAZ DROP COLUMN NOM_TIPO_EST_ARMAZ CASCADE CONSTRAINTS;
ALTER TABLE TIPO_NOTA_ENTRADA DROP COLUMN NOM_TIPO_NOTA_ENTRADA CASCADE CONSTRAINTS;
ALTER TABLE TIPO_PEDIDO_EXPEDICAO DROP COLUMN NOM_TIPO_PEDIDO_EXPEDICAO CASCADE CONSTRAINTS;
ALTER TABLE MOTIVO_DIVER_RECEB DROP COLUMN NOM_MOTIVO_DIVER_RECEB CASCADE CONSTRAINTS;

ALTER TABLE PRODUTO MODIFY (NUM_VOLUMES NUMBER(8) DEFAULT 0);
ALTER TABLE PRODUTO MODIFY (NUM_VOLUMES NUMBER(8) NULL);

ALTER TABLE UNITIZADOR RENAME COLUMN NUM_PESO TO NUM_PESO_OLD;
ALTER TABLE PRODUTO_VOLUME RENAME COLUMN NUM_PESO TO NUM_PESO_OLD;
ALTER TABLE VEICULO RENAME COLUMN NUM_CAPACIDADE_VEICULO TO NUM_CAPACIDADE_VEICULO_OLD;

ALTER TABLE UNITIZADOR ADD (NUM_PESO NUMBER(15,3));
ALTER TABLE PRODUTO_VOLUME ADD (NUM_PESO NUMBER(15,3));
ALTER TABLE VEICULO ADD (NUM_CAPACIDADE_VEICULO NUMBER(15,3));

UPDATE UNITIZADOR SET NUM_PESO = NUM_PESO;
UPDATE PRODUTO_VOLUME SET NUM_PESO = NUM_PESO_OLD;
UPDATE VEICULO SET NUM_CAPACIDADE_VEICULO = NUM_CAPACIDADE_VEICULO_OLD;

ALTER TABLE UNITIZADOR DROP COLUMN NUM_PESO_OLD CASCADE CONSTRAINTS;
ALTER TABLE PRODUTO_VOLUME DROP COLUMN NUM_PESO_OLD CASCADE CONSTRAINTS;
ALTER TABLE VEICULO DROP COLUMN NUM_CAPACIDADE_VEICULO_OLD CASCADE CONSTRAINTS;

ALTER TABLE NOTA_FISCAL MODIFY (COD_RECEBIMENTO VARCHAR2(20) NULL);



-- revision 2012-04-04 Adicionando recurso nota fiscal
INSERT INTO RECURSO (COD_RECURSO, DSC_RECURSO, COD_RECURSO_PAI, NOM_RECURSO) VALUES (SQ_RECURSO_01.NEXTVAL, 'Nota Fiscal', 0, 'consulta_nota-fiscal');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'consulta_nota-fiscal'), 5, 'Início');
INSERT INTO MENU_ITEM (COD_MENU_ITEM, COD_RECURSO_ACAO, COD_PAI, DSC_MENU_ITEM, NUM_PESO, DSC_URL) VALUES (SQ_MENU_ITEM_01.NEXTVAL, (SELECT COD_RECURSO_ACAO FROM RECURSO_ACAO WHERE COD_RECURSO  = (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'consulta_nota-fiscal') AND COD_ACAO = 5), 44, 'Nota Fiscal', 10, '#');

-- revision 2012-04-17 Relatorios > Planilhas
INSERT INTO MENU_ITEM (COD_MENU_ITEM, COD_RECURSO_ACAO, COD_PAI, DSC_MENU_ITEM, NUM_PESO, DSC_URL) VALUES (SQ_MENU_ITEM_01.NEXTVAL, 0, 54, 'Planilhas', 1, '0');

INSERT INTO RECURSO (COD_RECURSO, DSC_RECURSO, COD_RECURSO_PAI, NOM_RECURSO) VALUES (SQ_RECURSO_01.NEXTVAL, 'Planilha de Movimentação de Entrada e Saida', 0, 'planilha_mov-entrada-saida');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'planilha_mov-entrada-saida'), 5, 'Início');

INSERT INTO MENU_ITEM (COD_MENU_ITEM, COD_RECURSO_ACAO, COD_PAI, DSC_MENU_ITEM, NUM_PESO, DSC_URL, DSC_TARGET) VALUES (SQ_MENU_ITEM_01.NEXTVAL, 
    (SELECT COD_RECURSO_ACAO FROM RECURSO_ACAO WHERE COD_RECURSO = (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'planilha_mov-entrada-saida') AND COD_ACAO = 5), 
    (SELECT COD_MENU_ITEM FROM MENU_ITEM WHERE DSC_MENU_ITEM = 'Planilhas'), 'Cont. Movi. Entrada/Saida', 10, '0', '_blank');


-- revision 2012-04-19 Gerar Recebimento
INSERT INTO ACAO (COD_ACAO, DSC_ACAO, NOM_ACAO) VALUES (27, 'Gerar', 'gerar');

INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, 638, 27, 'Gerar Recebimento');

INSERT INTO MENU_ITEM (COD_MENU_ITEM, COD_RECURSO_ACAO, COD_PAI, DSC_MENU_ITEM, NUM_PESO, DSC_URL) VALUES (SQ_MENU_ITEM_01.NEXTVAL, 
    (SELECT COD_RECURSO_ACAO FROM RECURSO_ACAO WHERE COD_RECURSO = 638 AND COD_ACAO = 27), 
    49, 'Gerar Recebimento', 9, '0');

ALTER TABLE VEICULO DROP PRIMARY KEY CASCADE  DROP INDEX;
ALTER TABLE VEICULO ADD CONSTRAINT  PK_VEICU PRIMARY KEY (DSC_PLACA_VEICULO);
ALTER TABLE NOTA_FISCAL    ADD (DSC_PLACA_VEICULO VARCHAR2(10 BYTE) );
ALTER TABLE NOTA_FISCAL ADD CONSTRAINT  FK_NOFIS_VEICU FOREIGN KEY (DSC_PLACA_VEICULO) REFERENCES VEICULO(DSC_PLACA_VEICULO) ON DELETE SET NULL;




ALTER TABLE VEICULO DROP COLUMN COD_VEICULO CASCADE CONSTRAINTS;

INSERT INTO VEICULO
  (DSC_VEICULO, DSC_PLACA_VEICULO, COD_TIPO_VEICULO, COD_TRANSPORTADOR, IND_FROTA_PROPRIA)
VALUES
  ('PADRAO NOTA FISCAL', 'AAA0000', 1, 31, 'S');

INSERT INTO PARAMETRO 
  (COD_PARAMETRO, COD_CONTEXTO_PARAMETRO, DSC_PARAMETRO, DSC_TITULO_PARAMETRO, IND_PARAMETRO_SISTEMA, COD_TIPO_ATRIBUTO, DSC_VALOR_PARAMETRO)
VALUES
  (SQ_PARAMETRO_01.NEXTVAL, 5, 'PLACA_PADRAO_NOTAFISCAL', 'Placa Padrao Para Notas Fiscais', 'S', 'A', 'AAA0000');

-- alterando transportador de lugar 
UPDATE RECURSO SET NOM_RECURSO = 'consulta_transportador' WHERE NOM_RECURSO = 'transportador';

-- alterar tabela trasportador
ALTER TABLE TRANSPORTADOR ADD (IND_ATIVO CHAR(1 BYTE) DEFAULT  'S');
ALTER TABLE TRANSPORTADOR ADD (COD_TRANSPORTADOR_INTEGRACAO VARCHAR2(20) );
ALTER TABLE TRANSPORTADOR RENAME COLUMN COD_PESSOA TO COD_TRANSPORTADOR;

-- revision 2012-03-19 Adriano - Cadastros de Endereços do Depósito
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL , 337, 18, 'Desativar');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL , 337, 19, 'Ativar');

ALTER TABLE RECEBIMENTO_ANDAMENTO ADD (DSC_OBSERVACAO VARCHAR2(255 BYTE));
ALTER TABLE UNITIZADOR RENAME COLUMN NUM_PESO TO NUM_CAPACIDADE_VEICULO;

ALTER TABLE UNITIZADOR RENAME COLUMN NUM_DIM_LARGURA TO NUM_LARGURA_UNITIZADOR;
ALTER TABLE UNITIZADOR RENAME COLUMN NUM_DIM_ALTURA TO NUM_ALTURA_UNITIZADOR;
ALTER TABLE UNITIZADOR RENAME COLUMN NUM_DIM_PROFUNDIDADE TO NUM_PROFUNDIDADE_UNITIZADOR;
ALTER TABLE UNITIZADOR RENAME COLUMN NUM_CAPACIDADE_VEICULO TO NUM_CAPACIDADE_UNITIZADOR;
ALTER TABLE UNITIZADOR MODIFY(NUM_CAPACIDADE_UNITIZADOR NUMBER(15,3));

ALTER TABLE TIPO_ENDERECO RENAME COLUMN NUM_DIM_ALTURA TO NUM_ALTURA_ENDERECO;
ALTER TABLE TIPO_ENDERECO RENAME COLUMN NUM_DIM_LARGURA TO NUM_LARGURA_ENDERECO;
ALTER TABLE TIPO_ENDERECO RENAME COLUMN NUM_DIM_PROFUNDIDADE TO NUM_PROFUNDIDADE_ENDERECO;
ALTER TABLE TIPO_ENDERECO RENAME COLUMN NUM_CUBAGEM_UTIL TO NUM_CUBAGEM_ENDERECO;
ALTER TABLE TIPO_ENDERECO RENAME COLUMN NUM_PESO TO NUM_CAPACIDADE_ENDERECO;

ALTER TABLE TIPO_ENDERECO ADD NUM_CAP NUMBER(15,3);
UPDATE TIPO_ENDERECO SET NUM_CAP = NUM_CAPACIDADE_ENDERECO;

ALTER TABLE TIPO_ENDERECO DROP COLUMN NUM_CAPACIDADE_ENDERECO;
ALTER TABLE TIPO_ENDERECO RENAME COLUMN NUM_CAP TO NUM_CAPACIDADE_ENDERECO;

--revision 2012-05-07 adicionado busca de notas

INSERT INTO ACAO (COD_ACAO, DSC_ACAO, NOM_ACAO) VALUES (28, 'Buscar Notas', 'buscar-nota');

UPDATE RECURSO_ACAO SET COD_RECURSO = 639, COD_ACA0 = 28 WHERE COD_RECURSO = 638 AND COD_ACAO = 27;

INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, 639, 28, 'Buscar Notas');

UPDATE MENU_ITEM SET COD_RECURSO_ACAO = (SELECT COD_RECURSO_ACAO FROM RECURSO_ACAO WHERE COD_RECURSO = 639 AND COD_ACAO = 28) 
WHERE COD_RECURSO_ACAO = (SELECT COD_RECURSO_ACAO FROM RECURSO_ACAO WHERE COD_RECURSO = 639 AND COD_ACAO = 27);

--revision 2012-05-08 Adriano - sequence de recebimento
CREATE SEQUENCE SQ_RECEBIMENTO_01
  START WITH 1
  MAXVALUE 99999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


--revision 2012-05-09 Adriano - SIGLA de recebimento  
INSERT INTO SIGLA (COD_SIGLA, COD_TIPO_SIGLA, DSC_SIGLA, COD_REFERENCIA_SIGLA) VALUES (SQ_SIGLA_01.NEXTVAL, 50, 'CRIADO', 'CR');
UPDATE RECEBIMENTO SET COD_STATUS = 454 WHERE COD_STATUS = 459;
UPDATE RECEBIMENTO_ANDAMENTO SET COD_TIPO_ANDAMENTO = 454 WHERE COD_TIPO_ANDAMENTO = 459;

ALTER TABLE PRODUTO_EMBALAGEM DROP CONSTRAINT FK_PROEM_PRODU;
ALTER TABLE PRODUTO_VOLUME    DROP CONSTRAINT FK_PROVO_PRODU;
ALTER TABLE NOTA_FISCAL_ITEM  DROP CONSTRAINT FK_NFISI_PRODU;

ALTER TABLE PRODUTO           DROP PRIMARY KEY CASCADE  DROP INDEX;

DROP INDEX FK_PROEM_PRODU;
DROP INDEX FK_PROVO_PRODU;


ALTER TABLE VEICULO DROP COLUMN IND_FROTA_PROPRIA CASCADE CONSTRAINTS;

ALTER TABLE PRODUTO MODIFY (DSC_GRADE VARCHAR2(10 BYTE) NOT NULL);

CREATE  UNIQUE INDEX PK_PRODU ON PRODUTO
(
	COD_PRODUTO  ASC,
	DSC_GRADE  ASC
);

DELETE FROM nota_fiscal;
DELETE FROM nota_fiscal_item;

ALTER TABLE PRODUTO_EMBALAGEM ADD DSC_GRADE  VARCHAR2(10 BYTE)  NOT NULL;
ALTER TABLE PRODUTO_VOLUME    ADD DSC_GRADE  VARCHAR2(10 BYTE)  NOT NULL;
ALTER TABLE NOTA_FISCAL_ITEM  ADD DSC_GRADE  VARCHAR2(10 BYTE)  NOT NULL;

CREATE INDEX FK_PROEM_PRODU ON PRODUTO_EMBALAGEM
(
	COD_PRODUTO  ASC,
	DSC_GRADE  ASC
);

CREATE INDEX FK_PROVO_PRODU ON PRODUTO_VOLUME
(
	COD_PRODUTO  ASC,
	DSC_GRADE  ASC
);

CREATE INDEX FK_NFISI_PRODU ON NOTA_FISCAL_ITEM
(
	COD_PRODUTO  ASC,
	DSC_GRADE  ASC
);




ALTER TABLE PRODUTO              ADD CONSTRAINT  PK_PRODU PRIMARY KEY (COD_PRODUTO,DSC_GRADE);
ALTER TABLE PRODUTO_EMBALAGEM    ADD CONSTRAINT  FK_PROEM_PRODU FOREIGN KEY (COD_PRODUTO,DSC_GRADE) REFERENCES PRODUTO(COD_PRODUTO,DSC_GRADE) ON DELETE CASCADE;
ALTER TABLE PRODUTO_VOLUME       ADD CONSTRAINT  FK_PROVO_PRODU FOREIGN KEY (COD_PRODUTO,DSC_GRADE) REFERENCES PRODUTO(COD_PRODUTO,DSC_GRADE) ON DELETE CASCADE;
ALTER TABLE NOTA_FISCAL_ITEM     ADD CONSTRAINT  FK_NFISI_PRODU FOREIGN KEY (COD_PRODUTO,DSC_GRADE) REFERENCES PRODUTO(COD_PRODUTO,DSC_GRADE);



COMMENT ON COLUMN UNITIZADOR.NUM_CAPACIDADE_UNITIZADOR IS 'Número peso (capacidade de peso é em kg)';
COMMENT ON COLUMN PRODUTO.NUM_VOLUMES IS 'Número de volumes que este produto possui';
COMMENT ON COLUMN PRODUTO_EMBALAGEM.COD_PRODUTO_EMBALAGEM IS 'Código Produto Embalagem (código sequencial)';
COMMENT ON COLUMN PRODUTO_EMBALAGEM.DSC_EMBALAGEM IS 'Descrição (nome) da embalagem';
COMMENT ON COLUMN PRODUTO_EMBALAGEM.QTD_EMBALAGEM IS 'Quantidade de itens esta embalagem contém';
COMMENT ON COLUMN PRODUTO_EMBALAGEM.IND_PADRAO IS 'se a embalagem é padrão ou não (S - Sim/ N - Não)';
COMMENT ON COLUMN PRODUTO_EMBALAGEM.COD_BARRAS IS 'Código de barras da embalagem';
COMMENT ON COLUMN PRODUTO_EMBALAGEM.COD_PRODUTO IS 'Código do Produto';
COMMENT ON COLUMN PRODUTO_EMBALAGEM.DSC_GRADE IS 'Descrição da Grade (cor)';
COMMENT ON COLUMN PRODUTO_VOLUME.COD_PRODUTO_VOLUME IS 'Código produto volume (código sequêncial para o produto volume)';
COMMENT ON COLUMN PRODUTO_VOLUME.NUM_ALTURA IS 'Altura do volume';
COMMENT ON COLUMN PRODUTO_VOLUME.NUM_LARGURA IS 'Largura do volume';
COMMENT ON COLUMN PRODUTO_VOLUME.NUM_PROFUNDIDADE IS 'Profundidade do volume';
COMMENT ON COLUMN PRODUTO_VOLUME.NUM_CUBAGEM IS 'Cubagem do volume';
COMMENT ON COLUMN PRODUTO_VOLUME.COD_BARRAS IS 'Código de barras do volume';
COMMENT ON COLUMN PRODUTO_VOLUME.COD_SEQUENCIAL_VOLUME IS 'Código do volume';
COMMENT ON COLUMN PRODUTO_VOLUME.COD_PRODUTO IS 'Código do Produto';
COMMENT ON COLUMN PRODUTO_VOLUME.NUM_PESO IS 'Peso do volume';
COMMENT ON COLUMN PRODUTO_VOLUME.DSC_GRADE IS 'Descrição da Grade (cor)';
COMMENT ON COLUMN VEICULO.NUM_CAPACIDADE_VEICULO IS 'Capacidade de Carga do Veículo (em Kg)';
COMMENT ON COLUMN TIPO_ENDERECO.NUM_CAPACIDADE_ENDERECO IS 'Número peso (capacidade de peso é em kg)';
COMMENT ON COLUMN RECEBIMENTO_ANDAMENTO.COD_USUARIO IS 'Código do Usuário que realizou o Andamento do Recebimento (Criou, Fechou, Cancelou, etc)';
COMMENT ON TABLE NOTA_FISCAL_ITEM IS 'Cadastra o item (produto) da nota fiscal.';
COMMENT ON COLUMN NOTA_FISCAL_ITEM.COD_PRODUTO IS 'Código do Produto';
COMMENT ON COLUMN NOTA_FISCAL_ITEM.QTD_ITEM IS 'Quatidade Item (quantidade de cada produto)';
COMMENT ON COLUMN NOTA_FISCAL_ITEM.COD_NOTA_FISCAL_ITEM IS 'Código Nota Fiscal Item (código sequêncial para a nota fiscal item)';
COMMENT ON COLUMN NOTA_FISCAL_ITEM.DSC_GRADE IS 'Descrição da Grade (cor)';
COMMENT ON COLUMN MENU_ITEM.COD_RECURSO_ACAO IS 'Código do Recurso Ação (não há FK, pois nem todos Recursos Ação são itens de menu)';
COMMENT ON COLUMN MENU_ITEM.COD_PAI IS 'Código do Item do Menu Pai (hierarquia)';

ALTER TABLE NOTA_FISCAL_ITEM DROP COLUMN DSC_GRADE_PRODUTO CASCADE CONSTRAINTS;

INSERT INTO recurso_acao (cod_recurso_acao, cod_recurso, cod_acao, dsc_recurso_acao) values (823, 778, 5, 'Início');

UPDATE PARAMETRO SET DSC_VALOR_PARAMETRO = (SELECT COD_PERFIL_USUARIO FROM PERFIL_USUARIO WHERE NOM_PERFIL_USUARIO = 'ADMIN') WHERE DSC_PARAMETRO = 'COD_PERFIL_ADM_SISTEMA';

DELETE FROM recurso_acao where cod_recurso_acao = 800;

DELETE FROM recurso_acao where cod_recurso_Acao = 814;

INSERT INTO recurso_acao (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, 639, 8, 'View Conferencia');
INSERT INTO recurso_acao (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, 639, 27, 'Gravar Recebimento');

ALTER TABLE PRODUTO RENAME COLUMN COD_TIPO_ARMAZENAGEM TO COD_TIPO_COMERCIALIZACAO;
COMMENT ON COLUMN PRODUTO.COD_TIPO_COMERCIALIZACAO IS 'Código do Tipo de Comercialização (unitário, composto ou kit)';


ALTER TABLE RECEBIMENTO_CONFERENCIA ADD DSC_GRADE VARCHAR2(10 BYTE);

COMMENT ON COLUMN RECEBIMENTO_CONFERENCIA.COD_PRODUTO IS 'Código do Produto';
COMMENT ON COLUMN RECEBIMENTO_CONFERENCIA.DSC_GRADE   IS 'Descrição da Grade (cor)';

CREATE INDEX FK_CONRE_PRODU ON RECEBIMENTO_CONFERENCIA
(
	COD_PRODUTO  ASC,
	DSC_GRADE  ASC
);
ALTER TABLE RECEBIMENTO_CONFERENCIA ADD CONSTRAINT FK_CONRE_PRODU FOREIGN KEY (COD_PRODUTO, DSC_GRADE) REFERENCES PRODUTO (COD_PRODUTO, DSC_GRADE);

-- #################################################################### DAQUI PRA CIMA JA FOI RODADO NA HOMOLOG PARA TESTES #################################################################### 
-- #################################################################### DAQUI PRA CIMA JA FOI RODADO NA PRODUCAO #################################################################### 

COMMIT;


