-- Gerado por Oracle SQL Developer Data Modeler 3.1.0.699
--   em:        2013-03-20 15:01:48 BRT
--   site:      Oracle Database 11g
--   tipo:      Oracle Database 11g



CREATE TABLE WMS_ADM.CARGA 
    ( 
     COD_CARGA NUMBER (8)  NOT NULL , 
     COD_CARGA_EXTERNO NUMBER (8)  NOT NULL , 
     COD_TIPO_CARGA NUMBER (8)  NOT NULL , 
     CENTRAL_ENTREGA NUMBER (8) , 
     DSC_PLACA_CARGA VARCHAR2 (40 BYTE) , 
     DSC_PLACA_EXPEDICAO VARCHAR2 (40 BYTE) , 
     DTH_FECHAMENTO DATE , 
     COD_EXPEDICAO NUMBER (8)  NOT NULL 
    ) 
        PCTFREE 10 
        PCTUSED 40 
        MAXTRANS 255 
        TABLESPACE TS_WSM_ADM_D 
        LOGGING 
        STORAGE ( 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
    ) 
;

CREATE SEQUENCE SQ_CARGA_01
	INCREMENT BY 1
	START WITH 1
	MAXVALUE 999999999999999999999999999
	MINVALUE 0
	NOCYCLE
	NOCACHE
	NOORDER
;

ALTER TABLE WMS_ADM.CARGA 
    ADD CONSTRAINT CARGA_PK PRIMARY KEY ( COD_CARGA  ) ;


CREATE TABLE WMS_ADM.EXPEDICAO 
    ( 
     COD_EXPEDICAO NUMBER (8)  NOT NULL , 
     DSC_PLACA_EXPEDICAO VARCHAR2 (30 BYTE) , 
     COD_STATUS NUMBER (8) , 
     DTH_INICIO DATE , 
     DTH_FINALIZACAO DATE , 
     COD_DEPOSITO NUMBER (8) ,
     COD_BOX VARCHAR2 (5 BYTE)
    ) 
        PCTFREE 10 
        PCTUSED 40 
        MAXTRANS 255 
        TABLESPACE TS_WSM_ADM_D 
        LOGGING 
        STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
    ) 
;

CREATE SEQUENCE SQ_EXPEDICAO_01
	INCREMENT BY 1
	START WITH 1
	MAXVALUE 999999999999999999999999999
	MINVALUE 0
	NOCYCLE
	NOCACHE
	NOORDER
;

ALTER TABLE WMS_ADM.EXPEDICAO 
    ADD CONSTRAINT EXPEDICAO_PK PRIMARY KEY ( COD_EXPEDICAO  ) ;


CREATE TABLE WMS_ADM.PEDIDO 
    ( 
     COD_PEDIDO NUMBER (8)  NOT NULL , 
     COD_TIPO_PEDIDO NUMBER (8) , 
     DSC_LINHA_ENTREGA VARCHAR2 (300 BYTE) , 
     COD_CARGA NUMBER (8)  NOT NULL ,
     DTH_CANCELAMENTO DATE,
     CENTRAL_ENTREGA NUMBER(8,0)
    ) 
        PCTFREE 10 
        PCTUSED 40 
        MAXTRANS 255 
        TABLESPACE TS_WSM_ADM_D 
        LOGGING 
        STORAGE ( 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
    ) 
;


ALTER TABLE WMS_ADM.PEDIDO 
    ADD CONSTRAINT PEDIDO_PK PRIMARY KEY ( COD_PEDIDO  ) ;


CREATE TABLE WMS_ADM.PEDIDO_PRODUTO
    ( 
     COD_PRODUTO VARCHAR2 (20 BYTE)  NOT NULL , 
     DSC_GRADE VARCHAR2 (10 BYTE)  NOT NULL , 
     COD_PEDIDO NUMBER (8)  NOT NULL ,
     COD_PEDIDO_PRODUTO NUMBER(8) NOT NULL,
     QUANTIDADE NUMBER(8)
    );

ALTER TABLE WMS_ADM.PEDIDO_PRODUTO
ADD CONSTRAINT PEDIDO_PRODUTO_PK PRIMARY KEY ("COD_PEDIDO_PRODUTO");


CREATE SEQUENCE SQ_PEDIDO_PRODUTO_01
INCREMENT BY 1
START WITH 1
MAXVALUE 999999999999999999999999999
MINVALUE 0
NOCYCLE
NOCACHE
NOORDER
;

ALTER TABLE WMS_ADM.CARGA 
    ADD CONSTRAINT CARGA_EXPEDICAO_FK FOREIGN KEY 
    ( 
     COD_EXPEDICAO
    ) 
    REFERENCES WMS_ADM.EXPEDICAO 
    ( 
     COD_EXPEDICAO
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE WMS_ADM.EXPEDICAO 
    ADD CONSTRAINT EXPEDICAO_BOX_FK FOREIGN KEY 
    ( 
     COD_BOX,
     COD_DEPOSITO
    ) 
    REFERENCES WMS_ADM.BOX 
    (
     COD_BOX,
     COD_DEPOSITO
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE WMS_ADM.PEDIDO 
    ADD CONSTRAINT PEDIDO_CARGA_FK FOREIGN KEY 
    ( 
     COD_CARGA
    ) 
    REFERENCES WMS_ADM.CARGA 
    ( 
     COD_CARGA
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE WMS_ADM.PEDIDO_PRODUTO
ADD CONSTRAINT PEDIDO_PRODUTO_FK FOREIGN KEY
    ( 
     COD_PEDIDO
    ) 
    REFERENCES WMS_ADM.PEDIDO 
    ( 
     COD_PEDIDO
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE WMS_ADM.PEDIDO_PRODUTO
    ADD CONSTRAINT PEDIDO_PRODUTO_PRODUTO_FK FOREIGN KEY
    ( 
     COD_PRODUTO,
     DSC_GRADE
    ) 
    REFERENCES WMS_ADM.PRODUTO 
    ( 
     COD_PRODUTO,
     DSC_GRADE
    ) 
    NOT DEFERRABLE 
;


-- Relatório do Resumo do Oracle SQL Developer Data Modeler:
-- 
-- CREATE TABLE                             4
-- CREATE INDEX                             0
-- CREATE VIEW                              0
-- ALTER TABLE                              8
-- DROP TABLE                               0
-- DROP INDEX                               0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- DROP VIEW                                0

-- 
-- ERRORS                                   0
-- WARNINGS                                 0
