ALTER TABLE PARAMETRO MODIFY(DSC_TITULO_PARAMETRO VARCHAR2 (300 CHAR));
INSERT INTO PARAMETRO (COD_PARAMETRO, COD_CONTEXTO_PARAMETRO, DSC_PARAMETRO, DSC_TITULO_PARAMETRO, IND_PARAMETRO_SISTEMA, COD_TIPO_ATRIBUTO, DSC_VALOR_PARAMETRO) VALUES (SQ_PARAMETRO_01.NEXTVAL, (SELECT COD_CONTEXTO_PARAMETRO FROM CONTEXTO_PARAMETRO WHERE DSC_CONTEXTO_PARAMETRO = 'ENDERECAMENTO'), 'TIPO_RESSUPRIMENTO', 'Tipo de Ressuprimento 1- Abastecer Capacidade do Picking, 2- Completar Picking)', 'N', 'A', 'S');

INSERT INTO TIPO_SIGLA (COD_TIPO_SIGLA, DSC_TIPO_SIGLA, IND_SIGLA_SISTEMA) VALUES (74, 'STATUS RESSUPRIMENTO', 'S');
INSERT INTO SIGLA (COD_SIGLA, COD_TIPO_SIGLA, DSC_SIGLA, COD_REFERENCIA_SIGLA) VALUES (540, (SELECT COD_TIPO_SIGLA FROM TIPO_SIGLA WHERE DSC_TIPO_SIGLA = 'STATUS RESSUPRIMENTO'), 'ONDA GERADA', 'G');
INSERT INTO SIGLA (COD_SIGLA, COD_TIPO_SIGLA, DSC_SIGLA, COD_REFERENCIA_SIGLA) VALUES (541, (SELECT COD_TIPO_SIGLA FROM TIPO_SIGLA WHERE DSC_TIPO_SIGLA = 'STATUS RESSUPRIMENTO'), 'FINALIZADO', 'F');

ALTER TABLE PRODUTO
  ADD (PONTO_REPOSICAO    NUMBER (8) DEFAULT '0',
       CAPACIDADE_PICKING NUMBER (8) DEFAULT '0');

CREATE TABLE RESERVA_ESTOQUE
(
  COD_RESERVA_ESTOQUE     NUMBER (8) NOT NULL ,
  COD_DEPOSITO_ENDERECO   NUMBER (8) NOT NULL ,
  COD_PRODUTO             VARCHAR2 (20 BYTE) NOT NULL ,
  DSC_GRADE               VARCHAR2 (10 BYTE) NOT NULL ,
  QTD_RESERVADA           NUMBER (8) NOT NULL ,
  TIPO_RESERVA            VARCHAR2 (1 CHAR) ,
  IND_ATENDIDA            VARCHAR2 (1 CHAR),
  COD_USUARIO             NUMBER (8) NOT NULL ,
  DTH_RESERVA             DATE,
  DTH_ATENDIMENTO         DATE,
  COD_USUARIO_ATENDIMENTO NUMBER (8),
  DSC_OBSERVACAO          VARCHAR2 (300 CHAR)
);

ALTER TABLE RESERVA_ESTOQUE ADD CONSTRAINT RESERVA_ESTOQUE_PK PRIMARY KEY (COD_RESERVA_ESTOQUE);
ALTER TABLE RESERVA_ESTOQUE ADD CONSTRAINT RES_EST_DEP_END_FK FOREIGN KEY (COD_DEPOSITO_ENDERECO) REFERENCES DEPOSITO_ENDERECO (COD_DEPOSITO_ENDERECO) NOT DEFERRABLE;
ALTER TABLE RESERVA_ESTOQUE ADD CONSTRAINT RES_EST_PROD_FK FOREIGN KEY (COD_PRODUTO, DSC_GRADE) REFERENCES PRODUTO (COD_PRODUTO,DSC_GRADE) NOT DEFERRABLE;
ALTER TABLE RESERVA_ESTOQUE ADD CONSTRAINT RES_EST_USU_FK FOREIGN KEY (COD_USUARIO) REFERENCES USUARIO (COD_USUARIO) NOT DEFERRABLE ;
ALTER TABLE RESERVA_ESTOQUE ADD CONSTRAINT RES_EST_USU_AT_FK FOREIGN KEY (COD_USUARIO_ATENDIMENTO) REFERENCES WMS_ADM.USUARIO (COD_USUARIO) NOT DEFERRABLE ;

CREATE SEQUENCE SQ_RESERVA_ESTOQUE
	INCREMENT BY 1
	START WITH 1
	MAXVALUE 999999999999999999999999999
	MINVALUE 0
	NOCYCLE
	NOCACHE
	NOORDER;

CREATE TABLE RESERVA_ESTOQUE_ENDERECAMENTO
(
  UMA                 NUMBER (8) NOT NULL,
  COD_RESERVA_ESTOQUE NUMBER (8) NOT NULL
);

ALTER TABLE RESERVA_ESTOQUE_ENDERECAMENTO ADD CONSTRAINT RES_EST_END_UMA_FK FOREIGN KEY (UMA) REFERENCES PALETE (UMA) NOT DEFERRABLE ;
ALTER TABLE RESERVA_ESTOQUE_ENDERECAMENTO ADD CONSTRAINT RES_EST_RES_EST_FK FOREIGN KEY (COD_RESERVA_ESTOQUE) REFERENCES RESERVA_ESTOQUE (COD_RESERVA_ESTOQUE) NOT DEFERRABLE ;

CREATE TABLE RESERVA_ESTOQUE_EXPEDICAO
(
  COD_EXPEDICAO       NUMBER (8) NOT NULL,
  COD_RESERVA_ESTOQUE NUMBER (8) NOT NULL
);

ALTER TABLE RESERVA_ESTOQUE_EXPEDICAO ADD CONSTRAINT RES_EST_EXP_EXP_FK FOREIGN KEY (COD_EXPEDICAO) REFERENCES EXPEDICAO (COD_EXPEDICAO) NOT DEFERRABLE ;
ALTER TABLE RESERVA_ESTOQUE_EXPEDICAO ADD CONSTRAINT RES_EST_EXP_RES_FK FOREIGN KEY (COD_RESERVA_ESTOQUE) REFERENCES RESERVA_ESTOQUE (COD_RESERVA_ESTOQUE) NOT DEFERRABLE ;

CREATE TABLE ONDA_RESSUPRIMENTO
(
  COD_ONDA_RESSUPRIMENTO NUMBER (8) NOT NULL,
  COD_USUARIO            NUMBER (8) NOT NULL,
  DTH_CRIACAO            DATE,
  DSC_OBSERVACAO        VARCHAR2 (300 CHAR)
);

ALTER TABLE ONDA_RESSUPRIMENTO ADD CONSTRAINT ONDA_RESSUPRIMENTO_PK PRIMARY KEY (COD_ONDA_RESSUPRIMENTO) ;
ALTER TABLE ONDA_RESSUPRIMENTO ADD CONSTRAINT OND_RES_USU_FK FOREIGN KEY (COD_USUARIO) REFERENCES USUARIO (COD_USUARIO) NOT DEFERRABLE ;

CREATE SEQUENCE SQ_ONDA_RESSUPRIMENTO
	INCREMENT BY 1
	START WITH 1
	MAXVALUE 999999999999999999999999999
	MINVALUE 0
	NOCYCLE
	NOCACHE
	NOORDER;

CREATE TABLE ONDA_RESSUPRIMENTO_PEDIDO
(
  COD_ONDA_RESSUPRIMENTO_PEDIDO  NUMBER (8) NOT NULL,
  COD_ONDA_RESSUPRIMENTO         NUMBER (8) NOT NULL,
  COD_PEDIDO                     NUMBER (8) NOT NULL,
  COD_PRODUTO                    VARCHAR2 (20 BYTE) NOT NULL ,
  DSC_GRADE                      VARCHAR2 (10 BYTE) NOT NULL ,
  QTD                            NUMBER (8) NOT NULL
);

ALTER TABLE ONDA_RESSUPRIMENTO_PEDIDO ADD CONSTRAINT ONDA_RESSUPRIMENTO_PEDIDO_PK PRIMARY KEY (COD_ONDA_RESSUPRIMENTO_PEDIDO) ;
ALTER TABLE ONDA_RESSUPRIMENTO_PEDIDO ADD CONSTRAINT OND_RES_PED_OND_RES_FK FOREIGN KEY (COD_ONDA_RESSUPRIMENTO) REFERENCES ONDA_RESSUPRIMENTO (COD_ONDA_RESSUPRIMENTO) NOT DEFERRABLE ;
ALTER TABLE ONDA_RESSUPRIMENTO_PEDIDO ADD CONSTRAINT OND_RES_PED_PED_FK FOREIGN KEY (COD_PEDIDO) REFERENCES PEDIDO (COD_PEDIDO) NOT DEFERRABLE ;
ALTER TABLE ONDA_RESSUPRIMENTO_PEDIDO ADD CONSTRAINT OND_RES_PED_PROD_FK FOREIGN KEY (COD_PRODUTO, DSC_GRADE) REFERENCES PRODUTO (COD_PRODUTO,DSC_GRADE) NOT DEFERRABLE;

CREATE SEQUENCE SQ_ONDA_RESSUPRIMENTO_PEDIDO
	INCREMENT BY 1
	START WITH 1
	MAXVALUE 999999999999999999999999999
	MINVALUE 0
	NOCYCLE
	NOCACHE
	NOORDER;

CREATE TABLE ONDA_RESSUPRIMENTO_OS
(
  COD_ONDA_RESSUPRIMENTO_OS      NUMBER (8) NOT NULL,
  COD_ONDA_RESSUPRIMENTO         NUMBER (8) NOT NULL,
  COD_PRODUTO                    VARCHAR2 (20 BYTE) NOT NULL ,
  DSC_GRADE                      VARCHAR2 (10 BYTE) NOT NULL ,
  QTD                            NUMBER (8) NOT NULL,
  COD_DEPOSITO_ENDERECO          NUMBER (8) NOT NULL,
  COD_STATUS                     NUMBER (8) NOT NULL,
  COD_OS                         NUMBER (8) NOT NULL
);

CREATE SEQUENCE SQ_ONDA_RESSUPRIMENTO_OS
	INCREMENT BY 1
	START WITH 1
	MAXVALUE 999999999999999999999999999
	MINVALUE 0
	NOCYCLE
	NOCACHE
	NOORDER;

ALTER TABLE ONDA_RESSUPRIMENTO_OS ADD CONSTRAINT ONDA_RESSUPRIMENTO_OS_PK PRIMARY KEY (COD_ONDA_RESSUPRIMENTO_OS) ;
ALTER TABLE ONDA_RESSUPRIMENTO_OS ADD CONSTRAINT OND_RES_OS_OND_RES_FK FOREIGN KEY (COD_ONDA_RESSUPRIMENTO) REFERENCES ONDA_RESSUPRIMENTO (COD_ONDA_RESSUPRIMENTO) NOT DEFERRABLE ;
ALTER TABLE ONDA_RESSUPRIMENTO_OS ADD CONSTRAINT OND_RES_OS_PROD_FK FOREIGN KEY (COD_PRODUTO, DSC_GRADE) REFERENCES PRODUTO (COD_PRODUTO,DSC_GRADE) NOT DEFERRABLE;
ALTER TABLE ONDA_RESSUPRIMENTO_OS ADD CONSTRAINT OND_RES_OS_DEP_END_FK FOREIGN KEY (COD_DEPOSITO_ENDERECO) REFERENCES DEPOSITO_ENDERECO (COD_DEPOSITO_ENDERECO) NOT DEFERRABLE ;
ALTER TABLE ONDA_RESSUPRIMENTO_OS ADD CONSTRAINT OND_RES_OS_OS_FK FOREIGN KEY (COD_OS) REFERENCES ORDEM_SERVICO (COD_OS) NOT DEFERRABLE ;
ALTER TABLE ONDA_RESSUPRIMENTO_OS ADD CONSTRAINT OND_RES_OS_SIGLA_FK FOREIGN KEY (COD_STATUS) REFERENCES SIGLA (COD_SIGLA) NOT DEFERRABLE ;

CREATE TABLE RESERVA_ESTOQUE_ONDA_RESSUP
(
  COD_ONDA_RESSUPRIMENTO_OS NUMBER (8) NOT NULL,
  COD_RESERVA_ESTOQUE            NUMBER (8) NOT NULL,
  COD_OS                         NUMBER (8) NOT NULL
);

ALTER TABLE RESERVA_ESTOQUE_ONDA_RESSUP ADD CONSTRAINT RES_EST_OND_RES_OND_OS_FK FOREIGN KEY (COD_ONDA_RESSUPRIMENTO_OS) REFERENCES ONDA_RESSUPRIMENTO_OS (COD_ONDA_RESSUPRIMENTO_OS) NOT DEFERRABLE ;
ALTER TABLE RESERVA_ESTOQUE_ONDA_RESSUP ADD CONSTRAINT RES_EST_OND_RES_RES_EST_FK FOREIGN KEY (COD_RESERVA_ESTOQUE) REFERENCES RESERVA_ESTOQUE (COD_RESERVA_ESTOQUE) NOT DEFERRABLE ;
ALTER TABLE RESERVA_ESTOQUE_ONDA_RESSUP ADD CONSTRAINT RES_EST_OND_RES_OS_FK FOREIGN KEY (COD_OS) REFERENCES ORDEM_SERVICO (COD_OS) NOT DEFERRABLE ;

INSERT INTO RECURSO (COD_RECURSO, DSC_RECURSO, COD_RECURSO_PAI, NOM_RECURSO) VALUES (SQ_RECURSO_01.NEXTVAL, 'Onda de Ressuprimento', 0, 'expedicao:onda-ressuprimento');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO)VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'expedicao:onda-ressuprimento'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'index'), 'Geração de Onda de Ressuprimento');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO)VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'expedicao:onda-ressuprimento'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'gerar'), 'Gerar de Onda de Ressuprimento');
INSERT INTO MENU_ITEM (COD_MENU_ITEM, COD_RECURSO_ACAO, COD_PAI, DSC_MENU_ITEM, NUM_PESO, DSC_URL, SHOW) VALUES (SQ_MENU_ITEM_01.NEXTVAL,(SELECT COD_RECURSO_ACAO FROM RECURSO_ACAO WHERE COD_RECURSO = (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'expedicao:onda-ressuprimento') AND COD_ACAO = (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'index')),(SELECT MIN(COD_MENU_ITEM) FROM MENU_ITEM WHERE DSC_MENU_ITEM = 'Expedição' AND COD_PAI = 0),'Gerar Onda de Ressuprimento',1,'#','S');

INSERT INTO ATIVIDADE (COD_ATIVIDADE, DSC_ATIVIDADE, COD_SETOR_OPERACIONAL) VALUES (13, 'RESSUPRIMENTO',1);
