<script>
    $(document).ready(function(){

        $(".select-praca").change(function(){
            idCliente = $($(this)).parent().siblings('.cliente').val();
            pracaSelecionada = $(this).attr('value');
            $('#'+idCliente).val(pracaSelecionada);
        });

    });
</script>

<?php
echo $this->form;
?>

<form action="<?php echo $this->url(array('module' => 'expedicao', 'controller' =>'cliente', 'action' =>'associar-praca' ))?>" method="post" id="frm-salvar-associar-praca">
    <table class="tabContainer" border="2px" style="width: 100%; border: 1px">
        <tr>
            <th></th>
            <th>Código</th>
            <th>Nome</th>
            <th>Cidade</th>
            <th>Bairro</th>
            <th>Praça</th>
            <th>UF</th>
        </tr>
        <?php if(isset($this->clientes)) : ?>

            <?php foreach($this->clientes as $cliente) : ?>
                <tr>
                    <td style="text-align: center"><a title="Visualizar detalhes do Endereço" target="_blank" href="<?php echo $this->url(array('module' => 'expedicao', 'controller' =>'cliente', 'action' =>'consultar', 'codCliente' =>  $cliente['id']))?>" ><img alt="Opções" src="/img/icons/zoom.png"></li></a></td>
                    <td style="padding-left: 1px"><?php echo $cliente['id']; ?></td>
                    <td style="padding-left: 1px"><?php echo $cliente['nome']; ?></td>
                    <td style="padding-left: 1px"><?php echo $cliente['cidade']; ?></td>
                    <td style="padding-left: 1px"><?php echo $cliente['bairro']; ?></td>
                    <td>
                        <select class="select-praca" style="width: 100%">
                            <?php foreach($this->pracas as $key => $praca) : ?>

                                <?php if($cliente['praca'] == $key) : ?>
                                    <option value="<?php echo $key; ?>" selected><?php echo $praca; ?></option>
                                    <?php else : ?>
                                    <option value="<?php echo $key; ?>" ><?php echo $praca; ?></option>
                                <?php endif; ?>

                            <?php endforeach; ?>
                        </select>

                    </td>
                    <td style="text-align: center"><?php echo $cliente['estado']; ?></td>

                    <input type="hidden" class="cliente" value="<?php echo $cliente['id']; ?>" name="<?php echo $cliente['id'] ?>[id]" />
                    <input type="hidden" class="pracaId" id="<?php echo $cliente['id']; ?>" value="<?php echo $cliente['praca']; ?>" name="<?php echo $cliente['id'] ?>[pracaId]" value="<?php echo $cliente['praca']; ?>"/>
                </tr>

            <?php endforeach; ?>

        <?php endif; ?>
    </table>

    <br />
    <button type="submit">Salvar</button>
</form>