<script>
    $(document).ready(function(){

        $(".select-praca").change(function(){
            idCliente = $($(this)).parent().siblings('.cliente').val();
            pracaSelecionada = $(this).attr('value');
            $('#'+idCliente).val(pracaSelecionada);
        });

        $("a[rel=modal]").click (function(a){
            a.preventDefault();
            $.wmsDialogAjax({
                width: 800,
                height: 500,
                url: this.href,
                title: $(this).html()
            })
        });
    });

</script>

<?php
echo $this->form;

$i = 0;
?>

<form action="<?php echo $this->url(array('module' => 'expedicao', 'controller' =>'cliente', 'action' =>'associar-praca' ))?>" method="post" id="frm-salvar-associar-praca">
    <div class="grid">
        <table class="gTable">
            <tbody>
            <tr class="gTTitle">
                <td></td>
                <td>Código</td>
                <td>Nome</td>
                <td>Cidade</td>
                <td>Bairro</td>
                <td>Praça</td>
                <td>UF</td>
            </tr>
            <?php if(isset($this->clientes)) : ?>

                <?php foreach($this->clientes as $cliente) : ?>
                    <?php $i++; ?>
                    <tr class="gTResultSet <?php echo ($i % 2 == 0 ? 'gRowColor' : '')?>">
                        <td class="gTdOpcRow"><a rel="modal" title="Visualizar detalhes do Endereço" href="<?php echo $this->url(array('module' => 'expedicao', 'controller' =>'cliente', 'action' =>'consultar', 'codCliente' =>  $cliente['id']))?>"  ><img alt="Opções" src="/img/icons/zoom.png"></a></td>
                        <td class="text-align:left"><?php echo $cliente['id']; ?></td>
                        <td class="text-align:left"><?php echo $cliente['nome']; ?></td>
                        <td class="text-align:left"><?php echo $cliente['cidade']; ?></td>
                        <td class="text-align:left"><?php echo $cliente['bairro']; ?></td>
                        <td class="text-align:left">
                            <select class="select-praca" style="width: 100%">
                                <?php foreach($this->pracas as $key => $praca) : ?>

                                    <?php if($cliente['praca'] == $key) : ?>
                                        <option value="<?php echo $key; ?>" selected><?php echo $praca; ?></option>
                                    <?php else : ?>
                                        <option value="<?php echo $key; ?>" ><?php echo $praca; ?></option>
                                    <?php endif; ?>

                                <?php endforeach; ?>
                            </select>

                        </td>
                        <td class="text-align:left"><?php echo $cliente['estado']; ?></td>

                        <input type="hidden" class="cliente" value="<?php echo $cliente['id']; ?>" name="<?php echo $cliente['id'] ?>[id]" />
                        <input type="hidden" class="pracaId" id="<?php echo $cliente['id']; ?>" value="<?php echo $cliente['praca']; ?>" name="<?php echo $cliente['id'] ?>[pracaId]" value="<?php echo $cliente['praca']; ?>"/>
                    </tr>

                <?php endforeach; ?>

            <?php endif; ?>
            </tbody>
        </table>

        <br />
        <button type="submit">Salvar</button>
    </div>
</form>