<form id="formGrid" method="post" action="">
    <table>
        <tbody>
        <tr>
            <td bgcolor="aqua" width=""><span><?php echo 'RECEBIMENTO TRANSBORDO'; ?></span></td>
        </tr>
        <?php if (!isset($this->idExpedicao)) : ?>
            <tr>
                <td width=""><span><?php echo utf8_encode('Expedição'); ?></span></td>
            </tr>
            <td><input type="text" name="idExpedicao" id="idExpedicao"></td>

        <?php elseif (isset($this->idExpedicao)) : ?>

            <input type="hidden" value="<?php echo $this->idExpedicao ?>" name="idExpedicao" id="idExpedicao">
            <tr>
                <td colspan="1"></td>
                <td width=""><span>Nome Usuario</span></td>
            </tr>
            <?php foreach($this->operadores as $operador) : ?>
                <?php $usuarioChecked = $this->equipeRepo->findOneBy(array('usuario' => $operador['id'], 'expedicao' => $this->idExpedicao)); ?>
                <tr>
                    <?php if (count($usuarioChecked) > 0) : ?>
                        <td><input type="checkbox" value="<?php echo $operador['id'] ?>" name="mass-id[]" checked ></td>
                    <?php else : ?>
                        <td><input type="checkbox" value="<?php echo $operador['id'] ?>" name="mass-id[]" ></td>
                    <?php endif; ?>
                    <td style="text-align:left">&nbsp;<?php echo $operador['nome'] ?></td>
                </tr>
            <?php endforeach; ?>
        <?php endif; ?>



        </tbody>
    </table>
    <button type="submit"><span>Vincular</span></button>
</form>