INSERT INTO VERSAO (DTH, NUMERO_VERSAO, SCRIPT) VALUES (SYSDATE, '6.13.1','15-melhorias-integracao.sql');

ALTER TABLE TR_PEDIDO
  ADD (COD_MOTORISTA CHAR(50),
       NOM_MOTORISTA VARCHAR(200),
	     SEQUENCIA_ENTREGA NUMBER(8));