INSERT INTO VERSAO (DTH, NUMERO_VERSAO, SCRIPT) VALUES (SYSDATE, '6.13.4','17-parametro-embalagens.sql');

INSERT INTO PARAMETRO
    (COD_PARAMETRO,COD_CONTEXTO_PARAMETRO,DSC_PARAMETRO,DSC_TITULO_PARAMETRO,IND_PARAMETRO_SISTEMA,COD_TIPO_ATRIBUTO,DSC_VALOR_PARAMETRO)
      values
    (SQ_PARAMETRO_01.NEXTVAL,
     (SELECT COD_CONTEXTO_PARAMETRO FROM CONTEXTO_PARAMETRO WHERE DSC_CONTEXTO_PARAMETRO = 'PARÂMETROS DE INTEGRAÇÃO'),
     'INATIVA_EMBALAGENS_INEXISTENTES_ERP','Inativar embalagens inexistentes no ERP','S','A','N');