INSERT INTO VERSAO (DTH, NUMERO_VERSAO, SCRIPT) VALUES (SYSDATE, '6.2.8','1-hot-fix-dados-logisticos.sql');


--SE RETORNAR RESULTADO TERÁ QUE APAGAR ROWS NA TABELA PRODUTO_DADO_LOGISTICO PEGANDO PELO COD_PRODUTO_EMBALAGEM
SELECT COD_PRODUTO_EMBALAGEM, COUNT(COD_PRODUTO_EMBALAGEM)
FROM PRODUTO_DADO_LOGISTICO
GROUP BY COD_PRODUTO_EMBALAGEM
HAVING(COUNT(COD_PRODUTO_EMBALAGEM) > 1);

delete produto_dado_logistico where COD_PRODUTO_DADO_LOGISTICO = 'XXX';

UPDATE PRODUTO_EMBALAGEM EMB SET
  NUM_PESO = (SELECT NUM_PESO FROM PRODUTO_DADO_LOGISTICO WHERE COD_PRODUTO_EMBALAGEM = EMB.COD_PRODUTO_EMBALAGEM),
  NUM_LARGURA = (SELECT NUM_LARGURA FROM PRODUTO_DADO_LOGISTICO WHERE COD_PRODUTO_EMBALAGEM = EMB.COD_PRODUTO_EMBALAGEM),
  NUM_PROFUNDIDADE = (SELECT NUM_PROFUNDIDADE FROM PRODUTO_DADO_LOGISTICO WHERE COD_PRODUTO_EMBALAGEM = EMB.COD_PRODUTO_EMBALAGEM),
  NUM_CUBAGEM = (SELECT NUM_CUBAGEM FROM PRODUTO_DADO_LOGISTICO WHERE COD_PRODUTO_EMBALAGEM = EMB.COD_PRODUTO_EMBALAGEM),
  NUM_ALTURA = (SELECT NUM_ALTURA FROM PRODUTO_DADO_LOGISTICO WHERE COD_PRODUTO_EMBALAGEM = EMB.COD_PRODUTO_EMBALAGEM)
WHERE (EMB.NUM_ALTURA = 0 OR EMB.NUM_ALTURA IS NULL)
  AND (EMB.NUM_LARGURA = 0 OR EMB.NUM_LARGURA IS NULL)
  AND (NUM_PROFUNDIDADE = 0 OR NUM_PROFUNDIDADE IS NULL);


--VERIFICAR PRODUTOS Q ESTÃO COM EMBALAGENS SEM DADOS LOGISTICOS, DEVERÁ ENTRAR NA TELA DE PRODUTO E SALVAR CADA UM DELES
SELECT PE1.NUM_ALTURA, PE2.NUM_ALTURA, PE1.COD_PRODUTO
FROM PRODUTO_EMBALAGEM PE1
INNER JOIN (
        SELECT PE2.NUM_ALTURA, PE2.COD_PRODUTO
        FROM PRODUTO_EMBALAGEM PE2
    ) PE2 ON PE1.COD_PRODUTO = PE2.COD_PRODUTO
WHERE PE1.NUM_ALTURA <> PE2.NUM_ALTURA
AND (PE1.NUM_ALTURA = 0 OR PE2.NUM_ALTURA = 0 OR PE1.NUM_ALTURA IS NULL OR PE2.NUM_ALTURA IS NULL);