<form id="modelo-separacao-form" class="saveForm" method="post" action="" novalidate="novalidate">
    <fieldset id="fieldset-modelo">
        <legend><?php echo utf8_encode('Endereçamento Automático') ?></legend>
        <div>
            <label for="descricao"><?php echo utf8_encode('Descrição') ?></label>
            <input type="text" id="descricao" name="descricao">
            <label for="endereco"><?php echo utf8_encode('Endereço de Referência'); ?></label>
            <input type="text" id="endereco" alt="endereco" name="endereco" placeholder="00.000.00.00">
        </div>

        <table style="width: 100%">
            <tr>
                <td>
                    <fieldset id="enderecamento">
                        <legend><?php echo utf8_encode('Sequencia de Endereçamento') ?></legend>
                        <table style="width: 100%">
                            <tr>
                                <td style="vertical-align: top; width: 30%; padding-right: 7pt">
                                    <fieldset id="fieldset-areaArmazenagem">
                                        <legend>Area de Armazenagem</legend>
                                        <table class="gTable">
                                            <?php echo utf8_encode('<tr class="gTTitle"><td>Descrição</td><td>Sequência</td></tr>') ?>
                                            <?php foreach ($this->areaArmazenagens as $areaArmazenagem) : ?>
                                                <tr class="gTResultSet">
                                                    <td><?php echo $areaArmazenagem->getDescricao(); ?></td>
                                                    <td><input type="text" id="areaArmazenagem[<?php echo $areaArmazenagem->getId() ?>]" name="areaArmazenagem[<?php echo $areaArmazenagem->getId() ?>]"></td>
                                                </tr>
                                            <?php endforeach; ?>
                                        </table>
                                    </fieldset>
                                </td>
                                <td style="vertical-align: top; width: 30%">
                                    <fieldset id="fieldset-tipoEndereco">
                                        <legend>Estrutura de Armazenagem</legend>
                                        <table class="gTable">
                                            <?php echo utf8_encode('<tr class="gTTitle"><td>Descrição</td><td>Sequência</td></tr>') ?>
                                            <?php foreach ($this->estruturaArmazenagens as $estruturaArmazenagem) : ?>
                                                <tr class="gTResultSet">
                                                    <td><?php echo $estruturaArmazenagem->getDescricao(); ?></td>
                                                    <td><input type="text" id="estruturaArmazenagem[<?php echo $estruturaArmazenagem->getId() ?>]" name="estruturaArmazenagem[<?php echo $estruturaArmazenagem->getId() ?>]"></td>
                                                </tr>
                                            <?php endforeach; ?>
                                        </table>
                                    </fieldset>
                                </td>
                                <td style="vertical-align: top; width: 30%">
                                    <fieldset id="fieldset-tipoEndereco">
                                        <legend>Tipos de Enderecos</legend>
                                        <table class="gTable">
                                            <?php echo utf8_encode('<tr class="gTTitle"><td>Descrição</td><td>Sequência</td></tr>') ?>
                                            <?php foreach ($this->tiposEndereco as $tipoEndereco) : ?>
                                                <tr class="gTResultSet">
                                                    <td><?php echo $tipoEndereco->getDescricao(); ?></td>
                                                    <td><input type="text" id="tipoEndereco[<?php echo $tipoEndereco->getId() ?>]" name="tipoEndereco[<?php echo $tipoEndereco->getId() ?>]"></td>
                                                </tr>
                                            <?php endforeach; ?>
                                        </table>
                                    </fieldset>
                                </td>
                            </tr>
                        </table>
                    </fieldset>
                </td>
            </tr>
        </table>

    </fieldset>

</form>
