<form id="modelo-separacao-form" class="saveForm" method="post" action="" novalidate="novalidate">
    <fieldset id="fieldset-modelo">
        <legend>Prioridades</legend>
        <div>
            <label for="descricao">Descricao</label>
            <input type="text" id="descricao" name="descricao">
            <label for="endereco">Endereco</label>
            <input type="text" id="rua" name="rua" size="2" maxlength="2">
            <input type="text" id="predio" name="predio" size="3" maxlength="3">
            <input type="text" id="nivel" name="nivel" size="2" maxlength="2">
            <input type="text" id="apartamento" name="apartamento" size="2" maxlength="2">
        </div>

        <div class="fieldsets">
            <div class="fieldset-left">
                <fieldset>
                    <legend>Area de Armazenagem</legend>
                    <div>
                        <?php foreach ($this->areaArmazenagens as $areaArmazenagem) : ?>
                            <?php echo $areaArmazenagem->getDescricao(); ?>
                            <div class="fieldset-right">
                                <input type="text" id="areaArmazenagem[<?php echo $areaArmazenagem->getId() ?>]" name="areaArmazenagem[<?php echo $areaArmazenagem->getId() ?>]">
                            </div>
                        <?php endforeach; ?>
                    </div>
                </fieldset>

                <fieldset>
                    <legend>Estrutura de Armazenagem</legend>

                    <?php foreach ($this->estruturaArmazenagens as $estruturaArmazenagem) : ?>
                        <?php echo $estruturaArmazenagem->getDescricao(); ?>
                        <div class="fieldset-right">
                            <input type="text" id="estruturaArmazenagem[<?php echo $estruturaArmazenagem->getId() ?>]" name="estruturaArmazenagem[<?php echo $estruturaArmazenagem->getId() ?>]">
                        </div>
                    <?php endforeach; ?>
                </fieldset>
            </div>

            <div class="fieldset-right">
                <fieldset>
                    <legend>Tipos de Enderecos</legend>

                    <?php foreach ($this->tiposEndereco as $tipoEndereco) : ?>
                        <?php echo $tipoEndereco->getDescricao(); ?>
                        <div class="fieldset-right">
                            <input type="text" id="tipoEndereco[<?php echo $tipoEndereco->getId() ?>]" name="tipoEndereco[<?php echo $tipoEndereco->getId() ?>]">
                        </div>
                    <?php endforeach; ?>
                </fieldset>
            </div>

        </div>

    </fieldset>

</form>
