INSERT INTO VERSAO (DTH, NUMERO_VERSAO, SCRIPT) VALUES (SYSDATE, '7.11.0', '01-melhorias-produtividade.sql');

alter table PRODUTIVIDADE_DETALHE
    add COD_ATIVIDADE NUMBER(2);

UPDATE PRODUTIVIDADE_DETALHE SET COD_ATIVIDADE = 1 WHERE DSC_ATIVIDADE = 'RESSUPRIMENTO';
UPDATE PRODUTIVIDADE_DETALHE SET COD_ATIVIDADE = 2 WHERE DSC_ATIVIDADE = 'SEPARACAO - PADRAO';
UPDATE PRODUTIVIDADE_DETALHE SET COD_ATIVIDADE = 3 WHERE DSC_ATIVIDADE = 'ENDERECAMENTO';
UPDATE PRODUTIVIDADE_DETALHE SET COD_ATIVIDADE = 4 WHERE DSC_ATIVIDADE = 'SEPARACAO';
UPDATE PRODUTIVIDADE_DETALHE SET COD_ATIVIDADE = 5 WHERE DSC_ATIVIDADE = 'SEPARACAO - EMBALADO';
UPDATE PRODUTIVIDADE_DETALHE SET COD_ATIVIDADE = 6 WHERE DSC_ATIVIDADE = 'CONF. SEPARACAO';
UPDATE PRODUTIVIDADE_DETALHE SET COD_ATIVIDADE = 7 WHERE DSC_ATIVIDADE = 'CONF. RECEBIMENTO';
UPDATE PRODUTIVIDADE_DETALHE SET COD_ATIVIDADE = 8 WHERE DSC_ATIVIDADE = 'CONF. SEPARACAO - PADRAO';
UPDATE PRODUTIVIDADE_DETALHE SET COD_ATIVIDADE = 9 WHERE DSC_ATIVIDADE = 'CARREGAMENTO';
UPDATE PRODUTIVIDADE_DETALHE SET COD_ATIVIDADE = 10 WHERE DSC_ATIVIDADE = 'CONF. SEPARACAO - EMBALADO';
UPDATE PRODUTIVIDADE_DETALHE SET COD_ATIVIDADE = 11 WHERE DSC_ATIVIDADE = 'DESCARREGAMENTO';
UPDATE PRODUTIVIDADE_DETALHE SET COD_ATIVIDADE = 12 WHERE DSC_ATIVIDADE = 'RETORNO DE RESSUPRIMENTO ';
UPDATE PRODUTIVIDADE_DETALHE SET COD_ATIVIDADE = 13 WHERE DSC_ATIVIDADE = 'CONF. TRANSBORDO - PADRAO';
UPDATE PRODUTIVIDADE_DETALHE SET COD_ATIVIDADE = 14 WHERE DSC_ATIVIDADE = 'CONF. TRANSBORDO - EMBALADO';