<?php
echo $this->doctype();
$role = \Zend_Auth::getInstance()->getIdentity()->getRoleId();
$acl = \Zend_Registry::get('acl');

use Core\Util\Converter;
?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
        <meta http-equiv="Content-Language" content="pt-br" />
        <?php if (isset($this->refresh) && ($this->refresh == true)) : ?>
            <script type="text/javascript">

                function reloadExpedicao(){
                    setTimeout(function(){
                        if( $('.ui-dialog:visible').length == 0 && $('.flashMessenger').length == 0  )
                            window.location.reload();
                        else
                            reloadExpedicao();
                    }, 40000);
                }

                reloadExpedicao();

            </script>
        <?php endif; ?>
        <meta name="Keywords" content="" />
        <meta name="Description" content="" />
        <meta name="url" content="http://www.wmsms.com.br" />
        <meta name="reply-to" content="info@wmsms.com.br" />
        <meta name="copyright" content="www.wmsms.com.br" />
        <meta name="category" content="Internet" />
        <meta name="Robots" content="Index,Follow" />
        <meta name="author" content="Renato Medina" />
        <title>WMS - Imperium</title>
        <link rel="shortcut icon" href="<?php echo $this->baseUrl('img/admin/logomarca.png') ?>" type="image/x-icon" />
        <script type="text/javascript">
            var URL_SISTEMA = "<?php echo $this->serverUrl($this->baseUrl()); ?>";
            var URL_BASE = "<?php echo $this->baseUrl(); ?>";
            var URL_MODULO = URL_SISTEMA + "/<?php echo $this->request->getModuleName(); ?>";
            var URL = URL_SISTEMA + "<?php echo getenv("REQUEST_URI"); ?>";
        </script>
        <?php if('production' == APPLICATION_ENV): ?>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('wms/production.css'); ?>" />
        <script type="text/javascript" src="<?php echo $this->baseUrl('steal/steal.production.js?wms,production'); ?>"></script>
		<?php else: ?>
        <script type="text/javascript" src="<?php echo $this->baseUrl('steal/steal.js?wms,development'); ?>"></script>
		<?php endif; ?>
        <script type="text/javascript">
            $(document).ready(function(){

                $('html, body').scrollTop(0);

                /***************************************
                Tabs/Forms
                 ***************************************/
                $( ".tabContainer" ).tabs({
                    show: function(event, ui) {
                        // remove padding
                        $('div.ui-corner-bottom').attr('style', 'padding:5px 0px; color');
                    }
                });

                $(".saveForm").validate({
                    ignore: ".ignore",
                    submitHandler: function(form) {
                        form.submit();
                    },
                    // changes tab's colors
                    invalidHandler: function(form, validator) {
                        var errors = validator.numberOfInvalids();
                        if (errors) {
                            var invalidPanels = $(validator.invalidElements()).closest(".ui-tabs-panel", form);
                            if (invalidPanels.size() > 0) {
                                $.each($.unique(invalidPanels.get()), function(){
                                    $("a[href='#" + this.id + "']").parent()
                                    .addClass("ui-state-error")
                                    .show("pulsate",{
                                        times: 1
                                    });
                                });
                            }
                        }
                    },
                    unhighlight: function(element, errorClass, validClass) {
                        $(element).removeClass(errorClass).addClass(validClass);
                        $(element.form).find("label[for=" + element.id + "]").removeClass(errorClass);
                        var $panel = $('a[href=#' + $(element).parents('.ui-tabs-panel').attr('id') + ']').parent();
                    
                        if ($panel.size() > 0) {
                            if ($(element).parents('.ui-tabs-panel').find("." + errorClass + "").size() == 0)
                                $panel.removeClass("ui-state-error");
                        }
                    }
                });
                
                $('ul.errors').each(function(i, v) {
                    var id = $(this).parents('.ui-tabs-panel').attr('id');
                    $("a[href='#" + id + "']").parent().addClass("ui-state-error").show("pulsate",{
                                        times: 1
                    });;
                });
            });
        </script>
        
        <?php
            echo $this->headScript();
            echo $this->headLink();
        ?>
    </head>
    <body>
    <div id="loading">
        <center class="loading-image" ><img src="/img/ajax-loader.gif" width="35" height="35"/><p><b>Carregando...</b></p></center>
    </div>
        <div id="dialog-delete-record" title="Deseja excluir este registro?" style="display:none;">
            <p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>Este item será removido permanentemente e não poderá ser recuperado. Está certo disto?</p>
        </div>
        <div id="dialog-ajuda" title="Ajuda" style="display:none">
            <p><?php echo $this->textoAjuda; ?></p>
        </div>
        <div id="body">
            <?php if (APPLICATION_ENV == 'development') : ?>
            <div id="top" class="development">
                <?php else : ?>
                    <div id="top">
            <?php endif; ?>
                <div id="userInfo">
                    <img src="<?php echo $this->baseUrl('img/icons/user.png'); ?>" alt="#" /> Logado como <?php echo $this->nomeUsuario; ?>
                    <span>|</span> Depósito: <?php echo $this->formSelect('depositoLogado', $this->idDepositoLogado, array('id' => 'idDepositoLogado'), $this->depositosPermitidos); ?>
                    <span>|</span>
                    <?php
                    $date = new Zend_Date();
                    echo ucfirst($date->get("EEEE") . ', ' . $date->get("d") . ' de ' . $date->get("MMMM") . ' de ' . $date->get("Y"));
                    ?>
<?php if ($this->mostrarIconeAjuda) { ?>
                        <span>|</span>
                        <a href="#" id="btn-ajuda" title="Ajuda">
                            <img src="<?php echo $this->baseUrl('img/icons/help.png') ?>" />
                        </a>
<?php } ?>
                    <span>|</span>
                    <a href="<?php echo $this->url(array('module' =>'web', 'controller' => 'auth', 'action' => 'logout')); ?>" title="Desconectar" ><img src="<?php echo $this->baseUrl('img/icons/door_out.png'); ?>" alt="#" /> Sair</a>
                </div>
                <h1><a href="#" title="WMS - Imperium">WMS - Imperium</a></h1>
            </div>
            <div id="mainmenu-container">
                <?php
                $this->navigation()->setAcl($acl)->setRole($role);
                $this->navigation()->menu()->setUlClass('menu');
                echo $this->navigation();
                ?>
            </div>
            <div id="content">
                <div class="contentPadding">
                    <div id="panelPage">
                            <?php if (is_object($this->page)) { ?>
                            <div class="left">
                                <?php
                                foreach ($this->page->getButtons() as $button) {
                                    if ($button->getTag() == 'a') {
                                        ?>
                                        <a href="<?php echo $this->url($button->getUrlParams()); ?>" class="btn reader <?php echo $button->getCssClass() ?>"><span><?php echo $button->getLabel(); ?></span></a>
                                    <?php } else { ?>
                                        <button class="btn header <?php echo $button->getCssClass() ?>"><span><?php echo $button->getLabel(); ?></span></button>
                                        <?php
                                    }
                                }
                                ?>
                            </div>
<?php } ?>
                        <h4><?php echo $this->navigation()->breadcrumbs()->setRenderInvisible(TRUE)->setPartial('breadcrumb.phtml')->render(); ?></h4>
                    </div>
                    <?php $this->messenger(); ?>
<?php echo $this->layout()->content ?>
                </div>
            </div>
            <div id="footer">
                <p>Wms Imperium <?php $abc = new Zend_Date(); echo $abc->toString('Y') ?></p>
                <p>&copy; Todos os Direitos Reservados.</p>
                <?php if (APPLICATION_ENV == 'development') : ?>
                    <p class="development">
                    <?php else: ?>
                    <p>
                <?php endif;?>
                    <?php echo APPLICATION_ENV ?> | <?php echo $this->totalTimePage ?>
                </p>
            </div>
        </div>
        <?php
            if ( !empty($this->control) && $this->control=="roll"){
                echo "<script>$('html, body').animate({scrollTop:0}, 'slow');</script>";
            }
        ?>
    </body>
</html>
