<form id="filtro-produtividade-detalhada-form" method="get" class="filtro" action="">
    <div>
        <fieldset id="fieldset-busca">
            <legend>Filtros</legend>
            <table style="width:100%">
                <tr>
                    <!--<td>Expedição</td>-->
                    <td style="width: 110px;">
                        <p>Cod. Mapa de Sep.</p>
                        <p style="margin-top: 3px;">Cod. Recebimento</p> 
                        <p style="margin: 3px 0px 3px;">Cod. Expedição</p></td>
                    <td>Atividade</td>
                    <!--<td>Tipo Quebra</td>-->
                    <td>Data Inicial</td>
                    <td>Hora Inicial</td>
                    <td>Data Final</td>
                    <td>Hora Final</td>
                    <td>Usuário</td>
                    <td><?php echo $this->element->submit; ?></td>
                </tr>
                <tr>
                    <!--<td><?php //echo $this->element->expedicao; ?></td>-->
                    <td><?php echo $this->element->identidade; ?></td>
                    <td><?php echo $this->element->atividade; ?></td>
                    <!--<td><?php // echo $this->element->tipoQuebra; ?></td>-->
                    <td><?php echo $this->element->dataInicio; ?></td>
                    <td><?php echo $this->element->horaInicio; ?></td>
                    <td><?php echo $this->element->dataFim; ?></td>
                    <td><?php echo $this->element->horaFim; ?></td>
                    <td><?php echo $this->element->usuario; ?></td>
                    <td> <?php echo $this->element->btnRelatorio; ?></td>
                </tr>
            </table>
        </fieldset>
    </div>
</form>