<form id="filtro-produtividade-detalhada-form" method="get" class="filtro" action="">
    <div>
        <fieldset id="fieldset-busca">
            <legend>Filtros</legend>
            <table style="width:100%">
                <tr>
                    <td>Expedição</td>
                    <td>Mapa Separação</td>
                    <td>Data Inicial</td>
                    <td>Hora Inicial</td>
                    <td>Data Final</td>
                    <td>Hora Final</td>
                    <td>Usuário</td>
                    <td rowspan="4"><?php echo $this->element->submit; ?></td>
                </tr>
                <tr>
                    <td><?php echo $this->element->expedicao; ?></td>
                    <td><?php echo $this->element->mapaSeparacao; ?></td>
                    <td><?php echo $this->element->dataInicio; ?></td>
                    <td><?php echo $this->element->horaInicio; ?></td>
                    <td><?php echo $this->element->dataFim; ?></td>
                    <td><?php echo $this->element->horaFim; ?></td>
                    <td><?php echo $this->element->usuario; ?></td>
                </tr>
            </table>
        </fieldset>
    </div>
</form>