<?php
/**
 * Created by PhpStorm.
 * User: Luis Fernando
 * Date: 01/06/2018
 * Time: 10:00
 */

echo $this->form;
?>
<div id="estoque" style="text-align: center;"></div>
<script>
    $(window).load(function () {
        $('#qtdLote').parent().css('text-align', 'center');
        $('#loteInicio').parent().hide();
        $('#loteFim').parent().hide();
        $('#loteLimpo')
            .css('margin-top', '2px').parent().css('margin-top', '25px').hide()
            .find("label").last().css('margin-right', '20px');

        $('#tipoLote').change(function () {
            $('#codLote').parent().show();
            if ($(this).val() == 'I') {
                $('#loteInicio').parent().show();
                $('#loteFim').parent().show();
                $('#loteLimpo').parent().show();
            } else {
                $('#loteInicio').val('').parent().hide();
                $('#loteFim').val('').parent().hide();
                $('#loteLimpo').prop( "checked", false ).parent().hide();
            }
            if($(this).val() == 'E'){
                $('#codLote').val('');
                $('#codLote').parent().hide();
            }

        });
        $("#buscar").click(function () {
            $('#qtdLote').val('');
            $.ajax({
                url: URL_MODULO + '/lote-virgem/list-ajax/',
                type: 'post',
                dataType: 'html',
                data: $('form').serialize(),
                success: function (data) {
                    $('#estoque').html(data);
                    $("#imprimir").click(function () {
                        $('#cadastro-movimentacao').submit();
                        return false;
                    });
                }
            });
            return false;
        });



        $("#gerar").click(function () {
            if($('#qtdLote').val() > 0 && $('#qtdLote').val() != '') {
                $.ajax({
                    url: URL_MODULO + '/lote-virgem/criar-lote-ajax/',
                    type: 'post',
                    dataType: 'json',
                    data: $('form').serialize(),
                    success: function (data) {
                        if(data.success == 'success'){
                            $.wmsDialogAlert({
                                title: 'Sucesso',
                                msg: 'Lote(s) gerado(s).'
                            });
                            $('#cadastro-movimentacao').resetForm();
                            $("#tipoLote").val("I");
                            $("#loteLimpo").attr('checked','checked');
                            $("#loteInicio").val(data.loteInicio);
                            $("#loteFim").val(data.loteFim);
                            $('#cadastro-movimentacao').submit();
                            $.ajax({
                                url: URL_MODULO + '/lote-virgem/list-ajax/',
                                type: 'post',
                                dataType: 'html',
                                data: $('form').serialize(),
                                success: function (data) {
                                    $('#estoque').html(data);
                                    $("#imprimir").click(function () {
                                        $('#cadastro-movimentacao').submit();
                                        return false;
                                    });
                                }
                            });
                        }
                    }
                });
            }else{
                $.wmsDialogAlert({
                    title: 'ERRO',
                    msg: 'Digite a quantidade de lotes a serem gerados.'
                });
            }
            return false;
        });
    });
</script>