<?php echo $this->form; ?>

<?php if (!empty($this->IdInventario)) : ?>
    <h3 class="padding-top" style="font-size:30px">Inventário: <?php echo $this->IdInventario ?> </h3>
<?php endif; ?>

<?php echo $this->grid;
?>
<script>
    var idAtual = $("#id").val();
    $(".incluir").click(function () {
        var id = $("#id").val();
        if($("#incluirinput").val() == '' && idAtual != id){
            $("#incluirinput").val(idAtual);
        }
        
        if (id != '' && $("#incluirinput").val() != '') {
            $("#incluirinput").val($("#incluirinput").val() + ',' + id);
        }else{
            $("#incluirinput").val(id);
        }
        return true;
    });
    $("#submit").click(function () {
        $("#incluirinput").val('');
        return true;
    });

</script>