INSERT INTO VERSAO (DTH, NUMERO_VERSAO, SCRIPT) VALUES (SYSDATE, '7.4.0','01-parametro-atividade-separacao-obrigatoria');

INSERT INTO PARAMETRO (COD_PARAMETRO,COD_CONTEXTO_PARAMETRO,DSC_PARAMETRO,DSC_TITULO_PARAMETRO,IND_PARAMETRO_SISTEMA,COD_TIPO_ATRIBUTO,DSC_VALOR_PARAMETRO)
 VALUES (SQ_PARAMETRO_01.NEXTVAL,23,'ATIVIDADE_SEPARACAO_OBRIGATORIA','Obriga realizar a atividade de separação para finalizar uma expedição', 'S', 'A', 'S');