<style>
    #messenger {
        display: none;
    }

    #messenger.showing {
        display: block;
        position: absolute;
        left: 50%;
        top: 50%;
        margin-left:-125px; /* Metade do valor da Largura */
        width:250px;
    }
</style>
<div class="row">
    <div id="messenger"></div>
    <div class="row">
        <h3>Recebimentos Aguardando Conferência</h3>
        <?php if (empty($this->recebimentos['nao_iniciados'])): ?>
            <p>Nenhum Recebimento aguardando conferência.</p>
        <?php endif; ?>
        <?php foreach ($this->recebimentos['nao_iniciados'] as $idReceb => $recebimento): ?>
        <?php if (empty($recebimento['FORNECEDOR'])) : ?>
                <p><span style="background-color: #ff9c00; font-size: 18px">Todas as notas do recebimento <?php echo $recebimento['COD_RECEBIMENTO'] ?> foram removidas, cancele este recebimento</span></p>
            <?php else :
                $url = $this->url(array('controller' => 'recebimento', 'action' => 'ler-codigo-barras', 'idRecebimento' => $idReceb)); ?>
                <?php if (!empty($recebimento['DSC_OBSERVACAO']))
                    echo '<a class="recebimento-info" data-msg="'.$recebimento['DSC_OBSERVACAO'].'">
                            <img src="/img/icons/bell.png" alt="recebimento">
                          </a>'?>
                <a class="btn btn-xs gradientBtn" href="<?php echo $url ?>" title="<?php echo $idReceb ?>" >Receb. <?php echo $idReceb ?> - Box <?php echo $recebimento['COD_BOX'] ?> - F: <?php echo $recebimento['FORNECEDOR'] ?> </a>
            <?php endif; ?>
        <?php endforeach; ?>

        <h3>Recebimentos em Conferência por <?php echo \Zend_Auth::getInstance()->getIdentity()->getPessoa()->getNome() ?></h3>
        <?php if (empty($this->recebimentos['iniciados'])): ?>
            <P>Nenhum Recebimento Em Conferência Pelo seu Usuário.</P>
        <?php endif; ?>
        <?php foreach ($this->recebimentos['iniciados'] as $idReceb => $recebimento): ?>
            <?php if (empty($recebimento['FORNECEDOR'])) : ?>
                <p><span style="background-color: #ff9c00; font-size: 18px">Todas as notas do recebimento <?php echo $recebimento['COD_RECEBIMENTO'] ?> foram removidas, cancele este recebimento</span></p>
            <?php else :
                $url = $this->url(array('controller' => 'recebimento', 'action' => 'ler-codigo-barras', 'idRecebimento' => $idReceb)); ?>
                <?php if (!empty($recebimento['DSC_OBSERVACAO']))
                echo '<a href="" class="recebimento-info" data-msg="'.$recebimento['DSC_OBSERVACAO'].'">
                            <img src="/img/icons/bell.png" alt="recebimento">
                          </a>'?>
                <a class="btn btn-xs gradientBtn" href="<?php echo $url ?>" title="<?php echo $idReceb ?>" >Receb. <?php echo $idReceb ?> - Box <?php echo $recebimento['COD_BOX'] ?> - F: <?php echo $recebimento['FORNECEDOR'] ?> </a>
            <?php endif; ?>
        <?php endforeach; ?>
    </div>
</div>
<script>
    $(".recebimento-info").click(function () {
        var msg = $(this).data('msg');
        $("#messenger").html(
            '<ul class="flashMessenger">' +
            '    <li class="info_message" id="">' +
            '        <div style="display:block; float:right;">' +
            '            <a href="#" class="fmBtnClose">X</a>' +
            '        </div>' +
            '        <div style="display: block;" id="msg-text">' + msg + '</div>' +
            '    </li>' +
            '</ul>').addClass('showing');
    })

    $(".fmBtnClose").live("click", function () {
        $("#messenger").removeClass('showing').empty();
    });
</script>