<h3>Inventários disponíveis</h3>
<ul class="menu">
    <?php if(count($this->inventarios) == 0): ?>
        <li>Nenhum Inventário liberado para conferência.</li>
    <?php endif;?>
    <?php foreach($this->inventarios as $inventario): ?>
        <li>
            <a href="<?php echo $this->url(array('controller' => 'inventario', 'action' => 'seleciona-contagem', 'idInventario' => $inventario['id'] )); ?>" title="<?php echo $inventario['id'] ?>" >Cod. Inv. <?php echo $inventario['id'] ?> </a>
        </li>
    <?php endforeach; ?>
</ul>
