<div class="col-xs-12">
    <h3>Inventários disponíveis</h3>
    <?php if (count($this->inventarios) == 0): ?>
        <p>Nenhum Inventário liberado para conferência.</p>
    <?php endif; ?>
    <?php foreach ($this->inventarios as $inventario): ?>
        <a class="btn btn-xs gradientBtn" href="<?php echo $this->url(array('controller' => 'inventario', 'action' => 'seleciona-contagem', 'idInventario' => $inventario['id'])); ?>" title="<?php echo $inventario['id'] ?>" >Cod. Inv. <?php echo $inventario['id'] ?> </a>
    <?php endforeach; ?>
</div>

