<div class="row">
    <div class="row">
        <h3>Recebimentos Aguardando Conferência</h3>
        <?php if (count($this->recebimentoIniciado) == 0): ?>
            <p>Nenhum Recebimento aguardando conferência.</p>    
        <?php endif; ?>
        <?php foreach ($this->recebimentoIniciado as $recebimento): ?>
        <?php $nomFornecedor = $this->repo->getFornecedorbyRecebimento($recebimento->getId()) ;
            if (!$nomFornecedor) : ?>
                <p><span style="background-color: #ff9c00; font-size: 18px">Todas as notas do recebimento <?php echo $recebimento->getId() ?> foram removidas, cancele este recebimento</span></p>
            <?php else : ?>
                <a class="btn btn-xs gradientBtn" href="<?php echo $this->url(array('controller' => 'recebimento', 'action' => 'ler-codigo-barras', 'idRecebimento' => $recebimento->getId())); ?>" title="<?php echo $recebimento->getId() ?>" >Cod. Receb. <?php echo $recebimento->getId() ?> - Box <?php echo $recebimento->getBox()->getId() ?> - <?php echo $this->repo->getFornecedorbyRecebimento($recebimento->getId()) ?> </a>
            <?php endif; ?>
        <?php endforeach; ?>

        <h3>Recebimentos em Conferência por <?php echo \Zend_Auth::getInstance()->getIdentity()->getPessoa()->getNome() ?></h3>
        <?php if (count($this->recebimentoEmConferencia) == 0): ?>
            <P>Nenhum Recebimento Em Conferência Pelo seu Usuário.</P>    
        <?php endif; ?>
        <?php foreach ($this->recebimentoEmConferencia as $recebimento): ?>
            <?php $nomFornecedor = $this->repo->getFornecedorbyRecebimento($recebimento->getId()) ;
                if (!$nomFornecedor) : ?>
                    <p><span style="background-color: #ff9c00; font-size: 18px">Todas as notas do recebimento <?php echo $recebimento->getId() ?> foram removidas, cancele este recebimento</span></p>
                <?php else : ?>
                    <a class="btn btn-xs gradientBtn" href="<?php echo $this->url(array('controller' => 'recebimento', 'action' => 'ler-codigo-barras', 'idRecebimento' => $recebimento->getId())); ?>" title="<?php echo $recebimento->getId() ?>" >Cod. Receb. <?php echo $recebimento->getId() ?> - Box <?php echo $recebimento->getBox()->getId() ?> - <?php echo $this->repo->getFornecedorbyRecebimento($recebimento->getId()) ?> </a>
                <?php endif; ?>
        <?php endforeach; ?>
    </div>
</div>