<h3>Expedições disponíveis</h3>
<ul class="menu">
    <?php if(count($this->expedicoes) == 0): ?>
        <li>Nenhuma Expedição aguardando conferência.</li>
    <?php endif;?>
    <?php foreach($this->expedicoes as $expedicao):
        if (in_array($expedicao['id'],$this->iniciadas)) {
            //$this->complemento = ' (Conferência Iniciada)';
            $this->complemento = "";
        }
        else {
            $this->complemento = "";
        }

        if ($this->reconfere == "S") {
            if ($expedicao['codStatus'] == \Wms\Domain\Entity\Expedicao::STATUS_PRIMEIRA_CONFERENCIA) {
                $this->complemento .= " - 1ªC";
            }
            if ($expedicao['codStatus'] == \Wms\Domain\Entity\Expedicao::STATUS_EM_SEPARACAO) {
                $this->complemento .= " - 1ªC";
            }
            if ($expedicao['codStatus'] == \Wms\Domain\Entity\Expedicao::STATUS_SEGUNDA_CONFERENCIA) {
                $this->complemento .= " - 2ªC";
            }
        }

        //$this->complemento = "";
    ?>
        <li>
            <a href="<?php echo $this->url(array('controller' => 'expedicao', 'action' => 'carregamento', 'idExpedicao' => $expedicao['id'] )); ?>" title="<?php echo $expedicao['id'] ?>" >Cod. Exp. <?php echo $expedicao['id'] . ' - C:'. $expedicao['placaExpedicao'] . $this->complemento ?> </a>
        </li>
    <?php endforeach; ?>
</ul>
