<?php
echo $this->form;
echo $this->render('recebimento/view-gerar-recebimento.phtml');
?>
<script>
    $(document).ready(function(){
        $("#formGerarRecebmento").preventDoubleSubmission()

        $(document).ready(function(){
            $('#todos').live('click',function(){
                var checked_status = this.checked;
                $("input").each(function()
                {
                    this.checked = checked_status;
                });
            });
        });
    });
    jQuery.fn.preventDoubleSubmission = function() {
        $(this).on('submit',function(e){
            var $form = $(this);

            if ($form.data('submitted') === true) {
                // Previously submitted - don't submit again
                e.preventDefault();
            } else {
                // Mark it so that the next submit can be ignored
                $form.data('submitted', true);
            }
        });

        // Keep chainability
        return this;
    };
</script>