
<?php echo $this->render('recebimento/cabecalho.phtml'); ?>

<style>
    table.produtos th {
        text-align: left;
        font-weight: bold;
    }
    table.produtos tbody td {
        text-align: left;
        border-bottom: 1px solid #CCC;
    }
    label {
        display: inline !important;
    }
</style>

<form id="form-recebimento-conferencia" method="post" class="saveForm">    
    <div id="quantidade-grid" class="grid">
        <table class="gTable produtos">
            <thead>
                <tr class="gTTitle">
                    <td>Cód. Produto</td>
                    <td>Grade</td>
                    <?php if ($this->temLote) { ?>
                        <td>Lote</td>
                    <?php } ?>
                    <td>Unidade</td>
                    <td>Qtd Peças</td>
                    <?php if ($this->temFracionavel) { ?>
                        <td>Total em</td>
                    <?php } ?>
                    <?php if ($this->controlaValidade) { ?>
                        <td>Data Validade</td>
                    <?php } ?>
                    <td>Unitizador</td>
                    <td>Qtd. Avaria</td>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->produtos as $produto) { ?>
                    <tr height="35">
                        <td><?php echo $produto['codigo'] . ' - ' . $produto['descricao'] ?></td>
                        <td><?php echo $produto['grade'] ?></td>
                        <?php if ($this->temLote) { ?>
                            <td>
                                <?php if ($produto['ind_controla_lote'] == "S") {
                                    echo $this->formText("lote[{$produto['codigo']}][{$produto['grade']}][0]", null, [
                                        'size' => 16,
                                        'id' => "lote--$produto[codigo]--$produto[grade]--0",
                                        'class' => 'inputLote',
                                        'placeholder' => "Lote..."
                                    ]);
                                    echo "<span class='addLote' id='addLote--$produto[codigo]--$produto[grade]' style='cursor: pointer ; background: #4cae4c ; padding: 5px'><b>Add</b></span>";
                                }
                                ?>
                            </td>
                        <?php } ?>
                        <td>
                        <?php if (isset($produto['embalagens'])) {
                                echo "<select class='Embalagem' name='embalagem[$produto[codigo]][$produto[grade]][0]' title='Embalagem do produto $produto[codigo]-$produto[grade]' id='embalagem--$produto[codigo]--$produto[grade]--0'>";
                                foreach ($produto['embalagens'] as $embalagem) {
                                    echo "<option value='$embalagem[id]' data-fracionavel-default='$embalagem[isFracDefault]'>$embalagem[dsc]</option>";
                                }
                                echo "</select>";
                            } else {
                                $medida = null;
                                foreach ($this->unMedida as $key => $medidas) {
                                    if ($medidas['produto'] == $produto['codigo'] && $medidas['grade'] == $produto['grade']) {
                                        $medida[$medidas['id']] = $medidas['descricao'];
                                    }
                                }
                                if (isset($medida) && $medida != null) {
                                    echo $this->formSelect("unMedida[{$produto['codigo']}][{$produto['grade']}][0]", null, array(
                                        'validators' => array('numeric'),
                                        'alt' => 'number',
                                        'id' => "unMedida--$produto[codigo]--$produto[grade]--0",
                                        'class' => "unMedida",
                                        'title' => "[{$produto['codigo']}][{$produto['grade']}]",
                                    ), $medida);
                                } else {
                                    echo '-';
                                }
                            }
                        ?>
                        </td>
                        <td>
                            <?php
                            echo $this->formText("qtdConferida[{$produto['codigo']}][{$produto['grade']}][0]", 0, [
                                'size' => 8,
                                'validators' => array('numeric'),
                                'id' => "qtdConferida--$produto[codigo]--$produto[grade]--0",
                                'alt' => 'number',
                                'class' => "qtdConferida",
                                'title' => "[{$produto['codigo']}][{$produto['grade']}][]"
                            ]);
                            ?>
                        </td>
                        <?php if ($this->temFracionavel) { ?>
                        <td>
                            <div>
                                <?php
                                if ($produto['ind_fracionavel'] == 'S') {
                                echo $this->formText("qtdUnidFracionavel[{$produto['codigo']}][{$produto['grade']}][0]", 0, [
                                    'size' => 8,
                                    'validators' => array('numeric'),
                                    'id' => "qtdUnidFracionavel--$produto[codigo]--$produto[grade]--0",
                                    'alt' => 'centesimal',
                                    'class' => "qtdUnidFracionavel required",
                                    'title' => "Total unid fracionavel [{$produto['codigo']}][{$produto['grade']}][]"
                                ]); } ?>
                                <span id="<?php echo "txtUnid*-*$produto[codigo]*-*$produto[grade]*-*0"?>"></span>
                            </div>
                        </td>
                        <?php } ?>
                        <?php if ($this->controlaValidade) { ?>
                            <td>
                                <?php
                                if ($produto['possui_validade']) {
                                $date = new DateTime('now');
                                echo $this->formText("dataValidade[{$produto['codigo']}][{$produto['grade']}][0]", $date->format('d/m/Y'), array(
                                    'size' => 11,
                                    'validators' => array('numeric'),
                                    'id' => "dataValidade--$produto[codigo]--$produto[grade]--0",
                                    'alt' => 'date',
                                    'class' => "date dthValidade",
                                    'title' => "dataValidade[{$produto['codigo']}][{$produto['grade']}]",
                                    'maxLenght' => 10
                                ));
                                }
                                ?>
                            </td>
                        <?php  } ?>
                        <td>
                            <?php
                            if (isset($produto['normas']) && !empty($produto['normas']))
                                echo $this->formSelect("norma[{$produto['codigo']}][{$produto['grade']}][0]", key($produto['normas']) ,array(
                                        'required' => true,
                                        'class' => "norma",
                                        'id' => "norma--$produto[codigo]--$produto[grade]--0",
                                        'title' => "Norma de paletizacao do produto $produto[codigo]-$produto[grade]",
                                        'empty_option' => "Selecione a norma"
                                ), $produto['normas'])
                            ?>
                        </td>
                        <td>
                            <?php
                            echo $this->formText("qtdAvaria[{$produto['codigo']}][{$produto['grade']}][0]", 0, array(
                                'size' => 8,
                                'validators' => array('numeric'),
                                'id' => "qtdAvaria--$produto[codigo]--$produto[grade]--0",
                                'alt' => 'number',
                                'class' => "qtdAvaria",
                                'title' => "[{$produto['codigo']}][{$produto['grade']}]",
                                'readyonly' => 'readyonly',
                            ));
                            ?>
                        </td>
                    </tr>
                <?php } ?>
                <tr style="line-height: 50px;">
                    <td></td>
                    <td colspan="4">
                        <label>Conferente: 
                            <?php
                            $conferentes[] = 'Selecione';
                            foreach ($this->conferentes as $key => $conferente) {
                                $conferentes[$key] = $conferente;
                            }
                            echo $this->formSelect("idPessoa", null, null, $conferentes);
                            ?> 
                        </label>
                    </td>
                    <td colspan="2">
                        <button type="button" id="enviar" class="btn" style="margin-top: 0;">Salvar e Finalizar</button>
                        <?php
                        echo $this->formSubmit("submit", "Salvar e Finalizar", array('id' => 'btnCconferencia', 'class' => 'btn', 'style' => 'margin-top: 0; display:none;'));
                        ?>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</form>
<div id="modal-autorizacao" title="Confirmação" style="display: none">
    <form id="form-autorizacao">
        <p>A validade do(s) produto(s) abaixo é menor que o esperado:</p><br>
        <p id="msg-result"></p><br>
        <p>Para prosseguir insira a senha de autorização:</p><br>
        <fieldset>
            <label for="password">Senha de autorização: </label>
            <input type="password" name="password" id="password" class="text ui-widget-content ui-corner-all">
            <input type="submit" tabindex="-1" style="position:absolute; top:-1000px">
        </fieldset>
    </form>
</div>

<script>

    var strConcatId = "--";

    <?php if ($this->temLote) { ?>
    var inputNames = ["lote", "embalagem", "unMedida", "qtdConferida", "qtdUnidFracionavel", "dataValidade", "norma", "qtdAvaria"];
    var lotesArr = {};

    $(".inputLote").live("change", function (ev) {
        var inputLote = $(this);
        var arrId = inputLote.attr("id").toString().split(strConcatId);
        var cod = arrId[1];
        var grade = arrId[2];
        var index = arrId[3];
        var lote = (inputLote.val())? inputLote.val() : 0 ;

        var codGrade = [cod,grade].join("--");
        if (codGrade in lotesArr) {
            var oldLote = null;
            if (index in lotesArr[codGrade])
                oldLote = lotesArr[codGrade][index];

            var loteRepetido = false;
            if (oldLote !== lote) {
                $.each(lotesArr[codGrade], function (k, v) {
                    if (v === lote) {
                        loteRepetido = true;
                        alert("Já existe uma linha com o lote: '" + lote + "' nesse produto " + cod + " - " + grade + "!");
                        inputLote.val(oldLote);
                    }
                });
                if (loteRepetido) return false;

                lotes = lotesArr[codGrade];
                lotes[index] = lote;
                lotesArr[codGrade] = lotes;
            }
        } else {
            var lotes = {};
            lotes[index] = lote;
            lotesArr[codGrade] = lotes;
        }

        $.each(inputNames, function (k, name) {
            var idConcated = [name,cod,grade,index].join(strConcatId);
            var inpt = $("#" + idConcated);
            if (inpt.length) {
                var strName = name + "[" + [cod,grade,lote].join("][") + "]";
                inpt.attr("name", strName)
            }
        });
    });

    $("span.addLote").click(function () {
        var btnAdd = $(this);
        var arrId = btnAdd.attr("id").toString().split(strConcatId);
        var cod = arrId[1];
        var grade = arrId[2];
        var indexMatriz = 0;
        var tInputs = btnAdd.parent().find("input.inputLote");

        var nextIndex = 1;
        $.each(tInputs, function (k, input) {
            if (k === (tInputs.length -1)) {
                nextIndex = nextIndex + parseInt($(input).attr("id").toString().split(strConcatId)[3]);
            }
        });

        $.each(inputNames, function (k, name) {
            var idConcated = [name,cod,grade,indexMatriz].join(strConcatId);
            var inpt = $("#" + idConcated);
            if (inpt.length) {
                var elemCloned = inpt.clone();

                var strName = name + "[" + [cod,grade,nextIndex].join("][") + "]";
                elemCloned.attr("name", strName);

                var strId = [name,cod,grade,nextIndex].join(strConcatId);
                elemCloned.attr("id", strId);

                console.log(name);
                console.log(name in ["lote", "unMedida", "qtdConferida", "qtdUnidFracionavel", "qtdAvaria"]);
                if (name in ["lote", "unMedida", "qtdConferida", "qtdUnidFracionavel", "qtdAvaria"]) {
                    console.log("entrou");
                    elemCloned.val("");
                }

                var tdElement = inpt.parent();
                tdElement.append("<br>");
                tdElement.append(elemCloned);
            }
        });

        var strIdBtn = ["btnRemove",cod,grade,nextIndex].join(strConcatId);
        btnAdd.parent().append($("<img style='cursor: pointer' src='/img/icons/cross.png' class='btnRemover' title='Remover' id ='" + strIdBtn + "'>"));

    });

    $(".btnRemover").live("click", function () {
        var element = $(this);
        return $.wmsDialogConfirm({
            title: 'Tem certeza?',
            msg: "Deseja realmente remover esta linha?"
        }, remover, element);
    });

    function remover(elem) {
        var inpt = $(elem);
        var arrId = inpt.attr("id").toString().split(strConcatId);
        var cod = arrId[1];
        var grade = arrId[2];
        var index = arrId[3];

        $.each(inputNames, function (k, name) {
            var idConcated = [name,cod,grade,index].join(strConcatId);
            var inpt = $("#" + idConcated);
            if (inpt.length) {
                inpt.remove();
            }
        });

        var strIdBtn = ["#btnRemove",cod,grade,index].join(strConcatId);
        $(strIdBtn).remove();
    }

    <?php } ?>

    $(function () {
        $(".qtdUnidFracionavel").each(function () {
            getUnidadeFracionavel($(this));
        })
    });

    function getUnidadeFracionavel (elem) {
        var arrId = elem.attr("id").toString().split(strConcatId);
        var cod = arrId[1];
        var grade = arrId[2];
        var index = arrId[3];
        var strId = [cod,grade,index].join(strConcatId);
        var inptSelect = $("#embalagem" + strId).children("[data-fracionavel-default='S']").text();
        var arrUnids = <?php echo json_encode(\Wms\Domain\Entity\Produto::$listaUnidadeMedida)?>;
        var strUnid = arrUnids[inptSelect] + "S";
        var txtUnidElem = $("#txtUnid" + strId);
        if (txtUnidElem.length) {
            txtUnidElem.text(strUnid);
        }
    }

    $("#enviar").click(function () {
        var produtos = [];
        $(".dthValidade").each(function () {
            var input = $(this);
            var spl = input.attr("id").split(strConcatId);
            var id = spl[1];
            var grade = spl[2];
            var data = input.val();
            produtos.push({id:id, grade:grade, data:data});
        });
        var teste = {data:JSON.stringify(produtos)};
        var itens = '';
        if (produtos.length > 0) {
            $.post(URL_BASE + '/recebimento/check-shelflife-ajax', teste, function (data) {
                var result = data.result;
                var isOk = true;
                $.each(result, function (item, isValido) {
                    if (!isValido) {
                        isOk = false;
                        itens += item + "<br>";
                    }
                });

                if (!isOk) {
                    var password = $("#password");
                    password.keypress(function (e) {
                        var code = e.keyCode || e.which;
                        if (code === 13) {
                            e.preventDefault();
                            checkAutorizacao($("#modal-autorizacao"), $(this).val());
                        }
                    });
                    var checkAutorizacao = function (modal, senha) {
                        $.post(URL_BASE + '/recebimento/check-senha-autorizacao-ajax', {senha: senha}, function (data) {
                            if (data.result === true) {
                                modal.dialog("close");
                                $("#form-autorizacao").resetForm();
                                $("#btnCconferencia").trigger('click');
                            } else {
                                alert("Senha incorreta!!!");
                                $("#form-autorizacao").resetForm();
                            }
                        });
                    };
                    $("#msg-result").html(itens);
                    $("#dialog:ui-dialog").dialog("destroy");
                    $("#modal-autorizacao").dialog({
                        resizable: false,
                        height: 250,
                        width: 400,
                        modal: true,
                        buttons: {
                            "Confirmar": function () {
                                if (password.val() !== '' && password.val() !== null) {
                                    checkAutorizacao($(this), password.val());
                                } else {
                                    alert("Nenhuma senha foi informada!");
                                    $("#form-autorizacao").resetForm();
                                    $(this).dialog("close");
                                }
                            },
                            'Cancelar': function () {
                                $("#form-autorizacao").resetForm();
                                $(this).dialog("close");
                            }
                        }
                    })
                } else {
                    $("#btnCconferencia").trigger('click');
                }
            });
        } else {
            $("#btnCconferencia").trigger('click');
        }
    })
</script>