
<?php echo $this->render('recebimento/cabecalho.phtml'); ?>

<style>
    table.produtos th {
        text-align: left;
        font-weight: bold;
    }
    table.produtos tbody td {
        text-align: left;
        border-bottom: 1px solid #CCC;
    }
    label {
        display: inline !important;
    }
</style>

<form id="form-recebimento-conferencia" method="post" class="saveForm">    
    <div id="quantidade-grid" class="grid">
        <table class="gTable produtos">
            <thead>
                <tr class="gTTitle">
                    <td>Cód. - Produto</td>
                    <td>Grade</td>
                    <td>Unidade</td>
                    <td>Quantidade</td>
                    <td>Peso</td>
                    <td>Data Validade</td>
                    <td>Qtde. Avaria</td>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->produtos as $produto) { ?>
                    <tr height="35">
                        <td><?php echo $produto['codigo'] . ' - ' . $produto['descricao'] ?></td>
                        <td ><?php echo $produto['grade'] ?></td>
                        <td>

                            <?php
                            $medida = null;
                            foreach ($this->unMedida as $key => $medidas) {
                                if ($medidas['produto'] == $produto['codigo'] && $medidas['grade'] == $produto['grade']) {
                                    $medida[$medidas['id']] = $medidas['descricao'];
                                }
                            }
                            if (isset($medida) && $medida != null) {
                                //($name, $value = null, $attribs = null, $options = null, $listsep = "<br />\n")
                                echo $this->formSelect("unMedida[{$produto['codigo']}][{$produto['grade']}]", null, array(
                                    'validators' => array('numeric'),
                                    'alt' => 'number',
                                    'class' => "unMedida",
                                    'title' => "[{$produto['codigo']}][{$produto['grade']}]",
                                ), $medida);
                            } else {
                                echo '-';
                            }
                            ?>
                        </td>
                        <td>
                            <?php
                            echo $this->formHidden("qtdNF[{$produto['codigo']}][{$produto['grade']}]", $produto['quantidade'], array(
                                'title' => "[{$produto['codigo']}][{$produto['grade']}]",
                                'class' => "qtdNF",
                            ));
                            echo $this->formText("qtdConferida[{$produto['codigo']}][{$produto['grade']}]", 0, array(
                                'size' => 8,
                                'validators' => array('numeric'),
                                'alt' => 'number',
                                'class' => "qtdConferida",
                                'title' => "[{$produto['codigo']}][{$produto['grade']}]",
                            ));
                            ?>
                        </td>

                        <td>
                            <?php
                            echo $this->formText("numPeso[{$produto['codigo']}][{$produto['grade']}]", 0, array(
                                'size' => 8,
                                'validators' => array('numeric'),
                                'alt' => 'centesimal',
                                'class' => 'numPeso',
                                'title' => "[{$produto['codigo']}][{$produto['grade']}]",
                            ));
                            ?>
                        </td>

                        <td>
                            <?php if ($produto['possui_validade'] == 'S') {

                                $inputName = "dataValidade[{$produto['codigo']}][{$produto['grade']}]";
                                $id = "dataValidade-{$produto['codigo']}-{$produto['grade']}";
                                $date = new DateTime('now');

                                echo '<input type="text" name="'.$inputName.'" id="'.$id.'" value="' . $date->format('d/m/Y') . '" size="11" maxLength="10" alt="date" class="date dthValidade" />';
                            }?>
                        </td>
                        <td>
                            <?php
                            echo $this->formHidden("qtdAvaria[{$produto['codigo']}][{$produto['grade']}]", 0, array(
                                'size' => 8,
                                'validators' => array('numeric'),
                                'alt' => 'number',
                                'class' => "qtdAvaria",
                                'title' => "[{$produto['codigo']}][{$produto['grade']}]",
                                'readyonly' => 'readyonly',
                            ));
                            ?>
                        </td>
                    </tr>
                <?php } ?>
                <tr style="line-height: 50px;">
                    <td></td>
                    <td colspan="4">
                        <label>Conferente: 
                            <?php
                            $conferentes[] = 'Selecione';
                            foreach ($this->conferentes as $key => $conferente) {
                                $conferentes[$key] = $conferente;
                            }
                            //($name, $value = null, $attribs = null, $options = null, $listsep = "<br />\n")
                            echo $this->formSelect("idPessoa", null, null, $conferentes);
                            ?> 
                        </label>
                    </td>
                    <td colspan="2">
                        <button type="button" id="enviar" class="btn" style="margin-top: 0;">Salvar e Finalizar</button>
                        <?php
                        echo $this->formSubmit("submit", "Salvar e Finalizar", array('id' => 'btnCconferencia', 'class' => 'btn', 'style' => 'margin-top: 0; display:none;'));
                        ?>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</form>
<div id="modal-autorizacao" title="Confirmação" style="display: none">
    <form id="form-autorizacao">
        <p>A validade do(s) produto(s) abaixo é menor que o esperado:</p><br>
        <p id="msg-result"></p><br>
        <p>Para proceguir insira a senha de autorização:</p><br>
        <fieldset>
            <label for="password">Senha de autorização: </label>
            <input type="password" name="password" id="password" class="text ui-widget-content ui-corner-all">
            <input type="submit" tabindex="-1" style="position:absolute; top:-1000px">
        </fieldset>
    </form>
</div>

<script>
    $("#enviar").click(function () {
        var produtos = [];
        $(".dthValidade").each(function () {
            var input = $(this);
            var spl = input.attr("id").split("-");
            var id = spl[1];
            var grade = spl[2];
            var data = input.val();
            produtos.push({id:id, grade:grade, data:data});
        });
        var teste = {data:JSON.stringify(produtos)};
        var itens = '';
        if (produtos.length > 0) {
            $.post(URL_BASE + '/recebimento/check-shelflife-ajax', teste, function (data) {
                var result = data.result;
                var isOk = true;
                $.each(result, function (item, isValido) {
                    if (!isValido) {
                        isOk = false;
                        itens += item + "<br>";
                    }
                });

                if (!isOk) {
                    var password = $("#password");
                    password.keypress(function (e) {
                        var code = e.keyCode || e.which;
                        if (code === 13) {
                            e.preventDefault();
                            checkAutorizacao($("#modal-autorizacao"), $(this).val());
                        }
                    });
                    var checkAutorizacao = function (modal, senha) {
                        $.post(URL_BASE + '/recebimento/check-senha-autorizacao-ajax', {senha: senha}, function (data) {
                            if (data.result === true) {
                                modal.dialog("close");
                                $("#form-autorizacao").resetForm();
                                $("#btnCconferencia").trigger('click');
                            } else {
                                alert("Senha incorreta!!!");
                                $("#form-autorizacao").resetForm();
                            }
                        });
                    };
                    $("#msg-result").html(itens);
                    $("#dialog:ui-dialog").dialog("destroy");
                    $("#modal-autorizacao").dialog({
                        resizable: false,
                        height: 250,
                        width: 400,
                        modal: true,
                        buttons: {
                            "Confirmar": function () {
                                if (password.val() !== '' && password.val() !== null) {
                                    checkAutorizacao($(this), password.val());
                                } else {
                                    alert("Nenhuma senha foi informada!");
                                    $("#form-autorizacao").resetForm();
                                    $(this).dialog("close");
                                }
                            },
                            'Cancelar': function () {
                                $("#form-autorizacao").resetForm();
                                $(this).dialog("close");
                            }
                        }
                    })
                }
            });
        } else {
            $("#btnCconferencia").trigger('click');
        }
    })
</script>