
<?php echo $this->render('recebimento/cabecalho.phtml'); ?>

<style>
    table.produtoConferencias th {
        text-align: left;
        font-weight: bold;
    }
    table.produtoConferencias tbody td {
        text-align: left;
        border-bottom: 1px solid #CCC;
    }
    label {
        display: inline !important;
    }
</style>
<form id="recebimento-divergencia-form" method="post" class="saveForm">
    <?php
    echo $this->formHidden("acaoFinalizacao", "");
    $colspan = 2;
    if($this->lote == true){
        $colspan = 3;
    }

    ?>
    <div id="quantidade-grid" class="grid">
        <table class="gTable produtoConferencias">
            <thead>
            <tr style="text-align: center; font-weight: bold; border-left: #666; background: #CCC; line-height: 22px">
                <td colspan="<?php echo $colspan ?>">Item</td>
                <td colspan="3">Qtde. Recebida </td>
                <td colspan="3">Devolução</td>
            </tr>
            <tr class="gTTitle">
                <td>Cód. - Produto</td>
                <td>Grade</td>
                <?php
                if($this->lote == true){
                ?>
                    <td>Lote</td>
                <?php
                }
                ?>
                <td>Referência</td>
                <td>Qtde. Conferida </td>
                <td>Qtde. Avaria</td>
                <td>Qtde. Divergência</td>
                <td>Nota Fiscal</td>
                <td>Observação</td>
            </tr>
            </thead>
            <tbody>
            <?php
            $temDivergenciaDeVolume = false;
            foreach ($this->produtosConferencia as $produtoConferencia):
                $tipoDivergencia = ($produtoConferencia['qtdDivergencia'] < 0) ? 'Falta' : 'Sobra';
                ?>
                <tr height="35">
                    <td><?php echo $produtoConferencia['idProduto'] . ' - ' . $produtoConferencia['dscProduto'] ?></td>
                    <td><?php echo $produtoConferencia['grade'] ?></td>
                    <?php
                    if($this->lote == true){
                    ?>
                        <td><?php echo $produtoConferencia['lote'] ?></td>
                        <?php
                    }
                    ?>
                    <td><?php echo $produtoConferencia['referencia'] ?></td>
                    <?php if ($produtoConferencia['possui_peso_variavel'] == 'S') : ?>
                        <td style="text-align: center" ><?php echo $produtoConferencia['qtdConferida'] ?></td>
                        <td style="text-align: center" ><?php echo $produtoConferencia['qtdAvaria'] ?></td>
                        <td ><?php echo $produtoConferencia['qtdDivergencia'] ?></td>
                    <?php else : ?>
                        <td style="text-align: center" ><?php echo $produtoConferencia['qtdConferida'] ?></td>
                        <td style="text-align: center" ><?php echo $produtoConferencia['qtdAvaria'] ?></td>
                        <td ><?php echo "$produtoConferencia[qtdDivergencia] ($tipoDivergencia)" ?></td>
                    <?php endif; ?>
                    <?php if ($produtoConferencia['divergenciaVolumes'] == 'N') :?>
                    <td>
                        <?php
                        echo $this->formSelect("notasFiscais[{$produtoConferencia['id']}]", '', array('style' => 'max-width: 150px', 'class' => 'notaFiscal'), $produtoConferencia['nfs']);
                        ?>
                    </td>
                    <td align="center">
                        <?php
                        echo $this->formSelect("motivosDivergencia[{$produtoConferencia['id']}]", '', array('style' => 'width: 250px', 'class' => 'motivosDivergencia'), $this->motivosDivergencia);
                        ?>
                    </td>
                    <?php else : $temDivergenciaDeVolume = true;?>
                        <td colspan="2" style="text-align: center !important">
                            Divergência entre volumes. Recontagem obrigatória
                        </td>
                    <?php endif;?>
                </tr>
            <?php endforeach; ?>
            <tr style="line-height: 50px;">
                <td colspan="2">
                    Conferente:
                    <strong>
                        <?php if (isset($this->ordemServicoEntity) && !empty($this->ordemServicoEntity)) : ?>
                            <?php echo $this->ordemServicoEntity->getPessoa()->getNome(); ?>
                        <?php endif; ?>
                    </strong>
                </td>
                <td colspan="3">
                    <?php
                    echo $this->formSubmit("btnRecontagem", "Gerar Recontagem", array('class' => 'btn', 'style' => 'margin-top: 0;'));
                    ?>
                </td>
                    <?php if (!$temDivergenciaDeVolume) : ?>
                    <td colspan="<?php echo $colspan+1 ?>">
                        <?php
                        echo '<label>Senha de Divergencia: </label>';
                        echo $this->formPassword("senhaDivergencia", '', array(
                            'size' => '10',
                            'maxlength' => '20',
                        ));
                        echo $this->formSubmit("btnDivergencia", "Fechar Recebimento com Divergencia", array('class' => 'btnAlert', 'style' => 'margin: 0 0 0 10px;'));
                        ?>
                    </td>
                    <?php endif; ?>
            </tr>
            </tbody>
        </table>
    </div>
</form>
