<script>
    $(document).ready(function(){
        $('#todos').live('click',function(){
            var checked_status = this.checked;
            $("input").each(function()
            {
                $(this).attr('checked',checked_status);
            });
        });
    });

    function clk(tipo) {
        event.preventDefault();
        var redirect =  URL_MODULO + '/recebimento/imprimir-produto-ajax/';

        var table = document.getElementsByClassName("recebimento-imprimir-pdf");
        var rows = table[0].getElementsByClassName("gTResultSet");
        var form = document.createElement('form');
        var selecionado = false;
        var idRecebimento = document.getElementById('idRecebimento').value;

        document.body.appendChild(form);
        form.method = 'post';
        form.action = redirect;
        form.target = "_blank";

        for(var i = 0 ; i < rows.length ; i++) {
            var columns = rows[i].getElementsByTagName('td');
            var check   = columns[0].children.item(0).checked;
            var countSelecionadas = 0;

            if (check == true) {
                var codProduto = columns[1].innerHTML;
                var grade = columns[2].innerHTML;

                selecionado = true;

                var inputProduto = document.createElement('input');
                inputProduto.type = 'hidden';
                inputProduto.name = 'produtos[]';
                inputProduto.value = codProduto;
                form.appendChild(inputProduto);

                var inputGrade = document.createElement('input');
                inputGrade.type = 'hidden';
                inputGrade.name = 'grades[]';
                inputGrade.value = grade;
                form.appendChild(inputGrade);
            }
        }

        if (selecionado == false ) {
            alert("Selecione ao menos um produto para imprimir");
            return;
        }

        var inputRecebimento = document.createElement('input');
        inputRecebimento.type = 'hidden';
        inputRecebimento.name = 'id';
        inputRecebimento.value = idRecebimento;
        form.appendChild(inputRecebimento);

        var inputTipo = document.createElement('input');
        inputTipo.type = 'hidden';
        inputTipo.name = 'tipo';
        inputTipo.value = tipo;
        form.appendChild(inputTipo);

        form.submit();
    }

</script>

<form id="produtos-form" method="post" class="saveForm" action="">
    <button id="btnEtqProduto"     onclick="clk('produto')" class="btn">Imprimir Etiqueta de Produto</button>
    <button id="btnEtqRecebimento" onclick="clk('recebimento')" class="btn">Imprimir Dados do Recebimento</button>
    <input type="hidden" id="idRecebimento" value="<?php echo $this->idRecebimento?>" name="<?php echo $this->idRecebimento?>">
    <br>
    <br>
    <div id="imprimir-grid" class="grid">
        <table class="gTable recebimento-imprimir-pdf">
            <caption>Produtos para Imprimir</caption>
            <p><label><input style="vertical-align: middle" type="checkbox" id="todos"> Selecionar Todos<br></label></p>
            <tbody>
            <tr class ="gTTitle">
                <td>Check</td>
                <td>Código</td>
                <td>Grade</td>
                <td>Produto</td>
                <td>Quantidade</td>
            </tr>
            <?php
            foreach ($this->produtos as $produto):
                $fontColor = "black";
                $liberado = true;
                $checked = '';
                if ($produto['IMPRIMIR'] == 'S') {
                    $checked = 'checked="true"';
                }
                $this->color = !($this->color);?>
                <tr style="color: <?php echo ($fontColor)?>" class = "<?php if (!$this->color) {echo 'gTResultSet gRowColor';} else {echo 'gTResultSet';}?>">
                    <td><input name="produto[]" value="<?php echo $produto['COD_PRODUTO'] ?>" type="checkbox" <?php echo $checked?> /></td>
                    <td><?php echo $produto['COD_PRODUTO'] ?></td>
                    <td><?php echo $produto['DSC_GRADE'] ?></td>
                    <td><?php echo $produto['DSC_PRODUTO'] ?></td>
                    <td><?php echo $produto['QTD'] ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</form>
