<?php
///**
// * Created by PhpStorm.
// * User: Luis Fernando
// * Date: 09/03/2018
// * Time: 14:51
// */
//echo $this->form;
//?>
<!--<script src="--><?php //echo $this->baseUrl('angularJS/controllers/estoque-proprietario/proprietarioGridCtrl.js') ?><!--"></script>-->

<style>
    .gTTitle a.sort span{ background:none}
    .table-info-grid{
    border-collapse: collapse;
    } 
    .table-info-grid th{
    padding: 5px 10px; 
    width: 16.66%; 
    }
    .table-info-grid td{
    vertical-align: middle;
    text-align: center
    }
    </style>
<div ng-controller="proprietarioGridCtrl" style="font-size: 12px;" class="ui-dialog-content ui-widget-content">
    <form id="mainForm" enctype="application/x-www-form-urlencoded" accept-charset="UTF-8" action="">
        <div>
            <fieldset id="fieldset-Buscar">
                <legend>Resultado do inventário {{inventario.id}} ({{inventario.descricao}})</legend>
                <div class="field" style="margin: 0; padding-top: 10px">
                    <table class="table-info-grid">
                        <thead>
                            <tr>
                                <th>Controlar validade?</th>
                                <th>Número mínimo de contagens iguais?</th>
                                <th>Comparar com estoque atual?</th>
                                <th>Permitir mesmo usuário em N contagens?</th>
                                <th>Forçar contagem de todos os itens no endereço?</th>
                                <th>Contar volumes individualmente?</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>{{inventario.controlaValidadeLbl}}</td>
                                <td>{{inventario.numContagens}}</td>
                                <td><img ng-if="inventario.comparaEstoque" alt="Sim" src="/img/icons/tick.png"><img ng-if="!inventario.comparaEstoque" alt="Não" src="/img/icons/cross.png"></td>
                                <td><img ng-if="inventario.usuarioNContagens" alt="Sim" src="/img/icons/tick.png"><img ng-if="!inventario.usuarioNContagens" alt="Não" src="/img/icons/cross.png"></td>
                                <td><img ng-if="inventario.contarTudo" alt="Sim" src="/img/icons/tick.png"><img ng-if="!inventario.contarTudo" alt="Não" src="/img/icons/cross.png"></td>
                                <td><img ng-if="inventario.volumesSeparadamente" alt="Sim" src="/img/icons/tick.png"><img ng-if="!inventario.volumesSeparadamente" alt="Não" src="/img/icons/cross.png"></td>
                            </tr>
                        </tbody>
                        </table>
                    </div>
                </fieldset>
            </div>
        </form>
    <fieldset id="fs-grid-selected">
        <legend>Resultado</legend>
        <div class="grid">
            <div class="gMassAction">
                <div class="gAction">
                    <button ng-show="results.length" type="button" class="btn-grid" ng-click="export(\pdf\)"><span>Exportar PDF</span></button>
                    <button ng-show="results.length" type="button" class="btn-grid" ng-click="export(\csv\)"><span>Exportar CSV</span></button>
                    </div>
                </div>
            <table class="gTable" style="width:1127px!important">
                <tbody >
                <tr class="gTTitle">
                    <td ng-repeat="column in gridColumns" width="{{column.width}}">
                        <div><a href="" title="" class="sort" ng-click="ordenarPor(column.name)"><span>{{column.label}}</span></a></div>
                        <div align="center" class="field"><input ng-if="column.filter" type="text" ng-model="objectFilter[column.name]" ng-attr-ui-mask="{{column.filter.masked && column.filter.maskFilter || \\}}" ng-attr-model-view-value="{{column.filter.masked && true || false}}" size="{{column.filter.size}}" class=""></div>
                        </td>
                    </tr>
                </tbody>
                </table>
            <div style="overflow-y:scroll; max-height: 340px" >
                <table class="gTable">
                    <tr ng-show="showLoading">
                        <td colspan="100%" align="center">
                            <img height="150%" src="/img/ajax-bar-loader.gif" width="50%">
                            </td>
                        </tr>
                    <tr class="gTResultSet" ng-repeat="result in results | filter:objectFilter | orderBy:tbOrderBy:direction:typeSensitiveComparator">
                        <td ng-repeat="column in gridColumns" width="{{column.width}}">
                            <div>{{result[column.name]}}</div>
                            </td>
                        </tr>
                    <tr>
                        <td colspan="100%" align="center" ng-show="noResults" >Nenhum produto/endereço teve divergência</td>
                        </tr>
                    </table>
                </div>
            </div>
        </fieldset>
    </div>
