INSERT INTO VERSAO (DTH, NUMERO_VERSAO, SCRIPT) VALUES (SYSDATE, '6.21.0','01-integracaoEmbalagens.sql');

ALTER TABLE TR_PEDIDO ADD (
  FATOR_EMBALAGEM_VENDA NUMBER(20,10),
  QTD_EMBALAGEM_VENDA NUMBER(20,10)
);

ALTER TABLE PEDIDO_PRODUTO ADD (
  FATOR_EMBALAGEM_VENDA NUMBER(20,10),
  QTD_EMBALAGEM_VENDA NUMBER(20,10)
);

UPDATE TR_PEDIDO SET FATOR_EMBALAGEM_VENDA = 1 WHERE FATOR_EMBALAGEM_VENDA iS NULL;

UPDATE TR_PEDIDO SET QTD_EMBALAGEM_VENDA = (QTD/ FATOR_EMBALAGEM_VENDA) WHERE QTD_EMBALAGEM_VENDA IS NULL;

UPDATE PEDIDO_PRODUTO SET FATOR_EMBALAGEM_VENDA = 1 WHERE FATOR_EMBALAGEM_VENDA iS NULL;

UPDATE PEDIDO_PRODUTO SET QTD_EMBALAGEM_VENDA = (QUANTIDADE/ FATOR_EMBALAGEM_VENDA) WHERE QTD_EMBALAGEM_VENDA IS NULL;


