INSERT INTO VERSAO (DTH, NUMERO_VERSAO, SCRIPT) VALUES (SYSDATE, '6.21.0','01-integracaoEmbalagens.sql');

ALTER TABLE TR_PEDIDO ADD (
  FATOR_EMBALAGEM_VENDA NUMBER(20,10),
  QTD_EMBALAGEM_VENDA NUMBER(20,10)
);

ALTER TABLE PEDIDO_PRODUTO ADD (
  FATOR_EMBALAGEM_VENDA NUMBER(20,10),
  QTD_EMBALAGEM_VENDA NUMBER(20,10)
);