INSERT INTO VERSAO (DTH, NUMERO_VERSAO, SCRIPT) VALUES (SYSDATE, '6.21.0','02-motivo-Corte.sql');

CREATE TABLE MOTIVO_CORTE
(
  COD_MOTIVO_CORTE  NUMBER (8) NOT NULL ,
  DSC_MOTIVO_CORTE  VARCHAR (200) NOT NULL ,
  COD_EXTERNO  NUMBER (8)
)
LOGGING ;

ALTER TABLE MOTIVO_CORTE ADD CONSTRAINT Motivo_corte_PK PRIMARY KEY ( COD_MOTIVO_CORTE ) ;

CREATE SEQUENCE SQ_MOTIVO_CORTE_01
INCREMENT BY 1
START WITH 1
MAXVALUE 999999999999999999999999999
MINVALUE 0
NOCYCLE
NOCACHE
NOORDER;


INSERT INTO MOTIVO_CORTE(COD_MOTIVO_CORTE, DSC_MOTIVO_CORTE) VALUES (SQ_MOTIVO_CORTE_01.NEXTVAL, 'PRODUTO AVARIADO NO CARREGAMENTO');

INSERT INTO MOTIVO_CORTE(COD_MOTIVO_CORTE, DSC_MOTIVO_CORTE) VALUES (SQ_MOTIVO_CORTE_01.NEXTVAL, 'PRODUTO SEM ESTOQUE');

INSERT INTO MOTIVO_CORTE(COD_MOTIVO_CORTE, DSC_MOTIVO_CORTE) VALUES (SQ_MOTIVO_CORTE_01.NEXTVAL, 'PROBLEMAS NA VENDA');

INSERT INTO MOTIVO_CORTE(COD_MOTIVO_CORTE, DSC_MOTIVO_CORTE) VALUES (SQ_MOTIVO_CORTE_01.NEXTVAL, 'PEDIDO CANCELADO');
