INSERT INTO VERSAO (DTH, NUMERO_VERSAO, SCRIPT) VALUES (SYSDATE, '6.21.0','02-motivo-Corte.sql');

CREATE TABLE MOTIVO_CORTE
(
  COD_MOTIVO_CORTE  NUMBER (8) NOT NULL ,
  DSC_MOTIVO_CORTE  VARCHAR (200) NOT NULL ,
  COD_EXTERNO  VARCHAR(10)
)
LOGGING ;

ALTER TABLE MOTIVO_CORTE ADD CONSTRAINT Motivo_corte_PK PRIMARY KEY ( COD_MOTIVO_CORTE ) ;

CREATE SEQUENCE SQ_MOTIVO_CORTE_01
INCREMENT BY 1
START WITH 1
MAXVALUE 999999999999999999999999999
MINVALUE 0
NOCYCLE
NOCACHE
NOORDER;


INSERT INTO MOTIVO_CORTE(COD_MOTIVO_CORTE, DSC_MOTIVO_CORTE) VALUES (SQ_MOTIVO_CORTE_01.NEXTVAL, 'PRODUTO AVARIADO NO CARREGAMENTO');
INSERT INTO MOTIVO_CORTE(COD_MOTIVO_CORTE, DSC_MOTIVO_CORTE) VALUES (SQ_MOTIVO_CORTE_01.NEXTVAL, 'PRODUTO SEM ESTOQUE');
INSERT INTO MOTIVO_CORTE(COD_MOTIVO_CORTE, DSC_MOTIVO_CORTE) VALUES (SQ_MOTIVO_CORTE_01.NEXTVAL, 'PROBLEMAS NA VENDA');
INSERT INTO MOTIVO_CORTE(COD_MOTIVO_CORTE, DSC_MOTIVO_CORTE) VALUES (SQ_MOTIVO_CORTE_01.NEXTVAL, 'PEDIDO CANCELADO');
INSERT INTO MOTIVO_CORTE(COD_MOTIVO_CORTE, DSC_MOTIVO_CORTE) VALUES (SQ_MOTIVO_CORTE_01.NEXTVAL, 'CORTADO NO ERP');


INSERT INTO recurso (dsc_recurso, cod_recurso, cod_recurso_pai, nom_recurso) VALUES ('Modelo de Separacao', SQ_RECURSO_01.NEXTVAL, 0, 'expedicao:motivo-corte');

INSERT INTO recurso_acao (cod_recurso_acao, cod_recurso, cod_acao, dsc_recurso_acao)
VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'expedicao:motivo-corte'),
(SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'add'), 'Adicionar');

INSERT INTO recurso_acao (cod_recurso_acao, cod_recurso, cod_acao, dsc_recurso_acao)
VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'expedicao:motivo-corte'),
(SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'edit'), 'Editar');

INSERT INTO recurso_acao (cod_recurso_acao, cod_recurso, cod_acao, dsc_recurso_acao)
VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'expedicao:motivo-corte'),
(SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'delete'), 'Deletar');

INSERT INTO recurso_acao (cod_recurso_acao, cod_recurso, cod_acao, dsc_recurso_acao)
VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'expedicao:motivo-corte'),
(SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'index'), 'Início');

INSERT INTO MENU_ITEM (COD_MENU_ITEM, COD_RECURSO_ACAO, COD_PAI, DSC_MENU_ITEM, NUM_PESO, DSC_URL, DSC_TARGET, SHOW)
VALUES (SQ_MENU_ITEM_01.NEXTVAL,
(SELECT COD_RECURSO_ACAO FROM RECURSO_ACAO WHERE COD_RECURSO = (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'expedicao:motivo-corte') AND COD_ACAO = (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'index')),
(SELECT COD_MENU_ITEM FROM MENU_ITEM WHERE DSC_MENU_ITEM = 'Cadastros'),
'Motivo de Corte',
10, '#', '_self', 'S');

INSERT INTO PARAMETRO (COD_PARAMETRO, COD_CONTEXTO_PARAMETRO, DSC_PARAMETRO, DSC_TITULO_PARAMETRO, IND_PARAMETRO_SISTEMA, COD_TIPO_ATRIBUTO, DSC_VALOR_PARAMETRO)
VALUES (SQ_PARAMETRO_01.NEXTVAL,
(SELECT COD_CONTEXTO_PARAMETRO FROM CONTEXTO_PARAMETRO WHERE DSC_CONTEXTO_PARAMETRO = 'EXPEDICAO'),
'COD_MOTIVO_CORTE_AUTOMATICO',
'Código do Motivo de Corte para Cortes Automáticos',
'N',
'A',
'2');

INSERT INTO PARAMETRO (COD_PARAMETRO, COD_CONTEXTO_PARAMETRO, DSC_PARAMETRO, DSC_TITULO_PARAMETRO, IND_PARAMETRO_SISTEMA, COD_TIPO_ATRIBUTO, DSC_VALOR_PARAMETRO)
VALUES (SQ_PARAMETRO_01.NEXTVAL,
(SELECT COD_CONTEXTO_PARAMETRO FROM CONTEXTO_PARAMETRO WHERE DSC_CONTEXTO_PARAMETRO = 'EXPEDICAO'),
'COD_MOTIVO_CORTE_INTEGRACAO',
'Código do Motivo de Corte para Integração',
'N',
'A',
'5');

ALTER TABLE PEDIDO_PRODUTO ADD(
   COD_MOTIVO_CORTE  NUMBER(8)
);

ALTER TABLE PEDIDO_PRODUTO
  ADD CONSTRAINT PP_MOTIVO_CORTE_FK FOREIGN KEY (COD_MOTIVO_CORTE) REFERENCES MOTIVO_CORTE (COD_MOTIVO_CORTE) NOT DEFERRABLE ;
