ALTER TABLE RESERVA_ESTOQUE_EXPEDICAO ADD(
   COD_PEDIDO NUMBER(8,0)
);

INSERT INTO RECURSO (COD_RECURSO, COD_RECURSO_PAI, DSC_RECURSO, NOM_RECURSO) VALUES (SQ_RECURSO_01.NEXTVAL, 0, 'Equipamentos', 'equipamento');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO LIKE 'equipamento'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO LIKE 'index'), 'Equipamentos');
INSERT INTO MENU_ITEM (COD_MENU_ITEM, COD_RECURSO_ACAO, COD_PAI, DSC_MENU_ITEM, NUM_PESO, DSC_URL, DSC_TARGET, SHOW) VALUES (SQ_MENU_ITEM_01.NEXTVAL, (SELECT COD_RECURSO_ACAO FROM RECURSO_ACAO WHERE COD_RECURSO LIKE (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO LIKE 'equipamento') AND COD_ACAO LIKE (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO LIKE 'index')), 20, 'Equipamentos', 19, '#', '_self', 'S');

CREATE TABLE EQUIPAMENTO
  (
    COD_EQUIPAMENTO           NUMBER (8) NOT NULL,
    DESCRICAO                 VARCHAR2 (45) NOT NULL,
    MODELO                    VARCHAR2 (45),
    MARCA                     VARCHAR2 (45),
    NUM_PATRIMONIO            VARCHAR2 (45),
    COD_USUARIO               NUMBER (8) NOT NULL
  ) ;

CREATE SEQUENCE SQ_EQUIPAMENTO
INCREMENT BY 1
START WITH 1
MAXVALUE 999999999999999999999999999
MINVALUE 0
NOCYCLE
NOCACHE
NOORDER;

INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO LIKE 'equipamento'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO LIKE 'add'), 'Adicionar Equipamentos');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO LIKE 'equipamento'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO LIKE 'edit'), 'Adicionar Equipamentos');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO LIKE 'equipamento'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO LIKE 'delete'), 'Adicionar Equipamentos');