<script type="text/javascript">
    $(document).ready(function () {
        var validade = $('#validade');
        validade.hide();
        if ($('#parametroValidade').val() == 'S' && $('#validadeProduto').val() == 'S') {
            validade.show();
        }

        $('#validade').keyup(function (e) {
            var v = $('#validade').val();
            var key = e.which;
            if (key != 8) {
                if (v.match(/^\d{2}$/) !== null) {
                    $('#validade').val(v + '/');
                } else if (v.match(/^\d{2}\/\d{2}$/) !== null) {
                    $('#validade').val(v + '/');
                }
            }

            if (v != '' && v.length == 8) {
                avaria = document.getElementById('qtdAvaria');
                if (avaria) {
                    avaria.focus();
                    if (e.preventDefault) {
                        e.preventDefault();
                    } else {
                        e.returnValue = false;
                    }
                }
            }
        });

        $('#qtdConferida').keydown(function (e) {
            if (e.which == 13) {
                if (document.getElementById('qtdConferida').value != "") {
                    validade = document.getElementById('validade');
                    if (validade) {
                        if (validade.style.display != 'none') {
                            validade.focus();
                            if (e.preventDefault) {
                                e.preventDefault();
                            } else {
                                e.returnValue = false;
                            }
                        }
                    }
                }
            }
        });

        $('#qtdAvaria').keydown(function (e) {
            if (e.which === 13 && $('#parametroValidade').val() === 'S' && $('#validadeProduto').val() === 'S') {
                var dataSplit = validade.val().split('/');
                var dataAtual = new Date().toISOString().slice(0, 10);
                var dataValidade = new Date('20' + dataSplit[2], dataSplit[1] - 1, dataSplit[0]).toISOString().slice(0, 10);

                var confirma = true;

                if (dataAtual === dataValidade) {
                    confirma = confirm("A Data de validade informada " + validade.val() + " está vencendo hoje. Deseja continuar?");
                } else if (dataAtual > dataValidade) {
                    confirma = confirm("A Data de validade informada " + validade.val() + " está vencida. Deseja continuar?");
                }

                return confirma === true;
            }
        });

    });
</script>


<input type="hidden" id="codigoBarras" value="<?php echo $this->codigoBarras ?>">
<input type="hidden" id="parametroValidade" value="<?php echo $this->parametroValidade ?>">
<input type="hidden" id="validadeProduto" value="<?php echo $this->validadeProduto ?>">
<?php if ($this->produtosEndPicking) : ?>

    <table class="info">
        <caption>Endereço <?php echo $this->enderecoBipado ?> é picking dos produtos: </caption>
        <?php
        if (isset($this->produtosEndPicking)):
            ?>
            <tr>
                <td>
                    <div id="carousel">
                        <?php foreach ($this->produtosEndPicking as $produto): ?>
                            <div id="lista-produto<?php echo $produto['codProduto'] ?>"><?php echo $produto['descricao'] ?> - <?php echo $produto['grade'] ?></div>
                        <?php endforeach; ?>
                    </div>
                </td>
                <td style="width: 20%"> <button id="next"> >| </button></td>
            </tr>
            <?php
        endif;
        ?>
    </table>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#carousel').cycle({
                fx: 'turnDown',
                next: '#next',
                timeout: 0
            });

        });
    </script>

<?php endif; ?>

<?php echo $this->form; ?>

<?php if ($this->botoes) : ?>

    <div id="footer">
        <a style="margin-bottom: 10px;" href=<?php echo "/mobile/inventario/mudar-endereco/idInventarioEnd/" . $this->idInventarioEnd . "/idInventario/" . $this->idInventario . "/numContagem/" . $this->numContagem . "/divergencia/" . $this->divergencia ?> class="btn button finalizar mudar">Próximo Endereço</a>
    </div>

<?php endif; ?>

<div>
    <?php if ($this->enderecos) : ?>
        <ul>
            <?php foreach ($this->enderecos as $endereco) : ?>
                <li>
                <p>
                <?php if (isset($endereco['endereco'])) : ?>
                    <?php if (isset($endereco['zerar']) && $endereco['zerar'] > 0 && $this->codigoBarras != null) : ?>
                        <a class="gradientBtn btnZerar" style="color:#fff; cursor: pointer; border-radius: 4px;border-color: black; width: 50px;height: 40px;margin: 6px;font-weight: bold;padding: 2px; font-size: 12px;" name="btnFinalizar" type="submit" codigo-barras="<?php echo $endereco['zerar'] ?>">&nbsp;Zerar Item </a>
                    <?php endif; ?>
                    <?php echo $endereco['endereco']; ?>
                    <?php if (isset($endereco['zerar']) && $endereco['zerar'] < 0) : ?>
                        <?php echo " - <font color='red'>PRODUTO SEM COD.BARRAS</font>"; ?>
                    <?php endif; ?>
                <?php else : ?>
                    <?php echo $endereco['ENDERECO'] ?>
                <?php endif; ?>
                </p>
                </li>
            <?php endforeach; ?>
        </ul>
    <?php endif; ?>
</div>
<script type="text/javascript">
    $(".btnZerar").click(function () {
        $('form').find('#codigoBarras').val($(this).attr('codigo-barras'));
        $('form').append('<input type="hidden" id="desabilitar" name="desabilitar" value="1" />');
        $('#submit').click();
    });
</script>
<?php
if($this->parametroItem == 'S'){
    ?>
    <span id="dummy"></span>
    <bgsound id="bgSoundId" loop="0" volume="100" />
    <script>
        $('form #codigoBarras').focus();
        $("input").keydown(function (e) {
            if (e.which == 113) {
                $('.vali').show();
            }
        });
        function playSound(soundfile) {
            document.getElementById("dummy").innerHTML=
                "<embed src=\""+soundfile+"\" hidden=\"true\" autostart=\"true\" loop=\"false\" />";
        }

        var codbarras = 0;
        var validade = 'N';
        var erro = 0;

        $('#content').prepend('<div id="conferido" style="background: #13b213;text-align: center;font-weight: bold; display: none">Produto Conferido</div>');

        $('.field #codigoBarras').css('margin-bottom', '10px');
        $('#fieldset-identification div.field').prepend('<br /><label for="validade" class="field required vali" style="display:none">*Validade</label>' +
            '<input type="text" name="validade" id="validade" class="vali" value="" size="10" maxlength="8" placeholder="dd/mm/yy" style="text-align: center">');
        $('#fieldset-identification div.field').prepend('<label for="qtdConferida" class="field required">*Quantidade</label>' +
            '<input size="5" style="text-align: center" type="text" id="qtdConferida" name="qtdConferida" value="1"/>');

        var append = '<input type="hidden" id="idProduto" name="idProduto" value="0"/>' +
            '<input type="hidden" id="grade" name="grade" value="0"/>' +
            '<input type="hidden" id="codProdutoEmbalagem" name="codProdutoEmbalagem" value="0"/> ' +
            '<input type="hidden" id="contagemEndId" name="contagemEndId" value/>' +
            '<input type="hidden" id="qtdAvaria" name="qtdAvaria" value="0"/>' +
            '<input type="hidden" id="itemAitem" name="itemAitem" value="1"/>' +
            '<input type="hidden" name="divergencia" value="<?php echo $this->divergencia ?>" id="divergencia">';
        $( "form" ).append(append);

        $( "form" ).submit(function( event ) {
            $('#conferido').hide();
            if(codbarras == 0 || codbarras != $('form #codigoBarras').val()){
                codbarras = $('form #codigoBarras').val();
                $.ajax({
                    url: '/mobile/inventario/get-emb-produto-ajax/',
                    type: 'post',
                    dataType: 'json',
                    async: false,
                    data: $('form').serialize(),
                    success: function (data) {
                        $('#idProduto').val(data.idProduto);
                        $('#grade').val(data.grade);
                        $('#codProdutoEmbalagem').val(data.codProdutoEmbalagem);
                        $('#contagemEndId').val(data.contagemEndId);
                        if(data.status == 'ok'){
                            validade = data.validade;
                            if(data.validade == 'S'){
                                $('.vali').show();
                                if($('#validade').val() == ''){
                                    erro = 1;
                                    $('form #codigoBarras').val('');
                                    alert('Produto possui validade');
                                    return false;
                                }
                            }else{
                                $('.vali').hide();
                                $('#validade').val('');
                            }
                        }else{
                            erro = 1;
                            alert(data.msg);
                        }
                    }
                });
            }
            if(erro == 0) {
                $('form #codigoBarras').val('');
                if ($('#validade').val() == '' && validade == 'S') {
                    alert('Produto possui validade');
                    return false;
                } else {
                    $.ajax({
                        url: '/mobile/inventario/confirma-contagem/',
                        type: 'post',
                        dataType: 'json',
                        async: false,
                        data: $('form').serialize(),
                        success: function (data) {
                            if(data.status == 'ok'){
                                $('#conferido').show();
                                playSound("/confirm2.mp3");
                            }
                        }
                    });
                }
            }else{
                erro = 0;
            }
            return false;
        });
    </script>
<?php }?>
