<script type="text/javascript">
    $(document).ready(function(){
        var validade = $('#validade');
        validade.hide();
        if ($('#parametroValidade').val() == 'S' && $('#validadeProduto').val() == 'S') {
            validade.show();
        }

        $('#validade').keyup(function (e) {
            var v = $('#validade').val();
            var key = e.which;
            if (key != 8) {
                if (v.match(/^\d{2}$/) !== null) {
                    $('#validade').val(v + '/');
                }
                else if (v.match(/^\d{2}\/\d{2}$/) !== null) {
                    $('#validade').val(v + '/');
                }
            }

            if (v != '' && v.length == 8) {
                avaria = document.getElementById('qtdAvaria');
                if (avaria) {
                    avaria.focus();
                    if(event.preventDefault) {
                        event.preventDefault();
                    } else {
                        event.returnValue = false;
                    }
                }
            }
        });

        $('#qtdConferida').keyup(function (e) {
            if (e.which == 13) {
                if (document.getElementById('qtdConferida').value != "") {
                    validade   = document.getElementById('validade');
                    if (validade) {
                        validade.focus();
                        if(event.preventDefault) {
                            event.preventDefault();
                        } else {
                            event.returnValue = false;
                        }
                    }
                }
                if (document.getElementById('endereco').value != "") {
                    qtd        = document.getElementById('qtd');
                    if (qtd) {
                        qtd.focus();
                        if(event.preventDefault) {
                            event.preventDefault();
                        } else {
                            event.returnValue = false;
                        }
                    }
                }
            }
        })


    });
</script>

<input type="hidden" id="codigoBarras" value="<?php echo $this->codigoBarras?>">
<input type="hidden" id="parametroValidade" value="<?php echo $this->parametroValidade?>">
<input type="hidden" id="validadeProduto" value="<?php echo $this->validadeProduto?>">
<?php if ($this->produtosEndPicking) : ?>

    <table class="info">
        <caption>Endereço <?php echo $this->enderecoBipado ?> é picking dos produtos: </caption>
        <?php
        if (isset($this->produtosEndPicking)):
            ?>
            <tr>
                <td>
                    <div id="carousel">
                        <?php foreach ($this->produtosEndPicking as $produto): ?>
                            <div id="lista-produto<?php echo $produto['codProduto'] ?>"><?php echo $produto['descricao'] ?> - <?php echo $produto['grade'] ?></div>
                        <?php endforeach; ?>
                    </div>
                </td>
                <td style="width: 20%"> <button id="next"> >| </button></td>
            </tr>
        <?php
        endif;
        ?>
    </table>

    <script type="text/javascript">
        $(document).ready(function(){
            $('#carousel').cycle({
                fx:   'turnDown',
                next: '#next',
                timeout:  0
            });

        });
    </script>

<?php endif; ?>

<?php echo $this->form; ?>

<?php if ($this->botoes) : ?>

    <div id="footer">
    <a href=<?php echo "/mobile/inventario/mudar-endereco/idInventarioEnd/" . $this->idInventarioEnd . "/idInventario/" . $this->idInventario . "/numContagem/" . $this->numContagem . "/divergencia/" . $this->divergencia ?> class="btn button finalizar mudar">Próximo Endereço</a>
    </div>

<?php endif; ?>

    <div>
        <?php if ($this->enderecos) : ?>
            <ul>
                <?php foreach($this->enderecos as $endereco) : ?>
                     <li><?php echo $endereco ?></li>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>
    </div>


