<?php if (count($this->numContagens) > 0) : ?>
<div class="col-xs-12">
    <h3>Contagens</h3>
        <?php foreach ($this->numContagens as $numContagem) : ?>
            <div class="col-xs-12">
                <?php if ($numContagem['DIVERGENCIA'] != 1) : ?>
                    <a class="btn btn-xs gradientBtn" href="<?php echo $this->url(array('controller' => 'inventario', 'action' => 'consulta-endereco', 'idInventario' => $this->idInventario, 'numContagem' => $numContagem['CONTAGEM'])); ?>" title="<?php echo $this->idInventario ?>" > <?php echo $numContagem['CONTAGEM'] ?> Contagem</a>
                <?php else : ?>
                    <a class="btn btn-xs gradientBtn" href="<?php echo $this->url(array('controller' => 'inventario', 'action' => 'consulta-endereco', 'idInventario' => $this->idInventario, 'numContagem' => $numContagem['CONTAGEM'], 'divergencia' => 1)); ?>" title="<?php echo $this->idInventario ?>" > <?php echo $numContagem['CONTAGEM'] ?> Contagem Divergência</a>
                <?php endif; ?>
            </div>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
