INSERT INTO VERSAO (DTH, NUMERO_VERSAO, SCRIPT) VALUES (SYSDATE, '6.19.0','0-relatorio-cortes');


INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'expedicao:corte'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'relatorio'), 'Relatório de Cortes');

INSERT INTO MENU_ITEM (COD_MENU_ITEM, COD_RECURSO_ACAO, COD_PAI, DSC_MENU_ITEM, NUM_PESO, DSC_URL) VALUES
    (SQ_MENU_ITEM_01.NEXTVAL,0,(SELECT COD_MENU_ITEM FROM MENU_ITEM WHERE DSC_MENU_ITEM = 'Relatórios' AND COD_PAI = 0),
    'Expedição', 1, '#');

UPDATE MENU_ITEM SET COD_PAI = (SELECT COD_MENU_ITEM FROM MENU_ITEM WHERE COD_PAI = (SELECT COD_MENU_ITEM FROM MENU_ITEM WHERE DSC_MENU_ITEM = 'Relatórios' AND COD_PAI = 0) AND DSC_MENU_ITEM = 'Expedição') WHERE DSC_MENU_ITEM = 'Saída de Produtos';

INSERT INTO MENU_ITEM (COD_MENU_ITEM, COD_RECURSO_ACAO, COD_PAI, DSC_MENU_ITEM, NUM_PESO, DSC_URL) VALUES (SQ_MENU_ITEM_01.NEXTVAL,
    (SELECT COD_RECURSO_ACAO FROM RECURSO_ACAO WHERE COD_RECURSO = (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'expedicao:corte') AND COD_ACAO = (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'relatorio')),
    (SELECT COD_MENU_ITEM FROM MENU_ITEM WHERE COD_PAI = (SELECT COD_MENU_ITEM FROM MENU_ITEM WHERE DSC_MENU_ITEM = 'Relatórios' AND COD_PAI = 0) AND DSC_MENU_ITEM = 'Expedição'),
    'Relatório de Cortes', 10, '#');
