INSERT INTO VERSAO (DTH, NUMERO_VERSAO, SCRIPT) VALUES (SYSDATE, '3.8.0', 'equipeSeparacao.sql');
CREATE TABLE EQUIPE_SEPARACAO
(
  COD_EQUIPE_SEPARACAO NUMBER (8)  NOT NULL ,
  COD_USUARIO NUMBER (8)  NOT NULL ,
  ETIQUETA_INICIAL NUMBER (8)  NOT NULL ,
  ETIQUETA_FINAL NUMBER (8)  NOT NULL ,
  DTH_VINCULO DATE
) LOGGING
;

ALTER TABLE EQUIPE_SEPARACAO
ADD CONSTRAINT EQUIPE_SEPARACAO_PK PRIMARY KEY ( COD_EQUIPE_SEPARACAO  ) ;

CREATE SEQUENCE SQ_EQUIPE_SEPARACA_01
START WITH 1
MAXVALUE 99999999999999999
MINVALUE 1
NOCYCLE
NOCACHE
NOORDER;

INSERT INTO ACAO(COD_ACAO, DSC_ACAO, NOM_ACAO) VALUES (SQ_ACAO_01.NEXTVAL, 'Apontamento da Equipe de Separação','apontamento-separacao');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'expedicao:index'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'apontamento-separacao'), 'Apontamento da Equipe de Separação');
INSERT INTO MENU_ITEM (COD_MENU_ITEM, COD_RECURSO_ACAO, COD_PAI, DSC_MENU_ITEM, NUM_PESO, DSC_URL, DSC_TARGET, SHOW) VALUES (SQ_MENU_ITEM_01.NEXTVAL, (SELECT COD_RECURSO_ACAO FROM RECURSO_ACAO WHERE COD_RECURSO = (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'expedicao:index') AND COD_ACAO = (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'apontamento-separacao')), (SELECT COD_MENU_ITEM FROM MENU_ITEM WHERE DSC_MENU_ITEM = 'Expedição' AND COD_PAI = 0), 'Definir Equipe de Separação', 10, '#', '_selft', 'S');
