INSERT INTO VERSAO (DTH, NUMERO_VERSAO, SCRIPT) VALUES (SYSDATE, '3.8.0', 'numeroLacre.sql');

ALTER TABLE EXPEDICAO_VOLUME_PATRIMONIO ADD (
    NUM_LACRE VARCHAR2 (20),
    DTH_VINCULO_LACRE TIMESTAMP
);

ALTER TABLE EXPEDICAO_VOLUME_PATRIMONIO ADD (
    COD_USUARIO_LACRE NUMBER (8)
);