CREATE TABLE VERSAO
(
  DTH TIMESTAMP NOT NULL
, NUMERO_VERSAO VARCHAR2(20) NOT NULL
, SCRIPT VARCHAR2(100) NOT NULL
, CONSTRAINT VERSAO_PK PRIMARY KEY
  (
    DTH
  )
  ENABLE
);

ALTER TABLE RELATORIO_PICKING
ADD (
COD_PRODUTO NUMBER (8) NULL,
DTH_COLETA DATE NULL,
COD_OS NUMBER (8) NULL
);

INSERT INTO PARAMETRO (COD_PARAMETRO, COD_CONTEXTO_PARAMETRO, DSC_PARAMETRO, DSC_TITULO_PARAMETRO, IND_PARAMETRO_SISTEMA, COD_TIPO_ATRIBUTO, DSC_VALOR_PARAMETRO)
  VALUES (SQ_PARAMETRO_01.NEXTVAL, (SELECT COD_CONTEXTO_PARAMETRO FROM CONTEXTO_PARAMETRO WHERE DSC_CONTEXTO_PARAMETRO LIKE 'RELATORIOS E IMPRESSAO'),
  'MODELO_MAPA_SEPARACAO', 'Modelo de Mapa de Separação', 'S', 'A', 1);
