<style>
    <!--
    fieldset#fieldset-modelo{
        display: inline;
        width: 947px;
    }

    div.checkboxes {
        margin-bottom: 10px;
    }

    div.fieldsets {
        width: 100%;
        display: flex;
    }

    div.fieldset {
        flex-direction: row;
        flex: 1;
    }

    #fieldset-modelo input.error {
        border-color: #F00;
    }
    #fieldset-modelo select.error {
        border-color: #F00;
    }
    #fieldset-modelo label.error {
        display:none !important;
    }

    form fieldset div.field {
        display: block;
        float: none;
        margin-right: 20px;
        min-height: auto;
    }

    form fieldset div.checkbox {
        display: inline-block;
        float: none;
    }

    form fieldset div.checkbox label {
        margin: 0 0 0 5px;
    }
    -->
</style>
<form id="modelo-separacao-form" class="saveForm" method="post" action="" enctype="application/x-www-form-urlencoded" novalidate="novalidate">
    <fieldset id="fieldset-modelo">
        <legend>Cadastro</legend>
        <div>
            <?php echo $this->form->getSubForm('identificacao')->getElement('descricao'); ?>
        </div>

        <div class="fieldsets">
            <div class="fieldset">
                <div class="checkboxes">
                    <?php echo $this->form->getSubForm('identificacao')->getElement('utilizaCaixaMaster'); ?><br />
                    <?php echo $this->form->getSubForm('identificacao')->getElement('utilizaQuebraColetor'); ?><br />
                    <?php echo $this->form->getSubForm('identificacao')->getElement('utilizaEtiquetaMae'); ?><br />
                    <?php echo $this->form->getSubForm('identificacao')->getElement('usaConferenciaCarregamento'); ?><br />
                    <?php echo $this->form->getSubForm('identificacao')->getElement('usaSequenciaRotaPraca'); ?><br />
                    <?php echo $this->form->getSubForm('identificacao')->getElement('forcarEmbVenda'); ?><br />
                    <?php echo $this->form->getSubForm('identificacao')->getElement('produtoInventario'); ?><br />
                    <?php echo $this->form->getSubForm('identificacao')->getElement('utilizaVolumePatrimonio'); ?><br />
                    <?php echo $this->form->getSubForm('identificacao')->getElement('imprimeEtiquetaPatrimonio'); ?><br />
                    <?php echo $this->form->getSubForm('identificacao')->getElement('quebraUnidFracionavel'); ?><br /><br />
                    <?php echo $this->form->getSubForm('identificacao')->getElement('tipoConfCarregamento'); ?>
                    <?php echo $this->form->getSubForm('identificacao')->getElement('quebraPulmaDoca'); ?>
                </div>

                <fieldset>
                    <legend>Processo com Embalados</legend>

                    <?php echo $this->form->getSubForm('identificacao')->getElement('tipoQuebraVolume'); ?>
                    <?php echo $this->form->getSubForm('identificacao')->getElement('separacaoPc'); ?>
                    <fieldset id="fieldsetQuebraEmbalados" class="fieldsets">
                        <legend>Quebras</legend>
                        <?php echo $this->form->getSubForm('identificacao')->getElement('quebraEmbalados'); ?>
                    </fieldset><br />
                    <?php echo $this->form->getSubForm('identificacao')->getElement('agrupContEtiquetas'); ?>
                    <fieldset id="fieldSetCaixa" class="fieldsets">
                        <legend>Para criação dos volumes embalados:</legend>
                        <?php echo $this->form->getSubForm('identificacao')->getElement('usaCaixaPadrao'); ?><br /><br />
                        <?php echo $this->form->getSubForm('identificacao')->getElement('tipoAgroupSeqEtiquetas'); ?>
                    </fieldset>
                    <?php echo $this->form->getSubForm('identificacao')->getElement('criarVolsFinalCheckout'); ?><br /><br />
                    <?php echo $this->form->getSubForm('identificacao')->getElement('tipoSeparacaoEmbalado'); ?>
                    <?php echo $this->form->getSubForm('identificacao')->getElement('tipoDefaultEmbalado'); ?>
                    <?php echo $this->form->getSubForm('identificacao')->getElement('tipoConferenciaEmbalado'); ?>
                    <?php echo $this->form->getSubForm('identificacao')->getElement('tipoConferenciaNaoEmbalado'); ?>
                </fieldset>
            </div>

            <div class="fieldset">
                <fieldset>
                    <legend>Separação para Fracionados</legend>
                    <table>
                        <legend>Tipo de Separação:</legend>
                        <tr>
                            <td>
                                <?php echo $this->form->getSubForm('identificacao')->getElement('tipoSeparacaoFracionadoEmbalado'); ?>
                            </td>
                            <td>
                                <?php echo $this->form->getSubForm('identificacao')->getElement('tipoSeparacaoFracionado'); ?>
                            </td>
                        </tr>
                    </table>
                    <fieldset>
                        <legend>Quebras</legend>
                        <?php echo $this->form->getSubForm('identificacao')->getElement('quebraFracionados'); ?>
                    </fieldset>
                </fieldset>

                <fieldset>
                    <legend>Separação para não Fracionados</legend>
                    <table>
                        <legend>Tipo de Separação:</legend>
                        <tr>
                            <td>
                                <?php echo $this->form->getSubForm('identificacao')->getElement('tipoSeparacaoNaoFracionadoEmbalado'); ?>
                            </td>
                            <td>
                                <?php echo $this->form->getSubForm('identificacao')->getElement('tipoSeparacaoNaoFracionado'); ?>
                            </td>
                        </tr>
                    </table>

                    <fieldset>
                        <legend>Quebras</legend>
                        <?php echo $this->form->getSubForm('identificacao')->getElement('quebraNaoFracionados'); ?>
                    </fieldset>
                </fieldset>
            </div>
        </div>
    </fieldset>
</form>
<script>
    $(function () {
        $(document).ready(function () {
            checkStatusSeparacaoPc();
            checkAgroupCaixa();
        });

        $("#separacaoPc").change(function () {
            checkStatusSeparacaoPc();
        });

        function checkStatusSeparacaoPc() {
            if ($("#separacaoPc").val() === 'S') {
                $("#fieldsetQuebraEmbalados").show();
            } else {
                $("#fieldsetQuebraEmbalados").hide();
            }
        }

        $("#agrupContEtiquetas").change(function () {
            checkAgroupCaixa();
        });

        function checkAgroupCaixa() {
            if ($("#agrupContEtiquetas").attr('checked')) {
                $("#fieldSetCaixa").show();
            } else {
                $("#fieldSetCaixa").hide();
                $("#usaCaixaPadrao").attr('checked', false);
            }
        }

        $(".condicionalCheckout").click(function () {
            let atual = $(this);
            let setTo = atual.prop('checked');
            if (setTo) {
                $(".condicionalCheckout").each(function () {
                    $(this).prop('checked', false);
                });
            }
            atual.prop('checked', setTo);
        });

        $("#usaSequenciaRotaPraca").change(function () {
            if ($(this).prop("checked")) {
                $.wmsDialogAlert('Este parâmetro exige quebra por PRAÇA!<br>Todas as quebras por PRAÇA serão selecionadas!');
                $("#quebraFracionados-P").prop('checked', true);
                $("#quebraNaoFracionados-P").prop('checked', true);
                $("#quebraEmbalados-P").prop('checked', true);
                $("#quebraPulmaDoca").val("P");
            }
        });

        $(".disableSequenciaPraca").change(function () {
            let checkSeqPraca = $("#usaSequenciaRotaPraca");

            if (!checkSeqPraca.prop("checked")) return;

            let checkSeqPracaDisabled = false;

            if ((($(this).is("input[type='checkbox']") && $(this).prop("checked") === false && $(this).val() === "P") ||
                ($(this).is("select")) && $(this).val() !== "P")) {
                checkSeqPraca.prop("checked", false);
                checkSeqPracaDisabled = true;
            }

            if (checkSeqPracaDisabled) $.wmsDialogAlert('A Sequencia ROTA/PRAÇA exige todas as quebras de praça! O parâmetro será desmarcado');
        });
    })
</script>