INSERT INTO VERSAO (DTH, NUMERO_VERSAO, SCRIPT) VALUES (SYSDATE, '5.0.0','10 modelo-etiqueta-pulmao.sql');

INSERT INTO PARAMETRO (
  COD_PARAMETRO,
  COD_CONTEXTO_PARAMETRO,
  DSC_PARAMETRO,
  DSC_TITULO_PARAMETRO,
  IND_PARAMETRO_SISTEMA,
  COD_TIPO_ATRIBUTO,
  DSC_VALOR_PARAMETRO)
VALUES (
  SQ_PARAMETRO_01.NEXTVAL,
  (SELECT COD_CONTEXTO_PARAMETRO FROM CONTEXTO_PARAMETRO WHERE DSC_CONTEXTO_PARAMETRO LIKE 'RELATÓRIOS E IMPRESSÃO'),
  'MODELO_ETIQUETA_PULMAO',
  'Modelo da Etiqueta de Pulmão',
  'S',
  'A',
  (SELECT DSC_VALOR_PARAMETRO FROM PARAMETRO WHERE DSC_PARAMETRO = 'MODELO_ETIQUETA_PICKING'));