INSERT INTO VERSAO (DTH, NUMERO_VERSAO, SCRIPT) VALUES (SYSDATE, '5.0.0','11 fornecedor-devolucao.sql');

INSERT INTO PARAMETRO (
  COD_PARAMETRO,
  COD_CONTEXTO_PARAMETRO,
  DSC_PARAMETRO,
  DSC_TITULO_PARAMETRO,
  IND_PARAMETRO_SISTEMA,
  COD_TIPO_ATRIBUTO,
  DSC_VALOR_PARAMETRO)
VALUES (
  SQ_PARAMETRO_01.NEXTVAL,
  (SELECT COD_CONTEXTO_PARAMETRO FROM CONTEXTO_PARAMETRO WHERE DSC_CONTEXTO_PARAMETRO LIKE 'PARAMETROS DE INTEGRAÇÃO'),
  'COD_FORNECEDOR_DEVOLUCAO',
  'Código de Fornecedor Padrão para Devoluções',
  'S',
  'A',
  9999);


INSERT INTO PESSOA (COD_PESSOA, NOM_PESSOA, COD_TIPO_PESSOA) VALUES (SQ_PESSOA_01.NEXTVAL,'DEVOLUCAO','J');

INSERT INTO PESSOA_JURIDICA (COD_PESSOA, NOM_FANTASIA, NUM_CNPJ) VALUES((SELECT COD_PESSOA FROM PESSOA WHERE NOM_PESSOA = 'DEVOLUCAO'),'DEVOLUCAO','99999999999');

INSERT INTO FORNECEDOR (COD_FORNECEDOR, COD_EXTERNO) VALUES ((SELECT COD_PESSOA FROM PESSOA WHERE NOM_PESSOA = 'DEVOLUCAO'),'9999');