INSERT INTO VERSAO (DTH, NUMERO_VERSAO, SCRIPT) VALUES (SYSDATE, '5.0.0','13 Integracao-pedidos.sql');

INSERT INTO ACAO (COD_ACAO,DSC_ACAO,NOM_ACAO) VALUES (SQ_ACAO_01.NEXTVAL, 'Listar pedidos a integrar do ERP', 'listar-pedidos-erp');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO LIKE 'expedicao:pedido'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO LIKE 'listar-pedidos-erp'), 'Listar pedidos a integrar do ERP');

INSERT INTO SIGLA (COD_SIGLA, COD_TIPO_SIGLA, DSC_SIGLA, COD_REFERENCIA_SIGLA) VALUES (606, 79, 'PEDIDOS POR CARGA', 'P');