INSERT INTO VERSAO (DTH, NUMERO_VERSAO, SCRIPT) VALUES (SYSDATE, '5.0.0','14 consumo-banco-integracao.sql');


ALTER TABLE ACAO_INTEGRACAO_ANDAMENTO
	ADD (IND_DESTINO VARCHAR2(20 BYTE));

ALTER TABLE ACAO_INTEGRACAO_ANDAMENTO
	ADD (URL VARCHAR2(255 BYTE));

UPDATE ACAO_INTEGRACAO_ANDAMENTO SET IND_DESTINO = 'P';

CREATE SEQUENCE SQ_INTEGRACAO_NF_ENTRADA_01
START WITH 1
MAXVALUE 99999999999999999
MINVALUE 1
NOCYCLE
NOCACHE
NOORDER;

CREATE SEQUENCE SQ_INTEGRACAO_NF_PEDIDO_01
START WITH 1
MAXVALUE 99999999999999999
MINVALUE 1
NOCYCLE
NOCACHE
NOORDER;

CREATE TABLE INTEGRACAO_NF_ENTRADA (
	COD_INTEGRACAO_NF_ENTRADA NUMBER(8,0) NOT NULL,
	COD_FORNECEDOR 			      VARCHAR2(20 BYTE),
	COD_PRODUTO 			        VARCHAR2(20 BYTE),
	NOM_FORNECEDOR 			      VARCHAR2(100 BYTE),
	CPF_CNPJ 			            VARCHAR2(20 BYTE),
	DSC_GRADE 			          VARCHAR2(20 BYTE),
	INSCRICAO_ESTADUAL 		    VARCHAR2(20 BYTE),
	NUM_NOTA_FISCAL 		      VARCHAR2(20 BYTE),
	COD_SERIE_NOTA_FISCAL 	  VARCHAR2(20 BYTE),
	DAT_EMISSAO				        DATE,
	DSC_PLACA_VEICULO  		    VARCHAR2(20 BYTE),
	QTD_ITEM			            NUMBER(13,8),
	VALOR_TOTAL 			        NUMBER(13,8),
	DTH						            DATE
);
ALTER TABLE INTEGRACAO_NF_ENTRADA ADD CONSTRAINT INTEGRACAO_NF_ENTRADA_PK PRIMARY KEY (COD_INTEGRACAO_NF_ENTRADA);


CREATE TABLE INTEGRACAO_PEDIDO (
	COD_INTEGRACAO_PEDIDO  NUMBER(8,0) NOT NULL,
	CARGA 		      		   VARCHAR2(20 BYTE),
	PLACA				           VARCHAR2(20 BYTE),
	PEDIDO 				         VARCHAR2(20 BYTE),
	COD_PRACA 			       VARCHAR2(20 BYTE),
	DSC_PRACA 			       VARCHAR2(100 BYTE),
	COD_ROTA 			         VARCHAR2(20 BYTE),
	DSC_ROTA 			         VARCHAR2(100 BYTE),
	COD_CLIENTE 		       VARCHAR2(20 BYTE),
	NOME				           VARCHAR2(100 BYTE),
	CPF_CNPJ			         VARCHAR2(20 BYTE),
	TIPO_PESSOA			       VARCHAR2(20 BYTE),
	LOGRADOURO		         VARCHAR2(100 BYTE),
	NUMERO				         VARCHAR2(20 BYTE),
	BAIRRO				         VARCHAR2(100 BYTE),
	CIDADE				         VARCHAR2(100 BYTE),
	UF 					           VARCHAR2(20 BYTE),
	COMPLEMENTO 		       VARCHAR2(100 BYTE),
	REFERENCIA 			       VARCHAR2(100 BYTE),
	CEP					           VARCHAR2(20 BYTE),
	PRODUTO				         VARCHAR2(20 BYTE),
	GRADE				           VARCHAR2(20 BYTE),
	QTD				   	         NUMBER(13,8),
	VLR_VENDA 			       NUMBER(13,8),
	DTH					           DATE
);
ALTER TABLE INTEGRACAO_PEDIDO ADD CONSTRAINT INTEGRACAO_PEDIDO_PK PRIMARY KEY (COD_INTEGRACAO_PEDIDO);