INSERT INTO VERSAO (DTH, NUMERO_VERSAO, SCRIPT) VALUES (SYSDATE, '5.0.0','14 integracao-notaFiscal.sql');

INSERT INTO ACAO (COD_ACAO,DSC_ACAO,NOM_ACAO) VALUES (
  SQ_ACAO_01.NEXTVAL,
  'Listar informações do ERP',
  'listar-erp'
);

INSERT INTO RECURSO (COD_RECURSO, COD_RECURSO_PAI, NOM_RECURSO, DSC_RECURSO)
VALUES (
  SQ_RECURSO_01.NEXTVAL,
  0,
  'notafiscal:importar-erp',
  'Importação de Notas Fiscais de Entrada do ERP'
);


INSERT INTO RECURSO (COD_RECURSO, COD_RECURSO_PAI, NOM_RECURSO, DSC_RECURSO)
VALUES (
  SQ_RECURSO_01.NEXTVAL,
  0,
  'importar-erp',
  'Importação de Notas Fiscais de Entrada do ERP'
);

INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (
  SQ_RECURSO_ACAO_01.NEXTVAL,
  (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO LIKE 'notafiscal:importar-erp'),
  (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO LIKE 'listar-erp'),
  'Listar notas de entrada a integrar do ERP'
);

INSERT INTO MENU_ITEM (COD_MENU_ITEM, COD_RECURSO_ACAO, COD_PAI, DSC_MENU_ITEM, NUM_PESO, DSC_URL, SHOW) VALUES (
  SQ_MENU_ITEM_01.NEXTVAL,
  (SELECT COD_RECURSO_ACAO
     FROM RECURSO_ACAO
    WHERE COD_RECURSO = (SELECT COD_RECURSO
                           FROM RECURSO
                          WHERE NOM_RECURSO = 'notafiscal:importar-erp')
                            AND COD_ACAO = (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'listar-erp')),
  (SELECT COD_MENU_ITEM FROM MENU_ITEM WHERE DSC_MENU_ITEM = 'Recebimento' AND COD_PAI = '0'),
  'Importar NF Entrada do ERP',
  1,
  '#',
  'N'
);