INSERT INTO VERSAO (DTH, NUMERO_VERSAO, SCRIPT) VALUES (SYSDATE, '5.0.0','16-bonus-erp.sql');

ALTER TABLE NOTA_FISCAL
  ADD (COD_RECEBIMENTO_ERP NUMBER(8),
       IND_RECEBIMENTO_ERP_FINALIZADO CHAR(1 BYTE));

COMMENT ON COLUMN NOTA_FISCAL.IND_RECEBIMENTO_ERP_FINALIZADO IS 'Sinaliza se o recebimento (bonus) no ERP ja foi finalizado ''S/N''';
COMMENT ON COLUMN NOTA_FISCAL.COD_RECEBIMENTO_ERP IS 'Cod recebimento (bonus) ERP';

INSERT INTO PARAMETRO (COD_PARAMETRO,COD_CONTEXTO_PARAMETRO,DSC_PARAMETRO,DSC_TITULO_PARAMETRO,IND_PARAMETRO_SISTEMA,COD_TIPO_ATRIBUTO,DSC_VALOR_PARAMETRO)
  VALUES (SQ_PARAMETRO_01.NEXTVAL,(SELECT COD_CONTEXTO_PARAMETRO FROM CONTEXTO_PARAMETRO WHERE DSC_CONTEXTO_PARAMETRO = 'PARAMETROS DE INTEGRAÇÃO'),'UTILIZA_RECEBIMENTO_ERP','Integração de Recebimento com ERP','S','A','N');