ALTER TABLE RECEBIMENTO_EMBALAGEM
  ADD (QTD_EMBALAGEM NUMBER(13,3));

ALTER TABLE PALETE_PRODUTO
  ADD (QTD_EMBALAGEM NUMBER(13,3));

MERGE INTO PALETE_PRODUTO PP
USING (SELECT * FROM PRODUTO_EMBALAGEM) PE ON (PE.COD_PRODUTO_EMBALAGEM = PP.COD_PRODUTO_EMBALAGEM)
 WHEN MATCHED THEN UPDATE SET PP.QTD_EMBALAGEM = PE.QTD_EMBALAGEM;

MERGE INTO RECEBIMENTO_EMBALAGEM RE
USING (SELECT * FROM PRODUTO_EMBALAGEM) PE ON (PE.COD_PRODUTO_EMBALAGEM = RE.COD_PRODUTO_EMBALAGEM)
 WHEN MATCHED THEN UPDATE SET RE.QTD_EMBALAGEM = PE.QTD_EMBALAGEM;

UPDATE PALETE_PRODUTO SET QTD_EMBALAGEM = 1 WHERE COD_PRODUTO_VOLUME IS NOT NULL;

UPDATE PALETE_PRODUTO SET QTD_EMBALAGEM = 1 WHERE QTD_EMBALAGEM IS NULL;