/*
 Autor: Tarcísio César
 Data Criação: 02/03/2017
 */

INSERT INTO VERSAO (DTH, NUMERO_VERSAO, SCRIPT) VALUES (SYSDATE, '5.0.0','2 impInventario.sql');

ALTER TABLE INVENTARIO ADD (COD_INVENTARIO_ERP INT);
CREATE UNIQUE INDEX INVENTARIO_COD_EXT ON INVENTARIO (COD_INVENTARIO_ERP);

INSERT INTO PARAMETRO (
  COD_PARAMETRO,
  COD_CONTEXTO_PARAMETRO,
  DSC_PARAMETRO,
  DSC_TITULO_PARAMETRO,
  IND_PARAMETRO_SISTEMA,
  COD_TIPO_ATRIBUTO,
  DSC_VALOR_PARAMETRO)
VALUES (
  SQ_PARAMETRO_01.NEXTVAL,
  (SELECT COD_CONTEXTO_PARAMETRO FROM CONTEXTO_PARAMETRO WHERE DSC_CONTEXTO_PARAMETRO LIKE 'INVENTARIO'),
  'IMPORTA_INVENTARIO',
  'Importa inventário do ERP (S/N)',
  'S',
  'A',
  'N');