INSERT INTO VERSAO (DTH, NUMERO_VERSAO, SCRIPT) VALUES (SYSDATE, '5.0.0','20-EmbalagemMaster.sql');

DROP TABLE EMBALAGEM_MASTER;

CREATE TABLE EMBALAGEM_MASTER
(
  COD_PRODUTO VARCHAR2(20 BYTE) NOT NULL,
  DSC_GRADE VARCHAR2(10 BYTE) NOT NULL,
  NUM_PESO NUMBER(13,8),
  NUM_CUBAGEM NUMBER (13,8)
);

CREATE UNIQUE INDEX PRODUTO_PESO_PK ON PRODUTO_PESO (COD_PRODUTO ASC, DSC_GRADE ASC);
ALTER TABLE PRODUTO_PESO ADD CONSTRAINT PRODUTO_PESO_PK PRIMARY KEY (COD_PRODUTO, DSC_GRADE) USING INDEX PRODUTO_PESO_PK ENABLE;
ALTER TABLE PRODUTO_PESO ADD CONSTRAINT PRODUTO_PESO_FK1 FOREIGN KEY (COD_PRODUTO, DSC_GRADE) REFERENCES PRODUTO (COD_PRODUTO, DSC_GRADE) ENABLE;

DELETE FROM PRODUTO_PESO;

INSERT INTO PRODUTO_PESO (COD_PRODUTO, DSC_GRADE, NUM_PESO, NUM_CUBAGEM)
SELECT COD_PRODUTO, DSC_GRADE, NUM_PESO, NUM_CUBAGEM
  FROM (SELECT P.COD_PRODUTO,
		           P.DSC_GRADE,
		           PDL.NUM_PESO,
		           PDL.NUM_CUBAGEM
          FROM (SELECT PE.COD_PRODUTO, PE.DSC_GRADE, MIN(PDL.COD_PRODUTO_DADO_LOGISTICO) as COD_PRODUTO_DADO_LOGISTICO
		              FROM (SELECT MIN(PE.COD_PRODUTO_EMBALAGEM) AS COD_PRODUTO_EMBALAGEM, PE.COD_PRODUTO,PE.DSC_GRADE
				                  FROM PRODUTO_EMBALAGEM PE
                         INNER JOIN PRODUTO_DADO_LOGISTICO PDL ON PDL.COD_PRODUTO_EMBALAGEM = PE.COD_PRODUTO_EMBALAGEM
				                 INNER JOIN (SELECT MIN(QTD_EMBALAGEM) AS FATOR, COD_PRODUTO, DSC_GRADE
								                       FROM PRODUTO_EMBALAGEM PE
                                      INNER JOIN PRODUTO_DADO_LOGISTICO PDL ON PDL.COD_PRODUTO_EMBALAGEM = PE.COD_PRODUTO_EMBALAGEM
							                        GROUP BY COD_PRODUTO,DSC_GRADE) PEM
					                  ON (PEM.COD_PRODUTO = PE.COD_PRODUTO)
                           AND (PEM.DSC_GRADE = PE.DSC_GRADE)
                           AND (PEM.FATOR = PE.QTD_EMBALAGEM)
                         GROUP BY PE.COD_PRODUTO, PE.DSC_GRADE) PE
		             INNER JOIN PRODUTO_DADO_LOGISTICO PDL ON PDL.COD_PRODUTO_EMBALAGEM = PE.COD_PRODUTO_EMBALAGEM
		             GROUP BY COD_PRODUTO, DSC_GRADE) P
         INNER JOIN PRODUTO_DADO_LOGISTICO PDL ON PDL.COD_PRODUTO_DADO_LOGISTICO = P.COD_PRODUTO_DADO_LOGISTICO
         UNION
        SELECT PV.COD_PRODUTO,
		           PV.DSC_GRADE,
		           SUM(PV.NUM_PESO) as NUM_PESO,
		           SUM(PV.NUM_CUBAGEM) as NUM_CUBAGEM
	        FROM PRODUTO_VOLUME PV
         GROUP BY PV.COD_PRODUTO, PV.DSC_GRADE) P;

DROP VIEW SUM_PESO_PRODUTO;

CREATE OR REPLACE PROCEDURE PROC_ATUALIZA_PESO_PRODUTO
(
  PRODUTO IN VARCHAR2
, GRADE   IN VARCHAR2
) AS
BEGIN

  DELETE FROM PRODUTO_PESO WHERE COD_PRODUTO = PRODUTO AND DSC_GRADE = GRADE;

  INSERT INTO PRODUTO_PESO (COD_PRODUTO, DSC_GRADE, NUM_PESO, NUM_CUBAGEM)
  SELECT COD_PRODUTO, DSC_GRADE, NUM_PESO, NUM_CUBAGEM
    FROM (SELECT P.COD_PRODUTO,
  		           P.DSC_GRADE,
  		           PDL.NUM_PESO,
  		           PDL.NUM_CUBAGEM
            FROM (SELECT PE.COD_PRODUTO, PE.DSC_GRADE, MIN(PDL.COD_PRODUTO_DADO_LOGISTICO) as COD_PRODUTO_DADO_LOGISTICO
  		              FROM (SELECT MIN(PE.COD_PRODUTO_EMBALAGEM) AS COD_PRODUTO_EMBALAGEM, PE.COD_PRODUTO,PE.DSC_GRADE
  				                  FROM PRODUTO_EMBALAGEM PE
                           INNER JOIN PRODUTO_DADO_LOGISTICO PDL ON PDL.COD_PRODUTO_EMBALAGEM = PE.COD_PRODUTO_EMBALAGEM
  				                 INNER JOIN (SELECT MIN(QTD_EMBALAGEM) AS FATOR, COD_PRODUTO, DSC_GRADE
  								                       FROM PRODUTO_EMBALAGEM PE
                                        INNER JOIN PRODUTO_DADO_LOGISTICO PDL ON PDL.COD_PRODUTO_EMBALAGEM = PE.COD_PRODUTO_EMBALAGEM
  							                        GROUP BY COD_PRODUTO,DSC_GRADE) PEM
  					                  ON (PEM.COD_PRODUTO = PE.COD_PRODUTO)
                             AND (PEM.DSC_GRADE = PE.DSC_GRADE)
                             AND (PEM.FATOR = PE.QTD_EMBALAGEM)
                           GROUP BY PE.COD_PRODUTO, PE.DSC_GRADE) PE
		               INNER JOIN PRODUTO_DADO_LOGISTICO PDL ON PDL.COD_PRODUTO_EMBALAGEM = PE.COD_PRODUTO_EMBALAGEM
		               GROUP BY COD_PRODUTO, DSC_GRADE) P
           INNER JOIN PRODUTO_DADO_LOGISTICO PDL ON PDL.COD_PRODUTO_DADO_LOGISTICO = P.COD_PRODUTO_DADO_LOGISTICO
           UNION
          SELECT PV.COD_PRODUTO,
		             PV.DSC_GRADE,
		             SUM(PV.NUM_PESO) as NUM_PESO,
		             SUM(PV.NUM_CUBAGEM) as NUM_CUBAGEM
	          FROM PRODUTO_VOLUME PV
           GROUP BY PV.COD_PRODUTO, PV.DSC_GRADE) P
     WHERE COD_PRODUTO = PRODUTO AND DSC_GRADE = GRADE;

END PROC_ATUALIZA_PESO_PRODUTO;