INSERT INTO VERSAO (DTH, NUMERO_VERSAO, SCRIPT) VALUES (SYSDATE, '5.0.0','21-integracao-id.sql');

CREATE TABLE ACAO_INTEGRACAO_FILTRO (
  COD_ACAO_INTEGRACAO_FILTRO NUMBER(8) NOT NULL,
  COD_ACAO_INTEGRACAO NUMBER(8) NOT NULL,
  COD_TIPO_REGISTRO NUMBER(8) NOT NULL,
  DSC_FILTRO VARCHAR2(500 BYTE),
  CONSTRAINT COD_ACAO_INTEGRACAO_FILTRO_PK PRIMARY KEY (COD_ACAO_INTEGRACAO_FILTRO),
  CONSTRAINT COD_SIGLA_FK FOREIGN KEY (COD_TIPO_REGISTRO) REFERENCES SIGLA (COD_SIGLA),
  CONSTRAINT COD_ACAO_INTEGRACAO_FK FOREIGN KEY (COD_ACAO_INTEGRACAO) REFERENCES ACAO_INTEGRACAO (COD_ACAO_INTEGRACAO)
);

CREATE SEQUENCE SQ_ACAO_INTEGRACAO_FILTRO_01 MINVALUE 0 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;


INSERT INTO SIGLA (COD_SIGLA,COD_TIPO_SIGLA,DSC_SIGLA,COD_REFERENCIA_SIGLA)
  VALUES (610,79,'DATA ESPECIFICA','INTEGRACAO');

INSERT INTO SIGLA (COD_SIGLA,COD_TIPO_SIGLA,DSC_SIGLA,COD_REFERENCIA_SIGLA)
  VALUES (611,79,'CODIGO ESPECIFICO','INTEGRACAO');

INSERT INTO SIGLA (COD_SIGLA,COD_TIPO_SIGLA,DSC_SIGLA,COD_REFERENCIA_SIGLA)
  VALUES (612,79,'CONJUNTO CODIGOS','INTEGRACAO');

INSERT INTO SIGLA (COD_SIGLA,COD_TIPO_SIGLA,DSC_SIGLA,COD_REFERENCIA_SIGLA)
  VALUES (613,79,'INTERVALO CODIGO','INTEGRACAO');



--NOVAS QUERYS PARA INTEGRAÇÃO DE PEDIDOS



--NOVAS QUERYS PARA INTEGRAÇÃO DE NOTAS FISCAIS DE ENTRADA
DELETE FROM ACAO_INTEGRACAO_ANDAMENTO WHERE COD_ACAO_INTEGRACAO = 7;
DELETE FROM ACAO_INTEGRACAO_FILTRO WHERE COD_ACAO_INTEGRACAO = 7;
DELETE FROM ACAO_INTEGRACAO WHERE COD_ACAO_INTEGRACAO = 7;


INSERT INTO SIGLA (COD_SIGLA,COD_TIPO_SIGLA,DSC_SIGLA,COD_REFERENCIA_SIGLA) VALUES (606,79,'RECEBIMENTO BONUS','B');




