INSERT INTO VERSAO (DTH, NUMERO_VERSAO, SCRIPT) VALUES (SYSDATE, '5.0.0','22-integracao-finalizacao_conferencia_erp.sql');

INSERT INTO SIGLA (COD_SIGLA,COD_TIPO_SIGLA,DSC_SIGLA,COD_REFERENCIA_SIGLA) VALUES (608,79,'INFORMA ERP ETQ MAPAS IMPRESSOS','B');
INSERT INTO SIGLA (COD_SIGLA,COD_TIPO_SIGLA,DSC_SIGLA,COD_REFERENCIA_SIGLA) VALUES (609,79,'FINALIZA CONFERENCIA ERP','B');

INSERT INTO PARAMETRO (COD_PARAMETRO,COD_CONTEXTO_PARAMETRO,DSC_PARAMETRO,DSC_TITULO_PARAMETRO,IND_PARAMETRO_SISTEMA,COD_TIPO_ATRIBUTO,DSC_VALOR_PARAMETRO)
  VALUES (SQ_PARAMETRO_01.NEXTVAL,(SELECT COD_CONTEXTO_PARAMETRO FROM CONTEXTO_PARAMETRO WHERE DSC_CONTEXTO_PARAMETRO = 'PARAMETROS DE INTEGRAÇÃO'),'IND_INFORMA_ERP_ETQ_MAPAS_IMPRESSOS_INTEGRACAO','Imprime Etq/Mapas no ERP (S/N)','S','A','N');

INSERT INTO PARAMETRO (COD_PARAMETRO,COD_CONTEXTO_PARAMETRO,DSC_PARAMETRO,DSC_TITULO_PARAMETRO,IND_PARAMETRO_SISTEMA,COD_TIPO_ATRIBUTO,DSC_VALOR_PARAMETRO)
  VALUES (SQ_PARAMETRO_01.NEXTVAL,(SELECT COD_CONTEXTO_PARAMETRO FROM CONTEXTO_PARAMETRO WHERE DSC_CONTEXTO_PARAMETRO = 'PARAMETROS DE INTEGRAÇÃO'),'ID_INTEGRACAO_INFORMA_ERP_ETQ_MAPAS_IMPRESSOS','Id Integração Impressão Etq/Mapas no ERP','S','A','15');

INSERT INTO PARAMETRO (COD_PARAMETRO,COD_CONTEXTO_PARAMETRO,DSC_PARAMETRO,DSC_TITULO_PARAMETRO,IND_PARAMETRO_SISTEMA,COD_TIPO_ATRIBUTO,DSC_VALOR_PARAMETRO)
  VALUES (SQ_PARAMETRO_01.NEXTVAL,(SELECT COD_CONTEXTO_PARAMETRO FROM CONTEXTO_PARAMETRO WHERE DSC_CONTEXTO_PARAMETRO = 'PARAMETROS DE INTEGRAÇÃO'),'IND_FINALIZA_CONFERENCIA_ERP_INTEGRACAO','Finalização da Conferencia da Expedição no ERP (S/N)','S','A','N');

INSERT INTO PARAMETRO (COD_PARAMETRO,COD_CONTEXTO_PARAMETRO,DSC_PARAMETRO,DSC_TITULO_PARAMETRO,IND_PARAMETRO_SISTEMA,COD_TIPO_ATRIBUTO,DSC_VALOR_PARAMETRO)
  VALUES (SQ_PARAMETRO_01.NEXTVAL,(SELECT COD_CONTEXTO_PARAMETRO FROM CONTEXTO_PARAMETRO WHERE DSC_CONTEXTO_PARAMETRO = 'PARAMETROS DE INTEGRAÇÃO'),'ID_INTEGRACAO_FINALIZA_CONFERENCIA_ERP','ID Integração de Finalização da Conferencia da Expedição no ERP','S','A','16');