INSERT INTO VERSAO (DTH, NUMERO_VERSAO, SCRIPT) VALUES (SYSDATE, '5.0.0','33-integracao-produtos.sql');

CREATE TABLE INTEGRACAO_PRODUTO
(
    COD_INTEGRACAO_PRODUTO NUMBER(16) NOT NULL,
    DTH DATE,
    COD_PRODUTO VARCHAR2(16) NOT NULL,
    DESCRICAO_PRODUTO VARCHAR2(100),
    CODIGO_CLASSE_NIVEL_1 NUMBER(20),
    DSC_CLASSE_NIVEL_1 NUMBER(20),
    CODIGO_CLASSE_NIVEL_2 NUMBER(20),
    DSC_CLASSE_NIVEL_2 NUMBER(20),
    CODIGO_FABRICANTE NUMBER(8),
    DESCRICAO_FABRICANTE VARCHAR2(100),
    DESCRICAO_EMBALAGEM VARCHAR2(100),
    PESO_VARIAVEL VARCHAR2(1),
    QTD_EMBALAGEM NUMBER(12,4),
    COD_BARRAS VARCHAR2(20),
    PESO_BRUTO_EMBALAGEM NUMBER(12,4),
    ALTURA_EMBALAGEM NUMBER(12,4),
    LARGURA_EMBALAGEM NUMBER(12,4),
    PROFUNDIDADE_EMBALAGEM NUMBER(12,4),
    CUBAGEM_EMBALAGEM NUMBER(12,4),
    EMBALAGEM_ATIVA VARCHAR2(1)
);