/*
  EXEMPLO DE SCRIPT DE INTEGRAÇÃO COM A PC
 */
INSERT INTO VERSAO (DTH, NUMERO_VERSAO, SCRIPT) VALUES (SYSDATE, '5.0.0','5 organizacao-exception-integracao.sql');

ALTER TABLE ACAO_INTEGRACAO_ANDAMENTO
  ADD (TRACE VARCHAR2(4000),
       QUERY VARCHAR2(4000),
       ERR_NUMBER VARCHAR2 (40));