
INSERT INTO VERSAO (DTH, NUMERO_VERSAO, SCRIPT) VALUES (SYSDATE, '5.0.0','7 correcao-valores-cubagem.sql');

UPDATE PRODUTO_DADO_LOGISTICO SET NUM_CUBAGEM = NULL;
ALTER TABLE PRODUTO_DADO_LOGISTICO MODIFY NUM_CUBAGEM NUMBER(16,8);
UPDATE PRODUTO_DADO_LOGISTICO SET NUM_CUBAGEM = NUM_ALTURA * NUM_LARGURA * NUM_PROFUNDIDADE;