INSERT INTO VERSAO (DTH, NUMERO_VERSAO, SCRIPT) VALUES (SYSDATE, '5.0.0','8 habilitando-fornecedor-pessoa-fisica.sql');

ALTER TABLE FORNECEDOR DROP CONSTRAINT FK_FORNE_PEJUR;
ALTER TABLE FORNECEDOR ADD CONSTRAINT FK_FORNE_PESSOA FOREIGN KEY(COD_FORNECEDOR) REFERENCES PESSOA(COD_PESSOA);