INSERT INTO VERSAO (DTH, NUMERO_VERSAO, SCRIPT) VALUES (SYSDATE, '5.0.0','9 logWs.sql');

INSERT INTO PARAMETRO (
  COD_PARAMETRO,
  COD_CONTEXTO_PARAMETRO,
  DSC_PARAMETRO,
  DSC_TITULO_PARAMETRO,
  IND_PARAMETRO_SISTEMA,
  COD_TIPO_ATRIBUTO,
  DSC_VALOR_PARAMETRO)
VALUES (
  SQ_PARAMETRO_01.NEXTVAL,
  (SELECT COD_CONTEXTO_PARAMETRO FROM CONTEXTO_PARAMETRO WHERE DSC_CONTEXTO_PARAMETRO LIKE 'PARAMETROS DE INTEGRAÇÃO'),
  'HABILITA_LOG_WS',
  'Gravar log das requisições dos WebServices (S/N)',
  'S',
  'A',
  'N');