INSERT INTO SIGLA (COD_SIGLA, COD_TIPO_SIGLA, DSC_SIGLA,COD_REFERENCIA_SIGLA)
  VALUES (601, (SELECT COD_TIPO_SIGLA FROM TIPO_SIGLA WHERE DSC_TIPO_SIGLA LIKE 'INTEGRACAO'),'ESTOQUE', 'P');

CREATE TABLE ESTOQUE_ERP
  (
    COD_ESTOQUE_ERP     NUMBER(8,0) NOT NULL,
    COD_PRODUTO         VARCHAR2(20 BYTE),
    DSC_GRADE           VARCHAR2(10 BYTE),
    ESTOQUE_GERENCIAL   NUMBER(13,3),
    ESTOQUE_DISPONIVEL  NUMBER(13,3),
    VLR_ESTOQUE_TOTAL   NUMBER(13,3),
    VLR_ESTOQUE_UNIT    NUMBER(13,3),
    DSC_UNIDADE_VENDA   VARCHAR2(100 BYTE),
    FATOR_UNIDADE_VENDA NUMBER(13,3),
    PRIMARY KEY (COD_ESTOQUE_ERP)
  );

ALTER TABLE ESTOQUE_ERP
ADD CONSTRAINT ESTOQUE_ERP_FK_01 FOREIGN KEY (COD_PRODUTO, DSC_GRADE)
    REFERENCES PRODUTO (COD_PRODUTO, DSC_GRADE) ENABLE;

CREATE SEQUENCE SQ_ESTOQUE_ERP_01
START WITH 1
MAXVALUE 99999999999999999
MINVALUE 1
NOCYCLE
NOCACHE
NOORDER;

INSERT INTO VERSAO (DTH, NUMERO_VERSAO, SCRIPT) VALUES (SYSDATE, '5.0.0','integracaoEstoque.sql');

