INSERT INTO VERSAO (DTH, NUMERO_VERSAO, SCRIPT) VALUES (SYSDATE, '5.0.0','integracaoLinear.sql');

INSERT INTO CONEXAO_INTEGRACAO (COD_CONEXAO_INTEGRACAO, DSC_CONEXAO_INTEGRACAO, SERVIDOR, PORTA, USUARIO, SENHA, DBNAME, PROVEDOR)
VALUES (1,'INTEGRACAO DE PRODUTOS','localhost','1521','wms_linhares','wms_adm','xe', 'ORACLE');

INSERT INTO TIPO_SIGLA (COD_TIPO_SIGLA, DSC_TIPO_SIGLA, IND_SIGLA_SISTEMA) VALUES (SQ_TIPO_SIGLA_01.NEXTVAL, 'INTEGRACAO', 'S');

INSERT INTO SIGLA (COD_SIGLA, COD_TIPO_SIGLA, DSC_SIGLA,COD_REFERENCIA_SIGLA)
VALUES (600, (SELECT COD_TIPO_SIGLA FROM TIPO_SIGLA WHERE DSC_TIPO_SIGLA LIKE 'INTEGRACAO'),'PRODUTOS', 'P');

INSERT INTO ACAO_INTEGRACAO (COD_ACAO_INTEGRACAO, COD_CONEXAO_INTEGRACAO, DSC_QUERY, COD_TIPO_ACAO_INTEGRACAO,IND_UTILIZA_LOG,DTH_ULTIMA_EXECUCAO)
VALUES (1,1,
        'SELECT DATE_FORMAT(NOW(), ''%d/%m/%Y %H:%i:%s'') AS DTH, a.es1_cod AS COD_PRODUTO, ''UNICA'' AS DSC_GRADE, b.es1_desc AS DESCRICAO_PRODUTO, IF (b.es1_familia = 0, 9999 , b.es1_familia) AS CODIGO_CLASSE_NIVEL_1, f.tab_desc AS DSC_CLASSE_NIVEL_1, b.es1_departamento AS CODIGO_CLASSE_NIVEL_2, d.tab_desc AS DSC_CLASSE_NIVEL_2, b.es1_secao AS CODIGO_CLASSE_NIVEL_3, s.tab_desc AS DSC_CLASSE_NIVEL_3, b.es1_categoria AS CODIGO_CLASSE_NIVEL_4, g.tab_desc AS DSC_CLASSE_NIVEL_4, IF (a.cg2_cod = 0, 999999, a.cg2_cod) AS CODIGO_FABRICANTE, c.cg2_nome AS DESCRICAO_FABRICANTE, a.es1_um2 AS DESCRICAO_EMBALAGEM,  IF(a.es1_pesavel = 1,''S'',''N'') AS PESO_VARIAVEL, a.es1_qembc AS QTD_EMBALAGEM, b.es1_codbarra AS COD_BARRAS, w.es1_altura AS ALTURA_EMBALAGEM, w.es1_largura AS LARGURA_EMBALAGEM, w.es1_profundidade AS PROFUNDIDADE_EMBALAGEM, ''S'' AS EMBALAGEM_ATIVA, ''N'' as POSSUI_VALIDADE, NULL AS DIAS_VIDA_UTIL, 1 AS CUBAGEM_EMBALAGEM, 1 AS PESO_BRUTO_EMBALAGEM FROM es1 a INNER JOIN es1p b ON b.es1_cod = a.es1_cod LEFT JOIN st_familia f ON f.tab_cod = b.es1_familia LEFT JOIN st_departamento d ON d.tab_cod = b.es1_departamento LEFT JOIN st_secao s ON s.tab_cod = b.es1_secao LEFT JOIN st_categoria g ON g.tab_cod = b.es1_categoria LEFT JOIN es1w w ON w.es1_cod = a.es1_cod AND w.es1_empresa = a.es1_empresa LEFT JOIN cg2 c ON c.cg2_cod = a.cg2_cod WHERE a.es1_empresa = 1 and a.es1_dtalteracao > :dthExecucao',
        600,'S',null);

INSERT INTO ACAO_INTEGRACAO (COD_ACAO_INTEGRACAO, COD_CONEXAO_INTEGRACAO, DSC_QUERY, COD_TIPO_ACAO_INTEGRACAO,IND_UTILIZA_LOG,DTH_ULTIMA_EXECUCAO)
VALUES (2,1,
        'select e.codprod as COD_PRODUTO, e.qtestger as ESTOQUE_GERENCIAL, sum(e.qtestger-e.qtreserv-e.qtbloqueada) as ESTOQUE_DISPONIVEL, trunc(sum(e.qtestger*e.custoultent),2) VALOR_ESTOQUE, trunc(e.custoultent,2) CUSTO_UNITARIO, p.qtunit FATOR_UNIDADE_VENDA, p.unidade DSC_UNIDADE from pcest e, pcprodut p where e.codprod=p.codprod and e.codfilial=:codFilial group by e.codprod,e.qtestger,e.custoultent,p.qtunit,p.unidade',
        601,'S',null);

INSERT INTO SIGLA (COD_SIGLA, COD_TIPO_SIGLA, DSC_SIGLA,COD_REFERENCIA_SIGLA)
VALUES (602, (SELECT COD_TIPO_SIGLA FROM TIPO_SIGLA WHERE DSC_TIPO_SIGLA LIKE 'INTEGRACAO'),'ENVIO DE PEDIDOS', 'P');

INSERT INTO ACAO_INTEGRACAO (COD_ACAO_INTEGRACAO, COD_CONEXAO_INTEGRACAO, DSC_QUERY, COD_TIPO_ACAO_INTEGRACAO,IND_UTILIZA_LOG,DTH_ULTIMA_EXECUCAO)
VALUES (3,1,
        'SELECT DATE_FORMAT(NOW(), ''%d/%m/%Y %H:%i:%s'') AS DTH, pv1.pv1_cod AS CARGA, pv1.pv1_cod AS PLACA, pv1.pv1_cod AS PEDIDO, 1 AS COD_ROTA, ''PADRAO'' AS DSC_ROTA, pv1.cg1_cod AS COD_CLIENTE, cg1.cg1_nome AS NOME, IF(cg1.cg1_tipopessoa = ''J'',cg1.cg1_cgc, cg1.cg1_cpf) AS CPF_CNPJ, cg1.cg1_tipopessoa AS TIPO_PESSOA, cg1.cg1_end AS LOGRADOURO, cg1.cg1_numero AS NUMERO, cg1.cg1_bairro AS BAIRRO, cg1.cg1_cidade CIDADE, cg1.cg1_uf AS UF, cg1.cg1_compl AS COMPLEMENTO, NULL AS REFERENCIA, cg1.cg1_cep AS CEP, pv2.es1_cod AS PRODUTO, ''UNICA'' AS GRADE, pv2.pv2_quant AS QTD, pv2.pv2_TotItem AS VLR_VENDA FROM sglinx.pv2 INNER JOIN sglinx.pv1 ON pv1.pv1_cod = pv2.pv1_cod AND pv1.pv1_empresa = pv2.pv1_empresa INNER JOIN sglinx.cg1 ON cg1.cg1_cod = pv1.cg1_cod WHERE pv1.pv1_data >= :dthExecucao',
        602,'S',null);

INSERT INTO ACAO_INTEGRACAO (COD_ACAO_INTEGRACAO, COD_CONEXAO_INTEGRACAO, DSC_QUERY, COD_TIPO_ACAO_INTEGRACAO,IND_UTILIZA_LOG,DTH_ULTIMA_EXECUCAO)
VALUES (4,1,
        'SELECT C.COD_CARGA_EXTERNO as CARGA, SUM(PP.QUANTIDADE - NVL(pp.QTD_CORTADA,0)) as QTD FROM PEDIDO_PRODUTO PP LEFT JOIN PEDIDO P ON P.COD_PEDIDO = PP.COD_PEDIDO LEFT JOIN CARGA C ON C.COD_CARGA = P.COD_CARGA WHERE C.COD_CARGA_EXTERNO = :?1 GROUP BY COD_CARGA_EXTERNO',
        603,'S',null);

INSERT INTO ACAO_INTEGRACAO (COD_ACAO_INTEGRACAO, COD_CONEXAO_INTEGRACAO, DSC_QUERY, COD_TIPO_ACAO_INTEGRACAO,IND_UTILIZA_LOG,DTH_ULTIMA_EXECUCAO)
VALUES (5,1,
        'SELECT C.COD_CARGA_EXTERNO as CARGA, P.COD_PEDIDO as PEDIDO, PP.COD_PRODUTO as PRODUTO, PP.DSC_GRADE as GRADE, SUM(PP.QUANTIDADE - NVL(pp.QTD_CORTADA,0)) as QTD FROM PEDIDO_PRODUTO PP LEFT JOIN PEDIDO P ON P.COD_PEDIDO = PP.COD_PEDIDO LEFT JOIN CARGA C ON C.COD_CARGA = P.COD_CARGA WHERE C.COD_CARGA_EXTERNO = :?1 GROUP BY COD_CARGA_EXTERNO, P.COD_PEDIDO, PP.COD_PRODUTO, PP.DSC_GRADE',
        604,'S',null);

INSERT INTO ACAO_INTEGRACAO (COD_ACAO_INTEGRACAO, COD_CONEXAO_INTEGRACAO, DSC_QUERY, COD_TIPO_ACAO_INTEGRACAO,IND_UTILIZA_LOG,DTH_ULTIMA_EXECUCAO)
VALUES (6,1,
        'SELECT DATE_FORMAT(NOW(), ''%d/%m/%Y %H:%i:%s'') AS DTH, cmd.cg2_cod AS COD_FORNECEDOR, IF(cg2.cg2_tipopessoa = ''J'',cg2.cg2_cgc, cg2.cg2_cpf) AS CPF_CNPJ, IF(cg2.cg2_tipopessoa = ''J'',cg2.cg2_inscestad, cg2.cg2_rg) AS INSCRICAO_ESTADUAL, cg2.cg2_nome AS NOM_FORNECEDOR, cmd.cmd_num AS NUM_NOTA_FISCAL, cmd.cmd_serie AS COD_SERIE_NOTA_FISCAL, DATE_FORMAT(cmd.cmd_emissao , ''%d/%m/%Y'') AS DAT_EMISSAO, cmd.cmd_placa AS DSC_PLACA_VEICULO, cma.es1_cod AS COD_PRODUTO, ''UNICA'' AS DSC_GRADE, cma.cma_quant AS QTD_ITEM, cma.cma_vtotal AS VLR, cmd.cmd_dtent FROM sglinx.CMD INNER JOIN sglinx.cma ON cma.cmd_num = cmd.cmd_num AND cma.cmd_serie = cmd.cmd_serie AND cma.cg2_cod = cmd.cg2_cod AND cma.cmd_empresa = cmd.cmd_empresa AND cma.cmd_modelo = cmd.cmd_modelo AND cma.cmd_emissao = cmd.cmd_emissao INNER JOIN sglinx.cg2 ON cg2.cg2_cod = cmd.cg2_cod WHERE  cmd.cmd_dtent >= :dthExecucao',
        605,'S',null);
