INSERT INTO VERSAO (DTH, NUMERO_VERSAO, SCRIPT) VALUES (SYSDATE, '5.0.0','XX-permissao-corte-automatico.sql');

ALTER TABLE EXPEDICAO_ANDAMENTO ADD IND_CORTE_AUTOMATICO CHAR(1);

INSERT INTO PARAMETRO (
  COD_PARAMETRO, COD_CONTEXTO_PARAMETRO, DSC_PARAMETRO,
  DSC_TITULO_PARAMETRO, IND_PARAMETRO_SISTEMA, COD_TIPO_ATRIBUTO, DSC_VALOR_PARAMETRO)
VALUES (
  SQ_PARAMETRO_01.NEXTVAL,
  (SELECT COD_CONTEXTO_PARAMETRO FROM CONTEXTO_PARAMETRO WHERE DSC_CONTEXTO_PARAMETRO LIKE 'EXPEDIÇÃO'),
  'PERMISSAO_CORTE_AUTOMATICO',
  'Permitir corte automático na reserva de expedição',
  'S', 'A', 'N');

INSERT INTO RECURSO (DSC_RECURSO,COD_RECURSO,COD_RECURSO_PAI,NOM_RECURSO)
VALUES ('Itens Cortados',SQ_RECURSO_01.NEXTVAL,0,'itens_cortados');

INSERT INTO RECURSO (DSC_RECURSO,COD_RECURSO,COD_RECURSO_PAI,NOM_RECURSO)
VALUES ('Itens Cortados',SQ_RECURSO_01.NEXTVAL,0,'expedicao:itens_cortados');

INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO)
VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO LIKE 'importacao:gerenciamento'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO LIKE 'index'), 'Inserir registros de integração');

INSERT INTO MENU_ITEM (COD_MENU_ITEM, COD_RECURSO_ACAO, COD_PAI, DSC_MENU_ITEM, NUM_PESO,DSC_URL,DSC_TARGET,SHOW)
VALUES (SQ_MENU_ITEM_01.NEXTVAL, (select COD_RECURSO_ACAO from recurso_acao where COD_RECURSO = (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO LIKE 'importacao:gerenciamento') AND COD_ACAO = (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO LIKE 'index')),
        (SELECT COD_MENU_ITEM FROM MENU_ITEM WHERE DSC_MENU_ITEM = 'Importação'),'Integração Generica',10,'#','_self','N');