<?php
/**
 * Created by PhpStorm.
 * User: Tarcísio César
 * Date: 20/05/2020
 * Time: 10:51
 */
?>
<style>
    .btn {
        width: 95%;
    }

    .lbl-headers {
        font-size: 15px;
        font-weight: bold;
        padding: 0 6px;
    }

    div.input-area {
        padding: 10px;
        margin: 10px 15px;
        background-color: #f3f3f3;
        border-radius: 10px;
    }

    html, body {
        margin:0;
        height: 100%;
    }

    .btn-spacing {
        margin-top: 5px;
    }

    .div-loader {
        float:left;
        z-index: 99999;
        padding-top: 30px;
        position: absolute;
        background: #FFFFFF;
        width: 100%;
        height: inherit;
    }

    .btn-toggle {
        -moz-box-shadow:inset 0px 1px 0px 0px #ffffff;
        -webkit-box-shadow:inset 0px 1px 0px 0px #ffffff;
        box-shadow:inset 0px 1px 0px 0px #ffffff;
        background:-webkit-gradient(linear, left top, left bottom, color-stop(0.05, #ffffff), color-stop(1, #f6f6f6));
        background:-moz-linear-gradient(top, #ffffff 5%, #f6f6f6 100%);
        background:-webkit-linear-gradient(top, #ffffff 5%, #f6f6f6 100%);
        background:-o-linear-gradient(top, #ffffff 5%, #f6f6f6 100%);
        background:-ms-linear-gradient(top, #ffffff 5%, #f6f6f6 100%);
        background:linear-gradient(to bottom, #ffffff 5%, #f6f6f6 100%);
        filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#ffffff', endColorstr='#f6f6f6',GradientType=0);
        background-color:#ffffff;
        -webkit-border-radius:6px;
        -moz-border-radius:6px;
        border-radius:6px;
        border:1px solid #dcdcdc;
        display:inline-block;
        cursor:pointer;
        color:#666666;
        font-size:15px;
        font-weight:bold;
        padding:1px 24px 1px 16px;
        text-decoration:none;
        text-shadow:0px 1px 0px #ffffff;
        width: auto;
    }
    .btn-toggle:hover {
        background:-webkit-gradient(linear, left top, left bottom, color-stop(0.05, #f6f6f6), color-stop(1, #ffffff));
        background:-moz-linear-gradient(top, #f6f6f6 5%, #ffffff 100%);
        background:-webkit-linear-gradient(top, #f6f6f6 5%, #ffffff 100%);
        background:-o-linear-gradient(top, #f6f6f6 5%, #ffffff 100%);
        background:-ms-linear-gradient(top, #f6f6f6 5%, #ffffff 100%);
        background:linear-gradient(to bottom, #f6f6f6 5%, #ffffff 100%);
        filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#f6f6f6', endColorstr='#ffffff',GradientType=0);
        background-color:#f6f6f6;
    }
    .btn-toggle:active {
        position:relative;
        top:1px;
    }

    #arrow-info {
        -moz-transition: transform 350ms;
        -webkit-transition: transform 350ms;
        transition: transform 350ms;
    }

    .flip {
        transform: rotate(-180deg);
    }

    .accordion-title {

    }

    .accordion-item {

    }

    .accordion-row {

    }
</style>

<div id="dummy"></div>
<bgsound id="bgSoundId" loop="0" volume="100" />

<div id="loader" class="div-loader">
    <span style="font-size: 18px">Carregando...</span>
    <img src="/img/ajax-bar-loader.gif" alt="loading">
</div>

<div id="divBtnBack" style="display: none; margin-bottom: 5px">
    <button class="btn gradientBtn btn-spacing" id="btn-back-action">Voltar</button>
    <button class="btn gradientBtnSuccess btn-spacing" id="btn-start-action">Iniciar Conferência</button>
</div>

<a href="#messenger" style="display: none" id="anchorMsg"></a>
<div id="messenger"></div>

<div id="headers" style="padding-top: 5px; display: none">
    <div class="lbl-headers" id="lbl-expedicao"></div>
</div>

<div id="form-danfe" style="display: none;">
    <h3>Conferência de Carregamento</h3>
    <div class="input-area">
        <form>
            <div class="field">
                <label for="cod-barras-danfe" class="field required"><div class="lbl-headers">Chave de acesso da DANFE</div></label>
                <input type="number" name="cod-barras-danfe" id="cod-barras-danfe" data-destine="danfe" class="required focus enter-active" size="40" maxlength="100" style="width: 99%" alt="number">
            </div>
        </form>
        <button id="btn-consultar-danfe" class="btn gradientBtn btn-spacing">Buscar</button>
    </div>
    <div id="list-clients" style="padding-top: 5px; display: none">
        <div id="accordion">

        </div>
    </div>
    <div id="btn-row" style="padding-top: 6px; display: none">
        <button id="toggleInfo" class="btn-toggle"><img id="arrow-info" src="/img/icons/bullet_arrow_up.png" width="24" height="24" alt="Arrow direction"><span>Ocultar Info</span></button>
    </div>
</div>

<div id="bipagem-volume" style="display: none">
    <div class="input-area">
        <form>
            <div class="field">
                <label for="cod-barras-vol" class="field required"><div class="lbl-headers">Conferir Volume</div></label>
                <input type="text" name="cod-barras-vol" id="cod-barras-vol" data-destine="vol" class="required focus enter-active" size="40" maxlength="100" style="width: 99%" alt="number">
            </div>
        </form>
        <button id="btn-consultar-vol" class="btn gradientBtn btn-spacing">Buscar</button>
    </div>
</div>


<script>
    $(function () {
        $(".accordion-title").click( function () {
            toggleAccordionActive($(this));
        })

        var toggleAccordionActive = function (accHeader) {
            var active = $(".accordion-title.active");
            if (!isEmpty(active) && active.attr("id") !== accHeader.attr("id")) {
                active.toggleClass("active");
            }
            accHeader.toggleClass("active");
        }

        $(".enter-active").keypress(function( event ) {
            if (event.which === 13 || event.keyCode === 13) {
                disarmEvent(event);
                if (!isEmpty($(this).val())) {
                    if ($(this).data('destine') === 'danfe') {
                        validateDanfe($(this));
                    } else if ($(this).data('destine') === 'vol') {
                        //validateDanfe($(this));
                    }
                }
            }
        });

        var expConf = {
            codExpedicao: null,
            clientes: []
        };

        var danfeInfo = null;

        var showing = 0;
        var views = ["loader","form-danfe","bipagem-volume"];
        var msgShowed = true;

        function myIndexOf(collection, target) {
            var index;
            for(var val in collection){
                if(collection[val] === target){
                    index = val;
                    return index;
                }
            }
            return -1;
        }

        function playSound(soundfile) {
            if (<?php echo $this->isOldBrowserVersion ?> === 'S') {
                document.getElementById("bgSoundId").src = soundfile;
            } else {
                var dummy = '<audio autoplay> <source src=' + soundfile + ' type="audio/mp3">' +
                    '<source src="' + soundfile + '" type="audio/mpeg"></audio>';
                $('#dummy').html(dummy);
            }
        }

        $(document).ready(function () {
            changeViewer('form-danfe');
        });

        var disarmEvent = function (event) {
            if (event.preventDefault) {
                event.preventDefault();
            } else {
                event.returnValue = false;
            }
        };

        var dispareSound = function (type) {
            var songFile = "/alarme_curto.mp3";
            if (type === "success") {
                songFile = "/confirm2.mp3";
            } else if (type === "warning") {
                songFile = "/warning.mp3";
            }

            playSound(songFile);
        };

        var notificar = function (type, msg, instantShowed) {
            if (type === undefined) type = "success";

            $("#messenger").html(
                '<ul class="flashMessenger">' +
                '    <li class="' + type + '_message" id="">' +
                '        <div style="display:block; float:right;">' +
                '            <a href="#" class="fmBtnClose">X</a>' +
                '        </div>' +
                '        <div style="display: block;" id="msg-text">' + msg + '</div>' +
                '    </li>' +
                '</ul>');

            dispareSound(type);

            if (type === "error") alert(msg);
            msgShowed = instantShowed;

            focusOnInput()
            return (type === "success");
        };

        $(".fmBtnClose").live("click", function () {
            $("#messenger").empty();
        });

        var changeViewer = function (changeTo) {
            $.each(views, function (k,v) {
                $("#"+v).hide();
            });

            if (changeTo === undefined || myIndexOf(views, changeTo) < 0) {
                changeTo = views[1];
            }

            showing = myIndexOf(views, changeTo);

            if (showing > 1) {
                $("#divBtnBack").show();
            } else {
                $("#divBtnBack").hide();
            }

            if (changeTo !== "loader") {
                if (msgShowed) {
                    $("#messenger").empty();
                } else {
                    msgShowed = true;
                }
            }

            $("#" + changeTo).show();

            focusOnInput();

            if ($("#messenger > ul > li.warning_message, #messenger > ul >li.error_message").length > 0)
                $("#anchorMsg")[0].click();
        };

        var focusOnInput = function () {
            $("div.input-area form div:visible:first input").val("").focus();
        }

        $("#btn-back-action").click(function () {
            changeViewer('form-danfe');
        });

        $("#toggleInfo").click(function () {
            $(this).blur();
            if ($(this).hasClass("hiddingInfo")) {
                $("#headers").show(350);
                $(this).children("span").text("Ocultar Info");
            } else {
                $("#headers").hide(350);
                $(this).children("span").text("Exibir Info");
            }
            $(this).toggleClass("hiddingInfo");
            $(this).children("img").toggleClass("flip");
        });

        $("#btn-consultar-danfe").click(function () {
            validateDanfe($("#cod-barras-danfe"))
        });

        var validateDanfe = function (inpt) {
            if (inpt.val().length !== 44) {
                return notificar("error", "O código de barras bipado não tem a quantidade correta de dígitos exigidos");
            }

            changeViewer("loader");
            if (isEmpty(expConf.codExpedicao)) {
                getInfoDanfe(inpt.val());
            } else {
                checkOrInclude(inpt.val());
            }
            changeViewer("form-danfe");
        }

        var getInfoDanfe = function (keypass) {
            $.ajax({url: "/mobile/carregamento/get-info-danfe/keypass/" + keypass,
                success: function(result){
                    if (result.status === "ok") {
                        danfeInfo = result.response;
                    } else {
                        return notificar("error", result.exception);
                    }
                }, complete: function() {
                    if (!isEmpty(danfeInfo)) {
                        checkOrInclude(keypass);
                        danfeInfo = null;
                    }
                }
            });
        }

        var prepareInfoConf = function () {
            if (!isEmpty(expConf.codExpedicao)) {
                $("#lbl-expedicao").text("Carregamento da Expedição: " + expConf.codExpedicao).show();
                $("#headers").show();
                $("#list-clients").show();
            }
        }

        var checkOrInclude = function (keypass) {
            if (!isEmpty(danfeInfo)) {
                if (isEmpty(expConf.codExpedicao)) {
                    expConf = danfeInfo;
                    prepareInfoConf();
                } else {
                    if (expConf.codExpedicao === danfeInfo.codExpedicao) {
                        $.each(danfeInfo.clientes, function (i, cliente) {
                            expConf.clientes[i] = cliente;
                        });
                    } else {
                        return notificar("error", "Esta DANFE não está relacionada à expedição inicial desta conferência");
                    }
                }
                addNewClienteInfo(danfeInfo);
            }
            var forceExit = false;
            var findded = false;
            $.each(expConf.clientes, function (i, cliente) {
                $.each(cliente.danfes, function (key, danfe) {
                    if (key === keypass) {
                        if (!danfe.status) {
                            expConf.clientes[i].danfes[key].status = true;
                            notificar("success", "DANFE incluída com sucesso")
                        }
                        else {
                            notificar("error", "DANFE já incluída");
                        }
                        forceExit = true;
                        findded = true;
                    }
                    if (forceExit) return false;
                })
                if (forceExit) return false;
            })
            if (!findded) {
                getInfoDanfe(keypass);
            }
            checkClienteLiberado();
        }

        var checkClienteLiberado = function () {
            $.each(expConf.clientes, function (i, cliente) {
                var nfsOk = 0;
                $.each(cliente.danfes, function (danfe) {
                    if (danfe.status) nfsOk++;
                })
                expConf.clientes[i].checked = nfsOk;
                expConf.clientes[i].liberado = (cliente.totalDanfes === nfsOk);
            })
        }

        var addNewClienteInfo = function (danfe) {
            var listClients = $("#list-clients");
            listClients.html("");
            /*
                <div class='accordion-row'>
                    <h5 class='accordion-tittle'></h5>
                    <div class='accordion-content'></div>
                </div>
             */
            $.each(danfe.clientes, function (i, cliente) {
                var content = $("<div class='accordion-content'>");
                $.each(cliente.danfes, function (keypass, danfe) {
                    content.append($("<p class='accordion-item' id='danfe-info-"+keypass+"'>" +danfe.nota+"</p>"))
                })
                var title = $("<h5 class='accordion-title' id='div-accordion-" + i + "' data-client='" + i + "'>" + cliente.nome + "<span id='span-nfs'></span></h5>");
                var spanNfs = $("<span id='span-notas-ok-" + i + "'>"+ cliente.checked + "</span> de <span id='span-notas-total-" + cliente.i + "'>"+ cliente.totalDanfes + "</span>");
                title.find("div#span-nfs").append(spanNfs);
                var newAccordionRow = $("<div class='accordion-row'>")
                newAccordionRow.append(title).append(content);
                $("#list-clients").append(newAccordionRow);
            })
            var divAccordion = $("<div id='accordion'>")
            $("#accordion").accordion({
                header: "> div > h5",
                collapsible: true
            });
        }
    })
</script>
