<form id="header-expedicao-os-form" class="header" action="">
        <div>
            <fieldset id="fieldset-expedicao">
                <legend> Expediçao - placa: <?php echo $this->expedicao->getplacaExpedicao() ?></legend>
                <table style="width: 100%;">
                    <tbody>
                    <tr>
                        <td style="font-size: 16px; font-weight: bold">Expedicao</td>
                        <td style="font-size: 16px; font-weight: bold">Status</td>
                        <td style="font-size: 16px; font-weight: bold">Inicio</td>
                        <td style="font-size: 16px; font-weight: bold">Fim</td>
                    </tr>
                    <tr>
                        <td style="font-size: 14px;"><?php echo $this->idExpedicao; ?></td>
                        <td style="font-size: 14px;"><?php echo $this->status; ?></td>
                        <td style="font-size: 14px;"><?php echo $this->dataInicio;?></td>
                        <td style="font-size: 14px;"><?php echo $this->dataFim;?></td>
                    </tr>
                    <?php if ($this->expedicao->getStatus()->getId() != \Wms\Domain\Entity\Expedicao::STATUS_PARCIALMENTE_FINALIZADO) : ?>
                        <?php if ($this->qtdEtiquetas>0) {?>
                            <tr>
                                <td colspan="4">
                                    <table style="margin-top: 10px" class="gTable grid-expedicao-etiquetas">
                                        <caption>Etiquetas</caption>
                                        <tbody>
                                            <tr class="gTTitle">
                                                <td colspan="1"></td>
                                                <td width=""><span><b>Qtd. Etiquetas</b></span></td>
                                                <td width=""><span><b>Etq. Conferidas</b></span></td>
                                                <td width=""><span><b>Etq. Pendentes</b></span></td>
                                                <td width=""><span><b>% Conferencia</b></span></td>
                                            </tr>
                                            <tr class="gTResultSet">
                                                <td class="gTdOpcRow">
                                                    <div class="gOpcRow">
                                                        <ul>
                                                            <li><img src="/img/admin/icon_opc.gif" alt="Opções">
                                                                <ul>
                                                                    <li><a href="<?php echo "/expedicao/pendencia/index/id/" . $this->idExpedicao . "/status/522,523,524,525,526,531,532"; ?>" class="dialogAjax" title="" target="_self">Visualizar Etiquetas</a></li>
                                                                </ul>
                                                            </li>
                                                        </ul>
                                                    </div>
                                                </td>
                                                <td width = ""><span><?php echo $this->qtdEtiquetas;?></span></td>
                                                <td width = ""><span><?php echo $this->qtdConferidas;?></span></td>
                                                <td width = ""><span><?php echo $this->qtdPendentes;?></span></td>
                                                <td width = ""><span><?php echo $this->percentualConclusao;?></span></td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </td>
                            </tr>
                        <?php }?>
                        <?php if (isset($this->gridMapas)) {?>
                            <tr>
                                <td colspan="4">
                                    <?php echo $this->gridMapas?>
                                </td>
                            </tr>
                        <?php }?>
                    <?php endif; ?>
                    </tbody>
                </table>
            </fieldset>
        </div>

    <?php if ($this->expedicao->getStatus()->getId() == \Wms\Domain\Entity\Expedicao::STATUS_PARCIALMENTE_FINALIZADO) : ?>
        <div>
            <fieldset id="fieldset-resumo-cargas">
                <legend> Resumo por Placa da Carga</legend>
                <table class="gTable">
                    <tbody>
                       <tr calss = "">
                           <td width=""><span><b>Placa</b></span></td>
                           <td width=""><span><b>Ponto de Transbordo</b></span></td>
                           <td width=""><span><b>Qtd. Etiquetas</b></span></td>
                           <td width=""><span><b>Qtd. Conferidas</b></span></td>
                           <td width=""><span><b>Qtd. Recebido Transbordo</b></span></td>
                           <td width=""><span><b>Qtd. Expedido Transbordo</b></span></td>
                           <td width=""><span><b>Pendencias</b></span></td>
                       </tr>
                       <?php foreach($this->resumoPlacaCarga as $resumo) : ?>
                           <tr calss = "">
                               <td width=""><span><?php echo $resumo['placaCarga'];            ?></span></td>
                               <td width=""><span><?php echo $resumo['pontoTransbordo'];            ?></span></td>
                               <td width=""><span><?php echo $resumo['qtdEtiqueta'];           ?></span></td>
                               <td width=""><span><?php echo $resumo['qtdConferidas'];         ?></span></td>
                               <td width=""><span><?php echo $resumo['qtdRecebidoTransbordo']; ?></span></td>
                               <td width=""><span><?php echo $resumo['qtdExpedidoTransbordo']; ?></span></td>
                               <td width=""><span><a class="btn reader dialogAjax"
                                                     href="<?php echo "/expedicao/pendencia/index/id/". $this->idExpedicao . "/placa/" . $resumo['placaCarga'] . "/transbordo/" . $resumo['pontoTransbordo'] ?>">Pendencias</a></span></td>
                           </tr>
                       <?php endforeach; ?>
                    </tbody>
                </table>
            </fieldset>
        </div>
    <?php endif; ?>
</form>

<div class="padding-top">
    <?php
        echo $this->gridOS;
    ?>
</div>

<br>
<br>

<div class="padding-top">
    <?php
    echo $this->gridAndamento;
    ?>
</div>

<br>
<br>

<div class="padding-top">
    <?php
        echo $this->gridPendencias;
    ?>
</div>

