INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO LIKE 'expedicao:corte'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO LIKE 'list'), 'Listar Produtos do Pedido');
INSERT INTO ACAO (COD_ACAO, DSC_ACAO, NOM_ACAO) VALUES (SQ_ACAO_01.NEXTVAL, 'Cortar Pedidos da expedicao', 'cortar-pedido');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO LIKE 'expedicao:corte-pedido'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO LIKE 'cortar-pedido'), 'Cortar Pedido da Expedição');
INSERT INTO ACAO (COD_ACAO, DSC_ACAO, NOM_ACAO) VALUES (SQ_ACAO_01.NEXTVAL, 'Cortar Itens dos Pedidos', 'cortar-item');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO LIKE 'expedicao:corte'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO LIKE 'cortar-item'), 'Cortar Itens dos Pedido');


/* Rode primeiro essa linha, caso de problema de unique key, significa que esse arquivo .sql já foi executado anteriormente */
INSERT INTO VERSAO (DTH, NUMERO_VERSAO, SCRIPT) VALUES (SYSDATE, '3.8.2', 'mapaSeparacaoPedido.sql');

CREATE TABLE MAPA_SEPARACAO_PEDIDO
  (
    COD_MAPA_SEPARACAO_PEDIDO NUMBER (8) NOT NULL ,
    COD_MAPA_SEPARACAO        NUMBER (8) NOT NULL ,
	COD_PEDIDO_PRODUTO        NUMBER (8) NOT NULL
  )
  LOGGING ;

ALTER TABLE MAPA_SEPARACAO_PEDIDO
  ADD CONSTRAINT MAPA_SEPARACAO_PEDIDO_PK PRIMARY KEY (COD_MAPA_SEPARACAO_PEDIDO) ;

ALTER TABLE MAPA_SEPARACAO_PEDIDO
  ADD CONSTRAINT MAPA_SEPARACAO_PEDIDO_MS FOREIGN KEY (COD_MAPA_SEPARACAO) REFERENCES MAPA_SEPARACAO (COD_MAPA_SEPARACAO) NOT DEFERRABLE ;

ALTER TABLE MAPA_SEPARACAO_PEDIDO
  ADD CONSTRAINT MAPA_SEPARACAO_PEDIDO_PP FOREIGN KEY (COD_PEDIDO_PRODUTO) REFERENCES PEDIDO_PRODUTO (COD_PEDIDO_PRODUTO) NOT DEFERRABLE ;

CREATE SEQUENCE  SQ_MAPA_SEPARACAO_PEDIDO_01  MINVALUE 0 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;

