CREATE TABLE MAPA_SEPARACAO_PEDIDO
  (
    COD_MAPA_SEPARACAO_PEDIDO NUMBER (8) NOT NULL ,
    COD_MAPA_SEPARACAO        NUMBER (8) NOT NULL ,
	COD_PEDIDO_PRODUTO        NUMBER (8) NOT NULL
  )
  LOGGING ;

ALTER TABLE MAPA_SEPARACAO_PEDIDO
  ADD CONSTRAINT MAPA_SEPARACAO_PEDIDO_PK PRIMARY KEY (COD_MAPA_SEPARACAO_PEDIDO) ;

ALTER TABLE MAPA_SEPARACAO_PEDIDO
  ADD CONSTRAINT MAPA_SEPARACAO_PEDIDO_MS FOREIGN KEY (COD_MAPA_SEPARACAO) REFERENCES MAPA_SEPARACAO (COD_MAPA_SEPARACAO) NOT DEFERRABLE ;

ALTER TABLE MAPA_SEPARACAO_PEDIDO
  ADD CONSTRAINT MAPA_SEPARACAO_PEDIDO_PP FOREIGN KEY (COD_PEDIDO_PRODUTO) REFERENCES PEDIDO_PRODUTO (COD_PEDIDO_PRODUTO) NOT DEFERRABLE ;

CREATE SEQUENCE  SQ_MAPA_SEPARACAO_PEDIDO_01  MINVALUE 0 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;

INSERT INTO VERSAO (DTH, NUMERO_VERSAO, SCRIPT) VALUES (SYSDATE, '3.8.2', 'mapaSeparacaoPedido.sql');