<h3>Recebimentos Pendentes de Endereçamento</h3>
<ul class="menu">
    <?php if(count($this->recebimentos) == 0): ?>
        <li>Nenhum Recebimento aguardando conferência.</li>
    <?php elseif(count($this->recebimentos) > 0): ?>
        <?php foreach($this->recebimentos as $recebimento): ?>
            <li>
                <a href="<?php echo $this->url(array('controller' => 'enderecamento_manual', 'action' => 'ler-codigo-barras', 'id' => $recebimento['COD_RECEBIMENTO'], 'manual' => 1)); ?>"
                   title="<?php echo $recebimento['COD_RECEBIMENTO'] ?>" >Cod. Receb. <?php echo $recebimento['COD_RECEBIMENTO'] ?> - <?php echo $recebimento['BOX'] ?> - <?php echo $recebimento['NOM_FANTASIA'] ?></a>
            </li>
        <?php endforeach; ?>
    <?php endif;?>
</ul>