<div class="col-xs-12 text-center" >
    ﻿<h3>Recebimentos Pendentes de Endereçamento</h3>
    <?php if (count($this->recebimentos) == 0): ?>
        <p>Nenhum Recebimento aguardando conferência.</p>
    <?php elseif (count($this->recebimentos) > 0): ?>
        <?php foreach ($this->recebimentos as $recebimento): ?>
            <a class="btn gradientBtn" href="<?php echo $this->url(array('controller' => 'enderecamento_manual', 'action' => 'ler-codigo-barras', 'id' => $recebimento['COD_RECEBIMENTO'], 'manual' => 1)); ?>"
               title="<?php echo $recebimento['COD_RECEBIMENTO'] ?>" >Cod. Receb. <?php echo $recebimento['COD_RECEBIMENTO'] ?> - <?php echo $recebimento['BOX'] ?> - <?php echo $recebimento['NOM_FANTASIA'] ?></a>
           <?php endforeach; ?>
       <?php endif; ?>
</div>