<script>
    function nextInput(event, id) {
        if (event.which == 13 || event.keyCode == 13) {
            if (document.getElementById('produto').value != "") {
                endereco = document.getElementById('endereco');
                if (endereco) {
                    endereco.focus();
                    if (event.preventDefault) {
                        event.preventDefault();
                    } else {
                        event.returnValue = false;
                    }
                }
            }
            if (document.getElementById('endereco').value != "") {
                qtd = document.getElementById('qtd');
                if (qtd) {
                    qtd.focus();
                    if (event.preventDefault) {
                        event.preventDefault();
                    } else {
                        event.returnValue = false;
                    }
                }
            }
        }
        return true;
    }
</script>
<?php $this->headScript()->appendFile($this->baseUrl('coletor/enderecamento.js')); ?>
<div class="col-xs-12 text-center" >
    <form id="formulario">
        <dt id="identification-label">&nbsp;</dt>
        <dd id="identification-element">
            <fieldset id="fieldset-identification">
                <legend>Endereçamento Manual</legend>
                <div class="field">
                    <label>Produto:</label>
                    <input style="width: 99%" maxlength="100" class="focus form-control" size="40" type="text" name="produto" id="produto" value="" onkeydown="nextInput(event)" />
                </div>
                <div class="field">
                    <label>Endereço:</label>
                    <input style="width: 99%" class="form-control" maxlength="100" size="40" type="text" name="endereco" id="endereco" value="" onkeydown="nextInput(event)"/>
                </div>
                <div class="field">
                    <label>Qtd:</label>
                    <input style="width: 99%" class="form-control" maxlength="100" size="40" type="text" name="qtd" id="qtd" value="" />
                </div>
<!--                <input type="hidden" name="capacidadePicking" id="capacidadePicking" value="--><?php //echo $this->capacidadePicking  ?><!--">-->
                <div id="inserir"></div>
                <input class="btn gradientBtn" type="submit" name="submit" id="submit" value="Buscar" />
            </fieldset>
        </dd>
    </form>
</div>