<?php $this->headScript()->appendFile($this->baseUrl('coletor/enderecamento.js')); ?>
<div class="row text-center" >
    <form id="formulario" method="post">
        <dt id="identification-label">&nbsp;</dt>
        <dd id="identification-element">
            <fieldset id="fieldset-identification">
                <legend>Endereçamento Manual</legend>
                <input type="hidden" id="reservas" name="reservas">
                <input type="hidden" id="controlaLote" name="controlaLote" value="0">
                <div class="field">
                    <label>Produto:</label>
                    <input style="width: 99%" maxlength="100" class="focus form-control" size="40" type="text" name="produto" id="produto" value="" onkeydown="nextInput(this, event)"/>
                </div>
                <div class="field">
                    <label>Endereço:</label>
                    <input style="width: 99%" class="form-control" maxlength="100" size="40" type="text" name="endereco" id="endereco" value="" onkeydown="nextInput(this, event)"/>
                </div>
                <div class="field">
                    <label>Qtd:</label>
                    <input style="width: 99%" class="form-control" maxlength="100" size="40" type="text" name="qtd" id="qtd" value="" onkeydown="nextInput(this, event)"/>
                </div>
                <div class="field div-lote" style="display: none">
                    <label>Lote:</label>
                    <input style="width: 99%" class="form-control" maxlength="100" size="40" type="text" name="lote" id="lote" value="" onkeydown="nextInput(this, event)"/>
                </div>
                <div id="inserir"></div>
                <input class="btn gradientBtn lock-dbl-click" type="submit" name="submit" id="submit" value="Buscar" />
            </fieldset>

            <?php if ($this->teste == "S") {?>
                <fieldset id="Produto">
                    <legend>Endereços do Produto</legend>
                    <legend><?php echo $this->teste; ?></legend>
                </fieldset>
            <?php }?>

            <div id="lista-endereco"></div>

        </dd>
    </form>
</div>
<script>
    let controlaLote = false;

    $(function () {
        $("#efetivaEndPicking").live("click", function () {
            $("#qtd").val($(this).data('qtd')).prop('readonly', true);
            $("#submit").val("Confirmar");
            $("#reservas").val($(this).data('reservas'));
            $("#endereco").val('').focus();
        })
    });

    $(".form-control").focusin(function () {
        $(this).select();
    });

    function nextInput(input, event) {
        let inputReservas= $("#reservas");
        let inputEndereco = $("#endereco");
        let inputQtd = $("#qtd");
        let inputLote = $("#lote");
        let cancelEvet = false;
        if ((event.which === 13 || event.keyCode === 13) && !isEmpty(input.value)) {
            if (input.id === 'produto') {
                consultar(input.value);
                inputEndereco.focus();
            } else if (input.id === 'endereco' && isEmpty(inputReservas.val())) {
                inputQtd.focus();
            } else if (input.id === 'qtd' && controlaLote ) {
                inputLote.focus();
            } else if ((input.id === 'qtd' && !controlaLote) || (input.id === 'lote') || (input.id === 'endereco' && !isEmpty(inputReservas.val()))) {
                validateToSubmit();
            }
            cancelEvet = true;
        } else if ((event.which === 13 || event.keyCode === 13) && isEmpty(input.value)) {
            alert("Este campo não pode ficar vazio");
            cancelEvet = true;
        }

        if (cancelEvet) {
            if (event.preventDefault) {
                event.preventDefault();
            } else {
                event.returnValue = false;
            }
        }

        return true;
    }

    function consultar(val) {
        controlaLote = false;
        $.ajax({
            url: '/mobile/consulta-endereco/consultar/codigoBarras/' + val,
            success: function (data) {
                if (data.status === 'ok') {

                    $("#reservas").val('');
                    $("#submit").val("Buscar");
                    $("#qtd").prop('readonly', false);

                    var txt = '<fieldset id="fieldset-dadosProduto">';
                    txt += '<legend>Endereços do produto</legend>' +
                        '    <table class="gTable " style="width: 100%; border: 1px solid #E0E0E0;">' +
                        '        <tbody>' +
                        '        <tr class="gTTitle" style="background-color: #EDEDED; border-radius: 4px;\n' +
                        '    border: 1px solid #E0E0E0;' +
                        'line-height: 20px;">' +
                        '            <td><b>Endereço</b></td>' +
                        '            <td><b>Tipo</b></td>' +
                        '            <td><b>Qtd.</b></td>' +
                        '            <td><b>End. Pendente</b></td>' +
                        '            <td><b>Ação</b></td>' +
                        '        </tr>';

                    var color = true;

                    if (data.result.length >0) {

                        $.each(data.result, function (key, value) {
                            color = !color;

                            if(value.IND_CONTROLA_LOTE == 'S'){
                                //alert("linha 133");
                                controlaLote = true;
                                $('.div-lote').show();
                                $('#controlaLote').val(1);
                            }
                            if (color == true) {
                                txt += '<tr style="background-color: #EDEDED">'
                            } else {
                                txt += '<tr>'
                            }

                            txt += '   <td>' + value.ENDERECO + '</td>';
                            txt += '   <td>' + value.TIPO + '</td>';
                            txt += '   <td>' + value.QTD + '</td>';

                            if (value.RESERVAS !== null) {
                                txt += '   <td>' + value.QTD_RESERVADA +'</td>';
                                txt += '   <td><button type="button" id="efetivaEndPicking" data-reservas="'+value.RESERVAS+'" data-qtd="'+ value.QTD_RESERVADA +'" class="btn gradientBtn lock-dbl-click">Efetivar</button></td>';
                            } else {
                                txt += '   <td>-----</td>';
                                txt += '   <td>-----</td>';
                                txt += '</tr>'
                            }

                            txt += '</tr>'

                        });
                    } else {
                        txt += '<tr> <td colspan="3"> Produto não endereçado </td> </tr>'
                    }

                    txt += '</tbody>' +
                        '</table>';
                    txt += '</fieldset>';
                    $('#lista-endereco').html(txt);
                } else {
                    showErro(data.msg)
                }
            }
        });
    }

    function showErro(msg) {
        $('#lista-endereco').text(msg)
    }

    function validateToSubmit() {
        $("#submit").click();
    }

</script>