<form id="formulario">
        <dt id="identification-label">&nbsp;</dt>
        <dd id="identification-element">
            <fieldset id="fieldset-identification">
                <legend>Endereçamento Manual</legend>
                <div class="field">
                    <label>Informe um nivel:</label>
                    <input style="width: 99%" maxlength="100" size="40" type="text" name="nivel" id="nivel" value="" />
                </div>
                <input class="btn" type="submit" name="submit" id="submit" value="Buscar" />
            </fieldset>
        </dd>
</form>