INSERT INTO VERSAO (DTH, NUMERO_VERSAO, SCRIPT) VALUES (SYSDATE, '4.0.0', 'correcaoV_QTD_Recebimento.sql');

  CREATE OR REPLACE FORCE VIEW "WMS_SEGURACO"."V_QTD_RECEBIMENTO" ("QTD", "COD_RECEBIMENTO", "COD_PRODUTO", "DSC_GRADE", "COD_OS", "COD_NORMA_PALETIZACAO", "NUM_PESO") AS 
  SELECT MIN(QTD.QTD) as QTD,
    QTD.COD_RECEBIMENTO,
    QTD.COD_PRODUTO,
    QTD.DSC_GRADE,
    QTD.COD_OS,
    NP.COD_NORMA_PALETIZACAO,
	  SUM(QTD.NUM_PESO)
  FROM (SELECT SUM(NVL(RV.QTD_CONFERIDA,0)) AS QTD,
          RV.COD_RECEBIMENTO,
          RV.COD_PRODUTO_VOLUME,
          PV.COD_PRODUTO,
          PV.DSC_GRADE,
          OS.COD_OS,
		  SUM(RV.NUM_PESO) AS NUM_PESO
        FROM RECEBIMENTO_VOLUME RV
          INNER JOIN (SELECT DISTINCT DTH_FINAL_ATIVIDADE,
                        COD_OS,
                        COD_PRODUTO_VOLUME,
                        COD_RECEBIMENTO,
                        RANK() OVER(PARTITION BY COD_RECEBIMENTO, COD_PRODUTO_VOLUME ORDER BY DTH_FINAL_ATIVIDADE DESC) RANK
                      FROM (SELECT CASE WHEN DTH_FINAL_ATIVIDADE IS NULL THEN TO_DATE('31/12/9999','dd/mm/yyyy')
                                   ELSE DTH_FINAL_ATIVIDADE END AS DTH_FINAL_ATIVIDADE,
                              OS.COD_OS,
                              OS.COD_RECEBIMENTO,
                              RV.COD_PRODUTO_VOLUME
                            FROM RECEBIMENTO_VOLUME RV
                              LEFT JOIN ORDEM_SERVICO OS ON OS.COD_OS = RV.COD_OS)) OS
            ON OS.COD_OS = RV.COD_OS
               AND OS.RANK <= 1
               AND OS.COD_RECEBIMENTO = RV.COD_RECEBIMENTO
               AND OS.COD_PRODUTO_VOLUME = RV.COD_PRODUTO_VOLUME
          LEFT JOIN PRODUTO_VOLUME PV ON PV.COD_PRODUTO_VOLUME = RV.COD_PRODUTO_VOLUME
        GROUP BY RV.COD_RECEBIMENTO, RV.COD_PRODUTO_VOLUME, PV.COD_PRODUTO, PV.DSC_GRADE, OS.COD_OS, RV.NUM_PESO) QTD
    LEFT JOIN (SELECT MIN(RV.COD_NORMA_PALETIZACAO) as COD_NORMA_PALETIZACAO,
                 RV.COD_RECEBIMENTO,
                 PV.COD_PRODUTO,
                 PV.DSC_GRADE,
                 OS.COD_OS,
				 SUM(RV.NUM_PESO) AS NUM_PESO,
                 MIN(NP.NUM_NORMA) as NORMA
               FROM RECEBIMENTO_VOLUME RV
                 INNER JOIN (SELECT DISTINCT DTH_FINAL_ATIVIDADE,
                               COD_OS,
                               COD_PRODUTO_VOLUME,
                               COD_RECEBIMENTO,
                               RANK() OVER(PARTITION BY COD_RECEBIMENTO, COD_PRODUTO_VOLUME ORDER BY DTH_FINAL_ATIVIDADE DESC) RANK
                             FROM (SELECT CASE WHEN DTH_FINAL_ATIVIDADE IS NULL THEN TO_DATE('31/12/9999','dd/mm/yyyy')
                                          ELSE DTH_FINAL_ATIVIDADE END AS DTH_FINAL_ATIVIDADE,
                                     OS.COD_OS,
                                     OS.COD_RECEBIMENTO,
                                     RV.COD_PRODUTO_VOLUME
                                   FROM RECEBIMENTO_VOLUME RV
                                     LEFT JOIN ORDEM_SERVICO OS ON OS.COD_OS = RV.COD_OS)) OS
                   ON OS.COD_OS = RV.COD_OS
                      AND OS.RANK <= 1
                      AND OS.COD_RECEBIMENTO = RV.COD_RECEBIMENTO
                      AND OS.COD_PRODUTO_VOLUME = RV.COD_PRODUTO_VOLUME
                 LEFT JOIN PRODUTO_VOLUME PV ON PV.COD_PRODUTO_VOLUME = RV.COD_PRODUTO_VOLUME
                 LEFT JOIN NORMA_PALETIZACAO NP ON NP.COD_NORMA_PALETIZACAO = RV.COD_NORMA_PALETIZACAO
                 INNER JOIN RECEBIMENTO_CONFERENCIA RC ON RC.COD_OS = OS.COD_OS AND RC.COD_PRODUTO = PV.COD_PRODUTO
                 WHERE RC.QTD_DIVERGENCIA = 0 AND RC.QTD_AVARIA = 0 AND IND_DIVERGENCIA_PESO = 'N'
               GROUP BY RV.COD_RECEBIMENTO,  PV.COD_PRODUTO, PV.DSC_GRADE, OS.COD_OS, RV.NUM_PESO) NP
      ON NP.COD_RECEBIMENTO = QTD.COD_RECEBIMENTO
         AND NP.COD_PRODUTO = QTD.COD_PRODUTO
         AND NP.DSC_GRADE = QTD.DSC_GRADE
         AND NP.COD_OS = QTD.COD_OS
    
  GROUP BY QTD.COD_PRODUTO, QTD.COD_RECEBIMENTO, QTD.DSC_GRADE, QTD.COD_OS,QTD.NUM_PESO,NP.COD_NORMA_PALETIZACAO
  UNION
  SELECT SUM(RE.QTD_CONFERIDA * PE.QTD_EMBALAGEM) AS QTD,
    RE.COD_RECEBIMENTO,
    PE.COD_PRODUTO,
    PE.DSC_GRADE,
    OS.COD_OS,
    RE.COD_NORMA_PALETIZACAO,
	SUM(RE.NUM_PESO) AS NUM_PESO
  FROM RECEBIMENTO_EMBALAGEM RE
    INNER JOIN (SELECT DISTINCT DTH_FINAL_ATIVIDADE,
                  COD_OS,
                  COD_PRODUTO_EMBALAGEM,
                  COD_RECEBIMENTO,
                  RANK() OVER(PARTITION BY COD_RECEBIMENTO, COD_PRODUTO_EMBALAGEM ORDER BY DTH_FINAL_ATIVIDADE DESC) RANK
                FROM (SELECT CASE WHEN DTH_FINAL_ATIVIDADE IS NULL THEN TO_DATE('31/12/9999','dd/mm/yyyy')
                             ELSE DTH_FINAL_ATIVIDADE END AS DTH_FINAL_ATIVIDADE,
                        OS.COD_OS,
                        OS.COD_RECEBIMENTO,
                        RE.COD_PRODUTO_EMBALAGEM
                      FROM RECEBIMENTO_EMBALAGEM RE
                        LEFT JOIN ORDEM_SERVICO OS ON OS.COD_OS = RE.COD_OS)) OS
      ON OS.COD_OS = RE.COD_OS
         AND OS.RANK <= 1
         AND OS.COD_RECEBIMENTO = RE.COD_RECEBIMENTO
         AND OS.COD_PRODUTO_EMBALAGEM = RE.COD_PRODUTO_EMBALAGEM
    LEFT JOIN PRODUTO_EMBALAGEM PE ON PE.COD_PRODUTO_EMBALAGEM = RE.COD_PRODUTO_EMBALAGEM
    INNER JOIN RECEBIMENTO_CONFERENCIA RC ON RC.COD_OS = OS.COD_OS AND RC.COD_PRODUTO = PE.COD_PRODUTO
    WHERE RC.QTD_DIVERGENCIA = 0 AND RC.QTD_AVARIA = 0 AND IND_DIVERGENCIA_PESO = 'N'
  GROUP BY RE.COD_RECEBIMENTO,
    PE.COD_PRODUTO,
    PE.DSC_GRADE,
    OS.COD_OS,
    RE.COD_NORMA_PALETIZACAO;
