INSERT INTO VERSAO (DTH, NUMERO_VERSAO, SCRIPT) VALUES (SYSDATE, '4.0.0','indexCCBGeovani.sql');

create index dba_geovani_idx01 on MAPA_SEPARACAO_PRODUTO (COD_MAPA_SEPARACAO, COD_PRODUTO_EMBALAGEM);
create index dba_geovani_idx02 on MAPA_SEPARACAO_QUEBRA (COD_MAPA_SEPARACAO, IND_TIPO_QUEBRA, COD_QUEBRA);
create index dba_geovani_idx03 on MAPA_SEPARACAO_QUEBRA (COD_QUEBRA, COD_MAPA_SEPARACAO, IND_TIPO_QUEBRA);
create index dba_geovani_idx04 on MAPA_SEPARACAO_PEDIDO (COD_MAPA_SEPARACAO, COD_PEDIDO_PRODUTO);
create index dba_geovani_idx05 on MAPA_SEPARACAO_PEDIDO (COD_PEDIDO_PRODUTO, COD_MAPA_SEPARACAO);
create index dba_geovani_idx06 on MAPA_SEPARACAO (COD_STATUS);
create index dba_geovani_idx07 on PRODUTO (DSC_GRADE,COD_PRODUTO);
