INSERT INTO VERSAO (DTH, NUMERO_VERSAO, SCRIPT) VALUES (SYSDATE, 'v4.0.0', 'parametrosInativacao.sql');

INSERT INTO PARAMETRO
      (COD_PARAMETRO, COD_CONTEXTO_PARAMETRO, DSC_PARAMETRO, DSC_TITULO_PARAMETRO, IND_PARAMETRO_SISTEMA, COD_TIPO_ATRIBUTO, DSC_VALOR_PARAMETRO)
  VALUES (
      SQ_PARAMETRO_01.NEXTVAL, (SELECT COD_CONTEXTO_PARAMETRO FROM CONTEXTO_PARAMETRO WHERE DSC_CONTEXTO_PARAMETRO = 'PARAMETROS DE WEBSERVICE'), 'ALTERAR_CODIGO_BARRAS', 'Permitir alterar código de barras (S/N)', 'N', 'A', 'N');

UPDATE PARAMETRO SET DSC_TITULO_PARAMETRO = 'Envia os dados logisticos dos produtos por WebService - WebPDV (S/N)' WHERE DSC_PARAMETRO = 'CONSOME_WEBSERVICE_PRODUTOS';

UPDATE PARAMETRO SET COD_CONTEXTO_PARAMETRO = (SELECT COD_CONTEXTO_PARAMETRO FROM CONTEXTO_PARAMETRO WHERE DSC_CONTEXTO_PARAMETRO = 'PARAMETROS DE WEBSERVICE')  WHERE DSC_PARAMETRO = 'INTEGRACAO_CODIGO_BARRAS';

DELETE FROM CONTEXTO_PARAMETRO WHERE DSC_CONTEXTO_PARAMETRO = 'CADASTROS';