INSERT INTO ACAO (COD_ACAO, DSC_ACAO, NOM_ACAO) VALUES (SQ_ACAO_01.NEXTVAL, 'Transferência', 'transferir');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO,COD_ACAO,DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL,
  (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO LIKE 'enderecamento:movimentacao'),
  (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO LIKE 'transferir'), 'Transferência de estoque');

INSERT INTO ACAO (COD_ACAO, DSC_ACAO, NOM_ACAO) VALUES (SQ_ACAO_01.NEXTVAL, 'Movimentação', 'movimentar');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO,COD_ACAO,DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL,
  (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO LIKE 'enderecamento:movimentacao'),
  (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO LIKE 'movimentar'), 'Movimentação de estoque');