ALTER TABLE PRODUTO
  ADD PERC_TOLERANCIA FLOAT;
  
 ALTER TABLE PRODUTO
  ADD TOLERANCIA_NOMINAL FLOAT;  
  
 ALTER TABLE PALETE
  ADD PESO FLOAT;  
  
 ALTER TABLE NOTA_FISCAL
  ADD PESO_TOTAL FLOAT;
  
 ALTER TABLE RECEBIMENTO_EMBALAGEM
  ADD NUM_PESO FLOAT;
  
 ALTER TABLE RECEBIMENTO_VOLUME
  ADD NUM_PESO FLOAT;