
INSERT INTO ACAO (COD_ACAO, DSC_ACAO, NOM_ACAO) VALUES (SQ_ACAO_01.NEXTVAL, 'Reimprimir Embalados', 'reimprimir-embalados');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL,(SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO LIKE 'expedicao:etiqueta'),
  (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO LIKE 'reimprimir-embalados'), 'Reimprimir Volumes Embalados');

ALTER TABLE MAPA_SEPARACAO_EMB_CLIENTE
ADD (IND_ULTIMO_VOLUME CHAR(1) DEFAULT 'N');