INSERT INTO VERSAO (DTH, NUMERO_VERSAO, SCRIPT) VALUES (SYSDATE, '4.0.0', 'relatorioMovimentacaoInventario.sql');

INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO)
VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'inventario:index'),
        (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'relatorio'), 'Relatorio de movimentação no estoque pelo inventário');