INSERT INTO VERSAO (DTH, NUMERO_VERSAO, SCRIPT) VALUES (SYSDATE, '6.13.0','14-ajuste-norma.sql');

DECLARE
	idNovaNorma number;
    qtdNormasAntigas number;
BEGIN
    FOR i IN (SELECT PDL.COD_PRODUTO_DADO_LOGISTICO,
					 PDL.COD_NORMA_PALETIZACAO
				FROM PRODUTO_DADO_LOGISTICO PDL
			   WHERE PDL.COD_NORMA_PALETIZACAO IN (
				     SELECT COD_NORMA_PALETIZACAO
					   FROM PRODUTO_DADO_LOGISTICO PE
					  GROUP BY COD_NORMA_PALETIZACAO
					 HAVING COUNT (COD_PRODUTO_EMBALAGEM) > 1))
	LOOP
    BEGIN

		SELECT SQ_NORMA_PALETIZACAO_01.NEXTVAL INTO idNovaNorma FROM PRODUTO_DADO_LOGISTICO WHERE COD_PRODUTO_DADO_LOGISTICO = i.COD_PRODUTO_DADO_LOGISTICO;

        INSERT INTO NORMA_PALETIZACAO (NUM_LASTRO, NUM_CAMADAS, NUM_NORMA, IND_PADRAO, COD_UNITIZADOR, COD_NORMA_PALETIZACAO, NUM_PESO)
        SELECT NP.NUM_LASTRO,
               NP.NUM_CAMADAS,
               NP.NUM_NORMA,
               NP.IND_PADRAO,
               NP.COD_UNITIZADOR,
               idNovaNorma as COD_NORMA_PALETIZACAO,
               NP.NUM_PESO
          FROM NORMA_PALETIZACAO NP
         WHERE COD_NORMA_PALETIZACAO = i.COD_NORMA_PALETIZACAO;

         UPDATE PRODUTO_DADO_LOGISTICO SET COD_NORMA_PALETIZACAO = idNovaNorma WHERE COD_PRODUTO_DADO_LOGISTICO = i.COD_PRODUTO_DADO_LOGISTICO;

         SELECT COUNT(COD_NORMA_PALETIZACAO) INTO qtdNormasAntigas
           FROM (SELECT COD_NORMA_PALETIZACAO FROM PRODUTO_DADO_LOGISTICO
                  UNION
                 SELECT COD_NORMA_PALETIZACAO
                   FROM PRODUTO_VOLUME) N
          WHERE COD_NORMA_PALETIZACAO = i.COD_NORMA_PALETIZACAO;

         IF (qtdNormasAntigas = '0') THEN
            DELETE FROM NORMA_PALETIZACAO WHERE COD_NORMA_PALETIZACAO = i.COD_NORMA_PALETIZACAO;
         END IF;
	END;

	END LOOP;
END;