ALTER TABLE PRODUTO_EMBALAGEM ADD (
    DTH_INATIVACAO TIMESTAMP,
    COD_USUARIO_INATIVACAO NUMBER(8)
);

ALTER TABLE PRODUTO_VOLUME ADD (
    DTH_INATIVACAO TIMESTAMP,
    COD_USUARIO_INATIVACAO NUMBER(8)
);

INSERT INTO CONTEXTO_PARAMETRO (COD_CONTEXTO_PARAMETRO, DSC_CONTEXTO_PARAMETRO) VALUES (24, 'CADASTROS');
INSERT INTO PARAMETRO (COD_PARAMETRO, COD_CONTEXTO_PARAMETRO, DSC_PARAMETRO, DSC_TITULO_PARAMETRO, IND_PARAMETRO_SISTEMA, COD_TIPO_ATRIBUTO, DSC_VALOR_PARAMETRO) VALUES (SQ_PARAMETRO_01.NEXTVAL, (select COD_CONTEXTO_PARAMETRO from CONTEXTO_PARAMETRO WHERE DSC_CONTEXTO_PARAMETRO LIKE 'CADASTROS'), 'INTEGRACAO_CODIGO_BARRAS', 'Utiliza integração de Código de Barras (S/N)', 'N', 'A', 'S');
