ALTER TABLE PRODUTO 
ADD (ID_PRODUTO NUMBER(10) );

CREATE INDEX ID_PRODUTO_IDX01 ON PRODUTO (ID_PRODUTO DESC);

CREATE SEQUENCE SQ_PRODUTO_01
INCREMENT BY 1
START WITH 1
MAXVALUE 999999999999999999999999999
MINVALUE 0
NOCYCLE
NOCACHE
NOORDER
;

UPDATE PRODUTO P SET P.ID_PRODUTO = SQ_PRODUTO_01.NEXTVAL WHERE ID_PRODUTO is null;

CREATE TABLE FORNECEDOR_REFERENCIA
(
  COD_FORN_REF NUMBER(8, 0) NOT NULL
, ID_PRODUTO NUMBER(10, 0)
, COD_FORNECEDOR NUMBER(8, 0)
, DSC_REFERENCIA VARCHAR2(20 BYTE)
, CONSTRAINT FORNECEDOR_REFERENCIA_PK PRIMARY KEY
  (
    COD_FORN_REF
  )
  USING INDEX
  (
      CREATE UNIQUE INDEX FORNECEDOR_REFERENCIA_PK ON FORNECEDOR_REFERENCIA (COD_FORN_REF ASC)
      LOGGING
      TABLESPACE WMS_DEVELOP
      PCTFREE 10
      INITRANS 2
      STORAGE
      (
        INITIAL 524288
        NEXT 524288
        MINEXTENTS 1
        MAXEXTENTS UNLIMITED
        PCTINCREASE 0
        BUFFER_POOL DEFAULT
      )
      NOPARALLEL
  )
  ENABLE
)

ALTER TABLE FORNECEDOR_REFERENCIA
ADD CONSTRAINT COD_FORNECEDOR_PK FOREIGN KEY
(
  COD_FORNECEDOR
)
REFERENCES FORNECEDOR
(
  COD_FORNECEDOR
)
ENABLE;

CREATE SEQUENCE SQ_FORNECEDOR_REF_01
INCREMENT BY 1
START WITH 1
MAXVALUE 999999999999999999999999999
MINVALUE 0
NOCYCLE
NOCACHE
NOORDER
;