<?php
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

echo $this->form;
?>
<div id="estoque" style="text-align: center;"></div>
<script>
    $(window).load(function () {
        $('#ruaFinal').parent().css('clear', 'both');

        $("#buscar").click(function () {
            $.ajax({
                url: URL_MODULO + '/ressuprimento-preventivo/list-ajax/',
                type: 'post',
                dataType: 'html',
                data: $('form').serialize(),
                success: function (data) {
                    $('#estoque').html(data);

                }
            });
            return false;
        });
        $(".limpar-pulmao").click(function () {
            $.wmsDialogAlert({
                title: 'Limpar Pulmão',
                msg: 'Ação de limpar pulmão'
            });
            /*$.ajax({
             url: URL_MODULO + '/ressuprimento-preventivo/list-ajax/',
             type: 'post',
             dataType: 'html',
             data: $('form').serialize(),
             success: function (data) {
             $('#estoque').html(data);
             }
             });*/
            return false;
        });
        $(".completar-picking").click(function () {
            $.ajax({
                url: URL_MODULO + '/ressuprimento-preventivo/picking-ajax/',
                type: 'post',
                dataType: 'html',
                data: $('form').serialize(),
                success: function (data) {
                    $('#estoque').html(data);
                    $('.gControl').prepend('<button id="confirmar" style="width: 220px; margin: 10px;" class="btn">Confirmar Ação</button>');
                }
            });
            return false;
        });
    });
</script>