<?php
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
?>
<table class="gTable list">
    <tbody>
<?php
$codProdutoAnterior = null;
$gradeAnterior = null;
$codVolumeAnterior = null;

$qtdEstoque = 0;
$qtdReservaEntrada = 0;
$qtdReservaSaida = 0;
$count = 0;

foreach ($this->enderecos as $key => $endereco) {
    if (($codProdutoAnterior != $endereco['COD_PRODUTO']) || ($gradeAnterior != $endereco['DSC_GRADE']) || ($codVolumeAnterior != $endereco['COD_VOLUME'])) {

        if ($codProdutoAnterior != NULL) {
            ?><tr >
                        <td colspan="5"><b>Total</b></td>
                        <td><b><?php echo $qtdReservaEntrada ?></b></td>
                        <td><b><?php echo $qtdReservaSaida ?></b></td>
                        <td><b><?php echo $qtdEstoque ?></b></td>
                        <td colspan="2"></td>
                    </tr>
            <?php
        }

        $qtdEstoque = 0;
        $qtdReservaEntrada = 0;
        $qtdReservaSaida = 0;
        ?>

                <tr class ="gTTitle">
                    <td><b><?php echo "CÓDIGO: " . $endereco['COD_PRODUTO'] ?></b></td>
                    <td><b><?php echo "GRADE: " . $endereco['DSC_GRADE'] ?></b></td>
                    <td colspan="3"><b><?php echo "PRODUTO: " . $endereco['DSC_PRODUTO'] ?></b></td>
                    <td colspan="2"><b><?php echo "VOLUME: " . $endereco['VOLUME'] ?></b></td>
                    <td colspan="2">
        <?php if (isset($this->endPicking[$count])) : ?>
                            <b><?php echo "PICKING: " . $this->endPicking[$count]; ?></b>
                        <?php endif; ?>
                    </td>
                </tr>

                <tr class ="gTTitle">
                    <td><b>Endereço</b></td>
                    <td><b>Tipo</b></td>
                    <td><b>Data de Entrada</b></td>
                    <td><b>U.M.A.</b></td>
                    <td><b>Unitizador</b></td>
                    <td><b>Reserva Entrada</b></td>
                    <td><b>Reserva Saida</b></td>
                    <td><b>Qtd.Estoque</b></td>
                    <td><b>Validade</b></td>
                </tr>
        <?php
        $count++;
    }
    ?><tr>
                <td><?php echo $endereco['ENDERECO'] ?></td>
                <td><?php echo $endereco['TIPO'] ?></td>
                <td><?php echo $endereco['DTH_PRIMEIRA_MOVIMENTACAO'] ?></td>
                <td><?php echo $endereco['UMA'] ?></td>
                <td><?php echo $endereco['UNITIZADOR'] ?></td>
                <td><?php echo $endereco['RESERVA_ENTRADA'] ?></td>
                <td><?php echo $endereco['RESERVA_SAIDA'] ?></td>
                <td><?php echo $endereco['QTD_EMBALAGEM'] ?></td>
                <td><?php
        if (isset($endereco['DTH_VALIDADE']) && !empty($endereco['DTH_VALIDADE'])) {
            $dataValidade = new DateTime($endereco['DTH_VALIDADE']);
            $dataValidade = $dataValidade->format('d/m/Y');
            echo $dataValidade;
        } else {
            echo "<p style='text-align: center;'> - </p>";
        }
    ?></td>
            </tr>
                    <?php
                    $qtdEstoque = $qtdEstoque + $endereco['QTD'];
                    $qtdReservaEntrada = $qtdReservaEntrada + $endereco['RESERVA_ENTRADA'];
                    $qtdReservaSaida = $qtdReservaSaida + $endereco['RESERVA_SAIDA'];
                    $codProdutoAnterior = $endereco['COD_PRODUTO'];
                    $gradeAnterior = $endereco['DSC_GRADE'];
                    $codVolumeAnterior = $endereco['COD_VOLUME'];

                    if ($endereco == $this->enderecos[count($this->enderecos) - 1]) {
                        ?><tr>
                    <td colspan="5" style="text-align: center"><b>Total</b></td>
                    <td><b><?php echo $qtdReservaEntrada ?></b></td>
                    <td><b><?php echo $qtdReservaSaida ?></b></td>
                    <td><b><?php echo $qtdEstoque ?></b></td>
                    <td colspan="2"></td>
                </tr><?php
    }
}?>
</table>