<?php
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
echo $this->grid;
?>
<script>
    $('#check-all').click(function () {
        if ($(this).prop("checked")) {
            $('.checkBoxClass').each(function () {
                $(this).attr( 'checked',true );
            });
        }else{
            $('.checkBoxClass').each(function () {
                $(this).removeAttr( 'checked');
            });
        }
    });
</script>