<?php
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
echo $this->grid;
?>
<script>
    $('#check-all').click(function () {
        if ($(this).prop("checked")) {
            $('.checkBoxClass').each(function () {
                $(this).attr('checked', true);
            });
        } else {
            $('.checkBoxClass').each(function () {
                $(this).removeAttr('checked');
            });
        }
    });

    $("#confirmar").click(function () {
        return false;
        $("input:checked").each(function () {
            console.log($(this));
        });
//            $.ajax({
//                url: URL_MODULO + '/ressuprimento-preventivo/list-ajax/',
//                type: 'post',
//                dataType: 'html',
//                data: $('form').serialize(),
//                success: function (data) {
//                    $('#estoque').html(data);
//                }
//            });
        return false;
    });
</script>