<style>
    .gridTitle {
        font-size: 15px;
        font-weight: bold;
        text-align: center;
        text-shadow: #595959;
    }
</style>

<div id="identificacao-form">
    <fieldset id="identificacao">
    <legend>Produtos</legend>
        <div class="gridTitle"> <?php echo $this->element->alert->getValue(); ?> </div>
        <?php echo $this->element->grid->getValue(); ?>
    </fieldset>
</div>