<form id="filtro-produtos-conferidos-form" method="get" class="filtro" action="">
    <div>
        <fieldset id="fieldset-busca">
            <legend>Buscar Recebimento</legend>
            <table style="width:100%">
                <tr>
                    <td>Número do Recebimento:</td>
                    <td>Data Inicio do Recebimento:</td>
                    <td>Data Final do Recebimento:</td>
                    <td rowspan="2"><?php echo "{$this->element->submit}"; ?></td>
                </tr>
                <tr>
                    <td><?php echo "{$this->element->idRecebimento}"; ?></td>
                    <td><?php echo "{$this->element->dataInicial1}"; ?> a <?php echo "{$this->element->dataInicial2}"; ?></td>
                    <td><?php echo "{$this->element->dataFinal1}"; ?> a <?php echo "{$this->element->dataFinal2}"; ?></td>
                </tr>
            </table>
        </fieldset>
    </div>
</form>