INSERT INTO VERSAO (DTH, NUMERO_VERSAO, SCRIPT) VALUES (SYSDATE, '6.4.3','3-trigger-integracao-abrafer.sql');

-------------------------------------------------------------------------------------------
create or replace TRIGGER trg_imperium_produto
 AFTER
  INSERT OR UPDATE
 ON produto
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
declare

begin

merge into WMS_CARAPINA.PRODUTO
           using dual on (WMS_CARAPINA.PRODUTO.cod_produto = :new.cod_produto)
when not matched then
insert (COD_PRODUTO,
 DSC_PRODUTO,
 DSC_GRADE,
 DSC_REFERENCIA,
 COD_TIPO_COMERCIALIZACAO,
 COD_PRODUTO_CLASSE,
 COD_FABRICANTE,
 COD_LINHA_SEPARACAO,
 COD_BARRAS_BASE,
 NUM_VOLUMES,
 DIAS_VIDA_UTIL,
 POSSUI_VALIDADE,
 COD_ENDERECO_REF_END_AUTO,
 PERC_TOLERANCIA,
 TOLERANCIA_NOMINAL,
 ID_PRODUTO,
 IND_POSSUI_PESO_VARIAVEL)

 VALUES
 (:new.cod_produto,
  :new.DSC_PRODUTO,
  :new.DSC_GRADE,
  :new.DSC_REFERENCIA,
  :new.COD_TIPO_COMERCIALIZACAO,
  :new.COD_PRODUTO_CLASSE,
  :new.COD_FABRICANTE,
  :new.COD_LINHA_SEPARACAO,
  :new.COD_BARRAS_BASE,
  :new.NUM_VOLUMES,
  :new.DIAS_VIDA_UTIL,
  :new.POSSUI_VALIDADE,
  :new.COD_ENDERECO_REF_END_AUTO,
  :new.PERC_TOLERANCIA,
  :new.TOLERANCIA_NOMINAL,
  :new.ID_PRODUTO,
  :new.IND_POSSUI_PESO_VARIAVEL)

 when matched then

 update set
 DSC_PRODUTO = :new.DSC_PRODUTO,
 --DSC_GRADE = :new.DSC_GRADE,
 DSC_REFERENCIA = :new.DSC_REFERENCIA,
 COD_TIPO_COMERCIALIZACAO = :new.COD_TIPO_COMERCIALIZACAO,
 COD_PRODUTO_CLASSE = :new.COD_PRODUTO_CLASSE,
 COD_FABRICANTE = :new.COD_FABRICANTE,
 COD_LINHA_SEPARACAO = :new.COD_LINHA_SEPARACAO,
 COD_BARRAS_BASE = :new.COD_BARRAS_BASE,
 NUM_VOLUMES = :new.NUM_VOLUMES,
 DIAS_VIDA_UTIL = :new.DIAS_VIDA_UTIL,
 POSSUI_VALIDADE = :new.POSSUI_VALIDADE,
 COD_ENDERECO_REF_END_AUTO = :new.COD_ENDERECO_REF_END_AUTO,
 PERC_TOLERANCIA = :new.PERC_TOLERANCIA,
 TOLERANCIA_NOMINAL = :new.TOLERANCIA_NOMINAL,
 ID_PRODUTO = :new.ID_PRODUTO,
 IND_POSSUI_PESO_VARIAVEL = :new.IND_POSSUI_PESO_VARIAVEL;

 end;


-------------------------------------------------------------------------------------------

create or replace TRIGGER trg_imperium_produto_andamento
 AFTER
  INSERT OR UPDATE
 ON produto_andamento
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
declare

begin

merge into WMS_CARAPINA.PRODUTO_ANDAMENTO
           using dual on (WMS_CARAPINA.PRODUTO_ANDAMENTO.NUM_SEQUENCIA = :new.NUM_SEQUENCIA)
when not matched then
insert (NUM_SEQUENCIA,
        COD_PRODUTO,
        DSC_GRADE,
        COD_USUARIO,
        DTH_ANDAMENTO,
        DSC_OBSERVACAO)

 VALUES
 (:new.NUM_SEQUENCIA,
  :new.COD_PRODUTO,
  :new.DSC_GRADE,
  :new.COD_USUARIO,
  :new.DTH_ANDAMENTO,
  :new.DSC_OBSERVACAO);

end;

-------------------------------------------------------------------------------------------

create or replace TRIGGER trg_imperium_produto_embalagem
 AFTER
  INSERT OR UPDATE
 ON produto_embalagem
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
declare


begin

merge into  WMS_CARAPINA.PRODUTO_EMBALAGEM
           using dual on (WMS_CARAPINA.PRODUTO_EMBALAGEM.COD_PRODUTO_EMBALAGEM = :new.COD_PRODUTO_EMBALAGEM and
                          WMS_CARAPINA.PRODUTO_EMBALAGEM.COD_PRODUTO = :new.COD_PRODUTO)
when not matched then
insert (COD_PRODUTO_EMBALAGEM,
 DSC_EMBALAGEM,
 QTD_EMBALAGEM,
 IND_PADRAO,
 COD_BARRAS,
 COD_PRODUTO,
 DSC_GRADE,
 IND_CB_INTERNO,
 IND_IMPRIMIR_CB,
 COD_DEPOSITO_ENDERECO,
 IND_EMBALADO,
 PONTO_REPOSICAO,
 CAPACIDADE_PICKING,
 DTH_INATIVACAO,
 COD_USUARIO_INATIVACAO,
 NUM_ALTURA,
 NUM_CUBAGEM,
 NUM_PROFUNDIDADE,
 NUM_LARGURA,
 NUM_PESO)

 VALUES
 (:new.COD_PRODUTO_EMBALAGEM,
 :new.DSC_EMBALAGEM,
 :new.QTD_EMBALAGEM,
 :new.IND_PADRAO,
 :new.COD_BARRAS,
 :new.COD_PRODUTO,
 :new.DSC_GRADE,
 :new.IND_CB_INTERNO,
 :new.IND_IMPRIMIR_CB,
 :new.COD_DEPOSITO_ENDERECO,
 :new.IND_EMBALADO,
 :new.PONTO_REPOSICAO,
 :new.CAPACIDADE_PICKING,
 :new.DTH_INATIVACAO,
 :new.COD_USUARIO_INATIVACAO,
 :new.NUM_ALTURA,
 :new.NUM_CUBAGEM,
 :new.NUM_PROFUNDIDADE,
 :new.NUM_LARGURA,
 :new.NUM_PESO)

 when matched then

 update set
 DSC_EMBALAGEM = :new.DSC_EMBALAGEM,
 QTD_EMBALAGEM = :new.QTD_EMBALAGEM,
 IND_PADRAO = :new.IND_PADRAO,
 COD_BARRAS = :new.COD_BARRAS,
 DSC_GRADE = :new.DSC_GRADE,
 IND_CB_INTERNO = :new.IND_CB_INTERNO,
 IND_IMPRIMIR_CB = :new.IND_IMPRIMIR_CB,
 COD_DEPOSITO_ENDERECO = :new.COD_DEPOSITO_ENDERECO,
 IND_EMBALADO = :new.IND_EMBALADO,
 PONTO_REPOSICAO = :new.PONTO_REPOSICAO,
 CAPACIDADE_PICKING = :new.CAPACIDADE_PICKING,
 DTH_INATIVACAO = :new.DTH_INATIVACAO,
 COD_USUARIO_INATIVACAO = :new.COD_USUARIO_INATIVACAO,
 NUM_ALTURA = :new.NUM_ALTURA,
 NUM_CUBAGEM = :new.NUM_CUBAGEM,
 NUM_PROFUNDIDADE = :new.NUM_PROFUNDIDADE,
 NUM_LARGURA = :new.NUM_LARGURA,
 NUM_PESO = :new.NUM_PESO;
end;