INSERT INTO VERSAO (DTH, NUMERO_VERSAO, SCRIPT) VALUES (SYSDATE, '6.5.0','3-expedicao-pulmao-doca.sql');

ALTER TABLE RESERVA_ESTOQUE_EXPEDICAO ADD (QUEBRA_PULMAO_DOCA CHAR (1));
ALTER TABLE RESERVA_ESTOQUE_EXPEDICAO ADD (COD_CRITERIO_QUEBRA_PD VARCHAR (40));
ALTER TABLE RESERVA_ESTOQUE_EXPEDICAO ADD (TIPO_SAIDA CHAR (1));

UPDATE RESERVA_ESTOQUE_EXPEDICAO SET QUEBRA_PULMAO_DOCA = 'N';

ALTER TABLE ETIQUETA_SEPARACAO ADD (TIPO_SAIDA CHAR(1));