<form id="relatorio-picking-listar" method="post" class="saveForm" action="<?php echo $this->url(array('module' => 'enderecamento', 'controller' =>'relatorio_picking', 'action' =>'list' ))?>">
<div id="quantidade-grid" class="grid">
	<input type="submit" style="margin-bottom: 15px" name="busca" value="Confirmar selecionados" id="submit" class="btn">
    <table class="gTable ">
        <caption>Endereços Selecionados</caption>
        <tbody>
        <tr class ="gTTitle">
			<td></td>
            <td>Endereço</td>
            <td>Código</td>
            <td>Grade</td>
            <td>Produto</td>
            <td>Quantidade</td>
        </tr>
        <?php
        foreach ($this->enderecos as $picking): $this->color = !($this->color);?>
            <tr class = "<?php if (!$this->color) {echo 'gTResultSet gRowColor';} else {echo 'gTResultSet';}?>">
				<td><input name="endereco[]" value="<?php echo $picking['idEndereco'] ?>" type="checkbox" /> </td>
                <td><?php echo $picking['dscEndereco'] ?></td>
                <td><?php echo $picking['codProduto'] ?></td>
                <td><?php echo $picking['grade'] ?></td>
                <td><?php echo $picking['descricao'] ?></td>
				<td><?php echo $picking['qtd'] ?> </td>
				</tr>
        <?php endforeach; ?>
</tbody>
</table>
<div class = "gPager">
</form>
