<script>

    function playSound(soundfile) {
        document.getElementById("dummy").innerHTML=
            "<embed src=\""+soundfile+"\" hidden=\"true\" autostart=\"true\" loop=\"false\" />";
    }

    window.onload=function()
    {
        //playSound('/alarme.mp3')
        var audioElement = document.createElement('audio');
        audioElement.setAttribute('src', '/alarme.mp3');
        audioElement.play();
    };

</script>

<span id="dummy"></span>
<?php echo $this->form; ?>
