
<form enctype="application/x-www-form-urlencoded" accept-charset="UTF-8" action="/mobile/expedicao/ler-produto-mapa/idMapa/<?php echo $this->codigoBarras ?>/idExpedicao/<?php echo $this->idExpedicao ?>" method="post">
    <dt id="identification-label">&nbsp;</dt>
    <input type="hidden" name="idMapa" value="<?php echo $this->codigoBarras; ?>">
    <dd id="identification-element">
        <fieldset id="fieldset-identification">
            <legend>Selecionar Clientes</legend>
            <dl>
                <div class="field"><label for="codigoBarras" class="field required"></label>
                    <?php foreach ($this->clientes as $cliente) :
                        $caixas = null;
                        for ($count = $cliente['NUM_CAIXA_PC_INI']; $count <= $cliente['NUM_CAIXA_PC_FIM']; $count++) :
                            if ($count == $cliente['NUM_CAIXA_PC_FIM']) :
                                $caixas .= $count;
                            else :
                                $caixas .= $count.'; ';
                            endif;
                        endfor; ?>
                        <input type="radio" name="cliente" value="<?php echo $cliente['COD_PESSOA'] ?>"> <?php echo $cliente['NOM_PESSOA']?><b><?php echo' CAIXA(S): '.$caixas ?></b><br>
                    <?php endforeach; ?>
                <input type="submit" name="submit" id="submit" value="Buscar" class="btn">
            </dl>
        </fieldset>
    </dd>
</form>