<h3><?php echo utf8_encode('Recebimentos Pendentes de Endereçamento') ?></h3>
<ul class="menu">
    <?php foreach ($this->clientes as $cliente) : ?>
        <li>
            <a href="<?php echo $this->url(array('module' => 'mobile', 'controller' => 'expedicao', 'action' => 'ler-produto-mapa', 'idMapa' => $this->idMapa, 'idExpedicao' => $this->idExpedicao, 'cliente' => $cliente['COD_PESSOA']),null, true); ?>"
               title="<?php echo $cliente['NOM_PESSOA'] ?>" ><?php echo $cliente['NOM_PESSOA'] ?> - <?php echo ' CAIXA(S): '.$cliente['NUM_CAIXA_PC_INI'] ?></a>
        </li>
    <?php endforeach; ?>
</ul>
<td><a class="finalizar" href="<?php echo '/mobile/expedicao/finalizar/idExpedicao/'. $this->idExpedicao . '/idMapa/' .$this->codigoBarras .'/mapa/S' ?>" >Finalizar</a></td>

