
<form enctype="application/x-www-form-urlencoded" accept-charset="UTF-8" action="/mobile/expedicao/index" method="post">
    <input type="hidden" name="uma" value="" id="uma">
    <dt id="identification-label">&nbsp;</dt>
    <dd id="identification-element">
        <fieldset id="fieldset-identification">
            <legend>Confirma Operação?</legend>
            <dl>
                <label style="font-size: 15px"><?php echo $this->operacao ?></label>
                <label style="font-size: 15px">Expedição: <?php echo $this->expedicao ?></label>
                <?php if (isset($this->carga) && ($this->carga != null)) { ?>
                    <label style="font-size: 15px">Carga: <?php echo $this->carga ?></label>
                <?php } ?>
                <?php if (isset($this->placa) && ($this->placa != null)) { ?>
                    <label style="font-size: 15px">Placa: <?php echo $this->placa ?></label>
                <?php } ?>
                <a class="finalizar" href="<?php echo $this->url ?>" >INICIAR</a>
                <a class="finalizarAmarelo" href="<?php echo $this->url(array('module' => 'mobile', 'controller' => 'expedicao', 'action' => 'carregamento', 'idExpedicao' => $this->expedicao)) ?>" >EQUIPE</a>
            </dl>
        </fieldset>
    </dd>
</form>

