<form id="formGrid" method="post" action="<?php echo $this->url(array('module' => 'mobile', 'controller' => 'expedicao', 'action' => 'carregamento')) ?>">

    <table>
        <tbody>
        <tr>
            <td width=""><span><?php echo utf8_encode('Expedição'); ?></span></td>
        </tr>
        <td><input type="text" name="idExpedicao" id="idExpedicao"></td>
        </tbody>
    </table>
    <button type="submit"><span>Vincular</span></button>
</form>
