<div class="col-xs-12" >
        <form enctype="application/x-www-form-urlencoded" accept-charset="UTF-8" action="/mobile/expedicao/definir-operacao" method="post">
            <input type="hidden" name="uma" value="" id="uma">
            <dt id="identification-label">&nbsp;</dt>
            <dd id="identification-element">
                <fieldset id="fieldset-identification">
                    <legend>Iniciar Expedição</legend>
                    <dl>
                        <div class="field"><label for="codigoBarras" class="field required">*Código de Barras</label>
                            <input type="text" name="codigoBarras" id="codigoBarras" value="" class="form-control required focus" size="40" maxlength="100" style="width: 99%"></div>
                            <input class="btn gradientBtn" type="submit" name="submit" id="submit" value="Buscar" class="btn gradientBtn">
                    </dl>
                </fieldset>
            </dd>
        </form>
    <br>
    <div class="row" >
        <a class="btn gradientBtn" href="/mobile/onda-ressuprimento/listar-ondas" >ONDA DE RESSUPRIMENTO</a>
        <a class="btn gradientBtn" href="/mobile/expedicao/expedicao-carregamento" >EQUIPE DE CARREGAMENTO</a>
        <a class="btn gradientBtn" href="/mobile/expedicao/vincular-Lacre" >VINCULAR LACRE</a>
    </div>
</div>

