
<form enctype="application/x-www-form-urlencoded" accept-charset="UTF-8" action="/mobile/expedicao/confirmar-operacao" method="post">
    <input type="hidden" name="uma" value="" id="uma">
    <dt id="identification-label">&nbsp;</dt>
    <dd id="identification-element">
        <fieldset id="fieldset-identification">
            <legend>Iniciar Expedição</legend>
            <dl>
                <div class="field"><label for="codigoBarras" class="field required">*Código de Barras</label>
                    <input type="text" name="codigoBarras" id="codigoBarras" value="" class=" required focus" size="40" maxlength="100" style="width: 99%"></div>
                <input type="submit" name="submit" id="submit" value="Buscar" class="btn">
            </dl>
        </fieldset>
    </dd>
</form>

<ul style="margin-top: 10px" class="menu">
    <li>
        <a href="/mobile/onda-ressuprimento/listar-ondas" >ONDA DE RESSUPRIMENTO</a>
        <a href="/mobile/expedicao/expedicao-carregamento" >EQUIPE DE CARREGAMENTO</a>
        <a href="/mobile/expedicao/vincular-Lacre" >VINCULAR LACRE</a>
    </li>
</ul>

