
<form enctype="application/x-www-form-urlencoded" accept-charset="UTF-8" action="/mobile/expedicao/informa-qtd-mapa" method="post">
    <dt id="identification-label">&nbsp;</dt>
    <dd id="identification-element">

        <table>
            <tr>
                <td colspan="3">
                    <b><?php echo $this->descricao?></b>
                </td>
            </tr>
            <tr>
                <td colspan="1">
                    <?php echo $this->codProduto?>
                </td>
                <td colspan="1">
                    <?php echo $this->grade?>
                </td>
                <td colspan="1">
                    <?php echo $this->embalagem?>
                </td>
            </tr>
        </table>

        <fieldset id="fieldset-identification">
            <legend>Informe a Quantidade</legend>
            <dl>
                <div class="field">
                    <input type="hidden" name="idVolume" id="idVolume" value="<?php echo $this->idVolume?>">
                    <input type="hidden" name="codBarras" id="codBarras" value="<?php echo $this->codBarras?>">
                    <input type="hidden" name="idEmbVol" id="idEmbVol" value="<?php echo $this->idEmbVol?>">
                    <input type="hidden" name="tipo" id="tipo" value="<?php echo $this->tipo?>">
                    <input type="hidden" name="idMapa" id="idMapa" value="<?php echo $this->idMapa?>">
                    <input type="hidden" name="fator" id="fator" value="<?php echo $this->fator?>">
                    <input type="hidden" name="idExpedicao" id="idExpedicao" value="<?php echo $this->idExpedicao?>">
                    <input type="hidden" name="cliente" id="cliente" value="<?php echo $this->idPessoa ?>">
                <input type="text" name="qtd" id="qtd" value="" class=" required focus" size="40" maxlength="100" style="width: 99%"></div>
                <input type="submit" name="submit" id="submit" value="Conferir" class="btn">
            </dl>
        </fieldset>
    </dd>
</form>
