
<form enctype="application/x-www-form-urlencoded" accept-charset="UTF-8" action="" method="post">
    <dt id="identification-label">&nbsp;</dt>
    <dd id="identification-element">

        <fieldset id="fieldset-identification">
            <legend>Informe o Volume Embalado</legend>
            <dl>
                <div class="field">
                    <input type="text" name="embalado" id="embalado" value="" class="required focus" size="40" maxlength="100" style="width: 99%"></div>
                <input type="submit" name="submit" id="submit" value="Conferir" class="btn">
            </dl>
        </fieldset>
        <a class="finalizar" href="<?php echo $this->url(array('module' => 'mobile', 'controller' => 'expedicao', 'action' => 'ler-codigo-barras', 'idExpedicao' => $this->idExpedicao)); ?>">Alterar para Caixaria</a>
    </dd>

    <td><a class="finalizar" href="<?php echo '/mobile/expedicao/finalizar/idExpedicao/'. $this->idExpedicao  ?>" >Finalizar</a></td>
</form>
<div id="dummy"></div>
<bgsound id="bgSoundId" loop="0" volume="100" />

<script>
    function playSound(soundfile) {
        if (<?php echo $this->isOldBrowserVersion ?> === 'S') {
            document.getElementById("bgSoundId").src = soundfile;
        } else {
            var dummy = '<audio autoplay> <source src=' + soundfile + ' type="audio/mp3">' +
                '<source src="' + soundfile + '" type="audio/mpeg"></audio>';
            $('#dummy').html(dummy);
        }
    }

    <?php if ($this->error == true) : ?>
        var song = "/alarme.mp3";
        playSound(song);
    <?php endif ?>
</script>