
<form enctype="application/x-www-form-urlencoded" accept-charset="UTF-8" action="" method="post">
    <dt id="identification-label">&nbsp;</dt>
    <dd id="identification-element">

        <fieldset id="fieldset-identification">
            <legend>Informe o Volume Embalado</legend>
            <dl>
                <div class="field">
                    <input type="text" name="embalado" id="embalado" value="" class="required focus" size="40" maxlength="100" style="width: 99%"></div>
                <input type="submit" name="submit" id="submit" value="Conferir" class="btn">
            </dl>
        </fieldset>
    </dd>
    <td><a class="finalizar" href="<?php echo '/mobile/expedicao/finalizar/idExpedicao/'. $this->idExpedicao  ?>" >Finalizar</a></td>
</form>
