<script>

    function selecionar() {
        $('#qtd').select();
    }

    function load() {
        qtd = document.getElementById('qtd');
        qtd.style.display = 'none';
        qtdLabel = document.getElementById('label-qtd');
        qtdLabel.style.display = 'none';
    }

    function exibirQtd(event) {
        if (event.which == 13 || event.keyCode == 13) {

            qtd = document.getElementById('qtd');
            qtdLabel = document.getElementById('label-qtd');
            if (qtd) {
                qtd.style.display = 'block';
                qtdLabel.style.display = 'block';
                qtd.focus();
                if(event.preventDefault) {
                    event.preventDefault();
                } else {
                    event.returnValue = false;
                }
            }

            var codBarras = $('#codigoBarras').val();
            dadosProdutos = '';
            $.ajax({
                url: '/mobile/expedicao/consulta-produto/codigoBarras/' + codBarras,
                type: 'get',
                success: function (data) {
                    var codProduto         = data['result']['codProduto'];
                    var grade              = data['result']['grade'];
                    var descricao          = data['result']['descricao'];
                    var quantidade         = data['result']['quantidade'];
                    var descricaoEmbalagem = data['result']['descricaoEmbalagem'];

                    dadosProdutos = '<tr><td colspan="2"><b>Cod Produto: </b>'+codProduto+' - <b>Grade: </b>'+grade+'</td></tr>' +
                        '<tr><td colspan="2"><b>Descrição: </b>'+descricao+'</td></tr>' +
                        '<tr><td colspan="2"><b>Embalagem: </b>'+descricaoEmbalagem+' ('+quantidade+')</td></tr>';
                    $('#dados-produtos').html(dadosProdutos);
                }
            });
        }
        return true;
    }

    function nextInput(event) {
        if (event.which == 13 || event.keyCode == 13) {
            if (document.getElementById('qtd').value != "") {
                codigoBarras = document.getElementById('codigoBarras');
                if (codigoBarras) {
                    codigoBarras.focus();
                    if(event.preventDefault) {
                        event.preventDefault();
                    } else {
                        event.returnValue = false;
                    }
                }
            }
        }
        return true;
    }
</script>

<?php if ($this->exibeQtd == false) : ?>
    <body onLoad="load()"></body>
<?php endif; ?>


<table class="info">
    <caption>Mapa:  <?php echo $this->idMapa ?> </caption>
    <tr>
        <td colspan="2"><b>Produtos a serem conferidos</b></td>
    </tr>

    <tr></tr>
    <tr>
        <td><div id="dados-produtos"></div> </td>
    </tr>

    <?php if(count($this->produtosMapa) > 0) : ?>
        <script type="text/javascript">
            $(document).ready(function(){
                $('#carousel').cycle({
                    fx:   'turnDown',
                    next: '#next',
                    timeout:  0
                });

            });
        </script>

        <tr>
            <td>
                <div id="carousel">
                    <?php foreach ($this->produtosMapa as $produto): ?>
                        <div id="lista-produto<?php echo $produto['COD_PRODUTO'] ?>"><?php echo $produto['COD_PRODUTO'] ?> - <?php echo $produto['DSC_PRODUTO'] ?> - <?php echo $produto['QTD_CONFERIDA'] ?></div>
                    <?php endforeach; ?>
                </div>
            </td>
            <td style="width: 20%"> <button id="next"> >| </button></td>
        </tr>
    <?php endif; ?>

    <?php if(count($this->produtosClientes) > 0) : ?>
        <script type="text/javascript">
            $(document).ready(function(){
                $('#carousel-produtos').cycle({
                    fx:   'turnDown',
                    next: '#next',
                    timeout:  0
                });

            });
        </script>

        <tr>
            <td>
                <div id="carousel-produtos">
                    <?php foreach ($this->produtosClientes as $produto): ?>
                        <div id="lista-produto<?php echo $produto['COD_PRODUTO'] ?>"><?php echo $produto['COD_PRODUTO'] ?> - <?php echo $produto['DSC_PRODUTO'] ?></div>
                    <?php endforeach; ?>
                </div>
            </td>
            <td style="width: 20%"> <button id="next"> >| </button></td>
        </tr>
    <?php endif; ?>



</table>

<form enctype="application/x-www-form-urlencoded" accept-charset="UTF-8" action="/mobile/expedicao/ler-produto-mapa" method="post">
    <input type="hidden" name="uma" value="" id="uma">
    <dt id="identification-label">&nbsp;</dt>
    <dd id="identification-element">
        <fieldset id="fieldset-identification">
            <legend>Ler Código de Barras</legend>
            <dl>
                <div class="field">
                    <input type="hidden" name="idVolume" id="idVolume" value="<?php echo $this->idVolume?>" size="40" maxlength="100" style="width: 99%">
                    <input type="hidden" name="idMapa" id="idMapa" value="<?php echo $this->idMapa?>" size="40" maxlength="100" style="width: 99%">
                    <input type="hidden" name="idExpedicao" id="idExpedicao" value="<?php echo $this->idExpedicao?>" size="40" maxlength="100" style="width: 99%">
                    <input type="hidden" name="cliente" id="cliente" value="<?php echo $this->idPessoa?>" >

                    <table>
                        <tr>
                            <?php if ($this->exibeQtd == true) : ?>
                                <td><label for="qtd" id="label-qtd" class="field required">*Qtd</label></td>
                            <?php endif; ?>
                            <td><label for="codigoBarras" class="field required">*Código de Barras</label></td>
                            <?php if ($this->exibeQtd == false) : ?>
                                <td><label for="qtd" id="label-qtd" class="field required">*Qtd</label></td>
                            <?php endif; ?>
                        </tr>


                        <tr>
                            <?php if ($this->exibeQtd == true) : ?>
                                <td><input type="text" name="qtd" id="qtd" size="7" maxlength="100" value="1" onclick="selecionar()" onkeydown="nextInput(event)" style="width: 80%"></td>
                                <td><input type="text" name="codigoBarras" id="codigoBarras" class="required focus" size="40" maxlength="100" style="width: 99%"></td>
                            <?php else : ?>
                                <td><input type="text" name="codigoBarras" id="codigoBarras" onkeydown="exibirQtd(event)" class="required focus" size="40" maxlength="100" style="width: 99%"></td>
                                <td><input type="text" name="qtd" id="qtd" size="7" maxlength="100" style="width: 80%"></td>
                            <?php endif; ?>
                        </tr>
                    </table>
                </div>
                <input type="submit" name="submit" id="submit" value="Buscar" class="btn">
            </dl>
            <?php if ($this->idVolume != "") :?>
                <legend>Volume: <?php echo $this->dscVolume ?></legend>
                <td><a class="finalizar" href="<?php echo '/mobile/expedicao/fecha-volume-patrimonio-mapa/idMapa/' . $this->idMapa . '/idExpedicao/'. $this->idExpedicao . '/idVolume/' .$this->idVolume ?>" >Fechar</a></td>
            <?php endif; ?>
            <?php if ($this->mapaSeparacaoEmbalado == true) : ?>
                <td><a class="finalizar" href="<?php echo '/mobile/expedicao/fecha-mapa-embalado/idMapa/' . $this->idMapa . '/idExpedicao/'. $this->idExpedicao . '/cliente/' .$this->idPessoa ?>" >Fechar Caixa</a></td>
            <?php endif; ?>

        </fieldset>
    </dd>
    <?php if ($this->mapaSeparacaoEmbalado == false) : ?>
        <td><a class="finalizar" href="<?php echo '/mobile/expedicao/finalizar/idExpedicao/'. $this->idExpedicao . '/idMapa/' .$this->idMapa .'/mapa/S' ?>" >Finalizar</a></td>
        <td><a class="finalizarAmarelo" href="<?php echo '/mobile/expedicao/index/idCentral/'. $this->central ?>" >Alt. Mapa</a></td>
    <?php endif; ?>
</form>