<?php $this->headScript()->appendFile($this->baseUrl('coletor/expedicao.js'));
    $temLote = $this->temLote;
?>
<div id="dummy"></div>
<bgsound id="bgSoundId" loop="0" volume="100" />

<script>

    var codigosDeBarras = [<?php echo implode(", ", $this->arrCodBarras);?>];

    function playSound(soundfile) {
        if (<?php echo $this->isOldBrowserVersion ?> === 'S') {
            document.getElementById("bgSoundId").src = soundfile;
        } else {
            var dummy = '<audio autoplay> <source src=' + soundfile + ' type="audio/mp3">' +
                '<source src="' + soundfile + '" type="audio/mpeg"></audio>';
            $('#dummy').html(dummy);
        }
    }

    function selecionar() {
        $('#qtd').select();
    }

    function exibirQtd(event) {
        if (event.which === 13 || event.keyCode === 13) {
            var codBarras = $('#codigoBarras');

            if (checkCodBarrasMapa(codBarras, event)) {
                var qtd = $("#qtd");
                var qtdLabel = $("#label-qtd");
                if (qtd) {
                    qtd.removeClass("hidden");
                    qtdLabel.removeClass("hidden");
                    qtd.focus();
                    if (event.preventDefault) {
                        event.preventDefault();
                    } else {
                        event.returnValue = false;
                    }
                }

                dadosProdutos = '';
                $.ajax({
                    url: '/mobile/expedicao/consulta-produto/codigoBarras/' + codBarras.val(),
                    type: 'get',
                    success: function (data) {

                        var codProduto = data['result']['codProduto'];
                        var grade = data['result']['grade'];
                        var descricao = data['result']['descricao'];
                        var quantidade = data['result']['quantidade'];
                        var descricaoEmbalagem = data['result']['descricaoEmbalagem'];

                        dadosProdutos =
                            '<table style="border: solid 2px;"class="info">' +
                            '<tr><td colspan="2"><b>Cod Produto: </b>' + codProduto + ' - <b>Grade: </b>' + grade + '</td></tr>' +
                            '<tr><td colspan="2"><b>Descrição: </b>' + descricao + '</td></tr>' +
                            '<tr><td colspan="2"><b>Embalagem: </b>' + descricaoEmbalagem + ' (' + quantidade + ')</td></tr>' +
                            '</table>'
                        ;
                        $('#dados-produtos').html(dadosProdutos);
                    }
                });
            }
        }
        return true;
    }

    function nextInput(event) {

        if (event.which == 13 || event.keyCode == 13) {
            if ($('#qtd').val() !== "") {
                var codigoBarras = $('#codigoBarras');
                if (codigoBarras) {
                    codigoBarras.focus();
                    if (event.preventDefault) {
                        event.preventDefault();
                    } else {
                        event.returnValue = false;
                    }
                }
            }
        }
        return true;
    }

</script>
<table class="info row">
    <caption>Mapa:  <?php echo $this->idMapa ?> </caption>
    <tr>
        <td>
            <div id='erro' style="background-color: #ff0000; font-size: 20px" ></div>
        </td>
    </tr>
    <tr>
        <td>
            <div id='success' style="background-color: lightgreen; font-size: 12px" >
        </td>
    </tr>

    <tr>
        <td colspan="2"><b>Produtos a serem conferidos</b></td>
    </tr>
    <tr>
        <td>
            <div id="produtos-conferir" style="margin-bottom: 10px;">
                <button style="width: 30px;" class="btn gradientBtn"id="next"> > </button>
                <div id="carousel"></div>
            </div>
        </td>
    </tr>

    <tr></tr>
    <tr>
        <td><div id="dados-produtos"></div> </td>
    </tr>

    <tr>
        <td colspan="4"> </td>
    </tr>
</table>

<div id="div-principal">
    <form id="formulario" enctype="application/x-www-form-urlencoded" accept-charset="UTF-8" method="post">
        <input type="hidden" name="uma" value="" id="uma">
        <dt id="identification-label">&nbsp;</dt>
        <dd id="identification-element">

            <fieldset id="fieldset-identification">
                <legend>Ler Código de Barras</legend>
                <dl>
                    <div class="field">
                        <input type="hidden" name="idVolume" id="idVolume" value="<?php echo $this->idVolume ?>" size="40" maxlength="100" style="width: 99%">
                        <input type="hidden" name="idMapa" id="idMapa" value="<?php echo $this->idMapa ?>" size="40" maxlength="100" style="width: 99%">
                        <input type="hidden" name="idExpedicao" id="idExpedicao" value="<?php echo $this->idExpedicao ?>" size="40" maxlength="100" style="width: 99%">
                        <input type="hidden" name="cliente" id="cliente" value="<?php echo $this->idPessoa ?>" >
                        <input type="hidden" name="exibeQtd" id="confereQtd" value="<?php echo $this->confereQtd ?>" >
                        <input type="hidden" name="tipoDefaultEmbalado" id="tipoDefaultEmbalado" value="<?php echo $this->tipoDefaultEmbalado ?>" >
                        <input type="hidden" name="utilizaQuebra" id="utilizaQuebra" value="<?php echo $this->utilizaQuebra ?>" >
                        <input type="hidden" name="utilizaVolumePatrimonio" id="utilizaVolumePatrimonio" value="<?php echo $this->utilizaVolumePatrimonio ?>" >
                        <input type="hidden" name="tipoQuebraVolume" id="tipoQuebraVolume" value="<?php echo $this->tipoQuebraVolume ?>" >
                        <input type="hidden" name="agrupContEtiquetas" id="agrupContEtiquetas" value="<?php echo $this->agrupContEtiquetas ?>" >
                        <input type="hidden" name="usaCaixaPadrao" id="usaCaixaPadrao" value="<?php echo $this->usaCaixaPadrao ?>" >
                        <table>
                            <tr>
                                <?php if ($this->confereQtd) : ?>
                                    <td align="center"><label for="qtd" id="label-qtd" class="field required">*Qtd</label></td>
                                <?php endif; ?>
                                <td align="center"><label for="codigoBarras" class="field required">*Código de Barras</label></td>
                                <?php if (!$this->confereQtd) : ?>
                                    <td align="center"><label for="qtd" id="label-qtd" class="field required hidden">*Qtd</label></td>
                                <?php endif; ?>
                            </tr>
                            <tr>
                                <?php if ($this->confereQtd) : ?>
                                    <td><input name="qtd" id="qtd" size="7" maxlength="100" value="1" onclick="selecionar()" onkeydown="nextInput(event)" style="width: 80%"></td>
                                    <td><input name="codigoBarras" id="codigoBarras" class="required focus"  size="40" <?php if ($temLote) { ?> onkeydown="goToLote(event)" <?php } ?>  maxlength="100" style="width: 99%"></td>
                                <?php else : ?>
                                    <td><input name="codigoBarras" id="codigoBarras" <?php if ($temLote) { ?> onkeydown="goToLote(event)" <?php } else { ?> onkeydown="exibirQtd(event)" <?php } ?> class="required focus" size="40" maxlength="100" style="width: 99%"></td>
                                    <td><input name="qtd" id="qtd" size="7" maxlength="100" style="width: 80%" class="hidden"></td>
                                <?php endif; ?>
                            </tr>
                            <?php if ($temLote) { ?>
                            <tr>
                                <td colspan="2" align="center">
                                    <label for="lote" class="field required">*Lote</label>
                                    <input name="lote" id="lote" class="required"  onkeydown="redirectTo(event)" size="40" maxlength="100" style="width: 99%">
                                </td>
                            </tr>
                            <?php } ?>
                        </table>
                    </div>
                    <br />
                    <input type="submit" name="submit" id="submit" value="Buscar" class="btn">
                </dl>
                <div id="divBtnFechaVolume" <?php echo ($this->idVolume == "")? 'style="display: none"' : '' ?>>
                    <legend>Volume: <span id="spnDscVolume"><?php echo $this->dscVolume ?></span></legend>
                    <td><a id="btnFechaVolume" class="finalizar" href="<?php echo '/mobile/expedicao/fecha-volume-patrimonio-mapa/idMapa/' . $this->idMapa . '/idExpedicao/' . $this->idExpedicao . '/idVolume/var_id_volume' ?>" >Fechar</a></td>
                </div>

                <?php if ($this->separacaoEmbalado) :         ?>
                <td><a class="finalizar" href="<?php echo '/mobile/expedicao/fecha-mapa-embalado/idMapa/' . $this->idMapa . '/idExpedicao/' . $this->idExpedicao . '/cliente/' . $this->idPessoa ?>" >Fechar Volume</a></td>
                <?php endif; ?>

            </fieldset>
        </dd>
        <?php if (!$this->separacaoEmbalado) : ?>
            <td><a class="finalizar" href="<?php echo '/mobile/expedicao/finalizar/idExpedicao/' . $this->idExpedicao . '/idMapa/' . $this->idMapa . '/mapa/S' ?>" >Finalizar</a></td>
            <td><a class="finalizarAmarelo" href="<?php echo '/mobile/expedicao/index/idCentral/' . $this->central ?>" >Alt. Mapa</a></td>
        <?php endif; ?>
    </form>
</div>


<script type="text/javascript">

    <?php if ($temLote) { ?>
    var loteCodigoBarras = <?php echo $this->lotesCodBarras ?>;

    $("#lote").focus(function () {
        verificaCodBarras()
    });

    function goToLote( event ) {
        var result = true;
        if (event.which == 13 || event.keyCode == 13) {
            if (verificaCodBarras()) {
                var codBarras = $("#codigoBarras");
                if (loteCodigoBarras[codBarras.val()] instanceof Array) {
                    var lote = $('#lote');
                    if (lote) {
                        lote.focus();
                        lote.val("");
                    }
                } else {
                    return requestAjax(event, $("#qtd"), codBarras);
                }
            }
            if (event.preventDefault) {
                event.preventDefault();
            } else {
                event.returnValue = false;
            }
        }
        return result;
    }

    function verificaCodBarras () {
        var elem = $('#codigoBarras');
        var result = true;
        if (elem.val() === "") {
            elem.focus();
            alert("Informe primeiro o código de barras do produto");
            result = false;
        } else {
            var check = validaCodBarras(elem.val());
            if (!check) {
                elem.focus();
                elem.val("");
                result = false;
            }
        }
        return result;
    }

    function validaCodBarras(codBarras) {
        if (codBarras in loteCodigoBarras) {
            return true;
        } else {
            alert("Código de barras " + codBarras + " não esperado para este mapa");
            return false;
        }
    }
    
    function checkLoteByCodBarras(codBarras, loteBipado) {
        if (loteBipado !== "") {
            if ($.inArray(loteBipado, loteCodigoBarras[codBarras]) < 0) {
                alert("Lote " + loteBipado + " não esperado para este produto");
                return false;
            } else {
                return true;
            }
        } else {
            alert("Lote não informado!");
            return false;
        }
    }

    function redirectTo(event) {
        if (event.which == 13 || event.keyCode == 13) {
            var codBarras = $("#codigoBarras");
            var lote = $("#lote");
            var qtd = $("#qtd");
            var confereQtd = <?php echo ($this->confereQtd) ? "true" : "false" ?>;

            if (confereQtd) {
                requestAjax(event, qtd, codBarras);
            } else {
                if (verificacao(codBarras, lote)) {
                    exibirQtd(event);
                }
            }
        }
        return false;
    }

    function verificacao (codBarras, lote) {
        var result = true;
        if (validaCodBarras(codBarras.val())) {
            if (loteCodigoBarras[codBarras.val()] instanceof Array) {
                var checkLote = checkLoteByCodBarras(codBarras.val(), lote.val());
                if (!checkLote) {
                    lote.val("").focus();
                }
                result = checkLote;
            }
        } else {
            codBarras.val("").focus();
            result = false;
        }
        return result;
    }
    
    <?php  } ?>

    function checkCodBarrasMapa(codBarrasInput, event) {
        if (event.preventDefault) {
            event.preventDefault();
        } else {
            event.returnValue = false;
        }
        if ($.inArray(codBarrasInput.val(), codigosDeBarras) > -1) return true;
        codBarrasInput.val("").focus();
        alert("Código de barras inválido para esse mapa");
        return false;
    }

    function requestAjax(event, inputQtd, inputCodBarras) {
        <?php if ($temLote) { ?> var lote = $("#lote"); <?php } ?>
        if (checkCodBarrasMapa(inputCodBarras, event))
            if (inputQtd.val() !== '' && inputCodBarras.val() !== "" <?php if ($temLote) { ?> && verificacao(inputCodBarras, lote) <?php } ?>) {
                $.ajax({
                    url: '<?php echo $this->url(array('controller' => 'expedicao', 'action' => 'confere-produto-ajax')) ?>',
                    data: $('form').serialize(),
                    async: false,
                    type: 'post',
                    success: function (data) {
                        if (data.retorno.resposta.length > 0) {
                            var inptIdVolume = $("#idVolume");
                            inputCodBarras.val("").focus();
                            <?php if ($temLote) { ?> lote.val(""); <?php } ?>
                            var error = "";
                            var success = "";
                            var song = "";
                            var volumePatrimonio = "";

                            if (data.retorno.resposta == 'error') {
                                error = data.retorno.message;
                                success = "";
                                song = "/alarme.mp3";
                                volumePatrimonio = data.retorno.volumePatrimonio;
                            } else if (data.retorno.resposta == 'bloqued_os') {
                                error = data.retorno.errorMsg + " " + data.retorno.warningMsg;
                                success = "";
                                song = "/alarme.mp3";
                                volumePatrimonio = '';
                                $("#div-principal").html(data.retorno.blockOsForm);
                            } else {
                                success = data.retorno.message;
                                error = "";
                                song = "/confirm2.mp3";
                                volumePatrimonio = data.retorno.volumePatrimonio;
                            }

                            $("#erro").html(error);
                            $("#success").html(success);

                            if (volumePatrimonio !== '') {
                                inptIdVolume.val(volumePatrimonio.idVolume);
                                $("#spnDscVolume").text(volumePatrimonio.dscVolume);
                                var href = $("#btnFechaVolume").attr("href");
                                $("#btnFechaVolume").attr("href", href.replace('var_id_volume', volumePatrimonio.idVolume));
                            }

                            if (inptIdVolume.val() !== '') {
                                $("#divBtnFechaVolume").show();
                            }

                            try {
                                playSound(song);
                            } catch (e) {
                                alert(message);
                            }


                        }
                        $(".item-lista").remove();
                    }
                });
                $('#dados-produtos').html("");
                var confereQtd = $("#confereQtd").val();
                if (confereQtd === null || confereQtd === '' || confereQtd === false) {
                    inputQtd.addClass("hidden").val("");
                    $("#label-qtd").addClass("hidden");
                } else {
                    inputQtd.val(1);
                }
            } else {
                if (event.preventDefault) {
                    event.preventDefault();
                } else {
                    event.returnValue = false;
                }
            }
        return false;
    }

    $('#submit').on('click', function (ev) {
        return requestAjax(ev, $("#qtd"), $("#codigoBarras"));
    });

    $('#next').click(function (e) {
        if ($(".item-lista").length === 0) {
            $.ajax({
                url: '/mobile/expedicao/get-produtos-conferir',
                type: 'POST',
                async: false,
                data: {
                    idMapa: $('#idMapa').val(),
                    idExpedicao: $('#idExpedicao').val(),
                    cliente: $('#cliente').val()
                },
                success: function (data) {
                    var divCarrousel = $('#carousel');
                    for (var i = 0; i < data.dados.length; i++) {
                        divCarrousel.append('<div class="item-lista" id="lista-produto' + data.dados[i]['COD_PRODUTO'] + '">' + data.dados[i]['COD_PRODUTO'] + ' - ' + data.dados[i]['DSC_PRODUTO'] + ' - ' + data.dados[i]['DSC_GRADE'] + ' - ' + data.dados[i]['QTD_CONFERIDA'] + '</div>');
                    }
                    for (var j = 0; j < data.dadosClientes.length; j++) {
                        divCarrousel.append('<div class="item-lista" id="lista-produto' + data.dadosClientes[j]['COD_PRODUTO'] + '">' + data.dadosClientes[j]['COD_PRODUTO'] + ' - ' + data.dadosClientes[j]['DSC_PRODUTO'] + ' ' + data.dadosClientes[j]['DSC_GRADE'] + '</div>');
                    }
                }
            });
            $('#carousel').cycle({
                fx: 'turnDown',
                timeout: 0
            });
        } else {
            $('#carousel').cycle('next');
        }
        $('.item-lista').each(function () {
            $(this).css('position', 'relative');
            $(this).css('width', '100%');
        });

    });
    $("input").keydown(function (e) {
        if (e.which == 113) {
            var qtd = $('#qtd');
            qtd.focus();
            qtd.select();
            return false;
        }
    });

</script>

