<?php
/**
 * Created by PhpStorm.
 * User: Luis Fernando
 * Date: 25/10/2017
 * Time: 09:12
 */
if($this->mapa == null) {
    ?>
    <h3>Selecione o Mapa</h3>
    <?php
    foreach ($this->mapas as $values) {
        ?>
        <div class="row">
            <a class="btn gradientBtn"
               href="/mobile/expedicao/separacao-ajax/os/1/mapa/<?php echo $values['COD_MAPA_SEPARACAO'] ?>/expedicao/<?php echo $values['COD_EXPEDICAO'] ?>"><?php echo $values['COD_MAPA_SEPARACAO'] ?></a>
        </div>
        <?php
    }
}else{
    ?>
    <div class="row">
        <div id="div-busca">
            <form enctype="application/x-www-form-urlencoded" accept-charset="UTF-8" action="" method="post" id="form-endereco">
                <dt id="identification-label">&nbsp;</dt>
                <dd id="identification-element">
                    <fieldset id="fieldset-identification">
                        <legend>Endereço</legend>
                        <dl>
                            <div class="field" style="text-align: center"><label for="codigoBarras" class="field required">*Código de Barras Endereço</label>
                                <input type="text" name="codigoBarras" id="codigoBarras" value="" class=" required focus" size="40" maxlength="100" style="width: 99%">
                                <input type="hidden" name="codMapa" id="codMapa" value="<?php echo $this->mapa ?>">
                                <input type="hidden" name="idExpedicao" id="idExpedicao" value="<?php echo $this->idExpedicao ?>">
                                <input type="hidden" name="codOs" id="codOs" value="<?php echo $this->codOs ?>">
                                <input class="btn gradientBtn text-center" style="text-align: center" type="submit" name="buscar" id="buscar" value="Buscar" class="btn gradientBtn">
                            </div>
                        </dl>
                    </fieldset>
                </dd>
            </form>
            <br>
        </div>
        <table class="gTable  table-condensed row">
            <tbody>
            <?php
            $style = "background: #fcbbbb;";
            foreach ($this->enderecos as $values){
                ?>
                <tr>
                    <td style="<?php echo $style ?>">
                        <b><?php echo $values['DSC_DEPOSITO_ENDERECO'] ?></b>
                    </td>
                </tr>
                <?php
                $style = "";
            }
            ?>
            </tbody>
        </table>
    </div>
    <?php
}
?>
<script>

    $( "#form-endereco" ).submit(function( event ) {
        $.ajax({
            url: '/mobile/expedicao/get-produtos-end-ajax',
            type: 'post',
            dataType: 'html',
            async: false,
            data: $('form').serialize(),
            success: function (data) {
                $('body').html(data);
            }
        });
        event.preventDefault();
        return false;

    });
</script>
