<?php
/**
 * Created by PhpStorm.
 * User: Luis Fernando
 * Date: 25/10/2017
 * Time: 09:12
 */
if($this->mapa == null) {
    ?>
    <!--    <h3>Selecione o Mapa</h3>-->
    <div id="div-busca">
        <form enctype="application/x-www-form-urlencoded" accept-charset="UTF-8" action="" method="post" id="form-mapa">
            <dt id="identification-label">&nbsp;</dt>
            <dd id="identification-element">
                <fieldset id="fieldset-identification">
                    <legend>Mapa</legend>
                    <?php if ($this->pedido != null) {?>
                        <div class="field" style="text-align: center">
                            <label for="codigoBarras" class="field required">Mapas do Pedido: <?php echo $this->pedido ?></label>
                            <input type="hidden" name="codigoBarras" id="codigoBarras" value="">
                            <input class="btn gradientBtn text-center" codigoBarras="margin-top: 10px; text-align: center" type="submit" name="buscar" id="buscar" value="Voltar" class="btn gradientBtn">
                        </div>
                    <?php } else {?>
                    <dl>
                        <div class="field" style="text-align: center">
                            <label for="codigoBarras" class="field required">Mapa de Separação/Pedido</label>
                            <input type="hidden" name="codMapa" id="codMapa" value="<?php echo $this->mapa ?>">
                            <input type="hidden" name="idExpedicao" id="idExpedicao" value="<?php echo $this->idExpedicao ?>">
                            <input type="hidden" name="codOs" id="codOs" value="<?php echo $this->codOs ?>">
                            <input type="text" name="codigoBarras" id="codigoBarras" value="" class=" required focus" size="40" maxlength="100" style="width: 99%">
                            <input class="btn gradientBtn text-center" style="margin-top: 10px; text-align: center" type="submit" name="buscar" id="buscar" value="Buscar" class="btn gradientBtn">
                        </div>
                    </dl>
                    <?php }?>
                </fieldset>
            </dd>
        </form>
        <br>
    </div>
    <?php
    if (count($this->mapas) == 0) {
        echo "Nenhum mapa encontrado";
    }
    foreach ($this->mapas as $values) {
        ?>
        <div class="row">
            <a class="btn gradientBtn"
               href="/mobile/expedicao/separacao-ajax/mapa/<?php echo $values['COD_MAPA_SEPARACAO'] ?>/expedicao/<?php echo $values['COD_EXPEDICAO'] ?>"><?php echo $values['COD_MAPA_SEPARACAO'] ?></a>
            <input type="hidden" name="<?php echo $values['COD_MAPA_SEPARACAO'] ?>" id="<?php echo $values['COD_MAPA_SEPARACAO'] ?>" value="<?php echo $values['COD_EXPEDICAO'] ?>">
        </div>
        <?php
    }
}else{
    ?>
    <div class="row">
        <div id="div-busca">
            <form enctype="application/x-www-form-urlencoded" accept-charset="UTF-8" action="" method="post" id="form-endereco">
                <dt id="identification-label">&nbsp;</dt>
                <dd id="identification-element">
                    <fieldset id="fieldset-identification">
                        <legend>Endereço</legend>
                        <dl>
                            <div class="field" style="text-align: center"><label for="codigoBarras" class="field required">*Código de Barras Endereço</label>
                                <input type="text" name="codigoBarras" id="codigoBarras" value="" class=" required focus" size="40" maxlength="100" style="width: 99%">
                                <input type="hidden" name="codMapa" id="codMapa" value="<?php echo $this->mapa ?>">
                                <input type="hidden" name="idExpedicao" id="idExpedicao" value="<?php echo $this->idExpedicao ?>">
                                <input type="hidden" name="codOs" id="codOs" value="<?php echo $this->codOs ?>">
                                <input class="btn gradientBtn text-center" style="margin-top: 10px; text-align: center" type="submit" name="buscar" id="buscar" value="Buscar" class="btn gradientBtn">
                            </div>
                        </dl>
                    </fieldset>
                </dd>
            </form>
            <br>
        </div>
        <table class="gTable  table-condensed row">
            <tbody>
            <?php
            $style = "background: #fcbbbb;";
            foreach ($this->enderecos as $values){
                ?>
                <tr>
                    <td style="<?php echo $style ?>">
                        <b><?php echo $values['DSC_DEPOSITO_ENDERECO'] ?></b>
                    </td>
                </tr>
                <?php
                $style = "";
            }
            ?>
            </tbody>
        </table>
        <div id="footer">
            <a style="cursor: pointer" class="btn button finalizar mudar" id="fim-end">Finalizar Separação</a>
        </div>
    </div>
    <?php
}
?>
<script>
    $( "#fim-end" ).click(function( event ) {
        $.ajax({
            url: '/mobile/expedicao/finaliza-mapa-ajax',
            type: 'post',
            dataType: 'html',
            async: false,
            data: $('#form-endereco').serialize(),
            success: function (data) {
                alert("Separação finalizada com sucesso");
                window.location = "/mobile/expedicao/separacao-ajax";
                event.preventDefault();
            }
        });
    });

    $( "#form-mapa" ).submit(function( event ) {

        var inputVlr = $('#codigoBarras').val();
        var codMapa = inputVlr.slice(0,-1);
        var expedicao = $('#'+codMapa).val();

        if (expedicao != null) {
            //var prefixo = str.substring(0,2);
            //if(prefixo == 12){
                window.location = "/mobile/expedicao/separacao-ajax/mapa/"+codMapa+"/expedicao/"+expedicao;
            //}
        } else {
            window.location = "/mobile/expedicao/separacao-ajax/pedido/"+inputVlr;
        }

        event.preventDefault();
        return false;

    });

    $( "#form-endereco" ).submit(function( event ) {
        $.ajax({
            url: '/mobile/expedicao/get-produtos-end-ajax',
            type: 'post',
            dataType: 'html',
            async: false,
            data: $('form').serialize(),
            success: function (data) {
                $('body').html(data);
            }
        });
        event.preventDefault();
        return false;

    });
</script>
