INSERT INTO VERSAO (DTH, NUMERO_VERSAO, SCRIPT) VALUES (SYSDATE, '6.20.6','3-finalizacaoRessuprimentoDesktop.sql');

INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO)VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'expedicao:onda-ressuprimento'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'finalizar'), 'Efetivar onda de ressuprimento pelo desktop');

INSERT INTO SIGLA (COD_SIGLA, COD_TIPO_SIGLA, DSC_SIGLA, COD_REFERENCIA_SIGLA) VALUES (626, (SELECT COD_TIPO_SIGLA FROM TIPO_SIGLA WHERE DSC_TIPO_SIGLA = 'STATUS ANDAMENTO RESSUPRIMENTO'), 'GERADO', 'G');

INSERT INTO SIGLA (COD_SIGLA, COD_TIPO_SIGLA, DSC_SIGLA, COD_REFERENCIA_SIGLA) VALUES (627, (SELECT COD_TIPO_SIGLA FROM TIPO_SIGLA WHERE DSC_TIPO_SIGLA = 'STATUS ANDAMENTO RESSUPRIMENTO'), 'FINALIZADO', 'F');

ALTER TABLE ONDA_RESSUPRIMENTO_OS ADD  (IND_TIPO_FINALIZACAO VARCHAR2 (128 BYTE));

ALTER TABLE RESSUPRIMENTO_ANDAMENTO MODIFY (DSC_OBSERVACAO VARCHAR2 (128 BYTE));