ALTER TABLE FORNECEDOR_REFERENCIA ADD COD_PRODUTO_EMBALAGEM NUMBER(8,0);

ALTER TABLE FORNECEDOR_REFERENCIA
ADD CONSTRAINT COD_PROD_EMB_PK FOREIGN KEY
  (
    COD_PRODUTO_EMBALAGEM
  )
REFERENCES PRODUTO_EMBALAGEM
  (
    COD_PRODUTO_EMBALAGEM
  )
ENABLE;