  CREATE TABLE VERSAO
(
  DTH TIMESTAMP NOT NULL
, NUMERO_VERSAO VARCHAR2(20) NOT NULL
, SCRIPT VARCHAR2(100) NOT NULL
, CONSTRAINT VERSAO_PK PRIMARY KEY
  (
    DTH
  )
  ENABLE
);

ALTER TABLE RELATORIO_PICKING
ADD (
COD_PRODUTO NUMBER (8) NULL,
DTH_COLETA DATE NULL,
COD_OS NUMBER (8) NULL
);