<fieldset id="fieldset-busca">
    <table>
	<tr height="50">
	    <td width="120">Perfil&nbsp;de&nbsp;Usuário:</td>
	    <td width="350"><?php echo "{$this->element->perfis}"; ?></td>
	    
	    <td width="80">Depósito:</td>
	    <td width="350"><?php echo "{$this->element->depositos}"; ?></td>
            
	    <td width="80">Ativo:</td>
	    <td width="350"><?php echo "{$this->element->isAtivo}"; ?></td>
            
	    <td><input type="submit" class="btn" id="submit" value="Buscar" name="busca"/></td>
	</tr>
    </table>
</fieldset>