<div class="row">
    ﻿<form id="formulario" enctype="application/x-www-form-urlencoded" accept-charset="UTF-8" method="post">

        <div id="descricao"></div>
        <div>
            <label>Endereco:</label>
            <input class="focus" type="text" name="codigoBarras" id="codigoBarras"/>
        </div>
        <br>
        <div class="row">
            <input class="btn gradientBtn" type="submit" name="submit" id="submit" value="Buscar" />
        </div>
    </form>
    <br>
    <div id="lista-endereco"></div>
</div>
<script>
    $(function () {

        $('#formulario').submit(function (e) {
            e.preventDefault();
            consultar();
        });

        $('#codigoBarras').keypress(function (e) {
            if (e.which == 13 || e.keyCode == 13) {
                consultar();
            }
        });

        function consultar() {
            var codBarras = $('#codigoBarras');
            var val = codBarras.val();
            if (val != '') {
                $.ajax({
                    url: '/mobile/consulta-endereco/index/codigoBarras/' + val,
                    success: function (data) {
                        if (data.status === 'ok') {
                            var txt = '___________________________________<br>';
                            $.each(data.result, function (key, value) {
                                txt += value.produto + ' - ';
                                txt += value.desc + ' ( ' + value.grade + ' ) - ' + value.qtd + '<br> ';
                                if (value.dataValidade !== null && value.dataValidade !== undefined) {
                                    txt += value.dataValidade + '<br>';
                                }
                                txt += '___________________________________<br>';
                                $('#lista-endereco').html(txt);
                            });
                        } else {
                            showErro(data.msg)
                        }
                        codBarras.val('').focus();
                    }
                });
            } else {
                showErro("Informe um endereço");
            }
        }

        function showErro(msg) {
            $('#lista-endereco').text(msg)
        }
    });
</script>