<script>
    $(document).ready(function(){

        $('#codigoBarras').change(function () {
            var codBarras = $('#codigoBarras').val();
            var produto = '';
            $.ajax({
                url:  '/mobile/consulta-endereco/index/codigoBarras/'+codBarras,
                success: function(data) {
                    for (var x = 0; x < data['produtos'].length; x++) {
                        produto += data['produtos'][x]['COD_PRODUTO']+'-'+data['produtos'][x]['DSC_PRODUTO']+'</br>';
                    }
                    $('#lista-endereco').html(produto);
                    $('#codigoBarras').val('');
                }
            });
        });
    });

    function nextInput(event) {
        if (event.which == 13 || event.keyCode == 13) {
            if (document.getElementById('codigoBarras').value != "") {
                submit = document.getElementById('submit');
                if (submit) {
                    submit.focus();
                    if (event.preventDefault) {
                        event.preventDefault();
                    } else {
                        event.returnValue = false;
                    }
                }
            }
        }
    }
</script>


<form id="formulario" enctype="application/x-www-form-urlencoded" accept-charset="UTF-8" method="post">

    <div id="descricao"></div>
    <div>
        <label>Endereco:</label>
        <input class="focus" type="text" name="codigoBarras" id="codigoBarras" onkeydown="nextInput(event)" />
    </div>

    <div id="lista-endereco"></div>

    <input type="submit" name="submit" id="submit" value="Buscar" />
</form>
