<script>
    $(document).ready(function(){
        $('#todos').live('click',function(){
            var checked_status = this.checked;
            $("input").each(function()
            {
                this.checked = checked_status;
            });
        });

        $('.btn').click(function () {

            $.ajax({
                url: URL_MODULO + '/' + $('#controller').val() + '/' + $('#action').val() + '/id/' + $('#expedicao').val() + '/central/' + $(this).attr('id'),
                type: 'POST',
                data: {
                    cargas: $('input[type="checkbox"]:checked').val()
                },
                success: function(data){
                    location.href = 'expedicao/';
//                    if (data.result) {
//                        if (data.result != true) {
//                            alert(data.result);
//                        }
//                        if (data.redirect) {
//                            location.href = '/produtividade/carregamento/index/id/'.concat(564);
//                        } else {
//                            location.href = window.location.href;
//                        }
//                    }
                }
            });

        });


    });
</script>

<h2>Expedição: <?php echo $this->expedicao ?></h2>
<div class="padding-top">

    <?php if ($this->cargas) : ?>
        <p><b>Selecione as cargas</b> - <input style="vertical-align: middle" type="checkbox" id="todos"> Selecione Todas<br></p>

        <div id="cargas">
            <?php foreach($this->cargas as $carga) : ?>
                <input
                       class="checkBoxClass"
                       style="vertical-align: middle"
                       type="checkbox"
                       name="cargas[]"
                       value="<?php echo $carga['codCargaExterno']?>"
                       >
                Carga <?php echo $carga['codCargaExterno']?>
            <?php endforeach ?>
        </div>
    <?php endif; ?>

    <br><p><b>Selecione a central de entregas</b></p>
    <ul id="centrais">
        <input type="hidden" id="controller" value="<?php echo $this->controller; ?>">
        <input type="hidden" id="action" value="<?php echo $this->action; ?>">
        <input type="hidden" id="expedicao" value="<?php echo $this->expedicao ?>">
        <?php foreach($this->centraisEntrega as $central) : ?>
            <li>
                <input type="button" class="btn" id="<?php echo $central['centralEntrega'] ?>" value="Central <?php echo $central['centralEntrega'] ?>" name="central-<?php echo $central['centralEntrega'] ?>">
            </li>
        <?php endforeach; ?>
    </ul>
</div>