<h2 style="text-align: center;
    margin: 5px;
    margin-bottom: 0px;
    font-size: 14px;">
    Expedição: <?php echo $this->expedicao ?>
</h2>
<div class="padding-top">
    <?php if ($this->cargas) : ?>
        <fieldset id="fieldset-identification" rowspan="2">
            <legend>Selecione as cargas</legend>
            <div class="field" style="padding: 12px;">
                <b><label><input style="vertical-align: middle" type="checkbox" id="todos"> Selecione Todas</label></b>
            </div>
            <div id="cargas"><b>
                    <?php foreach($this->cargas as $carga) : ?>
                        <div class="field" style="padding: 12px;">
                            <label>
                                <input
                                        class="checkBoxClass"
                                        style="vertical-align: middle"
                                        type="checkbox"
                                        name="cargas"
                                        value="<?php echo $carga['codCargaExterno']?>"
                                >
                                Carga <?php echo $carga['codCargaExterno']?>
                            </label>
                        </div>
                    <?php endforeach ?>
                </b>
            </div>
        </fieldset>
    <?php endif; ?>
    <fieldset id="fieldset-identification" rowspan="2">
        <legend>Selecione a central de entregas</legend>
        <div id="centrais"><b>
                <input type="hidden" id="controller" value="<?php echo $this->controller; ?>">
                <input type="hidden" id="action" value="<?php echo $this->action; ?>">
                <input type="hidden" id="expedicao" value="<?php echo $this->expedicao ?>">
                <?php foreach($this->centraisEntrega as $central) : ?>
                <div class="field" style="padding: 12px;">
                        <input type="button" class="btn" id="<?php echo $central['centralEntrega'] ?>" value="Central <?php echo $central['centralEntrega'] ?>" name="central-<?php echo $central['centralEntrega'] ?>">
                </div>
                <?php endforeach; ?>
            </b>
        </div>
    </fieldset>

</div>

<script>
    $(function(){

        $('#todos').click(function () {
            var checked_status = this.checked;
            $(".checkBoxClass").each(function() {
                this.checked = checked_status;
            });
        });

        $('.btn').click(function (a) {
            var arr = [];
            for (var i = 0; i < $('input[name="cargas"]:checked').length; i++) {
                arr[i] = $('input[name="cargas"]:checked')[i].value;
            }
//            if (arr.length == 0){
//                alert("Selecione uma carga!");
//                return false;
//            }
            $.ajax({
                url: URL_MODULO + '/' + $('#controller').val() + '/' + $('#action').val() + '/id/' + $('#expedicao').val() + '/central/' + $(this).attr('id'),
                type: 'POST',
                data: { cargas: arr },
                success: function(data){
                    if (data.status === 'error') {
                        if (data.link === ''){
                            $.wmsDialogAlert({
                                title: 'Falha no procedimento',
                                msg: data.msg
                            });
                        } else {
                            if(confirm(data.msg)){
                                window.open(data.link,'_blank')
                            }
                        }
                        return
                    }
                    a.preventDefault();
                    $.wmsDialogAjax({
                        width: 750,
                        height: 450,
                        url: '/expedicao/etiqueta/listar-mapas-quebra-ajax/id/'+$('#expedicao').val(),
                        title: 'Mapas Pendentes de Impressão'
                    });
                }
            });
        });
    });
</script>