<h2 style="text-align: center;
    margin: 5px;
    margin-bottom: 0px;
    font-size: 14px;">
    Expedição: <?php echo $this->expedicao ?>
</h2>
<div class="padding-top">
    <?php if ($this->cargas) : ?>
        <fieldset id="fieldset-identification" rowspan="2">
            <legend>Selecione as cargas</legend>
            <div class="field" style="padding: 12px;">
                <b><label><input style="vertical-align: middle" type="checkbox" id="todos"> Selecione Todas</label></b>
            </div>
            <div id="cargas">
                <b>
                    <?php foreach($this->cargas as $carga) : ?>
                        <div class="field" style="padding: 12px;">
                            <label>
                                <input
                                        class="checkBoxClass"
                                        style="vertical-align: middle"
                                        type="checkbox"
                                        name="cargas"
                                        value="<?php echo $carga['codCargaExterno']?>"
                                >
                                Carga <?php echo $carga['codCargaExterno']?>
                            </label>
                        </div>
                    <?php endforeach ?>
                </b>
            </div>
        </fieldset>
    <?php endif; ?>
    <?php foreach($this->centraisEntrega as $central) : ?>
        <fieldset id="fieldset-identification">
            <legend>Central <?php echo $central['centralEntrega'] ?></legend>
            <div id="centrais">
                <b>
                    <input type="button" class="btn selectCentral" data-id="<?php echo $central['centralEntrega'] ?>" id="central-<?php echo $central['centralEntrega'] ?>" value="Selecionar Mapa/Etiqueta" name="central-<?php echo $central['centralEntrega'] ?>">
                    <input type="button" class="btn printAll" data-id="<?php echo $central['centralEntrega'] ?>" id="printAll-<?php echo $central['centralEntrega'] ?>" value="Imprimir tudo" name="printAll-<?php echo $central['centralEntrega'] ?>">
                    <input type="button" class="btn printConf" data-id="<?php echo $central['centralEntrega'] ?>" id="printConf-<?php echo $central['centralEntrega'] ?>" value="Imprimir Mapas Conferência" name="printConf-<?php echo $central['centralEntrega'] ?>">
                </b>
            </div>
        </fieldset>
    <?php endforeach; ?>
</div>

<script>
    $(function(){

        $('#todos').click(function () {
            var checked_status = this.checked;
            $(".checkBoxClass").each(function() {
                this.checked = checked_status;
            });
        });

        $('.selectCentral').click(function (a) {
            executeCommand("userSelect");
        });

        function executeCommand(option) {
            var arr = [];
            for (var i = 0; i < $('input[name="cargas"]:checked').length; i++) {
                arr[i] = $('input[name="cargas"]:checked')[i].value;
            }
            $.ajax({
                url: URL_MODULO + '/etiqueta/imprimir/id/<?php echo $this->expedicao ?>/central/' + $(this).attr('data-id'),
                type: 'POST',
                data: { cargas: arr },
                success: function(data){
                    if (data.status === 'error') {
                        if (data.link === ''){
                            $.wmsDialogAlert({
                                title: 'Falha no procedimento',
                                msg: data.msg
                            });
                        } else {
                            if(confirm(data.msg)){
                                window.open(data.link,'_blank')
                            }
                        }
                        return
                    }
                    a.preventDefault();
                    if (option === '"userSelect') {
                        $.wmsDialogAjax({
                            width: 750,
                            height: 450,
                            url: '/expedicao/etiqueta/listar-mapas-quebra-ajax/id/<?php echo $this->expedicao ?>',
                            title: 'Mapas/Etiquetas Pendentes de Impressão'
                        });
                    } else {
                        window.open('/expedicao/etiqueta/gerar-pdf-ajax/tipo/mapa/idMapa/'+arr, '_blank');
                        window.open('/expedicao/etiqueta/gerar-pdf-ajax/tipo/etiqueta/idEtiqueta/'+arr, '_blank');
                        window.open('/expedicao/etiqueta/gerar-pdf-ajax/tipo/mapa/conf/1/idMapa/'+arr, '_blank');
                        window.open('/expedicao/etiqueta/gerar-pdf-ajax/idExpedicao/<?php echo $this->idExpedicao; ?>/tipo/reentrega/todas/N/', '_blank');
                    }
                }
            });
        }
    });
</script>