<?php $idBox = $this->box; ?>
<script>
    $(document).ready(function(){
        $('#seleciona-todos-mapas').live('click',function(){
            var checked_status = this.checked;
            $('input[name="mapas"]').each(function()
            {
                this.checked = checked_status;
            });
        });

        $('#seleciona-todas-etiquetas').live('click',function(){
            var checked_status = this.checked;
            $('input[name="etiquetas"]').each(function()
            {
                this.checked = checked_status;
            });
        });

        $('.imprimir-etiquetas').click(function (a) {
            var arr = [];
            for (var i = 0; i < $('input[name="etiquetas"]:checked').length; i++) {
                arr[i] = $('input[name="etiquetas"]:checked')[i].value;
            }

            window.open('/expedicao/etiqueta/gerar-pdf-ajax/tipo/etiqueta/idEtiqueta/'+arr+'/box/'+String('<?php echo $idBox ?>'), '_blank');
        });

        $('.imprimir-mapa').click(function (a) {
            var arr = [];
            for (var i = 0; i < $('input[name="mapas"]:checked').length; i++) {
                arr[i] = $('input[name="mapas"]:checked')[i].value;
            }
            if(arr.length == 0){
                $.wmsDialogAlert({
                    title: 'Erro',
                    msg: 'Selecione pelo menos um mapa.'
                });
            }else{
                window.open('/expedicao/etiqueta/gerar-pdf-ajax/tipo/mapa/idMapa/'+arr+'/box/'+String('<?php echo $idBox ?>'), '_blank');
            }

        });

        $('#imprimir-mapa-conf').click(function (a) {
            var arr = [];
            for (var i = 0; i < $('input[name="mapas"]:checked').length; i++) {
                arr[i] = $('input[name="mapas"]:checked')[i].value;
            }
            if(arr.length == 0){
                $.wmsDialogAlert({
                    title: 'Erro',
                    msg: 'Selecione pelo menos um mapa.'
                });
            }else{
                window.open('/expedicao/etiqueta/gerar-pdf-ajax/tipo/mapa/conf/1/idMapa/'+arr, '_blank');
            }
        });
    });
</script>

<div class="padding-top">
    <?php if ($this->mapasSeparacao) : ?>
        <fieldset id="fieldset-identification" rowspan="2">
            <legend>Selecione o Mapa para Impressão</legend>
            <div id="mapas"><b>
                <div class="field" style="padding: 12px;">
                    <label><input style="vertical-align: middle" type="checkbox" id="seleciona-todos-mapas"> Selecionar Todos</label>
                </div>
                <?php foreach($this->mapasSeparacao as $mapaSeparacao) : ?>
                    <div class="field" style="padding: 12px;">
                        <label>
                            <input
                                    class="checkBoxClass"
                                    style="vertical-align: middle"
                                    type="checkbox"
                                    name="mapas"
                                    value="<?php echo $mapaSeparacao->getId(); ?>"
                            >
                            Mapa <?php echo $mapaSeparacao->getId().' - '.$mapaSeparacao->getDscQuebra(); ?>
                        </label>
                    </div>
                <?php endforeach ?>
                </b>
            </div>
            <input type="button" class="btn imprimir-mapa" id="imprimir-mapa" value="Imprimir Mapa" name="imprimir-mapa">
            <input type="button" class="btn" id="imprimir-mapa-conf" value="Imprimir Mapa Conferência" name="imprimir-mapa-conf">
        </fieldset>
    <?php endif; ?>
</div>


<div class="padding-top">
    <?php if ($this->etiquetasSeparacao) : ?>
        <p><b>Selecione Etiquetas para Impressão</b>

        <p><b>Selecione Todos</b> - <input style="vertical-align: middle" type="checkbox" id="seleciona-todas-etiquetas"> Selecione Todos<br></p>

        <div id="etiquetas">
            <?php foreach($this->etiquetasSeparacao as $etiquetaSeparacao) : ?>
                <label>
                <input
                    class="checkBoxClass"
                    style="vertical-align: middle"
                    type="checkbox"
                    name="etiquetas"
                    value="<?php echo $etiquetaSeparacao['id']; ?>"
                    >
                Etiqueta <?php echo $etiquetaSeparacao['id'].' - '.$etiquetaSeparacao['dscQuebra'] ?>
                </label>
            <?php endforeach ?>
        </div>
        <input type="button" class="btn imprimir-etiquetas" id="imprimir-etiqueta" value="Imprimir Etiquetas" name="imprimir-etiquetas">
    <?php endif; ?>
</div>

<div class="padding-top">
    <?php if ($this->reentrega =='S') : ?>
        <a class="btn" href="/expedicao/etiqueta/gerar-pdf-ajax/idExpedicao/<?php echo $this->idExpedicao; ?>/tipo/reentrega/todas/N/">Etiquetas de Reentrega</a>
    <?php endif; ?>
</div>

