<script>
    function nextInput(event) {
        if (event.which == 13 || event.keyCode == 13) {
            if (document.getElementById('codBarra').value != "") {
                motivo   = document.getElementById('motivo');
                if (motivo) {
                    motivo.focus();
                    if(event.preventDefault) {
                        event.preventDefault();
                    } else {
                        event.returnValue = false;
                    }
                }
            }
        }
        return true;
    }

    function checkEtiqueta(event) {
        if (event.which == 13 || event.keyCode == 13) {
            var codBarras = document.getElementById('codBarra').value;
            if (codBarras != "") {

                codBarras = codBarras.trim();
                codBarras = codBarras.substring(0,codBarras.length -1);
                codBarras = codBarras.replace(/^(0+)(\d)/g,"$2");

                var aChk = document.getElementsByName('etiqueta[]');
                var count = aChk.length;
                var encontrou = "N";

                for (var i=0; i<count ;i++){
                    if (aChk[i].value == codBarras) {
                        aChk[i].checked = true;
                        document.getElementById('codBarra').value = "";
                        encontrou = "S";
                    }
                }

                if (encontrou == "N") {
                    alert("Nenhuma etiqueta com o cód. barras " + codBarras + " nesta expedição para reimprimir " );
                }

            }

            if(event.preventDefault) {
                event.preventDefault();
            } else {
                event.returnValue = false;
            }
        }
        return true;
    }

    function check(event) {

        if($('#check-all').prop('checked')) {
            $( ".checkBoxClass" ).prop( "checked", true );
        } else {
            $( ".checkBoxClass" ).prop( "checked", false );
        }

    }


</script>
<form id="" method="post" class="saveForm" action="<?php echo $this->url(array('module' => 'expedicao', 'controller' =>'etiqueta', 'action' =>'reimprimir' ))?>">
    <div id="quantidade-grid" class="grid">
        <table class="gTable ">
            <thead>
            <tr class="gTTitle">
                <td><p><input checked="true" class="checkBoxClass" style="vertical-align: middle" value="checkAll" onclick="check(event)" name="check-all" id="check-all" type="checkbox"/></p></td>
                <td>Cód de barras</td>
                <td>Cód Produto</td>
                <td>Produto</td>
                <td>Grade</td>
                <td>Pedido</td>
                <td>Cliente</td>
            </tr>
            </thead>
            <tbody>
            <?php
            foreach ($this->etiquetas as $etiqueta): ?>
                <tr height="35">
                    <td><input class="checkBoxClass" name="etiqueta[]" value="<?php echo $etiqueta['codBarras'] ?>" type="checkbox" checked /></td>
                    <td><?php echo $etiqueta['codBarras'] ?></td>
                    <td><?php echo $etiqueta['codProduto'] ?></td>
                    <td ><?php echo $etiqueta['produto'] ?></td>
                    <td ><?php echo $etiqueta['grade'] ?></td>
                    <td ><?php echo $etiqueta['pedido'] ?></td>
                    <td ><?php echo $etiqueta['cliente'] ?></td>
                </tr>
            <?php endforeach; ?>
            <tr>
                <td colspan="3">
                    <label>Código de barras etiqueta:</label>
                    <input class="focus" type="text" name="codBarra" id="codBarra"  onkeydown="checkEtiqueta(event)" />
                </td>
                <td colspan="2">
                    <label>Motivo:</label>
                    <?php echo $this->formText('motivo') ?>
                </td>
                <td colspan="2">
                    <?php
                    echo '<label>Senha para confirmação: </label>';
                    echo $this->formPassword("senhaConfirmacao", '', array(
                        'size' => '10',
                        'maxlength' => '20',
                    ));
                    echo $this->formSubmit("btnConfirmacao", "Reimprimir", array('class' => 'btnAlert', 'style' => 'margin: 0 0 0 10px;'));
                    ?>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</form>