<script>
    function nextInput(event) {
        if (event.which == 13 || event.keyCode == 13) {
            if (document.getElementById('codBarra').value != "") {
                motivo   = document.getElementById('motivo');
                if (motivo) {
                    motivo.focus();
                    if(event.preventDefault) {
                        event.preventDefault();
                    } else {
                        event.returnValue = false;
                    }
                }
            }
        }
        return true;
    }
</script>
<form id="" method="post" class="saveForm" action="<?php echo $this->url(array('module' => 'expedicao', 'controller' =>'etiqueta', 'action' =>'reimprimir-mapa' ))?>">
    <div id="quantidade-grid" class="grid">
        <table class="gTable ">
            <thead>
            <tr class="gTTitle">
                <td>Cód de barras do Mapa</td>
            </tr>
            </thead>
            <tbody>
            <?php
            foreach ($this->mapaSeparacao as $mapa): ?>
                <tr height="35">
                    <td><?php echo $mapa['codBarras'] ?></td>
                </tr>
            <?php endforeach; ?>
            <tr>
                <td>
                    <label>Código de barras Mapa Separação:</label>
                    <input class="focus" type="text" name="codBarra" id="codBarra"  onkeydown="nextInput(event)" />
                    <?php
                    echo $this->formSubmit("btnConfirmacao", "Reimprimir por Código", array('class' => 'btnAlert', 'style' => 'margin: 0 0 0 10px;'));
                    echo $this->formSubmit("btnReimpressao", "Reimprimir Todos", array('class' => 'btnAlert', 'style' => 'margin: 0 0 0 10px;'));
                    ?>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</form>