<script>
    function nextInput(event) {
        if (event.which == 13 || event.keyCode == 13) {
            if (document.getElementById('codBarra').value != "") {
                motivo   = document.getElementById('motivo');
                if (motivo) {
                    motivo.focus();
                    if(event.preventDefault) {
                        event.preventDefault();
                    } else {
                        event.returnValue = false;
                    }
                }
            }
        }
        return true;
    }
</script>
<form id="" method="post" class="saveForm" action="<?php echo $this->url(array('module' => 'expedicao', 'controller' =>'etiqueta', 'action' =>'reimprimir' ))?>">
    <div id="quantidade-grid" class="grid">
        <table class="gTable ">
            <thead>
            <tr class="gTTitle">
                <td>Cód de barras</td>
                <td>Cód Produto</td>
                <td>Produto</td>
                <td>Grade</td>
            </tr>
            </thead>
            <tbody>
            <?php
            foreach ($this->etiquetas as $etiqueta): ?>
                <tr height="35">
                    <td><?php echo $etiqueta['codBarras'] ?></td>
                    <td><?php echo $etiqueta['codProduto'] ?></td>
                    <td ><?php echo $etiqueta['produto'] ?></td>
                    <td ><?php echo $etiqueta['grade'] ?></td>
                </tr>
            <?php endforeach; ?>
            <tr>
                <td>
                    <label>Código de barras etiqueta:</label>
                    <input class="focus" type="text" name="codBarra" id="codBarra"  onkeydown="nextInput(event)" />
                </td>
                <td>
                    <label>Motivo:</label>
                    <?php echo $this->formText('motivo') ?>
                </td>
                <td >
                    <?php
                    echo '<label>Senha para confirmação: </label>';
                    echo $this->formPassword("senhaConfirmacao", '', array(
                        'size' => '10',
                        'maxlength' => '20',
                    ));
                    echo $this->formSubmit("btnConfirmacao", "Reimprimir", array('class' => 'btnAlert', 'style' => 'margin: 0 0 0 10px;'));
                    ?>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</form>