<?php
$this->headScript()->appendFile('/jquery-ui-1.11.4/jquery-ui.js');
//echo $this->form;
?>
<div align="Left">
    <button type="button" id="startImport">Iniciar importação</button>
</div>

<script type="text/javascript">
    $("#startImport").click(function () {
        $.ajax({
            url: URL_MODULO + '/index/iniciar-ajax',
            type: 'post',
            success: function (data){
                if (data.result) {
                    if (data.result != true) {
                        alert(data.result);
                    }
                }
            }
        });
    });
</script>