/*
 DATA DE CRIAÇÃO: 25/02/2019
 CRIADO POR: Lucas Chinelate

 ATUALIZAÇÕES:
 Data        Autor              Modificação
 25/02/19   (Lucas Chinelate)   Criação da Procedure com a modificação para identificar separação embalado e separação padrão
 15/05/19   (Lucas Chinelate)   Inclusão da Atividade de Retorno de Ressuprimento
 11/12/19   (Lucas Chinelate)   Revisão das atividades para considerar o processo com etiquetas de separação
*/

create or replace PROCEDURE PROC_PRODUTIVIDADE_DETALHE (DTH_INICIAL IN VARCHAR2, DTH_FINAL IN VARCHAR2) AS
BEGIN
    DECLARE DTH_INICIO_PARAM VARCHAR2(100);
    DTH_FIM_PARAM VARCHAR2(100);
BEGIN

  if DTH_INICIAL = 'ONTEM' THEN
     DTH_INICIO_PARAM := TO_CHAR(SYSDATE() -1,'DD/MM/YYYY');
  ELSE
     DTH_INICIO_PARAM := DTH_INICIAL;
  END IF;

  if DTH_FINAL = 'ONTEM' THEN
     DTH_FIM_PARAM := TO_CHAR(SYSDATE,'DD/MM/YYYY');
  ELSE
     DTH_FIM_PARAM := DTH_FINAL;
  END IF;

  DELETE FROM PRODUTIVIDADE_DETALHE
   WHERE TO_DATE(TO_CHAR(DTH_INICIO,'DD/MM/YYYY'),'DD/MM/YYYY')
    BETWEEN TO_DATE(DTH_INICIO_PARAM,'DD/MM/YYYY') AND TO_DATE(DTH_FIM_PARAM,'DD/MM/YYYY');

INSERT INTO PRODUTIVIDADE_DETALHE (COD_ATIVIDADE, DSC_ATIVIDADE, IDENTIDADE, COD_PESSOA, COD_PRODUTO, DSC_GRADE, DTH_INICIO , DTH_FIM , QTD_PRODUTOS, QTD_VOLUMES, QTD_CUBAGEM, QTD_PESO, QTD_PALETES, QTD_CARGA)

SELECT COD_ATIVIDADE, DSC_ATIVIDADE, IDENTIDADE, COD_PESSOA, COD_PRODUTO, DSC_GRADE, DTH_INICIO ,  DTH_FIM , QTD_PRODUTOS, QTD_VOLUMES, QTD_CUBAGEM, QTD_PESO, QTD_PALETES, QTD_CARGA
FROM (

/*
 * ATIVIDADE DE RESSUPRIMENTO
 */

        SELECT
            1 as COD_ATIVIDADE,
            'RESSUPRIMENTO' as DSC_ATIVIDADE,
            TO_CHAR(ORO.COD_ONDA_RESSUPRIMENTO_OS) as IDENTIDADE,
            RE.COD_USUARIO_ATENDIMENTO as COD_PESSOA,
            OROP.COD_PRODUTO,
            OROP.DSC_GRADE,
            TO_DATE(TO_CHAR(RE.DTH_ATENDIMENTO, 'DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS')  as DTH_INICIO,
            TO_DATE(TO_CHAR(RE.DTH_ATENDIMENTO, 'DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS') as DTH_FIM,
            1 as QTD_PRODUTOS,
            SUM(OROP.QTD) / NVL(MP.FATOR,1) as QTD_VOLUMES,
            SUM(NVL(NVL(SPP.NUM_CUBAGEM,PV.NUM_CUBAGEM),0) * OROP.QTD) as QTD_CUBAGEM,
            SUM(NVL(NVL(SPP.NUM_PESO,PV.NUM_PESO),0) * OROP.QTD) as QTD_PESO,
            COUNT(DISTINCT ORO.COD_ONDA_RESSUPRIMENTO_OS) as QTD_PALETES,
            0 as QTD_CARGA
        FROM ONDA_RESSUPRIMENTO OND
  INNER JOIN ONDA_RESSUPRIMENTO_OS ORO ON ORO.COD_ONDA_RESSUPRIMENTO = OND.COD_ONDA_RESSUPRIMENTO
  INNER JOIN RESERVA_ESTOQUE_ONDA_RESSUP REOS ON REOS.COD_ONDA_RESSUPRIMENTO_OS = ORO.COD_ONDA_RESSUPRIMENTO_OS
  INNER JOIN RESERVA_ESTOQUE RE ON RE.COD_RESERVA_ESTOQUE = REOS.COD_RESERVA_ESTOQUE
  INNER JOIN ONDA_RESSUPRIMENTO_OS_PRODUTO OROP ON OROP.COD_ONDA_RESSUPRIMENTO_OS = ORO.COD_ONDA_RESSUPRIMENTO_OS
   LEFT JOIN PRODUTO_PESO SPP ON SPP.COD_PRODUTO = OROP.COD_PRODUTO AND SPP.DSC_GRADE = OROP.DSC_GRADE AND OROP.COD_PRODUTO_VOLUME IS NULL
   LEFT JOIN PRODUTO_VOLUME PV ON PV.COD_PRODUTO_VOLUME = OROP.COD_PRODUTO_VOLUME
   LEFT JOIN (SELECT MAX(QTD_EMBALAGEM) as FATOR, COD_PRODUTO, DSC_GRADE
                FROM PRODUTO_EMBALAGEM
               WHERE IND_PADRAO = 'S' AND DTH_INATIVACAO IS NULL
               GROUP BY COD_PRODUTO, DSC_GRADE) MP ON MP.COD_PRODUTO = OROP.COD_PRODUTO AND MP.DSC_GRADE = OROP.DSC_GRADE
        WHERE
            ORO.COD_STATUS = 541
            AND RE.TIPO_RESERVA = 'S'
            AND TO_DATE(TO_CHAR(RE.DTH_ATENDIMENTO,'DD/MM/YYYY'),'DD/MM/YYYY') BETWEEN TO_DATE(DTH_INICIO_PARAM,'DD/MM/YYYY') AND TO_DATE(DTH_FIM_PARAM,'DD/MM/YYYY')
        GROUP BY
            ORO.COD_ONDA_RESSUPRIMENTO_OS,
            RE.COD_USUARIO_ATENDIMENTO,
            RE.DTH_ATENDIMENTO,
            OROP.COD_PRODUTO,
            OROP.DSC_GRADE,
            MP.FATOR

  UNION

/*
 * ATIVIDADE DE SEPARACAO PARA MAPAS
 */

  SELECT
     CASE WHEN TP.TIPO_SEPARACAO = 'EMBALADO' THEN 5 ELSE 2 END AS COD_ATIVIDADE,
     'SEPARACAO - ' || TP.TIPO_SEPARACAO as DSC_ATIVIDADE,
     TO_CHAR(A.COD_MAPA_SEPARACAO) AS IDENTIDADE,
     A.COD_USUARIO as COD_PESSOA,
     M.COD_PRODUTO,
     M.DSC_GRADE,
     TO_DATE(TO_CHAR(A.DTH_CONFERENCIA,'DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS') as DTH_INICIO,
     TO_DATE(TO_CHAR(A.DTH_FIM_CONFERENCIA,'DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS') as DTH_FIM,
     1 as QTD_PRODUTOS,
     CASE WHEN TP.TIPO_SEPARACAO = 'EMBALADO' THEN
          SUM(M.QTD_SEPARAR * M.QTD_EMBALAGEM)
     ELSE
          SUM(M.QTD_SEPARAR * M.QTD_EMBALAGEM) / NVL(MP.FATOR,1)
     END AS QTD_VOLUMES,
     SUM(NVL(NVL(SPP.NUM_CUBAGEM, PV.NUM_CUBAGEM), 0) * (M.QTD_EMBALAGEM * M.QTD_SEPARAR) - NVL(M.QTD_CORTADO,0)) as QTD_CUBAGEM,
     SUM(NVL(NVL(SPP.NUM_PESO, PV.NUM_PESO), 0) * (M.QTD_EMBALAGEM * M.QTD_SEPARAR) - NVL(M.QTD_CORTADO,0)) as QTD_PESO,
     0 as QTD_PALETES,
     1 as QTD_CARGA
  FROM APONTAMENTO_SEPARACAO_MAPA A
 INNER JOIN MAPA_SEPARACAO_PRODUTO M ON A.COD_MAPA_SEPARACAO = M.COD_MAPA_SEPARACAO
  LEFT JOIN (SELECT MAX(QTD_EMBALAGEM) as FATOR, COD_PRODUTO, DSC_GRADE
               FROM PRODUTO_EMBALAGEM
              WHERE IND_PADRAO = 'S' AND DTH_INATIVACAO IS NULL
              GROUP BY COD_PRODUTO, DSC_GRADE) MP ON MP.COD_PRODUTO = M.COD_PRODUTO AND MP.DSC_GRADE = M.DSC_GRADE
  LEFT JOIN PRODUTO_PESO SPP ON SPP.COD_PRODUTO = M.COD_PRODUTO AND SPP.DSC_GRADE = M.DSC_GRADE AND M.COD_PRODUTO_EMBALAGEM IS NOT NULL
  LEFT JOIN PRODUTO_VOLUME PV ON PV.COD_PRODUTO_VOLUME = M.COD_PRODUTO_VOLUME
  LEFT JOIN (SELECT DISTINCT COD_MAPA_SEPARACAO,
                    CASE WHEN IND_TIPO_QUEBRA = 'T' THEN 'EMBALADO' ELSE 'PADRAO' END AS TIPO_SEPARACAO
               FROM MAPA_SEPARACAO_QUEBRA) TP ON TP.COD_MAPA_SEPARACAO = M.COD_MAPA_SEPARACAO
  WHERE (M.QTD_EMBALAGEM * M.QTD_SEPARAR) - NVL(M.QTD_CORTADO,0) > 0
    AND TO_DATE(TO_CHAR(A.DTH_CONFERENCIA,'DD/MM/YYYY'),'DD/MM/YYYY') BETWEEN TO_DATE(DTH_INICIO_PARAM,'DD/MM/YYYY') AND TO_DATE(DTH_FIM_PARAM,'DD/MM/YYYY')
  GROUP BY
    A.COD_USUARIO,
    M.COD_PRODUTO,
    TO_DATE(TO_CHAR(A.DTH_CONFERENCIA,'DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS'),
    TO_DATE(TO_CHAR(A.DTH_FIM_CONFERENCIA,'DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS'),
    A.COD_MAPA_SEPARACAO,
    M.DSC_GRADE,
    TP.TIPO_SEPARACAO,
    MP.FATOR

  UNION

/*
 * ATIVIDADE DE SEPARACAO ETIQUETA
 */

 SELECT CASE WHEN ES.COD_VOLUME_PATRIMONIO IS NOT NULL THEN 5 ELSE 2 END AS DSC_ATIVIDADE,
       CASE WHEN ES.COD_VOLUME_PATRIMONIO IS NOT NULL THEN 'SEPARACAO - EMBALADO' ELSE 'SEPARACAO - PADRAO' END AS DSC_ATIVIDADE,
       TO_CHAR(EM.COD_EXPEDICAO) AS IDENTIDADE,
       EQ.COD_USUARIO as COD_PESSOA,
       ES.COD_PRODUTO,
       ES.DSC_GRADE,
       TO_DATE(TO_CHAR(EQ.DTH_VINCULO,'DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS') as DTH_INICIO,
       TO_DATE(TO_CHAR(EQ.DTH_VINCULO,'DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS') as DTH_FIM,
       1 as QTD_PRODUTOS,
       (1/ ES.QTD_USUARIO) as QTD_VOLUME,
       SUM(NVL(PV.NUM_CUBAGEM,PE.NUM_CUBAGEM) / ES.QTD_USUARIO) as QTD_CUBAGEM,
       SUM(NVL(PV.NUM_PESO,PE.NUM_PESO) / ES.QTD_USUARIO) as QTD_PESO,
       0 as QTD_PALETES,
       1 as QTD_CARGA
  FROM EQUIPE_SEPARACAO EQ
  LEFT JOIN (SELECT COUNT(DISTINCT(EQ.COD_USUARIO)) as QTD_USUARIO,
                    ES.COD_ETIQUETA_SEPARACAO,
                    ES.COD_PRODUTO_VOLUME,
                    ES.COD_VOLUME_PATRIMONIO,
                    ES.COD_PRODUTO_EMBALAGEM,
                    ES.QTD_EMBALAGEM,
                    ES.COD_PRODUTO,
                    ES.DSC_GRADE,
                    COUNT(DISTINCT (ES.COD_PRODUTO || ES.DSC_GRADE)) as QTD_PRODUTOS,
                    ES.COD_ETIQUETA_MAE
               FROM EQUIPE_SEPARACAO EQ
              INNER JOIN ETIQUETA_SEPARACAO ES ON ES.COD_ETIQUETA_SEPARACAO BETWEEN EQ.ETIQUETA_INICIAL AND EQ.ETIQUETA_FINAL
                AND TO_DATE(TO_CHAR(EQ.DTH_VINCULO,'DD/MM/YYYY'),'DD/MM/YYYY') BETWEEN TO_DATE(DTH_INICIO_PARAM,'DD/MM/YYYY') AND TO_DATE(DTH_FIM_PARAM,'DD/MM/YYYY')
              --WHERE ES.COD_STATUS NOT IN (524,525)
              GROUP BY ES.COD_ETIQUETA_MAE, ES.COD_ETIQUETA_SEPARACAO, ES.COD_PRODUTO_VOLUME, ES.COD_PRODUTO_EMBALAGEM,QTD_EMBALAGEM, ES.COD_PRODUTO, ES.DSC_GRADE, ES.COD_VOLUME_PATRIMONIO) ES
    ON ES.COD_ETIQUETA_SEPARACAO BETWEEN EQ.ETIQUETA_INICIAL AND EQ.ETIQUETA_FINAL
  LEFT JOIN PRODUTO_VOLUME PV ON PV.COD_PRODUTO_VOLUME = ES.COD_PRODUTO_VOLUME
  LEFT JOIN PRODUTO_EMBALAGEM PE ON PE.COD_PRODUTO_EMBALAGEM = ES.COD_PRODUTO_EMBALAGEM
  LEFT JOIN ETIQUETA_MAE EM ON ES.COD_ETIQUETA_MAE = EM.COD_ETIQUETA_MAE
 WHERE TO_DATE(TO_CHAR(EQ.DTH_VINCULO,'DD/MM/YYYY'),'DD/MM/YYYY') BETWEEN TO_DATE(DTH_INICIO_PARAM,'DD/MM/YYYY') AND TO_DATE(DTH_FIM_PARAM,'DD/MM/YYYY')
  GROUP BY ES.COD_VOLUME_PATRIMONIO,
        EQ.COD_USUARIO,
        ES.COD_PRODUTO,
        ES.DSC_GRADE,
        ES.QTD_USUARIO,
        TO_CHAR(EM.COD_EXPEDICAO),
        TO_DATE(TO_CHAR(EQ.DTH_VINCULO,'DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS'),
        TO_DATE(TO_CHAR(EQ.DTH_VINCULO,'DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS')

  UNION

/*
 * ATIVIDADE DE ENDERECAMENTO
 */

  SELECT
    3 as COD_ATIVIDADE,
    'ENDERECAMENTO' as DSC_ATIVIDADE,
    TO_CHAR(P.COD_RECEBIMENTO) as IDENTIDADE,
    RE.COD_USUARIO_ATENDIMENTO as COD_PESSOA ,
    PP.COD_PRODUTO,
    PP.DSC_GRADE,
    TO_DATE(TO_CHAR(RE.DTH_RESERVA, 'DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS') as DTH_INICIO,
    TO_DATE(TO_CHAR(RE.DTH_ATENDIMENTO, 'DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS') as DTH_FIM,
    1 as QTD_PRODUTOS,
    SUM(PP.QTD) / NVL(MP.FATOR,1) as QTD_VOLUMES,
    SUM(NVL(NVL(SPP.NUM_CUBAGEM,0), PV.NUM_CUBAGEM) * PP.QTD) as QTD_CUBAGEM,
    SUM(NVL(NVL(SPP.NUM_PESO,0), PV.NUM_PESO) * PP.QTD) as QTD_PESO,
    COUNT (DISTINCT P.UMA) as QTD_PALETES,
    0 as QTD_CARGA
  FROM PALETE P
 INNER JOIN PALETE_PRODUTO PP ON P.UMA = PP.UMA
  LEFT JOIN (SELECT MAX(QTD_EMBALAGEM) as FATOR, COD_PRODUTO, DSC_GRADE
               FROM PRODUTO_EMBALAGEM
              WHERE IND_PADRAO = 'S' AND DTH_INATIVACAO IS NULL
              GROUP BY COD_PRODUTO, DSC_GRADE) MP ON MP.COD_PRODUTO = PP.COD_PRODUTO AND MP.DSC_GRADE = PP.DSC_GRADE
  LEFT JOIN PRODUTO_PESO SPP ON SPP.COD_PRODUTO = PP.COD_PRODUTO AND SPP.DSC_GRADE = PP.DSC_GRADE AND PP.COD_PRODUTO_VOLUME IS NULL
  LEFT JOIN PRODUTO_VOLUME PV ON PV.COD_PRODUTO_VOLUME = PP.COD_PRODUTO_VOLUME
 INNER JOIN RESERVA_ESTOQUE_ENDERECAMENTO REE ON REE.UMA = P.UMA
 INNER JOIN RESERVA_ESTOQUE RE ON RE.COD_RESERVA_ESTOQUE = REE.COD_RESERVA_ESTOQUE
  WHERE
    P.COD_STATUS = 536 AND
    RE.DTH_ATENDIMENTO IS NOT NULL AND
    RE.IND_ATENDIDA = 'S'
    AND TO_DATE(TO_CHAR(RE.DTH_RESERVA,'DD/MM/YYYY'),'DD/MM/YYYY') BETWEEN TO_DATE(DTH_INICIO_PARAM,'DD/MM/YYYY') AND TO_DATE(DTH_FIM_PARAM,'DD/MM/YYYY')
  GROUP BY
    RE.COD_USUARIO_ATENDIMENTO,
    PP.COD_PRODUTO,
    TO_DATE(TO_CHAR(RE.DTH_RESERVA, 'DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS'),
    TO_DATE(TO_CHAR(RE.DTH_ATENDIMENTO, 'DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS'),
    P.COD_RECEBIMENTO,
    PP.DSC_GRADE,
    MP.FATOR

  UNION

/*
 * ATIVIDADE DE CONF. RECEBIMENTO
 */

SELECT
    7 as COD_ATIVIDADE,
    'CONF. RECEBIMENTO' as DSC_ATIVIDADE,
    TO_CHAR(RC.COD_RECEBIMENTO) AS IDENTIDADE,
    OS.COD_PESSOA as COD_PESSOA,
    RC.COD_PRODUTO,
    RC.DSC_GRADE,
    TO_DATE(TO_CHAR(OS.DTH_INICIO_ATIVIDADE, 'DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS') DTH_INICIO,
    TO_DATE(TO_CHAR(OS.DTH_FINAL_ATIVIDADE, 'DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS') as DTH_FIM,
    1 as QTD_PRODUTOS,
    SUM(PROD.NUM_VOLUMES * RC.QTD_CONFERIDA) / NVL(MP.FATOR,1) as QTD_VOLUMES,
    SUM(NVL(PP.NUM_CUBAGEM, 0) * RC.QTD_CONFERIDA) as QTD_CUBAGEM,
    SUM(NVL(PP.NUM_PESO, 0) * RC.QTD_CONFERIDA) as QTD_PESO,
    0 as QTD_PALETES,
    COUNT(DISTINCT RC.COD_RECEBIMENTO) as QTD_CARGA
  FROM RECEBIMENTO_CONFERENCIA RC
  LEFT JOIN ORDEM_SERVICO OS ON OS.COD_OS = RC.COD_OS
  LEFT JOIN PESSOA P ON P.COD_PESSOA = OS.COD_PESSOA
  LEFT JOIN PRODUTO PROD ON PROD.COD_PRODUTO = RC.COD_PRODUTO AND PROD.DSC_GRADE = RC.DSC_GRADE
  LEFT JOIN PRODUTO_PESO PP ON PP.COD_PRODUTO = RC.COD_PRODUTO AND PP.DSC_GRADE = RC.DSC_GRADE
  LEFT JOIN (SELECT MAX(QTD_EMBALAGEM) as FATOR, COD_PRODUTO, DSC_GRADE
             FROM PRODUTO_EMBALAGEM
            WHERE IND_PADRAO = 'S' AND DTH_INATIVACAO IS NULL
            GROUP BY COD_PRODUTO, DSC_GRADE) MP ON MP.COD_PRODUTO = RC.COD_PRODUTO AND MP.DSC_GRADE = RC.DSC_GRADE
 WHERE TO_DATE(TO_CHAR(OS.DTH_INICIO_ATIVIDADE,'DD/MM/YYYY'),'DD/MM/YYYY') BETWEEN TO_DATE(DTH_INICIO_PARAM,'DD/MM/YYYY') AND TO_DATE(DTH_FIM_PARAM,'DD/MM/YYYY')
   AND ((RC.QTD_DIVERGENCIA = 0 AND RC.IND_DIVERG_VOLUMES = 'N' AND RC.IND_DIVERGENCIA_PESO = 'N') OR RC.COD_NOTA_FISCAL IS NOT NULL)
  GROUP BY
    OS.COD_PESSOA,
    RC.COD_PRODUTO,
    TO_DATE(TO_CHAR(OS.DTH_INICIO_ATIVIDADE, 'DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS'),
    TO_DATE(TO_CHAR(OS.DTH_FINAL_ATIVIDADE, 'DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS'),
    RC.COD_RECEBIMENTO,
    RC.DSC_GRADE,
    MP.FATOR
  UNION

/*
 * ATIVIDADE DE CONF. SEPARACAO - MAPA
 */

  SELECT CASE WHEN TP.TIPO_SEPARACAO = 'EMBALADO' THEN 10 ELSE 8 END as COD_ATIVIDADE,
         'CONF. SEPARACAO - ' || TP.TIPO_SEPARACAO as DSC_ATIVIDADE,
         TO_CHAR(MSC.COD_MAPA_SEPARACAO) AS IDENTIDADE,
         OS.COD_PESSOA as COD_PESSOA,
         SPP.COD_PRODUTO,
         SPP.DSC_GRADE,
         MIN(TO_DATE(TO_CHAR(MSC.DTH_CONFERENCIA, 'DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS')) as DTH_INICIO,
         MAX(TO_DATE(TO_CHAR(MSC.DTH_CONFERENCIA, 'DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS')) as DTH_FIM,
         1 as QTD_PRODUTOS,
         CASE WHEN TP.TIPO_SEPARACAO = 'EMBALADO' THEN
            SUM(MSC.QTD_CONFERIDA * MSC.QTD_EMBALAGEM)
         ELSE
            SUM((MSC.QTD_CONFERIDA * MSC.QTD_EMBALAGEM) /NVL(MP.FATOR,1))
         END AS QTD_VOLUMES,
         SUM(MSC.QTD_CONFERIDA * MSC.QTD_EMBALAGEM * NVL(SPP.NUM_CUBAGEM,0)) as CUBAGEM,
         SUM(MSC.QTD_CONFERIDA * MSC.QTD_EMBALAGEM * NVL(SPP.NUM_PESO,0)) as QTD_PESO,
         0 as QTD_PALETES,
         NVL(C.QTD_CARGA,0) / COUNT(DISTINCT OS.COD_PESSOA) as QTD_CARGA
    FROM MAPA_SEPARACAO_CONFERENCIA MSC
    LEFT JOIN (SELECT MAX(QTD_EMBALAGEM) as FATOR, COD_PRODUTO, DSC_GRADE
                 FROM PRODUTO_EMBALAGEM
                WHERE IND_PADRAO = 'S' AND DTH_INATIVACAO IS NULL
                GROUP BY COD_PRODUTO, DSC_GRADE) MP ON MP.COD_PRODUTO = MSC.COD_PRODUTO AND MP.DSC_GRADE = MSC.DSC_GRADE
   INNER JOIN MAPA_SEPARACAO MS ON MSC.COD_MAPA_SEPARACAO = MS.COD_MAPA_SEPARACAO
   INNER JOIN EXPEDICAO E ON MS.COD_EXPEDICAO = E.COD_EXPEDICAO
   INNER JOIN (SELECT COUNT(COD_CARGA) as QTD_CARGA, COD_EXPEDICAO FROM CARGA GROUP BY COD_EXPEDICAO) C
      ON E.COD_EXPEDICAO = C.COD_EXPEDICAO
    LEFT JOIN PRODUTO_PESO SPP ON MSC.COD_PRODUTO = SPP.COD_PRODUTO AND MSC.DSC_GRADE = SPP.DSC_GRADE
    LEFT JOIN ORDEM_SERVICO OS ON OS.COD_OS = MSC.COD_OS
    LEFT JOIN (SELECT DISTINCT COD_MAPA_SEPARACAO,
                      CASE WHEN IND_TIPO_QUEBRA = 'T' THEN 'EMBALADO' ELSE 'PADRAO' END AS TIPO_SEPARACAO
                 FROM MAPA_SEPARACAO_QUEBRA) TP ON TP.COD_MAPA_SEPARACAO = MS.COD_MAPA_SEPARACAO
   WHERE TO_DATE(TO_CHAR(MSC.DTH_CONFERENCIA,'DD/MM/YYYY'),'DD/MM/YYYY')
 BETWEEN TO_DATE(DTH_INICIO_PARAM,'DD/MM/YYYY')
     AND TO_DATE(DTH_FIM_PARAM,'DD/MM/YYYY')
   GROUP BY OS.COD_PESSOA,
            C.QTD_CARGA,
            MSC.COD_MAPA_SEPARACAO,
            SPP.COD_PRODUTO,
            SPP.DSC_GRADE,
            TP.TIPO_SEPARACAO,
            MP.FATOR

        UNION

/*
 * ATIVIDADE DE CONF. SEPARACAO - ETIQUETA
 */

 SELECT CASE WHEN ES.COD_VOLUME_PATRIMONIO IS NULL THEN 8 ELSE 10 END as COD_ATIVIDADE,
       'CONF. SEPARACAO - ' || CASE WHEN ES.COD_VOLUME_PATRIMONIO IS NULL THEN 'PADRAO' ELSE 'EMBALADO' END as DSC_ATIVIDADE,
        TO_CHAR(C.COD_EXPEDICAO) AS IDENTIDADE,
        OS.COD_PESSOA as COD_PESSOA,
        ES.COD_PRODUTO,
        ES.DSC_GRADE,
        MIN(TO_DATE(TO_CHAR(ES.DTH_CONFERENCIA, 'DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS')) as DTH_INICIO,
        MAX(TO_DATE(TO_CHAR(ES.DTH_CONFERENCIA, 'DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS')) as DTH_FIM,
        1 as QTD_PRODUTOS,
        COUNT(ES.COD_ETIQUETA_SEPARACAO) as QTD_VOLUMES,
        SUM(NVL(PE.NUM_CUBAGEM, PV.NUM_CUBAGEM)) as CUBAGEM,
        SUM(NVL(PE.NUM_PESO, PV.NUM_PESO)) as QTD_PESO,
        0 as QTD_PALETES,
        COUNT(DISTINCT C.COD_CARGA) / COUNT(DISTINCT OS.COD_PESSOA) as QTD_CARGA
  FROM ETIQUETA_SEPARACAO ES
  LEFT JOIN PEDIDO P ON P.COD_PEDIDO = ES.COD_PEDIDO
  LEFT JOIN CARGA C ON C.COD_CARGA = P.COD_CARGA
 INNER JOIN ORDEM_SERVICO OS ON OS.COD_OS = ES.COD_OS
  LEFT JOIN PRODUTO_EMBALAGEM PE ON PE.COD_PRODUTO_EMBALAGEM = ES.COD_PRODUTO_EMBALAGEM
  LEFT JOIN PRODUTO_VOLUME PV ON PV.COD_PRODUTO_VOLUME = ES.COD_PRODUTO_VOLUME
 WHERE 1 = 1
   AND TO_DATE(TO_CHAR(ES.DTH_CONFERENCIA,'DD/MM/YYYY'),'DD/MM/YYYY') BETWEEN TO_DATE(DTH_INICIO_PARAM,'DD/MM/YYYY') AND TO_DATE(DTH_FIM_PARAM,'DD/MM/YYYY')
 GROUP BY OS.COD_PESSOA,
          C.COD_EXPEDICAO,
          ES.COD_PRODUTO,
          ES.DSC_GRADE,
          ES.COD_VOLUME_PATRIMONIO

 UNION

/*
 * ATIVIDADE DE CARREGAMENTO - CAIXA FECHADA - MAPA DE SEPARAÇÃO
 */

      SELECT  9 as COD_ATIVIDADE,
              'CARREGAMENTO' as DSC_ATIVIDADE,
              TO_CHAR(E.COD_EXPEDICAO) as IDENTIDADE,
              E.COD_USUARIO as COD_PESSOA,
              MSC.COD_PRODUTO,
              MSC.DSC_GRADE,
              TO_DATE(TO_CHAR(E.DTH_INICIO, 'DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS') as DTH_INICIO,
              TO_DATE(TO_CHAR(E.DTH_FINAL, 'DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS') as DTH_FIM,
              1 / QTD_PES.QTD_USUARIOS as QTD_PRODUTOS,
              SUM((MSC.QTD_CONFERIDA * MSC.QTD_EMBALAGEM) /NVL(MP.FATOR,1)) /QTD_PES.QTD_USUARIOS  as QTD_VOLUMES,
              SUM(MSC.QTD_CONFERIDA * MSC.QTD_EMBALAGEM * NVL(SPP.NUM_CUBAGEM,0)) /QTD_PES.QTD_USUARIOS  as CUBAGEM,
              SUM(MSC.QTD_CONFERIDA * MSC.QTD_EMBALAGEM * NVL(SPP.NUM_PESO,0))  /QTD_PES.QTD_USUARIOS    as QTD_PESO,
              0 as QTD_PALETES,
              0 as QTD_CARGA
         FROM EQUIPE_CARREGAMENTO_EXPEDICAO E
         LEFT JOIN (SELECT COD_EXPEDICAO,
                           COUNT(COD_USUARIO) as QTD_USUARIOS
                      FROM EQUIPE_CARREGAMENTO_EXPEDICAO
                     GROUP BY COD_EXPEDICAO) QTD_PES ON QTD_PES.COD_EXPEDICAO = E.COD_EXPEDICAO
         LEFT JOIN MAPA_SEPARACAO MS ON MS.COD_EXPEDICAO = E.COD_EXPEDICAO
         LEFT JOIN MAPA_SEPARACAO_CONFERENCIA MSC ON MSC.COD_MAPA_SEPARACAO = MS.COD_MAPA_SEPARACAO
         LEFT JOIN PRODUTO_PESO SPP ON MSC.COD_PRODUTO = SPP.COD_PRODUTO AND MSC.DSC_GRADE = SPP.DSC_GRADE
        INNER JOIN (SELECT DISTINCT COD_MAPA_SEPARACAO FROM MAPA_SEPARACAO_QUEBRA WHERE IND_TIPO_QUEBRA <> 'T') TP
           ON TP.COD_MAPA_SEPARACAO = MS.COD_MAPA_SEPARACAO
         LEFT JOIN (SELECT MAX(QTD_EMBALAGEM) as FATOR, COD_PRODUTO, DSC_GRADE
                      FROM PRODUTO_EMBALAGEM
                     WHERE IND_PADRAO = 'S' AND DTH_INATIVACAO IS NULL
                     GROUP BY COD_PRODUTO, DSC_GRADE) MP ON MP.COD_PRODUTO = MSC.COD_PRODUTO AND MP.DSC_GRADE = MSC.DSC_GRADE
        WHERE TO_DATE(TO_CHAR(E.DTH_INICIO,'DD/MM/YYYY'),'DD/MM/YYYY') BETWEEN TO_DATE(DTH_INICIO_PARAM,'DD/MM/YYYY') AND TO_DATE(DTH_FIM_PARAM,'DD/MM/YYYY')
        GROUP BY E.COD_USUARIO,
                 TO_DATE(TO_CHAR(E.DTH_INICIO, 'DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS'),
                 TO_DATE(TO_CHAR(E.DTH_FINAL, 'DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS'),
                 MSC.COD_PRODUTO,
                 E.COD_EXPEDICAO,
                 MSC.DSC_GRADE,
                 QTD_PES.QTD_USUARIOS

  UNION

/*
 * ATIVIDADE DE CARREGAMENTO - VOLUME EMBALADO - MAPA DE SEPARAÇÃO
 */

  SELECT 9 as COD_ATIVIDADE,
         'CARREGAMENTO' as DSC_ATIVIDADE,
         TO_CHAR(E.COD_EXPEDICAO) as IDENTIDADE,
         E.COD_USUARIO as COD_PESSOA,
         CAST (MSC.COD_MAPA_SEPARACAO_EMBALADO as VARCHAR2(20)) as COD_PRODUTO,
         'EMBALADO' as DSC_GRADE,
         TO_DATE(TO_CHAR(E.DTH_INICIO, 'DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS') as DTH_INICIO,
         TO_DATE(TO_CHAR(E.DTH_FINAL, 'DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS') as DTH_FIM,
         COUNT(DISTINCT(MSC.COD_PRODUTO || MSC.DSC_GRADE)) / QTD_PES.QTD_USUARIOS as QTD_PRODUTOS,
         1 / QTD_PES.QTD_USUARIOS  as QTD_VOLUMES,
         SUM(MSC.QTD_CONFERIDA * MSC.QTD_EMBALAGEM * NVL(SPP.NUM_CUBAGEM,0)) /QTD_PES.QTD_USUARIOS  as CUBAGEM,
         SUM(MSC.QTD_CONFERIDA * MSC.QTD_EMBALAGEM * NVL(SPP.NUM_PESO,0))  /QTD_PES.QTD_USUARIOS    as QTD_PESO,
         0 as QTD_PALETES,
         0 as QTD_CARGA
    FROM EQUIPE_CARREGAMENTO_EXPEDICAO E
    LEFT JOIN (SELECT COD_EXPEDICAO,
                      COUNT(COD_USUARIO) as QTD_USUARIOS
                 FROM EQUIPE_CARREGAMENTO_EXPEDICAO
                GROUP BY COD_EXPEDICAO) QTD_PES ON QTD_PES.COD_EXPEDICAO = E.COD_EXPEDICAO
         LEFT JOIN MAPA_SEPARACAO MS ON MS.COD_EXPEDICAO = E.COD_EXPEDICAO
    LEFT JOIN MAPA_SEPARACAO_CONFERENCIA MSC ON MSC.COD_MAPA_SEPARACAO = MS.COD_MAPA_SEPARACAO
    LEFT JOIN PRODUTO_PESO SPP ON MSC.COD_PRODUTO = SPP.COD_PRODUTO AND MSC.DSC_GRADE = SPP.DSC_GRADE
   INNER JOIN MAPA_SEPARACAO_EMB_CLIENTE MSEC ON MSEC.COD_MAPA_SEPARACAO_EMB_CLIENTE = MSC.COD_MAPA_SEPARACAO_EMBALADO
                                             AND MSEC.COD_MAPA_SEPARACAO = MSC.COD_MAPA_SEPARACAO
   WHERE TO_DATE(TO_CHAR(E.DTH_INICIO,'DD/MM/YYYY'),'DD/MM/YYYY') BETWEEN TO_DATE(DTH_INICIO_PARAM,'DD/MM/YYYY') AND TO_DATE(DTH_FIM_PARAM,'DD/MM/YYYY')
   GROUP BY E.COD_USUARIO,
            TO_DATE(TO_CHAR(E.DTH_INICIO, 'DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS'),
            TO_DATE(TO_CHAR(E.DTH_FINAL, 'DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS'),
            MSC.COD_MAPA_SEPARACAO_EMBALADO,
            E.COD_EXPEDICAO,
            QTD_PES.QTD_USUARIOS

  UNION

/*
 * ATIVIDADE DE CARREGAMENTO - CAIXA FECHADA - ETIQUETA DE SEPARACAO
 */

  SELECT 9 as COD_ATIVIDADE,
         'CARREGAMENTO' as DSC_ATIVIDADE,
         TO_CHAR(E.COD_EXPEDICAO) as IDENTIDADE,
         E.COD_USUARIO as COD_PESSOA,
         ES.COD_PRODUTO,
         ES.DSC_GRADE,
         TO_DATE(TO_CHAR(E.DTH_INICIO, 'DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS') as DTH_INICIO,
         TO_DATE(TO_CHAR(E.DTH_FINAL, 'DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS') as DTH_FIM,
         1 / QTD_PES.QTD_USUARIOS as QTD_PRODUTOS,
         COUNT(DISTINCT(COD_ETIQUETA_SEPARACAO)) /QTD_PES.QTD_USUARIOS  as QTD_VOLUMES,
         SUM(NVL(PV.NUM_CUBAGEM,PE.NUM_CUBAGEM))  /QTD_PES.QTD_USUARIOS  as CUBAGEM,
         SUM(NVL(PV.NUM_PESO,PE.NUM_PESO))  /QTD_PES.QTD_USUARIOS    as QTD_PESO,
         0 as QTD_PALETES,
         0 as QTD_CARGA
    FROM EQUIPE_CARREGAMENTO_EXPEDICAO E
    LEFT JOIN (SELECT COD_EXPEDICAO,
                      COUNT(COD_USUARIO) as QTD_USUARIOS
                 FROM EQUIPE_CARREGAMENTO_EXPEDICAO
                GROUP BY COD_EXPEDICAO) QTD_PES ON QTD_PES.COD_EXPEDICAO = E.COD_EXPEDICAO
    LEFT JOIN ETIQUETA_MAE EM ON E.COD_EXPEDICAO = EM.COD_EXPEDICAO
    LEFT JOIN ETIQUETA_SEPARACAO ES ON ES.COD_ETIQUETA_MAE = EM.COD_ETIQUETA_MAE
    LEFT JOIN PRODUTO_VOLUME PV ON ES.COD_PRODUTO_VOLUME = PV.COD_PRODUTO_VOLUME
    LEFT JOIN PRODUTO_EMBALAGEM PE ON ES.COD_PRODUTO_EMBALAGEM = PE.COD_PRODUTO_EMBALAGEM
    LEFT JOIN EXPEDICAO EXP ON E.COD_EXPEDICAO = EXP.COD_EXPEDICAO
    WHERE COD_VOLUME_PATRIMONIO IS NULL
      AND TO_DATE(TO_CHAR(E.DTH_INICIO,'DD/MM/YYYY'),'DD/MM/YYYY') BETWEEN TO_DATE(DTH_INICIO_PARAM,'DD/MM/YYYY') AND TO_DATE(DTH_FIM_PARAM,'DD/MM/YYYY')
      AND EXP.COD_STATUS <> 466
      --AND ES.COD_STATUS NOT IN (524,525)

    GROUP BY E.COD_USUARIO,
             TO_DATE(TO_CHAR(E.DTH_INICIO, 'DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS'),
             TO_DATE(TO_CHAR(E.DTH_FINAL, 'DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS'),
             ES.COD_PRODUTO,
             E.COD_EXPEDICAO,
             ES.DSC_GRADE,
             QTD_PES.QTD_USUARIOS

  UNION

/*
 * ATIVIDADE DE CARREGAMENTO - CAIXA FECHADA - ETIQUETA DE SEPARACAO
 */

  SELECT 9 as COD_ATIVIDADE,
         'CARREGAMENTO' as DSC_ATIVIDADE,
         TO_CHAR(E.COD_EXPEDICAO) as IDENTIDADE,
         E.COD_USUARIO as COD_PESSOA,
         TO_CHAR(EVP.COD_VOLUME_PATRIMONIO) as COD_PRODUTO,
         'EMBALADO' as DSC_GRADE,
         TO_DATE(TO_CHAR(E.DTH_INICIO, 'DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS') as DTH_INICIO,
         TO_DATE(TO_CHAR(E.DTH_FINAL, 'DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS') as DTH_FIM,
         1 / QTD_PES.QTD_USUARIOS as QTD_PRODUTOS,
         COUNT(DISTINCT(COD_ETIQUETA_SEPARACAO)) /QTD_PES.QTD_USUARIOS  as QTD_VOLUMES,
         SUM(NVL(PV.NUM_CUBAGEM,PE.NUM_CUBAGEM))  /QTD_PES.QTD_USUARIOS  as CUBAGEM,
         SUM(NVL(PV.NUM_PESO,PE.NUM_PESO))  /QTD_PES.QTD_USUARIOS    as QTD_PESO,
         0 as QTD_PALETES,
         0 as QTD_CARGA
    FROM EQUIPE_CARREGAMENTO_EXPEDICAO E
    LEFT JOIN (SELECT COD_EXPEDICAO,
                      COUNT(COD_USUARIO) as QTD_USUARIOS
                 FROM EQUIPE_CARREGAMENTO_EXPEDICAO
                GROUP BY COD_EXPEDICAO) QTD_PES ON QTD_PES.COD_EXPEDICAO = E.COD_EXPEDICAO
   INNER JOIN EXPEDICAO_VOLUME_PATRIMONIO EVP ON E.COD_EXPEDICAO = EVP.COD_EXPEDICAO
   INNER JOIN ETIQUETA_MAE EM ON EM.COD_EXPEDICAO = EVP.COD_EXPEDICAO
   INNER JOIN ETIQUETA_SEPARACAO ES ON ES.COD_VOLUME_PATRIMONIO = EVP.COD_VOLUME_PATRIMONIO
                                   AND ES.COD_ETIQUETA_MAE = EM.COD_ETIQUETA_MAE
    LEFT JOIN PRODUTO_VOLUME PV ON ES.COD_PRODUTO_VOLUME = PV.COD_PRODUTO_VOLUME
    LEFT JOIN PRODUTO_EMBALAGEM PE ON ES.COD_PRODUTO_EMBALAGEM = PE.COD_PRODUTO_EMBALAGEM
    LEFT JOIN EXPEDICAO EXP ON E.COD_EXPEDICAO = EXP.COD_EXPEDICAO
    WHERE 1 = 1
    AND TO_DATE(TO_CHAR(E.DTH_INICIO,'DD/MM/YYYY'),'DD/MM/YYYY') BETWEEN TO_DATE(DTH_INICIO_PARAM,'DD/MM/YYYY') AND TO_DATE(DTH_FIM_PARAM,'DD/MM/YYYY')
    AND EXP.COD_STATUS <> 466
    --AND ES.COD_STATUS NOT IN (524,525)
    GROUP BY E.COD_USUARIO,
             TO_DATE(TO_CHAR(E.DTH_INICIO, 'DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS'),
             TO_DATE(TO_CHAR(E.DTH_FINAL, 'DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS'),
             EVP.COD_VOLUME_PATRIMONIO,
             E.COD_EXPEDICAO,
             QTD_PES.QTD_USUARIOS

    UNION

/*
 * ATIVIDADE DE DESCARREGAMENTO
 */

  SELECT
    11 as COD_ATIVIDADE,
    'DESCARREGAMENTO' as DSC_ATIVIDADE,
    TO_CHAR(RD.COD_RECEBIMENTO) as IDENTIDADE,
    RD.COD_USUARIO as COD_PESSOA,
    PP.COD_PRODUTO,
    PP.DSC_GRADE,
    TO_DATE(TO_CHAR(RD.DTH_VINCULO, 'DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS') as DTH_INICIO,
    TO_DATE(TO_CHAR(RD.DTH_VINCULO, 'DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS') as DTH_FIM,
    CAST(SUM(1/QTD_PES.QTD_USUARIOS)as NUMBER(30,2)) as QTD_PRODUTOS,
    CAST(SUM(((RC.QTD_CONFERIDA * P.NUM_VOLUMES)/NVL(MP.FATOR,1)) /QTD_PES.QTD_USUARIOS) as NUMBER(20,2)) as QTD_VOLUMES,
    CAST(SUM((RC.QTD_CONFERIDA * NVL(NVL(PP.NUM_CUBAGEM,0),0))/QTD_PES.QTD_USUARIOS) as NUMBER(30,2)) as QTD_CUBAGEM,
    CAST(SUM((RC.QTD_CONFERIDA * NVL(NVL(PP.NUM_PESO,0),0))/QTD_PES.QTD_USUARIOS)    as NUMBER(30,2)) as QTD_PESO,
    CAST(SUM(NVL(UMA.QTD_PALETE,0)/QTD_PES.QTD_USUARIOS)    as NUMBER(30,2)) as QTD_PALETE,
    0 as QTD_CARGA
  FROM RECEBIMENTO_DESCARGA RD
  LEFT JOIN (SELECT COD_RECEBIMENTO, COUNT(COD_USUARIO) as QTD_USUARIOS
               FROM RECEBIMENTO_DESCARGA GROUP BY COD_RECEBIMENTO) QTD_PES
    ON QTD_PES.COD_RECEBIMENTO = RD.COD_RECEBIMENTO
  LEFT JOIN RECEBIMENTO_CONFERENCIA RC
    ON RC.COD_RECEBIMENTO = RD.COD_RECEBIMENTO
   AND ((RC.QTD_DIVERGENCIA = 0 AND RC.IND_DIVERG_VOLUMES = 'N' AND RC.IND_DIVERGENCIA_PESO = 'N') OR RC.COD_NOTA_FISCAL IS NOT NULL)
  LEFT JOIN PRODUTO P ON P.COD_PRODUTO = RC.COD_PRODUTO AND P.DSC_GRADE = RC.DSC_GRADE
  LEFT JOIN (SELECT MAX(QTD_EMBALAGEM) as FATOR, COD_PRODUTO, DSC_GRADE
               FROM PRODUTO_EMBALAGEM
              WHERE IND_PADRAO = 'S' AND DTH_INATIVACAO IS NULL
              GROUP BY COD_PRODUTO, DSC_GRADE) MP ON MP.COD_PRODUTO = P.COD_PRODUTO AND MP.DSC_GRADE = P.DSC_GRADE
  LEFT JOIN (SELECT COUNT(UMA) as QTD_PALETE, COD_RECEBIMENTO FROM PALETE GROUP BY COD_RECEBIMENTO) UMA ON UMA.COD_RECEBIMENTO = RD.COD_RECEBIMENTO
  LEFT JOIN PRODUTO_PESO PP ON PP.COD_PRODUTO = RC.COD_PRODUTO AND PP.DSC_GRADE = RC.DSC_GRADE
 WHERE TO_DATE(TO_CHAR(RD.DTH_VINCULO,'DD/MM/YYYY'),'DD/MM/YYYY') BETWEEN TO_DATE(DTH_INICIO_PARAM,'DD/MM/YYYY') AND TO_DATE(DTH_FIM_PARAM,'DD/MM/YYYY')
 GROUP BY RD.COD_USUARIO,
          TO_DATE(TO_CHAR(RD.DTH_VINCULO, 'DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS'),
          RD.COD_RECEBIMENTO,
          PP.COD_PRODUTO,
          PP.DSC_GRADE,
          MP.FATOR

  UNION

  /*
   * ATIVIDADE DE RETORNO DE RESSUPRIMENTO
   */

SELECT 12 as COD_ATIVIDADE,
       'RETORNO RESSUPRIMENTO' as DSC_ATIVIDADE,
       TO_CHAR(RR.COD_ONDA_RESSUPRIMENTO_OS) as IDENTIDADE,
       OS.COD_PESSOA as COD_PESSOA,
       RRP.COD_PRODUTO,
       RRP.DSC_GRADE,
       TO_DATE(TO_CHAR(RR.DTH_MOVIMENTACAO, 'DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS')  as DTH_INICIO,
       TO_DATE(TO_CHAR(RR.DTH_MOVIMENTACAO, 'DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS')  as DTH_FIM,
       1 as QTD_PRODUTOS,
       SUM(RRP.QTD) / NVL(MP.FATOR,1) as QTD_VOLUMES,
       SUM(NVL(NVL(SPP.NUM_CUBAGEM,PV.NUM_CUBAGEM),0) * RRP.QTD) as QTD_CUBAGEM,
       SUM(NVL(NVL(SPP.NUM_PESO,PV.NUM_PESO),0) * RRP.QTD) as QTD_PESO,
       COUNT(DISTINCT RR.COD_ONDA_RESSUPRIMENTO_OS) as QTD_PALETES,
       0 as QTD_CARGA
  FROM RETORNO_RESSUPRIMENTO RR
  LEFT JOIN RETORNO_RESSUPRIMENTO_PRODUTO RRP ON RR.COD_RETORNO_RESSUPRIMENTO = RRP.COD_RETORNO_RESSUPRIMENTO
  LEFT JOIN PRODUTO_PESO SPP ON SPP.COD_PRODUTO = RRP.COD_PRODUTO AND SPP.DSC_GRADE = RRP.DSC_GRADE AND RRP.COD_PRODUTO_VOLUME IS NULL
  LEFT JOIN PRODUTO_VOLUME PV ON PV.COD_PRODUTO_VOLUME = RRP.COD_PRODUTO_VOLUME
  LEFT JOIN ORDEM_SERVICO OS ON OS.COD_OS = RR.COD_OS
  LEFT JOIN (SELECT MAX(QTD_EMBALAGEM) as FATOR, COD_PRODUTO, DSC_GRADE
               FROM PRODUTO_EMBALAGEM
              WHERE IND_PADRAO = 'S' AND DTH_INATIVACAO IS NULL
              GROUP BY COD_PRODUTO, DSC_GRADE) MP ON MP.COD_PRODUTO = RRP.COD_PRODUTO AND MP.DSC_GRADE = RRP.DSC_GRADE

 WHERE 1 = 1
   AND TO_DATE(TO_CHAR(RR.DTH_MOVIMENTACAO,'DD/MM/YYYY'),'DD/MM/YYYY') BETWEEN TO_DATE(DTH_INICIO_PARAM,'DD/MM/YYYY') AND TO_DATE(DTH_FIM_PARAM,'DD/MM/YYYY')
 GROUP BY RR.COD_ONDA_RESSUPRIMENTO_OS,
          OS.COD_PESSOA,
          RR.DTH_MOVIMENTACAO,
          RRP.COD_PRODUTO,
          RRP.DSC_GRADE,
          MP.FATOR

    UNION

/*
 * ATIVIDADE DE CONF. TRANSBORDO - ETIQUETA
 */

 SELECT CASE WHEN ES.COD_VOLUME_PATRIMONIO IS NULL THEN 13 ELSE 14 END as COD_ATIVIDADE,
        'CONF. TRANSBORDO - ' || CASE WHEN ES.COD_VOLUME_PATRIMONIO IS NULL THEN 'PADRAO' ELSE 'EMBALADO' END as DSC_ATIVIDADE,
        TO_CHAR(C.COD_EXPEDICAO) AS IDENTIDADE,
        OS.COD_PESSOA as COD_PESSOA,
        ES.COD_PRODUTO,
        ES.DSC_GRADE,
        MIN(TO_DATE(TO_CHAR(ES.DTH_CONFERENCIA_TRANSBORDO, 'DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS')) as DTH_INICIO,
        MAX(TO_DATE(TO_CHAR(ES.DTH_CONFERENCIA_TRANSBORDO, 'DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS')) as DTH_FIM,
        1 as QTD_PRODUTOS,
        COUNT(ES.COD_ETIQUETA_SEPARACAO) as QTD_VOLUMES,
        SUM(NVL(PE.NUM_CUBAGEM, PV.NUM_CUBAGEM)) as CUBAGEM,
        SUM(NVL(PE.NUM_PESO, PV.NUM_PESO)) as QTD_PESO,
        0 as QTD_PALETES,
        COUNT(DISTINCT C.COD_CARGA) / COUNT(DISTINCT OS.COD_PESSOA) as QTD_CARGA
  FROM ETIQUETA_SEPARACAO ES
  LEFT JOIN PEDIDO P ON P.COD_PEDIDO = ES.COD_PEDIDO
  LEFT JOIN CARGA C ON C.COD_CARGA = P.COD_CARGA
 INNER JOIN ORDEM_SERVICO OS ON OS.COD_OS = ES.COD_OS_TRANSBORDO
  LEFT JOIN PRODUTO_EMBALAGEM PE ON PE.COD_PRODUTO_EMBALAGEM = ES.COD_PRODUTO_EMBALAGEM
  LEFT JOIN PRODUTO_VOLUME PV ON PV.COD_PRODUTO_VOLUME = ES.COD_PRODUTO_VOLUME
 WHERE 1 = 1
   AND TO_DATE(TO_CHAR(ES.DTH_CONFERENCIA,'DD/MM/YYYY'),'DD/MM/YYYY') BETWEEN TO_DATE(DTH_INICIO_PARAM,'DD/MM/YYYY') AND TO_DATE(DTH_FIM_PARAM,'DD/MM/YYYY')
 GROUP BY OS.COD_PESSOA,
          C.COD_EXPEDICAO,
          ES.COD_PRODUTO,
          ES.DSC_GRADE,
          ES.COD_VOLUME_PATRIMONIO

)
  WHERE
    TO_DATE(TO_CHAR(DTH_INICIO,'DD/MM/YYYY'),'DD/MM/YYYY') BETWEEN
    TO_DATE(DTH_INICIO_PARAM,'DD/MM/YYYY') AND
    TO_DATE(DTH_FIM_PARAM,'DD/MM/YYYY');

END;
END PROC_PRODUTIVIDADE_DETALHE;