<?php
//echo $this->form;
/** @var Zend_Form $form */
$form = $this->form;
?>
<form method="get" class="filtro" action="">
    <div>
    <fieldset id="fieldset-apontamento">
        <legend>Relatório de comparativo de estoque ERP x WMS</legend>
        <?php echo $form->getElement('modeloInventario'); ?>
        <?php echo $form->getElement('inventario'); ?>
        <?php echo $form->getElement('divergencia'); ?>
        <?php echo $form->getElement('tipoDivergencia'); ?>
        <?php echo $form->getElement('estoqueWms'); ?>
        <?php echo $form->getElement('estoqueErp'); ?>
        <?php echo $form->getElement('deduzirAvaria'); ?>
        <?php echo $form->getElement('emInventario'); ?>
        <?php echo $form->getElement('fabricante'); ?>
        <?php echo $form->getElement('linhaSeparacao'); ?>
        <?php echo $form->getElement('considerarReserva'); ?>
        <?php echo $form->getElement('orderBy'); ?>
        <div class="field">
            <?php echo $form->getElement('directionOrder'); ?>
        </div>
        <div class="field">
            <input type="submit" name="submit" id="submit" value="Buscar" class="btn">
            <input type="submit" name="gerarPdf" id="gerarPdf" value="Gerar relatório" class="btn">
        </div>
    </fieldset>
    </div>
</form>

<?php
echo $this->grid;
?>


<div id="div-form-hidded"></div>
<script>
    $('.gAction').hide();
    $('.gMassAction').append('<button style="margin: 5px 15px 5px 10px; width: 200px;" type="button" name="inventariar" id="inventariar" class="btn">Inventário Parcial por produto</button>');

    $("#inventariar").click(function () {
        if ($("#modeloInventario").val() !== "N") {
            var dados = '';
            var grade = '';
            $(".gTable input:checked").each(function (e) {
                if ($(this).val() != 'on') {
                    if (dados == '') {
                        dados = $(this).val();
                        grade = "'" + $(this).parent().siblings().nextAll().first().text() + "'";
                    } else {
                        dados += ',' + $(this).val();
                        grade += ",'" + $(this).parent().siblings().nextAll().first().text() + "'";
                    }
                }
            });
            window.open("/inventario/parcial/produto?picking=1&pulmao=1&incluirinput=" + dados + "&grades=" + grade);
            return false;
        } else {
            let newForm = $("<form method='post' id='form-hided' action='/inventario_novo/index/criar-inventario/criterio/P'>");
            let itens = [];
            $(".gTable input:checked").each(function (k, e) {
                itens.push({codProduto: $(this).val(), grade: $(this).parent().siblings().nextAll().first().text()})
            });
            newForm.append($("<input type='hidden' name='itens' value='"+ JSON.stringify(itens)+"'>"));
            $("#div-form-hidded").append(newForm);
            newForm.submit();
        }
    });
    $(".massaction-check-opt").click(function () {
        if ($("#modeloInventario").val() !== "N") {
            var count = 0;
            $(".gTable input:checked").each(function (e) {
                count++;
            });
            if (count > 15) {
                $.wmsDialogAlert({
                    title: 'ERRO',
                    msg: 'Limite excedido.'
                });
                return false;
            }
        }
    });
    $(document).ready(function () {
        if (isEmpty($(".orderByInpt").val())) $("#directionOrder-label").parent().hide();
    });

    $(".orderByInpt").change(function () {
        let directionOrder = $("#directionOrder-label").parent();
        if (!isEmpty($(this).val())) directionOrder.show();
        else directionOrder.hide();
    })
</script>