<?php
echo $this->form;
echo $this->grid;
?>
<script>
    $('.gAction').hide();
    $('.gMassAction .gSelect').hide();
    $('.gMassAction').append('<input style="margin: 5px 15px 5px 10px; width: 200px;" type="submit" name="inventariar" id="inventariar" value="Inventários por Produto" class="btn">');

    $("#inventariar").click(function () {
        var dados = '';
        var grade = '';
        $(".gTable input:checked").each(function (e) {
            if ($(this).val() != 'on') {
                if (dados == '') {
                    dados = $(this).val();
                    grade = "'" + $(this).parent().siblings().nextAll().first().text() + "'";
                } else {
                    dados += ',' + $(this).val();
                    grade += ",'" + $(this).parent().siblings().nextAll().first().text() + "'";
                }
            }
        });
        window.open("/inventario/parcial/produto?picking=1&pulmao=1&incluirinput=" + dados + "&grades=" + grade);
        return false;
    });
    $(".massaction-check-opt").click(function () {
        var count = 0;
        $(".gTable input:checked").each(function (e) {
            count++;
        });
        if (count > 15) {
            $.wmsDialogAlert({
                title: 'ERRO',
                msg: 'Limite excedido.'
            });
            return false;
        }
    });
</script>