INSERT INTO VERSAO (DTH, NUMERO_VERSAO, SCRIPT) VALUES (SYSDATE, '6.12.0','10-unidade-fracionavel.sql');

ALTER TABLE PRODUTO ADD (IND_FRACIONAVEL CHAR(1), UNID_FRACAO VARCHAR(10));
UPDATE PRODUTO SET IND_FRACIONAVEL = 'N';

ALTER TABLE PRODUTO_EMBALAGEM ADD (IS_EMB_FRACIONAVEL_DEFAULT CHAR(1));
ALTER TABLE PRODUTO_EMBALAGEM ADD (IS_EMB_EXPEDICAO_DEFAULT CHAR(1));
UPDATE PRODUTO_EMBALAGEM SET IS_EMB_FRACIONAVEL_DEFAULT = 'N', IS_EMB_EXPEDICAO_DEFAULT = 'N';

ALTER TABLE RECEBIMENTO_EMBALAGEM ADD (NUM_PECAS NUMBER(8));
ALTER TABLE RECEBIMENTO_CONFERENCIA ADD (NUM_PECAS NUMBER(8));
ALTER TABLE PALETE_PRODUTO ADD (NUM_PECAS NUMBER(8));
ALTER TABLE RESERVA_ESTOQUE_PRODUTO ADD (NUM_PECAS NUMBER(8));
ALTER TABLE ESTOQUE ADD (NUM_PECAS NUMBER(8));
