INSERT INTO VERSAO (DTH, NUMERO_VERSAO, SCRIPT) VALUES (SYSDATE, '6.13.5','16-cadastro-rota.sql');

ALTER TABLE PRACA ADD COD_PRACA_EXTERNO VARCHAR2(50 BYTE);
ALTER TABLE ROTA ADD COD_ROTA_EXTERNO VARCHAR2(50 BYTE);
ALTER TABLE CLIENTE ADD COD_ROTA NUMBER(8,0);

ALTER TABLE MODELO_SEPARACAO_TPQUEB_NFRAC
  MODIFY (IND_TIPO_QUEBRA VARCHAR2(2));

ALTER TABLE MODELO_SEPARACAO_TPQUEB_FRAC
  MODIFY (IND_TIPO_QUEBRA VARCHAR2(2));

ALTER TABLE MODELO_SEPARACAO_TPQUEB_EMB
  MODIFY (IND_TIPO_QUEBRA VARCHAR2(2));