INSERT INTO VERSAO (DTH, NUMERO_VERSAO, SCRIPT) VALUES (SYSDATE, '6.13.5','18-id-triggers');

ALTER TABLE TR_PEDIDO ADD ID NUMBER(10,0);

CREATE SEQUENCE SQ_TR_PEDIDO;

CREATE OR REPLACE TRIGGER ID_TR_PEDIDO
  BEFORE INSERT ON TR_PEDIDO
  FOR EACH ROW
BEGIN
  SELECT SQ_TR_PEDIDO.NEXTVAL
  INTO :NEW.ID
  FROM DUAL;
END;

UPDATE ACAO_INTEGRACAO SET DSC_QUERY = 'SELECT ID, CARGA, PLACA, PEDIDO, TIPO_PEDIDO, COD_PRACA, DSC_PRACA, COD_ROTA, DSC_ROTA, COD_CLIENTE, NOME, CPF_CNPJ, TIPO_PESSOA, LOGRADOURO, NUMERO, BAIRRO, CIDADE, UF, COMPLEMENTO, REFERENCIA, CEP, PRODUTO, GRADE, QTD, VLR_VENDA, IND_PROCESSADO FROM TR_PEDIDO WHERE 1 = 1 AND (IND_PROCESSADO = ''N'' OR IND_PROCESSADO IS NULL) ORDER BY PEDIDO, PRODUTO' WHERE TABELA_REFERENCIA = 'TR_PEDIDO';

ALTER TABLE TR_NOTA_FISCAL_ENTRADA ADD ID NUMBER(10,0);

CREATE SEQUENCE SQ_TR_NF_ENTRADA;

CREATE OR REPLACE TRIGGER ID_TR_NOTA_FISCAL_ENTRADA
  BEFORE INSERT ON TR_NOTA_FISCAL_ENTRADA
  FOR EACH ROW
BEGIN
  SELECT SQ_TR_NF_ENTRADA.NEXTVAL
  INTO :NEW.ID
  FROM DUAL;
END;

UPDATE ACAO_INTEGRACAO SET DSC_QUERY = 'SELECT ID, COD_FORNECEDOR, COD_PRODUTO, NOM_FORNECEDOR, CPF_CNPJ, DSC_GRADE, INSCRICAO_ESTADUAL, NUM_NOTA_FISCAL, COD_SERIE_NOTA_FISCAL, TO_DATE(DAT_EMISSAO,''DD/MM/YYYY'') DAT_EMISSAO, TIPO_NOTA, DSC_PLACA_VEICULO, QTD_ITEM, VALOR_TOTAL, IND_PROCESSADO FROM TR_NOTA_FISCAL_ENTRADA WHERE 1 = 1 AND IND_PROCESSADO = ''N'' OR IND_PROCESSADO IS NULL ORDER BY NUM_NOTA_FISCAL, COD_SERIE_NOTA_FISCAL' WHERE TABELA_REFERENCIA = 'TR_NOTA_FISCAL_ENTRADA';

ALTER TABLE TR_PRODUTO ADD ID NUMBER(10,0);

CREATE SEQUENCE SQ_TR_PRODUTO;

CREATE OR REPLACE TRIGGER ID_TR_PRODUTO
  BEFORE INSERT ON TR_PRODUTO
  FOR EACH ROW
BEGIN
  SELECT SQ_TR_PRODUTO.NEXTVAL
  INTO :NEW.ID
  FROM DUAL;
END;

UPDATE ACAO_INTEGRACAO SET DSC_QUERY = 'SELECT DISTINCT ID, COD_PRODUTO, DESCRICAO_PRODUTO, CODIGO_CLASSE_NIVEL_1, DSC_CLASSE_NIVEL_1, CODIGO_CLASSE_NIVEL_2, DSC_CLASSE_NIVEL_2, CODIGO_FABRICANTE, DESCRICAO_FABRICANTE, DESCRICAO_EMBALAGEM, PESO_VARIAVEL, QTD_EMBALAGEM, COD_BARRAS, PESO_BRUTO_EMBALAGEM, ALTURA_EMBALAGEM, LARGURA_EMBALAGEM, PROFUNDIDADE_EMBALAGEM, CUBAGEM_EMBALAGEM, EMBALAGEM_ATIVA FROM TR_PRODUTO WHERE (IND_PROCESSADO = ''N'' OR IND_PROCESSADO IS NULL)' WHERE TABELA_REFERENCIA = 'TR_PRODUTO';

