INSERT INTO VERSAO (DTH, NUMERO_VERSAO, SCRIPT) VALUES (SYSDATE, '6.14','20-modelo-separacao.sql');

ALTER TABLE EXPEDICAO ADD COD_MODELO_SEPARACAO NUMBER(8) NULL;

INSERT INTO ACAO (COD_ACAO, DSC_ACAO, NOM_ACAO) VALUES (SQ_ACAO_01.NEXTVAL, 'Alterar modelo de separação', 'alterar-modelo-separacao');

INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO)
  VALUES (SQ_RECURSO_ACAO_01.NEXTVAL,
  (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO LIKE 'expedicao:onda-ressuprimento'),
  (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO LIKE 'alterar-modelo-separacao'),
  'Alterar Modelo de Separação na onda de ressuprimento');