INSERT INTO VERSAO (DTH, NUMERO_VERSAO, SCRIPT) VALUES (SYSDATE, '6.6.0','3-unidade-fracionavel.sql');

ALTER TABLE PRODUTO ADD (IND_FRACIONAVEL CHAR(1));
ALTER TABLE PRODUTO ADD (UNID_FRACAO VARCHAR(10));
UPDATE PRODUTO SET IND_FRACIONAVEL = 'N';