INSERT INTO VERSAO (DTH, NUMERO_VERSAO, SCRIPT) VALUES (SYSDATE, '6.6.0','4-kit.sql');


INSERT INTO PARAMETRO (COD_PARAMETRO, COD_CONTEXTO_PARAMETRO, DSC_PARAMETRO, DSC_TITULO_PARAMETRO, IND_PARAMETRO_SISTEMA, COD_TIPO_ATRIBUTO, DSC_VALOR_PARAMETRO)
  VALUES (SQ_PARAMETRO_01.NEXTVAL, 2, 'COD_INTEGRACAO_PEDIDOS_TELA_EXP', 'Código para integração de Pedidos tela Expedicao', 'S', 'A', 25);

UPDATE PARAMETRO SET DSC_TITULO_PARAMETRO = 'Código para integração de Pedidos tela Genérica' WHERE DSC_PARAMETRO = 'COD_INTEGRACAO_PEDIDOS';

INSERT INTO ACAO_INTEGRACAO (COD_ACAO_INTEGRACAO, COD_CONEXAO_INTEGRACAO, DSC_QUERY, COD_TIPO_ACAO_INTEGRACAO, IND_UTILIZA_LOG, DTH_ULTIMA_EXECUCAO, IND_EXECUCAO)
  VALUES (25, 2, 'SELECT CARGA, PLACA, PEDIDO, TIPO_PEDIDO, COD_PRACA, DSC_PRACA, COD_ROTA, DSC_ROTA, COD_CLIENTE, NOME, CPF_CNPJ, TIPO_PESSOA, LOGRADOURO, NUMERO, BAIRRO, CIDADE, UF, COMPLEMENTO, REFERENCIA, CEP, PRODUTO, GRADE, QTD, VLR_VENDA, IND_PROCESSADO FROM TR_PEDIDO WHERE 1 = 1 :where',
  602, 'S', SYSDATE, 'N');

ALTER TABLE ACAO_INTEGRACAO ADD (IND_TIPO_CONTROLE VARCHAR(1));
ALTER TABLE ACAO_INTEGRACAO ADD (TABELA_REFERENCIA VARCHAR(64));
ALTER TABLE TR_PEDIDO ADD (IND_PROCESSADO VARCHAR(1) DEFAULT 'N');

UPDATE ACAO_INTEGRACAO SET IND_TIPO_CONTROLE = 'F', TABELA_REFERENCIA = 'TR_PEDIDO' WHERE COD_ACAO_INTEGRACAO = 25;

UPDATE ACAO_INTEGRACAO SET DSC_QUERY = 'SELECT CARGA, PLACA, PEDIDO, TIPO_PEDIDO, COD_PRACA, DSC_PRACA, COD_ROTA, DSC_ROTA, COD_CLIENTE, NOME, CPF_CNPJ, TIPO_PESSOA, LOGRADOURO, NUMERO, BAIRRO, CIDADE, UF, COMPLEMENTO, REFERENCIA, CEP, PRODUTO, GRADE, QTD, VLR_VENDA, IND_PROCESSADO FROM TR_PEDIDO WHERE 1 = 1 AND IND_PROCESSADO = ''N'' OR IND_PROCESSADO IS NULL ORDER BY PEDIDO, PRODUTO' WHERE COD_ACAO_INTEGRACAO = 25;





-----------------------------------------------




ALTER TABLE TR_NOTA_FISCAL_ENTRADA ADD (IND_PROCESSADO VARCHAR(1) DEFAULT 'N');

INSERT INTO ACAO_INTEGRACAO (COD_ACAO_INTEGRACAO, COD_CONEXAO_INTEGRACAO, DSC_QUERY, COD_TIPO_ACAO_INTEGRACAO, IND_UTILIZA_LOG, DTH_ULTIMA_EXECUCAO, IND_EXECUCAO)
  VALUES (26, 2, 'SELECT COD_FORNECEDOR, COD_PRODUTO, NOM_FORNECEDOR, CPF_CNPJ, DSC_GRADE, INSCRICAO_ESTADUAL, NUM_NOTA_FISCAL, COD_SERIE_NOTA_FISCAL, TO_CHAR(DAT_EMISSAO,'||'''DD/MM/YYYY HH24:MI:SS'''||') DAT_EMISSAO, TIPO_NOTA, DSC_PLACA_VEICULO, QTD_ITEM, VALOR_TOTAL, IND_PROCESSADO FROM TR_NOTA_FISCAL_ENTRADA WHERE 1 = 1 :where',
  605, 'S', SYSDATE, 'N');

UPDATE ACAO_INTEGRACAO SET IND_TIPO_CONTROLE = 'F', TABELA_REFERENCIA = 'TR_NOTA_FISCAL_ENTRADA' WHERE COD_ACAO_INTEGRACAO = 26;

UPDATE ACAO_INTEGRACAO SET DSC_QUERY = 'SELECT COD_FORNECEDOR, COD_PRODUTO, NOM_FORNECEDOR, CPF_CNPJ, DSC_GRADE, INSCRICAO_ESTADUAL, NUM_NOTA_FISCAL, COD_SERIE_NOTA_FISCAL, TO_CHAR(DAT_EMISSAO,''DD/MM/YYYY'') DAT_EMISSAO, TIPO_NOTA, DSC_PLACA_VEICULO, QTD_ITEM, VALOR_TOTAL, IND_PROCESSADO FROM TR_NOTA_FISCAL_ENTRADA WHERE 1 = 1 AND IND_PROCESSADO = ''N'' OR IND_PROCESSADO IS NULL ORDER BY NUM_NOTA_FISCAL, COD_SERIE_NOTA_FISCAL' WHERE  COD_ACAO_INTEGRACAO = 26;

INSERT INTO PARAMETRO (COD_PARAMETRO, COD_CONTEXTO_PARAMETRO, DSC_PARAMETRO, DSC_TITULO_PARAMETRO, IND_PARAMETRO_SISTEMA, COD_TIPO_ATRIBUTO, DSC_VALOR_PARAMETRO)
  VALUES (SQ_PARAMETRO_01.NEXTVAL, 2, 'COD_INTEGRACAO_NOTAS_FISCAIS_TELA_ENTR', 'Código para integração de Notas Fiscais em tela Recebimento', 'S', 'A', 26);

UPDATE PARAMETRO SET DSC_TITULO_PARAMETRO = 'Código para integração de Notas Fiscais em tela Genérica' WHERE DSC_PARAMETRO = 'COD_INTEGRACAO_NOTAS_FISCAIS';

update acao_integracao set ind_tipo_controle = 'D' where ind_tipo_controle is null;

INSERT INTO SIGLA (COD_SIGLA, COD_TIPO_SIGLA, DSC_SIGLA, COD_REFERENCIA_SIGLA) VALUES (618, 70, 'KIT', 'K');
INSERT INTO SIGLA (COD_SIGLA, COD_TIPO_SIGLA, DSC_SIGLA, COD_REFERENCIA_SIGLA) VALUES (619, 70, 'VENDA_BALCAO', 'VB');
INSERT INTO SIGLA (COD_SIGLA, COD_TIPO_SIGLA, DSC_SIGLA, COD_REFERENCIA_SIGLA) VALUES (620, 70, 'SIMPLES_REMESSA', 'SR');

ALTER TABLE TR_PEDIDO
ADD DTH_INCLUSAO DATE DEFAULT SYSDATE
ADD DTH_PROCESSAMENTO DATE;
