INSERT INTO VERSAO (DTH, NUMERO_VERSAO, SCRIPT) VALUES (SYSDATE, '6.16.0','xx-ajustes-wilso.sql');

ALTER TABLE NOTA_FISCAL
  ADD (COD_TIPO_NOTA_FISCAL NUMBER(13,8));

INSERT INTO TIPO_SIGLA (COD_TIPO_SIGLA,DSC_TIPO_SIGLA,IND_SIGLA_SISTEMA) VALUES (80,'TIPO NOTA FISCAL','S');
INSERT INTO SIGLA (COD_SIGLA,COD_TIPO_SIGLA,DSC_SIGLA) VALUES (622,80,'ENTRADA_FORNECEDOR');
INSERT INTO SIGLA (COD_SIGLA,COD_TIPO_SIGLA,DSC_SIGLA) VALUES (623,80,'DEVOLUCAO_CLIENTE');

INSERT INTO PARAMETRO (COD_PARAMETRO, COD_CONTEXTO_PARAMETRO, DSC_PARAMETRO, DSC_TITULO_PARAMETRO, IND_PARAMETRO_SISTEMA, COD_TIPO_ATRIBUTO, DSC_VALOR_PARAMETRO) VALUES (SQ_PARAMETRO_01.NEXTVAL, (SELECT COD_CONTEXTO_PARAMETRO FROM CONTEXTO_PARAMETRO WHERE DSC_CONTEXTO_PARAMETRO = 'RECEBIMENTO'), 'ATUALIZAR_DATA_PICKING', 'Atualizar data do Picking em novos recebimentos de devolução(S/N)','N','A','N');
