<?php
echo $this->msg;
?>

<br>
<br>

<?php if ($this->tabela == true) {?>
    <legend><?php echo $this->norma[0]['dscProduto'] ?></legend>
    <table >
    <?php foreach ($this->norma as $norma) : ?>
        <tr>
            <td>Unidade: </td>
            <td>&nbsp;</td>
            <td><?php echo $norma['unidade']?></td>
        </tr>
        <tr>
            <td>Unitizador: </td>
            <td>&nbsp;</td>
            <td><?php echo $norma['unitizador']?></td>
        </tr>
        <tr>
            <td>Norma: </td>
            <td>&nbsp;</td>
            <td><?php echo $norma['lastro']. " x " . $norma['camadas'] . " = " . $norma['qtdNorma']?></td>
        </tr>
        <br>
        <tr>
            <?php if ($this->botaoConfirma == true) {?>
                <td><a class="btn reader dialogAjax"
                   href="<?php echo "/enderecamento/produto/confirmar-alteracao/id/" . $this->idRecebimento . "/codigo/" . $this->codProduto . "/grade/" . urlencode($this->grade) . '/norma/' . $norma['idNorma']?>">Confirmar</a></td>
            <?php }?>
        </tr>
        <tr><td><br></td></tr>
    <?php endforeach; ?>
</table>
<?php }?>

<br>

<?php //if ($this->botaoConfirma == true) {?>
<!--    <a class="btn reader dialogAjax"-->
<!--       href="--><?php //echo "/enderecamento/produto/confirmar-alteracao/id/" . $this->idRecebimento . "/codigo/" . $this->codProduto . "/grade/" . urlencode($this->grade) ?><!--">Confirmar</a>-->
<?php //}?>