<script>
    function gotoFinal(event) {
        if (event.which == 13 || event.keyCode == 13) {
            if (document.getElementById('etiquetas[etiquetaInicial]').value != "") {
                codBarrasFinal   = document.getElementById('etiquetas[etiquetaFinal]');
                if (codBarrasFinal) {
                    codBarrasFinal.focus();
                    if(event.preventDefault) {
                        event.preventDefault();
                    } else {
                        event.returnValue = false;
                    }
                }
            }
        }
        return true;
    }

    function gotoPessoa(event) {
        if (event.which == 13 || event.keyCode == 13) {
            if (document.getElementById('etiquetas[etiquetaFinal]').value != "") {
                pessoa   = document.getElementById('pessoa');
                if (pessoa) {
                    pessoa.focus();

                    if(event.preventDefault) {
                        event.preventDefault();
                    } else {
                        event.returnValue = false;
                    }
                }
            }
        }
        return true;
    }

    function gotoDadosPessoa(event) {

        var etiquetaInicial = $('#etiquetas-etiquetaInicial').val();
        var etiquetaFinal = $('#etiquetas-etiquetaFinal').val();
        etiquetaInicial = etiquetaInicial.substring(0,etiquetaInicial.length-1);
        etiquetaFinal = etiquetaFinal.substring(0,etiquetaFinal.length-1);

        var qtdEtiquetas = 0;
        if (etiquetaInicial != '' && etiquetaFinal != '') {
            qtdEtiquetas = etiquetaFinal - etiquetaInicial;
        }

        var action = '';
        var nome = '';
        var cpf = '';
        var quantidade = '';
        var tr = $('<tr>').addClass('gTResultSet');
        $.ajax({
            url: 'conferente-apontamento-separacao/cpf/'+$('#etiquetas-pessoa').val()+'/qtdEtiquetas/'+qtdEtiquetas,
            success: function (data) {
                nome += data[0]['NOM_PESSOA'];
                cpf += data[0]['NUM_CPF'];
                quantidade += data[0]['QUANTIDADE'];

                $('#tr').append(tr);
                $('#action').append(action);
                $('#nome').append(nome);
                $('#cpf').append(cpf);
                $('#quantidade').append(quantidade);
            }
        });
    }
</script>

<?php
echo $this->form;
echo $this->formMapaSeparacao;
?>
    <div id="exibe-pessoa-grid" class="grid">
        <table class="gTable ">
            <caption>Conferentes</caption>
            <tbody>
            <tr class ="gTTitle">
                <td></td>
                <td>Nome</td>
                <td>CPF</td>
                <td>Qtd. Etiquetas</td>
            </tr>
            <tr id="tr">
                <td id="action"></td>
                <td id="nome"></td>
                <td id="cpf"></td>
                <td id="quantidade"></td>
            </tr>
            </tbody>
        </table>
    </div>


