<?php

$temLote = $this->temLote;

if ($this->erro) {
    echo $this->erro;
} else {
    ?>
    <form id="formulario" enctype="application/x-www-form-urlencoded" accept-charset="UTF-8" method="post">
        <input type="hidden" name="uma" value="" id="uma">
        <fieldset id="fieldset-identification">
            <legend>Ler Código de Barras</legend>
            <div class="field">
                <input type="hidden" name="idVolume" id="idVolume" value="<?php echo $this->idVolume ?>" size="40" maxlength="100" style="width: 99%">
                <input type="hidden" name="idMapa" id="idMapa" value="<?php echo $this->idMapa ?>" size="40" maxlength="100" style="width: 99%">
                <input type="hidden" name="idExpedicao" id="idExpedicao" value="<?php echo $this->idExpedicao ?>" size="40" maxlength="100" style="width: 99%">
                <input type="hidden" name="cliente" id="cliente" value="<?php echo $this->idPessoa ?>" >
                <input type="hidden" name="exibeQtd" id="confereQtd" value="<?php echo $this->confereQtd ?>" >
                <input type="hidden" name="tipoDefaultEmbalado" id="tipoDefaultEmbalado" value="<?php echo $this->tipoDefaultEmbalado ?>" >
                <input type="hidden" name="utilizaQuebra" id="utilizaQuebra" value="<?php echo $this->utilizaQuebra ?>" >
                <input type="hidden" name="utilizaVolumePatrimonio" id="utilizaVolumePatrimonio" value="<?php echo $this->utilizaVolumePatrimonio ?>" >
                <input type="hidden" name="tipoQuebraVolume" id="tipoQuebraVolume" value="<?php echo $this->tipoQuebraVolume ?>" >
                <input type="hidden" name="criarVolsFinalCheckout" id="criarVolsFinalCheckout" value="<?php echo $this->criarVolsFinalCheckout ?>" >
                <input type="hidden" name="central" id="central" value="<?php echo $this->central ?>" >
                <input type="hidden" name="chekcout" id="chekcout" value="chekcout" >
            </div>
            <?php if ($this->confereQtd) : ?>
            <div class="field">
                <label for="qtd" class="field optional">*Qtd</label>
                <input type="text" name="qtd" id="qtd" size="7" maxlength="100" value="1" style="width: 80%">
            </div>
            <div class="field">
                <label for="codigoBarras" class="field required">*Código de Barras</label>
                <input type="text" name="codigoBarras" id="codigoBarras" class="focus" <?php if ($temLote) { ?> onkeydown="goToLote(event)" <?php } ?> size="40" maxlength="100" style="width: 99%">
            </div>
            <?php if ($temLote) { ?>
            <div class="field">
                <label for="lote" class="field required">*Lote</label>
                <input type="text" name="lote" id="lote" class="required"  onkeydown="redirectTo(event)" size="40" maxlength="100" style="width: 99%">
            </div>
            <?php } ?>
            <?php else : ?>
            <div class="field">
                <label for="codigoBarras" class="field optional">*Código de Barras</label>
                <input type="text" name="codigoBarras" id="codigoBarras" class="focus" size="40" <?php if ($temLote) { ?> onkeydown="goToLote(event)" <?php } ?> maxlength="100" style="width: 99%">
            </div>
            <?php if ($temLote) { ?>
            <div class="field">
                <label for="lote" class="field optional">*Lote</label>
                <input type="text" name="lote" id="lote" class="required"  onkeydown="redirectTo(event)" size="40" maxlength="100" style="width: 99%">
            </div>
            <?php } ?>
            <div class="field">
                <label for="qtd" class="field optional">*Qtd</label>
                <input type="text" name="qtd" id="qtd" size="7" maxlength="100" value="1" style="width: 80%">
            </div>
            <?php endif; ?>
            <input type="button" name="buscar-submit" id="buscar-submit" value="Conferir" class="btn gradientBtn">
            <?php if (!$this->separacaoEmbalado) : ?>
                <input style="width: 300px;" type="button" class="btn gradientBtn" onclick="window.location = '<?php echo '/mobile/expedicao/finalizar/idExpedicao/' . $this->idExpedicao . '/idMapa/' . $this->idMapa . '/mapa/S/checkout/1' ?>'" value="Finalizar">
                <input type="submit" class="btn gradientBtn" href="<?php echo '/mobile/expedicao/index/idCentral/' . $this->central ?>" value="Alt. Mapa">
            <?php endif; ?>
            <?php if ($this->idVolume != "") : ?>
                <legend>Volume: <?php echo $this->dscVolume ?></legend>
                <a class="btn gradientBtn" href="<?php echo '/mobile/expedicao/fecha-volume-patrimonio-mapa/idMapa/' . $this->idMapa . '/idExpedicao/' . $this->idExpedicao . '/idVolume/' . $this->idVolume ?>" >Fechar</a>
            <?php endif; ?>
            <?php if ($this->separacaoEmbalado) : ?>
                <?php if ($this->criarVolsFinalCheckout == 'S') : ?>
                <div class="field" id="divNVols">
                    <label for="nVols" class="field">Nº Volumes</label>
                    <input type="text" id="nVols" alt="number" class="required" size="10">
                </div>
                <?php endif; ?>
                <input type="button" style="margin-top:20px" class="btn gradientBtn" id="btnFechaCaixa" value="Fechar Caixa" />
            <?php endif; ?>

        </fieldset>
    </form>
    <div id="bloqued-os" style="display: none">
        <form id="bloqued-os-form" enctype="application/x-www-form-urlencoded" accept-charset="UTF-8" action="" method="post">
            <div>
                <fieldset>
                    <legend>Liberar Ordem de Serviço</legend>
                    <div class="field">
                        <label for="senha" class="field required">*Senha</label>
                        <input type="password" name="senha" id="senha" value="" class=" required focus" size="40" maxlength="100" style="width: 99%">
                    </div>
                    <input type="submit" name="submit" id="submit" value="Liberar Ordem de Serviço" class="btn">
                </fieldset>
            </div>
        </form>
    </div>
    <div style="text-align: center;font-size: 12px; color: #f14c4c; font-weight: bold;" id="error"></div>
    <div style="text-align: center;font-size: 12px; color: #19bd06; font-weight: bold;" id="success"></div>
    <div style="margin: 25px 17px 100px 17px;">
        <div style="margin-bottom: 10px;">
            <span style="font-size: 14px;color: #1c94c4;font-weight: bold; margin-left: 16%; margin-right: 32%;">PRODUTOS A CONFERIR</span>
            <span style="font-size: 14px;color: #1c94c4;font-weight: bold;">PRODUTOS CONFERIDOS</span>
        </div>
        <div id="conferir" class="boxConfer" style="float: left;">
            <?php
            if (is_array($this->produtos)) {
                foreach ($this->produtos as $key => $value) {
                    ?>
                    <p produto="<?php echo "$value[COD_PRODUTO]*+*$value[DSC_GRADE]*+*$value[DSC_LOTE]" ?>" style="color: rgba(132, 71, 28, 0.63); font-weight: bold; padding: 5px; margin-top: 10px; text-align: center;">
                        <?php
                        $strLote = (!empty($value['DSC_LOTE']) && $value['DSC_LOTE'] != \Wms\Domain\Entity\Produto\Lote::NCL) ?" Lote: '$value[DSC_LOTE]'" : "";
                        echo $value['COD_PRODUTO'] . ' - ' . $value['DSC_PRODUTO'] . $strLote;

                        ?>
                    </p>
                    <?php
                }
            }
            ?>
        </div>
        <div id="conferidos" class="boxConfer" style="float: right;">
            <?php
            $conferidos = array();
            if (is_array($this->produtos)) {
                foreach ($this->produtosConferidos as $key => $value) {
                    $codGradeLote = "$value[COD_PRODUTO]*+*$value[DSC_GRADE]*+*$value[DSC_LOTE]";
                    $background = $span = $quantidade = '';
                    if($value['QTD_SEPARAR'] != $value['QTD_CONFERIDA']){
                        $background = 'background: rgb(250, 208, 208);';
                        $span = '<span>'.$value['QTD_CONFERIDA_EMB'].'</span>';
                    }else{
                        $quantidade = $value['QUANTIDADE'];
                    }
                    $conferidos[$codGradeLote] = 1;
                    $strLote = (!empty($value['DSC_LOTE']) && $value['DSC_LOTE'] != \Wms\Domain\Entity\Produto\Lote::NCL) ?" Lote: '$value[DSC_LOTE]'" : "";
                    ?>
                    <p produto="<?php echo $codGradeLote ?>" style="<?php echo $background;?> color: rgba(132, 71, 28, 0.63); font-weight: bold; padding: 5px; text-align: center;margin-top: 10px; "><?php echo  $value['COD_PRODUTO'].' - '.$value['DSC_PRODUTO'].$strLote.' - '.$quantidade.' '.$span ?> </p>
                    <?php
                }
                foreach ($this->produtos as $key => $value) {
                    $codGradeLote = "$value[COD_PRODUTO]*+*$value[DSC_GRADE]*+*$value[DSC_LOTE]";
                    $strLote = (!empty($value['DSC_LOTE']) && $value['DSC_LOTE'] != \Wms\Domain\Entity\Produto\Lote::NCL) ?" Lote: '$value[DSC_LOTE]'" : "";
                    if(empty($conferidos[$codGradeLote])) {
                        ?>
                        <p produto="<?php echo $codGradeLote ?>"
                           style="color: rgba(132, 71, 28, 0.63); font-weight: bold; padding: 5px; text-align: center; display: none; margin-top: 10px;"><?php echo $value['COD_PRODUTO'] . ' - ' . $value['DSC_PRODUTO'] . $strLote . ' - ' ?>
                            <span></span> </p>
                        <?php
                    }
                }
            }
            ?>
        </div>
    </div>
    <?php
}
?>
<script>
    $('#codigoBarras').focus();
    $(document).keydown(function (e) {
        if (e.which == 113) {
            var qtd = $('#qtd');
            var lote = $('#lote');

            if (qtd && !qtd.is(":focus")) {
                qtd.focus();
                qtd.select();
                return false;
            } else if (lote && !lote.is(":focus")) {
                lote.focus();
                lote.select();
                return false;
            }
        }
    });

    <?php if ($temLote) { ?>
    var loteCodigoBarras = <?php echo $this->lotesCodBarras ?>;
    var desconsideraZeroEsquerda = <?php echo ($this->desconsideraZeroEsquerda) ? 'true': 'false' ?>;

    $("#lote").focus(function () {
        verificaCodBarras()
    });

    function goToLote( event ) {
        var result = true;
        if (event.which == 13 || event.keyCode == 13) {
            if (verificaCodBarras()) {
                var inptCodBarras = $("#codigoBarras");
                if (loteCodigoBarras[validaCodBarras(inptCodBarras.val())] instanceof Array) {
                    var lote = $('#lote');
                    if (lote) {
                        lote.focus();
                        lote.val("");
                    }
                } else {
                    return requestAjax(event, $("#qtd"), inptCodBarras);
                }
            }
            if (event.preventDefault) {
                event.preventDefault();
            } else {
                event.returnValue = false;
            }
        }
        return result;
    }

    function verificaCodBarras () {
        var elem = $('#codigoBarras');
        var result = true;
        if (elem.val() === "") {
            elem.focus();
            alert("Informe primeiro o código de barras do produto");
            result = false;
        } else {
            var check = validaCodBarras(elem.val());
            if (!check) {
                elem.focus();
                elem.val("");
                result = false;
            }
        }
        return result;
    }

    function validaCodBarras(codBarras) {
        if (desconsideraZeroEsquerda && codBarras.charAt(0) === '0') {
            codBarras = codBarras.substring(1);
        }
        if (codBarras in loteCodigoBarras) {
            return codBarras;
        } else {
            alert("Código de barras " + codBarras + " não esperado para este mapa");
            return false;
        }
    }

    function checkLoteByCodBarras(codBarras, loteBipado) {
        if (loteBipado !== "") {
            if ($.inArray(loteBipado, loteCodigoBarras[codBarras]) < 0) {
                alert("Lote " + loteBipado + " não esperado para este produto");
                return false;
            } else {
                return true;
            }
        } else {
            alert("Lote não informado!");
            return false;
        }
    }

    function redirectTo(event) {
        if (event.which == 13 || event.keyCode == 13) {
            var codBarras = $("#codigoBarras");
            var lote = $("#lote");
            var qtd = $("#qtd");
            var confereQtd = <?php echo ($this->confereQtd) ? "true" : "false" ?>;

            if (confereQtd) {
                requestAjax(event, qtd, codBarras);
            } else {
                if (verificacao(codBarras, lote)) {
                    qtd.select();
                }
            }
        }
        return false;
    }

    function verificacao (inptCodBarras, lote) {
        var result = true;
        var codBarras = validaCodBarras(inptCodBarras.val());
        if (codBarras) {
            if (loteCodigoBarras[codBarras] instanceof Array) {
                var checkLote = checkLoteByCodBarras(codBarras, lote.val());
                if (!checkLote) {
                    lote.val("").focus();
                }
                result = checkLote;
            }
        } else {
            inptCodBarras.val("").focus();
            result = false;
        }
        return result;
    }

    <?php  } else { ?>

    $("#codigoBarras").keydown(function (e) {
        if (e.which == 13) {
            $('#buscar-submit').click();
        }
    });
    <?php  } ?>

    $("#qtd").keydown(function (e) {
        if (e.which == 13) {
            $('#codigoBarras').focus();
            return false;
        }
    });

    function requestAjax(e, inputQtd, inputCodBarras) {
        <?php if ($temLote) { ?>
        var lote = $("#lote");
        <?php } ?>
        if (inputQtd.val() !== '' && inputCodBarras.val() !== "" <?php if ($temLote) { ?> && verificacao(inputCodBarras, lote) <?php } ?>) {
            var params = $('form').serialize();
            console.log(params);
            $.ajax({
                url: '<?php echo $this->url(array('module' => 'mobile', 'controller' => 'expedicao', 'action' => 'confere-produto-ajax')) ?>',
                data: params,
                async: false,
                type: 'post',
                success: function (data) {
                    if (data.retorno.resposta.length > 0) {
                        inputCodBarras.val("").focus();
                        inputQtd.val(1);
                        <?php if ($temLote) { ?>
                        lote.val("");
                        <?php } ?>
                        var error = "";
                        var success = "Quantidade conferida com sucesso";
                        if (data.retorno.resposta === 'error') {
                            error = data.retorno.message;
                            try {
                                playSound("/alarme.mp3");
                            } catch (e) {
                                alert(e);
                            }
                            success = "";
                        }  else if (data.retorno.resposta === 'bloqued_os') {
                            error = data.retorno.errorMsg + " " + data.retorno.warningMsg;
                            success = "";
                            playSound("/alarme.mp3");
                            $("#formulario").hide();
                            $("#bloqued-os").show();
                        } else {
                            playSound("/confirm2.mp3");
                            var produto = data.retorno.produto[0];
                            var codGradeLote = produto['codProduto'] + '*+*' + produto['dscGrade'] + '*+*' + produto['lote'];
                            var conferidos = $('#conferidos');
                            var conferido = conferidos.find('p[produto="' + codGradeLote +'"]');

                            if (conferido.is(":hidden")) {
                                conferido.show();
                            }
                            conferido.find('span').text(produto['qtdConferidaTotalEmb']);
                            console.log(produto);

                            if (data.retorno.message == 'checkout') {
                                $('#conferir').find('p[produto="' + codGradeLote +'"]').hide();
                                conferido.css('background','#f3f3f3');
                            }else{
                                conferido.css('background','#fad0d0');
                            }

                            conferidos.prepend(conferido);
                            error = "";

                            <?php if ($this->criarVolsFinalCheckout == 'S') : ?>
                                verifyShowNVals();
                            <?php endif; ?>

                        }
                        $("#error").html(error);
                        $("#success").html(success);
                    }
                }
            });
        }
        <?php if ($this->agrupaVolumes && $this->usaCaixaPadrao) : ?>
        $.ajax({
            url: '<?php echo $this->url(array('module' => 'expedicao', 'controller' => 'index', 'action' => 'get-count-volumes-consolidado-ajax' )) . "/idMapa/". $this->idMapa . '/cliente/' . $this->idPessoa?>',
            success: function (data) {
                $("span#counterVols").text(data);
            }
        });
        <?php endif; ?>
    }
    $("#bloqued-os-form").submit(function (e) {
        e.preventDefault();
        var inputPass = $("#senha");

        if (isEmpty(inputPass.val())){
            $.wmsDialogAlert({title: "Atenção", msg: "Senha de desbloqueio não informada!"})
            return false;
        }
        var params = {
            idExpedicao: $("#idExpedicao").val(),
            senha: inputPass.val(),
            checkout: true
        }
        $.ajax({
            url: '/mobile/expedicao/liberar-os',
            type: 'POST',
            data: params,
            success: function (data){
                if (data.retorno.status === 'ok') {
                    $("#success").html("OS Liberada!");
                    $("#error").html('');
                    $("#bloqued-os").hide();
                    $("#formulario").show();
                } else if(data.retorno.status === 'error') {
                    $.wmsDialogAlert({title:"Atenção", msg: data.retorno.msg})
                }
            }
        })
        inputPass.val("");
    })

    $('#buscar-submit').on('click', function (e) {
        var qtd = $("#qtd");
        if (qtd !== '') {
            var codBarras = $("#codigoBarras");
            requestAjax(e, qtd, codBarras);
            return false;
        }
    });

    $("#btnFechaCaixa").click(function () {
        let strNVols = "";
        <?php if ($this->criarVolsFinalCheckout == 'S') : ?>
        if (!checkTudoConferido()) {
            $.wmsDialogAlert({msg: "O modelo de separação exige que confira todos os produtos antes de fechar os volumes"});
            return false;
        }

        let nVols = $("#nVols").val();
        if (isEmpty(nVols) || parseInt(nVols) === 0) {
            $.wmsDialogAlert({msg: "Informe a quantidade de volumes que devem ser criados"});
            return false;
        }

        strNVols = "/nVols/" + nVols;
        <?php endif; ?>
        let strCpfEmbalador = "/cpfEmbalador/" + $("#cpfEmbalador").val().replace(/\D+/g, '');
        window.open('<?php echo '/mobile/expedicao/fecha-mapa-embalado/checkout/1/idMapa/' . $this->idMapa . '/idExpedicao/' . $this->idExpedicao . '/cliente/' . $this->idPessoa ?>' + strCpfEmbalador + strNVols, '_blanck')
    });

    <?php if ($this->criarVolsFinalCheckout == 'S') : ?>
    function checkTudoConferido() {
        let divConferir = $('#conferir');
        let divLines = divConferir.find('p').size();
        let divLinesHidded = divConferir.find('p:hidden').size();
        return (divLines === divLinesHidded)
    }

    function verifyShowNVals() {
        if (checkTudoConferido()) {
            $("#nVols").val("");
            $("#divNVols").show();
        } else {
            $("#divNVols").hide();
        }
    }

    $(document).ready(function () {
        verifyShowNVals();
    });

    <?php endif; ?>

    <?php if ($this->agrupaVolumes && $this->usaCaixaPadrao) : ?>
    $('#info').append('<p style="font-size: 12px; margin-top: 10px;"><?php echo "Volume pré calculado (<span id=\"counterVols\">$this->indexVol</span> de $this->MaxVolCliente) " ?></p>');
    <?php endif; ?>
</script>