<?php
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

echo $this->form;
$recarregar = $this->recarregar;
$idPessoa = $this->pessoa;
?>
<div id="produtos-mapa"></div>
<span id="dummy"></span>
<bgsound id="bgSoundId" loop="0" volume="100" />
<script>
    $('#codigoBarrasMapa').focus();
<?php
if ($recarregar == 1) {
    ?>
        $(window).load(function () {
            $(".buscar-mapa").click();
            <?php
            if ($idPessoa > 0) {
                ?>
                        setTimeout(function () {
                            $('input[cod_pessoa=<?php echo $idPessoa ?>]').click();
                        }, 2000);
                <?php
            }
            ?>
        });

    <?php
}
?>
function playSound(soundfile) {
    document.getElementById("dummy").innerHTML=
        "<embed src=\""+soundfile+"\" hidden=\"true\" autostart=\"true\" loop=\"false\" />";
}
    $(".buscar-mapa").click(function () {
        $.ajax({
            url: URL_MODULO + '/index/confirmar-cliente-ajax',
            type: 'post',
            dataType: 'html',
            data: $('form').serialize(),
            success: function (data) {
                $('#info').remove();
                $('#produtos-mapa').html(data);
                $(".cliente-btn").click(function () {
                    $('#checkout-expedicao').append($('#form-clientes').find('#idExpedicao'));
                    $('#checkout-expedicao').append('<input type="hidden" id="cod_pessoa" name="cod_pessoa" value="' + $(this).attr('cod_pessoa') + '" />');
                    $('#fieldset-identificacao').prepend('<div id="info" class="field" style=" color: rgba(208, 105, 33, 0.88); margin-top: 15px; float: right; margin-left: 30px; font-size: 12px; font-weight: bold; text-align: center;">\n\
                    <p style="font-size: 12px;">' + $(this).val() + '</p></div>');

                    $('#form-clientes').remove();
                    $.ajax({
                        url: URL_MODULO + '/index/carrega-mapa-ajax',
                        type: 'post',
                        dataType: 'html',
                        data: $('#checkout-expedicao').serialize(),
                        success: function (data) {
                            $('#produtos-mapa').html(data);
                            $('#buscar-sumbit').on('click', function (e) {
                                var qtd = $("#qtd");
                                if (qtd !== '') {
                                    $.ajax({
                                        url: '<?php echo $this->url(array('module' => 'mobile', 'controller' => 'expedicao', 'action' => 'confere-produto-ajax')) ?>',
                                        data: $('form').serialize(),
                                        async: false,
                                        type: 'post',
                                        success: function (data) {
                                            $('#codigoBarras').focus();
                                            if (data.retorno.resposta.length > 0) {
                                                $("#codigoBarras").val("").focus();
                                                var error = "";
                                                var success = "Quantidade conferida com sucesso";
                                                if (data.retorno.resposta == 'error') {
                                                    error = data.retorno.message;
                                                    try {
                                                        playSound("/alarme.mp3");
                                                    } catch (e) {
                                                        alert(e);
                                                    }
                                                    success = "";
                                                } else {

                                                    playSound("/confirm2.mp3");
                                                    $('#conferidos').find('p[produto="' + data.retorno.produto[0]['codProduto'] + '-'+data.retorno.produto[0]['dscGrade'] +'"]').show();
                                                    $('#conferidos').find('p[produto="' + data.retorno.produto[0]['codProduto'] + '-'+data.retorno.produto[0]['dscGrade'] +'"] #qtd').text(data.retorno.produto[0]['qtdConferidaTotalEmb']);
                                                    if (data.retorno.message == 'checkout') {
                                                        $('#conferir').find('p[produto="' + data.retorno.produto[0]['codProduto'] + '-'+data.retorno.produto[0]['dscGrade'] +'"]').hide();
                                                        $('#conferidos').find('p[produto="' + data.retorno.produto[0]['codProduto'] + '-'+data.retorno.produto[0]['dscGrade'] +'"]').css('background','#f3f3f3');;
                                                    }else{
                                                        $('#conferidos').find('p[produto="' + data.retorno.produto[0]['codProduto'] + '-'+data.retorno.produto[0]['dscGrade'] +'"]').css('background','#fad0d0');;
                                                    }
                                                    error = "";
                                                }
                                                $("#error").html(error);
                                                $("#success").html(success);
                                            }
                                            $(".item-lista").remove();
                                        }
                                    });
                                    $('#codigoBarras').focus();
                                    qtd.val(1);
                                    return false;
                                }
                            });
                        }
                    });
                    return false;
                });
            }
        });
        return false;
    });

</script>