<form id="" method="post" class="saveForm" action="<?php echo $this->url(array('module' => 'expedicao', 'controller' => 'index', 'action' => 'desagruparcarga')) ?>">
    <div>
        <label for="placa">Placa: </label>
        <input type="text" class="input-mini" id="placa" name="placa">

        <input type="submit" style="margin-bottom: 15px" name="salvar" value="Salvar" id="submit" class="btn">
    </div>
</form>