<?php
echo $this->form;
echo $this->grid;
?>
<script src="/javascript/corteJs.js"></script>


<script>

    $('.cancelar').click(function () {
        if (!confirm('Deseja Realmente cancelar a expedicao?')) {
            return false;
        }
    });

    $('.habilitar-corte').click(function () {
        if (!confirm('Deseja realmente habilitar os cortes no ERP para esta expedicao?')) {
            return false;
        }
    });


</script>