INSERT INTO CONEXAO_INTEGRACAO (COD_CONEXAO_INTEGRACAO, DSC_CONEXAO_INTEGRACAO, SERVIDOR, PORTA, USUARIO, SENHA, DBNAME, PROVEDOR)
 VALUES (1,'INTEGRACAO DE PRODUTOS','localhost','1521','wms_linhares','wms_adm','xe', 'ORACLE');

/* Integrações de Resumo da Conferencia*/
INSERT INTO ACAO_INTEGRACAO (COD_ACAO_INTEGRACAO, COD_CONEXAO_INTEGRACAO, DSC_QUERY, COD_TIPO_ACAO_INTEGRACAO,IND_UTILIZA_LOG,DTH_ULTIMA_EXECUCAO)
 VALUES (1,1,'SELECT * FROM PRODUTO',600,'S',null);

/* Integrações de Produtos*/
INSERT INTO ACAO_INTEGRACAO (COD_ACAO_INTEGRACAO, COD_CONEXAO_INTEGRACAO, DSC_QUERY, COD_TIPO_ACAO_INTEGRACAO,IND_UTILIZA_LOG,DTH_ULTIMA_EXECUCAO)
 VALUES (1,1,'select p.codprod as COD_PRODUTO, p.descricao as DESCRICAO_PRODUTO, d.codepto as CODIGO_CLASSE_NIVEL_1, d.descricao as DSC_CLASSE_NIVEL_1, sec.codsec as CODIGO_CLASSE_NIVEL_2, sec.descricao as DSC_CLASSE_NIVEL_2, p.codfornec as CODIGO_FABRICANTE, f.fornecedor as DESCRICAO_FABRICANTE, e.unidade as DESCRICAO_EMBALAGEM, p.pesovariavel as PESO_VARIAVEL, e.qtunit as QTD_EMBALAGEM, e.codauxiliar as COD_BARRAS, e.pesobruto as PESO_BRUTO_EMBALAGEM, e.altura as ALTURA_EMBALAGEM, e.largura as LARGURA_EMBALAGEM, e.comprimento as PROFUNDIDADE_EMBALAGEM, e.volume as CUBAGEM_EMBALAGEM, decode (p.obs2,' || '''FL''' || ',' || '''N''' | |','|| '''S''' || ') as EMBALAGEM_ATIVA from pcprodut p, pcembalagem e, pcdepto d, pcsecao sec, pcfornec f where p.codprod = e.codprod and d.codepto = p.codepto and sec.codsec = p.codsec and f.codfornec = p.codfornec and e.codfilial = :codFilial and p.dtultaltcom >= :dthExecucao order by p.codprod',600,'S',null);

/* Integrações de Envio do Estoque*/
INSERT INTO ACAO_INTEGRACAO (COD_ACAO_INTEGRACAO, COD_CONEXAO_INTEGRACAO, DSC_QUERY, COD_TIPO_ACAO_INTEGRACAO,IND_UTILIZA_LOG,DTH_ULTIMA_EXECUCAO)
 VALUES (2,1,'SELECT E.COD_PRODUTO, SUM(E.QTD) as ESTOQUE_GERENCIAL, SUM(E.QTD) as ESTOQUE_DISPONIVEL, SUM(E.QTD) as VALOR_ESTOQUE, 1 as CUSTO_UNITARIO, 1 as UNIDADE_VENDA, ' || '''FD''' ||' as DSC_UNIDADE FROM ESTOQUE E GROUP BY COD_PRODUTO',601,'S',null);

/* Integrações de Envio de Pedidos*/
 INSERT INTO ACAO_INTEGRACAO (COD_ACAO_INTEGRACAO, COD_CONEXAO_INTEGRACAO, DSC_QUERY, COD_TIPO_ACAO_INTEGRACAO,IND_UTILIZA_LOG,DTH_ULTIMA_EXECUCAO)
 VALUES (3,1,'SELECT C.COD_CARGA_EXTERNO as CARGA, C.DSC_PLACA_CARGA as PLACA, P.COD_PEDIDO as PEDIDO, null as COD_PRACA, null as DSC_PRACA, IT.COD_ITINERARIO as COD_ROTA, IT.DSC_ITINERARIO as DSC_ROTA, C.COD_CLIENTE_EXTERNO as COD_CLIENTE, PES.NOM_PESSOA as NOME, NVL(PF.NUM_CPF,PJ.NUM_CNPJ) as CPF_CNPJ, PES.COD_TIPO_PESSOA as TIPO_PESSOA, PE.DSC_ENDERECO as LOGRADOURO, PE.NUM_ENDERECO as NUMERO, PE.NOM_BAIRRO as BAIRRO, PE.NOM_LOCALIDADE as CIDADE, UF.COD_REFERENCIA_SIGLA as UF, PE.DSC_COMPLEMENTO as COMPLEMENTO, PE.DSC_PONTO_REFERENCIA as REFERENCIA, PE.NUM_CEP as CEP, PP.COD_PRODUTO as PRODUTO, PP.DSC_GRADE as GRADE, PP.QUANTIDADE as QTD, PP.VALOR_VENDA FROM CARGA C LEFT JOIN PEDIDO P ON P.COD_CARGA = C.COD_CARGA LEFT JOIN PEDIDO_ENDERECO PE ON PE.COD_PEDIDO = P.COD_PEDIDO LEFT JOIN ITINERARIO IT ON IT.COD_ITINERARIO = P.COD_ITINERARIO LEFT JOIN CLIENTE C ON C.COD_PESSOA = P.COD_PESSOA LEFT JOIN PESSOA PES ON PES.COD_PESSOA = C.COD_PESSOA LEFT JOIN PESSOA_FISICA PF ON PF.COD_PESSOA = PES.COD_PESSOA LEFT JOIN PESSOA_JURIDICA PJ ON PJ.COD_PESSOA = PES.COD_PESSOA LEFT JOIN SIGLA UF ON UF.COD_SIGLA = PE.COD_UF LEFT JOIN PEDIDO_PRODUTO PP ON PP.COD_PEDIDO = P.COD_PEDIDO WHERE C.COD_CARGA = 7004 ORDER BY C.COD_CARGA, P.COD_PEDIDO',602,'S',null);

/* Integrações de Resumo da Conferencia*/
INSERT INTO ACAO_INTEGRACAO (COD_ACAO_INTEGRACAO, COD_CONEXAO_INTEGRACAO, DSC_QUERY, COD_TIPO_ACAO_INTEGRACAO,IND_UTILIZA_LOG,DTH_ULTIMA_EXECUCAO)
 VALUES (4,1,'SELECT C.COD_CARGA_EXTERNO as CARGA, SUM(PP.QUANTIDADE - NVL(pp.QTD_CORTADA,0)) as QTD FROM PEDIDO_PRODUTO PP LEFT JOIN PEDIDO P ON P.COD_PEDIDO = PP.COD_PEDIDO LEFT JOIN CARGA C ON C.COD_CARGA = P.COD_CARGA WHERE C.COD_CARGA_EXTERNO = :?1 GROUP BY COD_CARGA_EXTERNO',603,'S',null);

/* Integrações do Detalhamento da Conferencia*/
INSERT INTO ACAO_INTEGRACAO (COD_ACAO_INTEGRACAO, COD_CONEXAO_INTEGRACAO, DSC_QUERY, COD_TIPO_ACAO_INTEGRACAO,IND_UTILIZA_LOG,DTH_ULTIMA_EXECUCAO)
 VALUES (5,1,'SELECT C.COD_CARGA_EXTERNO as CARGA, P.COD_PEDIDO as PEDIDO, PP.COD_PRODUTO as PRODUTO, PP.DSC_GRADE as GRADE, SUM(PP.QUANTIDADE - NVL(pp.QTD_CORTADA,0)) as QTD FROM PEDIDO_PRODUTO PP LEFT JOIN PEDIDO P ON P.COD_PEDIDO = PP.COD_PEDIDO LEFT JOIN CARGA C ON C.COD_CARGA = P.COD_CARGA WHERE C.COD_CARGA_EXTERNO = :?1 GROUP BY COD_CARGA_EXTERNO, P.COD_PEDIDO, PP.COD_PRODUTO, PP.DSC_GRADE',604,'S',null);
