/*
 * INTEGRAÇÃO DE PRODUTOS
 */
INSERT INTO ACAO_INTEGRACAO (COD_ACAO_INTEGRACAO, COD_CONEXAO_INTEGRACAO, DSC_QUERY, COD_TIPO_ACAO_INTEGRACAO,IND_UTILIZA_LOG,DTH_ULTIMA_EXECUCAO)
VALUES (1,1,
        'SELECT DATE_FORMAT(NOW(), ''%d/%m/%Y %H:%i:%s'') AS DTH,  a.es1_cod AS COD_PRODUTO, ''UNICA'' AS DSC_GRADE, b.es1_desc AS DESCRICAO_PRODUTO, IF (b.es1_familia = 0, 9999 , b.es1_familia) AS CODIGO_CLASSE_NIVEL_1, f.tab_desc AS DSC_CLASSE_NIVEL_1, b.es1_departamento AS CODIGO_CLASSE_NIVEL_2, d.tab_desc AS DSC_CLASSE_NIVEL_2, b.es1_secao AS CODIGO_CLASSE_NIVEL_3, s.tab_desc AS DSC_CLASSE_NIVEL_3, b.es1_categoria AS CODIGO_CLASSE_NIVEL_4, g.tab_desc AS DSC_CLASSE_NIVEL_4, IF (a.cg2_cod = 0, 999999, a.cg2_cod) AS CODIGO_FABRICANTE, c.cg2_nome AS DESCRICAO_FABRICANTE, emb.es1_umvenda AS DESCRICAO_EMBALAGEM,  IF(a.es1_pesavel = 1,''S'',''N'') AS PESO_VARIAVEL, emb.es1_qtvenda AS QTD_EMBALAGEM, emb.es1_codbarra AS COD_BARRAS, w.es1_altura AS ALTURA_EMBALAGEM, w.es1_largura AS LARGURA_EMBALAGEM, w.es1_profundidade AS PROFUNDIDADE_EMBALAGEM, ''S'' AS EMBALAGEM_ATIVA, ''N'' as POSSUI_VALIDADE, NULL AS DIAS_VIDA_UTIL, 1 AS CUBAGEM_EMBALAGEM, 1 AS PESO_BRUTO_EMBALAGEM FROM sglinx.es1 a INNER JOIN sglinx.es1p b ON b.es1_cod = a.es1_cod LEFT JOIN sglinx.es1a emb ON emb.es1_cod = a.es1_cod LEFT JOIN sglinx.st_familia f ON f.tab_cod = b.es1_familia LEFT JOIN sglinx.st_departamento d ON d.tab_cod = b.es1_departamento LEFT JOIN sglinx.st_secao s ON s.tab_cod = b.es1_secao LEFT JOIN sglinx.st_categoria g ON g.tab_cod = b.es1_categoria LEFT JOIN sglinx.es1w w ON w.es1_cod = a.es1_cod AND w.es1_empresa = a.es1_empresa LEFT JOIN sglinx.cg2 c ON c.cg2_cod = a.cg2_cod WHERE a.es1_empresa = 1 and :where ',
        600,'S',null);

INSERT INTO ACAO_INTEGRACAO_FILTRO (COD_ACAO_INTEGRACAO_FILTRO, COD_ACAO_INTEGRACAO, COD_TIPO_REGISTRO, DSC_FILTRO)
  VALUES (SQ_ACAO_INTEGRACAO_FILTRO_01.NEXTVAL, 1, 610, ' and a.es1_dtalteracao >=  '' :?1 '' ');

INSERT INTO ACAO_INTEGRACAO_FILTRO (COD_ACAO_INTEGRACAO_FILTRO, COD_ACAO_INTEGRACAO, COD_TIPO_REGISTRO, DSC_FILTRO)
  VALUES (SQ_ACAO_INTEGRACAO_FILTRO_01.NEXTVAL, 1, 611, ' AND a.es1_cod = :?1  ');

INSERT INTO ACAO_INTEGRACAO_FILTRO (COD_ACAO_INTEGRACAO_FILTRO, COD_ACAO_INTEGRACAO, COD_TIPO_REGISTRO, DSC_FILTRO)
  VALUES (SQ_ACAO_INTEGRACAO_FILTRO_01.NEXTVAL, 1, 612, ' AND a.es1_cod IN (:?1) ');

INSERT INTO ACAO_INTEGRACAO_FILTRO (COD_ACAO_INTEGRACAO_FILTRO, COD_ACAO_INTEGRACAO, COD_TIPO_REGISTRO, DSC_FILTRO)
  VALUES (SQ_ACAO_INTEGRACAO_FILTRO_01.NEXTVAL, 1, 613, ' AND a.es1_cod BETWEEN :?1 AND :?2 ');


/*
 * ESTOQUE
 */
INSERT INTO ACAO_INTEGRACAO (COD_ACAO_INTEGRACAO, COD_CONEXAO_INTEGRACAO, DSC_QUERY, COD_TIPO_ACAO_INTEGRACAO,IND_UTILIZA_LOG,DTH_ULTIMA_EXECUCAO)
VALUES (2,1,
        'select e.codprod as COD_PRODUTO, e.qtestger as ESTOQUE_GERENCIAL, sum(e.qtestger-e.qtreserv-e.qtbloqueada) as ESTOQUE_DISPONIVEL, trunc(sum(e.qtestger*e.custoultent),2) VALOR_ESTOQUE, trunc(e.custoultent,2) CUSTO_UNITARIO, p.qtunit FATOR_UNIDADE_VENDA, p.unidade DSC_UNIDADE from pcest e, pcprodut p where e.codprod=p.codprod and e.codfilial=:codFilial group by e.codprod,e.qtestger,e.custoultent,p.qtunit,p.unidade',
        601,'S',null);

/*
 * PEDIDOS
 */

INSERT INTO ACAO_INTEGRACAO (COD_ACAO_INTEGRACAO, COD_CONEXAO_INTEGRACAO, DSC_QUERY, COD_TIPO_ACAO_INTEGRACAO,IND_UTILIZA_LOG,DTH_ULTIMA_EXECUCAO)
VALUES (3,1,
        'SELECT DATE_FORMAT(NOW(), ''%d/%m/%Y %H:%i:%s'') AS DTH, CONCAT(cm11.cm11_empresa,cm11.cm11_num) AS CARGA, CONCAT(cm11.cm11_empresa,cm11.cm11_num) AS PLACA, CONCAT(cm11.cm11_empresa,cm11.cm11_num) AS PEDIDO, 1 AS COD_ROTA, ''PADRAO'' AS DSC_ROTA, cm11.cm11_empresa AS COD_CLIENTE, e.emp_razao AS NOME, e.emp_cgc AS CPF_CNPJ, ''J'' AS TIPO_PESSOA, e.emp_endereco AS LOGRADOURO, e.emp_numero AS NUMERO, e.emp_bairro AS BAIRRO, e.emp_cidade CIDADE, e.emp_uf AS UF, e.emp_complemento AS COMPLEMENTO, NULL AS REFERENCIA, e.emp_cep AS CEP, cm11a.es1_cod AS PRODUTO, ''UNICA'' AS GRADE, cm11a.cm11_quant AS QTD, (cm11a.cm11_quant * cm11a.cm11_prcompra - cm11a.CM11_VLDESC1) AS VLR_VENDA FROM sglinx.cm11a INNER JOIN sglinx.cm11 ON cm11.cm11_num = cm11a.cm11_num AND cm11.cm11_empresa = cm11a.cm11_empresa INNER JOIN sglinx.empresa e on cm11.cm11_empresa = e.emp_codigo WHERE cm11.cmd_num in (''Aberto'',''Parcial'') and cm11.cg2_cod = 15 :where',
        602,'S',null);

INSERT INTO ACAO_INTEGRACAO_FILTRO (COD_ACAO_INTEGRACAO_FILTRO, COD_ACAO_INTEGRACAO, COD_TIPO_REGISTRO, DSC_FILTRO)
  VALUES (SQ_ACAO_INTEGRACAO_FILTRO_01.NEXTVAL, 3, 610, ' cm11.cm11_data >= STR_TO_DATE( '' :?1 '', ''%Y-%m-%d'') ');

INSERT INTO ACAO_INTEGRACAO_FILTRO (COD_ACAO_INTEGRACAO_FILTRO, COD_ACAO_INTEGRACAO, COD_TIPO_REGISTRO, DSC_FILTRO)
  VALUES (SQ_ACAO_INTEGRACAO_FILTRO_01.NEXTVAL, 3, 611, ' AND pv1.pv1_cod = :?1  ');

INSERT INTO ACAO_INTEGRACAO_FILTRO (COD_ACAO_INTEGRACAO_FILTRO, COD_ACAO_INTEGRACAO, COD_TIPO_REGISTRO, DSC_FILTRO)
  VALUES (SQ_ACAO_INTEGRACAO_FILTRO_01.NEXTVAL, 3, 612, ' AND pv1.pv1_cod IN (:?1) ');

INSERT INTO ACAO_INTEGRACAO_FILTRO (COD_ACAO_INTEGRACAO_FILTRO, COD_ACAO_INTEGRACAO, COD_TIPO_REGISTRO, DSC_FILTRO)
  VALUES (SQ_ACAO_INTEGRACAO_FILTRO_01.NEXTVAL, 3, 613, ' AND pv1.pv1_cod BETWEEN :?1 AND :?2 ');


/*
 * CONFERENCIA DE EXPEDICAO
 */
INSERT INTO ACAO_INTEGRACAO (COD_ACAO_INTEGRACAO, COD_CONEXAO_INTEGRACAO, DSC_QUERY, COD_TIPO_ACAO_INTEGRACAO,IND_UTILIZA_LOG,DTH_ULTIMA_EXECUCAO)
VALUES (4,1,
        'SELECT C.COD_CARGA_EXTERNO as CARGA, SUM(PP.QUANTIDADE - NVL(pp.QTD_CORTADA,0)) as QTD FROM PEDIDO_PRODUTO PP LEFT JOIN PEDIDO P ON P.COD_PEDIDO = PP.COD_PEDIDO LEFT JOIN CARGA C ON C.COD_CARGA = P.COD_CARGA WHERE C.COD_CARGA_EXTERNO = :?1 GROUP BY COD_CARGA_EXTERNO',
        603,'S',null);

INSERT INTO ACAO_INTEGRACAO (COD_ACAO_INTEGRACAO, COD_CONEXAO_INTEGRACAO, DSC_QUERY, COD_TIPO_ACAO_INTEGRACAO,IND_UTILIZA_LOG,DTH_ULTIMA_EXECUCAO)
VALUES (5,1,
        'SELECT C.COD_CARGA_EXTERNO as CARGA, P.COD_PEDIDO as PEDIDO, PP.COD_PRODUTO as PRODUTO, PP.DSC_GRADE as GRADE, SUM(PP.QUANTIDADE - NVL(pp.QTD_CORTADA,0)) as QTD FROM PEDIDO_PRODUTO PP LEFT JOIN PEDIDO P ON P.COD_PEDIDO = PP.COD_PEDIDO LEFT JOIN CARGA C ON C.COD_CARGA = P.COD_CARGA WHERE C.COD_CARGA_EXTERNO = :?1 GROUP BY COD_CARGA_EXTERNO, P.COD_PEDIDO, PP.COD_PRODUTO, PP.DSC_GRADE',
        604,'S',null);

/*
 * NOTA FISCAL DE ENTRADA
 */

INSERT INTO ACAO_INTEGRACAO (COD_ACAO_INTEGRACAO, COD_CONEXAO_INTEGRACAO, DSC_QUERY, COD_TIPO_ACAO_INTEGRACAO,IND_UTILIZA_LOG,DTH_ULTIMA_EXECUCAO)
VALUES (6,1,
        'SELECT DATE_FORMAT(NOW(), ''%d/%m/%Y %H:%i:%s'') AS DTH, cmd.cg2_cod AS COD_FORNECEDOR, IF(cg2.cg2_tipopessoa = ''J'',cg2.cg2_cgc, cg2.cg2_cpf) AS CPF_CNPJ, IF(cg2.cg2_tipopessoa = ''J'',cg2.cg2_inscestad, cg2.cg2_rg) AS INSCRICAO_ESTADUAL, cg2.cg2_nome AS NOM_FORNECEDOR, cmd.cmd_num AS NUM_NOTA_FISCAL, cmd.cmd_serie AS COD_SERIE_NOTA_FISCAL, DATE_FORMAT(cmd.cmd_emissao, ''%d/%m/%Y'')  AS DAT_EMISSAO, cmd.cmd_placa AS DSC_PLACA_VEICULO, cma.es1_cod AS COD_PRODUTO, ''UNICA'' AS DSC_GRADE, cma.cma_quant AS QTD_ITEM, cma.cma_vtotal AS VLR FROM sglinx.CMD INNER JOIN sglinx.cma ON cma.cmd_num = cmd.cmd_num AND cma.cmd_serie = cmd.cmd_serie AND cma.cg2_cod = cmd.cg2_cod AND cma.cmd_empresa = cmd.cmd_empresa AND cma.cmd_modelo = cmd.cmd_modelo AND cma.cmd_emissao = cmd.cmd_emissao INNER JOIN sglinx.cg2 ON cg2.cg2_cod = cmd.cg2_cod WHERE 1 = 1 :where AND cmd.cmd_tipo IN ( 1, 3, 8, 11, 26, 47, 51, 56, 59)',
        605,'S',null);

INSERT INTO ACAO_INTEGRACAO_FILTRO (COD_ACAO_INTEGRACAO_FILTRO, COD_ACAO_INTEGRACAO, COD_TIPO_REGISTRO, DSC_FILTRO)
  VALUES (SQ_ACAO_INTEGRACAO_FILTRO_01.NEXTVAL, 6, 610, ' AND STR_TO_DATE(cmd.cmd_dtent, ''%Y-%m-%d'') >= STR_TO_DATE( '' :?1 '', ''%Y-%m-%d'')');

INSERT INTO ACAO_INTEGRACAO_FILTRO (COD_ACAO_INTEGRACAO_FILTRO, COD_ACAO_INTEGRACAO, COD_TIPO_REGISTRO, DSC_FILTRO)
  VALUES (SQ_ACAO_INTEGRACAO_FILTRO_01.NEXTVAL, 6, 611, ' AND cmd.cmd_num = :?1  ');

INSERT INTO ACAO_INTEGRACAO_FILTRO (COD_ACAO_INTEGRACAO_FILTRO, COD_ACAO_INTEGRACAO, COD_TIPO_REGISTRO, DSC_FILTRO)
  VALUES (SQ_ACAO_INTEGRACAO_FILTRO_01.NEXTVAL, 6, 612, ' AND cmd.cmd_num IN (:?1) ');

INSERT INTO ACAO_INTEGRACAO_FILTRO (COD_ACAO_INTEGRACAO_FILTRO, COD_ACAO_INTEGRACAO, COD_TIPO_REGISTRO, DSC_FILTRO)
  VALUES (SQ_ACAO_INTEGRACAO_FILTRO_01.NEXTVAL, 6, 613, ' AND cmd.cmd_num BETWEEN :?1 AND :?2 ');
