INSERT INTO VERSAO (DTH, NUMERO_VERSAO, SCRIPT) VALUES (SYSDATE, '7.12', '04-qtd-reservada_original.sql');

ALTER TABLE RESERVA_ESTOQUE_PRODUTO ADD QTD_RESERVADA_ORIGINAL NUMBER(13,3);

UPDATE RESERVA_ESTOQUE_PRODUTO SET QTD_RESERVADA_ORIGINAL = QTD_RESERVADA;