<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Abertura de Chamados</title>

</head>

<body>
<div class="container">
    <br>

    <form class="form-horizontal" name="logo" method="POST" action="<?php echo '/filial/logomarca' ?>" enctype="multipart/form-data">
        <fieldset>

            <!-- Título do formulário -->
            <legend>Logomarca</legend>

            <!-- Campo: logomarca -->
            <div class="form-group">

                <div class="col-md-4">
                    <input size="60" id="arquivo" name="arquivo" class="input-file" type="file" required="">
                    <span class="help-block">Somente arquivos com extensão JPEG</span>
                </div>
            </div>

            <!-- Botão Enviar -->
                <div class="form-group">
                    <label class="col-md-4 control-label" for="submit"></label>
                    <div class="col-md-4">
                        <button type="submit" name="submit" class="btn btn-inverse">Enviar</button>
                    </div>
                </div>

        </fieldset>
    </form>

</div>
</body>
</html>

