<style>
    <!--
    fieldset#fieldset-modelo{
        display: inline;
        width: 947px;
    }

    div.checkboxes {
        margin-bottom: 10px;
    }

    div.fieldsets {
        width: 650px;
    }

    div.fieldset-left {
        width: 320px;
        float: left;
    }

    div.fieldset-right {
        width: 320px;
        float: right;
    }

    #fieldset-modelo input.error {
        border-color: #F00;
    }
    #fieldset-modelo select.error {
        border-color: #F00;
    }
    #fieldset-modelo label.error {
        display:none !important;
    }

    form fieldset div.field {
        display: block;
        float: none;
        margin-right: 20px;
        min-height: auto;
    }

    form fieldset div.checkbox {
        display: inline-block;
        float: none;
    }

    form fieldset div.checkbox label {
        margin: 0 0 0 5px;
    }
    -->
</style>
<form id="modelo-inventario-form" class="saveForm" method="post" action="" enctype="application/x-www-form-urlencoded" novalidate="novalidate">
    <fieldset id="fieldset-modelo">
        <legend>Cadastro</legend>
        <div>
            <?php echo $this->form->getSubForm('identificacao')->getElement('descricao'); ?>
        </div>
        <div>
            <?php echo $this->form->getSubForm('identificacao')->getElement('numContagens'); ?>
        </div>

        <div class="fieldsets">
            <div class="fieldset-left">
                <div class="checkboxes">
                    <?php echo $this->form->getSubForm('identificacao')->getElement('ativo'); ?><br />
                    <?php echo $this->form->getSubForm('identificacao')->getElement('default'); ?><br />
                    <?php echo $this->form->getSubForm('identificacao')->getElement('itemAItem'); ?><br />
                    <?php echo $this->form->getSubForm('identificacao')->getElement('controlaValidade'); ?><br />
                    <?php echo $this->form->getSubForm('identificacao')->getElement('exigeUma'); ?><br />
                    <?php echo $this->form->getSubForm('identificacao')->getElement('comparaEstoque'); ?><br />
                    <?php echo $this->form->getSubForm('identificacao')->getElement('usuarioNContagens'); ?><br />
                    <?php echo $this->form->getSubForm('identificacao')->getElement('contarTudo'); ?><br />
                    <?php echo $this->form->getSubForm('identificacao')->getElement('volumesSeparadamente'); ?><br />
                </div>
            </div>

    </fieldset>
</form>
