<form action="/expedicao/corte-pedido/cortar-pedido">
    <b>Motivo do Corte:</b>
    <select name="motivoCorte" id="motivoCorte" required mostrarselecione="1">
        <option value="" label="Selecione...">Selecione...</option>
        <?php
        foreach ($this->motivos as $key => $motivo) {
            echo '<option value="' . $key . '" label="' .$motivo. '">' . $motivo. '</option>';
        }
        ?>
    </select>
    <input type="hidden" name="id" id="id" value="<?php echo $this->pedido; ?>">
    <input type="hidden" name="expedicao" id="expedicao" value="<?php echo $this->expedicao; ?>">
    <b>Senha:</b>
    <input type="password" name="senha" id="senha" value="" size="0%" title="senha" required style="margin-right: 25px">
    <input type="submit" name="submit" id="btnCortarPedido" value="Confirmar Cortes" class="btn" style="margin-top: 10px; margin-bottom: 15px">
</form>
