INSERT INTO VERSAO (DTH, NUMERO_VERSAO, SCRIPT) VALUES (SYSDATE, '6.0.0','1-update-funcionalidades.sql');

ALTER TABLE FUNCIONALIDADES ADD (COD_VERSAO VARCHAR2(10) );
UPDATE FUNCIONALIDADES SET COD_VERSAO = '5.0.0';