INSERT INTO VERSAO (DTH, NUMERO_VERSAO, SCRIPT) VALUES (SYSDATE, '6.0.0','4-qtd-mapa-pedido.sql');

ALTER TABLE MAPA_SEPARACAO_PEDIDO ADD (QTD NUMBER(13,3) NULL);
ALTER TABLE MAPA_SEPARACAO_PEDIDO ADD (QTD_CORTADA NUMBER(13,3) NULL);