INSERT INTO VERSAO (DTH, NUMERO_VERSAO, SCRIPT) VALUES (SYSDATE, '6.0.0','6-cancelar-carregamento-erp.sql');

CREATE TABLE TR_CANCELAMENTO_CARGA (
  COD_CARGA_EXTERNO NUMBER(8) NOT NULL,
  DTH_CANCELAMENTO DATE NOT NULL
);

INSERT INTO SIGLA (COD_SIGLA, COD_TIPO_SIGLA, DSC_SIGLA, COD_REFERENCIA_SIGLA)
  VALUES (617, 79, 'CANCELA CARGAS ERP P/ WMS', 'INTEGRACAO');

INSERT INTO CONEXAO_INTEGRACAO (COD_CONEXAO_INTEGRACAO, DSC_CONEXAO_INTEGRACAO, SERVIDOR, PORTA, USUARIO, SENHA, DBNAME, PROVEDOR)
  VALUES (2, 'INTEGRACAO LOCAL', 'localhost', 1521, 'wms_adm', 'wms_adm', 'xe', 'ORACLE');