INSERT INTO VERSAO (DTH, NUMERO_VERSAO, SCRIPT) VALUES (SYSDATE, '6.0.0','cancelar-carregamento-erp.sql');

CREATE TABLE TR_CANCELAMENTO_CARGA (
  COD_CARGA_EXTERNO NUMBER(8) NOT NULL,
  DTH_CANCELAMENTO DATE NOT NULL
);