INSERT INTO VERSAO (DTH, NUMERO_VERSAO, SCRIPT) VALUES (SYSDATE, '5.0.0','parametro-liberar-estoque-erp.sql');

CREATE TABLE INTEGRACAO_CANCELAMENTO_CARGA (
  COD_CARGA_EXTERNO NUMBER(8,0) NOT NULL,
  COD_STATUS NUMBER(8,0) NOT NULL,
  DTH_CANCELAMENTO DATE NOT NULL
);