<script>
    $(function() {

        $( "#btn-salvar-codigo-fornecedor" )
            .live('click', function(event){

                $('.grid-codFornecedor').append('<tr class="gTResultSet"> <td style="text-align:left">'+$("#codigoFornecedor-fornecedor").val()+'</td> <td style="text-align:left">'+$("#codigoFornecedor-codigo").val()+'</td> <td style="text-align:left"> <a href="javascript://" class="excluir-cod-fornecedor" title="Clique para Excluir"> <img src="http://wms.local/img/icons/delete.png"> </a> </td> </tr>');
                $('.grid-codFornecedor').append('<input type="hidden" name="fornecedor['+$("#tempCodFornecedor").val()+'][id]" value="'+$("#tempCodFornecedor").val()+'" />');
                $('.grid-codFornecedor').append('<input type="hidden" name="fornecedor['+$("#tempCodFornecedor").val()+'][cod]" value="'+$("#codigoFornecedor-codigo").val()+'" />');
                $('#codigoFornecedor-fornecedor').val('');
                event.preventDefault();
            });


        $( '.excluir-cod-fornecedor' )
            .live( 'click', function(event) {
                id = $(this).attr('data-id');
                thisId = $(this);
                $.getJSON( "/produto/excluir-cod-fornecedor-ajax/id/"+id, function( data) {
                    thisId.parent().parent().remove();
                });

                event.preventDefault();
            });

        var cache = {};

        $( "#codigoFornecedor-fornecedor" ).autocomplete({
            minLength: 2,
            source: function( request, response ) {
                var term = request.term;
                if ( term in cache ) {
                    response( cache[ term ] );
                    return;
                }

                $.getJSON( "/produto/codigo-fornecedor-ajax", request, function( data, status, xhr ) {
                    cache[ term ] = data;
                    response( data );
                });
            },
            select: function (event, ui) {
                this.value = ui.item.label;
                // Store value in hidden field
                $('#tempCodFornecedor').val(ui.item.id);
                // Prevent default behaviour
                return false;
            }
        });

    });

</script>

<div id="produto-codigo-fornecedor">
    <dd id="identification-element">
        <fieldset id="fieldset-codigo-fornecedor">
            <legend>Escolha o fornecedor e digite o código do produto no fornecedor escolhido</legend>
            <?php echo $this->element->fornecedor; ?>
            <?php echo $this->element->codigo; ?>
            <?php echo $this->element->btnAdicionar; ?>
        </fieldset>
    </dd>
    <input type="hidden" value="" id="tempCodFornecedor" name="tempCodFornecedor" />

    <table class="gTable grid-codFornecedor">
        <tbody><tr class="gTTitle">
            <td width=""><span>Fornecedor</span></td>
            <td width=""><span>Código do produto no fornecedor</span></td>
            <td width=""><span>Excluir?</span></td>
        </tr>
        <?php $codigosFornecedores = Zend_Layout::getMvcInstance()->getView()->codigosFornecedores;?>
        <?php foreach($codigosFornecedores as $codigoFornecedor) : ?>
            <tr class="gTResultSet ">
                <td style="text-align:left"><?php echo $codigoFornecedor->getFornecedor()->getPessoa()->getNome(); ?></td>
                <td style="text-align:left"><?php echo $codigoFornecedor->getDscReferencia() ?></td>
                <td style="text-align:left">
                    <a class="excluir-cod-fornecedor" title="Clique para Excluir" class="" data-id="<?php echo $codigoFornecedor->getId(); ?>" href="javascript://">
                        <img src="http://wms.local/img/icons/delete.png">
                    </a>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>

</div>