<style>
    #fieldset-embalagem {
        width: 350px; 
        float: left; 
        margin-right: 10px;
    }
    #fieldset-embalagem div.field {
        clear:both;
    }
    #fieldset-embalagens-cadastradas {
        float: right;
        width: 570px;
    }

    div.checkbox label.optional {
        margin: 0;
    }
</style>
<div id="produto-embalagem">
    <dd id="identification-element">
        <fieldset id="fieldset-embalagem">
            <legend>Criar Novo</legend>
            <?php
            echo $this->element->id;
            echo $this->element->grade;
            echo $this->element->acao;
            echo $this->element->idProduto;
            echo $this->element->codigoBarrasAntigo;
            echo $this->element->enderecoAntigo;
            echo $this->element->dataInativacao;
            ?>
            <table>
                <tr>
                    <td colspan="3"><?php echo $this->element->descricao; ?></td>
                </tr>
                <tr>
                    <td colspan="2"><?php echo $this->element->quantidade; ?></td>
                    <td colspan="1"><?php echo $this->element->isPadrao; ?></td>
                </tr>
                <tr>
                    <td colspan="2"><?php echo $this->element->CBInterno; ?></td>
                    <td colspan="1"><?php echo $this->element->imprimirCB; ?></td>
                </tr>
                <tr>
                    <td colspan="3"><?php echo $this->element->codigoBarras; ?></td>
                </tr>
                <tr>
                    <td colspan="2"><?php echo $this->element->embalado; ?></td>
                </tr>
            </table>
            <?php echo $this->element->btnEmbalagem; ?>
        </fieldset>
        <fieldset id="fieldset-campos-comuns" style="float: right; width: 580px;">
            <legend>Campos Gerais</legend>
            <?php
            echo $this->element->enderecoAntigo;
            echo $this->element->idProduto;
            echo $this->element->grade;
            ?>
            <table>
                <tr>
                    <td><?php echo $this->element->endereco; ?></td>
                    <td>
                        <div class="field">
                            <label for="embalagem-fator" class="field optional">Embalagem</label>
                            <select name="embalagem-fator" id="embalagem-fator" mostrarselecione="" class="valid">
                                <option value="1" label="Selecione ...">Selecione ...</option>
                            </select>
                        </div>
                        <input type="hidden" id="capacidadePicking-real" value="0" />
                        <input type="hidden" id="pontoReposicao-real" value="0" />
                        <input type="hidden" id="peso-real" value="0" />
                        <input type="hidden" id="altura-real" value="0" />
                    </td>
                    <td><?php echo $this->element->pontoReposicao; ?></td>
                    <td><?php echo $this->element->capacidadePicking; ?></td>
                </tr><tr>
                    <td><?php echo $this->element->altura; ?></td>
                    <td><?php echo $this->element->largura; ?></td>
                    <td><?php echo $this->element->profundidade; ?></td>
                    <td><?php echo $this->element->cubagem; ?></td>
                    <td><?php echo $this->element->peso; ?></td>
                </tr>
            </table>
        </fieldset>
        <fieldset id="fieldset-embalagens-cadastradas" style="width: 580px!important">
            <legend>Embalagens Cadastradas (Clique para Editar)</legend>
        </fieldset>
    </dd>
</div>