<div id="identificacao-form">
    <fieldset id="identificacao">
    <legend>Identificação</legend>
        <?php echo $this->element->cadastral; ?>
        <table style="width: 100%;" >
            <tr >
                <td style="width: 67%; padding-right: 1%"><?php echo $this->element->logistico; ?></td>
                <td><?php echo $this->element->unidComercio; ?></td>
            </tr>
        </table>
        <table style="width: 100%;" >
            <tr>
                <td style="width: 60%; padding-right: 1%"> <?php echo $this->element->pesoVariavel; ?> </td>
                <td> <?php echo $this->element->validadeProdutos; ?> </td>
            </tr>
        </table>
    </fieldset>
</div>