<?php
echo $this->headLink()->appendStylesheet('/css/admin/form/volumeForm.css');
?>
<div id="produto-volume">
    <dd id="identification-element">

        <fieldset id="fieldset-grupo-volumes">
            <legend>Normas de Paletização de Volumes - (Arraste os volumes sobre uma norma)</legend>
            <input type="button" name="btnAddGrupo" id="btn-add-grupo" value="Adicionar Nova Norma de Paletização" class="btnAddGrupo" />

            <div id="div-lista-volumes" class="ui-sortable"></div>
        </fieldset>

        <fieldset id="fieldset-volume">
            <legend>Criar Novo</legend>
            <?php
            echo $this->element->idProduto;
            echo $this->element->grade;
            echo $this->element->id;
            echo $this->element->idNormaPaletizacao;
            echo $this->element->acao;
            echo $this->element->idProduto;
            echo $this->element->grade;
            echo $this->element->codigoSequencial;
            echo $this->element->altura;
            echo $this->element->largura;
            echo $this->element->profundidade;
            echo $this->element->cubagem;
            echo $this->element->peso;
            echo $this->element->descricao;
            echo $this->element->CBInterno;
            echo $this->element->imprimirCB;
            echo $this->element->codigoBarras;
            echo $this->element->codigoBarrasAntigo;
            echo $this->element->endereco;
            echo $this->element->pontoReposicao;
            echo $this->element->capacidadePicking;
            echo $this->element->btnVolume;
            ?>
        </fieldset>

    </dd>
</div>