
INSERT INTO VERSAO (DTH, NUMERO_VERSAO, SCRIPT) VALUES (SYSDATE, 'x.xx', 'xx-correcao-apontamento-separacao.sql');

ALTER TABLE SEPARACAO_MAPA_SEPARACAO ADD (QTD_SEPARADA_BKP NUMBER(15,4));
ALTER TABLE SEPARACAO_MAPA_SEPARACAO MODIFY(QTD_SEPARADA null);
UPDATE SEPARACAO_MAPA_SEPARACAO SET QTD_SEPARADA_BKP = QTD_SEPARADA;
UPDATE SEPARACAO_MAPA_SEPARACAO SET QTD_SEPARADA = null;
ALTER TABLE SEPARACAO_MAPA_SEPARACAO MODIFY(QTD_SEPARADA NUMBER(15,4));
UPDATE SEPARACAO_MAPA_SEPARACAO SET QTD_SEPARADA = QTD_SEPARADA_BKP;
ALTER TABLE SEPARACAO_MAPA_SEPARACAO DROP COLUMN QTD_SEPARADA_BKP;