/* 
 * SCRIPT PARA: Estrutura para registrar data de criação do palete
 * DATA DE CRIAÇÃO: 10/06/2020 
 * CRIADO POR: Tarcísio César
 *
 */

INSERT INTO VERSAO (DTH, NUMERO_VERSAO, SCRIPT) VALUES (SYSDATE, '7.16', 'xx-xx-relatorios-customizados.sql.sql');

INSERT INTO RECURSO (DSC_RECURSO, COD_RECURSO, COD_RECURSO_PAI, NOM_RECURSO) VALUES ('Relatórios Customizados', SQ_RECURSO_01.NEXTVAL,0,'relatorio-customizado');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'relatorio-customizado'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'consultar'), 'Listar Relatórios Customizados');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'relatorio-customizado'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'relatorio'), 'Executar Relatórios Customizados');
INSERT INTO MENU_ITEM (COD_MENU_ITEM, COD_RECURSO_ACAO, COD_PAI, DSC_MENU_ITEM, NUM_PESO, DSC_URL, DSC_TARGET, SHOW) VALUES (SQ_MENU_ITEM_01.NEXTVAL, (SELECT COD_RECURSO_ACAO FROM RECURSO_ACAO WHERE COD_RECURSO = (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'relatorio-customizado') AND COD_ACAO = (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'consultar')), (SELECT COD_MENU_ITEM FROM MENU_ITEM WHERE DSC_MENU_ITEM = 'Relatórios' ), 'Relatórios Customizados', 12, '#','_selft', 'S')

CREATE TABLE RELATORIO_CUSTOMIZADO
(
  COD_RELATORIO_CUSTOMIZADO NUMBER (8) NOT NULL ,
  DSC_TITULO_RELATORIO      VARCHAR2 (200 BYTE) NOT NULL ,
  DSC_QUERY                 VARCHAR2 (4000 BYTE) NOT NULL ,
  COD_CONEXAO_INTEGRACAO    NUMBER (8) ,
  IND_ALLOW_XLS             VARCHAR2 (1 BYTE) NOT NULL,
  IND_ALLOW_PDF             VARCHAR2 (1 BYTE) NOT NULL,
  IND_ALLOW_SEARCH          VARCHAR2 (1 BYTE) NOT NULL,
  DTH_INATIVACAO            TIMESTAMP
) LOGGING;

ALTER TABLE RELATORIO_CUSTOMIZADO
  ADD CONSTRAINT REL_CUST_PK PRIMARY KEY ( COD_RELATORIO_CUSTOMIZADO ) ;

CREATE TABLE RELATORIO_CUSTOMIZADO_FILTRO
(
  COD_RELATORIO_CUST_FILTRO NUMBER (8) NOT NULL ,
  COD_RELATORIO_CUSTOMIZADO NUMBER (8) NOT NULL ,
  NOME_PARAM                VARCHAR2 (50 BYTE) NOT NULL ,
  DSC_TITULO                VARCHAR2 (50 BYTE) NOT NULL ,
  IND_OBRIGATORIO           VARCHAR2 (1 BYTE) NOT NULL,
  TIPO                      VARCHAR2 (50 BYTE) NOT NULL,
  PARAMS                    VARCHAR2 (1000 BYTE) NOT NULL,
  TAMANHO                   NUMBER (8) NOT NULL ,
  DSC_QUERY                 VARCHAR2 (4000 BYTE) NOT NULL
) LOGGING;

ALTER TABLE RELATORIO_CUSTOMIZADO_FILTRO
  ADD CONSTRAINT RelatorioCustomizadoFiltroPK PRIMARY KEY ( COD_RELATORIO_CUST_FILTRO ) ;

ALTER TABLE RELATORIO_CUSTOMIZADO_FILTRO
  ADD CONSTRAINT REL_CUST_FIL_REL_CUST_FK FOREIGN KEY ( COD_RELATORIO_CUSTOMIZADO ) REFERENCES RELATORIO_CUSTOMIZADO ( COD_RELATORIO_CUSTOMIZADO ) NOT DEFERRABLE ;

CREATE TABLE RELATORIO_CUSTOMIZADO_SORT
(
  COD_RELATORIO_CUST_SORT   NUMBER (8) NOT NULL ,
  COD_RELATORIO_CUSTOMIZADO NUMBER (8) NOT NULL ,
  DSC_QUERY                 VARCHAR2 (4000 BYTE) NOT NULL,
  DSC_TITULO                VARCHAR2 (50 BYTE) NOT NULL
) LOGGING;

ALTER TABLE RELATORIO_CUSTOMIZADO_SORT
  ADD CONSTRAINT RelatorioCustomizadoSortPK PRIMARY KEY ( COD_RELATORIO_CUST_SORT ) ;

ALTER TABLE RELATORIO_CUSTOMIZADO_SORT
  ADD CONSTRAINT REL_CUST_SRT_REL_CUST_FK FOREIGN KEY ( COD_RELATORIO_CUSTOMIZADO ) REFERENCES RELATORIO_CUSTOMIZADO ( COD_RELATORIO_CUSTOMIZADO ) NOT DEFERRABLE ;

CREATE SEQUENCE SQ_RELATORIO_CUSTOMIZADO_01
INCREMENT BY 1
START WITH 1
MAXVALUE 999999999999999999999999999
MINVALUE 0
NOCYCLE
NOCACHE
NOORDER;

CREATE SEQUENCE SQ_RELATORIO_CUST_FILTRO_01
INCREMENT BY 1
START WITH 1
MAXVALUE 999999999999999999999999999
MINVALUE 0
NOCYCLE
NOCACHE
NOORDER;

CREATE SEQUENCE SQ_RELATORIO_CUST_SORT_01
INCREMENT BY 1
START WITH 1
MAXVALUE 999999999999999999999999999
MINVALUE 0
NOCYCLE
NOCACHE
NOORDER;