<fieldset id="fieldset-busca">
    <table>
	<tr height="25">
	    <td width="60">Código:</td>
	    <td width="100"><?php echo "{$this->element->id}"; ?></td>

	    <td width="60">Descrição</td>
	    <td width="200"><?php echo "{$this->element->descricao}"; ?></td>
	    
	    <td width="200" align="right"><input type="submit" class="btn" id="submit" value="Buscar" name="busca"/></td>
	</tr>
    </table>
</fieldset>