<div id="pessoa-endereco">
    <fieldset id="fieldset-endereco" style="width: 480px; float: left; margin-right: 10px;">
        <legend>Identificação</legend>
        <?php
        foreach ($this->element->getElements() as $element) {
            echo $element;
        }
        ?>
    </fieldset>
    <fieldset id="fieldset-enderecos-cadastrados" style="width: 450px;">
        <legend>Endereços cadastrados</legend>
    </fieldset>
    
</div>