<fieldset id="fieldset-busca">
    <table>
	<tr height="25">
	    <td width="80">Razão Social:</td>
	    <td width="350"><?php echo "{$this->element->nome}"; ?></td>

	    <td width="90">Nome Fantasia:</td>
	    <td width="400"><?php echo "{$this->element->nomeFantasia}"; ?></td>
	</tr>
	
	<tr height="50">
	    <td width="80">CNPJ:</td>
	    <td width="350"><?php echo "{$this->element->cnpj}"; ?></td>

	    <td><input type="submit" class="btn" id="submit" value="Buscar" name="busca"/></td>
	</tr>
    </table>
</fieldset>