<style>
    <!--
    button#btn-salvar-telefone {
        margin-top: 15px;
    }
    -->
</style>
<div id="filial-parametros">
    <fieldset id="fieldset-parametros" style="width: 480px; float: left; margin-right: 10px;">
        <legend>Expedição de Transbordo</legend>
        <?php
            echo $this->element->recebimento_transbordo_obrigatorio;
            echo $this->element->duplo_bipe_transbordo;
        ?>
    </fieldset>
</div>