<style>
    table.ordemServico {
        width:100%;
    }
    table.ordemServico th {
        text-align: left;
        line-height:20px;
    }
</style>
<fieldset id="fieldset-recebimento">
    <legend>Ordem de Serviço</legend>
    <table class="ordemServico">
        <tr>
            <th>Ordem de Serviço:</th>
            <th>Usuário:</th>
            <th>Atividade:</th>
            <th>Data Inicial:</th>
            <th>Data Final:</th>
        </tr>
        <tr>
            <td><?php echo $this->ordemServico->getId(); ?></td>
            <td><?php echo $this->ordemServico->getPessoa()->getNome(); ?></td>
            <td><?php echo $this->ordemServico->getAtividade()->getDescricao(); ?></td>
            <td><?php echo $this->ordemServico->getDataInicial(); ?></td>
            <td><?php echo $this->ordemServico->getDataFinal(); ?></td>
        </tr>
    </table>
</fieldset>

<?php
echo $this->grid;