CREATE VIEW V_OCUP_RESERVA_LONGARINA
AS SELECT SUM(OCUPADO) AS OCUPADO,
       NUM_PREDIO,
       NUM_NIVEL,
       NUM_RUA,
       TAMANHO_LONGARINA
  FROM (SELECT NVL(E.TAM,0) * 100 as OCUPADO,
               DE.NUM_PREDIO,
               DE.NUM_NIVEL,
               DE.NUM_RUA,
               DE.NUM_APARTAMENTO,
               NVL(TL.TAMANHO,TP.DSC_VALOR_PARAMETRO) as TAMANHO_LONGARINA
  FROM DEPOSITO_ENDERECO DE
  LEFT JOIN (SELECT MAX(U.NUM_LARGURA_UNITIZADOR) as TAM, E.COD_DEPOSITO_ENDERECO
               FROM (SELECT RE.COD_DEPOSITO_ENDERECO, P.COD_UNITIZADOR FROM RESERVA_ESTOQUE_ENDERECAMENTO REE
                      INNER JOIN RESERVA_ESTOQUE RE ON RE.COD_RESERVA_ESTOQUE = REE.COD_RESERVA_ESTOQUE
                      INNER JOIN PALETE P ON P.UMA = REE.UMA
                      WHERE RE.IND_ATENDIDA = 'N'
                      UNION
                     SELECT COD_DEPOSITO_ENDERECO, COD_UNITIZADOR FROM ESTOQUE) E
               LEFT JOIN UNITIZADOR U ON U.COD_UNITIZADOR = E.COD_UNITIZADOR
              GROUP BY E.COD_DEPOSITO_ENDERECO) E ON E.COD_DEPOSITO_ENDERECO = DE.COD_DEPOSITO_ENDERECO
  LEFT JOIN TAMANHO_LONGARINA TL ON DE.NUM_PREDIO = TL.NUM_PREDIO AND DE.NUM_RUA = TL.NUM_RUA
  LEFT JOIN PARAMETRO         TP ON TP.DSC_PARAMETRO = 'TAMANHO_LONGARINA_PADRAO'
 WHERE DE.IND_ATIVO = 'S')
 GROUP BY NUM_PREDIO,
          NUM_NIVEL,
          NUM_RUA,
          TAMANHO_LONGARINA;
