--cria coluna COD_DEPOSITO_ENDERECO na tabela ETIQUETA_SEPARACAO
ALTER TABLE ETIQUETA_SEPARACAO
ADD (COD_DEPOSITO_ENDERECO NUMBER(12));

--cria coluna COD_DEPOSITO_ENDERECO na tabela MAPA_SEPARACAO_PRODUTO
ALTER TABLE MAPA_SEPARACAO_PRODUTO
ADD (COD_DEPOSITO_ENDERECO NUMBER(12));

