<script>
    $(document).keypress(function(e, v) {
        if(e.which == 13) {
            if(($.trim($("#codigoBarras").val()) == '')){
                $("#codigoBarras").focus();
                e.preventDefault();
                return false;
            }else if($.trim($("#qtd").val()) == ''){
                $("#qtd").focus();
                e.preventDefault();
                return false;
            }
        }
    });
</script>
<?php echo $this->form; ?>
<div id="footer">
    <a class="btn button finalizar" href="<?php echo $this->url(array('controller' => 'enderecamento_reabastecimento-manual', 'action' => 'fechar')); ?>">Fechar O.S</a>
</div>