
INSERT INTO VERSAO (DTH, NUMERO_VERSAO, SCRIPT) VALUES (SYSDATE, '7.17', '01-comparativo-inventario-ERP.sql');

INSERT INTO RECURSO (DSC_RECURSO, COD_RECURSO, COD_RECURSO_PAI, NOM_RECURSO)
     VALUES ('Exportação e Comparativo de Inventários', SQ_RECURSO_01.NEXTVAL,0,'inventario_novo:comparativo-inventario');

INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO)
     VALUES (SQ_RECURSO_ACAO_01.NEXTVAL,
             (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'inventario_novo:comparativo-inventario'),
             (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'index'),
             'Exportar e comparar inventários WMS x ERP');

INSERT INTO MENU_ITEM (COD_MENU_ITEM, COD_RECURSO_ACAO, COD_PAI, DSC_MENU_ITEM, NUM_PESO, DSC_URL, DSC_TARGET, SHOW)
     VALUES (SQ_MENU_ITEM_01.NEXTVAL,
             (SELECT COD_RECURSO_ACAO
                FROM RECURSO_ACAO
               WHERE COD_RECURSO = (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'inventario_novo:comparativo-inventario')
                 AND COD_ACAO = (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'index')),
            (SELECT COD_MENU_ITEM FROM MENU_ITEM WHERE DSC_MENU_ITEM = 'Novo Inventário'), 'Exportar inventário ERP', 12, '#','_selft', 'S');

UPDATE MENU_ITEM
  SET DSC_MENU_ITEM = 'Comparativo Estoque WMS x ERP',
      COD_PAI = (SELECT COD_MENU_ITEM FROM MENU_ITEM WHERE DSC_MENU_ITEM = 'Novo Inventário')
 WHERE DSC_MENU_ITEM = 'Comparativo Estoque ERP x WMS';

 UPDATE MENU_ITEM
    SET SHOW = 'N'
  WHERE DSC_MENU_ITEM = 'Inventário'
    AND COD_PAI = 0;

 UPDATE MENU_ITEM
    SET DSC_MENU_ITEM = 'Inventário'
  WHERE DSC_MENU_ITEM = 'Novo Inventário'
    AND COD_PAI = 0;

INSERT INTO SIGLA (COD_SIGLA,COD_TIPO_SIGLA,DSC_SIGLA,COD_REFERENCIA_SIGLA) VALUES (634,79,'COMPARATIVO DE INVENTÁRIO COM ERP','I');

INSERT INTO PARAMETRO (COD_PARAMETRO, COD_CONTEXTO_PARAMETRO, DSC_PARAMETRO, DSC_TITULO_PARAMETRO, IND_PARAMETRO_SISTEMA, COD_TIPO_ATRIBUTO, DSC_VALOR_PARAMETRO)
VALUES (SQ_PARAMETRO_01.NEXTVAL,
       (SELECT COD_CONTEXTO_PARAMETRO FROM CONTEXTO_PARAMETRO WHERE DSC_CONTEXTO_PARAMETRO = 'PARÂMETROS DE INTEGRAÇÃO'),
       'ID_INTEGRACAO_COMPARATIVO_INVENTARIO_ERP',
       'Id da integração de comparativo de inventário com ERP','S','A','');