<?php
/**
 * Created by PhpStorm.
 * User: tarci
 * Date: 11/01/2019
 * Time: 16:34
 */
?>

<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('css/admin/accordion.css'); ?>" />
<div>
    <div class="accordion" id="accordion-master">
        <div class="group">
            <h3 class="accordion-header">Section 1</h3>
            <div class="accordion-body">
                <p>Mauris mauris ante, blandit et, ultrices a, suscipit eget, quam. Integer ut neque. Vivamus nisi metus, molestie vel, gravida in, condimentum sit amet, nunc. Nam a nibh. Donec suscipit eros. Nam mi. Proin viverra leo ut odio. Curabitur malesuada. Vestibulum a velit eu ante scelerisque vulputate.</p>
            </div>
        </div>
        <div class="group">
            <h3 class="accordion-header">Section 2</h3>
            <div class="accordion-body">
                <div class="accordion">
                    <div class="group">
                        <h3 class="accordion-header">Sub section</h3>
                        <div class="accordion-body">
                            <p>Mauris mauris ante, blandit et, ultrices a, suscipit eget, quam. Integer ut neque. Vivamus nisi metus, molestie vel, gravida in, condimentum sit amet, nunc. Nam a nibh. Donec suscipit eros. Nam mi. Proin viverra leo ut odio. Curabitur malesuada. Vestibulum a velit eu ante scelerisque vulputate.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $(function() {
        var arrAndamento = <?php echo $this->andamentos; ?> ;

        $(document).ready(function () {
            if (arrAndamento.length > 0) {
                console.log(arrAndamento);
                $.each(arrAndamento, function (k, rua) {
                    $.each(rua, function (k, info) {

                    });
                })
            }
        });

        $(".accordion")
            .accordion({
                active: false,
                header: "> div > h3",
                autoHeight: false,
                fillHeight: true,
                collapsible: true,
                icons: {
                    header: "ui-icon-accordion-header",
                    headerSelected: "ui-icon-accordion-active"
                }
            })
            .sortable({
                axis: "y",
                handle: "h3",
                stop: function( event, ui ) {
                    // IE doesn't register the blur when sorting
                    // so trigger focusout handlers to remove .ui-state-focus
                    ui.item.children( "h3" ).triggerHandler( "focusout" );

                    // Refresh accordion to handle new order
                    $( this ).accordion( "refresh" );
                }
            });
    });
</script>
