
INSERT INTO VERSAO (DTH, NUMERO_VERSAO, SCRIPT) VALUES (SYSDATE, '7.0.0', '01-ajustes-integracao-BD.sql');

INSERT INTO SIGLA (COD_SIGLA,COD_TIPO_SIGLA,DSC_SIGLA,COD_REFERENCIA_SIGLA) VALUES (618,79,'FINALIZA CONFERENCIA ERP - RETORNO POR CARGAS','F');
INSERT INTO SIGLA (COD_SIGLA,COD_TIPO_SIGLA,DSC_SIGLA,COD_REFERENCIA_SIGLA) VALUES (619,79,'FINALIZA CONFERENCIA ERP - RETORNO POR CARGA','B');
INSERT INTO SIGLA (COD_SIGLA,COD_TIPO_SIGLA,DSC_SIGLA,COD_REFERENCIA_SIGLA) VALUES (620,79,'FINALIZA CONFERENCIA ERP - RETORNO POR PEDIDO','B');
UPDATE SIGLA SET DSC_SIGLA = 'FINALIZA CONFERENCIA ERP - RETORNO POR PRODUTOS' WHERE COD_SIGLA = 609;

/*
 * RODAR ESTA PARTE APENAS NA CAMPO BOM
 *  UPDATE ACAO_INTEGRACAO SET COD_TIPO_ACAO_INTEGRACAO = 618
 *   WHERE COD_ACAO_INTEGRACAO IN (10,12);
 */

/*
 * RODAR ESTA PARTE APENAS NA WILSO e CDC
 *
 *  UPDATE ACAO_INTEGRACAO SET COD_TIPO_ACAO_INTEGRACAO = 618
 *   WHERE COD_ACAO_INTEGRACAO IN (SELECT DSC_VALOR_PARAMETRO FROM PARAMETRO WHERE DSC_PARAMETRO = 'ID_INTEGRACAO_FINALIZA_CONFERENCIA_ERP')
 */

/*
 * RODAR ESTA PARTE APENAS NA EDMIL
 * RODAR ESTA PARTE APENAS NA CAMPO BOM
 *  UPDATE ACAO_INTEGRACAO SET COD_TIPO_ACAO_INTEGRACAO = 618
 *   WHERE COD_ACAO_INTEGRACAO IN (3);
 */