INSERT INTO VERSAO (DTH, NUMERO_VERSAO, SCRIPT) VALUES (SYSDATE, '7.0.0', 'xx-tabelas-lote.sql');

CREATE TABLE LOTE
  (
    COD_LOTE NUMBER(11) NOT NULL,
    DSC_LOTE VARCHAR2 (200),
    DTH_CRIACAO DATE NOT NULL,
    COD_PESSOA_CRIACAO NUMBER(11) NOT NULL,
    COD_PRODUTO NUMBER(11) NOT NULL,
    DSC_GRADE VARCHAR2 (200)
  );

CREATE SEQUENCE SQ_LOTE_01
INCREMENT BY 1
START WITH 1
MAXVALUE 999999999999999999999999999
MINVALUE 0
NOCYCLE
NOCACHE
NOORDER;

-------------------------------------------------------------------------------