CREATE TABLE PEDIDO_ENDERECO
   ("COD_PEDIDO_ENDERECO" NUMBER(8,0),
	"COD_PEDIDO" NUMBER(8,0), 
	"COD_TIPO_ENDERECO" NUMBER(8,0), 
	"NUM_CEP" VARCHAR2(10 BYTE), 
	"DSC_ENDERECO" VARCHAR2(100 BYTE),
	"NUM_ENDERECO" VARCHAR2(6 BYTE), 
	"DSC_COMPLEMENTO" VARCHAR2(36 BYTE), 
	"NOM_BAIRRO" VARCHAR2(72 BYTE), 
	"NOM_LOCALIDADE" VARCHAR2(72 BYTE), 
	"COD_UF" NUMBER(8,0), 
	"DSC_PONTO_REFERENCIA" VARCHAR2(255 BYTE), 
	"IND_ENDERECO_ECT" CHAR(1 BYTE), 
	"COD_LOCALIDADE" NUMBER(8,0)
   );

CREATE SEQUENCE SQ_PEDIDO_ENDERECO_01
	INCREMENT BY 1
	START WITH 1
	MAXVALUE 999999999999999999999999999
	MINVALUE 0
	NOCYCLE
	NOCACHE
	NOORDER;

DELETE FROM PEDIDO_ENDERECO;

INSERT INTO PEDIDO_ENDERECO
SELECT SQ_PEDIDO_ENDERECO_01.NEXTVAL,
       P.COD_PEDIDO,
       E.COD_TIPO_ENDERECO,
       E.NUM_CEP,
       E.DSC_ENDERECO,
       E.NUM_ENDERECO,
       E.DSC_COMPLEMENTO,
       E.NOM_BAIRRO,
       E.NOM_LOCALIDADE,
       E.COD_UF,
       E.DSC_PONTO_REFERENCIA,
       E.IND_ENDERECO_ECT,
       E.COD_LOCALIDADE
  FROM PEDIDO P
  INNER JOIN (SELECT MAX(COD_PESSOA_ENDERECO), COD_PESSOA FROM PESSOA_ENDERECO GROUP BY COD_PESSOA) PE ON PE.COD_PESSOA = P.COD_PESSOA
  LEFT JOIN PESSOA_ENDERECO E ON E.COD_PESSOA = PE.COD_PESSOA;
