INSERT INTO ACAO (COD_ACAO, DSC_ACAO, NOM_ACAO) VALUES (SQ_ACAO_01.NEXTVAL ,'EQUIPE QUE RECEBEU OS PRODUTOS', 'equipe-recebimento');

INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (select COD_RECURSO from recurso WHERE NOM_RECURSO LIKE 'relatorio_produto-recebido'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO LIKE 'equipe-recebimento'), 'Obter a equipe responsavel pelo recebimento dos produtos');
