INSERT INTO VERSAO (DTH, NUMERO_VERSAO, SCRIPT) VALUES (SYSDATE, '5.0.0','24-integracoes-simultaneas.sql');

ALTER TABLE ACAO_INTEGRACAO
  ADD (IND_EXECUCAO VARCHAR(1));

UPDATE ACAO_INTEGRACAO SET IND_EXECUCAO = 'N';
