INSERT INTO VERSAO (DTH, NUMERO_VERSAO, SCRIPT) VALUES (SYSDATE, '5.0.0','parametroCaracterEndereco.sql');

INSERT INTO PARAMETRO
(COD_PARAMETRO, COD_CONTEXTO_PARAMETRO, DSC_PARAMETRO, DSC_TITULO_PARAMETRO,
 IND_PARAMETRO_SISTEMA, COD_TIPO_ATRIBUTO, DSC_VALOR_PARAMETRO)
VALUES (
  SQ_PARAMETRO_01.NEXTVAL,
  (SELECT COD_CONTEXTO_PARAMETRO FROM CONTEXTO_PARAMETRO WHERE DSC_CONTEXTO_PARAMETRO LIKE 'ENDERECAMENTO'),
  'TAMANHO_CARACT_RUA',
  'Qtd. Caracteres p/ Rua',
  'S', 'A', 2);

INSERT INTO PARAMETRO
(COD_PARAMETRO, COD_CONTEXTO_PARAMETRO, DSC_PARAMETRO, DSC_TITULO_PARAMETRO,
 IND_PARAMETRO_SISTEMA, COD_TIPO_ATRIBUTO, DSC_VALOR_PARAMETRO)
VALUES (
  SQ_PARAMETRO_01.NEXTVAL,
  (SELECT COD_CONTEXTO_PARAMETRO FROM CONTEXTO_PARAMETRO WHERE DSC_CONTEXTO_PARAMETRO LIKE 'ENDERECAMENTO'),
  'TAMANHO_CARACT_PREDIO',
  'Qtd. Caracteres p/ Predio',
  'S', 'A', 3);

INSERT INTO PARAMETRO
(COD_PARAMETRO, COD_CONTEXTO_PARAMETRO, DSC_PARAMETRO, DSC_TITULO_PARAMETRO,
 IND_PARAMETRO_SISTEMA, COD_TIPO_ATRIBUTO, DSC_VALOR_PARAMETRO)
VALUES (
  SQ_PARAMETRO_01.NEXTVAL,
  (SELECT COD_CONTEXTO_PARAMETRO FROM CONTEXTO_PARAMETRO WHERE DSC_CONTEXTO_PARAMETRO LIKE 'ENDERECAMENTO'),
  'TAMANHO_CARACT_NIVEL',
  'Qtd. Caracteres p/ Nivel',
  'S', 'A', 2);

INSERT INTO PARAMETRO
(COD_PARAMETRO, COD_CONTEXTO_PARAMETRO, DSC_PARAMETRO, DSC_TITULO_PARAMETRO,
 IND_PARAMETRO_SISTEMA, COD_TIPO_ATRIBUTO, DSC_VALOR_PARAMETRO)
VALUES (
  SQ_PARAMETRO_01.NEXTVAL,
  (SELECT COD_CONTEXTO_PARAMETRO FROM CONTEXTO_PARAMETRO WHERE DSC_CONTEXTO_PARAMETRO LIKE 'ENDERECAMENTO'),
  'TAMANHO_CARACT_APARTAMENTO',
  'Qtd. Caracteres p/ Apto',
  'S', 'A', 2);