CREATE TABLE PRODUTO_END_TIPO_EST_ARMAZ
  (
    COD_PRODUTO_END_TIPO_EST_ARMAZ NUMBER (8) NOT NULL ,
    COD_TIPO_EST_ARMAZ             NUMBER (8) NOT NULL ,
    COD_PRODUTO                    VARCHAR2 (20) NOT NULL ,
    DSC_GRADE                      VARCHAR2 (20) NOT NULL ,
    NUM_PRIORIDADE                 NUMBER (8)
  ) ;

ALTER TABLE PRODUTO_END_TIPO_EST_ARMAZ
  ADD CONSTRAINT PRODUTO_END_TIPO_EST_ARMAZ_PK PRIMARY KEY ( COD_PRODUTO_END_TIPO_EST_ARMAZ ) ;

ALTER TABLE PRODUTO_END_TIPO_EST_ARMAZ
  ADD CONSTRAINT PROD_END_TP_EST_ARMAZ_PROD_FK FOREIGN KEY (COD_PRODUTO, DSC_GRADE) REFERENCES PRODUTO (COD_PRODUTO,DSC_GRADE) NOT DEFERRABLE;

ALTER TABLE PRODUTO_END_TIPO_EST_ARMAZ
  ADD CONSTRAINT PROD_END_TP_EST_ARMAZ_TPEST_FK FOREIGN KEY ( COD_TIPO_EST_ARMAZ ) REFERENCES TIPO_EST_ARMAZ ( COD_TIPO_EST_ARMAZ ) NOT DEFERRABLE ;

CREATE SEQUENCE SQ_PROD_END_TIPO_EST_ARMAZ
INCREMENT BY 1
START WITH 1
MAXVALUE 999999999999999999999999999
MINVALUE 0
NOCYCLE
NOCACHE
NOORDER;

CREATE TABLE PRODUTO_END_AREA_ARMAZENAGEM
  (
    COD_PRODUTO_END_AREA_ARMAZ   NUMBER (8) NOT NULL ,
    COD_AREA_ARMAZENAGEM             NUMBER (8) NOT NULL ,
    COD_PRODUTO                  VARCHAR2 (20) NOT NULL ,
    DSC_GRADE                    VARCHAR2 (20) NOT NULL ,
    NUM_PRIORIDADE               NUMBER (8)
  ) ;

ALTER TABLE PRODUTO_END_AREA_ARMAZENAGEM
  ADD CONSTRAINT PRODUTO_END_AREA_ARMAZ_PK PRIMARY KEY ( COD_PRODUTO_END_AREA_ARMAZ ) ;

ALTER TABLE PRODUTO_END_AREA_ARMAZENAGEM
  ADD CONSTRAINT PRODUTO_END_AREA_ARMAZ_PROD_FK FOREIGN KEY (COD_PRODUTO, DSC_GRADE) REFERENCES PRODUTO (COD_PRODUTO,DSC_GRADE) NOT DEFERRABLE;

ALTER TABLE PRODUTO_END_AREA_ARMAZENAGEM
  ADD CONSTRAINT PRODUTO_END_AREA_ARMAZ_AREA_FK FOREIGN KEY ( COD_AREA_ARMAZENAGEM ) REFERENCES AREA_ARMAZENAGEM ( COD_AREA_ARMAZENAGEM ) NOT DEFERRABLE ;

CREATE SEQUENCE SQ_PROD_END_AREA_ARMAZENAGEM
INCREMENT BY 1
START WITH 1
MAXVALUE 999999999999999999999999999
MINVALUE 0
NOCYCLE
NOCACHE
NOORDER;

CREATE TABLE PRODUTO_END_TIPO_ENDERECO
  (
    COD_PRODUTO_END_TIPO_ENDERECO   NUMBER (8) NOT NULL ,
    COD_TIPO_ENDERECO             NUMBER (8) NOT NULL ,
    COD_PRODUTO                  VARCHAR2 (20) NOT NULL ,
    DSC_GRADE                    VARCHAR2 (20) NOT NULL ,
    NUM_PRIORIDADE               NUMBER (8)
  ) ;

ALTER TABLE PRODUTO_END_TIPO_ENDERECO
  ADD CONSTRAINT PRODUTO_END_TIPO_ENDERECO_PK PRIMARY KEY ( COD_PRODUTO_END_TIPO_ENDERECO ) ;

ALTER TABLE PRODUTO_END_TIPO_ENDERECO
  ADD CONSTRAINT PROD_END_TIPO_ENDERECO_PROD_FK FOREIGN KEY (COD_PRODUTO, DSC_GRADE) REFERENCES PRODUTO (COD_PRODUTO,DSC_GRADE) NOT DEFERRABLE;

ALTER TABLE PRODUTO_END_TIPO_ENDERECO
  ADD CONSTRAINT PROD_END_TIPO_END_TPEND_FK FOREIGN KEY ( COD_TIPO_ENDERECO ) REFERENCES TIPO_ENDERECO ( COD_TIPO_ENDERECO ) NOT DEFERRABLE ;

CREATE SEQUENCE SQ_PROD_END_TIPO_ENDERECO
INCREMENT BY 1
START WITH 1
MAXVALUE 999999999999999999999999999
MINVALUE 0
NOCYCLE
NOCACHE
NOORDER;

ALTER TABLE PRODUTO
  ADD ( COD_ENDERECO_REF_END_AUTO NUMBER (8));

ALTER TABLE PRODUTO
  ADD CONSTRAINT PRODUTO_ENDERECO_REFERENCIA_FK FOREIGN KEY ( COD_ENDERECO_REF_END_AUTO ) REFERENCES DEPOSITO_ENDERECO ( COD_DEPOSITO_ENDERECO ) NOT DEFERRABLE ;
