ALTER TABLE PRODUTO_EMBALAGEM ADD (
    DTH_INATIVACAO TIMESTAMP,
    COD_USUARIO_INATIVACAO NUMBER(8)
);

ALTER TABLE PRODUTO_VOLUME ADD (
    DTH_INATIVACAO TIMESTAMP,
    COD_USUARIO_INATIVACAO NUMBER(8)
);