INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (1, 'Controle de funcionalidades no sistema',null, SYSDATE);
INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (2, 'Prefixos nos códigos de barras indernos de produtos',null, SYSDATE);
INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (3, 'Correçao da integração de pedidos com o winthor','4 exemplo-novas-integracoes.sql', SYSDATE);
INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (4, 'Alteração da estrutura para autorizar recebimento cego',null, SYSDATE);
INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (5, 'Correçao da inserção de itinerarios (run flush não definido)',null, SYSDATE);
INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (6, 'Compatibilidade do recebimento no coletor com versões anteriores do php',null, SYSDATE);
INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (7, 'Tirando o limite de time out do envio de pedidos',null, SYSDATE);
INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (8, 'Habilitado fornecedor pessoa fisica','8 habilitando-fornecedor-pessoa-fisica.sql', SYSDATE);
INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (9, 'Inclusão de conexão MySql na integração e propriedades de produto',NULL , SYSDATE);
INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (10, 'Gravando log dos WebServices request','9 logWs.sql', SYSDATE);
INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (11, 'Criando Classe Math para conceito de divisao e modulo',null,SYSDATE);
INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (12, 'Modelo de etiqueta separado entre Picking e Pulmão', '10 modelo-etiqueta-pulmao.sql',SYSDATE);
INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (13, 'Reformatação de relatorios PDF automaticos do grid com controle de comprimento de strings', null,SYSDATE);
INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (14, 'Alteração de consulta para exibição de cubagem e peso por expedição', null,SYSDATE);
INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (15, 'Inclusão de mensagem para registro de andamento de recebimento com divergência', null,SYSDATE);
INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (16, 'Consulta de produto no coletor pelo codigo interno', null,SYSDATE);
INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (17, 'Mensagem amigavel para conferencia cega quando não houver conferente', null,SYSDATE);
INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (18, 'Exibindo o fator da embalagem a ser ressuprida', null,SYSDATE);
INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (xx, 'Integração de NF: Ao não encontrar o fornecedor, assumir o padrão de devolução', null,SYSDATE);
INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (xx, 'Corrigindo o percentual de conferencia da expedição no coletor', null,SYSDATE);
INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (xx, 'Tirando a obrigatoriedade de informar unitizador nas operações de saida na tela de movimentação manual', null,SYSDATE);
INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (xx, 'Correção: Forçar finalização da expedição com senha (gerando as conferencias ao finalizar a expedição)', null,SYSDATE);
INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (xx, 'Exportação em csv/pdf do grid de produtividade detalhado', null,SYSDATE);
INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (xx, 'Correção: Considerando embalagens inativas na geração do ressuprimento', null,SYSDATE);
INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (xx, 'Exibindo o endereço de picking do produto no coletor', null,SYSDATE);
INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (xx, 'Exibindo as embalagens do produto na tela de movimentação manual', null,SYSDATE);
INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (xx, 'Alerta de confirmação para cancelar inventario', null,SYSDATE);
INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (xx, 'Relatório de Carregamento: Alterando posição do campo cliente para aparecer após a sequencia', null,SYSDATE);
INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (xx, 'Exibindo o nome de fornecedor na listagem de recebimentos do coletor', null,SYSDATE);
INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (xx, 'Exibindo o endereço de picking no relatório de produtos não endereçados', null,SYSDATE);
INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (xx, 'Log de alteração de picking/capacidade de picking', null,SYSDATE);
