INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (1, 'Controle de funcionalidades no sistema',null, SYSDATE);
INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (2, 'Prefixos nos códigos de barras indernos de produtos',null, SYSDATE);
INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (3, 'Correçao da integração de pedidos com o winthor','4 exemplo-novas-integracoes.sql', SYSDATE);
INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (4, 'Alteração da estrutura para autorizar recebimento cego',null, SYSDATE);
INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (5, 'Correçao da inserção de itinerarios (run flush não definido)',null, SYSDATE);
INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (6, 'Compatibilidade do recebimento no coletor com versões anteriores do php',null, SYSDATE);
INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (7, 'Tirando o limite de time out do envio de pedidos',null, SYSDATE);
INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (8, 'Habilitado fornecedor pessoa fisica','8 habilitando-fornecedor-pessoa-fisica.sql', SYSDATE);
INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (9, 'Inclusão de conexão MySql na integração e propriedades de produto',NULL , SYSDATE);
INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (10, 'Gravando log dos WebServices request','9 logWs.sql', SYSDATE);
INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (11, 'Criando Classe Math para conceito de divisao e modulo',null,SYSDATE);
INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (12, 'Modelo de etiqueta separado entre Picking e Pulmão', '10 modelo-etiqueta-pulmao.sql',SYSDATE);
INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (13, 'Reformatação de relatorios PDF automaticos do grid com controle de comprimento de strings', null,SYSDATE);
INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (14, 'Alteração de consulta para exibição de cubagem e peso por expedição', null,SYSDATE);
INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (15, 'Inclusão de mensagem para registro de andamento de recebimento com divergência', null,SYSDATE);
INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (16, 'Consulta de produto no coletor pelo codigo interno', null,SYSDATE);
INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (17, 'Mensagem amigavel para conferencia cega quando não houver conferente', null,SYSDATE);
INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (18, 'Exibindo o fator da embalagem a ser ressuprida', null,SYSDATE);
INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (19, 'Permite ou não salvar as embalagens de integração como ativas, de acordo com o parametro selecionado', '11-inserir-embalagem-inativa.sql', sysdate);
INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (20, 'Integração de NF: Ao não encontrar o fornecedor, assumir o padrão de devolução', null,SYSDATE);
INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (21, 'Corrigindo o percentual de conferencia da expedição no coletor', null,SYSDATE);
INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (22, 'Tirando a obrigatoriedade de informar unitizador nas operações de saida na tela de movimentação manual', null,SYSDATE);
INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (23, 'Correção: Forçar finalização da expedição com senha (gerando as conferencias ao finalizar a expedição)', null,SYSDATE);
INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (24, 'Exportação em csv/pdf do grid de produtividade detalhado', null,SYSDATE);
INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (25, 'Correção: Considerando embalagens inativas na geração do ressuprimento', null,SYSDATE);
INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (26, 'Exibindo o endereço de picking do produto no coletor', null,SYSDATE);
INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (27, 'Exibindo as embalagens do produto na tela de movimentação manual', null,SYSDATE);
INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (28, 'Alerta de confirmação para cancelar inventario', null,SYSDATE);
INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (29, 'Relatório de Carregamento: Alterando posição do campo cliente para aparecer após a sequencia', null,SYSDATE);
INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (30, 'Exibindo o nome de fornecedor na listagem de recebimentos do coletor', null,SYSDATE);
INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (31, 'Exibindo o endereço de picking no relatório de produtos não endereçados', null,SYSDATE);
INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (32, 'Log de alteração de picking/capacidade de picking', null,SYSDATE);
INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (33, 'Alerta na tela inicial de produtos com estoque sem capacidade de picking definida', null,SYSDATE);
INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (34, 'Destacando a atividade no relatório de produtividade detalhada', null,SYSDATE);
INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (35, 'Correção: Alterando a capacidade de picking e o picking apenas se for informado um picking dinamico', null,SYSDATE);
INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (36, 'Relatório de Produtividade: Permitir tirar o sintetico geral ou detalhado por dia', null,SYSDATE);
INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (37, 'Ocultando botão de gerar ressuprimento para evitar requisições assincronas', null,SYSDATE);
INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (38, 'Mostrar a quantidade em caixa master em todas as telas do coletor do ressuprimento', null,SYSDATE);
INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (39, 'Validação da conferencia de mapas consolidados no checkout, ao finalizar a expedição por desktop', null,SYSDATE);
INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (40, 'Ao finalizar a expedição no desktop, não esta exibindo alertas informando que a expedição foi finalizada', null,SYSDATE);
INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (41, 'Problema ao forçar a finalização de expedição caso o mapa ja tenha iniciado a conferencia.', null,SYSDATE);
INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (42, 'Melhoria de performance na geração de ressuprimento. Evitando multiplas chamadas ao banco', null,SYSDATE);
INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (43, 'Melhoria na tela de apontamento para Etiqueta', '12-imprimir-codigo-barras-cpf.sql',SYSDATE);
INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (44, 'Tratamento de integração de nota via consulta', null,SYSDATE);
