INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (1, 'Controle de funcionalidades no sistema',null, SYSDATE);
INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (2, 'Prefixos nos códigos de barras indernos de produtos',null, SYSDATE);
INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (3, 'Correçao da integração de pedidos com o winthor','4 exemplo-novas-integracoes.sql', SYSDATE);
INSERT INTO FUNCIONALIDADES (COD_FUNCIONALIDADE, DSC_FUNCIONALIDADE, SCRIPT, DTH_ATUALIZACAO) VALUES (3, 'Alteração da estrutura para autorizar recebimento cego',null, SYSDATE);

