CREATE TABLE ETIQUETA_MAE
  (
    COD_ETIQUETA_MAE NUMBER (8) NOT NULL ,
    DSC_QUEBRA       CHAR (400) ,
    COD_EXPEDICAO    NUMBER (8) NOT NULL
  )
  LOGGING ;

ALTER TABLE ETIQUETA_MAE 
  ADD CONSTRAINT ETIQUETA_MAE_PK PRIMARY KEY ( COD_ETIQUETA_MAE ) ;

CREATE TABLE ETIQUETA_MAE_QUEBRA
  (
    COD_ETIQUETA_MAE_QUEBRA NUMBER (8) NOT NULL ,
    IND_TIPO_QUEBRA         CHAR (1) NOT NULL,
    COD_QUEBRA              NUMBER (8) NOT NULL,
    COD_ETIQUETA_MAE        NUMBER (8) NOT NULL
  )
  LOGGING ;

ALTER TABLE ETIQUETA_MAE_QUEBRA 
  ADD CONSTRAINT ETIQUETA_MAE_QUEBRA_PK PRIMARY KEY ( COD_ETIQUETA_MAE_QUEBRA ) ;

CREATE TABLE ETIQUETA_PULMAO_DOCA
  (
    COD_ETIQUETA_PULMAO_DOCA NUMBER (8) NOT NULL ,
    DTH_CONFERENCIA          TIMESTAMP ,
    COD_STATUS               NUMBER (8) NOT NULL,
    COD_PRODUTO              VARCHAR2 (20) NOT NULL,
    DSC_GRADE                VARCHAR2 (20) NOT NULL,
    DSC_REIMPRESSAO          VARCHAR2 (120) ,
    COD_OS                   NUMBER (8) ,
    COD_OS_TRANSBORDO        NUMBER (8) ,
    COD_DEPOSITO_ENDERECO    NUMBER (8) NOT NULL,
    COD_EXPEDICAO            NUMBER (8) NOT NULL ,
    COD_CLIENTE              NUMBER (8) ,
    COD_PRACA                NUMBER (8)
  )
  LOGGING ;

ALTER TABLE ETIQUETA_PULMAO_DOCA 
  ADD CONSTRAINT ETIQUETA_PULMAO_DOCA_PK PRIMARY KEY ( COD_ETIQUETA_PULMAO_DOCA ) ;

CREATE TABLE ETIQUETA_PULMAO_DOCA_PRODUTO
  (
    COD_ETIQUETA_PULMAO_DOCA_PROD NUMBER (8) NOT NULL ,
    COD_ETIQUETA_PULMAO_DOCA      NUMBER (8) NOT NULL ,
    COD_PRODUTO_EMBALAGEM         NUMBER (8) ,
    COD_PRODUTO_VOLUME            NUMBER (8) ,
    QTD_PRODUTO                   NUMBER (8)
  )
  LOGGING ;

ALTER TABLE ETIQUETA_PULMAO_DOCA_PRODUTO 
  ADD CONSTRAINT ETQ_PULMAO_DOCA_PROD_PK PRIMARY KEY ( COD_ETIQUETA_PULMAO_DOCA_PROD ) ;

ALTER TABLE ETIQUETA_SEPARACAO 
  ADD ( QTD_PRODUTO NUMBER (8),
        COD_ETIQUETA_MAE NUMBER (8) ) ;

ALTER TABLE PEDIDO 
  ADD (IND_ETIQUETA_MAPA_GERADO CHAR (1)) ;


ALTER TABLE ETIQUETA_MAE 
  ADD CONSTRAINT ETQ_MAE_EXP_FQ FOREIGN KEY ( COD_EXPEDICAO ) REFERENCES EXPEDICAO ( COD_EXPEDICAO ) NOT DEFERRABLE ;

ALTER TABLE ETIQUETA_MAE_QUEBRA 
  ADD CONSTRAINT ETQ_MAE_QUEBRA_FK FOREIGN KEY ( COD_ETIQUETA_MAE ) REFERENCES ETIQUETA_MAE ( COD_ETIQUETA_MAE ) NOT DEFERRABLE ;

ALTER TABLE ETIQUETA_PULMAO_DOCA 
  ADD CONSTRAINT ETQ_PULMAO_DOCA_EXP FOREIGN KEY ( COD_EXPEDICAO ) REFERENCES EXPEDICAO ( COD_EXPEDICAO ) NOT DEFERRABLE ;

ALTER TABLE ETIQUETA_PULMAO_DOCA 
  ADD CONSTRAINT ETQ_PULMAO_DOCA_END FOREIGN KEY ( COD_DEPOSITO_ENDERECO ) REFERENCES DEPOSITO_ENDERECO ( COD_DEPOSITO_ENDERECO ) NOT DEFERRABLE ;

ALTER TABLE ETIQUETA_PULMAO_DOCA_PRODUTO 
  ADD CONSTRAINT ETQ_PULMAO_DOCA_PROD FOREIGN KEY ( COD_ETIQUETA_PULMAO_DOCA ) REFERENCES ETIQUETA_PULMAO_DOCA ( COD_ETIQUETA_PULMAO_DOCA ) NOT DEFERRABLE ;

ALTER TABLE ETIQUETA_SEPARACAO 
  ADD CONSTRAINT ES_ETQ_MAE_FK FOREIGN KEY ( COD_ETIQUETA_MAE ) REFERENCES ETIQUETA_MAE ( COD_ETIQUETA_MAE ) NOT DEFERRABLE;

ALTER TABLE ETIQUETA_PULMAO_DOCA 
   ADD CONSTRAINT ETQ_PD_PROD_FK FOREIGN KEY (COD_PRODUTO, DSC_GRADE) REFERENCES PRODUTO (COD_PRODUTO,DSC_GRADE) NOT DEFERRABLE;

ALTER TABLE ETIQUETA_PULMAO_DOCA_PRODUTO 
  ADD CONSTRAINT  ETQ_PD_EMB FOREIGN KEY (COD_PRODUTO_EMBALAGEM) REFERENCES PRODUTO_EMBALAGEM(COD_PRODUTO_EMBALAGEM) NOT DEFERRABLE ;

ALTER TABLE ETIQUETA_PULMAO_DOCA
  ADD CONSTRAINT  ETQ_PD_PRACA FOREIGN KEY (COD_PRACA) REFERENCES PRACA(COD_PRACA) NOT DEFERRABLE ;

ALTER TABLE ETIQUETA_PULMAO_DOCA
  ADD CONSTRAINT  ETQ_PD_CLIENTE FOREIGN KEY (COD_CLIENTE) REFERENCES CLIENTE (COD_PESSOA) NOT DEFERRABLE ;

CREATE SEQUENCE  SQ_ETIQUETA_MAE_01  MINVALUE 0 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
CREATE SEQUENCE  SQ_ETIQUETA_MAE_QUEBRA_01  MINVALUE 0 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
CREATE SEQUENCE  SQ_ETIQUETA_PULMAO_DOCA_01  MINVALUE 0 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;

CREATE SEQUENCE  SQ_ETIQUETA_PULMAO_DOCA_PR_01  MINVALUE 0 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;

CREATE INDEX PEDIDO_INDEX1 ON PEDIDO (IND_ETIQUETA_MAPA_GERADO ASC) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

update PEDIDO SET IND_ETIQUETA_MAPA_GERADO='N';
