INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'enderecamento:movimentacao'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'consultar'), 'Consultar detalhes do Estoque');

INSERT INTO RECURSO (COD_RECURSO, DSC_RECURSO, COD_RECURSO_PAI, NOM_RECURSO) VALUES (SQ_RECURSO_01.NEXTVAL, 'Relatório Produtos Armazenados em picking incorretos', 0, 'enderecamento:relatorio_produtos-endereco-incorreto');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'enderecamento:relatorio_produtos-endereco-incorreto'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'index'), 'Início');
INSERT INTO MENU_ITEM (COD_MENU_ITEM, COD_RECURSO_ACAO, COD_PAI, DSC_MENU_ITEM, NUM_PESO, DSC_URL,SHOW) VALUES (SQ_MENU_ITEM_01.NEXTVAL, (SELECT COD_RECURSO_ACAO FROM RECURSO_ACAO WHERE COD_RECURSO = (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'enderecamento:relatorio_produtos-endereco-incorreto') AND COD_ACAO = (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'index')), (SELECT COD_MENU_ITEM FROM MENU_ITEM WHERE COD_PAI = 54 AND DSC_MENU_ITEM = 'Armazenagem'), 'Produtos Com Estoque em Pickins Errados', 10, '#', 'S');

CREATE VIEW V_PALETE_DISPONIVEL_PICKING
AS SELECT PK.COD_DEPOSITO_ENDERECO,
       U.COD_UNITIZADOR,
       U.NUM_LARGURA_UNITIZADOR * 100 as TAMANHO_UNITIZADOR
  FROM UNITIZADOR U, (
 SELECT COD_DEPOSITO_ENDERECO,
        CASE WHEN (TAM.TAMANHO_LONGARINA -OCUPADO) < 0 THEN 0
             ELSE (TAM.TAMANHO_LONGARINA -OCUPADO)
        END AS TAMANHO_DISPONIVEL
   FROM DEPOSITO_ENDERECO DE
   LEFT JOIN (SELECT SUM(OCUPADO) AS OCUPADO,
                     NUM_PREDIO,
                     NUM_NIVEL,
                     NUM_RUA,
                     TAMANHO_LONGARINA
                FROM (SELECT NVL(E.TAM,0) * 100 as OCUPADO,
                             DE.NUM_PREDIO,
                             DE.NUM_NIVEL,
                             DE.NUM_RUA,
                             DE.NUM_APARTAMENTO,
                             NVL(TL.TAMANHO,TP.DSC_VALOR_PARAMETRO) as TAMANHO_LONGARINA
                FROM DEPOSITO_ENDERECO DE
                LEFT JOIN (SELECT DE.COD_DEPOSITO_ENDERECO, MAX(U.NUM_LARGURA_UNITIZADOR) as TAM
                             FROM PRODUTO P
                        LEFT JOIN PRODUTO_VOLUME PV ON PV.COD_PRODUTO = P.COD_PRODUTO AND PV.DSC_GRADE = P.DSC_GRADE
                        LEFT JOIN PRODUTO_EMBALAGEM PE ON PE.COD_PRODUTO = P.COD_PRODUTO AND PE.DSC_GRADE = P.DSC_GRADE
                        LEFT JOIN PRODUTO_DADO_LOGISTICO PDL ON PDL.COD_PRODUTO_EMBALAGEM = PE.COD_PRODUTO_EMBALAGEM
                        LEFT JOIN NORMA_PALETIZACAO NP ON NP.COD_NORMA_PALETIZACAO = PV.COD_NORMA_PALETIZACAO OR NP.COD_NORMA_PALETIZACAO = PDL.COD_NORMA_PALETIZACAO
                        LEFT JOIN UNITIZADOR U ON U.COD_UNITIZADOR = NP.COD_UNITIZADOR
                       INNER JOIN DEPOSITO_ENDERECO DE ON DE.COD_DEPOSITO_ENDERECO = PV.COD_DEPOSITO_ENDERECO OR DE.COD_DEPOSITO_ENDERECO = PE.COD_DEPOSITO_ENDERECO
                       GROUP BY DE.COD_DEPOSITO_ENDERECO) E ON E.COD_DEPOSITO_ENDERECO = DE.COD_DEPOSITO_ENDERECO
                LEFT JOIN TAMANHO_LONGARINA TL ON DE.NUM_PREDIO = TL.NUM_PREDIO AND DE.NUM_RUA = TL.NUM_RUA
                LEFT JOIN PARAMETRO         TP ON TP.DSC_PARAMETRO = 'TAMANHO_LONGARINA_PADRAO'
                WHERE DE.COD_CARACTERISTICA_ENDERECO = 37)
               GROUP BY NUM_PREDIO,
                        NUM_NIVEL,
                        NUM_RUA,
                        TAMANHO_LONGARINA) TAM ON TAM.NUM_PREDIO = DE.NUM_PREDIO
                                              AND TAM.NUM_NIVEL = DE.NUM_NIVEL
                                              AND TAM.NUM_RUA = DE.NUM_RUA
  WHERE DE.COD_CARACTERISTICA_ENDERECO = 37
    AND DE.COD_DEPOSITO_ENDERECO NOT IN (SELECT DISTINCT COD_DEPOSITO_ENDERECO
                                           FROM PRODUTO_EMBALAGEM
                                          WHERE COD_DEPOSITO_ENDERECO IS NOT NULL)
    AND DE.COD_DEPOSITO_ENDERECO NOT IN (SELECT DISTINCT COD_DEPOSITO_ENDERECO
                                           FROM PRODUTO_VOLUME
                                          WHERE COD_DEPOSITO_ENDERECO IS NOT NULL)
    AND DE.IND_ATIVO = 'S') PK
  WHERE PK.TAMANHO_DISPONIVEL - (U.NUM_LARGURA_UNITIZADOR * 100) >= 0;

INSERT INTO PARAMETRO (COD_PARAMETRO, COD_CONTEXTO_PARAMETRO, DSC_PARAMETRO, DSC_TITULO_PARAMETRO, IND_PARAMETRO_SISTEMA, COD_TIPO_ATRIBUTO, DSC_VALOR_PARAMETRO) VALUES (SQ_PARAMETRO_01.NEXTVAL, (SELECT COD_CONTEXTO_PARAMETRO FROM CONTEXTO_PARAMETRO WHERE DSC_CONTEXTO_PARAMETRO = 'PARAMETROS DO SISTEMA'),'UTILIZA_GRADE', 'Utiliza Grade no Sistema (S/N)','N','A','S');
