INSERT INTO RECURSO (COD_RECURSO, DSC_RECURSO, COD_RECURSO_PAI, NOM_RECURSO) VALUES (SQ_RECURSO_01.NEXTVAL, 'Index Inventario', 0, 'inventario:index');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'inventario:index'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'index'), 'Index');
INSERT INTO MENU_ITEM (COD_MENU_ITEM, COD_RECURSO_ACAO, COD_PAI, DSC_MENU_ITEM, NUM_PESO, DSC_URL, SHOW) VALUES (SQ_MENU_ITEM_01.NEXTVAL, (SELECT COD_RECURSO_ACAO FROM RECURSO_ACAO WHERE COD_RECURSO = (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'inventario:index') AND COD_ACAO = (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'index')), (SELECT COD_MENU_ITEM FROM MENU_ITEM WHERE DSC_MENU_ITEM = 'Inventário' AND COD_PAI = 0), 'Monitoramento', 1, '#', 'S');

INSERT INTO RECURSO (COD_RECURSO, DSC_RECURSO, COD_RECURSO_PAI, NOM_RECURSO) VALUES (SQ_RECURSO_01.NEXTVAL, 'Inventario Parcial', 0, 'inventario:parcial');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'inventario:parcial'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'index'), 'Index Parcial');
INSERT INTO MENU_ITEM (COD_MENU_ITEM, COD_RECURSO_ACAO, COD_PAI, DSC_MENU_ITEM, NUM_PESO, DSC_URL, SHOW) VALUES (SQ_MENU_ITEM_01.NEXTVAL, (SELECT COD_RECURSO_ACAO FROM RECURSO_ACAO WHERE COD_RECURSO = (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'inventario:parcial') AND COD_ACAO = (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'index')), (SELECT COD_MENU_ITEM FROM MENU_ITEM WHERE DSC_MENU_ITEM = 'Inventário' AND COD_PAI = 0), 'Parcial', 1, '#', 'S');

INSERT INTO ACAO (COD_ACAO, DSC_ACAO, NOM_ACAO) VALUES (SQ_ACAO_01.NEXTVAL, 'Produto', 'produto');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'inventario:parcial'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'produto'), 'Inventario Parcial por produto');

INSERT INTO ACAO (COD_ACAO, DSC_ACAO, NOM_ACAO) VALUES (SQ_ACAO_01.NEXTVAL, 'Endereco', 'endereco');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'inventario:parcial'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'endereco'), 'Inventario Parcial por endereco');

INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'inventario:index'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'atualizar'), 'Atualizar Estoque');

INSERT INTO RECURSO (COD_RECURSO, DSC_RECURSO, COD_RECURSO_PAI, NOM_RECURSO) VALUES (SQ_RECURSO_01.NEXTVAL, 'Relatorio Avaria', 0, 'inventario:relatorio_avaria');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'inventario:relatorio_avaria'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'index'), 'Index Relatorio avaria');
INSERT INTO MENU_ITEM (COD_MENU_ITEM, COD_RECURSO_ACAO, COD_PAI, DSC_MENU_ITEM, NUM_PESO, DSC_URL, SHOW) VALUES (SQ_MENU_ITEM_01.NEXTVAL, (SELECT COD_RECURSO_ACAO FROM RECURSO_ACAO WHERE COD_RECURSO = (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'inventario:relatorio_avaria') AND COD_ACAO = (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'index')), (SELECT COD_MENU_ITEM FROM MENU_ITEM WHERE DSC_MENU_ITEM = 'Inventário' AND COD_PAI = 0), 'Relatorio Avaria', 1, '#', 'N');

INSERT INTO RECURSO (COD_RECURSO, DSC_RECURSO, COD_RECURSO_PAI, NOM_RECURSO) VALUES (SQ_RECURSO_01.NEXTVAL, 'Relatorio Divergencia', 0, 'inventario:relatorio_divergencia');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'inventario:relatorio_divergencia'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'index'), 'Index Relatorio Divergencia');
INSERT INTO MENU_ITEM (COD_MENU_ITEM, COD_RECURSO_ACAO, COD_PAI, DSC_MENU_ITEM, NUM_PESO, DSC_URL, SHOW) VALUES (SQ_MENU_ITEM_01.NEXTVAL, (SELECT COD_RECURSO_ACAO FROM RECURSO_ACAO WHERE COD_RECURSO = (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'inventario:relatorio_divergencia') AND COD_ACAO = (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'index')), (SELECT COD_MENU_ITEM FROM MENU_ITEM WHERE DSC_MENU_ITEM = 'Inventário' AND COD_PAI = 0), 'Relatorio Divergencia', 1, '#', 'N');

INSERT INTO ACAO (COD_ACAO, DSC_ACAO, NOM_ACAO) VALUES (SQ_ACAO_01.NEXTVAL, 'Cancelar', 'cancelar');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'inventario:index'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'cancelar'), 'Index');

INSERT INTO "CONTEXTO_PARAMETRO" (COD_CONTEXTO_PARAMETRO, DSC_CONTEXTO_PARAMETRO) VALUES ('22', 'INVENTARIO');
INSERT INTO PARAMETRO (COD_PARAMETRO, COD_CONTEXTO_PARAMETRO, DSC_PARAMETRO, DSC_TITULO_PARAMETRO, IND_PARAMETRO_SISTEMA, COD_TIPO_ATRIBUTO, DSC_VALOR_PARAMETRO) VALUES (SQ_PARAMETRO_01.NEXTVAL, (SELECT COD_CONTEXTO_PARAMETRO FROM CONTEXTO_PARAMETRO WHERE DSC_CONTEXTO_PARAMETRO = 'INVENTARIO'),'CONTROLE_VALIDADE', 'Controle de validade','N','A','N');
INSERT INTO PARAMETRO (COD_PARAMETRO, COD_CONTEXTO_PARAMETRO, DSC_PARAMETRO, DSC_TITULO_PARAMETRO, IND_PARAMETRO_SISTEMA, COD_TIPO_ATRIBUTO, DSC_VALOR_PARAMETRO) VALUES (SQ_PARAMETRO_01.NEXTVAL, (SELECT COD_CONTEXTO_PARAMETRO FROM CONTEXTO_PARAMETRO WHERE DSC_CONTEXTO_PARAMETRO = 'INVENTARIO'),'EXIGENCIA_UMA', 'Exigencia de uma','N','A','N');
INSERT INTO PARAMETRO (COD_PARAMETRO, COD_CONTEXTO_PARAMETRO, DSC_PARAMETRO, DSC_TITULO_PARAMETRO, IND_PARAMETRO_SISTEMA, COD_TIPO_ATRIBUTO, DSC_VALOR_PARAMETRO) VALUES (SQ_PARAMETRO_01.NEXTVAL, (SELECT COD_CONTEXTO_PARAMETRO FROM CONTEXTO_PARAMETRO WHERE DSC_CONTEXTO_PARAMETRO = 'INVENTARIO'),'REGRA_CONTAGEM', '1- Primeira definitiva 2 - Duas contagens iguais necessarias','N','A','1');
INSERT INTO PARAMETRO (COD_PARAMETRO, COD_CONTEXTO_PARAMETRO, DSC_PARAMETRO, DSC_TITULO_PARAMETRO, IND_PARAMETRO_SISTEMA, COD_TIPO_ATRIBUTO, DSC_VALOR_PARAMETRO) VALUES (SQ_PARAMETRO_01.NEXTVAL, (SELECT COD_CONTEXTO_PARAMETRO FROM CONTEXTO_PARAMETRO WHERE DSC_CONTEXTO_PARAMETRO = 'INVENTARIO'),'VALIDA_ESTOQUE_ATUAL', 'Validacao com estoque atual','N','A','S');
INSERT INTO PARAMETRO (COD_PARAMETRO, COD_CONTEXTO_PARAMETRO, DSC_PARAMETRO, DSC_TITULO_PARAMETRO, IND_PARAMETRO_SISTEMA, COD_TIPO_ATRIBUTO, DSC_VALOR_PARAMETRO) VALUES (SQ_PARAMETRO_01.NEXTVAL, (SELECT COD_CONTEXTO_PARAMETRO FROM CONTEXTO_PARAMETRO WHERE DSC_CONTEXTO_PARAMETRO = 'INVENTARIO'),'RECONTAGEM_MESMO_USUARIO', 'Permitir o mesmo usuário fazer mais de uma contagem','N','A','S');

INSERT INTO "TIPO_SIGLA" (COD_TIPO_SIGLA, DSC_TIPO_SIGLA, IND_SIGLA_SISTEMA) VALUES ('75', 'STATUS INVENTARIO', 'S');
INSERT INTO SIGLA (COD_SIGLA, COD_TIPO_SIGLA, DSC_SIGLA, COD_REFERENCIA_SIGLA) VALUES (542, (SELECT COD_TIPO_SIGLA FROM TIPO_SIGLA WHERE DSC_TIPO_SIGLA = 'STATUS INVENTARIO'), 'GERADO', 'G');
INSERT INTO SIGLA (COD_SIGLA, COD_TIPO_SIGLA, DSC_SIGLA, COD_REFERENCIA_SIGLA) VALUES (543, (SELECT COD_TIPO_SIGLA FROM TIPO_SIGLA WHERE DSC_TIPO_SIGLA = 'STATUS INVENTARIO'), 'LIBERADO', 'L');
INSERT INTO SIGLA (COD_SIGLA, COD_TIPO_SIGLA, DSC_SIGLA, COD_REFERENCIA_SIGLA) VALUES (544, (SELECT COD_TIPO_SIGLA FROM TIPO_SIGLA WHERE DSC_TIPO_SIGLA = 'STATUS INVENTARIO'), 'FINALIZADO', 'F');
INSERT INTO SIGLA (COD_SIGLA, COD_TIPO_SIGLA, DSC_SIGLA, COD_REFERENCIA_SIGLA) VALUES (545, (SELECT COD_TIPO_SIGLA FROM TIPO_SIGLA WHERE DSC_TIPO_SIGLA = 'STATUS INVENTARIO'), 'CANCELADO', 'C');

CREATE TABLE INVENTARIO
(
  COD_INVENTARIO  NUMBER (8) NOT NULL ,
  DTH_INICIO      DATE ,
  DTH_FINALIZACAO DATE ,
  COD_STATUS      NUMBER (8)
)
LOGGING ;
ALTER TABLE INVENTARIO ADD CONSTRAINT Inventario_PK PRIMARY KEY ( COD_INVENTARIO ) ;

CREATE SEQUENCE SQ_INVENTARIO_01
INCREMENT BY 1
START WITH 1
MAXVALUE 999999999999999999999999999
MINVALUE 0
NOCYCLE
NOCACHE
NOORDER;

CREATE TABLE INVENTARIO_CONTAGEM_ENDERECO
(
  COD_INV_CONT_END           NUMBER (8) NOT NULL ,
  QTD_AVARIA                 NUMBER (8) ,
  QTD_CONTADA                NUMBER (8) ,
  COD_INVENTARIO_CONTAGEM_OS NUMBER (8) NOT NULL ,
  COD_INVENTARIO_ENDERECO    NUMBER (8) NOT NULL ,
  COD_PRODUTO                VARCHAR2 (20) ,
  DSC_GRADE                  VARCHAR2 (10) ,
  COD_PRODUTO_EMBALAGEM      VARCHAR2 (128 BYTE) ,
  COD_PRODUTO_VOLUME         VARCHAR2 (128 BYTE) ,
  QTD_DIVERGENCIA            NUMBER (8),
  NUM_CONTAGEM               NUMBER (8),
  DIVERGENCIA                CHAR (1)
)
LOGGING ;
ALTER TABLE INVENTARIO_CONTAGEM_ENDERECO ADD CONSTRAINT INV_CONT_EN_PK PRIMARY KEY ( COD_INV_CONT_END ) ;


CREATE SEQUENCE SQ_CONTAGEM_ENDERECO_01
INCREMENT BY 1
START WITH 1
MAXVALUE 999999999999999999999999999
MINVALUE 0
NOCYCLE
NOCACHE
NOORDER;

CREATE TABLE INVENTARIO_CONTAGEM_OS
(
  COD_INVENTARIO_CONTAGEM_OS NUMBER (8) NOT NULL ,
  COD_OS                     NUMBER (8) NOT NULL ,
  COD_INVENTARIO             NUMBER (8) NOT NULL
)
LOGGING ;
ALTER TABLE INVENTARIO_CONTAGEM_OS ADD CONSTRAINT INVENTARIO_CONTAGEM_OS_PK PRIMARY KEY ( COD_INVENTARIO_CONTAGEM_OS ) ;

CREATE SEQUENCE SQ_CONTAGEM_OS_01
INCREMENT BY 1
START WITH 1
MAXVALUE 999999999999999999999999999
MINVALUE 0
NOCYCLE
NOCACHE
NOORDER;

CREATE TABLE INVENTARIO_ENDERECO
(
  COD_INVENTARIO_ENDERECO NUMBER (8) NOT NULL ,
  COD_DEPOSITO_ENDERECO   NUMBER (8) NOT NULL ,
  COD_INVENTARIO          NUMBER (8) NOT NULL ,
  NUM_CONTAGEM            NUMBER (8) ,
  DIVERGENCIA             CHAR (1),
  INVENTARIADO            CHAR (1),
  ATUALIZA_ESTOQUE        CHAR (1)
)
LOGGING ;

CREATE SEQUENCE SQ_INV_END_01
INCREMENT BY 1
START WITH 1
MAXVALUE 999999999999999999999999999
MINVALUE 0
NOCYCLE
NOCACHE
NOORDER;

ALTER TABLE INVENTARIO_ENDERECO ADD CONSTRAINT INVENTARIO_ENDERECO_PK PRIMARY KEY ( COD_INVENTARIO_ENDERECO ) ;

ALTER TABLE INVENTARIO_CONTAGEM_ENDERECO ADD CONSTRAINT INV_CONT_OS_FK FOREIGN KEY ( COD_INVENTARIO_CONTAGEM_OS ) REFERENCES INVENTARIO_CONTAGEM_OS ( COD_INVENTARIO_CONTAGEM_OS ) NOT DEFERRABLE ;

ALTER TABLE INVENTARIO_CONTAGEM_ENDERECO ADD CONSTRAINT INV_CON_END_FK FOREIGN KEY ( COD_INVENTARIO_ENDERECO ) REFERENCES INVENTARIO_ENDERECO ( COD_INVENTARIO_ENDERECO ) NOT DEFERRABLE ;

ALTER TABLE INVENTARIO_CONTAGEM_OS ADD CONSTRAINT INV_CONT_OS_OS_FK FOREIGN KEY ( COD_OS ) REFERENCES ORDEM_SERVICO ( COD_OS ) NOT DEFERRABLE ;

ALTER TABLE INVENTARIO_CONTAGEM_OS ADD CONSTRAINT INV_CONT_OS_INV_FK FOREIGN KEY ( COD_INVENTARIO ) REFERENCES INVENTARIO ( COD_INVENTARIO ) NOT DEFERRABLE ;

ALTER TABLE INVENTARIO_ENDERECO ADD CONSTRAINT INV_END_DE_FK FOREIGN KEY ( COD_DEPOSITO_ENDERECO ) REFERENCES DEPOSITO_ENDERECO ( COD_DEPOSITO_ENDERECO ) NOT DEFERRABLE ;

ALTER TABLE INVENTARIO_ENDERECO ADD CONSTRAINT INV_END_FK FOREIGN KEY ( COD_INVENTARIO ) REFERENCES INVENTARIO ( COD_INVENTARIO ) NOT DEFERRABLE ;

INSERT INTO ATIVIDADE (COD_ATIVIDADE, DSC_ATIVIDADE, COD_SETOR_OPERACIONAL) VALUES (14, 'INVENTARIO',1);