CREATE TABLE MAPA_SEPARACAO
  (
    COD_MAPA_SEPARACAO NUMBER (8) NOT NULL ,
    COD_EXPEDICAO      NUMBER (8) NOT NULL,
    DTH_CRIACAO        DATE NOT NULL,
    COD_STATUS         NUMBER (8) NOT NULL,
    DSC_QUEBRA         CHAR (400)
  )
  LOGGING ;

ALTER TABLE MAPA_SEPARACAO
  ADD CONSTRAINT MAPA_SEPARACAO_PK PRIMARY KEY ( COD_MAPA_SEPARACAO ) ;

CREATE TABLE MAPA_SEPARACAO_QUEBRA
  (
    COD_MAPA_SEPARACAO_QUEBRA NUMBER (8) NOT NULL ,
    COD_MAPA_SEPARACAO        NUMBER (8) NOT NULL ,
    IND_TIPO_QUEBRA           CHAR (1) NOT NULL,
    COD_QUEBRA                NUMBER (8) NOT NULL
  )
  LOGGING ;

ALTER TABLE MAPA_SEPARACAO_QUEBRA
  ADD CONSTRAINT MAPA_SEPARACAO_QUEBRA_PK PRIMARY KEY (COD_MAPA_SEPARACAO_QUEBRA) ;

CREATE TABLE MAPA_SEPARACAO_PRODUTO
  (
    COD_MAPA_SEPARACAO_PRODUTO NUMBER (8) NOT NULL ,
    COD_MAPA_SEPARACAO         NUMBER (8) NOT NULL ,
    COD_PRODUTO                VARCHAR2 (20 BYTE) NOT NULL,
    DSC_GRADE                  VARCHAR2 (20 BYTE) NOT NULL ,
    COD_PRODUTO_VOLUME         NUMBER (8) ,
    COD_PRODUTO_EMBALAGEM      NUMBER (8) ,
    QTD_EMBALAGEM              NUMBER (8) NOT NULL,
    QTD_SEPARAR                NUMBER (8) NOT NULL,
    COD_PEDIDO_PRODUTO         NUMBER (8),
    IND_CONFERIDO  VARCHAR2(20 BYTE) default 'N'
  )
  LOGGING ;

ALTER TABLE MAPA_SEPARACAO_PRODUTO
  ADD CONSTRAINT MAPA_SEPARACAO_PRODUTO_PK PRIMARY KEY ( COD_MAPA_SEPARACAO_PRODUTO ) ;

ALTER TABLE MAPA_SEPARACAO
  ADD CONSTRAINT MAPA_SEPARACAO_EXP_FK FOREIGN KEY (COD_EXPEDICAO) REFERENCES EXPEDICAO (COD_EXPEDICAO) NOT DEFERRABLE ;

ALTER TABLE MAPA_SEPARACAO
  ADD CONSTRAINT MAPA_SEPARACAO_SIGLA_FK FOREIGN KEY (COD_STATUS) REFERENCES SIGLA (COD_SIGLA) NOT DEFERRABLE ;

ALTER TABLE MAPA_SEPARACAO_QUEBRA
  ADD CONSTRAINT MAPA_SEPARACAO_QUEBRA_MP_FK FOREIGN KEY (COD_MAPA_SEPARACAO) REFERENCES MAPA_SEPARACAO (COD_MAPA_SEPARACAO) NOT DEFERRABLE ;

ALTER TABLE MAPA_SEPARACAO_PRODUTO
  ADD CONSTRAINT MAPA_SEPARACAO_PRODUTO_MP_FK FOREIGN KEY (COD_MAPA_SEPARACAO) REFERENCES MAPA_SEPARACAO (COD_MAPA_SEPARACAO) NOT DEFERRABLE ;

ALTER TABLE MAPA_SEPARACAO_PRODUTO
  ADD CONSTRAINT MAPA_SEPARACAO_PRODUTO_PROD_FK FOREIGN KEY (COD_PRODUTO, DSC_GRADE) REFERENCES PRODUTO (COD_PRODUTO,DSC_GRADE) NOT DEFERRABLE;

ALTER TABLE MAPA_SEPARACAO_PRODUTO
  ADD CONSTRAINT MAPA_SEPARACAO_PRODUTO_PV_FK FOREIGN KEY (COD_PRODUTO_VOLUME) REFERENCES PRODUTO_VOLUME (COD_PRODUTO_VOLUME) NOT DEFERRABLE ;

ALTER TABLE MAPA_SEPARACAO_PRODUTO
  ADD CONSTRAINT MAPA_SEPARACAO_PRODUTO_PE_FK FOREIGN KEY (COD_PRODUTO_EMBALAGEM) REFERENCES PRODUTO_EMBALAGEM (COD_PRODUTO_EMBALAGEM) NOT DEFERRABLE ;

CREATE SEQUENCE  SQ_MAPA_SEPARACAO_01  MINVALUE 0 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
CREATE SEQUENCE  SQ_MAPA_SEPARACAO_PROD_01  MINVALUE 0 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
CREATE SEQUENCE  SQ_MAPA_SEPARACAO_QUEB_01  MINVALUE 0 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;

CREATE TABLE MAPA_SEPARACAO_CONFERENCIA
  (
    COD_MAPA_SEPARACAO_CONFERENCIA NUMBER (8) NOT NULL ,
    COD_MAPA_SEPARACAO             NUMBER (8) NOT NULL ,
    COD_PRODUTO                    VARCHAR2 (20 BYTE) NOT NULL,
    DSC_GRADE                      VARCHAR2 (20 BYTE) NOT NULL ,
    COD_PRODUTO_VOLUME             NUMBER (8) ,
    COD_PRODUTO_EMBALAGEM          NUMBER (8) ,
    QTD_EMBALAGEM                  NUMBER (8) NOT NULL,
    QTD_CONFERIDA                  NUMBER (8) NOT NULL,
    COD_OS                         NUMBER (8) NOT NULL,
    NUM_CONFERENCIA                NUMBER (8) NOT NULL,
    IND_CONFERENCIA_FECHADA        VARCHAR2(20 BYTE) default 'N',
    DTH_CONFERENCIA                DATE ,
    COD_VOLUME_PATRIMONIO          NUMBER (8)
  )
LOGGING ;

ALTER TABLE MAPA_SEPARACAO_CONFERENCIA
  ADD CONSTRAINT MAPA_SEPARACAO_CONF_PK PRIMARY KEY (COD_MAPA_SEPARACAO_CONFERENCIA) ;

ALTER TABLE MAPA_SEPARACAO_CONFERENCIA
  ADD CONSTRAINT MAPA_SEPARACAO_CONF_MP_FK FOREIGN KEY (COD_MAPA_SEPARACAO) REFERENCES MAPA_SEPARACAO (COD_MAPA_SEPARACAO) NOT DEFERRABLE ;

ALTER TABLE MAPA_SEPARACAO_CONFERENCIA
  ADD CONSTRAINT MAPA_SEPARACAO_CONF_PROD_FK FOREIGN KEY (COD_PRODUTO, DSC_GRADE) REFERENCES PRODUTO (COD_PRODUTO,DSC_GRADE) NOT DEFERRABLE;

ALTER TABLE MAPA_SEPARACAO_CONFERENCIA
  ADD CONSTRAINT MAPA_SEPARACAO_CONF_PV_FK FOREIGN KEY (COD_PRODUTO_VOLUME) REFERENCES PRODUTO_VOLUME (COD_PRODUTO_VOLUME) NOT DEFERRABLE ;

ALTER TABLE MAPA_SEPARACAO_CONFERENCIA
  ADD CONSTRAINT MAPA_SEPARACAO_CONF_PE_FK FOREIGN KEY (COD_PRODUTO_EMBALAGEM) REFERENCES PRODUTO_EMBALAGEM (COD_PRODUTO_EMBALAGEM) NOT DEFERRABLE;

ALTER TABLE MAPA_SEPARACAO_CONFERENCIA
  ADD CONSTRAINT MAPA_SEPARACAO_CONF_OS_FK FOREIGN KEY (COD_OS) REFERENCES ORDEM_SERVICO (COD_OS) NOT DEFERRABLE;

ALTER TABLE MAPA_SEPARACAO_CONFERENCIA
  ADD CONSTRAINT MAPA_SEPARACAO_CONF_VP_FK FOREIGN KEY (COD_VOLUME_PATRIMONIO) REFERENCES VOLUME_PATRIMONIO ( COD_VOLUME_PATRIMONIO ) NOT DEFERRABLE ;

CREATE SEQUENCE  SQ_MAPA_SEPARACAO_CONF_01  MINVALUE 0 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;

ALTER TABLE PEDIDO_PRODUTO ADD(
   QTD_ATENDIDA NUMBER(8) DEFAULT 0,
   QTD_CORTADA  NUMBER(8) DEFAULT 0
);

INSERT INTO PARAMETRO (COD_PARAMETRO, COD_CONTEXTO_PARAMETRO, DSC_PARAMETRO, DSC_TITULO_PARAMETRO, IND_PARAMETRO_SISTEMA, COD_TIPO_ATRIBUTO, DSC_VALOR_PARAMETRO) VALUES (SQ_PARAMETRO_01.NEXTVAL, (SELECT COD_CONTEXTO_PARAMETRO FROM CONTEXTO_PARAMETRO WHERE DSC_CONTEXTO_PARAMETRO = 'EXPEDICAO'),'MODELO_SEPARACAO_PADRAO', 'Modelo de Separação Padrão','S','A','1');
