CREATE SEQUENCE  SQ_MODELO_SEPARACAO_01  MINVALUE 0 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;

CREATE TABLE MODELO_SEPARACAO (
  COD_MODELO_SEPARACAO NUMBER(8) PRIMARY KEY,
  TIPO_SEPARACAO_FRACIONADO VARCHAR2(20) CHECK( TIPO_SEPARACAO_FRACIONADO IN ('ETIQUETA','MAPA') ) NOT NULL,
  TIPO_SEPARACAO_NAOFRACIONADO  VARCHAR2(20) CHECK( TIPO_SEPARACAO_NAOFRACIONADO IN ('ETIQUETA','MAPA') ) NOT NULL,
  TIPO_QUEBRA_FRACIONADO VARCHAR2(20) CHECK( TIPO_QUEBRA_FRACIONADO IN ('RUA','PRACA','CLIENTE','SEM QUEBRA','LINHA DE SEPARACAO') )  ,
  TIPO_QUEBRA_NAOFRACIONADO VARCHAR2(20) CHECK( TIPO_QUEBRA_NAOFRACIONADO IN ('RUA','PRACA','CLIENTE','SEM QUEBRA','LINHA DE SEPARACAO') )  ,
  QUEBRA_COLETOR VARCHAR2(20) CHECK( QUEBRA_COLETOR IN ('SIM','NAO') ) NOT NULL,
  EMITIR_ETIQUETA_MAE VARCHAR2(20) CHECK( EMITIR_ETIQUETA_MAE IN ('SIM','NAO') ) NOT NULL,
  EMITIR_ETIQUETA_MAPA VARCHAR2(20) CHECK( EMITIR_ETIQUETA_MAPA IN ('SIM','NAO') ) NOT NULL,
  CONVERSAO_FATOR_PRODUTO VARCHAR2(20) CHECK( CONVERSAO_FATOR_PRODUTO IN ('SIM','NAO') ) NOT NULL
);

CREATE SEQUENCE  SQ_ROTA_01  MINVALUE 0 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;

CREATE TABLE ROTA (
  COD_ROTA NUMBER(8) PRIMARY KEY,
  NOME_ROTA VARCHAR2(50)
);

CREATE SEQUENCE  SQ_ROTA_PRACA_01  MINVALUE 0 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
CREATE TABLE ROTA_PRACA (
  COD_ROTA_PRACA NUMBER(8) PRIMARY KEY,
  COD_ROTA NUMBER(8) ,
  COD_PRACA NUMBER(8)
);

CREATE SEQUENCE  SQ_PRACA_01  MINVALUE 0 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;

CREATE TABLE PRACA (
  COD_PRACA NUMBER(8) PRIMARY KEY,
  NOME_PRACA VARCHAR2(50)
);

CREATE SEQUENCE  SQ_PRACA_FAIXA_01  MINVALUE 0 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;

CREATE TABLE PRACA_FAIXA (
  COD_PRACA_FAIXA NUMBER(8) PRIMARY KEY,
  COD_PRACA NUMBER(8) ,
  FAIXA_CEP1 VARCHAR2(50),
  FAIXA_CEP2 VARCHAR2(50)
);

INSERT INTO RECURSO (COD_RECURSO, DSC_RECURSO, COD_RECURSO_PAI, NOM_RECURSO) VALUES (SQ_RECURSO_01.NEXTVAL, 'Mapa de Separacao', 0, 'modelo-separacao');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO)VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'modelo-separacao'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'add'), 'Cadastrar Modelo de Separação');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO)VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'modelo-separacao'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'edit'), 'Editar Modelo de Separação');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO)VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'modelo-separacao'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'index'), 'Grid Modelo de Separação');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO)VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'modelo-separacao'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'delete'), 'Excluir Modelo de Separação');
INSERT INTO MENU_ITEM (COD_MENU_ITEM, COD_RECURSO_ACAO, COD_PAI, DSC_MENU_ITEM, NUM_PESO, DSC_URL, SHOW) VALUES (SQ_MENU_ITEM_01.NEXTVAL, (SELECT COD_RECURSO_ACAO FROM RECURSO_ACAO WHERE COD_RECURSO = (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'modelo-separacao') and COD_ACAO = (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'index')), (SELECT COD_MENU_ITEM FROM MENU_ITEM WHERE DSC_MENU_ITEM = 'Controle de Acesso' AND COD_PAI = 13), 'Cadastrar Modelo de Separacao', 1, '#', 'S');

INSERT INTO RECURSO (COD_RECURSO, DSC_RECURSO, COD_RECURSO_PAI, NOM_RECURSO) VALUES (SQ_RECURSO_01.NEXTVAL, 'Praça', 0, 'praca');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO)VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'praca'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'add'), 'Cadastrar Praça');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO)VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'praca'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'edit'), 'Alterar Praça');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO)VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'praca'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'index'), 'Grid Praça');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO)VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'praca'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'delete'), 'Excluir Praça');;
INSERT INTO MENU_ITEM (COD_MENU_ITEM, COD_RECURSO_ACAO, COD_PAI, DSC_MENU_ITEM, NUM_PESO, DSC_URL, SHOW) VALUES (SQ_MENU_ITEM_01.NEXTVAL, (SELECT COD_RECURSO_ACAO FROM RECURSO_ACAO WHERE COD_RECURSO = (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'praca') and COD_ACAO = (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'index')), (SELECT COD_MENU_ITEM FROM MENU_ITEM WHERE DSC_MENU_ITEM = 'Controle de Acesso' AND COD_PAI = 13), 'Cadastrar Praça', 1, '#', 'S');

INSERT INTO RECURSO (COD_RECURSO, DSC_RECURSO, COD_RECURSO_PAI, NOM_RECURSO) VALUES (SQ_RECURSO_01.NEXTVAL, 'Rota', 0, 'rota');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO)VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'rota'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'add'), 'Cadastrar Rota');INSERT INTO ACAO (COD_ACAO, DSC_ACAO, NOM_ACAO) VALUES (SQ_ACAO_01.NEXTVAL, 'Pegar Pracas', 'getPracasAjax');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO)VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'rota'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'getPracasAjax'), 'Pegar Praças');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO)VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'rota'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'index'), 'Grid Rota');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO)VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'rota'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'delete'), 'Excluir Rota');
INSERT INTO MENU_ITEM (COD_MENU_ITEM, COD_RECURSO_ACAO, COD_PAI, DSC_MENU_ITEM, NUM_PESO, DSC_URL, SHOW) VALUES (SQ_MENU_ITEM_01.NEXTVAL, (SELECT COD_RECURSO_ACAO FROM RECURSO_ACAO WHERE COD_RECURSO = (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'rota') and COD_ACAO = (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'index')), (SELECT COD_MENU_ITEM FROM MENU_ITEM WHERE DSC_MENU_ITEM = 'Controle de Acesso' AND COD_PAI = 13), 'Cadastrar Rota', 1, '#', 'S');