CREATE TABLE "WMS_DEVELOP"."PEDIDO_ENDERECO" 
   (	"COD_PEDIDO_ENDERECO" NUMBER(8,0), 
	"COD_PEDIDO" NUMBER(8,0), 
	"COD_TIPO_ENDERECO" NUMBER(8,0), 
	"NUM_CEP" VARCHAR2(10 BYTE), 
	"DSC_ENDERECO" VARCHAR2(10 BYTE), 
	"NUM_ENDERECO" VARCHAR2(6 BYTE), 
	"DSC_COMPLEMENTO" VARCHAR2(36 BYTE), 
	"NOM_BAIRRO" VARCHAR2(72 BYTE), 
	"NOM_LOCALIDADE" VARCHAR2(72 BYTE), 
	"COD_UF" NUMBER(8,0), 
	"DSC_PONTO_REFERENCIA" VARCHAR2(255 BYTE), 
	"IND_ENDERECO_ECT" CHAR(1 BYTE), 
	"COD_LOCALIDADE" NUMBER(8,0)
   )