CREATE TABLE NOTA_FISCAL_SAIDA
  (
    COD_NOTA_FISCAL_SAIDA NUMBER (8) NOT NULL,
    NUMERO_NOTA NUMBER (8) NOT NULL,
    SERIE VARCHAR2 (20 BYTE) NOT NULL,
    VALOR_TOTAL_NF NUMBER(15,2) NOT NULL
  );

  CREATE SEQUENCE SQ_NF_SAIDA_01  MINVALUE 0 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;

CREATE TABLE NOTA_FISCAL_SAIDA_PRODUTO
  (
    COD_NOTA_FISCAL_SAIDA_PRODUTO NUMBER (8) NOT NULL,
    COD_PRODUTO VARCHAR2 (20 BYTE) NOT NULL,
    DSC_GRADE VARCHAR2 (20 BYTE) NOT NULL,
    QUANTIDADE NUMBER (8) NOT NULL,
    VALOR_VENDA NUMBER(15,2) NOT NULL,
    COD_NOTA_FISCAL_SAIDA NUMBER(8) NOT NULL
  );

  CREATE SEQUENCE SQ_NF_SAIDA_PRODUTO_01  MINVALUE 0 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;

CREATE TABLE NOTA_FISCAL_SAIDA_PEDIDO
  (
    COD_NOTA_FISCAL_SAIDA_PEDIDO NUMBER (8) NOT NULL,
    COD_NOTA_FISCAL_SAIDA NUMBER (8) NOT NULL,
    COD_PEDIDO NUMBER (8) NOT NULL
  );

  CREATE SEQUENCE SQ_NF_SAIDA_PEDIDO_01  MINVALUE 0 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;

  INSERT INTO PARAMETRO (COD_PARAMETRO, COD_CONTEXTO_PARAMETRO, DSC_PARAMETRO, DSC_TITULO_PARAMETRO, IND_PARAMETRO_SISTEMA, COD_TIPO_ATRIBUTO, DSC_VALOR_PARAMETRO)
VALUES (SQ_PARAMETRO_01.NEXTVAL, 23, 'CONFERE_RECEBIMENTO_REENTREGA', 'Confere Recebimento de Reentrega (S/N)', 'N', 'A', 'S');

INSERT INTO PARAMETRO (COD_PARAMETRO, COD_CONTEXTO_PARAMETRO, DSC_PARAMETRO, DSC_TITULO_PARAMETRO, IND_PARAMETRO_SISTEMA, COD_TIPO_ATRIBUTO, DSC_VALOR_PARAMETRO)
VALUES (SQ_PARAMETRO_01.NEXTVAL, 23, 'CONFERE_EXPEDICAO_REENTREGA', 'Confere Expedição de Reentrega (S/N)', 'N', 'A', 'S');
