CREATE TABLE "SUM_PESO_PRODUTO"
   (	"COD_PRODUTO" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"DSC_GRADE" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"NUM_PESO" NUMBER, 
	"NUM_CUBAGEM" NUMBER, 
	 CONSTRAINT "SUM_PESO_PRODUTO_PK" PRIMARY KEY ("COD_PRODUTO", "DSC_GRADE")
   )
