-- revision 2013-02-21 - Menu Expedicao - Mateus Azevedo

-- gravo recurso
INSERT INTO RECURSO (COD_RECURSO, DSC_RECURSO, COD_RECURSO_PAI, NOM_RECURSO) VALUES (SQ_RECURSO_01.NEXTVAL, 'Expedição', 0, 'expedicao:index');
-- gravo permissoes
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'expedicao:index'), 5, 'Início');

-- gravo menu
INSERT INTO MENU_ITEM (COD_MENU_ITEM, COD_RECURSO_ACAO, COD_PAI, DSC_MENU_ITEM, NUM_PESO, DSC_URL) VALUES (SQ_MENU_ITEM_01.NEXTVAL, (SELECT COD_RECURSO_ACAO FROM RECURSO_ACAO WHERE COD_RECURSO = (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'expedicao:index') AND COD_ACAO = '5'), 53, 'Expedição Mercadorias', 10, '#');

-- revision 2013-02-22 - Mateus Azevedo

-- revision 2013-03-05

INSERT INTO "TIPO_SIGLA" (COD_TIPO_SIGLA, DSC_TIPO_SIGLA, IND_SIGLA_SISTEMA) VALUES (69, 'TIPO DE CARGA', 'S');
INSERT INTO "TIPO_SIGLA" (COD_TIPO_SIGLA, DSC_TIPO_SIGLA, IND_SIGLA_SISTEMA) VALUES (70, 'TIPO DE PEDIDO', 'S');
INSERT INTO "TIPO_SIGLA" (COD_TIPO_SIGLA, DSC_TIPO_SIGLA, IND_SIGLA_SISTEMA) VALUES (53, 'STATUS DA EXPEDICAO', 'S');

INSERT INTO "SIGLA" (COD_SIGLA, COD_TIPO_SIGLA, DSC_SIGLA, COD_REFERENCIA_SIGLA) VALUES (517, (SELECT COD_TIPO_SIGLA FROM TIPO_SIGLA WHERE DSC_TIPO_SIGLA = 'TIPO DE CARGA'), 'CARGA', 'C');
INSERT INTO "SIGLA" (COD_SIGLA, COD_TIPO_SIGLA, DSC_SIGLA, COD_REFERENCIA_SIGLA) VALUES (518, (SELECT COD_TIPO_SIGLA FROM TIPO_SIGLA WHERE DSC_TIPO_SIGLA = 'TIPO DE CARGA'), 'TRANSBORDO', 'T');

INSERT INTO "SIGLA" (COD_SIGLA, COD_TIPO_SIGLA, DSC_SIGLA, COD_REFERENCIA_SIGLA) VALUES (519, (SELECT COD_TIPO_SIGLA FROM TIPO_SIGLA WHERE DSC_TIPO_SIGLA = 'TIPO DE PEDIDO'), 'MOSTRUARIO', 'M');
INSERT INTO "SIGLA" (COD_SIGLA, COD_TIPO_SIGLA, DSC_SIGLA, COD_REFERENCIA_SIGLA) VALUES (520, (SELECT COD_TIPO_SIGLA FROM TIPO_SIGLA WHERE DSC_TIPO_SIGLA = 'TIPO DE PEDIDO'), 'REPOSICAO', 'R');
INSERT INTO "SIGLA" (COD_SIGLA, COD_TIPO_SIGLA, DSC_SIGLA, COD_REFERENCIA_SIGLA) VALUES (521, (SELECT COD_TIPO_SIGLA FROM TIPO_SIGLA WHERE DSC_TIPO_SIGLA = 'TIPO DE PEDIDO'), 'ENTREGA', 'E');

INSERT INTO "SIGLA" (COD_SIGLA, COD_TIPO_SIGLA, DSC_SIGLA, COD_REFERENCIA_SIGLA) VALUES (462, (SELECT COD_TIPO_SIGLA FROM TIPO_SIGLA WHERE DSC_TIPO_SIGLA = 'STATUS DA EXPEDICAO'), 'INTEGRADO', 'I');
INSERT INTO "SIGLA" (COD_SIGLA, COD_TIPO_SIGLA, DSC_SIGLA, COD_REFERENCIA_SIGLA) VALUES (463, (SELECT COD_TIPO_SIGLA FROM TIPO_SIGLA WHERE DSC_TIPO_SIGLA = 'STATUS DA EXPEDICAO'), 'EM SEPARACAO', 'S');
INSERT INTO "SIGLA" (COD_SIGLA, COD_TIPO_SIGLA, DSC_SIGLA, COD_REFERENCIA_SIGLA) VALUES (464, (SELECT COD_TIPO_SIGLA FROM TIPO_SIGLA WHERE DSC_TIPO_SIGLA = 'STATUS DA EXPEDICAO'), 'EM CONFERENCIA', 'C');
INSERT INTO "SIGLA" (COD_SIGLA, COD_TIPO_SIGLA, DSC_SIGLA, COD_REFERENCIA_SIGLA) VALUES (465, (SELECT COD_TIPO_SIGLA FROM TIPO_SIGLA WHERE DSC_TIPO_SIGLA = 'STATUS DA EXPEDICAO'), 'FINALIZADO', 'F');


INSERT INTO RECURSO (COD_RECURSO, DSC_RECURSO, COD_RECURSO_PAI, NOM_RECURSO) VALUES (SQ_RECURSO_01.NEXTVAL, 'Imprimir etiquetas ', 0, 'expedicao:etiqueta');

alter sequence SQ_ACAO_01 INCREMENT BY 13;
SELECT SQ_ACAO_01.NEXTVAL FROM DUAL;
alter sequence SQ_ACAO_01 INCREMENT BY 1;

INSERT INTO ACAO (COD_ACAO, DSC_ACAO, NOM_ACAO) VALUES (SQ_ACAO_01.NEXTVAL, 'Imprimir', 'imprimir');
INSERT INTO ACAO (COD_ACAO, DSC_ACAO, NOM_ACAO) VALUES (SQ_ACAO_01.NEXTVAL, 'Reimprimir', 'reimprimir');

INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'expedicao:etiqueta'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'imprimir'), 'imprimir');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'expedicao:etiqueta'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'reimprimir'), 'reimprimir');

INSERT INTO "MENU_ITEM" (COD_MENU_ITEM, COD_RECURSO_ACAO, COD_PAI, DSC_MENU_ITEM, NUM_PESO, DSC_URL, SHOW) VALUES (SQ_MENU_ITEM_01.NEXTVAL, (SELECT MIN(COD_RECURSO_ACAO) FROM RECURSO_ACAO RA, RECURSO R WHERE RA.COD_RECURSO = R.COD_RECURSO AND NOM_RECURSO = 'expedicao:etiqueta'), (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'expedicao:index'), 'Imprimir Etiquetas', '0', '#', 'N');
