-- A Partir daqui começa o endereçamento

INSERT INTO RECURSO (COD_RECURSO, DSC_RECURSO, COD_RECURSO_PAI, NOM_RECURSO) VALUES (SQ_RECURSO_01.NEXTVAL, 'Palete enderecamento', 0, 'enderecamento:palete');
INSERT INTO ACAO (COD_ACAO, DSC_ACAO, NOM_ACAO) VALUES (SQ_ACAO_01.NEXTVAL, 'Endereçar', 'enderecar');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'enderecamento:palete'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'index'), 'index palete');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'enderecamento:palete'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'imprimir'), 'imprimir palete');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'enderecamento:palete'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'enderecar'), 'enderecar palete');
INSERT INTO "MENU_ITEM" (COD_MENU_ITEM, COD_RECURSO_ACAO, COD_PAI, DSC_MENU_ITEM, NUM_PESO, DSC_URL, SHOW) VALUES (SQ_MENU_ITEM_01.NEXTVAL, (SELECT MIN(COD_RECURSO_ACAO) FROM RECURSO_ACAO RA, RECURSO R WHERE RA.COD_RECURSO = R.COD_RECURSO AND NOM_RECURSO = 'enderecamento:palete'), (SELECT COD_MENU_ITEM FROM MENU_ITEM WHERE DSC_MENU_ITEM = 'Armazenagem'), 'Palete', '0', '#', 'N');

INSERT INTO RECURSO (COD_RECURSO, DSC_RECURSO, COD_RECURSO_PAI, NOM_RECURSO) VALUES (SQ_RECURSO_01.NEXTVAL, 'Endereco enderecamento', 0, 'enderecamento:endereco');
INSERT INTO ACAO (COD_ACAO, DSC_ACAO, NOM_ACAO) VALUES (SQ_ACAO_01.NEXTVAL, 'Filtrar', 'filtrar');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'enderecamento:endereco'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'filtrar'), 'filtrar enderecamento');
INSERT INTO "MENU_ITEM" (COD_MENU_ITEM, COD_RECURSO_ACAO, COD_PAI, DSC_MENU_ITEM, NUM_PESO, DSC_URL, SHOW) VALUES (SQ_MENU_ITEM_01.NEXTVAL, (SELECT MIN(COD_RECURSO_ACAO) FROM RECURSO_ACAO RA, RECURSO R WHERE RA.COD_RECURSO = R.COD_RECURSO AND NOM_RECURSO = 'enderecamento:endereco'), (SELECT COD_MENU_ITEM FROM MENU_ITEM WHERE DSC_MENU_ITEM = 'Armazenagem'), 'Endereco', '0', '#', 'N');

INSERT INTO RECURSO (COD_RECURSO, DSC_RECURSO, COD_RECURSO_PAI, NOM_RECURSO) VALUES (SQ_RECURSO_01.NEXTVAL, 'Produto enderecamento', 0, 'enderecamento:produto');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'enderecamento:produto'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'index'), 'index produto end.');
INSERT INTO "MENU_ITEM" (COD_MENU_ITEM, COD_RECURSO_ACAO, COD_PAI, DSC_MENU_ITEM, NUM_PESO, DSC_URL, SHOW) VALUES (SQ_MENU_ITEM_01.NEXTVAL, (SELECT MIN(COD_RECURSO_ACAO) FROM RECURSO_ACAO RA, RECURSO R WHERE RA.COD_RECURSO = R.COD_RECURSO AND NOM_RECURSO = 'enderecamento:produto'), (SELECT COD_MENU_ITEM FROM MENU_ITEM WHERE DSC_MENU_ITEM = 'Armazenagem'), 'Produto', '0', '#', 'N');

ALTER TABLE RECEBIMENTO_EMBALAGEM ADD (COD_NORMA_PALETIZACAO NUMBER(8));
ALTER TABLE RECEBIMENTO_VOLUME    ADD (COD_NORMA_PALETIZACAO NUMBER(8));

INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'enderecamento:endereco'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'enderecar'), 'selecionar endereço');

ALTER TABLE DEPOSITO_ENDERECO
ADD (IND_DISPONIVEL CHAR(1 BYTE) DEFAULT 'S');

CREATE TABLE PALETE
(
  UMA                   NUMBER (8) NOT NULL ,
  COD_RECEBIMENTO       VARCHAR2 (20 BYTE) NOT NULL ,
  COD_UNITIZADOR        NUMBER (8) NOT NULL ,
  COD_NORMA_PALETIZACAO NUMBER (8) ,
  COD_PRODUTO           VARCHAR2 (20 BYTE) NOT NULL ,
  DSC_GRADE             VARCHAR2 (10 BYTE) NOT NULL ,
  COD_DEPOSITO_ENDERECO NUMBER (8) ,
  QTD                   NUMBER (8) ,
  COD_STATUS            NUMBER (8)
)
LOGGING ;
ALTER TABLE PALETE ADD CONSTRAINT PALETE_PK PRIMARY KEY ( UMA ) ;

ALTER TABLE PALETE ADD CONSTRAINT PALETE_RECEBIMENTO_FK FOREIGN KEY ( COD_RECEBIMENTO ) REFERENCES WMS_ADM.RECEBIMENTO ( COD_RECEBIMENTO ) NOT DEFERRABLE ;

ALTER TABLE PALETE ADD CONSTRAINT PALETE_UNITIZADOR_FK FOREIGN KEY ( COD_UNITIZADOR ) REFERENCES WMS_ADM.UNITIZADOR ( COD_UNITIZADOR ) NOT DEFERRABLE ;

ALTER TABLE PALETE ADD CONSTRAINT PALETE_PRODUTO_FK FOREIGN KEY ( COD_PRODUTO, DSC_GRADE ) REFERENCES WMS_ADM.PRODUTO ( COD_PRODUTO, DSC_GRADE ) NOT DEFERRABLE ;

ALTER TABLE PALETE ADD CONSTRAINT PALETE_DEPOSITO_ENDERECO_FK FOREIGN KEY ( COD_DEPOSITO_ENDERECO ) REFERENCES WMS_ADM.DEPOSITO_ENDERECO ( COD_DEPOSITO_ENDERECO ) NOT DEFERRABLE ;

CREATE SEQUENCE SQ_PALETE_01
INCREMENT BY 1
START WITH 1
MAXVALUE 999999999999999999999999999
MINVALUE 0
NOCYCLE
NOCACHE
NOORDER
;

INSERT INTO "TIPO_SIGLA" (COD_TIPO_SIGLA, DSC_TIPO_SIGLA, IND_SIGLA_SISTEMA) VALUES (73, 'STATUS ENDERECAMENTO', 'S');

INSERT INTO "SIGLA" (COD_SIGLA, COD_TIPO_SIGLA, DSC_SIGLA, COD_REFERENCIA_SIGLA) VALUES (534, (SELECT COD_TIPO_SIGLA FROM TIPO_SIGLA WHERE DSC_TIPO_SIGLA = 'STATUS ENDERECAMENTO'), 'RECEBIDO', 'R');
INSERT INTO "SIGLA" (COD_SIGLA, COD_TIPO_SIGLA, DSC_SIGLA, COD_REFERENCIA_SIGLA) VALUES (535, (SELECT COD_TIPO_SIGLA FROM TIPO_SIGLA WHERE DSC_TIPO_SIGLA = 'STATUS ENDERECAMENTO'), 'EM ENDERECAMENTO', 'M');
INSERT INTO "SIGLA" (COD_SIGLA, COD_TIPO_SIGLA, DSC_SIGLA, COD_REFERENCIA_SIGLA) VALUES (536, (SELECT COD_TIPO_SIGLA FROM TIPO_SIGLA WHERE DSC_TIPO_SIGLA = 'STATUS ENDERECAMENTO'), 'ENDERECADO', 'E');

INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'enderecamento:palete'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'relatorio'), 'Relatório de Paletes para Endereçar');

INSERT INTO "SIGLA" (COD_SIGLA, COD_TIPO_SIGLA, DSC_SIGLA, COD_REFERENCIA_SIGLA) VALUES (537, (SELECT COD_TIPO_SIGLA FROM TIPO_SIGLA WHERE DSC_TIPO_SIGLA = 'STATUS ENDERECAMENTO'), 'EM RECEBIMENTO', 'S');

CREATE TABLE ESTOQUE
(
  COD_ESTOQUE               NUMBER (8)  NOT NULL ,
  COD_PRODUTO               VARCHAR2 (20 BYTE) NOT NULL ,
  DSC_GRADE                 VARCHAR2 (10 BYTE) NOT NULL ,
  COD_DEPOSITO_ENDERECO     NUMBER (8)  NOT NULL ,
  DTH_PRIMEIRA_MOVIMENTACAO DATE ,
  QTD                       NUMBER (8)
)
LOGGING;
ALTER TABLE ESTOQUE ADD CONSTRAINT ESTOQUE_PK PRIMARY KEY ( COD_ESTOQUE ) ;

CREATE TABLE HISTORICO_ESTOQUE
(
  COD_HISTORICO_ESTOQUE NUMBER (8)  NOT NULL ,
  QTD                   NUMBER (8) ,
  COD_PRODUTO           VARCHAR2 (20 BYTE) NOT NULL ,
  DSC_GRADE             VARCHAR2 (10 BYTE) NOT NULL ,
  COD_DEPOSITO_ENDERECO NUMBER (8)  NOT NULL ,
  OBSERVACAO            VARCHAR2 (300 CHAR) ,
  IND_TIPO              VARCHAR2 (1 CHAR) ,
  DTH_MOVIMENTACAO      DATE ,
  COD_OS                NUMBER (8) ,
  COD_PESSOA            NUMBER (8)  NOT NULL
)
LOGGING;
ALTER TABLE HISTORICO_ESTOQUE ADD CONSTRAINT HISTORICO_ESTOQUE_PK PRIMARY KEY ( COD_HISTORICO_ESTOQUE ) ;

ALTER TABLE ESTOQUE ADD CONSTRAINT ESTOQUE_DEPOSITO_ENDERECO_FK FOREIGN KEY (COD_DEPOSITO_ENDERECO) REFERENCES DEPOSITO_ENDERECO (COD_DEPOSITO_ENDERECO) NOT DEFERRABLE;
ALTER TABLE ESTOQUE ADD CONSTRAINT ESTOQUE_PRODUTO_FK FOREIGN KEY ( COD_PRODUTO, DSC_GRADE ) REFERENCES PRODUTO (COD_PRODUTO,DSC_GRADE) NOT DEFERRABLE;

ALTER TABLE HISTORICO_ESTOQUE ADD CONSTRAINT HISTORICO_ESTOQUE_ENDERECO_FK FOREIGN KEY (COD_DEPOSITO_ENDERECO) REFERENCES DEPOSITO_ENDERECO (COD_DEPOSITO_ENDERECO) NOT DEFERRABLE;
ALTER TABLE HISTORICO_ESTOQUE ADD CONSTRAINT HISTORICO_ESTOQUE_OS_FK FOREIGN KEY (COD_OS) REFERENCES ORDEM_SERVICO (COD_OS)NOT DEFERRABLE;
ALTER TABLE HISTORICO_ESTOQUE ADD CONSTRAINT HISTORICO_ESTOQUE_PESSOA_FK FOREIGN KEY (COD_PESSOA) REFERENCES PESSOA (COD_PESSOA) NOT DEFERRABLE;
ALTER TABLE HISTORICO_ESTOQUE ADD CONSTRAINT HISTORICO_ESTOQUE_PRODUTO_FK FOREIGN KEY (COD_PRODUTO,DSC_GRADE) REFERENCES PRODUTO (COD_PRODUTO,DSC_GRADE) NOT DEFERRABLE;

CREATE SEQUENCE SQ_ESTOQUE_01
INCREMENT BY 1
START WITH 1
MAXVALUE 999999999999999999999999999
MINVALUE 0
NOCYCLE
NOCACHE
NOORDER
;

CREATE SEQUENCE SQ_HISTORICO_ESTOQUE_01
INCREMENT BY 1
START WITH 1
MAXVALUE 999999999999999999999999999
MINVALUE 0
NOCYCLE
NOCACHE
NOORDER
;

CREATE TABLE RELATORIO_PICKING
(
  COD_RELATORIO_PICKING NUMBER (8)  NOT NULL ,
  COD_DEPOSITO_ENDERECO     NUMBER (8)  NOT NULL
)
LOGGING;

ALTER TABLE RELATORIO_PICKING ADD CONSTRAINT RELATORIO_PICKING_PK PRIMARY KEY (COD_RELATORIO_PICKING) ;
ALTER TABLE RELATORIO_PICKING ADD CONSTRAINT RELATORIO_PICKING_DE_FK FOREIGN KEY (COD_DEPOSITO_ENDERECO) REFERENCES DEPOSITO_ENDERECO (COD_DEPOSITO_ENDERECO) NOT DEFERRABLE;

CREATE SEQUENCE SQ_RELATORIO_PICKING_01
INCREMENT BY 1
START WITH 1
MAXVALUE 999999999999999999999999999
MINVALUE 0
NOCYCLE
NOCACHE
NOORDER
;

INSERT INTO ACAO (COD_ACAO, DSC_ACAO, NOM_ACAO) VALUES (SQ_ACAO_01.NEXTVAL, 'LIMPAR', 'limpar');
INSERT INTO RECURSO (COD_RECURSO, DSC_RECURSO, COD_RECURSO_PAI, NOM_RECURSO) VALUES (SQ_RECURSO_01.NEXTVAL, 'Abastecimento de Picking Manual', 0, 'enderecamento:relatorio_picking');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'enderecamento:relatorio_picking'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'index'), 'Início');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'enderecamento:relatorio_picking'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'imprimir'), 'Imprimir');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'enderecamento:relatorio_picking'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'limpar'), 'Limpar');

INSERT INTO MENU_ITEM (COD_MENU_ITEM, COD_RECURSO_ACAO, COD_PAI, DSC_MENU_ITEM, NUM_PESO, DSC_URL,SHOW) VALUES (SQ_MENU_ITEM_01.NEXTVAL, 0, 54, 'Armazenagem', 10, '#', 'S');
INSERT INTO MENU_ITEM (COD_MENU_ITEM, COD_RECURSO_ACAO, COD_PAI, DSC_MENU_ITEM, NUM_PESO, DSC_URL,SHOW) VALUES (SQ_MENU_ITEM_01.NEXTVAL, (SELECT COD_RECURSO_ACAO FROM RECURSO_ACAO WHERE COD_RECURSO = (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'enderecamento:relatorio_picking') AND COD_ACAO = (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'index')), (SELECT COD_MENU_ITEM FROM MENU_ITEM WHERE COD_PAI = 54 AND DSC_MENU_ITEM = 'Armazenagem'), 'Abastecimento de Picking Manual', 10, '#', 'S');

ALTER TABLE UNITIZADOR
ADD (QTD_ENDERECOS_BLOQUEAR NUMBER (8) DEFAULT 0);

ALTER TABLE ESTOQUE
ADD (COD_UNITIZADOR NUMBER (8) DEFAULT NULL);

ALTER TABLE ESTOQUE ADD CONSTRAINT ESTOQUE_UNITIZADOR_FK FOREIGN KEY ( COD_UNITIZADOR ) REFERENCES WMS_ADM.UNITIZADOR ( COD_UNITIZADOR ) NOT DEFERRABLE ;

INSERT INTO CONTEXTO_PARAMETRO(COD_CONTEXTO_PARAMETRO, DSC_CONTEXTO_PARAMETRO) VALUES ( SQ_CONTEXTO_PARAMETRO_01.NEXTVAL, 'ENDERECAMENTO');
INSERT INTO PARAMETRO (COD_PARAMETRO, COD_CONTEXTO_PARAMETRO, DSC_PARAMETRO, DSC_TITULO_PARAMETRO, IND_PARAMETRO_SISTEMA, COD_TIPO_ATRIBUTO, DSC_VALOR_PARAMETRO) VALUES (SQ_PARAMETRO_01.NEXTVAL, (SELECT COD_CONTEXTO_PARAMETRO FROM CONTEXTO_PARAMETRO WHERE DSC_CONTEXTO_PARAMETRO = 'ENDERECAMENTO'), 'TAMANHO_LONGARINA_PADRAO', 'Tamanho Padrão da Longarina', 'N', 'A', '350');

CREATE TABLE TAMANHO_LONGARINA
(
  NUM_RUA NUMBER(8) NOT NULL,
  NUM_PREDIO NUMBER(8) NOT NULL,
  TAMANHO NUMBER(15,3) DEFAULT 0 NOT NULL
)
LOGGING;

INSERT INTO RECURSO (COD_RECURSO, DSC_RECURSO, COD_RECURSO_PAI, NOM_RECURSO) VALUES (SQ_RECURSO_01.NEXTVAL, 'Movimentacao enderecamento', 0, 'enderecamento:movimentacao');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'enderecamento:movimentacao'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'index'), 'index movimentacao');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'enderecamento:movimentacao'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'filtrar'), 'filtrar movimentacao');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'enderecamento:movimentacao'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'list'), 'list movimentacao');
INSERT INTO ACAO (COD_ACAO, DSC_ACAO, NOM_ACAO) VALUES (SQ_ACAO_01.NEXTVAL, 'saldo', 'saldo');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'enderecamento:movimentacao'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'saldo'), 'saldo estoque');
INSERT INTO "MENU_ITEM" (COD_MENU_ITEM, COD_RECURSO_ACAO, COD_PAI, DSC_MENU_ITEM, NUM_PESO, DSC_URL, SHOW) VALUES (SQ_MENU_ITEM_01.NEXTVAL, (SELECT MIN(COD_RECURSO_ACAO) FROM RECURSO_ACAO RA, RECURSO R WHERE RA.COD_RECURSO = R.COD_RECURSO AND NOM_RECURSO = 'enderecamento:movimentacao'), (SELECT COD_MENU_ITEM FROM MENU_ITEM WHERE DSC_MENU_ITEM = 'Armazenagem' AND COD_PAI = 0 ), 'Movimentacao', '0', '#', 'S');

INSERT INTO RECURSO (COD_RECURSO, DSC_RECURSO, COD_RECURSO_PAI, NOM_RECURSO) VALUES (SQ_RECURSO_01.NEXTVAL, 'Relatório Inventário', 0, 'enderecamento:relatorio_inventario');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'enderecamento:relatorio_inventario'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'index'), 'Início');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'enderecamento:relatorio_inventario'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'imprimir'), 'Imprimir');
INSERT INTO MENU_ITEM (COD_MENU_ITEM, COD_RECURSO_ACAO, COD_PAI, DSC_MENU_ITEM, NUM_PESO, DSC_URL,SHOW) VALUES (SQ_MENU_ITEM_01.NEXTVAL, (SELECT COD_RECURSO_ACAO FROM RECURSO_ACAO WHERE COD_RECURSO = (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'enderecamento:relatorio_inventario') AND COD_ACAO = (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'index')), (SELECT COD_MENU_ITEM FROM MENU_ITEM WHERE COD_PAI = 54 AND DSC_MENU_ITEM = 'Armazenagem'), 'Inventario por Rua', 10, '#', 'S');

INSERT INTO RECURSO (COD_RECURSO, DSC_RECURSO, COD_RECURSO_PAI, NOM_RECURSO) VALUES (SQ_RECURSO_01.NEXTVAL, 'Index enderecamento', 0, 'enderecamento:index');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'enderecamento:index'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'index'), 'index enderecamento');
INSERT INTO "MENU_ITEM" (COD_MENU_ITEM, COD_RECURSO_ACAO, COD_PAI, DSC_MENU_ITEM, NUM_PESO, DSC_URL, SHOW) VALUES (SQ_MENU_ITEM_01.NEXTVAL, (SELECT MIN(COD_RECURSO_ACAO) FROM RECURSO_ACAO RA, RECURSO R WHERE RA.COD_RECURSO = R.COD_RECURSO AND NOM_RECURSO = 'enderecamento:index'), (SELECT COD_MENU_ITEM FROM MENU_ITEM WHERE DSC_MENU_ITEM = 'Armazenagem' AND COD_PAI = 0 ), 'Endereçamento', '0', '#', 'S');

--ACTIONS PARA RELATORIOS
INSERT INTO RECURSO (COD_RECURSO, DSC_RECURSO, COD_RECURSO_PAI, NOM_RECURSO) VALUES (SQ_RECURSO_01.NEXTVAL, 'Relatório UMA', 0, 'enderecamento:relatorio_uma');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'enderecamento:relatorio_uma'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'index'), 'Início');
INSERT INTO MENU_ITEM (COD_MENU_ITEM, COD_RECURSO_ACAO, COD_PAI, DSC_MENU_ITEM, NUM_PESO, DSC_URL,SHOW) VALUES (SQ_MENU_ITEM_01.NEXTVAL, (SELECT COD_RECURSO_ACAO FROM RECURSO_ACAO WHERE COD_RECURSO = (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'enderecamento:relatorio_uma') AND COD_ACAO = (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'index')), (SELECT COD_MENU_ITEM FROM MENU_ITEM WHERE COD_PAI = 54 AND DSC_MENU_ITEM = 'Armazenagem'), 'Relatório de UMAs', 10, '#', 'S');

INSERT INTO RECURSO (COD_RECURSO, DSC_RECURSO, COD_RECURSO_PAI, NOM_RECURSO) VALUES (SQ_RECURSO_01.NEXTVAL, 'Relatório UMA', 0, 'enderecamento:relatorio_estoque');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'enderecamento:relatorio_estoque'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'index'), 'Início');
INSERT INTO MENU_ITEM (COD_MENU_ITEM, COD_RECURSO_ACAO, COD_PAI, DSC_MENU_ITEM, NUM_PESO, DSC_URL,SHOW) VALUES (SQ_MENU_ITEM_01.NEXTVAL, (SELECT COD_RECURSO_ACAO FROM RECURSO_ACAO WHERE COD_RECURSO = (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'enderecamento:relatorio_estoque') AND COD_ACAO = (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'index')), (SELECT COD_MENU_ITEM FROM MENU_ITEM WHERE COD_PAI = 54 AND DSC_MENU_ITEM = 'Armazenagem'), 'Relatório de Estoque', 10, '#', 'S');

INSERT INTO ACAO (COD_ACAO, DSC_ACAO, NOM_ACAO) VALUES (SQ_ACAO_01.NEXTVAL, 'picking', 'picking');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'enderecamento:palete'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'picking'), 'Endereçar no picking');


CREATE OR REPLACE FORCE VIEW "WMS_ADM"."V_QTD_RECEBIMENTO" ("QTD", "COD_RECEBIMENTO", "COD_PRODUTO", "DSC_GRADE", "COD_OS", "COD_NORMA_PALETIZACAO") AS
  SELECT MIN(QTD.QTD) as QTD,
    QTD.COD_RECEBIMENTO,
    QTD.COD_PRODUTO,
    QTD.DSC_GRADE,
    QTD.COD_OS,
    NP.COD_NORMA_PALETIZACAO
  FROM (SELECT SUM(NVL(RV.QTD_CONFERIDA,0)) AS QTD,
          RV.COD_RECEBIMENTO,
          RV.COD_PRODUTO_VOLUME,
          PV.COD_PRODUTO,
          PV.DSC_GRADE,
          OS.COD_OS
        FROM RECEBIMENTO_VOLUME RV
          INNER JOIN (SELECT DISTINCT DTH_FINAL_ATIVIDADE,
                        COD_OS,
                        COD_PRODUTO_VOLUME,
                        COD_RECEBIMENTO,
                        RANK() OVER(PARTITION BY COD_RECEBIMENTO, COD_PRODUTO_VOLUME ORDER BY DTH_FINAL_ATIVIDADE DESC) RANK
                      FROM (SELECT CASE WHEN DTH_FINAL_ATIVIDADE IS NULL THEN TO_DATE('31/12/9999','dd/mm/yyyy')
                                   ELSE DTH_FINAL_ATIVIDADE END AS DTH_FINAL_ATIVIDADE,
                              OS.COD_OS,
                              OS.COD_RECEBIMENTO,
                              RV.COD_PRODUTO_VOLUME
                            FROM RECEBIMENTO_VOLUME RV
                              LEFT JOIN ORDEM_SERVICO OS ON OS.COD_OS = RV.COD_OS)) OS
            ON OS.COD_OS = RV.COD_OS
               AND OS.RANK <= 1
               AND OS.COD_RECEBIMENTO = RV.COD_RECEBIMENTO
               AND OS.COD_PRODUTO_VOLUME = RV.COD_PRODUTO_VOLUME
          LEFT JOIN PRODUTO_VOLUME PV ON PV.COD_PRODUTO_VOLUME = RV.COD_PRODUTO_VOLUME
        GROUP BY RV.COD_RECEBIMENTO, RV.COD_PRODUTO_VOLUME, PV.COD_PRODUTO, PV.DSC_GRADE, OS.COD_OS) QTD
    LEFT JOIN (SELECT RV.COD_NORMA_PALETIZACAO,
                 RV.COD_RECEBIMENTO,
                 PV.COD_PRODUTO,
                 PV.DSC_GRADE,
                 OS.COD_OS,
                 MIN(NP.NUM_NORMA) as NORMA
               FROM RECEBIMENTO_VOLUME RV
                 INNER JOIN (SELECT DISTINCT DTH_FINAL_ATIVIDADE,
                               COD_OS,
                               COD_PRODUTO_VOLUME,
                               COD_RECEBIMENTO,
                               RANK() OVER(PARTITION BY COD_RECEBIMENTO, COD_PRODUTO_VOLUME ORDER BY DTH_FINAL_ATIVIDADE DESC) RANK
                             FROM (SELECT CASE WHEN DTH_FINAL_ATIVIDADE IS NULL THEN TO_DATE('31/12/9999','dd/mm/yyyy')
                                          ELSE DTH_FINAL_ATIVIDADE END AS DTH_FINAL_ATIVIDADE,
                                     OS.COD_OS,
                                     OS.COD_RECEBIMENTO,
                                     RV.COD_PRODUTO_VOLUME
                                   FROM RECEBIMENTO_VOLUME RV
                                     LEFT JOIN ORDEM_SERVICO OS ON OS.COD_OS = RV.COD_OS)) OS
                   ON OS.COD_OS = RV.COD_OS
                      AND OS.RANK <= 1
                      AND OS.COD_RECEBIMENTO = RV.COD_RECEBIMENTO
                      AND OS.COD_PRODUTO_VOLUME = RV.COD_PRODUTO_VOLUME
                 LEFT JOIN PRODUTO_VOLUME PV ON PV.COD_PRODUTO_VOLUME = RV.COD_PRODUTO_VOLUME
                 LEFT JOIN NORMA_PALETIZACAO NP ON NP.COD_NORMA_PALETIZACAO = RV.COD_NORMA_PALETIZACAO
               GROUP BY RV.COD_RECEBIMENTO,  PV.COD_PRODUTO, PV.DSC_GRADE, OS.COD_OS, RV.COD_NORMA_PALETIZACAO) NP
      ON NP.COD_RECEBIMENTO = QTD.COD_RECEBIMENTO
         AND NP.COD_PRODUTO = QTD.COD_PRODUTO
         AND NP.DSC_GRADE = QTD.DSC_GRADE
         AND NP.COD_OS = QTD.COD_OS
  GROUP BY QTD.COD_PRODUTO, QTD.COD_RECEBIMENTO, QTD.DSC_GRADE, QTD.COD_OS,NP.COD_NORMA_PALETIZACAO
  UNION
  SELECT SUM(RE.QTD_CONFERIDA * PE.QTD_EMBALAGEM) AS QTD,
    RE.COD_RECEBIMENTO,
    PE.COD_PRODUTO,
    PE.DSC_GRADE,
    OS.COD_OS,
    RE.COD_NORMA_PALETIZACAO
  FROM RECEBIMENTO_EMBALAGEM RE
    INNER JOIN (SELECT DISTINCT DTH_FINAL_ATIVIDADE,
                  COD_OS,
                  COD_PRODUTO_EMBALAGEM,
                  COD_RECEBIMENTO,
                  RANK() OVER(PARTITION BY COD_RECEBIMENTO, COD_PRODUTO_EMBALAGEM ORDER BY DTH_FINAL_ATIVIDADE DESC) RANK
                FROM (SELECT CASE WHEN DTH_FINAL_ATIVIDADE IS NULL THEN TO_DATE('31/12/9999','dd/mm/yyyy')
                             ELSE DTH_FINAL_ATIVIDADE END AS DTH_FINAL_ATIVIDADE,
                        OS.COD_OS,
                        OS.COD_RECEBIMENTO,
                        RE.COD_PRODUTO_EMBALAGEM
                      FROM RECEBIMENTO_EMBALAGEM RE
                        LEFT JOIN ORDEM_SERVICO OS ON OS.COD_OS = RE.COD_OS)) OS
      ON OS.COD_OS = RE.COD_OS
         AND OS.RANK <= 1
         AND OS.COD_RECEBIMENTO = RE.COD_RECEBIMENTO
         AND OS.COD_PRODUTO_EMBALAGEM = RE.COD_PRODUTO_EMBALAGEM
    LEFT JOIN PRODUTO_EMBALAGEM PE ON PE.COD_PRODUTO_EMBALAGEM = RE.COD_PRODUTO_EMBALAGEM
  GROUP BY RE.COD_RECEBIMENTO,
    PE.COD_PRODUTO,
    PE.DSC_GRADE,
    OS.COD_OS,
    RE.COD_NORMA_PALETIZACAO;


ALTER TABLE PALETE
ADD (IND_IMPRESSO CHAR (1) DEFAULT 'N');

INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'enderecamento:palete'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'desfazer'), 'Retornar status do palete');

CREATE OR REPLACE FORCE VIEW "WMS_ADM"."V_SALDO_ESTOQUE" ("COD_PRODUTO", "DSC_GRADE", "COD_DEPOSITO_ENDERECO", "DSC_DEPOSITO_ENDERECO", "COD_LINHA_SEPARACAO", "DSC_LINHA_SEPARACAO", "QTDE", "COD_UNITIZADOR", "DSC_UNITIZADOR") AS
  SELECT E.COD_PRODUTO, E.DSC_GRADE,  E.COD_DEPOSITO_ENDERECO, E.DSC_DEPOSITO_ENDERECO, E.COD_LINHA_SEPARACAO, E.DSC_LINHA_SEPARACAO, SUM(E.QTD) as QTDE, E.COD_UNITIZADOR, E.DSC_UNITIZADOR
  FROM (SELECT P.COD_PRODUTO, P.DSC_GRADE, DE.COD_DEPOSITO_ENDERECO, DE.DSC_DEPOSITO_ENDERECO,LS.COD_LINHA_SEPARACAO, LS.DSC_LINHA_SEPARACAO, NVL(E.QTD,0) AS QTD, E.COD_UNITIZADOR, UN.DSC_UNITIZADOR
        FROM (SELECT DISTINCT P.COD_PRODUTO, P.DSC_GRADE,P.COD_LINHA_SEPARACAO,  NVL(PV.COD_DEPOSITO_ENDERECO, PE.COD_DEPOSITO_ENDERECO) AS COD_DEPOSITO_ENDERECO
              FROM PRODUTO P
                LEFT JOIN PRODUTO_VOLUME PV ON P.COD_PRODUTO = PV.COD_PRODUTO AND P.DSC_GRADE = PV.DSC_GRADE AND PV.COD_DEPOSITO_ENDERECO IS NOT NULL
                LEFT JOIN PRODUTO_EMBALAGEM PE ON P.COD_PRODUTO = PE.COD_PRODUTO AND P.DSC_GRADE = PE.DSC_GRADE AND PE.COD_DEPOSITO_ENDERECO IS NOT NULL) P
          LEFT JOIN ESTOQUE E ON P.COD_PRODUTO = E.COD_PRODUTO AND P.DSC_GRADE = E.DSC_GRADE AND P.COD_DEPOSITO_ENDERECO = E.COD_DEPOSITO_ENDERECO
          LEFT JOIN LINHA_SEPARACAO LS ON LS.COD_LINHA_SEPARACAO = P.COD_LINHA_SEPARACAO
          INNER JOIN DEPOSITO_ENDERECO DE ON DE.COD_DEPOSITO_ENDERECO = P.COD_DEPOSITO_ENDERECO
          LEFT JOIN UNITIZADOR UN ON UN.COD_UNITIZADOR = E.COD_UNITIZADOR) E
  GROUP BY COD_PRODUTO, DSC_GRADE, COD_DEPOSITO_ENDERECO, DSC_DEPOSITO_ENDERECO, COD_LINHA_SEPARACAO, DSC_LINHA_SEPARACAO, COD_UNITIZADOR, DSC_UNITIZADOR
  UNION
  SELECT P.COD_PRODUTO, P.DSC_GRADE, DE.COD_DEPOSITO_ENDERECO, DE.DSC_DEPOSITO_ENDERECO,LS.COD_LINHA_SEPARACAO, LS.DSC_LINHA_SEPARACAO, SUM(NVL(E.QTD,0)) AS QTDE, E.COD_UNITIZADOR, UN.DSC_UNITIZADOR as UNITIZADOR
  FROM ESTOQUE E
  LEFT JOIN DEPOSITO_ENDERECO DE ON DE.COD_DEPOSITO_ENDERECO = E.COD_DEPOSITO_ENDERECO
  LEFT JOIN PRODUTO P ON P.COD_PRODUTO = E.COD_PRODUTO AND P.DSC_GRADE = E.DSC_GRADE
  LEFT JOIN LINHA_SEPARACAO LS ON LS.COD_LINHA_SEPARACAO = P.COD_LINHA_SEPARACAO
  LEFT JOIN UNITIZADOR UN ON E.COD_UNITIZADOR = UN.COD_UNITIZADOR
  LEFT JOIN PARAMETRO PARAM ON PARAM.DSC_PARAMETRO = 'ID_CARACTERISTICA_PICKING'
  WHERE DE.COD_CARACTERISTICA_ENDERECO != PARAM.DSC_VALOR_PARAMETRO
  GROUP BY P.COD_PRODUTO, P.DSC_GRADE, LS.COD_LINHA_SEPARACAO, LS.DSC_LINHA_SEPARACAO, DE.COD_DEPOSITO_ENDERECO, DE.DSC_DEPOSITO_ENDERECO, E.COD_UNITIZADOR, UN.DSC_UNITIZADOR;

INSERT INTO ACAO (COD_ACAO, DSC_ACAO, NOM_ACAO) VALUES (SQ_ACAO_01.NEXTVAL, 'alterar-norma', 'alterar-norma');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'enderecamento:produto'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'alterar-norma'), 'Alterar Norma de Paletização');

ALTER TABLE ESTOQUE
ADD (UMA NUMBER (8) DEFAULT NULL);

ALTER TABLE ESTOQUE
ADD CONSTRAINT ESTOQUE_UMA_FK FOREIGN KEY (UMA)
REFERENCES WMS_ADM.PALETE (UMA ) NOT DEFERRABLE ;

ALTER TABLE PALETE
ADD (QTD_ENDERECADA NUMBER (8) DEFAULT 0);

--CORREÇÃO PARA O BUG NA EXPEDIÇÃO
ALTER TABLE WMS_ADM.ETIQUETA_SEPARACAO
ADD (COD_OS_TRANSBORDO NUMBER ( 8 ));

ALTER TABLE WMS_ADM.ETIQUETA_SEPARACAO
ADD CONSTRAINT ETQ_SEPAR_OS_TRANSBORDO FOREIGN KEY
  (
    COD_OS_TRANSBORDO
  )
REFERENCES WMS_ADM.ORDEM_SERVICO
  (
    COD_OS
  )
NOT DEFERRABLE
;

INSERT INTO ACAO (COD_ACAO, DSC_ACAO, NOM_ACAO) VALUES (SQ_ACAO_01.NEXTVAL, 'Conferencia de Transbordo', 'conferencia-transbordo');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'expedicao:os'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'conferencia-transbordo'), 'conferencia de transbordo');

--ACTIONS PARA OS NOVOS RELATORIOS
INSERT INTO RECURSO (COD_RECURSO, DSC_RECURSO, COD_RECURSO_PAI, NOM_RECURSO) VALUES (SQ_RECURSO_01.NEXTVAL, 'Relatório Estoque por Produto Consolidado', 0, 'enderecamento:relatorio_estoque-consolidado');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'enderecamento:relatorio_estoque-consolidado'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'index'), 'Início');
INSERT INTO MENU_ITEM (COD_MENU_ITEM, COD_RECURSO_ACAO, COD_PAI, DSC_MENU_ITEM, NUM_PESO, DSC_URL,SHOW) VALUES (SQ_MENU_ITEM_01.NEXTVAL, (SELECT COD_RECURSO_ACAO FROM RECURSO_ACAO WHERE COD_RECURSO = (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'enderecamento:relatorio_estoque-consolidado') AND COD_ACAO = (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'index')), (SELECT COD_MENU_ITEM FROM MENU_ITEM WHERE COD_PAI = 54 AND DSC_MENU_ITEM = 'Armazenagem'), 'Estoque por Produto (Consolidado)', 10, '#', 'S');

INSERT INTO RECURSO (COD_RECURSO, DSC_RECURSO, COD_RECURSO_PAI, NOM_RECURSO) VALUES (SQ_RECURSO_01.NEXTVAL, 'Relatório Movimentação por Produto', 0, 'enderecamento:relatorio_movimentacao-produto');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'enderecamento:relatorio_movimentacao-produto'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'index'), 'Início');
INSERT INTO MENU_ITEM (COD_MENU_ITEM, COD_RECURSO_ACAO, COD_PAI, DSC_MENU_ITEM, NUM_PESO, DSC_URL,SHOW) VALUES (SQ_MENU_ITEM_01.NEXTVAL, (SELECT COD_RECURSO_ACAO FROM RECURSO_ACAO WHERE COD_RECURSO = (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'enderecamento:relatorio_movimentacao-produto') AND COD_ACAO = (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'index')), (SELECT COD_MENU_ITEM FROM MENU_ITEM WHERE COD_PAI = 54 AND DSC_MENU_ITEM = 'Armazenagem'), 'Movimentação por Produto', 10, '#', 'S');

INSERT INTO RECURSO (COD_RECURSO, DSC_RECURSO, COD_RECURSO_PAI, NOM_RECURSO) VALUES (SQ_RECURSO_01.NEXTVAL, 'Relatório Movimentação por Produto', 0, 'enderecamento:relatorio_disponibilidade-endereco');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'enderecamento:relatorio_disponibilidade-endereco'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'index'), 'Início');
INSERT INTO MENU_ITEM (COD_MENU_ITEM, COD_RECURSO_ACAO, COD_PAI, DSC_MENU_ITEM, NUM_PESO, DSC_URL,SHOW) VALUES (SQ_MENU_ITEM_01.NEXTVAL, (SELECT COD_RECURSO_ACAO FROM RECURSO_ACAO WHERE COD_RECURSO = (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'enderecamento:relatorio_disponibilidade-endereco') AND COD_ACAO = (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'index')), (SELECT COD_MENU_ITEM FROM MENU_ITEM WHERE COD_PAI = 54 AND DSC_MENU_ITEM = 'Armazenagem'), 'Disponibilidade de Endereço', 10, '#', 'S');

INSERT INTO SIGLA (COD_SIGLA, COD_TIPO_SIGLA, DSC_SIGLA, COD_REFERENCIA_SIGLA) VALUES (538, (SELECT COD_TIPO_SIGLA FROM TIPO_SIGLA WHERE DSC_TIPO_SIGLA = 'STATUS ENDERECAMENTO'), 'CANCELADO', 'C');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'enderecamento:movimentacao'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'imprimir'), 'imprimir etiqueta de mov avulsa');

INSERT INTO PARAMETRO (COD_PARAMETRO, COD_CONTEXTO_PARAMETRO, DSC_PARAMETRO, DSC_TITULO_PARAMETRO, IND_PARAMETRO_SISTEMA, COD_TIPO_ATRIBUTO, DSC_VALOR_PARAMETRO) VALUES (SQ_PARAMETRO_01.NEXTVAL, (SELECT COD_CONTEXTO_PARAMETRO FROM CONTEXTO_PARAMETRO WHERE DSC_CONTEXTO_PARAMETRO = 'RECEBIMENTO'), 'CANCELA_PALETES_DESFAZER_RECEBIMENTO', 'Cancela os paletes ao desfazer o recebimento (S/N)', 'N', 'A', 'S');
INSERT INTO PARAMETRO (COD_PARAMETRO, COD_CONTEXTO_PARAMETRO, DSC_PARAMETRO, DSC_TITULO_PARAMETRO, IND_PARAMETRO_SISTEMA, COD_TIPO_ATRIBUTO, DSC_VALOR_PARAMETRO) VALUES (SQ_PARAMETRO_01.NEXTVAL, (SELECT COD_CONTEXTO_PARAMETRO FROM CONTEXTO_PARAMETRO WHERE DSC_CONTEXTO_PARAMETRO = 'PARAMETROS DO SISTEMA'), 'COD_PERFIL_OPERADOR_EMPILHADEIRA', 'Código do Perfil de Operadores de Empilhadeiras', 'N', 'A', '87');
-- ACERTAR O CÖDIGO DO PERFIL DE OPERADOR DE EMPILHADEIRA DEPOIS DE CRIAR O PARAMETRO

INSERT INTO ACAO (COD_ACAO, DSC_ACAO, NOM_ACAO) VALUES (SQ_ACAO_01.NEXTVAL, 'Confirmar Alterações', 'confirmar-alteracao');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'enderecamento:produto'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'confirmar-alteracao'), 'Confirmar Alteração da norma de paletização');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'enderecamento:produto'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'list'), 'Listar o andamento do produto');

CREATE TABLE ENDERECAMENTO_ANDAMENTO
(
  NUM_SEQUENCIA NUMBER (8)  NOT NULL ,
  COD_RECEBIMENTO NUMBER (8)  NOT NULL ,
  COD_PRODUTO VARCHAR2 (20 BYTE)  NOT NULL ,
  DSC_GRADE VARCHAR2 (10 BYTE)  NOT NULL ,
  COD_USUARIO NUMBER (8) ,
  DTH_ANDAMENTO DATE ,
  DSC_OBSERVACAO VARCHAR2 (512 BYTE)
) LOGGING;

ALTER TABLE ENDERECAMENTO_ANDAMENTO
ADD CONSTRAINT ENDERECAMENTO_ANDAMENTO_PK PRIMARY KEY ( NUM_SEQUENCIA  ) ;

CREATE SEQUENCE SQ_END_ANDAMENTO_01
START WITH 1
MAXVALUE 99999999999999999
MINVALUE 1
NOCYCLE
NOCACHE
NOORDER;

ALTER TABLE WMS_ADM.ENDERECAMENTO_ANDAMENTO
ADD CONSTRAINT END_ANDAMENTO_PRODUTO_FK FOREIGN KEY
  (
    COD_PRODUTO,
    DSC_GRADE
  )
REFERENCES WMS_ADM.PRODUTO
  (
    COD_PRODUTO,
    DSC_GRADE
  )
NOT DEFERRABLE
;

ALTER TABLE WMS_ADM.ENDERECAMENTO_ANDAMENTO
ADD CONSTRAINT END_ANDAMENTO_USUARIO_FK FOREIGN KEY
  (
    COD_USUARIO
  )
REFERENCES WMS_ADM.USUARIO
  (
    COD_USUARIO
  )
NOT DEFERRABLE
;

INSERT INTO RECURSO (COD_RECURSO, COD_RECURSO_PAI, DSC_RECURSO, NOM_RECURSO) VALUES (SQ_RECURSO_01.NEXTVAL, 0, 'Relatório Acompanhamento Ocupação CD', 'enderecamento:relatorio_ocupacao-cd');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'enderecamento:relatorio_ocupacao-cd'),(SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'index'), 'Início');
INSERT INTO MENU_ITEM (COD_MENU_ITEM, COD_RECURSO_ACAO, COD_PAI, DSC_MENU_ITEM, NUM_PESO, DSC_URL,SHOW)VALUES (SQ_MENU_ITEM_01.NEXTVAL, (SELECT COD_RECURSO_ACAO FROM RECURSO_ACAO WHERE COD_RECURSO = (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'enderecamento:relatorio_ocupacao-cd') AND COD_ACAO = (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'index')), (SELECT COD_MENU_ITEM FROM MENU_ITEM WHERE COD_PAI = 54 AND DSC_MENU_ITEM = 'Armazenagem'), 'Acompanhamento Ocupação CD', 10, '#', 'S');

INSERT INTO RECURSO (COD_RECURSO, COD_RECURSO_PAI, DSC_RECURSO, NOM_RECURSO) VALUES (SQ_RECURSO_01.NEXTVAL, 0, 'Relatório Acompanhamento Ocupação CD por período', 'enderecamento:relatorio_ocupacaocd-periodo');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'enderecamento:relatorio_ocupacaocd-periodo'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'index'), 'Início');
INSERT INTO MENU_ITEM (COD_MENU_ITEM, COD_RECURSO_ACAO, COD_PAI, DSC_MENU_ITEM, NUM_PESO, DSC_URL,SHOW) VALUES (SQ_MENU_ITEM_01.NEXTVAL, (SELECT COD_RECURSO_ACAO FROM RECURSO_ACAO WHERE COD_RECURSO = (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'enderecamento:relatorio_ocupacaocd-periodo') AND COD_ACAO = (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'index')), (SELECT COD_MENU_ITEM FROM MENU_ITEM WHERE COD_PAI = 54 AND DSC_MENU_ITEM = 'Armazenagem'), 'Acompanhamento Ocupação CD por período', 10, '#', 'S');

CREATE TABLE POSICAO_ESTOQUE
(
  COD_POSICAO_ESTOQUE       NUMBER (8)  NOT NULL ,
  COD_PRODUTO               VARCHAR2 (20 BYTE) NOT NULL ,
  DSC_GRADE                 VARCHAR2 (10 BYTE) NOT NULL ,
  COD_DEPOSITO_ENDERECO     NUMBER (8)  NOT NULL ,
  DTH_PRIMEIRA_MOVIMENTACAO DATE ,
  QTD                       NUMBER (8),
  COD_UNITIZADOR            NUMBER (8) DEFAULT NULL,
  UMA NUMBER (8)            DEFAULT NULL,
  DTH_ESTOQUE               DATE
) LOGGING;

ALTER TABLE POSICAO_ESTOQUE ADD CONSTRAINT PE_PK PRIMARY KEY ( COD_POSICAO_ESTOQUE );
ALTER TABLE POSICAO_ESTOQUE ADD CONSTRAINT PE_DEPOSITO_ENDERECO_FK FOREIGN KEY (COD_DEPOSITO_ENDERECO) REFERENCES DEPOSITO_ENDERECO (COD_DEPOSITO_ENDERECO) NOT DEFERRABLE;
ALTER TABLE POSICAO_ESTOQUE ADD CONSTRAINT PE_PRODUTO_FK FOREIGN KEY ( COD_PRODUTO, DSC_GRADE ) REFERENCES PRODUTO (COD_PRODUTO,DSC_GRADE) NOT DEFERRABLE;
ALTER TABLE POSICAO_ESTOQUE ADD CONSTRAINT PE_UNITIZADOR_FK FOREIGN KEY ( COD_UNITIZADOR ) REFERENCES WMS_ADM.UNITIZADOR ( COD_UNITIZADOR ) NOT DEFERRABLE ;
ALTER TABLE POSICAO_ESTOQUE ADD CONSTRAINT PE_UMA_FK FOREIGN KEY (UMA) REFERENCES WMS_ADM.PALETE (UMA ) NOT DEFERRABLE;

CREATE SEQUENCE SQ_POSICAO_ESTOQUE_01
INCREMENT BY 1
START WITH 1
MAXVALUE 999999999999999999999999999
MINVALUE 0
NOCYCLE
NOCACHE
NOORDER;

---------------------------------------
-- RODAR A PARTIR DAQUI NA SIMONETTI --
-- RODAR VIES
---------------------------------------

CREATE OR REPLACE FORCE VIEW "WMS_ADM"."V_OCUPACAO_LONGARINA" ("OCUPADO", "NUM_PREDIO", "NUM_NIVEL", "NUM_RUA", "TAMANHO_LONGARINA") AS
  SELECT SUM(OCUPADO) AS OCUPADO,
    NUM_PREDIO,
    NUM_NIVEL,
    NUM_RUA,
    TAMANHO_LONGARINA
  FROM (SELECT NVL(E.TAM,0) * 100 as OCUPADO,
          DE.NUM_PREDIO,
          DE.NUM_NIVEL,
          DE.NUM_RUA,
          DE.NUM_APARTAMENTO,
               NVL(TL.TAMANHO,TP.DSC_VALOR_PARAMETRO) as TAMANHO_LONGARINA
        FROM DEPOSITO_ENDERECO DE
          LEFT JOIN (SELECT MAX(U.NUM_LARGURA_UNITIZADOR) as TAM, E.COD_DEPOSITO_ENDERECO
                     FROM ESTOQUE E
                       LEFT JOIN UNITIZADOR U ON U.COD_UNITIZADOR = E.COD_UNITIZADOR
                     GROUP BY E.COD_DEPOSITO_ENDERECO) E ON E.COD_DEPOSITO_ENDERECO = DE.COD_DEPOSITO_ENDERECO
          LEFT JOIN TAMANHO_LONGARINA TL ON DE.NUM_PREDIO = TL.NUM_PREDIO AND DE.NUM_RUA = TL.NUM_RUA
          LEFT JOIN PARAMETRO         TP ON TP.DSC_PARAMETRO = 'TAMANHO_LONGARINA_PADRAO')
  GROUP BY NUM_PREDIO,
    NUM_NIVEL,
    NUM_RUA,
    TAMANHO_LONGARINA;

CREATE OR REPLACE FORCE VIEW "WMS_ADM"."V_SALDO_ESTOQUE_COMPLETO" ("COD_PRODUTO", "DSC_GRADE", "COD_DEPOSITO_ENDERECO", "DSC_DEPOSITO_ENDERECO", "COD_LINHA_SEPARACAO", "DSC_LINHA_SEPARACAO", "QTDE", "COD_UNITIZADOR", "DSC_UNITIZADOR") AS
  SELECT E.COD_PRODUTO, E.DSC_GRADE,  E.COD_DEPOSITO_ENDERECO, E.DSC_DEPOSITO_ENDERECO, E.COD_LINHA_SEPARACAO, E.DSC_LINHA_SEPARACAO, SUM(E.QTD) as QTDE, E.COD_UNITIZADOR, E.DSC_UNITIZADOR
  FROM (SELECT P.COD_PRODUTO, P.DSC_GRADE, DE.COD_DEPOSITO_ENDERECO, DE.DSC_DEPOSITO_ENDERECO,LS.COD_LINHA_SEPARACAO, LS.DSC_LINHA_SEPARACAO, NVL(E.QTD,0) AS QTD, E.COD_UNITIZADOR, UN.DSC_UNITIZADOR
        FROM (SELECT DISTINCT P.COD_PRODUTO, P.DSC_GRADE,P.COD_LINHA_SEPARACAO,  NVL(PV.COD_DEPOSITO_ENDERECO, PE.COD_DEPOSITO_ENDERECO) AS COD_DEPOSITO_ENDERECO
              FROM PRODUTO P
                LEFT JOIN PRODUTO_VOLUME PV ON P.COD_PRODUTO = PV.COD_PRODUTO AND P.DSC_GRADE = PV.DSC_GRADE AND PV.COD_DEPOSITO_ENDERECO IS NOT NULL
                LEFT JOIN PRODUTO_EMBALAGEM PE ON P.COD_PRODUTO = PE.COD_PRODUTO AND P.DSC_GRADE = PE.DSC_GRADE AND PE.COD_DEPOSITO_ENDERECO IS NOT NULL) P
          LEFT JOIN ESTOQUE E ON P.COD_PRODUTO = E.COD_PRODUTO AND P.DSC_GRADE = E.DSC_GRADE AND P.COD_DEPOSITO_ENDERECO = E.COD_DEPOSITO_ENDERECO
          LEFT JOIN LINHA_SEPARACAO LS ON LS.COD_LINHA_SEPARACAO = P.COD_LINHA_SEPARACAO
          INNER JOIN DEPOSITO_ENDERECO DE ON DE.COD_DEPOSITO_ENDERECO = P.COD_DEPOSITO_ENDERECO
          LEFT JOIN UNITIZADOR UN ON UN.COD_UNITIZADOR = E.COD_UNITIZADOR) E
  GROUP BY COD_PRODUTO, DSC_GRADE, COD_DEPOSITO_ENDERECO, DSC_DEPOSITO_ENDERECO, COD_LINHA_SEPARACAO, DSC_LINHA_SEPARACAO, COD_UNITIZADOR, DSC_UNITIZADOR
  UNION
  SELECT P.COD_PRODUTO, P.DSC_GRADE, DE.COD_DEPOSITO_ENDERECO, DE.DSC_DEPOSITO_ENDERECO,LS.COD_LINHA_SEPARACAO, LS.DSC_LINHA_SEPARACAO, SUM(NVL(E.QTD,0)) AS QTDE, E.COD_UNITIZADOR, UN.DSC_UNITIZADOR as UNITIZADOR
  FROM DEPOSITO_ENDERECO DE
  LEFT JOIN ESTOQUE E ON DE.COD_DEPOSITO_ENDERECO = E.COD_DEPOSITO_ENDERECO
  LEFT JOIN PRODUTO P ON P.COD_PRODUTO = E.COD_PRODUTO AND P.DSC_GRADE = E.DSC_GRADE
  LEFT JOIN LINHA_SEPARACAO LS ON LS.COD_LINHA_SEPARACAO = P.COD_LINHA_SEPARACAO
  LEFT JOIN UNITIZADOR UN ON E.COD_UNITIZADOR = UN.COD_UNITIZADOR
  LEFT JOIN PARAMETRO PARAM ON PARAM.DSC_PARAMETRO = 'ID_CARACTERISTICA_PICKING'
  WHERE DE.COD_CARACTERISTICA_ENDERECO != PARAM.DSC_VALOR_PARAMETRO
  GROUP BY P.COD_PRODUTO, P.DSC_GRADE, LS.COD_LINHA_SEPARACAO, LS.DSC_LINHA_SEPARACAO, DE.COD_DEPOSITO_ENDERECO, DE.DSC_DEPOSITO_ENDERECO, E.COD_UNITIZADOR, UN.DSC_UNITIZADOR;

INSERT INTO PARAMETRO (COD_PARAMETRO, COD_CONTEXTO_PARAMETRO, DSC_PARAMETRO, DSC_TITULO_PARAMETRO, IND_PARAMETRO_SISTEMA, COD_TIPO_ATRIBUTO, DSC_VALOR_PARAMETRO) VALUES (SQ_PARAMETRO_01.NEXTVAL, (SELECT COD_CONTEXTO_PARAMETRO FROM CONTEXTO_PARAMETRO WHERE DSC_CONTEXTO_PARAMETRO = 'ENDERECAMENTO'), 'ID_CARACTERISTICA_PICKING', 'Código da Caracteristica Picking', 'N', 'A', '37');
INSERT INTO RECURSO (COD_RECURSO, DSC_RECURSO, COD_RECURSO_PAI, NOM_RECURSO) VALUES (SQ_RECURSO_01.NEXTVAL, 'Relatório de Produtos sem Picking', 0, 'enderecamento:relatorio_produtos-sem-picking');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'enderecamento:relatorio_produtos-sem-picking'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'index'), 'Início');
INSERT INTO MENU_ITEM (COD_MENU_ITEM, COD_RECURSO_ACAO, COD_PAI, DSC_MENU_ITEM, NUM_PESO, DSC_URL,SHOW) VALUES (SQ_MENU_ITEM_01.NEXTVAL, (SELECT COD_RECURSO_ACAO FROM RECURSO_ACAO WHERE COD_RECURSO = (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'enderecamento:relatorio_produtos-sem-picking') AND COD_ACAO = (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'index')), (SELECT COD_MENU_ITEM FROM MENU_ITEM WHERE COD_PAI = 54 AND DSC_MENU_ITEM = 'Armazenagem'), 'Relatório de Produtos sem Picking', 10, '#', 'S');

INSERT INTO RECURSO (COD_RECURSO, DSC_RECURSO, COD_RECURSO_PAI, NOM_RECURSO) VALUES (SQ_RECURSO_01.NEXTVAL, 'Relatório de Produtos sem Picking', 0, 'enderecamento:relatorio_picking-multiplos-produtos');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'enderecamento:relatorio_picking-multiplos-produtos'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'index'), 'Início');
INSERT INTO MENU_ITEM (COD_MENU_ITEM, COD_RECURSO_ACAO, COD_PAI, DSC_MENU_ITEM, NUM_PESO, DSC_URL,SHOW) VALUES (SQ_MENU_ITEM_01.NEXTVAL, (SELECT COD_RECURSO_ACAO FROM RECURSO_ACAO WHERE COD_RECURSO = (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'enderecamento:relatorio_picking-multiplos-produtos') AND COD_ACAO = (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'index')), (SELECT COD_MENU_ITEM FROM MENU_ITEM WHERE COD_PAI = 54 AND DSC_MENU_ITEM = 'Armazenagem'), 'Relatório de Pickings com Multiplos Produtos', 10, '#', 'S');

ALTER TABLE DEPOSITO_ENDERECO
ADD (IND_ATIVO CHAR(1 BYTE) DEFAULT 'S');

INSERT INTO ACAO (COD_ACAO, DSC_ACAO, NOM_ACAO) VALUES (SQ_ACAO_01.NEXTVAL, 'Disponibilidade Ativar', 'disponativar');
INSERT INTO ACAO (COD_ACAO, DSC_ACAO, NOM_ACAO) VALUES (SQ_ACAO_01.NEXTVAL, 'Disponibilidade Inativar', 'disponinativar');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'endereco'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'disponativar'), 'Disponibilidade Ativar');
INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO) VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO = 'endereco'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO = 'disponinativar'), 'Disponibilidade Inativar');