CREATE TABLE MODELO_RECEBIMENTO
  (
    COD_MODELO_RECEBIMENTO NUMBER (8) NOT NULL ,
    CONTROLE_VALIDADE      CHAR (1) NOT NULL
  );

CREATE SEQUENCE SQ_MODELO_RECEBIMENTO_01  MINVALUE 0 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE;

ALTER TABLE MODELO_RECEBIMENTO
  ADD CONSTRAINT MODELO_RECEBIMENTO_PK PRIMARY KEY (COD_MODELO_RECEBIMENTO);

ALTER TABLE PRODUTO ADD(
   DIAS_VIDA_UTIL NUMBER(8,0),
   POSSUI_VALIDADE CHAR (1) DEFAULT 'N'
);

INSERT INTO ACAO (COD_ACAO, DSC_ACAO, NOM_ACAO) VALUES (SQ_ACAO_01.NEXTVAL, 'MODELO RECEBIMENTO', 'modelo-recebimento');

INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO)
  VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO LIKE 'recebimento'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO LIKE 'modelo-recebimento'), 'parametros para recebimento');

ALTER TABLE MODELO_RECEBIMENTO
  ADD (DESCRICAO VARCHAR2 (100 BYTE)) ;

INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO)
  VALUES (SQ_RECURSO_ACAO_01.NEXTVAL, (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO LIKE 'recebimento'), (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO LIKE 'add'), 'adicionar parametros para recebimento');
