CREATE TABLE MODELO_RECEBIMENTO
  (
    COD_MODELO_RECEBIMENTO NUMBER (8) NOT NULL ,
    CONTROLE_VALIDADE      CHAR (1) NOT NULL
  );

CREATE SEQUENCE  SQ_MODELO_RECEBIMENTO_01  MINVALUE 0 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE;

ALTER TABLE MODELO_RECEBIMENTO
  ADD CONSTRAINT MODELO_RECEBIMENTO_PK PRIMARY KEY (COD_MODELO_RECEBIMENTO);

ALTER TABLE PRODUTO ADD(
   DIAS_VIDA_UTIL NUMBER(8,0),
   POSSUI_VALIDADE CHAR (1) DEFAULT 'N'
);

