/* 
 * SCRIPT PARA: Estrutura para permitir cadastro de tipos de notas, fornecedores serem tanto PJ quanto PF e vincular notas de devolução ao cliente
 * DATA DE CRIAÇÃO: 05/08/2020 
 * CRIADO POR: Tarcísio César
 *
 */
INSERT INTO VERSAO (DTH, NUMERO_VERSAO, SCRIPT) VALUES (SYSDATE, 'v8.0', '05-tipo-nota-fiscal.sql');

CREATE TABLE EMISSOR
(
    COD_EMISSOR NUMBER(8) NOT NULL,
    IND_TIPO CHAR (1 BYTE) NOT NULL
);

ALTER TABLE FORNECEDOR RENAME COLUMN COD_FORNECEDOR TO COD_EMISSOR;
INSERT INTO EMISSOR (COD_EMISSOR, IND_TIPO) SELECT DISTINCT COD_EMISSOR, 'F' FROM FORNECEDOR;

ALTER TABLE CLIENTE RENAME COLUMN COD_CLIENTE_EXTERNO TO COD_EXTERNO;
ALTER TABLE CLIENTE RENAME COLUMN COD_PESSOA TO COD_EMISSOR;

ALTER TABLE TIPO_NOTA_ENTRADA ADD (IND_EMISSOR CHAR(1));
ALTER TABLE TIPO_NOTA_ENTRADA ADD (COD_EXTERNO VARCHAR(50));
ALTER TABLE TIPO_NOTA_ENTRADA ADD (IND_SYS_DEFAULT CHAR(1) DEFAULT 0 NOT NULL);
ALTER TABLE TIPO_NOTA_ENTRADA ADD (IND_RECEB_DEFAULT CHAR(1) DEFAULT 0 NOT NULL);
/*
 * APOS INCLUIR OS CAMPOS IND_EMISSOR E COD_EXTERNO, ADEQUAR OS VALORES ANTES DE RODAR DAQUI PRA BAIXO
 */
UPDATE TIPO_NOTA_ENTRADA SET IND_EMISSOR = 'F';
UPDATE TIPO_NOTA_ENTRADA SET IND_EMISSOR = 'F' WHERE COD_TIPO_NOTA_ENTRADA = 1;
UPDATE TIPO_NOTA_ENTRADA SET IND_EMISSOR = 'C' WHERE COD_TIPO_NOTA_ENTRADA = 2;

UPDATE TIPO_NOTA_ENTRADA SET COD_EXTERNO = 624 WHERE COD_TIPO_NOTA_ENTRADA = 1;
UPDATE TIPO_NOTA_ENTRADA SET COD_EXTERNO = 625 WHERE COD_TIPO_NOTA_ENTRADA = 2;

ALTER TABLE TIPO_NOTA_ENTRADA MODIFY (IND_EMISSOR NOT NULL, COD_EXTERNO );
CREATE UNIQUE INDEX TIPO_NOTA_COD_EXTERNO ON TIPO_NOTA_ENTRADA (COD_EXTERNO);

/*
 * ANTES DE EXECUTAR ESTE TRECHO AVALIAR SE EXISTE OS REGISTROS 1 E 2 E SE EXISTE OUTRO ALEM DESTES NÃO UTILIZADOS
 */
UPDATE TIPO_NOTA_ENTRADA SET IND_SYS_DEFAULT = 1, DSC_TIPO_NOTA_ENTRADA = 'COMPRA', IND_RECEB_DEFAULT = 1 WHERE COD_TIPO_NOTA_ENTRADA = 1;
UPDATE TIPO_NOTA_ENTRADA SET IND_SYS_DEFAULT = 1, DSC_TIPO_NOTA_ENTRADA = 'DEVOLUÇÃO' WHERE COD_TIPO_NOTA_ENTRADA = 2;

DELETE FROM TIPO_NOTA_ENTRADA WHERE IND_SYS_DEFAULT = 0;