INSERT INTO VERSAO (DTH, NUMERO_VERSAO, SCRIPT) VALUES (SYSDATE, '6.17.0','01-cancelamento-carga.sql');

ALTER TABLE TR_CANCELAMENTO_CARGA
  ADD (
  IND_PROCESSADO VARCHAR2(1) DEFAULT 'N',
  DTH_INCLUSAO DATE DEFAULT SYSDATE,
  DTH_PROCESSAMENTO DATE,
  ID NUMBER(16));

UPDATE ACAO_INTEGRACAO SET DSC_QUERY = 'SELECT ID, COD_CARGA_EXTERNO, TO_CHAR(DTH_CANCELAMENTO, ''DD/MM/YYYY HH24:MI:SS'') DTH_CANCELAMENTO FROM TR_CANCELAMENTO_CARGA WHERE (IND_PROCESSADO = ''N'' OR IND_PROCESSADO IS NULL)' WHERE COD_ACAO_INTEGRACAO = 24;
UPDATE ACAO_INTEGRACAO SET IND_TIPO_CONTROLE = 'F', TABELA_REFERENCIA = 'TR_CANCELAMENTO_CARGA' WHERE COD_ACAO_INTEGRACAO = 24;

CREATE SEQUENCE SQ_TR_CANCELAMENTO_CARGA;

CREATE OR REPLACE TRIGGER ID_TR_CANCELAMENTO_CARGA
  BEFORE INSERT ON TR_CANCELAMENTO_CARGA
  FOR EACH ROW
BEGIN
  SELECT SQ_TR_CANCELAMENTO_CARGA.NEXTVAL
  INTO :NEW.ID
  FROM DUAL;
END;

ALTER TABLE TR_PEDIDO
  ADD (DSC_OBSERVACAO_INTEGRACAO VARCHAR2(512 BYTE));