<div class="col-xs-12" >
    ﻿<form id="formulario" enctype="application/x-www-form-urlencoded" accept-charset="UTF-8" action="<?php echo $this->url(array('controller' => 'ressuprimento', 'action' => 'retirar-estoque')) ?>" method="post">
        <div>
            <b><label style="font-size:17px">Produto:</label></b>
            <input class="focus form-control" type="text" name="etiquetaProduto" id="etiquetaProduto" value="" />
        </div>
        <br>
        <div>
            <div class="table-responsive">
                <table class="gTable  table-condensed">
                    <tbody>
                        <tr>
                            <td>Rua: <?php echo $this->rua ?></td>
                            <td>&nbsp;</td><td>&nbsp;</td>
                            <td>Prédio: <?php echo $this->predio ?></td>
                        </tr>
                        <tr>
                            <td>Nível: <?php echo $this->nivel ?></td>
                            <td>&nbsp;</td><td>&nbsp;</td>
                            <td>Apartamento: <?php echo $this->apartamento ?></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <br>
        <div class="col-xs-12">
            <input type="submit" class="btn gradientBtn" name="submit" id="submit" value="Buscar" />
        </div>
        <a style="width: auto;" class="finalizar btn" href="<?php echo $this->url(array('controller' => 'ressuprimento', 'action' => 'endereco-uma', 'cb' => $this->cb)); ?>">Alternar para U.M.A.</a>
    </form>

    <div class = "gPager"></div>
</div>
