<div class="col-xs-12">
    ﻿<form id="formulario" enctype="application/x-www-form-urlencoded" accept-charset="UTF-8" action="<?php echo $this->url(array('controller' => 'ressuprimento', 'action' => 'confirma-movimentacao')) ?>" method="post">
        <div id="quantidade-grid" class="grid">
            <label><?php echo $this->descricaoProduto ?></label>
            <br>
            <div class="table-responsive">
                <table class="gTable  table-condensed" style="width: 50%">
                    <tbody>
                        <tr>
                            <td>Endereço</td>
                            <td>&nbsp;</td><td>&nbsp;</td>
                            <td>Código</td>
                            <td>&nbsp;</td><td>&nbsp;</td>
                            <td>Grade</td>
                            <td>&nbsp;</td><td>&nbsp;</td>
                            <td>Qtde</td>
                        </tr>
                        <tr>
                            <td><?php echo $this->endereco ?></td>
                            <td>&nbsp;</td><td>&nbsp;</td>
                            <td><?php echo $this->codProduto ?></td>
                            <td>&nbsp;</td><td>&nbsp;</td>
                            <td><?php echo $this->grade ?></td>
                            <td>&nbsp;</td><td>&nbsp;</td>
                            <td><?php echo $this->qtd ?></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>

        <div>
            <input type="hidden" name="idProduto" id="idProduto" value="<?php echo $this->codProduto ?>"/>
            <input type="hidden" name="grade" id="grade" value="<?php echo $this->grade ?>"/>
            <input type="hidden" name="idEndereco" id="idEndereco" value="<?php echo $this->idEndereco ?>"/>
            <?php if (!empty($this->codEmbalagem)) { ?>
                <input type="hidden" name="codEmbalagem" id="codEmbalagem" value="<?php echo $this->codEmbalagem ?>"/>
            <?php } ?>
            <div class="table-responsive">
                <table class="gTable  table-condensed">
                    <?php if (!empty($this->embalagens)) { ?>
                        <tr>
                            <td>Embalagem:</td>
                            <td>
                                <select id="codEmbalagem" name="codEmbalagem" title="Embalagem" required>
                                    <?php foreach ($this->embalagens as $key => $item) { ?>
                                        <option value="<?php echo $key ?>"><?php echo $item['embalagem'] . "($item[qtd])" ?></option>
                                    <?php } ?>
                                </select>
                            </td>
                        </tr>
                    <?php } ?>
                    <tr>
                        <td>Quantidade:</td>
                        <td><input class="focus form-control" title="Quantidade" type="text" name="quantidade" id="quantidade" value="" width="30px"/></td>
                    </tr>
                </table>
            </div>
            <div class="col-xs-12">
                <input class="btn gradientBtn" type="submit" name="submit" id="submit" value="Movimentar" />
            </div>
        </div>
    </form>
</div>


