
INSERT INTO VERSAO (DTH, NUMERO_VERSAO, SCRIPT) VALUES (SYSDATE, '7.6', '1-acompanhamento-operacao.sql');

INSERT INTO MENU_ITEM (COD_MENU_ITEM, COD_RECURSO_ACAO, COD_PAI, DSC_MENU_ITEM, NUM_PESO, DSC_URL, DSC_TARGET, SHOW)
VALUES (SQ_MENU_ITEM_01.NEXTVAL,
0,
(SELECT COD_MENU_ITEM FROM MENU_ITEM WHERE DSC_MENU_ITEM = 'Expedição' AND COD_PAI = 0),
'Separação',
10, '#', '_self', 'S');

UPDATE MENU_ITEM
   SET COD_PAI = (SELECT COD_MENU_ITEM FROM MENU_ITEM WHERE DSC_MENU_ITEM = 'Separação'
                     AND COD_PAI = (SELECT COD_MENU_ITEM FROM MENU_ITEM WHERE DSC_MENU_ITEM = 'Expedição' AND COD_PAI = 0))
WHERE DSC_MENU_ITEM IN ('Definir Equipe de Separação');

UPDATE MENU_ITEM
   SET SHOW = 'N'
WHERE DSC_MENU_ITEM IN ('Equipe Expedição','Pedido Acumulado');

UPDATE MENU_ITEM SET NUM_PESO = 0 WHERE COD_PAI = (SELECT COD_MENU_ITEM FROM MENU_ITEM WHERE DSC_MENU_ITEM = 'Expedição' AND COD_PAI = 0) AND SHOW = 'S'
AND DSC_MENU_ITEM = 'Etiqueta de Separação';

UPDATE MENU_ITEM SET NUM_PESO = 1 WHERE COD_PAI = (SELECT COD_MENU_ITEM FROM MENU_ITEM WHERE DSC_MENU_ITEM = 'Expedição' AND COD_PAI = 0) AND SHOW = 'S'
AND DSC_MENU_ITEM = 'Ressuprimento';

UPDATE MENU_ITEM SET NUM_PESO = 2 WHERE COD_PAI = (SELECT COD_MENU_ITEM FROM MENU_ITEM WHERE DSC_MENU_ITEM = 'Expedição' AND COD_PAI = 0) AND SHOW = 'S'
AND DSC_MENU_ITEM = 'Separação';

UPDATE MENU_ITEM SET NUM_PESO = 3 WHERE COD_PAI = (SELECT COD_MENU_ITEM FROM MENU_ITEM WHERE DSC_MENU_ITEM = 'Expedição' AND COD_PAI = 0) AND SHOW = 'S'
AND DSC_MENU_ITEM = 'Ordem Carregamento';

UPDATE MENU_ITEM SET NUM_PESO = 4 WHERE COD_PAI = (SELECT COD_MENU_ITEM FROM MENU_ITEM WHERE DSC_MENU_ITEM = 'Expedição' AND COD_PAI = 0) AND SHOW = 'S'
AND DSC_MENU_ITEM = 'Checkout Expedição';

UPDATE MENU_ITEM SET NUM_PESO = 5 WHERE COD_PAI = (SELECT COD_MENU_ITEM FROM MENU_ITEM WHERE DSC_MENU_ITEM = 'Expedição' AND COD_PAI = 0) AND SHOW = 'S'
AND DSC_MENU_ITEM = 'Expedição Mercadorias';

INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO, COD_ACAO, DSC_RECURSO_ACAO)
VALUES (SQ_RECURSO_ACAO_01.NEXTVAL,
        (SELECT COD_RECURSO FROM RECURSO
          WHERE NOM_RECURSO = 'expedicao:os'),
        (SELECT COD_ACAO FROM ACAO
          WHERE NOM_ACAO = 'consultar'),
        'Acompanhamento da Separação');

INSERT INTO MENU_ITEM (COD_MENU_ITEM, COD_RECURSO_ACAO, COD_PAI, DSC_MENU_ITEM, NUM_PESO, DSC_URL, SHOW)
VALUES (SQ_MENU_ITEM_01.NEXTVAL,
       (SELECT COD_RECURSO_ACAO FROM RECURSO_ACAO
         WHERE COD_RECURSO = (SELECT COD_RECURSO FROM RECURSO
                               WHERE NOM_RECURSO = 'expedicao:os')
           AND COD_ACAO = (SELECT COD_ACAO
                             FROM ACAO WHERE NOM_ACAO = 'consultar')),
        (SELECT MAX(COD_MENU_ITEM) FROM MENU_ITEM WHERE DSC_MENU_ITEM = 'Separação'),
        'Acompanhamento da Separação',1,'#','S');