<table class="gTable ">

    <caption>Estoque do produto - Picking cadastrado: <?php echo $this->endPicking; ?></caption>
    <tbody>
    <?php
    $enderecoAnterior = null;
    $descricaoProdutoAnterior = null;
    $codProdutoAnterior = null;
    $gradeAnterior = null;
    $codVolumeAnterior = null;
    $qtdReservaEntrada = 0;
    $qtdReservaSaida = 0;
    $qtdEstoqueFinal = 0;
    $arrayEnderecos = array();
    $arrayQtds = array();
    $arrayVolumes = array();
    $arrayVolumesPorEndereco = array();
    $volumes = null;

    foreach($this->enderecos as $endereco) {
        if (($codProdutoAnterior != null && $codProdutoAnterior != $endereco['COD_PRODUTO']) || ($gradeAnterior != null && $gradeAnterior != $endereco['DSC_GRADE'])) { ?>

            <tr class ="gTTitle">
                <td><b><?php echo "CÓDIGO: " . $codProdutoAnterior; ?></b></td>
                <td><b><?php echo "GRADE: " . $gradeAnterior; ?></b></td>
                <td><b><?php echo "PRODUTO: " . $descricaoProdutoAnterior; ?></b></td>
                <td colspan="4"></td>
            </tr>

            <tr>
                <td><b>Endereço</b></td>
                <td><b>Tipo</b></td>
                <td><b>Data de Entrada</b></td>
                <td><b>Reserva Entrada</b></td>
                <td><b>Reserva Saida</b></td>
                <td><b>Qtd.Estoque</b></td>
                <td><b>Volume</b></td>
            </tr>

            <?php foreach ($arrayEnderecos as $key => $end) : ?>
                <?php foreach ($end as $data => $dados) : ?>
                    <tr>
                        <td><?php echo $key ?></td>
                        <td><?php echo $dados['TIPO'] ?></td>
                        <td><?php echo $dados['DTH_PRIMEIRA_MOVIMENTACAO'] ?></td>
                        <td><?php echo $dados['RESERVA_ENTRADA'] ?></td>
                        <td><?php echo $dados['RESERVA_ENTRADA'] ?></td>
                        <td><?php echo $dados['QTD'] ?></td>
                        <td><?php echo $dados['VOLUME'] ?></td>
                    </tr>
                <?php endforeach; ?>
            <?php endforeach; ?>

            <?php if ($codProdutoAnterior != null) : ?>
                <tr >
                    <td colspan="3"><b>Total</b></td>
                    <td><b><?php echo $qtdReservaEntrada?></b></td>
                    <td><b><?php echo $qtdReservaSaida?></b></td>
                    <td><b><?php echo $qtdEstoqueFinal?></b></td>
                </tr>
            <?php endif; ?>

            <?php
            $volumes = null;
            $arrayVolumesPorEndereco = array();
            $arrayQtds = array();
            $arrayVolumes = array();
            $arrayEnderecos = array();
            $dados = null;
            $qtdEstoqueFinal = 0;
            $qtdReservaEntrada = 0;
            $qtdReservaSaida = 0;
            ?>
        <?php } ?>

        <?php if (array_key_exists($endereco['ENDERECO'], $arrayEnderecos)) {
            if (array_key_exists($endereco['DTH_PRIMEIRA_MOVIMENTACAO'], $arrayEnderecos[$endereco['ENDERECO']])) {
                $arrayEnderecos[$endereco['ENDERECO']][$endereco['DTH_PRIMEIRA_MOVIMENTACAO']]['QTD'] = $arrayEnderecos[$endereco['ENDERECO']][$endereco['DTH_PRIMEIRA_MOVIMENTACAO']]['QTD'] + $endereco['QTD'];
                $arrayEnderecos[$endereco['ENDERECO']][$endereco['DTH_PRIMEIRA_MOVIMENTACAO']]['RESERVA_ENTRADA'] = $arrayEnderecos[$endereco['ENDERECO']][$endereco['DTH_PRIMEIRA_MOVIMENTACAO']]['RESERVA_ENTRADA'] + $endereco['RESERVA_ENTRADA'];
                $arrayEnderecos[$endereco['ENDERECO']][$endereco['DTH_PRIMEIRA_MOVIMENTACAO']]['RESERVA_SAIDA'] = $arrayEnderecos[$endereco['ENDERECO']][$endereco['DTH_PRIMEIRA_MOVIMENTACAO']]['RESERVA_SAIDA'] + $endereco['RESERVA_SAIDA'];

                array_push($arrayQtds, $endereco['QTD']);
                array_push($arrayVolumes, $endereco['VOLUME']);

                for ($i = 0; $i < count($arrayVolumes); $i++) {
                    if ($endereco['QTD'] != $arrayQtds[$i] && $endereco['VOLUME'] != $arrayVolumes[$i]) {
                        $arrayEnderecos[$endereco['ENDERECO']][$endereco['DTH_PRIMEIRA_MOVIMENTACAO']]['ENDERECO'] = $endereco['ENDERECO'];
                        $arrayEnderecos[$endereco['ENDERECO']][$endereco['DTH_PRIMEIRA_MOVIMENTACAO']]['DTH_PRIMEIRA_MOVIMENTACAO'] = $endereco['DTH_PRIMEIRA_MOVIMENTACAO'];
                        $arrayEnderecos[$endereco['ENDERECO']][$endereco['DTH_PRIMEIRA_MOVIMENTACAO']]['TIPO'] = $endereco['TIPO'];
                        $arrayEnderecos[$endereco['ENDERECO']][$endereco['DTH_PRIMEIRA_MOVIMENTACAO']]['QTD'] = $endereco['QTD'];
                        $arrayEnderecos[$endereco['ENDERECO']][$endereco['DTH_PRIMEIRA_MOVIMENTACAO']]['RESERVA_ENTRADA'] = $endereco['RESERVA_ENTRADA'];
                        $arrayEnderecos[$endereco['ENDERECO']][$endereco['DTH_PRIMEIRA_MOVIMENTACAO']]['RESERVA_SAIDA'] = $endereco['RESERVA_SAIDA'];
                        $arrayEnderecos[$endereco['ENDERECO']][$endereco['DTH_PRIMEIRA_MOVIMENTACAO']]['VOLUME'] = $endereco['VOLUME'];

                        if (!array_key_exists($endereco['ENDERECO'], $arrayVolumesPorEndereco)) {
                            $arrayVolumesPorEndereco[$endereco['ENDERECO']] = array();
                            array_push($arrayVolumesPorEndereco[$endereco['ENDERECO']], $endereco['VOLUME']);
                        } else {
                            array_push($arrayVolumesPorEndereco[$endereco['ENDERECO']], $endereco['VOLUME']);
                        }
                        $i = count($arrayVolumes);
                    } elseif ($endereco['QTD'] == $arrayQtds[$i] && $endereco['VOLUME'] != $arrayVolumes[$i]) {
                        if (!in_array($endereco['ENDERECO'], $arrayVolumesPorEndereco[$endereco['ENDERECO']])) {
                            $arrayVolumesPorEndereco[$endereco['ENDERECO']] = array();
                            $result = array_push($arrayVolumesPorEndereco[$endereco['ENDERECO']], $endereco['VOLUME']);
                        } else {
                            array_push($arrayVolumesPorEndereco[$endereco['ENDERECO']], $endereco['VOLUME']);
                        }

                        $i = count($arrayVolumes);
                    }
                }
            }
        } else {
            $arrayEnderecos[$endereco['ENDERECO']][$endereco['DTH_PRIMEIRA_MOVIMENTACAO']]['ENDERECO'] = $endereco['ENDERECO'];
            $arrayEnderecos[$endereco['ENDERECO']][$endereco['DTH_PRIMEIRA_MOVIMENTACAO']]['DTH_PRIMEIRA_MOVIMENTACAO'] = $endereco['DTH_PRIMEIRA_MOVIMENTACAO'];
            $arrayEnderecos[$endereco['ENDERECO']][$endereco['DTH_PRIMEIRA_MOVIMENTACAO']]['TIPO'] = $endereco['TIPO'];
            $arrayEnderecos[$endereco['ENDERECO']][$endereco['DTH_PRIMEIRA_MOVIMENTACAO']]['QTD']  = $endereco['QTD'];
            $arrayEnderecos[$endereco['ENDERECO']][$endereco['DTH_PRIMEIRA_MOVIMENTACAO']]['RESERVA_ENTRADA'] = $endereco['RESERVA_ENTRADA'];
            $arrayEnderecos[$endereco['ENDERECO']][$endereco['DTH_PRIMEIRA_MOVIMENTACAO']]['RESERVA_SAIDA'] = $endereco['RESERVA_SAIDA'];
            if (!array_key_exists($endereco['ENDERECO'], $arrayVolumesPorEndereco)) {
                $arrayVolumesPorEndereco[$endereco['ENDERECO']] = array();
                array_push($arrayVolumesPorEndereco[$endereco['ENDERECO']], $endereco['VOLUME']);
            } else {
                array_push($arrayVolumesPorEndereco[$endereco['ENDERECO']], $endereco['VOLUME']);
            }
        } ?>


        <?php
        $codProdutoAnterior = $endereco['COD_PRODUTO'];
        $descricaoProdutoAnterior = $endereco['DSC_PRODUTO'];
        $gradeAnterior = $endereco['DSC_GRADE'];
        $qtdEstoqueFinal = $qtdEstoqueFinal + $endereco['QTD'];
        $volumeAnterior = $endereco['VOLUME'];
        $qtdReservaSaida = $qtdReservaSaida + $endereco['RESERVA_SAIDA'];
        $qtdReservaEntrada = $qtdReservaEntrada + $endereco['RESERVA_ENTRADA'];
        ?>
    <?php } ?>

</table>