<script>
    $(document).ready(function () {
        $("a[rel=modal]").click(function (a) {
            a.preventDefault();
            $.wmsDialogAjax({
                width: 800,
                height: 500,
                url: this.href,
                title: $(this).html()
            })
        });
    });
</script>

<table class="gTable list">
    <?php
    $ends = '';
    if (isset($this->endPicking) && !empty($this->endPicking)) :
        foreach ($this->endPicking as $endsPicking) {
            $ends .= $endsPicking . ' - ';
        }
        ?>

        <?php if (isset($this->enderecos) && empty($this->enderecos)) : ?>
            <caption>Estoque do produto - Picking cadastrado: <?php echo $ends; ?></caption>
        <?php endif; ?>
<?php endif; ?>

    <tbody>
        <?php
        $codProdutoAnterior = null;
        $gradeAnterior = null;
        $codVolumeAnterior = null;

        $qtdEstoque = 0;
        $qtdReservaEntrada = 0;
        $qtdReservaSaida = 0;
        $count = 0;
        $colspan = 3;
        if($this->controlaLote == 'S'){
            $colspan = 4;
        }
        $this->possuiInativo = "N";
        foreach ($this->enderecos as $key => $endereco) {
            if (($codProdutoAnterior != $endereco['COD_PRODUTO']) || ($gradeAnterior != $endereco['DSC_GRADE']) || ($codVolumeAnterior != $endereco['COD_VOLUME'])) {

                if ($codProdutoAnterior != NULL) {
                    ?>
                    <tr>
                        <td colspan="<?php echo $colspan + 2 ?>" style="text-align: center"><b>Total</b></td>
                        <td><b><?php echo $qtdReservaEntrada ?></b></td>
                        <td><b><?php echo $qtdReservaSaida ?></b></td>
                        <td><b><?php echo $qtdEstoque ?></b></td>
                        <td colspan="2"></td>
                    </tr>
                    <?php
                }

                $qtdEstoque = 0;
                $qtdReservaEntrada = 0;
                $qtdReservaSaida = 0;
                ?>

                <tr class ="gTTitle" >
                    <td><b><?php echo "CÓDIGO: " . $endereco['COD_PRODUTO'] ?></b></td>
                    <td><b><?php echo "GRADE: " . $endereco['DSC_GRADE'] ?></b></td>
                    <td colspan="3"><b><?php echo "PRODUTO: " . $endereco['DSC_PRODUTO'] ?></b></td>
                    <td colspan="2"><b><?php echo "VOLUME: " . $endereco['VOLUME'] ?></b></td>
                    <td colspan="<?php echo $colspan ?>">
                        <?php if (isset($this->endPicking[$count])) : ?>
                            <b><?php echo "PICKING: " . $this->endPicking[$count]; ?></b>
        <?php endif; ?>
                    </td>
                </tr>

                <tr class ="gTTitle" >
                    <td><b>Endereço</b></td>
                    <td><b>Tipo</b></td>
                    <?php
                    if($this->controlaLote == 'S'){ ?>
                    <td><b>Lote</b></td>
                    <?php } ?>
                    <td><b>Data de Entrada</b></td>
                    <td><b>U.M.A.</b></td>
                    <td><b>Unitizador</b></td>
                    <td><b>Reserva Entrada</b></td>
                    <td><b>Reserva Saida</b></td>
                    <td><b>Qtd.Estoque</b></td>
                    <td><b>Validade</b></td>
                    <td><b>Ações</b></td>
                </tr>
                <?php
                $count++;
            }
            ?><tr  <?php
                if ($endereco['SITUACAO'] == 'INATIVO') {
                    $this->possuiInativo = "S";
                    echo 'style="background-color:#f1b0b7"';
                } else if ($endereco['SITUACAO'] != "DISPONIVEL") {
                    echo 'style="background-color:#F1F1C3"';
                }

                ?>>
                <td><?php if ($endereco['SITUACAO'] == "DISPONIVEL") {
                    echo $endereco['ENDERECO'];
                } else {
                    echo $endereco['ENDERECO']. " (". $endereco['SITUACAO'].  ")";
                }?></td>
                <td><?php echo $endereco['TIPO'] ?></td>
                <?php
                if($this->controlaLote == 'S'){
                    ?>
                    <td><b><?php echo (isset($endereco['LOTE']))? $endereco['LOTE'] : '-' ?></b></td>
                    <?php
                }
                ?>
                <td><?php echo $endereco['DTH_PRIMEIRA_MOVIMENTACAO'] ?></td>
                <td><?php echo $endereco['UMA'] ?></td>
                <td><?php echo $endereco['UNITIZADOR'] ?></td>
                <td><?php echo $endereco['RE_EMBALAGEM'] ?></td>
                <td><?php echo $endereco['RS_EMBALAGEM'] ?></td>
                <td><?php echo $endereco['QTD_EMBALAGEM'] ?></td>
                <td><?php
                    if (isset($endereco['DTH_VALIDADE']) && !empty($endereco['DTH_VALIDADE'])) {
                        $dataValidade = new DateTime($endereco['DTH_VALIDADE']);
                        $dataValidade = $dataValidade->format('d/m/Y');
                        echo $dataValidade;
                    } else {
                        echo "<p style='text-align: center;'> - </p>";
                    }
                    ?></td>
                <td><?php if (($endereco['RESERVA_SAIDA'] != 0) || ($endereco['RESERVA_ENTRADA'] != 0)) { ?>
                        <a rel="modal" class="btn" <?php echo 'href="/enderecamento/movimentacao/consultar/idVolume/' . $endereco['COD_VOLUME'] . '/idProduto/' . $endereco['COD_PRODUTO'] . '/grade/' . urlencode($endereco['DSC_GRADE']) . '/idEndereco/' . $endereco['COD_ENDERECO']  . '/dscLote/' . $endereco['LOTE']. '"'; ?> >Mais</a>
                    <?php
                    } else {
                        echo "<p style='text-align: center;'> - </p>";
                    }
                    ?></td>
            </tr>
            <?php
            if ($endereco['SITUACAO'] != 'INATIVO') {
                $qtdEstoque = $qtdEstoque + $endereco['QTD'];
            }
            $qtdReservaEntrada = $qtdReservaEntrada + $endereco['RESERVA_ENTRADA'];
            $qtdReservaSaida = $qtdReservaSaida + $endereco['RESERVA_SAIDA'];
            $codProdutoAnterior = $endereco['COD_PRODUTO'];
            $gradeAnterior = $endereco['DSC_GRADE'];
            $codVolumeAnterior = $endereco['COD_VOLUME'];

            if ($endereco == $this->enderecos[count($this->enderecos) - 1]) {
                ?><tr>
                    <td colspan="<?php echo $colspan + 2 ?>" style="text-align: center"><b>
                            <?php if ($this->possuiInativo == "N") {
                                echo "Total";
                            } else {
                                echo "Total (Considera apenas os endereços ativos)";
                            } ?>
                        </b></td>
                    <td><b><?php
                            $vetEstoque = $this->embalagemRepo->getQtdEmbalagensProduto($endereco['COD_PRODUTO'], $endereco['DSC_GRADE'], $qtdReservaEntrada);
                            if(is_array($vetEstoque)) {
                                $qtdReservaEntrada = implode(' + ', $vetEstoque);
                            }else{
                                $qtdReservaEntrada = $vetEstoque;
                            }
                            echo $qtdReservaEntrada;
                            ?></b></td>
                    <td><b><?php
                            $vetEstoque = $this->embalagemRepo->getQtdEmbalagensProduto($endereco['COD_PRODUTO'], $endereco['DSC_GRADE'], $qtdReservaSaida);
                            if(is_array($vetEstoque)) {
                                $qtdReservaSaida = implode(' + ', $vetEstoque);
                            }else{
                                $qtdReservaSaida = $vetEstoque;
                            }
                            echo $qtdReservaSaida
                            ?></b></td>
                    <td><b><?php
                            $vetEstoque = $this->embalagemRepo->getQtdEmbalagensProduto($endereco['COD_PRODUTO'], $endereco['DSC_GRADE'], $qtdEstoque);
                            if(is_array($vetEstoque)) {
                                $qtdEstoque = implode(' + ', $vetEstoque);
                            }else{
                                $qtdEstoque = $vetEstoque;
                            }
                            echo $qtdEstoque
                            ?></b></td>
                    <td colspan="2"></td>
                </tr><?php
            }
        }
        ?>
</table>

