INSERT INTO VERSAO (DTH, NUMERO_VERSAO, SCRIPT) VALUES (SYSDATE, '6.18.0','07-parametro-comparar-expedicao');

INSERT INTO PARAMETRO (COD_PARAMETRO,COD_CONTEXTO_PARAMETRO,DSC_PARAMETRO,DSC_TITULO_PARAMETRO,IND_PARAMETRO_SISTEMA,COD_TIPO_ATRIBUTO,DSC_VALOR_PARAMETRO)
 VALUES (SQ_PARAMETRO_01.NEXTVAL,2,'COMPARA_PRODUTOS_EXPEDICAO_ERP','Compara produtos entre WMS e ERP', 'S', 'A', 'S');