<fieldset>
    <legend>Produto a Cortar</legend>
    <table class="gTable">
        <tr>
            <td><b>Código</b></td>
            <td><b>Grade</b></td>
            <td><b>Produto</b></td>
        </tr>
        <tr>
            <td><?php echo $this->idProduto; ?></td>
            <td><?php echo $this->grade; ?></td>
            <td><?php echo $this->produto; ?></td>
        </tr>
    </table>
</fieldset>

<fieldset>
    <legend>Corte</legend>
    <form action="/expedicao/corte/confirma-corte-total-ajax">

        <input type="hidden" name="COD_PRODUTO" id="COD_PRODUTO" value="<?php echo $this->idProduto; ?>">
        <input type="hidden" name="DSC_GRADE" id="DSC_GRADE" value="<?php echo $this->grade; ?>">
        <input type="hidden" name="id" id="expedicao" value="<?php echo $this->id; ?>">

        <b>Motivo do Corte:</b>
        <input type="text" name="motivoCorte" id="motivoCorte" value="" size="35" title="motivoCorte" required style="margin-right: 15px">
        <b>Senha:</b>
        <input type="password" name="senha" id="senha" value="" size="11" title="senha" required style="margin-right: 25px">
        <input type="submit" name="submit" id="btnCortar" value="Confirmar Cortes" class="btn" style="margin-top: 10px; margin-bottom: 15px">
    </form>
</fieldset>
<fieldset>
    <legend>Pedidos</legend>
    <?php echo $this->grid; ?>
</fieldset>
