<?php
if ($this->permiteCortes == 'S') {
    echo $this->form;
} else {
    echo "Corte Desabilitado no WMS";
    echo "<script>alert('Os cortes foram desabilitados no WMS'); </script>";
}

?>

<div id="gridCorte">
    <?php
    if ($this->permiteCortes == 'S') {
        echo $this->grid;
    }
    ?>
</div>

<div id="motivoCorte">
    <?php
    if ($this->permiteCortes == 'S') {
        echo $this->formMotivo;
    }
    ?>
</div>


<div id="arrCortes">
    <?php
        echo $this->pedidos;
    ?>
</div>


<input type="hidden" name="id" id="id" value="<?php echo $this->id ?>">

<script>

    function confirmaCorte() {
        event.preventDefault();

        var table = document.getElementsByClassName("expedicao-corte-produtos-grid");
        var rows = table[0].getElementsByClassName("gTResultSet");
        var rowsCorte = document.getElementsByClassName("grid-corte-resumo");

        var cortes = [];

        for(var i = 0 ; i < rows.length ; i++) {
            var columns = rows[i].getElementsByTagName('td');
            var codPedido   = rowsCorte[i].getElementsByTagName('td').item(0).innerHTML;
            var idEmbalagem = columns[5].children.item(0).value;
            var qtdCortar   = columns[6].children.item(0).value;

            if (qtdCortar >0) {
                var corte = [];
                corte[0] = codPedido;
                corte[1] = idEmbalagem;
                corte[2] = qtdCortar;

                cortes[cortes.length] = corte;
            }
        }

        if (cortes.length <= 0) {
            alert("Selecione ao menos um pedido para cortar");
            return;
        }

        if ($('#motivo').val() == "") {
            alert("Selecione um motivo de corte");
            return;
        }

        $.ajax({
            url:  URL_MODULO + '/corte/confirma-corte-produto-ajax/',
            type: 'post',
            data: {
                codProduto: $('#codProduto').val(),
                grade: $('#grade').val(),
                motivo: $('#motivo').val(),
                cortes: cortes
            },
            success: function (data) {
                if (data.error) {
                    alert(data.error);
                } else {
                    alert("Produtos cortados com sucesso");
                    $("#gridCorte").html("");
                    $("#motivoCorte").html("");
                    $("#arrCortes").html("");
                }
            }
        });

    }

    function corteTotal() {
        event.preventDefault();


        //var rows = document.getElementsByClassName("gTResultSet");
        //var rows = document.getElementsByTagName("tr");

        var table = document.getElementsByClassName("expedicao-corte-produtos-grid");
        var rows = table[0].getElementsByClassName("gTResultSet");
        var rowsCorte = document.getElementsByClassName("grid-corte-resumo");

        for(var i = 0 ; i < rows.length ; i++) {
            var columns = rows[i].getElementsByTagName('td');

            var fatorCorte     = rowsCorte[i].getElementsByTagName('td').item(9).innerHTML;
            var qtdPedidoUnit  = rowsCorte[i].getElementsByTagName('td').item(10).innerHTML;
            var qtdCortadaUnit = rowsCorte[i].getElementsByTagName('td').item(11).innerHTML;
            var idEmbalagem    = rowsCorte[i].getElementsByTagName('td').item(12).innerHTML;

            var qtdCortar = (qtdPedidoUnit - qtdCortadaUnit) / fatorCorte;

            columns[5].children.item(0).value = idEmbalagem;
            columns[6].children.item(0).value = qtdCortar;
        }

    }

    $('#btnSubmit').click(function () {
        $.ajax({
            url:  URL_MODULO + '/corte/corte-produto-ajax/',
            type: 'post',
            data: {
                id: $('#id').val(),
                codProduto: $('#codProduto').val(),
                grade: $('#grade').val(),
                acao: 'buscar'
            },
            success: function (data) {
                if (data.error) {
                    $("#gridCorte").html("");
                    $("#motivoCorte").html("");
                    $("#arrCortes").html("");
                    alert(data.error);
                } else {
                    $("#gridCorte").html(
                        "<fieldset>" +
                        "<legend>Pedidos</legend>" +
                        "<form style='margin-bottom: -15px'> " +
                        "   <div align='right' class='gMassAction'>\n" +
                        "       <input onclick='corteTotal()' style='margin: 5px 15px 5px 10px; width: 130px;' type='submit' name='total' id='total' value='Corte Total' class='btn'>" +
                        "   </div>\n" +
                        "</form>"
                        + data.resultGrid +
                        "</legend>");
                    $("#motivoCorte").html(data.resultForm);
                    $("#arrCortes").html(data.pedidos);
                }
            }
        });
    });
</script>
