<?php
    echo $this->form;
?>
<div id="gridCorte">
    <fieldset>
        <legend>Pedidos</legend>
        <form style="margin-bottom: -15px">
            <div align="right" class="gMassAction">
                <input style="margin: 5px 15px 5px 10px; width: 130px;" type="submit" name="total" id="corteTotal" value="Corte Total" class="btn">
            </div>
        </form>
        <form id="formGrid" action="?" method="post">
            <div id="expedicao-corte-produtos-grid" class="grid">
                <table class="gTable expedicao-corte-produtos-grid">
                    <tbody>
                        <tr class="gTTitle">
                            <td><span>Expedicao</span></td>
                            <td><span>Carga</span></td>
                            <td><span>Pedido</span></td>
                            <td><span>Mapa</span></td>
                            <td><span>Cod.Cliente</span></td>
                            <td><span>Cliente</span></td>
                            <td><span>Itinerario</span></td>
                            <td><span>Qtd.Pedido</span></td>
                            <td><span>Emb.Corte</span></td>
                            <td><span>Qtd.Cortar</span></td>
                            <td><span>Qtd.Conf</span></td>
                            <td><span>Qtd.Corte/Mapa</span></td>
                            <td><span>Qtd.Cortada Total</span></td>
                        </tr>
                    </tbody>
                    <tbody id="result-list">
                    </tbody>
                </table>
            </div>
        </form>
    </fieldset>
</div>

<div id="motivoCorte">
    <?php
        echo $this->formMotivo;
    ?>
</div>

<script>

    let itens = [];
    let embs = [];
    let forcarEmbVenda = <?php echo ($this->forcaEmbVenda == "S") ? "true": "false" ?>;
    let idExpedicao = <?php echo $this->id ?>;

    function testShowGrid() {
        let grid = $("#gridCorte");
        if (!isEmpty(itens)) {
            grid.show();
        } else {
            grid.hide();
        }
    }

    function updateList()
    {
        let newTd = function (content) {
            return $("<td style='text-align:left'></td>").append( content );
        };
        let tbody = $("#result-list");
        tbody.html("");

        $.each(itens, function (i, item) {
            let newRow = $("<tr class='gTResultSet' id='row-item-" + i + "' >");

            newRow.append( newTd( idExpedicao ) );
            newRow.append( newTd( item.carga ) );
            newRow.append( newTd( item.id ) );
            newRow.append( newTd( item.mapa ) );
            newRow.append( newTd( item.codcli ) );
            newRow.append( newTd( item.cliente ) );
            newRow.append( newTd( item.itinerario ) );
            newRow.append( newTd( item.quantidadeUnitaria ) );
            let newEmbSelector = "";
            if (!isEmpty(embs)) {
                newEmbSelector = $("<select id='emb-" + i + "' data-index='" + i + "' class='qtdCortar' ></select>");
                if (forcarEmbVenda) newEmbSelector.prop("disabled", true);
                $.each(embs, function (l, emb) {
                    let selecionado = (forcarEmbVenda && (emb.fator == item.fatorEmbalagemVenda)) ? "selected" : "";
                    newEmbSelector.append("<option " + selecionado + " value='" + emb.id + "' data-index='" + l + "'>" + emb.dscEmb + "</option>");
                });
            }
            newRow.append( newTd( newEmbSelector ) );
            newRow.append( newTd( $("<input style='width:40px;' type='text' class='qtdCortar' id='qtdCortar-" + i + "' data-index='" + i + "'>") ) );
            newRow.append( newTd( item.qtdConf ) );
            newRow.append( newTd( item.qtdCortada ) );
            newRow.append( newTd( item.qtdCorteTotal ) );

            if ( getSaldoCorte(item) <= 0 ) newRow.find("input, select").prop("disabled", true);

            tbody.append(newRow);
        })
    }

    function getSaldoCorte(item) {
        let qtdCortada = parseFloat((!isEmpty(item.qtdCortadaUnitaria)) ? item.qtdCortadaUnitaria : item.qtdCorteTotalUnitaria);
        let qtdConferida = parseFloat(item.qtdConf);
        let qtdPedido = parseFloat(item.quantidadeUnitaria);
        let fator = parseFloat(embs[0].fator);
        return parseFloat((qtdPedido - parseFloat(qtdCortada + qtdConferida)) / fator);
    }

    function calculaCorte(input) {
        let index = input.data("index");
        let indexEmb = $("#emb-"+index).find(":selected").data("index");
        let inputQtd = $("#qtdCortar-"+index);
        let qtd = inputQtd.val();
        let item = itens[index];
        let qtdCortarUn = parseFloat(qtd * embs[indexEmb].fator);
        let saldo = getSaldoCorte(item);
        if ( qtdCortarUn > saldo ) {
            $.wmsDialogAlert({msg: "A quantidade excede o saldo disponível para corte! <br> Utilize uma embalagem menor ou reduza a quantidade!"},
                function (objInput) {
                    objInput.inputQtd.val("");
                    objInput.inputEven.focus();
                },
                {inputQtd: inputQtd, inputEven: input}
            );
        }
    }

    $(".qtdCortar").live("focusout", function () {
        calculaCorte($(this));
    });
    
    function confirmaCorte()
    {
        event.preventDefault();

        let cortes = [];

        $.each(itens, function (i, item) {
            let qtdCortar = $("#qtdCortar-" + i).val();
            if (!isEmpty(qtdCortar)) {
                var corte = [];
                corte[0] = item.ID;
                corte[1] = $("#emb-" + i).val();
                corte[2] = qtdCortar;
                corte[3] = item.mapa;

                cortes[cortes.length] = corte;
            }
        });

        if (cortes.length <= 0) {
            $.wmsDialogAlert({msg:"Selecione ao menos um pedido para cortar"});
            return;
        }

        if ($('#motivo').val() == "") {
            $.wmsDialogAlert({msg:"Selecione um motivo de corte"});
            return;
        }

        $.ajax({
            url:  URL_MODULO + '/corte/confirma-corte-produto-ajax/',
            type: 'post',
            data: {
                codProduto: $('#codProduto').val(),
                grade: $('#grade').val(),
                motivo: $('#motivo').val(),
                cortes: cortes,
            },
            success: function (data) {
                if (data.error) {
                    $.wmsDialogAlert({msg:data.error});
                } else {
                    $.wmsDialogAlert({msg:"Produto cortado com sucesso"});
                    itens = [];
                    $("#result-list").html("");
                    $("#motivoCorte").html("");
                }
            }
        });
    }

    $("#corteTotal").click( function(e) {
        e.preventDefault();
        $.each(itens, function (i, item) {
            calculaCorte(i);
            $("#qtdCortar-"+i).val(getSaldoCorte(item));
        });
    });

    function executeRequest() {
        $.ajax({
            url: URL_MODULO + '/corte/get-data-produto-corte-ajax/',
            type: 'post',
            data: {
                id: idExpedicao,
                codProduto: $('#codProduto').val(),
                grade: $('#grade').val()
            },
            success: function (data) {
                if (data.status === "error") {
                    $("#motivoCorte").html("");
                    $.wmsDialogAlert({msg: data.msg});
                } else {
                    itens = data.itens;
                    embs = data.embs;
                    updateList();
                    $("#motivoCorte").html(data.formMotivo);
                    testShowGrid();
                }
            }
        });
    }

    $('#btnSubmit').click(function () {
        validate();
    });

    $("input#codProduto, input#grade").keypress(function( event ) {
        if ((event.which === 13 || event.keyCode === 13)) {
            validate();
        }
    });

    function validate()
    {
        if (!isEmpty($("input#codProduto").val())){
            executeRequest();
        }
        else {
            $.wmsDialogAlert({msg: "Informe o código do produto!"});
        }
    }

    testShowGrid();
</script>
