<?php
    echo $this->form;
?>
<div id="gridCorte">
    <input type="hidden" id="idExpedicaoCorte" value="<?php echo $this->id ?>">
    <?php
        echo $this->grid;
    ?>
</div>
<input type="hidden" name="COD_MAPA_SEPARACAO" id="COD_MAPA_SEPARACAO" value="<?php echo $this->idMapa ?>">

<script>
    $('#btnSubmitPedido').click(function () {
        $.ajax({
            url:  URL_MODULO + '/corte/corte-pedido/',
            type: 'post',
            data: {
                id: $("#gridCorte #idExpedicaoCorte").val(),
                codProduto: $('#codProduto').val(),
                grade: $('#grade').val(),
                COD_MAPA_SEPARACAO: $('#COD_MAPA_SEPARACAO').val(),
                acao: 'buscar'
            },
            success: function (data) {
                $("#gridCorte").html(data.result);
            }
        });
    });
</script>
