<?php
if ($this->permiteCortes == 'S') {
    echo $this->form;
} else {
    echo "Corte Desabilitado no WMS";
    echo "<script>alert('Os cortes foram desabilitados no WMS'); </script>";
}

?>
<div id="motivoCorte">
    <?php
    if ($this->permiteCortes == 'S') {
        echo $this->formMotivo;
    }
    ?>
</div>

<div id="gridCorte">
    <?php
    if ($this->permiteCortes == 'S') {
        echo $this->grid;
    }
    ?>
</div>

<div id="arrCortes">
    <?php
        echo $this->pedidos;
    ?>
</div>


<input type="hidden" name="id" id="id" value="<?php echo $this->id ?>">

<script>

    function confirmaCorte() {
        var rows = document.getElementsByClassName("gTResultSet");
        for(var i = 0 ; i < rows.length ; i++) {
            var columns = rows[i].getElementsByTagName('td');
            var codPedido = columns[0].innerHTML;
            var idEmbalagem = columns[5].children.item(0).value;
            var qtdCortar = columns[6].children.item(0).value;

            $.ajax({
                url:  URL_MODULO + '/corte/confirma-corte-produto-ajax/',
                type: 'post',
                data: {
                    codProduto: $('#codProduto').val(),
                    grade: $('#grade').val(),
                    pedido: codPedido,
                    idEmbalagem: idEmbalagem,
                    qtdCortar: qtdCortar,

                },
                success: function (data) {
                    if (data.error) {
                        alert(data.error);
                    } else {
                        $("#motivoCorte").html(data.resultForm);
                    }
                }
            });
        }

        event.preventDefault();
    }

    function corteTotal() {

        var rows = document.getElementsByClassName("gTResultSet");
        //var rows = document.getElementsByTagName("tr");
        var rowsCorte = document.getElementsByClassName("teste");

        for(var i = 0 ; i < rows.length ; i++) {
            var columns = rows[i].getElementsByTagName('td');

            var fatorCorte     = rowsCorte[i].getElementsByTagName('td').item(9).innerHTML;
            var qtdPedidoUnit  = rowsCorte[i].getElementsByTagName('td').item(10).innerHTML;
            var qtdCortadaUnit = rowsCorte[i].getElementsByTagName('td').item(11).innerHTML;
            var idEmbalagem    = rowsCorte[i].getElementsByTagName('td').item(12).innerHTML;

            var qtdCortar = (qtdPedidoUnit - qtdCortadaUnit) / fatorCorte;

            columns[5].children.item(0).value = idEmbalagem;
            columns[6].children.item(0).value = qtdCortar;
        }

        event.preventDefault();
    }

    $('#btnSubmit').click(function () {
        $.ajax({
            url:  URL_MODULO + '/corte/corte-produto-ajax/',
            type: 'post',
            data: {
                id: $('#id').val(),
                codProduto: $('#codProduto').val(),
                grade: $('#grade').val(),
                COD_MAPA_SEPARACAO: $('#COD_MAPA_SEPARACAO').val(),
                acao: 'buscar'
            },
            success: function (data) {
                if (data.error) {
                    $("#gridCorte").html("");
                    $("#motivoCorte").html("");
                    alert(data.error);
                } else {
                    $("#gridCorte").html(
                        "<form style='margin-bottom: -15px'> " +
                        "   <div align='right' class='gMassAction'>\n" +
                        "       <input onclick='corteTotal()' style='margin: 5px 15px 5px 10px; width: 130px;' type='submit' name='total' id='total' value='Corte Total' class='btn'>" +
                        "   </div>\n" +
                        "</form>"
                        + data.resultGrid);
                    $("#motivoCorte").html(data.resultForm);
                    $("#arrCortes").html(data.pedidos);
                }
            }
        });
    });
</script>
