<form action="/expedicao/corte/cortar-item">
    <b>Motivo do Corte:</b>

    <select name="motivoCorte" id="motivoCorte" required mostrarselecione="1">
        <option value="" label="Selecione...">Selecione...</option>
        <?php
            foreach ($this->motivos as $key => $motivo) {
                echo '<option value="' . $key . '" label="' .$motivo. '">' . $motivo. '</option>';
            }
        ?>
    </select>
    <br />

    <input type="hidden" name="id" id="id" value="<?php echo $this->pedido; ?>">
    <input type="hidden" name="origin" id="origin" value="<?php echo $this->origin; ?>">
    <input type="hidden" name="COD_PRODUTO" id="COD_PRODUTO" value="<?php echo $this->produto; ?>">
    <input type="hidden" name="DSC_GRADE" id="DSC_GRADE" value="<?php echo $this->grade; ?>">
    <input type="hidden" name="expedicao" id="expedicao" value="<?php echo $this->expedicao; ?>">
    <input type="hidden" name="qtdConf" id="qtdConf" value="<?php echo $this->qtdConf; ?>">
    <input type="hidden" name="COD_MAPA_SEPARACAO" id="COD_MAPA_SEPARACAO" value="<?php if (isset($this->mapaPreSelected) && !empty($this->mapaPreSelected) ) echo $this->mapaPreSelected; ?>">
    <b>Senha:</b>
    <input type="password" name="senha" id="senha" value="" size="11" title="senha" required style="margin-right: 25px">
    <br />
    <b>Quantidade:</b>
    <input type="text" name="quantidade" id="quantidade" value="" size="4" required title="quantidade" style="margin-right: 25px">
    <input type="submit" name="submit" id="btnCortarPedido" value="Confirmar Cortes" class="btn" style="margin-top: 10px; margin-bottom: 15px">
</form>
