<?php
if ($this->permiteCortes == 'S') {
    echo $this->form;
} else {
    echo "Corte Desabilitado no WMS";
    echo "<script>alert('Os cortes foram desabilitados no WMS'); </script>";
}

?>
<div id="gridCorte">
    <?php
    if ($this->permiteCortes == 'S') {
        echo $this->grid;
    }
    ?>
</div>
<input type="hidden" name="id" id="id" value="<?php echo $this->id ?>">
<input type="hidden" name="COD_MAPA_SEPARACAO" id="COD_MAPA_SEPARACAO" value="<?php echo $this->idMapa ?>">

<script>
    $('#btnSubmit').click(function () {
        $.ajax({
            url:  URL_MODULO + '/corte/corte-antecipado-ajax/',
            type: 'post',
            data: {
                id: $('#id').val(),
                codProduto: $('#codProduto').val(),
                grade: $('#grade').val(),
                COD_MAPA_SEPARACAO: $('#COD_MAPA_SEPARACAO').val(),
                acao: 'buscar'
            },
            success: function (data) {
                $("#gridCorte").html(data.result);
            }
        });
    });
</script>
