<?php
    echo $this->form;
?>
<div id="gridCorte">
    <input type="hidden" id="forcarEmbVenda" value="<?php echo ($this->forcaEmbVenda == "S") ? "true": "false" ?>">
    <input type="hidden" id="idExpedicaoCorte" value="<?php echo $this->id ?>">
    <fieldset>
        <legend>Pedidos</legend>
        <form style="margin-bottom: -15px">
            <div align="right" class="gMassAction">
                <input style="margin: 5px 15px 5px 10px; width: 130px;" type="button" name="total" id="corteTotal" value="Corte Total" class="btn">
            </div>
        </form>
        <form id="formGrid" action="?" method="post">
            <div id="expedicao-corte-produtos-grid" class="grid">
                <table class="gTable expedicao-corte-produtos-grid">
                    <tbody>
                        <tr class="gTTitle">
                            <td><span>Expedicao</span></td>
                            <td><span>Carga</span></td>
                            <td><span>Pedido</span></td>
                            <td><span>Mapa</span></td>
                            <td id="colEnd"><span>Endereço</span></td>
                            <td><span>Cod.Cliente</span></td>
                            <td><span>Cliente</span></td>
                            <td><span>Itinerario</span></td>
                            <td><span>Qtd.Pedido</span></td>
                            <td id="colLote"><span>Lote</span></td>
                            <td><span>Emb.Corte</span></td>
                            <td><span>Qtd.Cortar</span></td>
                            <td><span>Qtd.Cortada</span></td>
                        </tr>
                    </tbody>
                    <tbody id="result-list">
                    </tbody>
                </table>
            </div>
        </form>
    </fieldset>
</div>

<div id="motivoCorte">
    <?php
        echo $this->formMotivo;
    ?>
</div>
<script>
    testShowGrid();
    $("#gridCorte").hide();
    $("#colEnd").hide();
    $("#colLote").hide();
</script>