<?php
    echo $this->form;
?>
<div id="gridCorte">
    <fieldset>
        <legend>Pedidos</legend>
        <form style="margin-bottom: -15px">
            <div align="right" class="gMassAction">
                <input style="margin: 5px 15px 5px 10px; width: 130px;" type="submit" name="total" id="corteTotal" value="Corte Total" class="btn">
            </div>
        </form>
        <form id="formGrid" action="?" method="post">
            <div id="expedicao-corte-produtos-grid" class="grid">
                <table class="gTable expedicao-corte-produtos-grid">
                    <tbody>
                        <tr class="gTTitle">
                            <td><span>Expedicao</span></td>
                            <td><span>Carga</span></td>
                            <td><span>Pedido</span></td>
                            <td><span>Mapa</span></td>
                            <td><span>Cod.Cliente</span></td>
                            <td><span>Cliente</span></td>
                            <td><span>Itinerario.</span></td>
                            <td><span>Qtd.Pedido</span></td>
                            <td><span>Emb.Corte</span></td>
                            <td><span>Qtd.Cortar</span></td>
                            <td><span>Qtd.Corte/Mapa</span></td>
                            <td><span>Qtd.Cortada Total</span></td>
                        </tr>
                    </tbody>
                    <tbody id="result-list">
                    </tbody>
                </table>
            </div>
        </form>
    </fieldset>
</div>

<div id="motivoCorte">
    <?php
        echo $this->formMotivo;
    ?>
</div>


<input type="hidden" name="id" id="id" value="<?php echo $this->id ?>">

<script>

    let itens = [];
    let forcarEmbVenda = <?php echo ($this->forcaEmbVenda == "S") ?>;
    
    function updateList()
    {
        let newTd = function (content) {
            return $("<td style='text-align:left'></td>").append( content );
        };
        let tbody = $("#result-list");
        tbody.clear();

        $.each(itens, function (i, item) {
            let newRow = $("<tr class='gTResultSet' id='row-item-" + i + "' >");

            newRow.append( newTd( item.expedicao ) );
            newRow.append( newTd( item.carga ) );
            newRow.append( newTd( item.mapa ) );
            newRow.append( newTd( item.cliente ) );
            newRow.append( newTd( item.dscCliente ) );
            newRow.append( newTd( item.itinerario ) );
            newRow.append( newTd( item.qtdPedido ) );

            if (!isEmpty(item.embs)) {
                let newEmbSelector = $("<select id='emb-" + i + "' ></select>");
                $.each(item.embs, function (l, emb) {
                    let selecionado = (emb.isEmbVenda) ? "selected='selected'" : "";
                    let enabled = (!forcarEmbVenda) ? "disabled=disabled" : "";
                    newEmbSelector.append("<option " + selecionado + " " + enabled + " value='" + emb.id + "'>" + emb.dscEmb + "</option>")
                });
                newRow.append(newTd(newEmbSelector));
            } else {
                newRow.append(newTd(""));
            }

            newRow.append( newTd( $("<input style='width:40px;' type='text' class='qtdCortar' id='qtdCortar-" + i + "' data-index='" + i + "'>") ) );
            newRow.append( newTd( item.qtdCortadoMapa ) );
            newRow.append( newTd( item.qtdCortadoTotal ) );

            tbody.append(newRow);
        })
    }
    
    function confirmaCorte()
    {

        let cortes = [];

        $.each(itens, function (i, item) {
            let qtdCortar = $("#qtdCortar-" + i).val();
            if (!isEmpty(qtdCortar)) {
                var corte = [];
                corte[0] = item.codPedido;
                corte[1] = $("#emb-" + i).val();
                corte[2] = qtdCortar;
                corte[3] = item.mapa;

                cortes[cortes.length] = corte;
            }
        });

        if (cortes.length <= 0) {
            $.wmsDialogAlert({msg:"Selecione ao menos um pedido para cortar"});
            return;
        }

        if ($('#motivo').val() == "") {
            $.wmsDialogAlert({msg:"Selecione um motivo de corte"});
            return;
        }

        $.ajax({
            url:  URL_MODULO + '/corte/confirma-corte-produto-ajax/',
            type: 'post',
            data: {
                codProduto: $('#codProduto').val(),
                grade: $('#grade').val(),
                motivo: $('#motivo').val(),
                cortes: cortes,
            },
            success: function (data) {
                if (data.error) {
                    $.wmsDialogAlert({msg:data.error});
                } else {
                    $.wmsDialogAlert({msg:"Produto cortado com sucesso"});
                    itens = [];
                    $("#result-list").clear()
                }
            }
        });
    }

    $("#corteTotal").click( function() {
        $.each(itens, function (i, item) {
            let qtdCortada = (!isEmpty(item.qtdCortadoMapa)) ? item.qtdCortadoMapa : item.qtdCortadoTotal;
            let qtdConferida = (!isEmpty(item.qtdConferidaMapa)) ? item.qtdConferidaMapa : item.qtdConferidaTotal;
            $("#qtdCortar-"+i).val((item.qtdPedido - (qtdCortada + qtdConferida)) / item.embs[0].fator);
        });
    });

    function executeRequest() {
        $.ajax({
            url: URL_MODULO + '/corte/corte-produto/',
            type: 'post',
            data: {
                id: $('#id').val(),
                codProduto: $('#codProduto').val(),
                grade: $('#grade').val()
            },
            success: function (data) {
                if (data.error) {
                    $("#motivoCorte").html("");
                    $.wmsDialogAlert({msg:data.error});
                } else {
                    itens = data.itens;
                    updateList();
                    $("#motivoCorte").html(data.resultForm);
                }
            }
        });
    }

    $('#btnSubmit').click(function () {
        validate();
    });

    $("input#codProduto, input#grade").keypress(function( event ) {
        if ((event.which === 13 || event.keyCode === 13)) {
            validate();
        }
    });

    function validate()
    {
        if (!isEmpty($("input#codProduto").val())){
            executeRequest();
        }
        else {
            $.wmsDialogAlert({msg: "Informe o código do produto!"});
        }
    }

    $(".qtdCortar").live("focusout", function () {
        var input = $(this);
        var tbody = input.parent().parent().parent();
        console.log(tbody);
        console.log(input.parent().parentNode);
    })
</script>
