<?php
echo $this->form;
?>
<div id="gridCorte">
    <?php echo $this->grid; ?>
</div>
<input type="hidden" name="id" id="id" value="<?php echo $this->id ?>">

<script>
    $('#btnSubmit').click(function () {
        $.ajax({
            url:  URL_MODULO + '/corte/corte-antecipado-ajax/',
            type: 'post',
            data: {
                id: $('#id').val(),
                codProduto: $('#codProduto').val(),
                grade: $('#grade').val(),
                acao: 'buscar'
            },
            success: function (data) {
                $("#gridCorte").html(data.result);
            }
        });
    });
</script>
