<form id="filtro-expedicao-mercadoria-form" class="filtro" action="">
    <div>
        <fieldset id="fieldset-busca">
            <legend>Filtros</legend>
            <table style="width:100%">
                <tr>
                    <td>Expedição:</td>
                    <td>Carga:</td>
                    <td>Pedido:</td>
                    <td>Data Inicio da Expedição:</td>
                    <td>Data Final da Expedição:</td>
                    <td rowspan="4"><?php echo $this->element->submit; ?></td>
                </tr>
                <tr>
                    <td><?php echo $this->element->idExpedicao; ?></td>
                    <td><?php echo $this->element->codCargaExterno ; ?></td>
                    <td><?php echo $this->element->pedido ; ?></td>
                    <td><?php echo $this->element->dataInicial1; ?> a <?php echo $this->element->dataInicial2; ?></td>
                    <td><?php echo $this->element->dataFinal1; ?> a <?php echo $this->element->dataFinal2; ?></td>
                    <td><?php echo $this->element->status; ?></td>
                </tr>
            </table>
        </fieldset>
    </div>
</form>