/* 
 * SCRIPT PARA: Alterações de banco para permitir bloqueio de endereços
 * DATA DE CRIAÇÃO: 23/09/2019 
 * CRIADO POR: Tarcísio César
 *
 */

INSERT INTO VERSAO (DTH, NUMERO_VERSAO, SCRIPT) VALUES (SYSDATE, '7.9', '02-bloqueio-de-endereco.sql');

ALTER TABLE DEPOSITO_ENDERECO ADD (BLOQUEADA_ENTRADA NUMBER(1) DEFAULT 0 NOT NULL, BLOQUEADA_SAIDA NUMBER(1) DEFAULT 0 NOT NULL);
UPDATE DEPOSITO_ENDERECO SET BLOQUEADA_ENTRADA = 1, BLOQUEADA_SAIDA = 1 WHERE IND_SITUACAO = 'B';
ALTER TABLE DEPOSITO_ENDERECO DROP COLUMN IND_SITUACAO;


 
 