INSERT INTO VERSAO (DTH, NUMERO_VERSAO, SCRIPT) VALUES (SYSDATE, '6.21.0','04-integracaoSqlSrv.sql');

/*
 * Só não pode rodar na DM
 */
UPDATE CONEXAO_INTEGRACAO SET PROVEDOR = 'SQLSRV' WHERE PROVEDOR = 'MSSQL';