INSERT INTO VERSAO (DTH, NUMERO_VERSAO, SCRIPT) VALUES (SYSDATE, '6.21.0','07-historico-resumo-estoque-detalhado.sql');


CREATE TABLE POSICAO_ESTOQUE_DETALHADA (
  COD_POSICAO_ESTOQUE       NUMBER (8)  NOT NULL ,
  PERIODO                   VARCHAR2 (20 BYTE) NOT NULL ,
  COD_PRODUTO               VARCHAR2 (20 BYTE) NOT NULL ,
  DSC_GRADE                 VARCHAR2 (20 BYTE) NOT NULL ,
  COD_DEPOSITO_ENDERECO     NUMBER (8)  NOT NULL ,
  COD_PRODUTO_VOLUME        NUMBER (8) ,
  SALDO_FINAL               NUMBER (20,10)
) LOGGING;


CREATE SEQUENCE SQ_POSICAO_ESTOQUE_DET_01
INCREMENT BY 1
START WITH 1
MAXVALUE 999999999999999999999999999
MINVALUE 0
NOCYCLE
NOCACHE
NOORDER;


CREATE OR REPLACE PROCEDURE PROC_POSICAO_ESTOQUE_DETALHADA (DATA_ESTOQUE IN VARCHAR2) AS
BEGIN
    DECLARE PERIODO_QUERY VARCHAR2(100);
            DTH_PARAM VARCHAR2(100);
BEGIN

    if DATA_ESTOQUE = 'ATUAL' THEN
        PERIODO_QUERY := TO_CHAR(SYSDATE,'MM/YYYY');
        DTH_PARAM     := '01/' || TO_CHAR(ADD_MONTHS(TRUNC(SYSDATE), 1),'MM/YY') || ' 00:00:00';
    ELSE
        PERIODO_QUERY := TO_CHAR(TO_DATE(DATA_ESTOQUE, 'DD/MM/YYYY'),'MM/YYYY');
        DTH_PARAM     := '01/' || TO_CHAR(ADD_MONTHS(TO_DATE(DATA_ESTOQUE, 'DD/MM/YYYY'), 1),'MM/YY') || ' 00:00:00';
    END IF;

    DELETE FROM POSICAO_ESTOQUE_DETALHADA WHERE PERIODO = PERIODO_QUERY;

    INSERT INTO POSICAO_ESTOQUE_DETALHADA (
            COD_POSICAO_ESTOQUE,
            PERIODO,
            COD_PRODUTO,
            DSC_GRADE,
            COD_DEPOSITO_ENDERECO,
            COD_PRODUTO_VOLUME,
            SALDO_FINAL)
    SELECT SQ_POSICAO_ESTOQUE_DET_01.NEXTVAL as COD_POSICAO_ESTOQUE,
           PERIODO_QUERY as PERIODO,
           HE.COD_PRODUTO,
           HE.DSC_GRADE,
           HE.COD_DEPOSITO_ENDERECO,
           HE.COD_PRODUTO_VOLUME,
           HE.SALDO_FINAL
      FROM HISTORICO_ESTOQUE HE
     INNER JOIN (SELECT MAX(COD_HISTORICO_ESTOQUE) COD_HISTORICO_ESTOQUE
                   FROM HISTORICO_ESTOQUE HE
                  WHERE TO_DATE(DTH_MOVIMENTACAO,'DD/MM/YY HH24:MI:SS') < TO_DATE(DTH_PARAM,'DD/MM/YY HH24:MI:SS')
                  GROUP BY COD_PRODUTO, DSC_GRADE, COD_DEPOSITO_ENDERECO, COD_PRODUTO_VOLUME) M
        ON M.COD_HISTORICO_ESTOQUE = HE.COD_HISTORICO_ESTOQUE
     WHERE HE.SALDO_FINAL > 0;
END;
END PROC_POSICAO_ESTOQUE_DETALHADA;

BEGIN
    DBMS_SCHEDULER.CREATE_JOB (
            job_name => '"JOB_ESTOQUE_DETALHADO"',
            job_type => 'STORED_PROCEDURE',
            job_action => 'PROC_POSICAO_ESTOQUE_DETALHADA',
            number_of_arguments => 1,
            start_date => NULL,
            repeat_interval => 'FREQ=DAILY;BYDAY=MON,TUE,WED,THU,FRI,SAT,SUN;BYHOUR=23;BYMINUTE=55;BYSECOND=0',
            end_date => NULL,
            enabled => FALSE,
            auto_drop => FALSE,
            comments => '');

    DBMS_SCHEDULER.SET_JOB_ARGUMENT_VALUE(
             job_name => '"JOB_ESTOQUE_DETALHADO"',
             argument_position => 1,
             argument_value => 'ATUAL');

    DBMS_SCHEDULER.SET_ATTRIBUTE(
             name => '"JOB_ESTOQUE_DETALHADO"',
             attribute => 'logging_level', value => DBMS_SCHEDULER.LOGGING_OFF);

    DBMS_SCHEDULER.enable(
             name => '"JOB_ESTOQUE_DETALHADO"');
END;


EXECUTE PROC_POSICAO_ESTOQUE_DETALHADA('01/01/2017');
EXECUTE PROC_POSICAO_ESTOQUE_DETALHADA('01/02/2017');
EXECUTE PROC_POSICAO_ESTOQUE_DETALHADA('01/03/2017');
EXECUTE PROC_POSICAO_ESTOQUE_DETALHADA('01/04/2017');
EXECUTE PROC_POSICAO_ESTOQUE_DETALHADA('01/05/2017');
EXECUTE PROC_POSICAO_ESTOQUE_DETALHADA('01/06/2017');
EXECUTE PROC_POSICAO_ESTOQUE_DETALHADA('01/07/2017');
EXECUTE PROC_POSICAO_ESTOQUE_DETALHADA('01/08/2017');
EXECUTE PROC_POSICAO_ESTOQUE_DETALHADA('01/09/2017');
EXECUTE PROC_POSICAO_ESTOQUE_DETALHADA('01/10/2017');
EXECUTE PROC_POSICAO_ESTOQUE_DETALHADA('01/11/2017');
EXECUTE PROC_POSICAO_ESTOQUE_DETALHADA('01/12/2017');


EXECUTE PROC_POSICAO_ESTOQUE_DETALHADA('01/01/2018');
EXECUTE PROC_POSICAO_ESTOQUE_DETALHADA('01/02/2018');
EXECUTE PROC_POSICAO_ESTOQUE_DETALHADA('01/03/2018');
EXECUTE PROC_POSICAO_ESTOQUE_DETALHADA('01/04/2018');
EXECUTE PROC_POSICAO_ESTOQUE_DETALHADA('01/05/2018');
EXECUTE PROC_POSICAO_ESTOQUE_DETALHADA('01/06/2018');
EXECUTE PROC_POSICAO_ESTOQUE_DETALHADA('01/07/2018');
EXECUTE PROC_POSICAO_ESTOQUE_DETALHADA('01/08/2018');
EXECUTE PROC_POSICAO_ESTOQUE_DETALHADA('01/09/2018');
EXECUTE PROC_POSICAO_ESTOQUE_DETALHADA('01/10/2018');
