<form id="" method="post" class="saveForm" action="">
    <input type="hidden" name="idOrdemServico" id="idOrdemServico" value="<?php echo $this->idOrdemServico; ?>" >
    <input type="hidden" name="qtdNFs" id="qtdNFs" value="<?php echo $this->qtdNFs; ?>" >
    <input type="hidden" name="qtdAvarias" id="qtdAvarias" value="<?php echo $this->qtdAvarias; ?>" >
    <input type="hidden" name="qtdConferidas" id="qtdConferidas" value="<?php echo $this->qtdConferidas; ?>" >
    <input type="hidden" name="idConferente" id="idConferente" value="<?php echo $this->idConferente; ?>" >
    <input type="hidden" name="unMedida" id="unMedida" value="<?php echo $this->unMedida; ?>" >
    <input type="hidden" name="dataValidade" id="dataValidade" value="<?php echo $this->dataValidade; ?>" >
    <input type="hidden" name="conferenciaCega" id="conferenciaCega" value="<?php echo $this->conferenciaCega; ?>" >
    <div id="quantidade-grid" class="grid">
        <table class="gTable">
            <tbody>
            <tr>
                <td>
                    <div>
                        <p><b>Data validade menor que prazo maximo de Shelf Life</b></p>
                        <p><b>Autoriza Recebimento?</b></p>
                    </div>
                </td>
            </tr>
            <tr style="line-height: 50px;">
                <td colspan="3">
                    <?php
                    echo '<label>Senha para confirmação: </label>';
                    echo $this->formPassword("senhaConfirmacao", '', array(
                        'size' => '50',
                        'maxlength' => '20',
                    ));
                    ?>
                    <button name="btnFinalizar" type="submit" value="semConferencia">Autorizar Recebimento</button>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</form>