<?php
$placaVeiculo = '';

if ($this->placaVeiculo)
    $placaVeiculo = $this->placaVeiculo;

if ($this->emissor) {
    $emissor = $this->emissor;
}
?>
<div class="row" >
    <table class="info table">
        <caption>Recebimento:  <?php echo $this->recebimento->getId() ?> - <?php echo $this->recebimento->getBox()->getDescricao() ?> - <?php echo $this->recebimento->getDataInicial() ?></caption>
        <caption>Veículo: <?php echo $placaVeiculo ?></caption>
        <caption>Emissor: <?php echo $this->emissor ?></caption>
        <?php
        if (isset($this->listaProdutos)):
            ?>
            <tr>
                <td colspan="2"><b>Produtos a serem conferidos</b></td>
            </tr>
            <tr>
                <td style="padding: 35px;">
                    <div id="carousel" class="row">
                        <?php foreach ($this->listaProdutos as $produto): ?>
                            <div class="row" id="lista-produto<?php echo $produto['codigo'] ?>"><?php echo $produto['codigo'] ?> - <?php echo $produto['descricao'] ?> - <?php echo $produto['grade'] ?></div>
                        <?php endforeach; ?>
                    </div>
                </td>
            </tr>
            <tr>
                <td style="width: 20%"> <button style="margin-top: 25px;" class="btn gradientBtn" id="next"> >| </button></td>
            </tr>
            <?php
        endif;
        ?>
    </table>
</div>