<?php echo $this->render('recebimento/produto-detalhes.phtml');

$cssQtd = 'col-xs-12';

if ($this->itemNF['validade'] == 'S') {
    $cssQtd = 'col-lg-3 col-md-4 col-xs-5';
}

$lblQtd = ($this->indFracionavel == "S") ? \Wms\Domain\Entity\Produto::$listaUnidadeMedida[$this->itemNF['unidFracao']] . "S" : "Quantidade";

?>
<div class="row" >
    <form method="post" id="recebimento-embalagem-quantidade-form" action="<?php echo $this->url(array('controller' => 'recebimento', 'action' => 'produto-conferencia')); ?>" accept-charset="UTF-8" enctype="application/x-www-form-urlencoded">

        <input type="hidden" id="idRecebimento" name="idRecebimento" value="<?php echo $this->recebimento->getId() ?>" />
        <input type="hidden" id="idProdutoEmbalagem" name="idProdutoEmbalagem" value="<?php echo $this->itemNF['idEmbalagem'] ?>" />
        <input type="hidden" id="unidadePorEmbalagem" name="unidadePorEmbalagem" value="<?php echo ($this->indFracionavel != "S") ? $this->itemNF['quantidadeEmbalagem'] : 1 ?>" />
        <input type="hidden" id="isEmbFracDefault" name="isEmbFracDefault" value="<?php echo $this->embFracionavelDefault ?>" />

        <div class="row margin-row">
            <div class="col-md-4 col-xs-4 text-center">
                <div class="row"><b>Descrição Emb.</b></div>
                <div class="row">
                    <?php if ($this->embFracionavelDefault == 'S'){
                        $txtEmb = \Wms\Domain\Entity\Produto::$listaUnidadeMedida[$this->itemNF['unidFracao']];
                        $dscEmb = $this->itemNF['descricaoEmbalagem']." ($txtEmb)";
                        echo $dscEmb;
                    } else {
                        echo $this->itemNF['descricaoEmbalagem'];
                    }
                    ?>
                </div>
            </div>
            <div class="col-md-8 col-xs-5 text-center">
                <div class="row"><b>Código de Barras</b></div>
                <div class="row" id="codBarras"><?php echo $this->itemNF['codigoBarras'] ?></div>
            </div>
        </div>
        <div class="row margin-row">
            <div class="col-md-4 col-xs-4 text-center">
                <div class="row"><b>Norma:</b></div>
                <div class="row"><?php echo $this->itemNF['numLastro'] . ' x ' . $this->itemNF['numCamadas'] . ' = ' . $this->itemNF['numNorma'] ?></div>
            </div>
            <div class="col-md-8 col-xs-5 text-center">
                <div class="row"><label class="field required" for="idNormaPaletizacao">Unitizador</label></div>
                <div class="row">
                    <select class="required" id="idNormaPaletizacao" name="idNormaPaletizacao">
                    <?php foreach ($this->normasPaletizacao as $id => $descricao): ?>
                        <option value="<?php echo $id; ?>" <?php echo $this->itemNF['idNorma'] == $id ? "selected" : ""; ?>><?php echo $descricao; ?></option>
                    <?php endforeach; ?>
                    </select>
                </div>
            </div>
        </div>
        <div class="row margin-row">
            <div class="col-xs-9 text-center">
            <?php if ($this->indFracionavel != 'S') : ?>
                <b>Unids. Por Emb. : <?php echo $this->itemNF['quantidadeEmbalagem'] ?></b>
            <?php elseif ($this->indFracionavel == 'S' && !empty($this->dscEmbFracDefault)) : ?>
                <b><label class="field required" for="qtdUnidFracionavel">Qtd de: <?php echo $this->dscEmbFracDefault ?>'s</label></b>
                <input type="text" value="1" size="6" name="qtdUnidFracionavel" id="qtdUnidFracionavel" class="required"/>
            <?php endif; ?>
            </div>
        </div>
        <?php if ($this->itemNF['validade'] == 'S') : ?>
        <div class="row margin-row">
            <div class="col-xs-10">
                <label class="required" for="dataValidade">
                    <b>Data Validade: </b>
                    <input type="text" placeholder="dd/mm/yy" maxlength="8" size="6" class="required validade-input" id="dataValidade" name="dataValidade"/>
                </label>
            </div>
        </div>
        <?php endif; ?>
        <div class="row margin-row">
            <div class="col-md-4 col-xs-9 text-center">
            <?php if ($this->pesoVariavel != 'S') :?>
                <table id="conferencias">
                    <tr class="margin-row">
                        <th>nº</th>
                        <th><b><?php echo $lblQtd?></b></th>
                        <?php if ($this->controlaLote == 'S') : ?>
                        <th width="40%"><b>Lote(s):</b></th>
                        <th width="20%"></th>
                        <?php endif; ?>
                    </tr>
                    <tr id="row-inputs-0" data-id="0" class="input-row">
                        <td>1</td>
                        <td><input type="text" maxlength="15" size="6" id="qtdConferida-0" name="qtdConferida[0]" class="qtd-input" /></td>
                        <?php if ($this->controlaLote == 'S') : ?>
                        <td><input type="text" size="11" id="lote-0" name="lotes[0]" class="lote-input"/></td>
                        <td></td>
                        <?php endif; ?>
                    </tr>
                </table>
            <?php else : ?>
                <div class="row margin-row">
                    <b><label class="field required" for="numPeso">Peso (Kg)</label></b>
                </div>
                <div class="row">
                    <input type="text" maxlength="15" size="6" class="required" id="numPeso" name="numPeso"/>
                </div>
            <?php endif; ?>
            </div>

        </div>
        <div class="row">
            <div class="col-xs-10 margin-row text-center">
                <?php if ($this->indFracionavel != 'S') : ?>
                    <div class="row"><b>Total Unidades:&nbsp;</b><span id="totalQuantidade">0</span></div>
                <?php else : ?>
                    <div class="row"><b>Total Recebido:&nbsp;</b><span id="totalQuantidade">0</span></div>
                <?php endif; ?>
            </div>
        </div>

        <div class="row margin-row">
            <?php if ($this->indFracionavel == 'S') : ?>
                <p>Para a fração utilizar ponto "." ex.: 3.25</p>
            <?php endif; ?>
            <button type="button" class="btn gradientBtn"  id="submitBtn">Salvar</button>
        </div>
    </form>
</div>

<div id="dummy"></div>
<bgsound id="bgSoundId" loop="0" volume="100" />

<script>
    $(function () {
        var controlaLote     = <?php echo ($this->controlaLote == 'S') ? "true" : "false"?>;
        var controlaValidade = <?php echo ($this->itemNF['validade'] == 'S') ? "true" : "false"?>;
        var pesoVariavel     = <?php echo ($this->pesoVariavel == 'S') ? "true" : "false"?>;

        $(document).ready(function () {
            if (controlaValidade) {
                $("#dataValidade").focus().select()
            } else if (pesoVariavel) {
                $("#numPeso").focus().select()
            } else {
                $("#qtdConferida-0").focus().select()
            }
        });

        $("#recebimento-embalagem-quantidade-form").submit(function (event) {
            event.preventDefault();
        });

        $("input:text").live("keyup", function ( event ) {
            if ( event.which === 13  || event.keyCode === 13 ) {
                if ($(this).hasClass("lote-input")) {
                    if ($(this).parent().parent().data("id") === $(".input-row").last().data("id")) {
                        if (!isEmpty($(this).val())) {
                            addNewRow($(this).parent().parent().data("id"));
                            $("#qtdConferida-" + $(this).parent().parent().data("id")).removeAttr("style");
                        } else {
                            removeRowLote($(this).parent().parent().data("id"));
                            $("#recebimento-embalagem-quantidade-form").off('submit').trigger('submit');
                        }
                    } else {
                        $(".lote-input").last().focus().select();
                    }
                } else if ($(this).hasClass("qtd-input")) {
                    if (controlaLote) {
                        $("#lote-" + $(this).parent().parent().data("id")).focus().select();
                    } else if (checkInputs(false)) {
                        $("#recebimento-embalagem-quantidade-form").off('submit').trigger('submit');
                    }
                } else if ($(this).hasClass("validade-input")) {
                    $("#qtdConferida-0").focus().select();
                } else if (checkInputs(true)) {
                    $("#recebimento-embalagem-quantidade-form").off('submit').trigger('submit');
                }
            }
        });

        $("#qtdConferida-0").keyup(function () {
            $("#totalQuantidade").text($(this).val() * $("#unidadePorEmbalagem").val());
        });

        var calcTotalLote = function () {
            var inputQtd, inputLote = null;
            var sumTotal = 0;
            var rows = $(".input-row");
            for(var k = 0; k < rows.length; k++){
                if (!isEmpty($("#row-inputs-"+k))) {
                    inputQtd = $("#qtdConferida-" + k);
                    inputLote = $("#lote-" + k);
                    if (!isEmpty(inputQtd.val()) && !isEmpty(inputLote.val())) {
                        sumTotal += parseFloat(inputQtd.val());
                    }
                }
            }
            $("#totalQuantidade").text(sumTotal);
        };

        $(".lote-input").live("focusout", function () {
            calcTotalLote();
        });

        var addNewRow = function (lastId) {
            var nextId = (lastId + 1);
            var newRow = $(
                '<tr id="row-inputs-' + nextId + '" data-id="' + nextId + '" class="input-row">' +
                    '<td>' + (nextId + 1)+ '</td>' +
                    '<td><input type="text" maxlength="15" size="6" id="qtdConferida-' + nextId + '" name="qtdConferida[' + nextId + ']"  class="qtd-input" /></td>' +
                    '<td><input type="text" size="11" id="lote-' + nextId + '" name="lotes[' + nextId + ']" class="lote-input"/></td>' +
                    '<td><img src="/img/icons/cancel.png"  class="remover-lote" id="' + nextId + '"></td>' +
                '</tr>');

            $("#conferencias").append(newRow);
            var lastInptQtd = $("#qtdConferida-" + lastId);
            $("#qtdConferida-" + nextId).attr("style","background-color: #bdbdbd !important").val(lastInptQtd.val());
            $(".lote-input").last().focus();
        };

        $(".remover-lote").live("click", function () {
            var id = $(this).attr("id");
            removeRowLote(id);
            alert("Removeu o lote na linha " + (parseInt(id)+1));
        });

        var removeRowLote = function (id) {
            $("#row-inputs-"+id).remove();
            calcTotalLote();
        }

        var checkInputs = function (toNext) {
            var inputVal = $("#dataValidade");

            if ( controlaValidade && isEmpty(inputVal.val())) {
                if (!toNext) {
                    playSound("/alarme.mp3");
                    alert("A data de validade não foi especificada");
                }
                inputVal.focus().select();
                return false;
            }

            var inputQtd = null;
            var msg = "";
            var result = true;

            if ( controlaLote ) {
                var inputLote = null;
                var rows = $(".input-row");
                for(var k = 0; k < rows.length; k++){
                    if (!isEmpty($("#row-inputs-"+k))) {
                        inputQtd = $("#qtdConferida-" + k);
                        inputLote = $("#lote-" + k);
                        if (isEmpty(inputQtd.val())) {
                            playSound("/alarme.mp3");
                            msg = "A quantidade na linha " + (k + 1) + " não pode ser 0 ou nula";
                            inputQtd.focus().select();
                            result = false;
                            break;
                        }
                        if ((k < (rows.length - 1) || (k === 0 && rows.length === 1))&& isEmpty(inputLote.val())) {
                            playSound("/alarme.mp3");
                            msg = "O lote na linha " + (k + 1) + " não pode ficar em branco";
                            inputLote.focus().select();
                            result = false;
                            break;
                        }
                    }
                }
                if (result && !toNext && isEmpty(inputLote.val())) {
                    rows.last().remove();
                }
            } else {
                inputQtd = (!pesoVariavel) ? $("#qtdConferida-0") : $("#numPeso") ;
                if (isEmpty(inputQtd.val())) {
                    playSound("/alarme.mp3");
                    msg = "A quantidade não pode ser 0 ou nula";
                    inputQtd.focus().select();
                    result = false;
                } else {
                    result = checkQtd();
                }
            }

            if (!toNext && !isEmpty(msg)) alert(msg);
            return result;
        };

        $("#dataValidade").keyup(function (event) {

            var v = $(this).val();

            v = v.replace(/\D/g, "");
            v = v.replace(/(\d{2})(\d)/, "$1/$2");
            v = v.replace(/(\d{2})(\d)/, "$1/$2");
            v = v.replace(/(\d{2})(\d{2})$/, "$1$2");

            $(this).val(v);

            if (v != '' && v.length == 8) {

                var strRegex = /^(((([0-2][0-8]|09|19)(-|\/)(0[1-9]|1[012]))|((29|30|31)(-|\/)(0[13578]|1[02]))|((29|30)(-|\/)(0[469]|11)))(-|\/)(\d{2}))|((29)(-|\/)(02)(-|\/)(([02468][048])|([13579][26])))$/;
                var regexp = new RegExp(strRegex);
                if (!regexp.test(v)) {
                    playSound("/alarme.mp3");
                    alert('A data ' + v + ' é inválida');
                    $(this).val('');
                    return false;
                } else {
                    if (checkValidade()) {
                        var quantidade = document.getElementById('qtdConferida-0');
                        if (quantidade) {
                            quantidade.select();
                            if (event.preventDefault) {
                                event.preventDefault();
                            } else {
                                event.returnValue = false;
                            }
                        }
                    }
                }
            }

        });

        $("#submitBtn").click(function () {
            if (!checkInputs() || !checkValidade()) return false;
            $("#recebimento-embalagem-quantidade-form").off('submit').trigger('submit');
        });

        function checkQtd() {
            if (controlaLote) {
                var rows = $(".input-row");
                for(var k = 0; k < rows.length; k++){
                    var qtdDigitada = $("#qtdConferida-" + k).val();
                    if (validaQuantidade(qtdDigitada) == false) {
                        $("#qtdConferida-" + k).focus().select();
                        return false;
                    }
                }
            } else {
                var qtdDigitada = $("#qtdConferida-0").val();
                if (validaQuantidade(qtdDigitada) == false) {
                    $("#qtdConferida-0").focus().select();
                    return false;
                }
            }
            return true;
        }

        function validaQuantidade(qtd) {
            var codBarras = $("#codBarras").text();

            if (qtd == codBarras) {
                var alert = "Quantidade informada é igual ao código de barras bipado. Confirma conferencia de " + qtd;
                if (confirm(alert) == false) {
                    playSound("/alarme.mp3");
                    return false;
                }
            } else if (qtd > 9999999) {
                var alert = "Quantidade conferida elevada. Confirma a quantidade conferida de " + qtd;
                if (confirm(alert) == false) {
                    playSound("/alarme.mp3");
                    return false;
                }
            }
        }

        function checkValidade() {
            var obj = $("#dataValidade");
            if (obj.length) {
                var data = obj.val();
                if (data.length < 8) {
                    playSound("/alarme.mp3");
                    alert("O campo 'Data de validade' não foi preenchido corretamente!");
                    return false;
                }
                var hj = new Date();
                var validade = gerarData(data);
                if (validade <= hj) {
                    var hjStr = hj.toLocaleDateString();
                    var validadeStr = validade.toLocaleDateString();
                    playSound("/alarme.mp3");
                    alert("A data de validade ("+validadeStr+") não pode ser menor ou igual a data atual ("+hjStr+")");
                    obj.val('');
                    return false;
                }
            }
            return true;
        }

        function gerarData(str) {
            var partes = str.split("/");
            return new Date("20" + partes[2], partes[1] - 1, partes[0]);
        }

        function playSound(soundfile) {
            if (<?php echo $this->isOldBrowserVersion ?> === 'S') {
                document.getElementById("bgSoundId").src = soundfile;
            } else {
                var dummy = '<audio autoplay> <source src=' + soundfile + ' type="audio/mp3">' +
                    '<source src="' + soundfile + '" type="audio/mpeg"></audio>';
                $('#dummy').html(dummy);

            }
        }

    })

</script>