<?php echo $this->render('recebimento/produto-detalhes.phtml'); ?>
<div class="row" >
    <form method="post" id="recebimento-embalagem-quantidade-form" action="<?php echo $this->url(array('controller' => 'recebimento', 'action' => 'produto-conferencia')); ?>" accept-charset="UTF-8" enctype="application/x-www-form-urlencoded">

        <input type="hidden" id="idRecebimento" name="idRecebimento" value="<?php echo $this->recebimento->getId() ?>" />
        <input type="hidden" id="idItem" name="idItem" value="<?php echo $this->itemNF['idItem'] ?>" />
        <input type="hidden" id="idProdutoEmbalagem" name="idProdutoEmbalagem" value="<?php echo $this->itemNF['idEmbalagem'] ?>" />
        <input type="hidden" id="unidadePorEmbalagem" name="unidadePorEmbalagem" value="<?php echo ($this->indFracionavel != "S") ? $this->itemNF['quantidadeEmbalagem'] : 1 ?>" />
        <input type="hidden" id="isEmbFracDefault" name="isEmbFracDefault" value="<?php echo $this->embFracionavelDefault ?>" />

        <div class="row margin-row">
            <div class="col-md-3 col-xs-4 text-center">
                <div class="row"><b>Descrição Emb.</b></div>
                <div class="row">
                    <?php if ($this->embFracionavelDefault == 'S'){
                        $txtEmb = \Wms\Domain\Entity\Produto::$listaUnidadeMedida[$this->itemNF['unidFracao']];
                        $dscEmb = $this->itemNF['descricaoEmbalagem']." ($txtEmb)";
                        echo $dscEmb;
                    } else {
                        echo $this->itemNF['descricaoEmbalagem'];
                    }
                    ?>
                </div>
            </div>
            <div class="col-md-9 col-xs-8 text-center">
                <div class="row"><b>Código de Barras</b></div>
                <div class="row"><?php echo $this->itemNF['codigoBarras'] ?></div>
            </div>
        </div>

        <div>
            <table class="info  table">
<!--                <tr class="title">-->
<!--                    <td>Descrição Emb.</td>-->
<!--                    <td colspan="2">Código de Barras</td>-->
<!--                </tr>-->
<!--                <tr>-->
<!--                    <td>-->
<!--                        --><?php //if ($this->embFracionavelDefault == 'S'){
//                            $txtEmb = \Wms\Domain\Entity\Produto::$listaUnidadeMedida[$this->itemNF['unidFracao']];
//                            $dscEmb = $this->itemNF['descricaoEmbalagem']." ($txtEmb)";
//                            echo $dscEmb;
//                        } else {
//                            echo $this->itemNF['descricaoEmbalagem'];
//                        }
//                        ?>
<!--                    </td>-->
<!--                    <td colspan="2">--><?php //echo $this->itemNF['codigoBarras'] ?><!--</td>-->
<!--                </tr>-->

                <tr class="title padding-top">
                    <td>Norma:</td>
                    <td colspan="2"><label class="field required" for="idNormaPaletizacao">Unitizador</label></td>
                </tr>
                <tr>
                    <td><?php echo $this->itemNF['numLastro'] . ' x ' . $this->itemNF['numCamadas'] . ' = ' . $this->itemNF['numNorma'] ?></td>
                    <td colspan="2">
                        <select class=" required" mostrarselecione="" id="idNormaPaletizacao" name="idNormaPaletizacao">
                            <?php foreach ($this->normasPaletizacao as $id => $descricao): ?>
                                <option value="<?php echo $id; ?>" <?php echo $this->itemNF['idNorma'] == $id ? "selected" : ""; ?>><?php echo $descricao; ?></option>
                            <?php endforeach; ?>
                        </select>
                    </td>
                </tr>

                <tr class="title">
                    <?php if ($this->indFracionavel != 'S') : ?>
                        <td>Unidades Por Emb.</td>
                    <?php elseif ($this->indFracionavel == 'S' && !empty($this->dscEmbFracDefault)) : ?>
                        <td><label class="field required" for="qtdUnidFracionavel">Qtd de: <?php echo $this->dscEmbFracDefault ?>'s</label></td>
                    <?php else : ?>
                        <td></td>
                    <?php endif; ?>
                    <?php if ($this->itemNF['validade'] == 'S') : ?>
                        <td><label class="field required" for="dataValidade">Data Validade</label></td>
                    <?php endif; ?>
                    <?php if ($this->pesoVariavel != 'S') :
                            if ($this->indFracionavel == "S") :?>
                                <td><label class="field required" for="qtdConferida"><?php echo \Wms\Domain\Entity\Produto::$listaUnidadeMedida[$this->itemNF['unidFracao']] . "S"?></label></td>
                            <?php else : ?>
                                <td><label class="field required" for="qtdConferida">Quantidade</label></td>
                            <?php endif;
                        else : ?>
                        <td><label class="field required" for="numPeso">Peso (Kg)</label></td>
                    <?php endif; ?>
                    <?php if ($this->indFracionavel != 'S') : ?>
                        <td>Total Unidades</td>
                    <?php else : ?>
                        <td>Total Recebido</td>
                    <?php endif; ?>
                </tr>

                <tr>
                    <?php if ($this->indFracionavel != 'S') : ?>
                        <td><?php echo $this->itemNF['quantidadeEmbalagem'] ?></td>
                    <?php elseif ($this->indFracionavel == 'S' && !empty($this->dscEmbFracDefault)): ?>
                        <td><input type="text" value="1" size="6" name="qtdUnidFracionavel" id="qtdUnidFracionavel" class="required"/></td>
                    <?php else : ?>
                        <td></td>
                    <?php endif; ?>
                    <?php if ($this->itemNF['validade'] == 'S') : ?>
                        <td><input type="text" placeholder="dd/mm/yy" maxlength="8" size="10" class="required focus" id="dataValidade" name="dataValidade"/></td>
                    <?php endif; ?>
                    <?php if ($this->pesoVariavel != 'S') : ?>
                        <td><input type="text" maxlength="15" size="6" class="required <?php if ($this->itemNF['validade'] != 'S') : echo " focus "; endif ?>" id="qtdConferida" name="qtdConferida" /></td>
                    <?php else : ?>
                        <td><input type="text" maxlength="15" size="6" class="required focus" id="numPeso" name="numPeso"/></td>
                    <?php endif; ?>
                    <td><span id="totalQuantidade">0</span></td>
                </tr>
            </table>
            <?php if ($this->indFracionavel == 'S') : ?>
                <p>Para a fração utilizar ponto "." ex.: 3.25</p>
            <?php endif; ?>
        </div>
        <input type="submit" class="btn gradientBtn" value="Salvar" id="submit" name="submit">
    </form>
</div>

<script>
    $(function () {
        $("#dataValidade").keyup(function (event) {

            var v = $(this).val();

            v = v.replace(/\D/g, "");
            v = v.replace(/(\d{2})(\d)/, "$1/$2");
            v = v.replace(/(\d{2})(\d)/, "$1/$2");
            v = v.replace(/(\d{2})(\d{2})$/, "$1$2");

            $(this).val(v);

            if (v != '' && v.length == 8) {

                var strRegex = /^(((([0-2][0-8]|09|19)(-|\/)(0[1-9]|1[012]))|((29|30|31)(-|\/)(0[13578]|1[02]))|((29|30)(-|\/)(0[469]|11)))(-|\/)(\d{2}))|((29)(-|\/)(02)(-|\/)(([02468][048])|([13579][26])))$/;
                var regexp = new RegExp(strRegex);
                if (!regexp.test(v)) {
                    alert('A data ' + v + ' é inválida');
                    $(this).val('');
                    return false;
                } else {
                    if (checkValidade()) {
                        var quantidade = document.getElementById('qtdConferida');
                        if (quantidade) {
                            quantidade.focus();
                            if (event.preventDefault) {
                                event.preventDefault();
                            } else {
                                event.returnValue = false;
                            }
                        }
                    }
                }
            }

        });

        $("#recebimento-embalagem-quantidade-form").submit(function () {
            return checkValidade();
        });

        function checkValidade() {
            var obj = $("#dataValidade");
            if (obj.length) {
                var data = obj.val();
                if (data.length < 8) {
                    alert("O campo 'Data de validade' não foi preenchido corretamente!");
                    return false;
                }
                var hj = new Date();
                var validade = gerarData(data);
                if (validade <= hj) {
                    alert("A data de validade não pode ser menor ou igual a data atual");
                    obj.val('');
                    return false;
                }
            }
            return true;
        }

        function gerarData(str) {
            var partes = str.split("/");
            return new Date("20" + partes[2], partes[1] - 1, partes[0]);
        }
    })
</script>