<?php echo $this->render('recebimento/detalhes.phtml'); ?>
<?php echo $this->form; ?>

<div id="dummy"></div>
<bgsound id="bgSoundId" loop="0" volume="100" />

<script type="text/javascript">
    $(document).ready(function () {
        $('#carousel').cycle({
            fx: 'turnDown',
            next: '#next',
            timeout: 0
        });


        <?php if (isset($this->dataValidadeValida)) : ?>
            <?php if ($this->dataValidadeValida === 'true') : ?>
                var dataValidadeValida = 'true';
            <?php else : ?>
                var dataValidadeValida = 'false';
            <?php endif; ?>
        <?php else : ?>
            var dataValidadeValida = 'noAudio';
        <?php endif; ?>

        if (dataValidadeValida === 'false') {
            playSound("/alarme.mp3");
        } else if (dataValidadeValida === 'true'){
            playSound("/confirm2.mp3");
        }
    });

    function playSound(soundfile) {
        if (<?php echo $this->isOldBrowserVersion ?> === 'S') {
            document.getElementById("bgSoundId").src = soundfile;
        } else {
            var dummy = '<audio autoplay> <source src=' + soundfile + ' type="audio/mp3">' +
                '<source src="' + soundfile + '" type="audio/mpeg"></audio>';
            $('#dummy').html(dummy);

        }
    }

</script>
<span id="dummy"></span>
<div id="footer">
    <a href="<?php echo "/mobile/recebimento/finalizar/id/" . $this->idRecebimento . "/os/" . $this->os ?>" style="   margin-right: 0px; margin-top: 7px; float: left" class="finalizar">
        Finalizar
    </a>

    <?php if ($this->recebimento->getDeposito()->getUsaEnderecamento()) : ?>
    <a href="<?php echo "/mobile/enderecamento/listar-paletes/id/" . $this->idRecebimento . "/os/" . $this->os ?>" style="     margin-right: 1px;    margin-top: 7px;float: left" class="finalizarAmarelo">
        Endereçar
    </a>
    <?php endif ?>
    <a href="<?php echo "/mobile/recebimento/observacoes-recebimento/id/" . $this->idRecebimento ?>" style="    margin-top: 7px;float: left" id="btnShowObs">
        Observações
    </a>
</div>
