<?php echo $this->render('recebimento/produto-detalhes.phtml'); ?>

<div class="row table table-striped" >
    <form method="post" id="recebimento-volume-quantidade-form" action="<?php echo $this->url(array('controller' => 'recebimento', 'action' => 'produto-conferencia')); ?>" accept-charset="UTF-8" enctype="application/x-www-form-urlencoded">

        <input type="hidden" id="idRecebimento" name="idRecebimento"  value="<?php echo $this->recebimento->getId() ?>"/>
        <input type="hidden" id="idItem" name="idItem" value="<?php echo $this->itemNF['idItem'] ?>" />
        <input type="hidden" id="idProdutoVolume" name="idProdutoVolume" value="<?php echo $this->itemNF['idVolume'] ?>" />
        <input type="hidden" id="unidadePorVolume" value="0" name="quantidadeVolume" />

        <div class="row margin-row">
            <div class="col-md-8 col-xs-9 text-center">
                <div class="row"><b>Código de Barras</b></div>
                <div class="row"><?php echo $this->itemNF['codigoBarras'] ?></div>
            </div>
        </div>
        <div class="row margin-row">
            <div class="col-md-4 col-xs-4 text-center">
                Norma: <span style="font-weight: normal;"><?php echo $this->itemNF['numNorma'] ?></span>
            </div>
            <div class="col-md-8 col-xs-5 text-center">
                Sequência: <span style="font-weight: normal;"><?php echo $this->itemNF['sequenciaVolume'] ?></span>
            </div>
        </div>
        <?php if ($this->controlaLote == 'S') : ?>
        <div class="row margin-row">
            <div class="col-xs-10">
                <label class="field required" for="lote">
                    <b>Lote: </b>
                    <input type="text" size="11" class="required" id="lote" name="lote"/>
                </label>
            </div>
        </div>
        <?php endif; ?>
        <?php if ($this->itemNF['validade'] == 'S') : ?>
        <div class="row margin-row">
            <div class="col-xs-10">
                <label class="required" for="dataValidade">
                    <b>Data Validade: </b>
                    <input type="text" placeholder="dd/mm/yy" maxlength="8" size="6" class="required focus" id="dataValidade" name="dataValidade"/>
                </label>
            </div>
        </div>
        <?php endif; ?>
        <div class="row margin-row">
            <div class="col-md-4 col-xs-10 text-center">
                <?php if ($this->pesoVariavel != 'S') :?>
                <label class="field required" for="qtdConferida">
                    <b>Quantidade: </b>
                    <input type="text" maxlength="15" size="6" class="required <?php if ($this->itemNF['validade'] != 'S') : echo " focus "; endif ?>" id="qtdConferida" name="qtdConferida[0]"/>
                </label>
                <?php else : ?>
                <label class="field required" for="numPeso">
                    <b>Peso (Kg): </b>
                    <input type="text" maxlength="15" size="6" class="required focus" id="numPeso" name="numPeso"/>
                </label>
                <?php endif; ?>
            </div>
        </div>
        <input type="submit" class="btn gradientBtn" value="Salvar" id="submit" name="submit">
    </form>
</div>
