
<link rel="stylesheet" href="<?php echo $this->baseUrl('ParamQueryGrid/pqgrid.min.js') ?>" />
<script type="text/javascript" src="<?php echo $this->baseUrl('ParamQueryGrid/pqgrid.min.js') ?>" ></script>

<script>
    $(function(){
        var data = [ [1,'Exxon Mobil','339,938.0','36,130.0'],
            [2,'Wal-Mart Stores','315,654.0','11,231.0'],
            [3,'Royal Dutch Shell','306,731.0','25,311.0'],
            [4,'BP','267,600.0','22,341.0'],
            [5,'General Motors','192,604.0','-10,567.0'],
            [6,'Chevron','189,481.0','14,099.0'],
            [7,'DaimlerChrysler','186,106.3','3,536.3']];

        var obj = {};
        obj.width = 700;
        obj.height = 400;
        obj.colModel = [{title:"Rank", width:100, dataType:"integer"},
            {title:"Company", width:200, dataType:"string"},
            {title:"Revenues ($ millions)", width:150, dataType:"float", align:"right"},
            {title:"Profits ($ millions)", width:150, dataType:"float", align:"right"}];
        obj.dataModel = {data:data};
        $("#grid_array").pqGrid( obj );

    });

</script>   

<div id="grid_array"></div>
