/* 
 * SCRIPT PARA: Estrutura para permitir cadastro de tipos de notas, fornecedores serem tanto PJ quanto PF e vincular notas de devolução ao cliente
 * DATA DE CRIAÇÃO: 05/08/2020 
 * CRIADO POR: Tarcísio César
 *
 */
INSERT INTO VERSAO (DTH, NUMERO_VERSAO, SCRIPT) VALUES (SYSDATE, '7.17', 'xx-tipo-nota-fiscal.sql.sql');

ALTER TABLE TIPO_NOTA_ENTRADA ADD (IND_EMISSOR CHAR(1));
ALTER TABLE TIPO_NOTA_ENTRADA ADD (COD_EXTERNO VARCHAR(50));
ALTER TABLE TIPO_NOTA_ENTRADA ADD (SYS_DEFAULT CHAR(1) DEFAULT 0 NOT NULL);
/*
 * APOS INCLUIR OS CAMPOS IND_EMISSOR E COD_EXTERNO, ADEQUAR OS VALORES ANTES DE RODAR DAQUI PRA BAIXO
 */
ALTER TABLE TIPO_NOTA_ENTRADA MODIFY (IND_EMISSOR NOT NULL, COD_EXTERNO NOT NULL);
CREATE UNIQUE INDEX TIPO_NOTA_COD_EXTERNO ON TIPO_NOTA_ENTRADA (COD_EXTERNO);

/*
 * ANTES DE EXECUTAR ESTE TRECHO AVALIAR SE EXISTE OS REGISTROS 1 E 2 E SE EXISTE OUTRO ALEM DESTES NÃO UTILIZADOS
 */
UPDATE TIPO_NOTA_ENTRADA SET SYS_DEFAULT = 1, DSC_TIPO_NOTA_ENTRADA = 'COMPRA' WHERE COD_TIPO_NOTA_ENTRADA = 1;
UPDATE TIPO_NOTA_ENTRADA SET SYS_DEFAULT = 1, DSC_TIPO_NOTA_ENTRADA = 'DEVOLUÇÃO' WHERE COD_TIPO_NOTA_ENTRADA = 2;
DELETE FROM TIPO_NOTA_ENTRADA WHERE SYS_DEFAULT = 0;
