<style>
    .obs {
        font-size: 15px;
        font-weight: bold;
        text-align: center;
        text-shadow: #595959;
    }
</style>

<form id="filtro-produtividade-detalhada-form" method="get" class="filtro" action="">
    <div>
        <fieldset id="fieldset-busca">
            <legend>Filtros</legend>
            <?php echo $this->element->codInventarioERP; ?>
            <?php echo $this->element->btnSubmit; ?>
            <?php echo $this->element->btnExport; ?>
            <div class="obs"> <?php echo $this->element->obs->getValue(); ?> </div>
        </fieldset>
    </div>
</form>