
INSERT INTO VERSAO (DTH, NUMERO_VERSAO, SCRIPT) VALUES (SYSDATE, '5.0.0','7 correcao-valores-cubagem.sql');

ALTER TABLE PRODUTO_DADO_LOGISTICO DROP COLUMN NUM_CUBAGEM;
ALTER TABLE PRODUTO_DADO_LOGISTICO ADD NUM_CUBAGEM NUMBER(16,8);
UPDATE PRODUTO_DADO_LOGISTICO SET NUM_CUBAGEM = NUM_ALTURA * NUM_LARGURA * NUM_PROFUNDIDADE;