/* 
 * SCRIPT PARA: Estrutura para registrar data de criação do palete
 * DATA DE CRIAÇÃO: 10/06/2020 
 * CRIADO POR: Tarcísio César
 *
 */

INSERT INTO VERSAO (DTH, NUMERO_VERSAO, SCRIPT) VALUES (SYSDATE, '7.15', '03-dth-criacao-palete.sql');

ALTER TABLE PALETE ADD (DTH_CRIACAO DATE);

BEGIN
    FOR I IN (
        SELECT PL.UMA, NVL(NVL(HE.DTH_MOVIMENTACAO, RE.DTH_FINAL_RECEB), RE.DTH_INICIO_RECEB) AS DTH FROM PALETE PL
        INNER JOIN RECEBIMENTO RE ON PL.COD_RECEBIMENTO = RE.COD_RECEBIMENTO
         LEFT JOIN (SELECT HE1.UMA, HE1.DTH_MOVIMENTACAO FROM HISTORICO_ESTOQUE HE1 WHERE HE1.COD_HISTORICO_ESTOQUE IN (
                    SELECT MIN(HE2.COD_HISTORICO_ESTOQUE) FROM HISTORICO_ESTOQUE HE2 GROUP BY HE2.UMA)) HE ON HE.UMA = PL.UMA
        WHERE PL.DTH_CRIACAO IS NULL) LOOP

        UPDATE PALETE SET DTH_CRIACAO = I.DTH WHERE UMA = I.UMA;
    END LOOP;
END;

ALTER TABLE PALETE MODIFY (DTH_CRIACAO NOT NULL);