INSERT INTO VERSAO (DTH, NUMERO_VERSAO, SCRIPT) VALUES (SYSDATE, '7.0.0', '04-tabelas-lote.sql');

ALTER TABLE PRODUTO ADD (IND_CONTROLA_LOTE CHAR(1) DEFAULT 'N' NOT NULL);

CREATE TABLE LOTE
  (
    COD_LOTE NUMBER(11) NOT NULL,
    DSC_LOTE VARCHAR2 (200) NOT NULL,
    DTH_CRIACAO DATE NOT NULL,
    COD_PESSOA_CRIACAO NUMBER(11) NOT NULL,
    COD_PRODUTO VARCHAR2(20) NULL,
    DSC_GRADE VARCHAR2 (200) NULL,
    IND_ORIGEM_LOTE CHAR (1) NULL
  );

CREATE SEQUENCE SQ_LOTE_01
INCREMENT BY 1
START WITH 1
MAXVALUE 999999999999999999999999999
MINVALUE 0
NOCYCLE
NOCACHE
NOORDER;

ALTER TABLE LOTE ADD CONSTRAINT  PK_LOTE PRIMARY KEY (COD_LOTE);
-------------------------------------------------------------------------------

CREATE TABLE PEDIDO_PRODUTO_LOTE
  (
    COD_PEDIDO_PRODUTO_LOTE NUMBER(11) NOT NULL,
    COD_PEDIDO_PRODUTO NUMBER(11) NOT NULL,
    DSC_LOTE VARCHAR2 (200) NOT NULL,
    QUANTIDADE NUMBER(13,3) NULL,
    QTD_ATENDIDA NUMBER(13,3) NULL,
    QTD_CORTE NUMBER(13,3),
    IND_DEFINIDO CHAR (1) NULL
  );

CREATE SEQUENCE SQ_PEDIDO_PRODUTO_LOTE_01
INCREMENT BY 1
START WITH 1
MAXVALUE 999999999999999999999999999
MINVALUE 0
NOCYCLE
NOCACHE
NOORDER;

-------------------------------------------------------------------------------

CREATE TABLE NOTA_FISCAL_ITEM_LOTE
  (
    COD_NOTA_FISCAL_ITEM_LOTE NUMBER(11) NOT NULL,
    COD_NOTA_FISCAL_ITEM NUMBER(11) NOT NULL,
    DSC_LOTE VARCHAR2 (200),
    QUANTIDADE NUMBER(13,3) NULL
  );

CREATE SEQUENCE SQ_NOTA_FISCAL_ITEM_LOTE_01
INCREMENT BY 1
START WITH 1
MAXVALUE 999999999999999999999999999
MINVALUE 0
NOCYCLE
NOCACHE
NOORDER;

-------------------------------------------------------------------------------

ALTER TABLE RECEBIMENTO_VOLUME ADD DSC_LOTE VARCHAR2 (200);
ALTER TABLE RECEBIMENTO_EMBALAGEM ADD DSC_LOTE VARCHAR2 (200);
ALTER TABLE RECEBIMENTO_CONFERENCIA ADD DSC_LOTE VARCHAR2 (200);
ALTER TABLE RECEBIMENTO_CONFERENCIA ADD (IND_DIVERG_LOTE CHAR(1));
ALTER TABLE RESERVA_ESTOQUE_PRODUTO ADD DSC_LOTE VARCHAR2 (200);
ALTER TABLE MAPA_SEPARACAO_PRODUTO ADD DSC_LOTE VARCHAR2 (200);
ALTER TABLE ETIQUETA_SEPARACAO ADD DSC_LOTE VARCHAR2 (200);
ALTER TABLE ETIQUETA_CONFERENCIA ADD DSC_LOTE VARCHAR2 (200);
ALTER TABLE MAPA_SEPARACAO_CONFERENCIA ADD DSC_LOTE VARCHAR2 (200);
ALTER TABLE SEPARACAO_MAPA_SEPARACAO ADD DSC_LOTE VARCHAR2 (200);
ALTER TABLE PALETE_PRODUTO ADD DSC_LOTE VARCHAR2 (200);
ALTER TABLE ESTOQUE ADD DSC_LOTE VARCHAR2 (200);
ALTER TABLE ONDA_RESSUPRIMENTO_OS_PRODUTO ADD DSC_LOTE VARCHAR2 (200);
-------------------------------------------------------------------------------