/* 
 * SCRIPT PARA: Scripts gerais do Cross-Docking
 * DATA DE CRIAÇÃO: 21/01/2019 
 * CRIADO POR: Tarcísio César
 *
 */
DECLARE
  CHECK_RESULT VARCHAR2(100);
BEGIN
  SELECT FUNC_CHECK_SCRIPT('07-cross-docking.sql', '') INTO CHECK_RESULT FROM DUAL;
  IF (CHECK_RESULT <> 'TRUE') THEN
    DBMS_OUTPUT.PUT_LINE(CHECK_RESULT);
  ELSE
    INSERT INTO VERSAO (DTH, NUMERO_VERSAO, SCRIPT) VALUES (SYSDATE, '7', '07-cross-docking.sql');
    /************************************************************************
**        COLOQUE O SCRIPT À SER EXECUTADO ENTRE ESTA DEMARCAÇÃO       **
************************************************************************/

    INSERT INTO CARACTERISTICA_ENDERECO (COD_CARACTERISTICA_ENDERECO, DSC_CARACTERISTICA_ENDERECO) VALUES (40, 'CROSS DOCKING');

    EXECUTE IMMEDIATE 'ALTER TABLE TIPO_PEDIDO_EXPEDICAO ADD (COD_EXTERNO VARCHAR2(30))';
    DELETE FROM TIPO_PEDIDO_EXPEDICAO;

    INSERT INTO TIPO_PEDIDO_EXPEDICAO (COD_TIPO_PEDIDO_EXPEDICAO, DSC_TIPO_PEDIDO_EXPEDICAO, COD_EXTERNO) VALUES (1, 'Mostruário','MOSTRUARIO');
    INSERT INTO TIPO_PEDIDO_EXPEDICAO (COD_TIPO_PEDIDO_EXPEDICAO, DSC_TIPO_PEDIDO_EXPEDICAO, COD_EXTERNO) VALUES (2, 'Reposição','REPOSICAO');
    INSERT INTO TIPO_PEDIDO_EXPEDICAO (COD_TIPO_PEDIDO_EXPEDICAO, DSC_TIPO_PEDIDO_EXPEDICAO, COD_EXTERNO) VALUES (3, 'Entrega','ENTREGA');
    INSERT INTO TIPO_PEDIDO_EXPEDICAO (COD_TIPO_PEDIDO_EXPEDICAO, DSC_TIPO_PEDIDO_EXPEDICAO, COD_EXTERNO) VALUES (4, 'Sugestão','SUGESTAO');
    INSERT INTO TIPO_PEDIDO_EXPEDICAO (COD_TIPO_PEDIDO_EXPEDICAO, DSC_TIPO_PEDIDO_EXPEDICAO, COD_EXTERNO) VALUES (5, 'Avulso','AVULSO');
    INSERT INTO TIPO_PEDIDO_EXPEDICAO (COD_TIPO_PEDIDO_EXPEDICAO, DSC_TIPO_PEDIDO_EXPEDICAO, COD_EXTERNO) VALUES (6, 'Assistencia','ASSISTENCIA');
    INSERT INTO TIPO_PEDIDO_EXPEDICAO (COD_TIPO_PEDIDO_EXPEDICAO, DSC_TIPO_PEDIDO_EXPEDICAO, COD_EXTERNO) VALUES (7, 'Kit','KIT');
    INSERT INTO TIPO_PEDIDO_EXPEDICAO (COD_TIPO_PEDIDO_EXPEDICAO, DSC_TIPO_PEDIDO_EXPEDICAO, COD_EXTERNO) VALUES (8, 'Venda Balcão','VENDA_BALCAO');
    INSERT INTO TIPO_PEDIDO_EXPEDICAO (COD_TIPO_PEDIDO_EXPEDICAO, DSC_TIPO_PEDIDO_EXPEDICAO, COD_EXTERNO) VALUES (9, 'Simples Remessa','SIMPLES_REMESSA');
    INSERT INTO TIPO_PEDIDO_EXPEDICAO (COD_TIPO_PEDIDO_EXPEDICAO, DSC_TIPO_PEDIDO_EXPEDICAO, COD_EXTERNO) VALUES (10, 'Reentrega','REENTREGA');
    INSERT INTO TIPO_PEDIDO_EXPEDICAO (COD_TIPO_PEDIDO_EXPEDICAO, DSC_TIPO_PEDIDO_EXPEDICAO, COD_EXTERNO) VALUES (11, 'Pedido Antecipado','PEDIDO_ANTECIPADO');
    INSERT INTO TIPO_PEDIDO_EXPEDICAO (COD_TIPO_PEDIDO_EXPEDICAO, DSC_TIPO_PEDIDO_EXPEDICAO, COD_EXTERNO) VALUES (12, 'Outros','OUTROS');
    INSERT INTO TIPO_PEDIDO_EXPEDICAO (COD_TIPO_PEDIDO_EXPEDICAO, DSC_TIPO_PEDIDO_EXPEDICAO, COD_EXTERNO) VALUES (13, 'CROSS DOCKING','CROSS_DOCKING');

    BEGIN
      FOR I IN (SELECT COD_EXTERNO FROM TIPO_PEDIDO_EXPEDICAO) LOOP
        update pedido set cod_tipo_pedido = (select COD_TIPO_PEDIDO_EXPEDICAO from TIPO_PEDIDO_EXPEDICAO where COD_EXTERNO = I.COD_EXTERNO) where cod_tipo_pedido in (
          select cod_sigla from sigla where DSC_SIGLA = I.COD_EXTERNO and COD_TIPO_SIGLA = 70
        );
      END LOOP;
    END;

    /************************************************************************
**                 NÃO ALTERAR ABAIXO DESTA REGIÃO                     **
************************************************************************/
    DBMS_OUTPUT.PUT_LINE('Script executado com sucesso');
  END IF;
END;
 
 