INSERT INTO VERSAO (DTH, NUMERO_VERSAO, SCRIPT) VALUES (SYSDATE, '4.0.0', 'produtoPeso.sql');

CREATE TABLE PRODUTO_PESO
(
  COD_PRODUTO VARCHAR2(20 BYTE) NOT NULL ,
  DSC_GRADE VARCHAR2(10 BYTE) NOT NULL ,
  NUM_PESO NUMBER ,
  NUM_CUBAGEM NUMBER ,
  CONSTRAINT PRODUTO_PESO_PK PRIMARY KEY ( COD_PRODUTO , DSC_GRADE )
);

ALTER TABLE PRODUTO_PESO
	ADD CONSTRAINT PRODUTO_PESO_FK1 FOREIGN KEY( COD_PRODUTO , DSC_GRADE )
	REFERENCES PRODUTO ( COD_PRODUTO , DSC_GRADE )
ENABLE;

INSERT INTO PRODUTO_PESO (COD_PRODUTO, DSC_GRADE, NUM_PESO, NUM_CUBAGEM)
SELECT COD_PRODUTO, DSC_GRADE, NUM_PESO, NUM_CUBAGEM FROM SUM_PESO_PRODUTO;


