INSERT INTO VERSAO (DTH, NUMERO_VERSAO, SCRIPT) VALUES (SYSDATE, '4.0.0', 'relatorioIndicadoresProdutividade.sql');

INSERT INTO RECURSO (COD_RECURSO, COD_RECURSO_PAI, NOM_RECURSO, DSC_RECURSO)
VALUES (
  SQ_RECURSO_01.NEXTVAL,
  0,
  'produtividade:relatorio_indicadores',
  'Apontamento de Produtividade'
);

INSERT INTO RECURSO_ACAO (COD_RECURSO_ACAO, COD_RECURSO,COD_ACAO,DSC_RECURSO_ACAO)
VALUES (
  SQ_RECURSO_ACAO_01.NEXTVAL,
  (SELECT COD_RECURSO FROM RECURSO WHERE NOM_RECURSO LIKE 'produtividade:relatorio_indicadores'),
  (SELECT COD_ACAO FROM ACAO WHERE NOM_ACAO LIKE 'index'),
  'Apontamento de Produtividade'
);

INSERT INTO MENU_ITEM (COD_MENU_ITEM, COD_RECURSO_ACAO, COD_PAI, DSC_MENU_ITEM, NUM_PESO, DSC_URL, DSC_TARGET, SHOW)
VALUES (
  SQ_MENU_ITEM_01.NEXTVAL,
  (SELECT COD_RECURSO_ACAO
   FROM RECURSO_ACAO
   WHERE COD_RECURSO = (SELECT COD_RECURSO FROM recurso WHERE NOM_RECURSO LIKE 'produtividade:relatorio_indicadores')
         AND COD_ACAO = (SELECT COD_ACAO FROM acao WHERE NOM_ACAO LIKE 'index')),
  (SELECT COD_MENU_ITEM FROM MENU_ITEM WHERE COD_PAI = 0 AND DSC_MENU_ITEM = 'Relatórios'),
  'Apontamento de Produtividade', 5, '#', '_self', 'S'
);