create or replace PROCEDURE EXPORTA_EQUIPE_CARREGAMENTO AS 
BEGIN

execute immediate 'DROP TABLE EXPORTACAO_EQUIPE_CARREGAMENTO';

execute immediate 'CREATE TABLE EXPORTACAO_EQUIPE_CARREGAMENTO AS
SELECT E.COD_EXPEDICAO as EXPEDICAO,
       TO_CHAR(EQ.DTH_VINCULO,''DD/MM/YYYY HH24:MI:SS'') "DTH_VINCULO",
       U.DSC_IDENTIFICACAO_USUARIO as USUARIO,
       PES.NOM_PESSOA as PESSOA,
	   PF.NUM_CPF AS CPF_USUARIO
  FROM EQUIPE_CARREGAMENTO_EXPEDICAO EQ
  LEFT JOIN EXPEDICAO E ON E.COD_EXPEDICAO = EQ.COD_EXPEDICAO
  LEFT JOIN USUARIO U ON U.COD_USUARIO = EQ.COD_USUARIO
  LEFT JOIN PESSOA PES ON PES.COD_PESSOA = EQ.COD_USUARIO
  LEFT JOIN PESSOA_FISICA PF ON PF.COD_PESSOA = U.COD_USUARIO
                 WHERE (E.COD_STATUS <> 466)
                 AND (E.DTH_INICIO >= TO_DATE(''01-05-2015 00:00'', ''DD-MM-YYYY HH24:MI''))';

END EXPORTA_EQUIPE_CARREGAMENTO;