create or replace PROCEDURE EXPORTA_EQUIPE_DESCARGA AS 
BEGIN

execute immediate 'DROP TABLE EXPORTACAO_EQUIPE_DESCARGA ';

execute immediate 
'CREATE TABLE EXPORTACAO_EQUIPE_DESCARGA AS
SELECT RE.COD_RECEBIMENTO as RECEBIMENTO,
       TO_CHAR(RE.DTH_VINCULO,''DD/MM/YYYY HH24:MI:SS'') "DTH_VINCULO",
       U.DSC_IDENTIFICACAO_USUARIO as USUARIO,
       PES.NOM_PESSOA as PESSOA,
	   PF.NUM_CPF AS CPF_USUARIO
  FROM RECEBIMENTO_DESCARGA RE
  LEFT JOIN RECEBIMENTO R ON R.COD_RECEBIMENTO = RE.COD_RECEBIMENTO
  LEFT JOIN USUARIO U ON U.COD_USUARIO = RE.COD_USUARIO
  LEFT JOIN PESSOA PES ON PES.COD_PESSOA = RE.COD_USUARIO
  LEFT JOIN PESSOA_FISICA PF ON PF.COD_PESSOA = U.COD_USUARIO
  WHERE R.DTH_INICIO_RECEB >= TO_DATE(''01-05-2015 00:00'', ''DD-MM-YYYY HH24:MI'')';

END EXPORTA_EQUIPE_DESCARGA;