<form id="formulario" enctype="application/x-www-form-urlencoded" accept-charset="UTF-8" action="<?php echo $this->url(array('controller' => 'onda-ressuprimento', 'action' => 'finalizar')) ?>" method="post">
    <div class="table-responsive">
        <table class="gTable table-condensed" style="width: 100%">
            <?php if ($this->temLote) { ?>
                <tbody>
                <tr>
                    <td colspan="2"><b><?php echo $this->dscProduto ?></b></td>
                </tr>
                <tr>
                    <td><div class="row"><B>Cod:</B></div><div class="row"><?php echo $this->codProduto ?></div></td>
                    <td><div class="row"><B>Grade:</B></div><div class="row"><?php echo $this->grade ?></div></td>
                </tr>
                <tr>
                    <td><div class="row"><B>Lote:</B></div></td>
                    <td><div class="row"><B>Qtd:</B></div></td>
                </tr>
                <?php foreach ($this->qtd as $lote => $grupo) { ?>
                    <tr style="border-bottom: thin solid">
                        <td style="font-size: 14px"><div class="row"><?php echo $lote; ?>
                                <img style="display: none" id="lote-<?php echo $lote?>" src="/img/icons/accept.png"/></div>
                        </td>
                        <td style="font-size: 14px">
                            <?php foreach ($grupo as $item) { ?>
                                <div class="row"><?php echo $item; ?></div>
                            <?php } ?>
                        </td>
                    </tr>
                <?php } ?>
                <tr>
                    <td style="font-size: 145%"><B>Origem:</B> <?php echo $this->endPulmao ?></td>
                    <td style="font-size: 145%"><B>Destino:</B> <?php echo $this->endPicking ?></td>
                </tr>
                </tbody>
            <?php } else { ?>
                <tbody>
                <tr>
                    <td colspan="3"><b><?php echo $this->dscProduto ?></b></td>
                </tr>
                <tr>
                    <td><B>Cod:</B> <div class="row"><?php echo $this->codProduto ?></div></td>
                    <td><B>Grade:</B> <div class="row"><?php echo $this->grade ?></div></td>
                    <td style="font-size: 12px"><B>Qtd:</B>
                        <?php foreach ($this->qtd as $qtds) {
                            foreach ($qtds as $qtd) { ?>
                                <div class="row"><?php echo $qtd; ?></div>
                            <?php }
                        } ?>
                    </td>
                </tr>
                <tr>
                    <td colspan="1" style="font-size: 145%"><B>Origem:</B> <?php echo $this->endPulmao ?></td>
                    <td colspan="2" style="font-size: 145%"><B>Destino:</B> <?php echo $this->endPicking ?></td>
                </tr>
                </tbody>
            <?php } ?>
        </table>
    </div>
    <br>


<table>
    <tr>
        <td>
            <label style="font-size:17px" for="etiquetaProduto"><b>Produto</b></label>
            <input class="focus" type="text" name="etiquetaProduto" id="etiquetaProduto" value="" onkeydown="nextInput(event, this)" />
            <?php if ($this->temLote) { ?>
            <br>
            <label style="font-size:17px" for="codLote"><b>Lote</b></label>
            <input type="text" id="codLote" value="" onkeydown="nextInput(event, this)" />
            <?php } ?>
        </td>
        <td>
            <a class="finalizar" href="<?php echo $this->url(array('controller' => 'onda-ressuprimento', 'action' => 'selecionar-uma', 'idOnda' => $this->idOnda)); ?>">Alternar para U.M.A.</a>
        </td>
    </tr>
</table>

<br>
<div>
    <input type="submit" name="submit" id="submit" <?php if ($this->temLote) { ?> onclick="submitClick(event)" <?php } ?>value="Buscar" />
</div>

    <?php if ($this->produtos[0]->getCodProdutoVolume() !=NULL) {?>
        <div id="quantidade-grid" class="grid">
        <table class="gTable" style="width: 70%; margin-left: 5%; margin-right: 5%; margin-top: 3%; margin-bottom:  3%">
            <tbody>
            <tr class ="gTTitle">
                <td><b>Volumes</b></td>
                <td><b>Quantidade</b></td>
            </tr>
            <?php
            foreach ($this->produtos as $produto): $this->color = !($this->color);?>
                <tr class = "<?php if (!$this->color) {echo 'gTResultSet gRowColor';} else {echo 'gTResultSet';}?>">
                    <td><?php
                        /** @var \Doctrine\ORM\EntityManager $em */
                        $em = \Zend_Registry::get('doctrine')->getEntityManager();

                        if ($produto->getCodProdutoEmbalagem() == NULL) {
                            $volumeEn = $em->getRepository("wms:Produto\Volume")->findOneBy(array('id'=>$produto->getCodProdutoVolume()));
                            echo $volumeEn->getDescricao() ;
                        } else {
                            $embalagemEn = $em->getRepository("wms:Produto\Embalagem")->findOneBy(array('id'=>$produto->getCodProdutoEmbalagem()));
                            echo $embalagemEn->getDescricao() ;
                        }

                        ?></td>
                    <td><?php echo $produto->getQtd() ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
        <div class = "gPager"></div>
    <?php }?>


</form>
<div class = "gPager"></div>
<?php if ($this->temLote) { ?>
<script>
    var lotes = <?php echo $this->lotes?>;

    function nextInput(event, elem) {
        if (event.which === 13 || event.keyCode === 13) {
            var escaparSubmit = false;
            if (elem.id === "etiquetaProduto") {
                if (elem.value === "") {
                    alert("O código de barras não foi informado");
                    elem.focus();
                    escaparSubmit = true;
                } else {
                    var campoLote = $("#codLote");
                    if (campoLote.length) {
                        campoLote.focus();
                        escaparSubmit = true;
                    }
                }
            } else if (elem.id === "codLote") {
                var loteBipado = elem.value;
                if ( loteBipado === "") {
                    alert("O Lote não foi informado");
                    elem.focus();
                    escaparSubmit = true;
                } else {
                    var codBarra = $("#etiquetaProduto");
                    if (codBarra.val() === "") {
                        alert("O código de barras não foi informado");
                        codBarra.focus();
                        escaparSubmit = true;
                    } else {
                        if (loteBipado in lotes) {
                            lotes[loteBipado] = true;
                            var idSpan = "lote-" + loteBipado;
                            $("#" + idSpan).show();
                            if (!checkLotes()) {
                                escaparSubmit = true;
                            }
                        } else {
                            alert("Lote inválido para esta OS.");
                            escaparSubmit = true;
                        }

                    }
                }
            }

            if (escaparSubmit) {
                if (event.preventDefault) {
                    event.preventDefault();
                } else {
                    event.returnValue = false;
                }
            }
        }
        return true;
    }

    function checkLotes () {
        $.each(lotes, function (lote, status) {
            if (!status) {
                return false;
            }
        });
        return true;
    }

    function submitClick (event) {
        var codBarras = $("#etiquetaProduto").val();
        if (!checkLotes() || !codBarras) {
            if (!codBarras) {
                alert("O código de barras não foi informado");
            } else {
                alert("Existem lotes pendentes");
            }
            if (event.preventDefault) {
                event.preventDefault();
            } else {
                event.returnValue = false;
            }
        }
    }
</script>
<?php }?>