<script>
    function nextInput(event) {
        if (event.which == 13 || event.keyCode == 13) {
            if (document.getElementById('codigoBarras').value != "") {
                nivel = document.getElementById('nivel');
                if (nivel) {
                    nivel.focus();
                    if (event.preventDefault) {
                        event.preventDefault();
                    } else {
                        event.returnValue = false;
                    }
                }
            }
        }
        return true;
    }
</script>
<div class="row" >
    <form id="formulario" enctype="application/x-www-form-urlencoded" accept-charset="UTF-8" action="<?php echo $this->url(array('controller' => 'onda-ressuprimento', 'action' => 'validar-endereco')) ?>" method="post">
            <div class="table-responsive">
                <table class="gTable table-condensed" style="width: 100%">
                    <?php if ($this->temLote) { ?>
                        <tbody>
                        <tr>
                            <td colspan="2"><b><?php echo $this->dscProduto ?></b></td>
                        </tr>
                        <tr>
                            <td><B>Cod:</B> <div class="row"><?php echo $this->codProduto ?></div></td>
                            <td><B>Grade:</B> <div class="row"><?php echo $this->grade ?></div></td>
                        </tr>
                        <tr>
                            <td><B>Lote:</B></td>
                            <td><B>Qtd:</B></td>
                        </tr>
                        <?php foreach ($this->qtd as $lote => $grupo) { ?>
                            <tr style="border-bottom: thin solid">
                                <td style="font-size: 14px"><?php echo $lote; ?></td>
                                <td style="font-size: 14px">
                                    <?php foreach ($grupo as $item) { ?>
                                        <div class="row"><?php echo $item; ?></div>
                                    <?php } ?>
                                </td>
                            </tr>
                        <?php } ?>
                        <tr>
                            <td style="font-size: 145%"><B>Origem:</B> <?php echo $this->endPulmao ?></td>
                            <td style="font-size: 145%"><B>Destino:</B> <?php echo $this->endPicking ?></td>
                        </tr>
                        </tbody>
                    <?php } else { ?>
                    <tbody>
                        <tr>
                            <td colspan="3"><b><?php echo $this->dscProduto ?></b></td>
                        </tr>
                        <tr>
                            <td><B>Cod:</B> <div class="row"><?php echo $this->codProduto ?></div></td>
                            <td><B>Grade:</B> <div class="row"><?php echo $this->grade ?></div></td>
                            <td style="font-size: 12px"><B>Qtd:</B>

                                <?php

                                foreach ($this->qtd as $qtds) {
                                    if (count($this->qtd) == 1) {
                                        ?><div class="row"><?php echo $qtds; ?></div><?php
                                    } else {
                                        foreach ($qtds as $qtd) {
                                            ?><div class="row"><?php echo $qtd; ?></div><?php
                                        }
                                    }
                                } ?>
                            </td>
                            </tr>
                            <tr>
                                <td colspan="1" style="font-size: 145%"><B>Origem:</B> <?php echo $this->endPulmao ?></td>
                                <td colspan="2" style="font-size: 145%"><B>Destino:</B> <?php echo $this->endPicking ?></td>
                            </tr>
                        </tbody>
                    <?php } ?>
                    </table>

                </div>

                <div class="wrapper">
                    <div class="content-main"><label>Endereço:</label>
                        <input class="focus form-control" type="text" name="codigoBarras" id="codigoBarras" value="<?php echo $this->codigoBarras; ?>" onkeydown="nextInput(event)" /></div>
                    <div class="content-secondary"><label>Nível:</label>
                        <input class="form-control" type="text" name="nivel" id="nivel" value="" />
                    </div>
                </div>
                <br />
                <div class="row" >
                    <input type="submit" name="submit" class="btn gradientBtn" id="submit" value="Buscar" />
                </div>
                <div class="pull-right" >
                    <a class="btn finalizar" style="width: auto;" href="<?php echo $this->url(array('controller' => 'onda-ressuprimento', 'action' => 'divergencia', 'idOnda' => $this->idOnda)); ?> " onclick="return confirm('Confirma divergencia de estoque?')">Divergencia de Estoque</a>
                </div>
                <input type="hidden" name="idOnda" id="idOnda" value="<?php echo $this->idOnda ?>"/>
                <input type="hidden" name="idEnderecoPulmao" id="idEnderecoPulmao" value="<?php echo $this->idEnderecoPulmao ?>"/>

    <?php if ($this->produtos[0]->getCodProdutoVolume() != NULL) { ?>
                    <div id="quantidade-grid" class="grid">
                        <table class="table-condensed" style="width: 70%; margin-left: 5%; margin-right: 5%; margin-top: 3%; margin-bottom:  3%">
                            <tbody>
                                <tr class ="gTTitle">
                                    <td><b>Volumes</b></td>
                                    <td><b>Quantidade</b></td>
                                </tr>
                                <?php foreach ($this->produtos as $produto): $this->color = !($this->color); ?>
                                    <tr class = "<?php
                                    if (!$this->color) {
                                        echo 'gTResultSet gRowColor';
                                    } else {
                                        echo 'gTResultSet';
                                    }
                                    ?>">
                                        <td><?php
                                            /** @var \Doctrine\ORM\EntityManager $em */
                                            $em = \Zend_Registry::get('doctrine')->getEntityManager();

                                            if ($produto->getCodProdutoEmbalagem() == NULL) {
                                                $volumeEn = $em->getRepository("wms:Produto\Volume")->findOneBy(array('id' => $produto->getCodProdutoVolume()));
                                                echo $volumeEn->getDescricao();
                                            } else {
                                                $embalagemEn = $em->getRepository("wms:Produto\Embalagem")->findOneBy(array('id' => $produto->getCodProdutoEmbalagem()));
                                                echo $embalagemEn->getDescricao();
                                            }
                                            ?></td>
                                        <td><?php echo $produto->getQtd() ?></td>
                                    </tr>
        <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                    <div class = "gPager"></div>
    <?php } ?>


    </form>
</div>
